'use client';
import {useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import styles from './setup.module.css';
type Row={id:string;company_name?:string;document?:string;status?:string;name?:string;consumer_unit_number?:string;distributor?:string;city?:string;state?:string};
export default function RegistrationList({kind,customers,refresh,canEdit,onEdit}:{kind:'customers'|'consumer-units';customers:{id:string;company_name:string}[];refresh:number;canEdit:boolean;onEdit:(id:string,readOnly?:boolean)=>void}){
 const unit=kind==='consumer-units',title=unit?'Unidades cadastradas':'Clientes cadastrados';
 const [filters,setFilters]=useState<Record<string,string>>({}),[applied,setApplied]=useState<Record<string,string>>({}),[page,setPage]=useState(1),[size,setSize]=useState(10),[sort,setSort]=useState('asc'),[data,setData]=useState<{items:Row[];total:number}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');const params=new URLSearchParams({...applied,page:String(page),size:String(size),sort});apiRequest<{items:Row[];total:number}>('/api/v1/'+kind+'/search?'+params).then(result=>{if(cancelled)return;const last=Math.max(1,Math.ceil(result.total/size));if(page>last){setPage(last);return;}setData(result);}).catch(e=>{if(!cancelled){setData(null);setError(e instanceof Error?e.message:'Consulta indisponível.');}}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[kind,applied,page,size,sort,refresh,retry]);
 const field=(key:string,label:string)=><Input label={label} value={filters[key]??''} maxLength={150} onChange={e=>setFilters(f=>({...f,[key]:e.target.value}))}/>;
 const total=data?.total??0,pages=Math.max(1,Math.ceil(total/size));
 return <Card title={title}><form className={styles.search} onSubmit={e=>{e.preventDefault();setPage(1);setApplied({...filters});}}>
 {field('q',unit?'Pesquisar nome da unidade':'Pesquisar razão social ou nome fantasia')}
 <details className={styles.advanced}><summary>Filtros avançados</summary><div className={styles.filters}>
 {unit?<><label>Cliente vinculado<select className="ds-input" value={filters.customerId??''} onChange={e=>setFilters(f=>({...f,customerId:e.target.value}))}><option value="">Todos</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label>{field('code','Número da UC / instalação')}{field('distributor','Distribuidora')}{field('city','Cidade')}{field('state','Estado')}{field('tariffGroup','Grupo tarifário')}</>:<>{field('document','CPF / CNPJ')}{field('economicGroup','Grupo econômico')}<label>Situação<select className="ds-input" value={filters.status??''} onChange={e=>setFilters(f=>({...f,status:e.target.value}))}><option value="">Todas</option><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option></select></label></>}
 </div></details><div className={styles.actions}><Button type="submit" disabled={loading}>Pesquisar</Button><Button type="button" variant="secondary" disabled={loading} onClick={()=>{setFilters({});setApplied({});setPage(1);}}>Limpar filtros</Button></div>
 </form><div className={styles.pagination}><label>Registros por página<select className="ds-input" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[10,20,50].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>Ordenação<select className="ds-input" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="asc">Nome: A–Z</option><option value="desc">Nome: Z–A</option></select></label></div>
 {error?<><Alert variant="error">{error}</Alert><Button onClick={()=>setRetry(v=>v+1)}>Tentar novamente</Button></>:null}
 {loading?<p role="status">Consultando cadastros…</p>:data?<><p role="status">{total?'Exibindo '+((page-1)*size+1)+'–'+Math.min(page*size,total)+' de '+total+' registros.':'Nenhum registro encontrado para os filtros selecionados.'}</p><div className={styles.records}>{data.items.map(row=><article key={row.id} className="ds-card"><p>{unit?row.name:row.company_name} · {unit?row.consumer_unit_number:row.document}{!unit?' · '+(row.status==='ACTIVE'?'Ativo':row.status==='INACTIVE'?'Inativo':row.status??''):''}</p>{unit?<p>{[row.distributor,row.city,row.state].filter(Boolean).join(' · ')}</p>:null}<div className={styles.actions}>{canEdit?<Button variant="secondary" onClick={()=>onEdit(row.id)}>{unit?'Editar unidade':'Editar cliente / situação'}</Button>:null}<Button variant="secondary" onClick={()=>onEdit(row.id,true)}>Histórico</Button></div></article>)}</div></>:null}
 <nav className={styles.pagination} aria-label={'Paginação de '+(unit?'unidades':'clientes')}><Button variant="secondary" disabled={loading||!!error||page<=1} onClick={()=>setPage(p=>p-1)}>Anterior</Button><span>Página {page} de {pages}</span><Button variant="secondary" disabled={loading||!!error||page>=pages} onClick={()=>setPage(p=>p+1)}>Próxima</Button></nav>
 </Card>;
}
