'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {getUsers,OrganizationUser} from '@/app/lib/api/users';
import {useAuth} from '@/app/providers';
type Row={id:string;edit_version:number;status:string;free_market?:boolean|null;deactivated_user_ids?:string[];[key:string]:unknown};
type Edit={id:string;created_by_name?:string;created_at:string;reason:string;changes:Record<string,unknown>;before_record:Record<string,unknown>;after_record:Record<string,unknown>&{deactivated_user_ids?:string[]}};
const customerFields=[['company_name','Razão social'],['trade_name','Nome fantasia'],['document','CPF / CNPJ'],['contact_name','Contato'],['contact_email','E-mail'],['contact_phone','Telefone'],['economic_group','Grupo econômico']];
const unitFields=[['name','Nome da unidade'],['code','Número da UC / instalação'],['distributor','Distribuidora'],['address','Endereço'],['city','Cidade'],['state','Estado']];
const columns:Record<string,string>={code:'consumer_unit_number',freeMarket:'free_market',hasGd:'has_gd',hasBess:'has_bess'};
const labels:Record<string,string>=Object.fromEntries([...customerFields,...unitFields].map(([k,v])=>[columns[k]||k,v]));
Object.assign(labels,{status:'Situação',exclusive_user_ids:'Usuários exclusivos',deactivated_user_ids:'Usuários desativados',free_market:'Ambiente de contratação',has_gd:'Geração Distribuída (GD)',has_bess:'Armazenamento em baterias (BESS)'});
function shown(value:unknown,key:string){if(key.endsWith('_user_ids'))return Array.isArray(value)?value.length+' usuário(s)':'Nenhum';if(value==null||value==='')return 'Não informado';if(value==='ACTIVE')return 'Ativo';if(value==='INACTIVE')return 'Inativo';if(typeof value==='boolean')return value?'Sim':'Não';return String(value);}
export default function RegistrationEditor({kind,id,readOnly=false,onClose,onSaved}:{kind:'customers'|'consumer-units';id:string;readOnly?:boolean;onClose:()=>void;onSaved:(row:Row)=>void}){
 const {hasPermission}=useAuth();const [row,setRow]=useState<Row|null>(null),[history,setHistory]=useState<Edit[]>([]),[users,setUsers]=useState<OrganizationUser[]>([]),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('ACTIVE');const pending=useRef(false),attempt=useRef({body:'',id:''}),originalLinks=useRef<string[]>([]);
 const customer=kind==='customers',manageUsers=hasPermission('5f91d918-8def-4bc1-b6c7-37e1ff2d14e2')&&hasPermission('f60e405e-f120-4420-a563-691162504b15');const base='/api/v1/'+kind+'/'+encodeURIComponent(id);
 useEffect(()=>{let live=true;Promise.all([apiRequest<Row>(base),apiRequest<Edit[]>(base+'/edits'),customer&&!readOnly?apiRequest<string[]>(base+'/exclusive-users'):Promise.resolve([]),customer&&manageUsers&&!readOnly?getUsers():Promise.resolve([])]).then(([r,h,links,members])=>{if(live){setRow(r);setStatus(r.status||'ACTIVE');setHistory(h);setSelected(links);originalLinks.current=links;setUsers(members);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[base,customer,manageUsers,readOnly]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!row||pending.current)return;const f=new FormData(e.currentTarget),changes:Record<string,unknown>={};
 for(const [key] of customer?customerFields:unitFields){const value=String(f.get(key)||'').trim(),old=row[columns[key]||key]??'';if(value!==old)changes[key]=value;}
 if(customer&&status!==row.status)changes.status=status;
 if(!customer){for(const key of ['freeMarket','hasGd','hasBess']){const v=String(f.get(key)||''),value=v===''?null:v==='true';if(value!==(row[columns[key]]??null))changes[key]=value;}}
 if(customer&&manageUsers){const previous=originalLinks.current;if(JSON.stringify(previous)!==JSON.stringify([...selected].sort()))changes.exclusive_user_ids=[...selected].sort();}
 if(!Object.keys(changes).length){setError('Nenhuma alteração identificada.');return;}
 const payload={changes,reason:String(f.get('reason')||'').trim(),expectedVersion:row.edit_version};const signature=JSON.stringify(payload);if(attempt.current.body!==signature)attempt.current={body:signature,id:crypto.randomUUID()};
 pending.current=true;setBusy(true);setError('');try{const saved=await apiRequest<Row>(base,{method:'PUT',body:{...payload,requestId:attempt.current.id}});onSaved(saved);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{pending.current=false;setBusy(false);}
 }
 return <Card title={readOnly?'Histórico de alterações':customer?'Editar cliente':'Editar unidade'}><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Fechar</Button>{error?<Alert variant="error">{error}</Alert>:null}{!row?<p>Carregando cadastro...</p>:<>{!readOnly?<form onSubmit={save} className="organizations-create__form"><fieldset disabled={busy} style={{border:0,display:'grid',gap:16}}>
 {(customer?customerFields:unitFields).map(([key,label])=><Input key={key} name={key} label={label} defaultValue={String(row[columns[key]||key]??'')} required={['company_name','document','name','code','distributor'].includes(key)} type={key==='contact_email'?'email':'text'} maxLength={key==='address'?1000:key==='contact_phone'||key==='code'?20:key==='distributor'||key==='state'?50:255}/>)}
 {customer?<><label>Situação<select className="ds-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option>{!['ACTIVE','INACTIVE'].includes(row.status)?<option value={row.status}>{row.status}</option>:null}</select></label>
 <p>Desativar preserva os registros e desativa somente as contas explicitamente exclusivas deste cliente. As vagas desses usuários ficam disponíveis na licença da organização. Reativar o cliente não reativa contas automaticamente.</p>
 {manageUsers?<fieldset><legend>Usuários exclusivos deste cliente</legend><p>Marque somente usuários que atendem exclusivamente este cliente. Usuários compartilhados e do backoffice devem ficar desmarcados. Este vínculo controla a desativação; não altera permissões de acesso.</p>{users.filter(u=>u.role.name==='consulta'&&u.affiliationType==='external'||selected.includes(u.userId)).map(u=><label key={u.userId} style={{display:'block'}}><input type="checkbox" checked={selected.includes(u.userId)} onChange={e=>setSelected(old=>e.target.checked?[...old,u.userId]:old.filter(x=>x!==u.userId))}/>{u.name||u.email} · {u.membershipStatus==='active'?'Ativo':'Inativo'}</label>)}{!users.some(u=>u.role.name==='consulta'&&u.affiliationType==='external')?<p>Nenhum usuário externo de consulta elegível. Cadastre ou ajuste o usuário no módulo Usuários.</p>:null}</fieldset>:<p>{selected.length} usuário(s) exclusivo(s) vinculado(s). A alteração dos vínculos exige permissão para gerenciar usuários.</p>}
 </>:<><label>Unidade no Mercado Livre<select className="ds-input" name="freeMarket" defaultValue={row.free_market==null?'':String(row.free_market)}><option value="">Não informado</option><option value="true">Sim — ACL</option><option value="false">Não — ACR</option></select></label><p>O ambiente ACL/ACR, a GD e o BESS são independentes e podem ser combinados por unidade.</p>{[['hasGd','Geração Distribuída (GD)'],['hasBess','Armazenamento em baterias (BESS)']].map(([key,label])=><label key={key}>{label}<select className="ds-input" name={key} defaultValue={row[columns[key]]==null?'':String(row[columns[key]])}><option value="">Não informado</option><option value="true">Sim</option><option value="false">Não</option></select></label>)}</>}
 <label>Justificativa obrigatória<textarea className="ds-input" name="reason" minLength={3} maxLength={1000} required/></label><p>A alteração será registrada com seu nome, data e valores anteriores e novos. Documentos e resultados anteriores permanecem preservados.</p><Button type="submit">{busy?'Salvando...':'Salvar alteração auditada'}</Button></fieldset></form>:null}
 <h3>Histórico auditado</h3>{history.length?history.map(h=><article key={h.id} className="ds-card"><p><strong>{h.created_by_name||'Autor não identificado'}</strong> · {new Date(h.created_at).toLocaleString('pt-BR')}</p><p>Justificativa: {h.reason}</p><dl>{Object.keys(h.changes).map(key=><div key={key}><dt>{labels[key]||key.replace(/_/g,' ')}</dt><dd>{shown(h.before_record[key],key)} → {shown(h.after_record[key],key)}</dd></div>)}</dl>{h.after_record.deactivated_user_ids?.length?<p>{h.after_record.deactivated_user_ids.length} usuário(s) exclusivo(s) desativado(s); vagas liberadas.</p>:null}</article>):<p>Nenhuma alteração registrada nesta etapa de auditoria.</p>}</>}</Card>;
}
