import {PortalLicenseService} from './portal-license.service';
import {PortalLicenseGuard} from './portal-license.guard';
import {portalRouteModule} from './portal-route-module';
import {PortalLicenseDto,ClientAdditionDto} from './portal-license.dto';
import {validateWriteDto} from '../../common/validation/validate-write-dto';
import {PERMISSIONS as P} from '../../common/constants/permissions';
const id='11111111-1111-4111-8111-111111111111';
function fixture(flag='true'){
 const client={rpc:jest.fn(async()=>({data:{enabled:true,organizationId:'org',customerId:id,modules:['reports','bot']},error:null})),from:jest.fn()};
 const service=new PortalLicenseService({getClient:()=>client} as any,{get:()=>flag} as any);
 const tenant:any={organizationId:'org',userId:'actor',roleId:'role',role:'consulta',scope:'organization',permissions:[P.DOCUMENTS_REPORTS_VIEW]};
 return {client,service,tenant};
}
describe('Isolated portal license policy',()=>{
 it.each([undefined,'false','TRUE','1'])('is disabled by default or nonliteral flag %s',async value=>{const f=fixture();f.service=new PortalLicenseService({getClient:()=>f.client} as any,{get:()=>value} as any);expect(await f.service.client(f.tenant)).toEqual({enabled:false});expect(f.client.rpc).not.toHaveBeenCalled();});
 it('derives actor, role and organization from authenticated context',async()=>{const f=fixture();await f.service.client(f.tenant,'reports');expect(f.client.rpc).toHaveBeenCalledWith('client_portal_entitlement',{p_org:'org',p_actor:'actor',p_role:'role',p_module:'reports'});});
 it.each([{role:'gestor'},{accessMode:'platform_operation'},{userId:''},{roleId:''},{organizationId:''}])('rejects forged or backoffice client scope %p',async patch=>{const f=fixture();await expect(f.service.client({...f.tenant,...patch})).rejects.toMatchObject({status:403});expect(f.client.rpc).not.toHaveBeenCalled();});
 it('cannot substitute a module not present in the concession',async()=>{const f=fixture();await expect(f.service.client(f.tenant,'forecasts')).rejects.toMatchObject({status:403});});
 it('does not forward unrelated payload when organization policy is disabled',async()=>{const f=fixture();f.client.rpc.mockResolvedValue({data:{enabled:false,customerId:'foreign',privateData:'not part of compatibility'},error:null} as any);expect(await f.service.client(f.tenant,'reports')).toEqual({enabled:false});});
 it('fails closed on missing/foreign/expired entitlement RPC response',async()=>{for(const data of [null,{}, {enabled:true,modules:['reports']}]){const f=fixture();f.client.rpc.mockResolvedValue({data,error:null} as any);await expect(f.service.client(f.tenant,'reports')).rejects.toThrow();}});
 it.each(['42501','P3410','P3411','P3412','P3413'])('does not convert failed authorization/quota into a positive response %s',async code=>{const f=fixture();f.client.rpc.mockResolvedValue({data:null,error:{code}} as any);await expect(f.service.client(f.tenant,'reports')).rejects.toThrow();});
 it('does not query unavailable migration tables when rollout is globally disabled',async()=>{const f=fixture('false');const t={...f.tenant,role:'admin_org',permissions:[P.ORGANIZATION_LICENSES_VIEW]};expect(await f.service.list(t)).toMatchObject({available:false,enabled:false});expect(f.client.from).not.toHaveBeenCalled();});
 it.each([{role:'consulta'},{scope:'global'},{permissions:[]}])('blocks the client/global actor from management %p',async patch=>{const f=fixture();const t={...f.tenant,role:'admin_org',permissions:[P.ORGANIZATION_LICENSES_VIEW],...patch};await expect(f.service.list(t)).rejects.toMatchObject({status:403});expect(f.client.from).not.toHaveBeenCalled();});
 it('writes require platform operation and license permission independently',async()=>{const f=fixture();const input:any={customerId:id};for(const t of [{...f.tenant,role:'gestor',permissions:[P.ORGANIZATION_LICENSES_UPDATE]},{...f.tenant,role:'admin_org',accessMode:'platform_operation',permissions:[]}])await expect(f.service.save(t,input)).rejects.toMatchObject({status:403});expect(f.client.rpc).not.toHaveBeenCalled();});
 it('cannot enable the feature or save a license through disabled rollout',async()=>{const f=fixture('false');const t:any={...f.tenant,role:'admin_org',accessMode:'platform_operation',permissions:[P.ORGANIZATION_LICENSES_UPDATE]};await expect(f.service.save(t,{customerId:id} as any)).rejects.toMatchObject({status:404});await expect(f.service.policy(t,{enabled:true} as any)).rejects.toMatchObject({status:404});expect(f.client.rpc).not.toHaveBeenCalled();});
 it('requires server-confirmed scope after license writes',async()=>{const f=fixture();const t:any={...f.tenant,role:'admin_org',accessMode:'platform_operation',permissions:[P.ORGANIZATION_LICENSES_UPDATE]};f.client.rpc.mockResolvedValue({data:{id,organization_id:'foreign',customer_id:id},error:null} as any);await expect(f.service.save(t,{customerId:id} as any)).rejects.toMatchObject({status:500});});
 it('strict DTOs reject client-supplied tenant, permission, price and fractional seats',async()=>{const valid={customerId:id,revision:0,status:'ACTIVE',starts:'2026-10-09',ends:'2027-10-09',modules:['reports'],maxUsers:1,maxUnits:2,reason:'Contract reference'};await expect(validateWriteDto(PortalLicenseDto,valid)).resolves.toMatchObject(valid);for(const patch of [{organizationId:'other'},{permissions:['admin']},{price:0},{maxUsers:0.5},{modules:['reports','reports']},{modules:['backoffice']},{ends:'2027-13-01'}])await expect(validateWriteDto(PortalLicenseDto,{...valid,...patch})).rejects.toThrow();await expect(validateWriteDto(ClientAdditionDto,{id,revision:0,slots:0,starts:'2026-10-09',ends:'2027-10-09',status:'ACTIVE',reference:'approved',reason:'approved'})).rejects.toThrow();});
});
describe('Explicit licensed portal routes',()=>{
 it.each([['/api/v1/portal/financial','GET','reports'],['/portal/energy-forecasts','GET','forecasts'],['/portal/energy-prices','GET','energy_prices'],['/portal/acl-admissions','GET','acl'],['/bot-energy/reports/client','POST','bot'],['/bot-energy/reports/client/units','GET','bot'],['/portal/evidence/'+id+'/upload','POST','documents'],['/portal/evidence/'+id+'/files/'+id,'GET','documents']])('maps the existing client operation %s', (path,method,module)=>{expect(portalRouteModule(path,method)).toBe(module);});
 it.each([['/portal/preview','GET'],['/backoffice/reports','GET'],['/portal/financial','POST'],['/portal/evidence/not-an-id','GET'],['/portal/evidence/'+id,'DELETE'],['/portal/evidence/'+id+'/transition','POST'],['/bot-energy/reports/backoffice','POST']])('does not open a backoffice/write/unknown path %s',(path,method)=>{expect(portalRouteModule(path,method)).toBeNull();});
 it('guards data before the handler and skips only unchanged backoffice/public/default-disabled scope',async()=>{const f=fixture();const guard=new PortalLicenseGuard(f.service);const request:any={tenantContext:f.tenant,path:'/api/v1/portal/financial',method:'GET'};const context:any={switchToHttp:()=>({getRequest:()=>request})};await guard.canActivate(context);expect(f.client.rpc).toHaveBeenCalledTimes(1);request.tenantContext={...f.tenant,role:'gestor'};await guard.canActivate(context);expect(f.client.rpc).toHaveBeenCalledTimes(1);});
});
describe('Organization-scoped portal license presentation',()=>{
 function listFixture(rows:any[]){
  const f=fixture();const filters:any[]=[];
  f.client.from.mockImplementation((table:string)=>{const result={data:table==='client_portal_licenses'?rows:table==='client_portal_policies'?{enabled:false,revision:0}:[],error:null};const query:any={select:jest.fn(()=>query),eq:jest.fn((key,value)=>{filters.push([table,key,value]);return query;}),order:jest.fn(()=>query),limit:jest.fn(()=>query),maybeSingle:jest.fn(async()=>result),then:(resolve:any)=>Promise.resolve(result).then(resolve)};return query;});
  return {...f,filters,manager:{...f.tenant,role:'admin_org',permissions:[P.ORGANIZATION_LICENSES_VIEW]}};
 }
 it('returns company labels only after matching both license and customer organization',async()=>{const f=listFixture([{organization_id:'org',customers:{organization_id:'org',company_name:'Company'}}]);const r=await f.service.list(f.manager);expect(r.licenses[0].customers.company_name).toBe('Company');expect(f.filters).toContainEqual(['client_portal_licenses','organization_id','org']);expect(f.filters).toContainEqual(['client_portal_licenses','customers.organization_id','org']);});
 it('rejects a foreign customer relation without returning its name',async()=>{const f=listFixture([{organization_id:'org',customers:{organization_id:'foreign',company_name:'Private company'}}]);await expect(f.service.list(f.manager)).rejects.toMatchObject({status:500});});
 it('never returns a partial license list at the management boundary',async()=>{const f=listFixture(Array.from({length:201},()=>({organization_id:'org',customers:{organization_id:'org'}})));await expect(f.service.list(f.manager)).rejects.toMatchObject({status:400});});
});
