import {PlatformWorkflowsService} from './platform-workflows.service';
import {workflowQuery} from './platform-workflows.controller';
describe('platform workflows boundary',()=>{
 const actor={userId:'11111111-1111-4111-8111-111111111111',ip:'127.0.0.1',agent:'test'};
 let rpc:jest.Mock,storage:any,service:PlatformWorkflowsService;
 beforeEach(()=>{rpc=jest.fn().mockResolvedValue({data:{rows:[]},error:null});storage={upload:jest.fn().mockResolvedValue({error:null}),createSignedUrl:jest.fn().mockResolvedValue({data:{signedUrl:'https://example.test/signed'},error:null})};service=new PlatformWorkflowsService({getClient:()=>({rpc,storage:{from:()=>storage}})} as any);});
 it('rejects unknown filters and arrays',()=>{for(const query of [{page:['0']},{id:'invalid'},{page:'1001'},{forged:'tenant'}])expect(()=>workflowQuery(query)).toThrow();expect(workflowQuery({page:'0'})).toEqual({page:0,id:undefined,filter:{}});});
 it('uses authenticated actor rather than body actor',async()=>{await service.save(actor,'support',actor.userId,{revision:1,body:{reason:'Verified investigation'}});expect(rpc).toHaveBeenCalledWith('save_platform_support_case',expect.objectContaining({p_actor:actor.userId,p_revision:1,p_ip:actor.ip}));await expect(service.save(actor,'support',actor.userId,{revision:1,body:{},actor:'forged'})).rejects.toMatchObject({status:400});});
 it('rejects unsafe revisions and extra fields',async()=>{for(const revision of [-1,1.5,1000001,'1'])await expect(service.save(actor,'finance',actor.userId,{revision,action:'PROPOSE',body:{}})).rejects.toMatchObject({status:400});expect(rpc).not.toHaveBeenCalled();});
 it('maps role, stale and unavailable results without exposing SQL',async()=>{for(const [code,status] of [['42501',403],['40001',409],['23505',409],['22023',400],['XX000',503]]){rpc.mockResolvedValueOnce({error:{code,message:'private SQL'},data:null});await expect(service.read(actor,'finance')).rejects.toMatchObject({status});}});
 it('fails closed on provider/database transport outage',async()=>{rpc.mockRejectedValue(new Error('private secret'));await expect(service.read(actor,'support')).rejects.toMatchObject({status:503});});
 it('authorizes before uploading private evidence',async()=>{rpc.mockResolvedValue({error:{code:'42501'},data:null});await expect(service.upload(actor)).rejects.toMatchObject({status:403});expect(storage.upload).not.toHaveBeenCalled();});
 it('hashes the actual PDF bytes and uses a private immutable object',async()=>{const buffer=Buffer.from('%PDF-1.4\nbody\n%%EOF');rpc.mockResolvedValueOnce({data:{rows:[]},error:null}).mockResolvedValueOnce({data:{},error:null}).mockResolvedValueOnce({data:{id:'verified'},error:null});await service.upload(actor,{buffer,originalname:'invoice.pdf',mimetype:'application/pdf',size:buffer.length});expect(storage.upload).toHaveBeenCalledWith(expect.stringMatching(/\/evidence.pdf$/),buffer,{contentType:'application/pdf',upsert:false});expect(rpc).toHaveBeenLastCalledWith('register_platform_financial_evidence',expect.objectContaining({p_actor:actor.userId,p_hash:expect.stringMatching(/^[a-f0-9]{64}$/),p_bytes:buffer.length}));});
 it('does not sign files on revoked access',async()=>{rpc.mockResolvedValue({error:{code:'42501'},data:null});await expect(service.download(actor,actor.userId)).rejects.toMatchObject({status:403});expect(storage.createSignedUrl).not.toHaveBeenCalled();});
 it('signs only the server resolved private path for 60 seconds',async()=>{rpc.mockResolvedValue({data:{path:'verified/evidence.pdf',filename:'invoice.pdf'},error:null});expect((await service.download(actor,actor.userId)).expiresIn).toBe(60);expect(storage.createSignedUrl).toHaveBeenCalledWith('verified/evidence.pdf',60,{download:'invoice.pdf'});});
});
