import {ReportPreparationWorker} from './report-preparation.worker';
describe('durable report preparation',()=>{
 const config={name:'Mensal',customerId:'00000000-0000-4000-8000-000000000010',unitId:'00000000-0000-4000-8000-000000000011',frequency:'MONTHLY',days:[5],hour:9,monthlyLimit:1,kinds:['OPERATIONAL'],formats:['pdf'],channels:['email'],contactIds:['00000000-0000-4000-8000-000000000012']};
 const claim={job:{id:'00000000-0000-4000-8000-000000000020',lease_id:'00000000-0000-4000-8000-000000000021',organization_id:'o1',owner_id:'actor',config,month:'2026-09-01',requests:{OPERATIONAL:'00000000-0000-4000-8000-000000000022'}},context:{organizationId:'o1',userId:'actor'}};
 it('uses a persistent request and previous complete month with the existing report engine',async()=>{const rpc=jest.fn().mockResolvedValueOnce({data:claim}).mockResolvedValue({}),create=jest.fn().mockResolvedValue({id:'report'});await new ReportPreparationWorker({getClient:()=>({rpc})} as any,{create} as any).runOnce();expect(create).toHaveBeenCalledWith(expect.objectContaining({from:'2026-09',to:'2026-09',requestId:claim.job.requests.OPERATIONAL}),claim.context);expect(rpc).toHaveBeenLastCalledWith('finish_report_preparation',expect.objectContaining({p_reports:[{id:'report',kind:'OPERATIONAL'}],p_reason:null}));});
 it('never generates from a cross-organization claim',async()=>{const create=jest.fn(),rpc=jest.fn().mockResolvedValue({data:{...claim,context:{organizationId:'o2',userId:'actor'}}});await expect(new ReportPreparationWorker({getClient:()=>({rpc})} as any,{create} as any).runOnce()).rejects.toThrow('CLAIM_INVALID');expect(create).not.toHaveBeenCalled();});
 it('keeps missing publications explicit and performs no transport call',async()=>{const rpc=jest.fn().mockResolvedValueOnce({data:claim}).mockResolvedValue({}),create=jest.fn().mockRejectedValue(Error('Não há resultados publicados completos'));await new ReportPreparationWorker({getClient:()=>({rpc})} as any,{create} as any).runOnce();expect(rpc).toHaveBeenLastCalledWith('finish_report_preparation',expect.objectContaining({p_reason:'WAITING_PUBLICATION'}));});
 it('does not overlap preparation while a lease is being processed',async()=>{let resolve:any;const rpc=jest.fn().mockImplementation(()=>new Promise(r=>resolve=r));const worker=new ReportPreparationWorker({getClient:()=>({rpc})} as any,{} as any);const run=worker.runOnce();await worker.runOnce();expect(rpc).toHaveBeenCalledTimes(1);resolve({data:null});await run;});
});
