import ExcelJS from 'exceljs';
import {reportPdf,reportExcel,money} from './report.render';
const row:any={id:'report',payload_hash:'a'.repeat(64),body:{kind:'OPERATIONAL',formatVersion:'energy-report-1.0',generatedAt:'2026-10-06T12:00:00Z',header:{organizationName:'Expert Energy',customerName:'=HYPERLINK("https://example.invalid")',unitName:'Unidade',unitCode:'001',distributor:'CPFL',address:'Rua',city:'Ribeirão Preto',state:'SP'},period:{from:'2026-08',to:'2026-09'},totals:{acr:'1000.00',aclAfterFees:'850.00',totalFees:'50.00',savingsAfterFees:'150.00',savingsPercent:'15.00'},months:[{month:'2026-08',totals:{acr:'1000.00',aclAfterFees:'850.00',savingsAfterFees:'150.00'},cumulative:'150.00',widths:{acr:'100.00',acl:'85.00'}},{month:'2026-09',totals:null,cumulative:null,widths:null}],coverage:{publishedMonths:1,requestedMonths:2,missingMonths:['2026-09']},invoices:[{month:'2026-08',version:2,consumptionKwh:'12345.6789',scenarios:null,findings:[],reservationCount:1}],composition:null,publications:[{month:'2026-08',version:2,id:'group',payloadHash:'b'.repeat(64),publishedAt:'2026-09-01T12:00:00Z'}],unavailable:['ROI indisponível'],events:[],disclosure:'Resultados publicados',context:'Dados sintéticos de teste'}};
describe('private report output formats',()=>{
 it('formats large exact currency without floating point rounding',()=>expect(money('123456789012345.67')).toBe('R$ 123.456.789.012.345,67'));
 it('keeps amounts above Excel 15 significant digits as exact text',async()=>{const large={...row,body:{...row.body,totals:{...row.body.totals,acr:'123456789012345.67'}}},w=new ExcelJS.Workbook();await w.xlsx.load(await reportExcel(large) as any);expect(w.getWorksheet('Resumo')!.getCell('B17').value).toBe('123456789012345.67');});
 it('generates three PDF pages without extra footer pages',async()=>{const pdf=await reportPdf(row);expect(pdf.subarray(0,4).toString()).toBe('%PDF');expect(pdf.toString('latin1').match(/\/Type \/Page\b/g)).toHaveLength(3);});
 it('writes native XLSX with exact consumption, absent-month text, source hash and literal untrusted strings',async()=>{const buffer=await reportExcel(row),w=new ExcelJS.Workbook();await w.xlsx.load(buffer as any);expect(w.worksheets.map(s=>s.name)).toEqual(['Resumo','Evolução','Consumo e custos','Eventos e alertas','Fontes exatas']);expect(w.getWorksheet('Consumo e custos')!.getCell('B2').value).toBe('12345.6789');expect(w.getWorksheet('Evolução')!.getCell('B3').value).toBe('Indisponível');expect(w.getWorksheet('Fontes exatas')!.getCell('D2').value).toBe('b'.repeat(64));const name=w.getWorksheet('Resumo')!.getCell('B4');expect(typeof name.value).toBe('string');expect(name.value).toBe(row.body.header.customerName);for(const s of w.worksheets)s.eachRow(r=>r.eachCell(c=>expect(c.type).not.toBe(ExcelJS.ValueType.Formula)));});
});
