import {ReportDeliveryWorker} from './report-delivery.worker';
import {sendReportDelivery} from './report-delivery';
jest.mock('./report.render',()=>({reportPdf:jest.fn().mockResolvedValue(Buffer.from('pdf')),reportExcel:jest.fn().mockResolvedValue(Buffer.from('excel'))}));
jest.mock('./report-delivery',()=>({reportProviderReady:()=>true,sendReportDelivery:jest.fn().mockResolvedValue({state:'ACCEPTED',providerId:'receipt'})}));
describe('report delivery authorization',()=>{
 const old={...process.env};beforeEach(()=>{process.env.REPORTS_DELIVERY_ENABLED='true';jest.clearAllMocks();});afterEach(()=>{process.env={...old};});
 const claim={delivery:{id:'d1',job_id:'j1',organization_id:'o1',channel:'email',destination:'selected@example.invalid',lease_id:'lease'},job:{id:'j1',organization_id:'o1',owner_id:'actor',month:'2026-09-01',config:{customerId:'c1',unitId:'u1',formats:['pdf']},report_ids:[{id:'r1',kind:'OPERATIONAL'}]},context:{organizationId:'o1',userId:'actor'}};
 it('does not send without explicit platform activation',async()=>{delete process.env.REPORTS_DELIVERY_ENABLED;const rpc=jest.fn();await new ReportDeliveryWorker({getClient:()=>({rpc})} as any,{} as any).runOnce();expect(rpc).not.toHaveBeenCalled();expect(sendReportDelivery).not.toHaveBeenCalled();});
 it('rejects a cross-tenant claim before loading documents or sending',async()=>{const rpc=jest.fn().mockResolvedValue({data:{...claim,context:{organizationId:'o2',userId:'actor'}}}),one=jest.fn();await expect(new ReportDeliveryWorker({getClient:()=>({rpc})} as any,{one} as any).runOnce()).rejects.toThrow('DELIVERY_SCOPE_INVALID');expect(one).not.toHaveBeenCalled();expect(sendReportDelivery).not.toHaveBeenCalled();});
 it('revalidates before network start and does not send after revocation',async()=>{const rpc=jest.fn().mockResolvedValueOnce({data:claim}).mockResolvedValueOnce({data:false}),one=jest.fn().mockResolvedValue({customer_id:'c1',consumer_unit_id:'u1'});await new ReportDeliveryWorker({getClient:()=>({rpc})} as any,{one} as any).runOnce();expect(rpc).toHaveBeenLastCalledWith('start_report_delivery',{p_org:'o1',p_id:'d1',p_lease:'lease'});expect(sendReportDelivery).not.toHaveBeenCalled();});
 it('preserves the provider receipt against the leased tenant delivery',async()=>{const rpc=jest.fn().mockResolvedValueOnce({data:claim}).mockResolvedValueOnce({data:true}).mockResolvedValue({}),one=jest.fn().mockResolvedValue({customer_id:'c1',consumer_unit_id:'u1'});await new ReportDeliveryWorker({getClient:()=>({rpc})} as any,{one} as any).runOnce();expect(sendReportDelivery).toHaveBeenCalledTimes(1);expect(rpc).toHaveBeenLastCalledWith('finish_report_delivery',expect.objectContaining({p_org:'o1',p_id:'d1',p_state:'ACCEPTED',p_provider_id:'receipt'}));});
});
