import {reportProviderReady,sendReportDelivery} from './report-delivery';
describe('report delivery transport',()=>{
 const old={...process.env};afterEach(()=>{process.env={...old};});
 const input={id:'delivery-id',channel:'email',destination:'client@example.invalid',attachments:[{filename:'EnergyOS.pdf',content:'cGRm'}]};
 it('blocks absent providers and unapproved templates',async()=>{delete process.env.RESEND_API_KEY;delete process.env.WHATSAPP_REPORT_TEMPLATE_APPROVED;const transport=jest.fn();expect((await sendReportDelivery(input,transport)).state).toBe('FAILED');expect(transport).not.toHaveBeenCalled();expect(reportProviderReady('whatsapp')).toBe(false);expect(reportProviderReady('sms')).toBe(false);});
 it('sends private attachments to one selected email with a durable idempotency key',async()=>{Object.assign(process.env,{RESEND_API_KEY:'synthetic',REPORTS_EMAIL_FROM:'EnergyOS <reports@example.invalid>'});const transport=jest.fn().mockResolvedValue({ok:true,json:async()=>({id:'receipt'})});expect(await sendReportDelivery(input,transport)).toEqual({state:'ACCEPTED',providerId:'receipt'});const call=transport.mock.calls[0];expect(call[0]).toBe('https://api.resend.com/emails');expect(call[1].headers['Idempotency-Key']).toBe('report-delivery/delivery-id');expect(JSON.parse(call[1].body).to).toEqual([input.destination]);expect(JSON.parse(call[1].body).attachments).toEqual(input.attachments);});
 it('uses a separate report template and shares no financial values or document links on WhatsApp',async()=>{Object.assign(process.env,{WHATSAPP_ACCESS_TOKEN:'synthetic',WHATSAPP_PHONE_NUMBER_ID:'123',WHATSAPP_GRAPH_VERSION:'v25.0',WHATSAPP_REPORT_TEMPLATE:'energyos_relatorio_disponivel',WHATSAPP_REPORT_TEMPLATE_APPROVED:'true'});const transport=jest.fn().mockResolvedValue({ok:true,json:async()=>({messages:[{id:'wamid.receipt'}]})});expect((await sendReportDelivery({...input,channel:'whatsapp',destination:'+5516999999999'},transport)).state).toBe('ACCEPTED');expect(JSON.parse(transport.mock.calls[0][1].body)).toEqual({messaging_product:'whatsapp',to:'5516999999999',type:'template',template:{name:'energyos_relatorio_disponivel',language:{code:'pt_BR'}}});});
 it('does not retry ambiguous responses and rejects incomplete receipts',async()=>{Object.assign(process.env,{RESEND_API_KEY:'synthetic',REPORTS_EMAIL_FROM:'reports@example.invalid'});const transport=jest.fn().mockRejectedValue(Error('network'));expect((await sendReportDelivery(input,transport)).state).toBe('UNKNOWN');expect(transport).toHaveBeenCalledTimes(1);transport.mockResolvedValue({ok:true,json:async()=>({})});expect((await sendReportDelivery(input,transport)).reason).toBe('MISSING_RECEIPT');transport.mockResolvedValue({ok:false,status:400});expect((await sendReportDelivery(input,transport)).state).toBe('FAILED');});
 it('blocks malformed recipients and oversize attachments before network access',async()=>{Object.assign(process.env,{RESEND_API_KEY:'synthetic',REPORTS_EMAIL_FROM:'reports@example.invalid'});const transport=jest.fn();expect((await sendReportDelivery({...input,destination:'bad\r\nemail'},transport)).reason).toBe('INVALID_DESTINATION');expect((await sendReportDelivery({...input,attachments:[]},transport)).reason).toBe('ATTACHMENT_LIMIT');expect(transport).not.toHaveBeenCalled();});
});
