import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';

export function money(v:unknown){if(typeof v!=='string'||!/^\-?\d+\.\d{2}$/.test(v))return 'Indisponível';const [a,b]=v.split('.');return 'R$ '+a.replace(/\B(?=(\d{3})+(?!\d))/g,'.')+','+b;}
const titles:Record<string,string>={OPERATIONAL:'Relatório operacional',EXECUTIVE:'Relatório executivo'};
const colors=['#2367C9','#14A085','#7858BC','#DF9A29','#6D839B'];
const when=(v:string)=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});
// Geometry uses backend chart widths only; published monetary amounts are never recalculated here.
export async function reportPdf(row:any):Promise<Buffer>{
 const b=row.body,h=b.header,doc=new PDFDocument({size:'A4',margin:40,bufferPages:true,info:{Title:`EnergyOS · ${titles[b.kind]}`,Author:'Expert Energy',Subject:'Resultados publicados da unidade'}});
 const chunks:Buffer[]=[];const done=new Promise<Buffer>((resolve,reject)=>{doc.on('data',c=>chunks.push(c));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);});
 let y=40;
 const line=(s:string,size=9,color='#3A5067')=>{doc.font('Helvetica').fontSize(size).fillColor(color);const height=doc.heightOfString(s,{width:515});if(y+height>760){doc.addPage();y=42;}doc.text(s,40,y,{width:515});y+=height+8;};
 const section=(s:string)=>{if(y>720){doc.addPage();y=42;}y+=8;line(s,13,'#142D46');};
 const page=(title:string)=>{doc.addPage();y=42;line('EnergyOS · '+title,18,'#142D46');line(h.customerName+' · '+h.unitName,10);};
 doc.rect(0,0,595,118).fill('#142D46');doc.font('Helvetica-Bold').fontSize(12).fillColor('#5AD6BF').text('ENERGYOS  /  EXPERT ENERGY',40,29);doc.fontSize(24).fillColor('#FFFFFF').text(titles[b.kind],40,51);doc.font('Helvetica').fontSize(10).text(`${b.period.from} a ${b.period.to}  ·  Unidade ${h.unitCode}`,40,88,{width:510});
 y=136;line(h.customerName,16,'#142D46');line(`${h.unitName} · ${h.distributor||'Distribuidora não informada'}`);line([h.address,h.city,h.state].filter(Boolean).join(' · '));line(`${h.organizationName} · ${h.contactName||'Contato não informado'}${h.contactEmail?' · '+h.contactEmail:''}`);
 line(`Versão ${b.formatVersion} · Emitido em ${when(b.generatedAt)} · Publicações: ${b.publications.length}`,8);
 line(b.context,9);
 if(y>570){doc.addPage();y=42;}
 const cardY=y+8,cardW=248,cardH=69;
 const cards=[['Custo ACR',money(b.totals.acr)],['ACL com honorários',money(b.totals.aclAfterFees)],['Economia após honorários',money(b.totals.savingsAfterFees)],['Score de economia publicado',b.totals.savingsPercent===null?'Indisponível':b.totals.savingsPercent.replace('.',',')+'%']];
 cards.forEach(([label,value],i)=>{const x=40+(i%2)*267,cy=cardY+Math.floor(i/2)*79;doc.roundedRect(x,cy,cardW,cardH,9).fill('#EDF4F8');doc.circle(x+18,cy+18,7).fill(i===2?'#14A085':'#2367C9');doc.moveTo(x+15,cy+18).lineTo(x+18,cy+21).lineTo(x+22,cy+15).lineWidth(1.3).stroke('#FFFFFF');doc.font('Helvetica').fontSize(9).fillColor('#3A5067').text(label,x+34,cy+13,{width:cardW-44});doc.font('Helvetica-Bold').fontSize(value.length>26?13:17).fillColor('#142D46').text(value,x+15,cy+37,{width:cardW-25});});
 y=cardY+162;section('Evolução dos custos e da economia');line('Azul: custo ACR · Verde: ACL com honorários. Valores publicados na mesma escala.',8);
 for(const m of b.months){if(y>715){doc.addPage();y=42;}line(`${m.month}  ·  ${m.totals?'Economia '+money(m.totals.savingsAfterFees):'Sem publicação; não representa zero.'}`,9);if(m.totals&&m.widths){const maxW=240;doc.rect(40,y,maxW*Number(m.widths.acr)/100,7).fill(colors[0]);doc.rect(40,y+11,maxW*Number(m.widths.acl)/100,7).fill(colors[1]);doc.fontSize(8).fillColor('#3A5067').text('ACR '+money(m.totals.acr)+'  /  ACL '+money(m.totals.aclAfterFees),294,y,{width:260});y+=28;}}
 line(`Cobertura: ${b.coverage.publishedMonths}/${b.coverage.requestedMonths} meses. Sem publicação: ${b.coverage.missingMonths.join(', ')||'nenhum'}.`,8);
 page(b.kind==='EXECUTIVE'?'Resultados, evolução e decisões':'Consumo, custos e indicadores');
 if(b.kind==='EXECUTIVE'){section('Economia e evolução');line('Economia acumulada no recorte: '+money(b.totals.savingsAfterFees));line('Honorários preservados: '+money(b.totals.totalFees));for(const m of b.months)line(m.month+' · Acumulado '+(m.cumulative===null?'sem publicação':money(m.cumulative)),9);}
 section('Consumo validado e comparação ACL × ACR');
 for(const i of b.invoices){line(`${i.month} · Consumo ${i.consumptionKwh===null?'indisponível':i.consumptionKwh.replace('.',',')+' kWh'} · Publicação v${i.version}`);for(const s of i.scenarios??[])line(`${s.scenario}: distribuidora ${money(s.distributor)} · fornecedor ${money(s.supplier)} · encargos ${money(s.additional)} · tributos adicionais ${money(s.taxes)} · subtotal ${money(s.subtotal)}`,8);if(i.reservationCount)line(`${i.reservationCount} ressalvas preservadas. Consulte o Expert para interpretar as condições da publicação.`,8);}
 section('Composição do custo ACL com honorários');
 if(!b.composition)line('Composição indisponível nesta publicação.');else for(const [i,c] of b.composition.entries()){if(y>723){doc.addPage();y=42;}doc.rect(40,y+2,8,8).fill(colors[i%colors.length]);doc.fontSize(9).fillColor('#3A5067').text(`${c.label}: ${money(c.amount)} · ${c.percent.replace('.',',')}%`,55,y,{width:495});y+=23;}
 section('Indicadores, ROI e projeções');for(const s of b.unavailable)line(s,9);line(b.disclosure,8);
 page('Eventos, alertas e fontes');section('Principais eventos publicados da unidade');if(!b.events.length)line('Nenhum evento publicado incluído neste recorte. Confira cobertura e permissões.');for(const e of b.events)line(`${e.effectiveDate} · ${e.title} · ${e.priority} · revisão ${e.revision}`,9);
 section('Alertas registrados nas apurações');let alerts=0;for(const i of b.invoices)for(const f of i.findings){alerts++;line(`${i.month} · ${f.code||'Revisão'} · ${f.message}`,9);}if(!alerts)line('Nenhum alerta de revisão incluído. Isso não comprova ausência de desperdício.');
 section('Publicações preservadas e integridade');for(const p of b.publications){line(`${p.month} · v${p.version} · Publicado ${when(p.publishedAt)}`,9);line('Grupo '+p.id+' · SHA-256 '+p.payloadHash,7);}
 section('Contexto e rastreabilidade');line('Este documento registra um recorte imutável. Alterações posteriores no cadastro ou nas apurações não modificam esta versão. Não comprova quitação de débitos. Comparações não normalizam consumo, produção ou duração.',9);line('Relatório '+row.id+' · SHA-256 '+row.payload_hash,7);
 const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.page.margins.bottom=0;doc.moveTo(40,793).lineTo(555,793).lineWidth(.5).stroke('#D3DFE8');doc.font('Helvetica').fontSize(7).fillColor('#6D839B').text(`Powered by Expert Energy · ${b.formatVersion} · ${when(b.generatedAt)}   |   ${i+1}/${range.count}`,40,801,{width:515,lineBreak:false});doc.page.margins.bottom=40;}
 doc.end();return done;
}
// Cell strings remain strings, including values starting '='. No imported formulas or macros.
export async function reportExcel(row:any):Promise<Buffer>{
 const b=row.body,w=new ExcelJS.Workbook();w.creator='Expert Energy';w.created=new Date(b.generatedAt);w.modified=w.created;
 const sheet=(name:string,headers:string[],rows:any[][])=>{const s=w.addWorksheet(name,{views:[{state:'frozen',ySplit:1}]});s.columns=headers.map((h,i)=>({header:h,key:String(i),width:i===0?27:34}));s.addRows(rows);s.getRow(1).height=28;s.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};s.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF142D46'}};s.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,rows.length+1),column:headers.length}};s.eachRow((r,n)=>{if(n>1){r.alignment={vertical:'top',wrapText:true};r.height=Math.min(180,Math.max(26,...rows[n-2].map(v=>Math.ceil(String(v??'').length/30)*14)));if(n%2===0)r.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFEDF4F8'}};}});s.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};return s;};
 const amount=(v:unknown)=>typeof v==='string'&&/^-?\d+\.\d{2}$/.test(v)&&Number.isSafeInteger(Number(v.replace('.','')))?Number(v):v??'Indisponível';
 const summary=sheet('Resumo',['Indicador','Valor'],[['Tipo',titles[b.kind]],['Organização',b.header.organizationName],['Cliente',b.header.customerName],['Unidade',b.header.unitName],['Código da unidade',b.header.unitCode],['Endereço',[b.header.address,b.header.city,b.header.state].filter(Boolean).join(' · ')],['Distribuidora',b.header.distributor],['Contato',b.header.contactName],['E-mail',b.header.contactEmail],['De',b.period.from],['Até',b.period.to],['Emitido em',when(b.generatedAt)],['Versão',b.formatVersion],['Cobertura',`${b.coverage.publishedMonths}/${b.coverage.requestedMonths}`],['Contexto',b.context],['Custo ACR',amount(b.totals.acr)],['ACL com honorários',amount(b.totals.aclAfterFees)],['Honorários',amount(b.totals.totalFees)],['Economia',amount(b.totals.savingsAfterFees)],['Score de economia publicado',b.totals.savingsPercent===null?'Indisponível':b.totals.savingsPercent+'%'],...b.unavailable.map((s:string)=>['Indisponibilidade',s]),['Ressalvas',b.disclosure],['ID relatório',row.id],['Hash relatório',row.payload_hash]]);
 summary.getColumn(2).width=92;for(const n of [16,17,18,19])summary.getCell(n+1,2).numFmt='"R$" #,##0.00;[Red]-"R$" #,##0.00';summary.getRow(16).height=65;
 const months=sheet('Evolução',['Mês','Custo ACR (R$)','ACL com honorários (R$)','Economia (R$)','Economia acumulada (R$)','Cobertura'],b.months.map((m:any)=>[m.month,amount(m.totals?.acr),amount(m.totals?.aclAfterFees),amount(m.totals?.savingsAfterFees),amount(m.cumulative),m.totals?'Publicado':'Sem publicação']));for(const c of [2,3,4,5])months.getColumn(c).numFmt='#,##0.00;[Red]-#,##0.00';
 sheet('Consumo e custos',['Mês','Consumo validado (kWh exato)','Cenário','Distribuidora (R$)','Fornecedor (R$)','Encargos (R$)','Tributos adicionais (R$)','Subtotal (R$)','Versão'],b.invoices.flatMap((i:any)=>(i.scenarios??[{scenario:'Indisponível'}]).map((s:any)=>[i.month,i.consumptionKwh??'Indisponível',s.scenario,amount(s.distributor),amount(s.supplier),amount(s.additional),amount(s.taxes),amount(s.subtotal),i.version])));
 sheet('Eventos e alertas',['Data ou mês','Tipo','Título ou código','Descrição','Fonte'],[...b.events.map((e:any)=>[e.effectiveDate,'Evento publicado',e.title,e.priority,e.id]),...b.invoices.flatMap((i:any)=>i.findings.map((f:any)=>[i.month,'Alerta registrado',f.code,f.message,i.groupId]))]);
 sheet('Fontes exatas',['Mês','Versão publicada','Grupo','SHA-256 publicado','Publicação','ACR exato (R$)','ACL exato (R$)','Economia exata (R$)'],b.publications.map((p:any)=>{const m=b.months.find((m:any)=>m.month===p.month);return [p.month,p.version,p.id,p.payloadHash,p.publishedAt,m?.totals?.acr??'Indisponível',m?.totals?.aclAfterFees??'Indisponível',m?.totals?.savingsAfterFees??'Indisponível'];}));
 return Buffer.from(await w.xlsx.writeBuffer());
}
