import {ServiceUnavailableException} from '@nestjs/common';
import {proposalDocumentModel,ProposalDocumentModel} from './sales-proposal-document';
const labels:Record<string,string>={validUntil:'Validade da oferta',contractTerm:'Prazo de contratação proposto',paymentTerms:'Condições de pagamento',implementationTerms:'Implantação e inclusões',supportTerms:'Condições de suporte',renewalCancellationTerms:'Renovação e cancelamento',exclusions:'Exclusões do escopo'};
export function offerDocumentModel(data:any):ProposalDocumentModel{
 const t=data?.terms,d=t?.definition;
 if(!t||t.status!=='APPROVED_INTERNAL'||!Number.isSafeInteger(t.revision)||t.revision<1||!d||typeof d!=='object'||Object.keys(d).length!==7||Object.keys(labels).some(k=>typeof d[k]!=='string'||d[k].trim().length<5||d[k].length>1000)||typeof data.expired!=='boolean'||!/^\d{4}-\d{2}-\d{2}$/.test(data.asOfDate??'')||!/^\d{4}-\d{2}-\d{2}$/.test(d.validUntil)||typeof t.approvedAt!=='string')throw new ServiceUnavailableException('Documento consolidado indisponível.');
 const base=proposalDocumentModel(data.proposal),clean=(v:string)=>v.replace(/[\u0000-\u001f\u007f]/g,' ');
 return {...base,title:'Proposta e condições internas',notice:'Minuta interna - sem aceite, assinatura, cobrança ou ativação de licença.',sections:[...base.sections.filter(s=>s.title!=='Condições e ressalvas'),{title:'Preços e escopo preservados',rows:base.sections.at(-1)!.rows.filter(r=>r.label!=='Limites desta prévia')},{title:'Condições aprovadas internamente',rows:[{label:'Revisão explícita',value:String(t.revision)},{label:'Aprovada em',value:clean(t.approvedAt)},{label:'Consulta em (UTC)',value:data.asOfDate},{label:'Situação da validade',value:data.expired?'VENCIDA - documento histórico, não é oferta vigente':'Validade registrada; aprovação somente interna'},...Object.entries(labels).map(([key,label])=>({label,value:clean(d[key])})),{label:'Limites deste documento',value:'Não constitui contrato, aceite do cliente ou comprovação de pagamento. Meios de pagamento, renovação e liberação são condições propostas; este documento não executa essas ações.'}]}]};
}
