import {BadRequestException,ForbiddenException,ServiceUnavailableException} from '@nestjs/common';
import {Reflector} from '@nestjs/core';
import {SalesAsaasService} from './sales-asaas.service';
import {SalesAsaasAdapter,SANDBOX_URL,cents,paymentSummary} from './sales-asaas.adapter';
import {SalesAsaasController,SalesAsaasWebhookController} from './sales-asaas.controller';
import {PUBLIC_KEY} from '../../common/decorators/public.decorator';
import {PERMISSIONS_KEY} from '../../common/decorators/require-permission.decorator';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const token='test-only-webhook-token-'.repeat(3);
const payment={id:'pay_fixture',customer:'cus_fixture',value:850,netValue:840,status:'RECEIVED',externalReference:id};
const payload={id:'evt_fixture&123',event:'PAYMENT_RECEIVED',payment:{...payment,email:'private@example.com',cpfCnpj:'private',invoiceUrl:'private'}};
describe('Asaas sandbox foundation',()=>{
 let rpc:jest.Mock,adapter:{payment:jest.Mock},service:SalesAsaasService,settings:Record<string,string>;
 beforeEach(()=>{settings={SALES_ASAAS_SANDBOX_ENABLED:'true',SALES_ASAAS_SANDBOX_WEBHOOK_TOKEN:token};rpc=jest.fn().mockResolvedValue({data:{},error:null});adapter={payment:jest.fn()};service=new SalesAsaasService({getClient:()=>({rpc})} as any,{get:(key:string)=>settings[key]} as any,adapter as any);});
 it('defaults off, before token, database or network',async()=>{delete settings.SALES_ASAAS_SANDBOX_ENABLED;await expect(service.webhook(token,payload)).rejects.toBeInstanceOf(ServiceUnavailableException);await expect(service.list(id,{})).rejects.toBeInstanceOf(ServiceUnavailableException);expect(rpc).not.toHaveBeenCalled();expect(adapter.payment).not.toHaveBeenCalled();});
 it.each([undefined,'',token+'x','wrong'])('rejects unauthorized ingress',async t=>{await expect(service.webhook(t,payload)).rejects.toBeInstanceOf(ForbiddenException);expect(rpc).not.toHaveBeenCalled();});
 it('requires separate strong webhook configuration',async()=>{settings.SALES_ASAAS_SANDBOX_WEBHOOK_TOKEN='short';await expect(service.webhook('short',payload)).rejects.toBeInstanceOf(ServiceUnavailableException);});
 it('persists only allowlisted fields before acknowledging',async()=>{await expect(service.webhook(token,payload)).resolves.toEqual({received:true});const stored=rpc.mock.calls[0][1];expect(stored.p_actor).toBeNull();expect(stored.p_action).toBe('inbox');expect(JSON.stringify(stored)).not.toMatch(/private|invoiceUrl|cpfCnpj|email|test-only/);expect(stored.p_body.event.payment.grossCents).toBe(85000);});
 it('does not acknowledge persistence failure',async()=>{rpc.mockResolvedValue({error:{code:'XX000'}});await expect(service.webhook(token,payload)).rejects.toBeInstanceOf(ServiceUnavailableException);});
 it.each([null,[],{...payload,id:'bad'},{...payload,event:'TRANSFER_DONE'},{...payload,payment:{...payment,value:-1}},{...payload,payment:{...payment,netValue:900}},{...payload,extra:'x'.repeat(17000)}])('rejects malformed or oversized events',async b=>{await expect(service.webhook(token,b)).rejects.toBeInstanceOf(BadRequestException);expect(rpc).not.toHaveBeenCalled();});
 it.each([{page:'-1'},{page:'1e2'},{environment:'PRODUCTION'},{from:'yesterday'},{status:'PAID'},{search:{}}])('rejects invalid filters',q=>expect(()=>service.list(id,q)).toThrow(BadRequestException));
 it('cannot change values or environment in a binding',()=>{expect(()=>service.bind(id,{id,proposalId:id,paymentId:'pay_fixture',customerId:'cus_fixture',justification:'Test fixture',grossCents:1})).toThrow(BadRequestException);expect(rpc).not.toHaveBeenCalled();});
 it('does not call Asaas after Owner authorization fails',async()=>{rpc.mockResolvedValue({error:{code:'42501'}});await expect(service.verify(id,id)).rejects.toBeInstanceOf(ForbiddenException);expect(adapter.payment).not.toHaveBeenCalled();});
 it('skips already verified or unlinked records',async()=>{rpc.mockResolvedValue({data:{skip:true,status:'VERIFIED'}});await expect(service.verify(id,id)).resolves.toEqual({status:'VERIFIED'});expect(adapter.payment).not.toHaveBeenCalled();});
 it('preserves a recoverable review on timeout and never retries a creation',async()=>{rpc.mockResolvedValueOnce({data:{paymentId:'pay_fixture'}}).mockResolvedValue({data:{status:'REVIEW'}});adapter.payment.mockRejectedValue(new Error('timeout credential should not appear'));await expect(service.verify(id,id)).rejects.toThrow('evento continua em análise');expect(rpc.mock.calls[1][1].p_body.summary).toBeNull();expect(adapter.payment).toHaveBeenCalledTimes(1);});
 it('passes a point query to database validation after claiming',async()=>{rpc.mockResolvedValueOnce({data:{paymentId:'pay_fixture'}}).mockResolvedValue({data:{status:'VERIFIED'}});adapter.payment.mockResolvedValue(paymentSummary(payment));await expect(service.verify(id,id)).resolves.toEqual({status:'VERIFIED'});expect(rpc.mock.calls[1][1].p_body.lease).toBe(rpc.mock.calls[0][1].p_body.lease);});
 it('protects every admin endpoint and isolates public ingress',()=>{const r=new Reflector();for(const key of ['list','read','bind','verify'] as const)expect(r.get(PERMISSIONS_KEY,SalesAsaasController.prototype[key])).toEqual(['82e7fc71-479a-4dd6-8b22-4fba6eaa6841']);expect(r.get(PUBLIC_KEY,SalesAsaasWebhookController.prototype.webhook)).toBe(true);});
 it.each([0,0.01,850,9999999.99])('handles valid currency precision',v=>expect(cents(v)).toBe(Math.round(v*100)));
 it.each([-1,NaN,Infinity,'1',0.001,10000001])('rejects invalid currency precision',v=>expect(()=>cents(v)).toThrow(BadRequestException));
 it('unknown net value is not zero',()=>expect(paymentSummary({...payment,netValue:undefined}).netCents).toBeNull());
 it('does not persist contact data in arbitrary external references',()=>expect(paymentSummary({...payment,externalReference:'private@example.com'}).reference).toBeNull());
 it('canonicalizes the allowed binding UUID',()=>expect(paymentSummary({...payment,externalReference:id.toUpperCase()}).reference).toBe(id));
});
describe('Read-only Asaas adapter',()=>{
 const original=global.fetch;afterEach(()=>{global.fetch=original;});
 const config=(overrides:Record<string,string|undefined>={})=>({get:(key:string)=>({SALES_ASAAS_SANDBOX_ENABLED:'true',SALES_ASAAS_SANDBOX_CALLS_ENABLED:'true',SALES_ASAAS_BASE_URL:SANDBOX_URL,SALES_ASAAS_SANDBOX_API_KEY:'test-key-never-used-externally',...overrides} as Record<string,string>)[key]});
 it.each([{SALES_ASAAS_BASE_URL:'https://api.asaas.com/v3'},{SALES_ASAAS_SANDBOX_CALLS_ENABLED:'false'},{SALES_ASAAS_SANDBOX_API_KEY:''}])('blocks unapproved external calls',async c=>{global.fetch=jest.fn();await expect(new SalesAsaasAdapter(config(c) as any).payment('pay_fixture')).rejects.toBeInstanceOf(ServiceUnavailableException);expect(global.fetch).not.toHaveBeenCalled();});
 it('uses only GET to the fixed sandbox endpoint with redirects disabled',async()=>{global.fetch=jest.fn().mockResolvedValue(new Response(JSON.stringify(payment)));await expect(new SalesAsaasAdapter(config() as any).payment('pay_fixture')).resolves.toEqual(paymentSummary(payment));expect(global.fetch).toHaveBeenCalledWith(SANDBOX_URL+'/payments/pay_fixture',expect.objectContaining({method:'GET',redirect:'error'}));});
 it.each([new Response('{}',{status:403}),new Response(JSON.stringify({...payment,id:'pay_other'})),new Response('x'.repeat(70000))])('fails closed on HTTP, identity or size mismatch',async response=>{global.fetch=jest.fn().mockResolvedValue(response);await expect(new SalesAsaasAdapter(config() as any).payment('pay_fixture')).rejects.toBeInstanceOf(ServiceUnavailableException);});
 it('rejects URL injection before fetch',async()=>{global.fetch=jest.fn();await expect(new SalesAsaasAdapter(config() as any).payment('../customers')).rejects.toBeInstanceOf(BadRequestException);expect(global.fetch).not.toHaveBeenCalled();});
});
