import {normalizeLead} from './sales-intake.input';
import {SalesIntakeService} from './sales-intake.service';
import {salesCors} from './sales-intake.cors';
const lead={requestId:'11111111-1111-4111-8111-111111111111',name:'Pessoa de Teste',company:'Empresa de Teste',cnpj:'11222333000181',jobTitle:'Gestão',email:'TEST@example.com',phone:'+55 16 99999-9999',units:3,users:2,freeMarket:'yes',solar:false,buysEnergy:true,management:'spreadsheet',goals:['ocr'],contactMethod:'email',consent:true,consentVersion:'sales-contact-v1',website:''};
describe('Sales intake: no identity, licensing or payment side effects',()=>{
 const env={...process.env};afterEach(()=>{process.env={...env};});
 test('normalizes CNPJ, email and phone',()=>{expect(normalizeLead(lead)).toMatchObject({email:'test@example.com',phone:'+5516999999999',cnpj:'11222333000181',emailKind:'CORPORATE'});});
 test('accepts Receita Federal public alphanumeric example with verified digits',()=>{expect(normalizeLead({...lead,cnpj:'00.000.000/E08G-12'}).cnpj).toBe('00000000E08G12');expect(()=>normalizeLead({...lead,cnpj:'00.000.000/E08G-13'})).toThrow();});
 test('personal email is received for commercial review',()=>{expect(normalizeLead({...lead,email:'pessoa@gmail.com'}).emailKind).toBe('PERSONAL');});
 test.each([{cnpj:'11222333000182'},{consent:false},{consentVersion:'other'},{website:'spam'},{organization_id:'victim'},{role:'admin_platform'},{units:0},{users:1.5},{goals:[]},{goals:['ocr','ocr']},{goals:['hidden_module']},{phone:'16999999999'},{name:'x\nsecret'},{freeMarket:'unknown'}])('rejects invalid or unauthorized fields %j',patch=>{expect(()=>normalizeLead({...lead,...patch})).toThrow();});
 test('feature is off by default',async()=>{delete process.env.SALES_INTAKE_ENABLED;const rpc=jest.fn();await expect(new SalesIntakeService({getClient:()=>({rpc})} as any).submit(lead,'https://www.expertenergy.com.br','1')).rejects.toMatchObject({status:404});expect(rpc).not.toHaveBeenCalled();});
 test('requires allowed origin and server secret',async()=>{process.env.SALES_INTAKE_ENABLED='true';const rpc=jest.fn();const service=new SalesIntakeService({getClient:()=>({rpc})} as any);await expect(service.submit(lead,'https://evil.example','1')).rejects.toMatchObject({status:403});delete process.env.SALES_INTAKE_HASH_SECRET;await expect(service.submit(lead,'https://www.expertenergy.com.br','1')).rejects.toMatchObject({status:503});expect(rpc).not.toHaveBeenCalled();});
 test('only returns a receipt after database confirmation',async()=>{process.env.SALES_INTAKE_ENABLED='true';process.env.SALES_INTAKE_HASH_SECRET='x'.repeat(32);const rpc=jest.fn().mockResolvedValue({data:{receipt:lead.requestId},error:null});const service=new SalesIntakeService({getClient:()=>({rpc})} as any);expect(await service.submit(lead,'https://www.expertenergy.com.br','127.0.0.1')).toMatchObject({receipt:lead.requestId,status:'RECEIVED'});expect(rpc.mock.calls[0][0]).toBe('submit_platform_sales_lead');expect(rpc.mock.calls[0][1].p_requester).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(rpc.mock.calls[0])).not.toContain('127.0.0.1');});
 test.each([['P3601',409],['P3602',429],['database_down',503]])('failure never reports success %s',async(code,status)=>{process.env.SALES_INTAKE_ENABLED='true';process.env.SALES_INTAKE_HASH_SECRET='x'.repeat(32);const service=new SalesIntakeService({getClient:()=>({rpc:jest.fn().mockResolvedValue({error:{code}})})} as any);await expect(service.submit(lead,'https://www.expertenergy.com.br','1')).rejects.toMatchObject({status});});
 test('database owner denial is preserved',async()=>{const service=new SalesIntakeService({getClient:()=>({rpc:jest.fn().mockResolvedValue({error:{code:'42501'}})})} as any);await expect(service.list('user',0,'')).rejects.toMatchObject({status:403});});
 test('CORS stays unchanged outside the exact intake path',()=>{process.env.CORS_ORIGIN='https://app.expertenergy.com.br';let options:any;const cb=(_e:any,v:any)=>{options=v;};salesCors({url:'/api/v1/licenses'},cb);expect(options).toEqual({origin:'https://app.expertenergy.com.br',credentials:true});salesCors({url:'/api/v1/public/sales/leads'},cb);expect(options.credentials).toBe(false);expect(options.methods).toEqual(['POST','OPTIONS']);expect(options.origin).toBe('https://www.expertenergy.com.br');salesCors({url:'/api/v1/public/sales/leads/other'},cb);expect(options.credentials).toBe(true);});
});
