import {validateCceeRecord} from './ccee-validation';
function fixture(){const binding={organizationId:'o1',customerId:'c1',unitId:'u1',profileCode:'80021',measurementPoint:'m1',authorizationId:'authorization',authorizationRevision:1};const record:any={schemaVersion:'ccee-record/1',kind:'CREDIT',binding:{...binding},evidence:{provider:'CCEE',service:'confirmed-adapter',externalId:'id',revision:'1',month:'2026-08',retrievedAt:'2026-10-08T12:00:00Z',sourceHash:'a'.repeat(64),finality:'FINAL'},lines:[{type:'MONEY',code:'credit',amountBrl:'125.34',effect:'CREDIT',taxTreatment:'GROSS',category:'CCEE'}]};return {binding,record};}
describe('CCEE normalized private records',()=>{
 it('preserves credit direction and requires review before calculation',()=>{const f=fixture(),r=validateCceeRecord(f.record,f.binding);expect(r).toMatchObject({state:'READY_FOR_REVIEW',calculationAllowed:false,requiresHumanReview:true});expect(r.record.lines[0]).toMatchObject({effect:'CREDIT',amountBrl:'125.34'});});
 it.each(['organizationId','customerId','unitId','profileCode','measurementPoint','authorizationId','authorizationRevision'])('rejects mismatched %s',key=>{const f=fixture();f.record.binding[key]='foreign';expect(()=>validateCceeRecord(f.record,f.binding)).toThrow('BINDING');});
 it('does not accept an empty authorized binding object',()=>{const f=fixture();expect(()=>validateCceeRecord(f.record,{} as any)).toThrow('BINDING');});
 it.each(['PROVISIONAL','UNKNOWN_TAX'])('holds incomplete finality/tax data %s',kind=>{const f=fixture();if(kind==='PROVISIONAL')f.record.evidence.finality=kind;else f.record.lines[0].taxTreatment='UNKNOWN';expect(validateCceeRecord(f.record,f.binding).state).toBe('PENDING');});
 it('rejects credits represented as debits or duplicate charge lines',()=>{const f=fixture();f.record.lines[0].effect='DEBIT';expect(()=>validateCceeRecord(f.record,f.binding)).toThrow('KIND');f.record.lines[0].effect='CREDIT';f.record.lines.push({...f.record.lines[0]});expect(()=>validateCceeRecord(f.record,f.binding)).toThrow('DUPLICATE');});
});
