import {cceeConfig,soapRequest,CceeConfig} from './ccee-config';
import {parseCcee,pldHours,monthlyPld,profilePresent} from './ccee-response';
import {CceeService} from './ccee.service';
const config:CceeConfig={organizationId:'org-test',profile:'123',username:'123456',password:'a<&"b',pfx:Buffer.alloc(0),passphrase:'secret'};
const envelope=(body:string,pages='1')=>`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" xmlns:mh="http://xmlns.energia.org.br/MH/v1" xmlns:bm="http://xmlns.energia.org.br/BM/v1" xmlns:bo="http://xmlns.energia.org.br/BO/v1"><s:Header><mh:paginacao><mh:numero>1</mh:numero><mh:totalPaginas>${pages}</mh:totalPaginas><mh:quantidadeTotalItens>1</mh:quantidadeTotalItens></mh:paginacao></s:Header><s:Body>${body}</s:Body></s:Envelope>`;
const business=`<bm:listarPLDResponse><bm:plds><bm:pld><bo:vigencia><bo:inicio>2026-08-01T00:00:00-03:00</bo:inicio><bo:fim>2026-08-01T01:00:00-03:00</bo:fim></bo:vigencia><bo:valores>${[1,2,3,4].map(code=>`<bo:valor><bo:indicadorRedeEletrica>false</bo:indicadorRedeEletrica><bo:submercado><bo:codigo>${code}</bo:codigo></bo:submercado><bo:tipo>HORARIO</bo:tipo><bo:valor><bo:codigo>BRL</bo:codigo><bo:valor>220.25</bo:valor></bo:valor></bo:valor>`).join('')}</bo:valores></bm:pld></bm:plds></bm:listarPLDResponse>`;
describe('CCEE read connector',()=>{
 it('defaults to disabled and rejects incomplete credentials',()=>{expect(()=>cceeConfig({})).toThrow('CCEE_NOT_CONFIGURED');expect(new CceeService().status().automaticImport).toBe(false);});
 it('escapes WS-Security values and rejects arbitrary months/pages',()=>{const request=soapRequest(config,'pld',1,'2026-02');expect(request).toContain('a&lt;&amp;&quot;b');expect(request).toContain('2026-02-28T00:00:00');expect(()=>soapRequest(config,'pld',0,'2026-02')).toThrow();expect(()=>soapRequest(config,'pld',1,'2026-99')).toThrow();});
 it('reads official hourly structure, pagination and provenance',()=>{const parsed=parseCcee(envelope(business),'pld',1);expect(parsed.hash).toMatch(/^[a-f0-9]{64}$/);expect(pldHours(parsed.body,'2026-08')).toHaveLength(4);expect(pldHours(parsed.body,'2026-08')[0].value).toBe(220.25);});
 it.each(['<!DOCTYPE a [<!ENTITY b SYSTEM "file:///secret">]>','<!ENTITY b "secret">'])('rejects XML entity declarations',declaration=>expect(()=>parseCcee(declaration+envelope(business),'pld',1)).toThrow());
 it('rejects SOAP faults, wrong namespaces and unbounded pagination',()=>{expect(()=>parseCcee(envelope('<s:Fault><faultstring>secret provider echo</faultstring></s:Fault>'),'pld',1)).toThrow('CCEE_SOAP_FAULT');expect(()=>parseCcee(envelope(business).replace('http://xmlns.energia.org.br/BM/v1','https://foreign.test'),'pld',1)).toThrow();expect(()=>parseCcee(envelope(business,'200'),'pld',1)).toThrow('CCEE_INVALID_PAGINATION');});
 it('rejects foreign business data and duplicate markets',()=>{expect(()=>parseCcee(envelope(business.replace('<bo:vigencia>','<x:vigencia xmlns:x="https://foreign.test">').replace('</bo:vigencia>','</x:vigencia>')),'pld',1)).toThrow();const body=parseCcee(envelope(business),'pld',1).body;body.plds.pld.valores.valor[1].submercado.codigo='1';expect(()=>pldHours(body,'2026-08')).toThrow();});
 it('refuses partial months or repeated hours instead of inventing an average',()=>{const single=pldHours(parseCcee(envelope(business),'pld',1).body,'2026-08');expect(()=>monthlyPld(single,'2026-08')).toThrow('CCEE_INCOMPLETE_MONTH');expect(()=>monthlyPld(Array.from({length:744},()=>single).flat(),'2026-08')).toThrow('CCEE_INCOMPLETE_MONTH');});
 it('averages a complete month independently for all four markets',()=>{const rows=Array.from({length:744},(_,i)=>['SE_CO','S','NE','N'].map(submarket=>({start:new Date(Date.parse('2026-08-01T03:00:00Z')+i*3600000).toISOString(),end:'',submarket:submarket as 'SE_CO',value:i%2?300:200}))).flat();expect(monthlyPld(rows,'2026-08').map(r=>r.meanBrlMwh)).toEqual([250,250,250,250]);});
 it('does not confirm a foreign profile',()=>{expect(profilePresent({perfis:{perfil:{codigo:'999'}}},'123')).toBe(false);expect(profilePresent({perfis:{perfil:{codigo:'123'}}},'123')).toBe(true);});
 it('rejects caller-supplied organization/profile and open months before any network call',async()=>{const service=new CceeService();await expect(service.preview({month:'2026-08',organizationId:'foreign'})).rejects.toThrow();await expect(service.preview({month:'2099-01'})).rejects.toThrow();});
});
