import {registrationReadiness,CceeReadinessContext} from './ccee-registration-readiness';
const context=():CceeReadinessContext=>({organizationId:'o1',checkedAt:'2026-10-08T12:00:00Z',record:{id:'record',revision:3,status:'APPROVED',operation:'VALIDATE_AMOUNTS',customer_id:'client',consumer_unit_id:'unit',deadline:'2026-10-20T12:00:00Z'},customerActive:true,agendaCurrent:true,representation:{id:'proof',revision:2,status:'APPROVED',profileCode:'12345',independentReview:true}});
describe('CCEE registration preflight',()=>{
 it('never equates an approved draft and documentary evidence with provider authorization',()=>{const r=registrationReadiness(context());expect(r.transmissionEnabled).toBe(false);expect(r.providerVerified).toBe(false);expect(r.checks.filter(c=>c.status==='PENDING').map(c=>c.code)).toEqual(['PROVIDER_AUTHORIZATION','LAYOUT','PILOT','EXACT_APPROVAL']);});
 it.each(['DRAFT','REVOKED'])('blocks replaced representation %s',status=>{const c=context();c.representation!.status=status;expect(registrationReadiness(c).checks.find(c=>c.code==='REPRESENTATION_DOCUMENT')?.status).toBe('PENDING');});
 it('requires independent representation review',()=>{const c=context();c.representation!.independentReview=false;expect(registrationReadiness(c).checks.find(c=>c.code==='REPRESENTATION_DOCUMENT')?.status).toBe('PENDING');});
 it('keeps missing representation, manual deadline and changed agenda pending',()=>{const c=context();c.representation=null;c.agendaCurrent=null;const r=registrationReadiness(c);expect(r.profileCode).toBeNull();expect(r.checks.find(c=>c.code==='AGENDA')?.status).toBe('PENDING');c.agendaCurrent=false;expect(registrationReadiness(c).checks.find(c=>c.code==='AGENDA')?.status).toBe('PENDING');});
 it('checks current customer, status and expired deadline',()=>{const c=context();c.customerActive=false;c.record.status='CANCELLED';c.record.deadline=c.checkedAt;expect(registrationReadiness(c).checks.slice(0,3).every(c=>c.status==='PENDING')).toBe(true);});
 it('rejects invalid operational context',()=>{expect(()=>registrationReadiness({...context(),checkedAt:'bad'})).toThrow();expect(()=>registrationReadiness({...context(),record:{...context().record,operation:'SEND'}})).toThrow();});
});
