import {noticeReady,sendCustomerNotice} from './customer-notice.transport';
import {TemplateSnapshot} from '../whatsapp-delivery/whatsapp-templates.service';
describe('customer notice privacy and send gates',()=>{
 const old={...process.env};afterEach(()=>process.env={...old});
 const d={id:'7f39c52c-4f6d-4d0e-a20f-2390dc38c693',channel:'email',event:'REQUEST',destination:'test@example.invalid'};
 it('emails a generic authenticated portal notice with durable idempotency and no operation content',async()=>{Object.assign(process.env,{RESEND_API_KEY:'synthetic',REPORTS_EMAIL_FROM:'notice@example.invalid'});const transport=jest.fn().mockResolvedValue({ok:true,json:async()=>({id:'accepted'})});expect((await sendCustomerNotice(d,undefined,transport)).state).toBe('ACCEPTED');const request=transport.mock.calls[0][1],body=JSON.parse(request.body);expect(request.headers['Idempotency-Key']).toBe('customer-notice/'+d.id);expect(body.attachments).toBeUndefined();expect(body.text).toContain('https://app.expertenergy.com.br');expect(body.text).not.toContain(d.id);});
 it('requires approved parameterless WhatsApp template, never the cost alert model',async()=>{Object.assign(process.env,{WHATSAPP_ACCESS_TOKEN:'synthetic',WHATSAPP_PHONE_NUMBER_ID:'123',WHATSAPP_GRAPH_VERSION:'v26.0'});const templates:TemplateSnapshot={configured:true,checkedAt:'',manageUrl:null,rows:[{name:'energyos_solicitacao_cliente',label:'Pedido',status:'APPROVED',parameterless:true}]};expect(noticeReady('whatsapp','REQUEST',templates)).toBe(true);expect(noticeReady('whatsapp','REQUEST',{...templates,rows:templates.rows.map(r=>({...r,parameterless:false}))})).toBe(false);const transport=jest.fn().mockResolvedValue({ok:true,json:async()=>({messages:[{id:'wamid.ok'}]})});await sendCustomerNotice({...d,channel:'whatsapp',destination:'+5516999999999'},templates,transport);expect(JSON.parse(transport.mock.calls[0][1].body).template.name).toBe('energyos_solicitacao_cliente');});
 it('blocks unapproved channels and treats uncertain sends as unknown without retry',async()=>{const transport=jest.fn();expect((await sendCustomerNotice({...d,channel:'whatsapp'},undefined,transport)).reason).toBe('PROVIDER_NOT_READY');expect(transport).not.toHaveBeenCalled();Object.assign(process.env,{RESEND_API_KEY:'synthetic',REPORTS_EMAIL_FROM:'notice@example.invalid'});transport.mockRejectedValue(Error('timeout'));expect((await sendCustomerNotice(d,undefined,transport)).state).toBe('UNKNOWN');expect(transport).toHaveBeenCalledTimes(1);});
});
