import {baselineFromStudy,indicativePrice,specificPrice,decimal,energyReference} from './energy-price-score';
const line=(q:string)=>({quantity:q,grossRate:'1',netRate:'0.5',amount:q+'.00',source:'Invoice',pages:[1]});
function study(){return {location:{code:'SE_CO',energyReference:{state:'AVAILABLE',month:'2026-08',peak:line('100'),off:line('900'),gd:line('400')}},proposal:{energyBasis:{checked:true,method:'LOSS_UPLIFT_ICMS_INSIDE',baseBrlMwh:'220',lossPercent:'2.5',icmsPercent:'18'}},rows:Array.from({length:12},(_,i)=>({month:'2026-'+String(i+1).padStart(2,'0'),sourceMonth:'2026-'+String(i+1).padStart(2,'0'),peakKwh:'100',offPeakKwh:'900'})),gdHistory:{rows:Array.from({length:12},(_,i)=>({month:'2026-'+String(i+1).padStart(2,'0'),gdKwh:'400'}))},gdComparison:{tusdCredit:'999999.00'}};}
describe('specific energy price',()=>{
 it('subtracts GD TE only, uses measured total consumption and excludes TUSD',()=>{const b=baselineFromStudy(study());expect(b.grossBrlMwh).toBe('600.00');expect(b.netBrlMwh).toBe('300.00');expect(b.annualKwh).toBe('12000.000000000');expect(b.contractNetBrlMwh).toBe('225.50');expect(indicativePrice(b.netBrlMwh!,b.contractNetBrlMwh!)).toMatchObject({value:'225.50',notice:'não contém tributo na indicação'});});
 it('calculates no-GD base without inventing credits',()=>{const r=study();r.location.energyReference.gd=null as any;expect(baselineFromStudy(r).grossBrlMwh).toBe('1000.00');});
 it('does not assume an ICMS rate or zero for missing tax reference',()=>{const r=study();r.location.energyReference.peak.netRate=null as any;expect(baselineFromStudy(r).netBrlMwh).toBeNull();expect(indicativePrice(null,'220.00').value).toBeNull();});
 it('rejects credits exceeding energy and nonconsecutive history',()=>{const r=study();r.gdHistory.rows[0].gdKwh='1001';expect(()=>baselineFromStudy(r)).toThrow('Crédito TE');const s=study();s.rows[0].sourceMonth='2025-01';expect(()=>baselineFromStudy(s)).toThrow('consecutivo');});
 it('weights cost by consumption instead of averaging unit prices',()=>{expect(specificPrice(10000n+90000n,decimal('100')+decimal('300'))).toBe('2500.00');expect(specificPrice(0n,0n)).toBeNull();});
 it('requires independent review when table confidence is missing, preserving traceability',()=>{const f=(v:string)=>({text:v,decimal:v,pages:[1],spans:[{offset:0,length:1}],issues:['MISSING_CONFIDENCE'],confidence:null});const op=(period:string):any=>({component:'TE',role:'CHARGE',period,source:'invoice table',issues:[],fields:{description:f('TE '+period),quantity:f('100'),grossRate:f('1'),aneelRate:f('0.5'),amount:f('100.00'),unit:f('kWh')}});const p=op('PEAK'),o=op('OFF_PEAK');expect(energyReference([p,o],'2026-08')).toMatchObject({state:'AVAILABLE',reviewRequired:true});p.fields.amount.spans=[];expect(energyReference([p,o],'2026-08').state).toBe('BLOCKED');});
 it('blocks ambiguous peak identification and nontraceable OCR fields',()=>{const field=(decimal:string)=>({decimal,text:decimal,pages:[1],spans:[{offset:0,length:1}],issues:[],confidence:1});const op:any={component:'TE',role:'CHARGE',period:'UNSPECIFIED',source:'invoice',issues:[],fields:{quantity:field('100'),grossRate:field('1'),amount:field('100.00'),unit:{...field('0'),text:'kWh'},description:field('TE')}};expect(energyReference([op,op],'2026-08').state).toBe('BLOCKED');});
});

 it('recognizes signed CPFL GD TE with appended month even when generic role is CHARGE',()=>{const f=(v:string)=>({text:v,decimal:v,pages:[1],spans:[{offset:0,length:1}],issues:[],confidence:1});const op=(d:string,q:string,a:string,period:string):any=>({component:'TE',role:'CHARGE',period,source:d,issues:[],fields:{description:f(d),quantity:f(q),grossRate:f('1'),aneelRate:f('0.5'),amount:f(a),unit:f('kWh')}});const p=op('TE Ponta','100','100.00','PEAK'),o=op('TE Fora Ponta','900','900.00','OFF_PEAK'),g=op('Energia Atv Inj TEAGO26','400','-400.00','UNSPECIFIED'),t=op('Energia Atv Inj TUSDAGO26','400','-400.00','UNSPECIFIED');expect(energyReference([p,o,g,t],'2026-08')).toMatchObject({state:'AVAILABLE',gd:{amount:'400.00',netRate:'0.5'}});g.fields.amount=f('400.00');expect(energyReference([p,o,g],'2026-08').state).toBe('BLOCKED');});

 it('preserves nine-place GD estimates until cent rounding',()=>{const r=study();r.gdHistory.rows[0].gdKwh='400.123456789';const b=baselineFromStudy(r);expect(b.months?.[0].grossTe).toBe('599.88');expect(b.months?.[0].netTe).toBe('299.94');});
