import {randomUUID} from 'node:crypto';
import {AclAdmissionService,ACL_VIEW,ACL_MANAGE} from './acl-admission.service';
const permissions=[ACL_VIEW,ACL_MANAGE,'cbb2e904-0718-4eec-9396-dba899118cdd','8f105b02-4443-49de-b188-847e0284e7ed','1479c0b7-9608-4e95-bd83-7e6899255a78','cb949e2a-e01d-4cf0-8c69-6ca74fe4d627','d1f1b3be-a842-41e7-aeb1-45fefeb2f4c1','6da45eb4-810c-4e40-9933-d9cda66a8841'];
const tenant:any={organizationId:'o1',userId:randomUUID(),roleId:'r1',role:'gestor',scope:'organization',permissions};
const id=randomUUID(),body={requestId:randomUUID(),expectedRevision:1,stageKey:'technical',subject:'Enviar documento',body:'Envie o CUSD vigente no portal.',dueAt:'2027-01-01T18:00:00Z',responsibleId:tenant.userId,priority:'NORMAL',requestType:'DOCUMENT',reason:'Conferência técnica pelo Consultor.',checked:true};
function fixture(){const rpc=jest.fn(async(name:string,p:any)=>({data:name==='acl_assert_actor'?{organizationId:p.p_org,actorId:p.p_actor,canWork:true,canApprove:true}:name==='acl_request_read'?[]:{id:randomUUID(),requestRecordId:randomUUID(),agendaRecordId:randomUUID(),messageId:randomUUID()}}));const licenses={requireEntitlement:jest.fn().mockResolvedValue({})};const config={get:jest.fn((key?:string)=> 'o1')};return{rpc,licenses,config,service:new AclAdmissionService({getClient:()=>({rpc})} as any,licenses as any,config as any)};}
describe('ACL requests boundary',()=>{
 it('derives scope from the authenticated tenant and requires current licenses',async()=>{const f=fixture();await f.service.createRequest(id,body,tenant);expect(f.licenses.requireEntitlement).toHaveBeenCalledWith('o1','document_management');expect(f.rpc).toHaveBeenLastCalledWith('acl_request_create',expect.objectContaining({p_org:'o1',p_actor:tenant.userId,p_id:id,p_revision:1,p_data:expect.objectContaining({stageKey:'technical'})}));});
 it.each(['organizationId','customerId','unitId','actorId','documents','status'])('rejects injected %s',async field=>{const f=fixture();await expect(f.service.createRequest(id,{...body,[field]:'foreign'},tenant)).rejects.toThrow();expect(f.rpc).not.toHaveBeenCalled();});
 it('rejects unconfirmed, invalid deadline and invalid admission',async()=>{const f=fixture();for(const change of [{checked:false},{dueAt:'tomorrow'},{expectedRevision:0},{stageKey:'unknown'}])await expect(f.service.createRequest(id,{...body,...change},tenant)).rejects.toThrow();await expect(f.service.createRequest('bad',body,tenant)).rejects.toThrow();});
 it('rejects global, external client and missing operation permissions',async()=>{const f=fixture();for(const change of [{scope:'global'},{role:'consulta'},{permissions:permissions.filter(p=>p!=='6da45eb4-810c-4e40-9933-d9cda66a8841')}])await expect(f.service.createRequest(id,body,{...tenant,...change})).rejects.toThrow();});
 it('keeps provider-independent requests disabled until specifically enabled',async()=>{const f=fixture();f.config.get.mockImplementation((key:any)=>key==='ACL_ADMISSION_ORGANIZATIONS'?'o1':'');await expect(f.service.createRequest(id,body,tenant)).rejects.toThrow('habilitadas');});
 it('uses keyset pagination and refuses malformed or foreign request fields',async()=>{const f=fixture(),after=randomUUID();expect(await f.service.requests(id,{after},tenant)).toEqual({rows:[],nextCursor:null});expect(f.rpc).toHaveBeenLastCalledWith('acl_request_read',expect.objectContaining({p_after:after,p_id:id}));await expect(f.service.requests(id,{customerId:'o2'},tenant)).rejects.toThrow();});
 it('maps a transaction conflict without silently retrying a changed request',async()=>{const f=fixture();f.rpc.mockImplementation(async(name:string,p:any):Promise<any>=>name==='acl_assert_actor'?{data:{organizationId:p.p_org,actorId:p.p_actor,canWork:true,canApprove:true}}:{error:{code:'40001'}});await expect(f.service.createRequest(id,body,tenant)).rejects.toThrow('mudou');});
});
