import {financialBasis,financialComparison,financialDraft} from './acl-financial-comparison';
import {supplierPreview,supplierProposal} from './acl-supplier-preview';
import type {InvoiceCostReference} from './acl-gd-comparison';
const ref:InvoiceCostReference={state:'AVAILABLE_REVIEW_REQUIRED',documentId:'doc',month:'2026-08',billTotal:'610.00',gdCredits:'280.00',consumptionKwh:'1000',excludedTotals:[],pending:[],lines:[
 ...[['TUSD_PEAK','Consumo Ponta TUSD','100','100','1'],['TUSD_OFF','Consumo FPonta TUSD','180','900','0.2'],['DEMAND','Demanda','100','10','10'],['TE','Cons Ponta TE','50','100','0.5'],['TE','Cons FPonta TE','450','900','0.5'],['GD_CREDIT','Energia Atv Inj FPonta TUSD','-80','400','0.2'],['GD_CREDIT','Energia Atv Inj FPonta TE','-200','400','0.5'],['SHARED','Iluminação','10',null,null]].map((v,i)=>({kind:v[0] as any,description:v[1]!,amount:v[2]!,quantity:v[3],grossRate:v[4],source:'row'+i,pages:[1]}))]};
const history={sourceDocumentId:'doc',rows:Array.from({length:12},(_,i)=>({month:i<4?'2025-'+String(i+9).padStart(2,'0'):'2026-'+String(i-3).padStart(2,'0'),peakKwh:'100',offPeakKwh:'900',demandKw:'10',days:30,page:1,source:'row'+i}))};
function proposal(energy='100',investment='100'){return supplierProposal({supplier:'Fornecedor teste',energyBrlMwh:energy,startMonth:'2026-09',months:12,fixedMonthlyBrl:'10',savingsPercent:'10',estimatedMonthlyAclBrl:'5',distribution:{peakBrlKwh:'1',offPeakBrlKwh:'0.2',demandBrlKw:'10',discountPercent:'50',source:'Tarifas de referência conferidas.',checked:true},losses:'INCLUDED',taxes:'INCLUDED',source:'Modelo de teste com custos revisados.',checked:true,financialBasis:{method:'FIXED_TARIFFS_MEASURED_DEMAND',sharedMonthlyBrl:'10',source:'Custos comuns e demanda medida conferidos.',checked:true},costPremises:{additionalCostDescription:'Associação',cceePercent:'10',cceeBase:'REFERENCE_INVOICE_TOTAL',migrationInvestmentBrl:investment,source:'Custos estimados conferidos para teste.',gdHistoryEstimate:'REFERENCE_RATIO_TOTAL_POINT_REDUCTION',checked:true}});}
function compute(energy='100',investment='100'){const p=proposal(energy,investment);return financialComparison(ref,p,supplierPreview(history,p)) as any;}
describe('Complete simulated financial comparison',()=>{
 it('reconciles every monthly fee and cash balance with investment only at time zero',()=>{const r=compute();expect(r.state).toBe('COMPLETE_SIMULATED');expect(r.rows[0]).toMatchObject({acr:'578.89',aclBeforeFees:'452.89',variableFee:'12.60',aclAfterFees:'475.49',saving:'103.40',cumulative:'3.40',ccee:'57.89'});expect(r.rows[11]).toMatchObject({referenceDocumentary:true,acr:'610.00',saving:'128.60'});expect(r.operatingSavings).toBe('1266.00');expect(r.netCash).toBe('1166.00');expect(r.roiPercent).toBe('1166.00');expect(r.paybackMonths).toBe('0.97');});
 it('reports negative ROI without manufacturing a payback or charging success fees on losses',()=>{const r=compute('1000');expect(Number(r.roiPercent)).toBeLessThan(0);expect(r.paybackMonths).toBeNull();expect(r.paybackState).toBe('NOT_RECOVERED_IN_HORIZON');expect(r.rows.every((m:any)=>m.variableFee==='0.00')).toBe(true);});
 it('does not divide by zero investment or extrapolate past the horizon',()=>{expect(compute('100','0')).toMatchObject({roiPercent:null,paybackState:'NO_INVESTMENT'});expect(compute('100','100000')).toMatchObject({paybackMonths:null,paybackState:'NOT_RECOVERED_IN_HORIZON'});});
 it('blocks missing and ambiguous current TE rather than inheriting old rates',()=>{const p=proposal(),preview=supplierPreview(history,p);expect(financialComparison({...ref,lines:ref.lines.filter(l=>l.kind!=='TE')},p,preview)).toMatchObject({state:'BLOCKED'});expect(financialComparison({...ref,lines:[...ref.lines,ref.lines[3]]},p,preview)).toMatchObject({state:'BLOCKED'});});
 it('suggests only positive common debits and excludes an episodic refund',()=>{expect(financialDraft({...ref,lines:[...ref.lines,{...ref.lines[7],amount:'-20',description:'Ressarcimento'}]})).toMatchObject({sharedMonthlyBrl:'10.00',checked:false});});
 it('requires explicit financial assumptions and rejects injected results',()=>{expect(()=>financialBasis({...proposal().financialBasis,roi:'100'})).toThrow();expect(()=>financialBasis({...proposal().financialBasis,checked:false})).toThrow();const p=proposal();delete p.financialBasis;expect(financialComparison(ref,p,supplierPreview(history,p))).toBeNull();});
});
