import {supplierPreview,supplierProposal} from './acl-supplier-preview';
const history=()=>({sourceDocumentId:'invoice',rows:Array.from({length:12},(_,i)=>({month:new Date(Date.UTC(2025,8+i,1)).toISOString().slice(0,7),peakKwh:String(i+1),offPeakKwh:'1000',demandKw:'200',days:30,page:2,source:'table'}))});
const proposal=()=>({supplier:'Fornecedor teste',energyBrlMwh:'220',startMonth:'2026-11',months:12,fixedMonthlyBrl:'990',savingsPercent:'9.5',losses:'PENDING',taxes:'PENDING',source:'Parâmetros informados para simulação interna, sem contratação.',checked:true});
describe('Supplier seasonal preview',()=>{
 it('aligns seasonal source months and applies R$/MWh to combined kWh exactly',()=>{const r=supplierPreview(history(),proposal());expect(r.rows[0]).toMatchObject({month:'2026-11',sourceMonth:'2025-11',referenceKwh:'1003.000000',energy:'220.66'});expect(r.rows[11]).toMatchObject({month:'2027-10',sourceMonth:'2025-10'});expect(r.fixedFeeSubtotal).toBe('11880.00');expect(r.energySubtotal).toBe('2657.16');});
 it('rounds the single combined energy line instead of summing rounded periods',()=>{const h=history();h.rows.forEach(r=>{r.peakKwh='0.005';r.offPeakKwh='0.005';});const r=supplierPreview(h,{...proposal(),energyBrlMwh:'1000'});expect(r.rows[0].energy).toBe('0.01');expect(r.energySubtotal).toBe('0.12');});
 it('retains actual zero and nine-decimal prices',()=>{const h=history();h.rows.forEach(r=>{r.peakKwh='0';r.offPeakKwh='0';});const r=supplierPreview(h,{...proposal(),energyBrlMwh:'220.123456789',fixedMonthlyBrl:'0'});expect(r.energySubtotal).toBe('0.00');expect(r.fixedFeeSubtotal).toBe('0.00');});
 it('never treats unknown fees, distribution or taxes as zero or publishes savings/ROI',()=>{const r=supplierPreview(history(),proposal());expect(r.partial).toBe(true);for(const k of ['variableFee','totalAclCost','savings','roi','payback'] as const)expect(r[k]).toBeNull();expect(r.rows.every(v=>v.variableFee===null)).toBe(true);expect(r.pending.join(' ')).toContain('Confirmar se perdas');expect(r.pending.join(' ')).toContain('TUSD');});
 it('included/excluded tax and loss declarations change pending items without inventing uplifts',()=>{const a=supplierPreview(history(),{...proposal(),losses:'EXCLUDED',taxes:'INCLUDED'});expect(a.pending.join(' ')).toContain('Quantificar perdas');expect(a.pending.join(' ')).not.toContain('Confirmar se tributos');expect(a.energySubtotal).toBe('2657.16');expect(a.partial).toBe(true);});
 it.each([{checked:false},{months:13},{months:1.5},{months:0},{startMonth:'2026-13'},{supplier:''},{source:'curta'},{energyBrlMwh:'1e3'},{energyBrlMwh:220},{fixedMonthlyBrl:'990,00'},{savingsPercent:'100.1'},{losses:'0'},{taxes:null},{organizationId:'foreign'},{savings:'1000'}])('rejects invalid, unreviewed or forged parameters %s',change=>expect(()=>supplierProposal({...proposal(),...change})).toThrow());
 it('rejects incomplete and forged histories',()=>{const h=history();h.rows.pop();expect(()=>supplierPreview(h,proposal())).toThrow();const other=history();Object.assign(other.rows[0],{cost:'10'});expect(()=>supplierPreview(other,proposal())).toThrow();});
});
