import {invoiceTariffDraft,scenarioDraft} from './acl-scenario-draft';
import type {CpflOperation} from '../ocr/cpfl-paulista-layout';
const field=(text:string,decimal:string|null=null)=>({text,decimal,confidence:null,pages:[1],spans:[{offset:1,length:text.length}],issues:[]});
const row=(desc:string,component:string,rate:string,unit='kWh'):CpflOperation=>({source:desc,row:1,component,period:'UNSPECIFIED',role:'CHARGE',fields:{description:field(desc),grossRate:field(rate,rate),unit:field(unit),quantity:field('100','100'),amount:field('100','100')},issues:[],arithmetic:{state:'MATCH_WITHIN_ONE_CENT',differenceCents:'0'}});
const layout=()=>({layoutId:'cpfl-paulista-a',operations:[row('Consumo Ponta TUSD','TUSD_ENERGY','1.7'),row('Consumo Fora Ponta TUSD','TUSD_ENERGY','0.2'),row('Demanda TUSD','DEMAND_BILLED','21','kW')]});
const model=()=>({id:'study',version:4,hash:'a'.repeat(64),review:null,body:{result:{proposal:{supplier:'AXIA',energyBrlMwh:'275',energyBasis:{baseBrlMwh:'220',lossPercent:'2.5',icmsPercent:'18',method:'LOSS_UPLIFT_ICMS_INSIDE',checked:true},startMonth:'2026-11',months:12,fixedMonthlyBrl:'990',savingsPercent:'9.5',estimatedMonthlyAclBrl:'350',losses:'INCLUDED',taxes:'INCLUDED',source:'Private customer name and address must not be copied.',distribution:{peakBrlKwh:'999',offPeakBrlKwh:'888',demandBrlKw:'777',discountPercent:'50',source:'Private old invoice tariff source.',checked:true},costPremises:{additionalCostDescription:'Contribuição associativa',cceePercent:'9',cceeBase:'REFERENCE_INVOICE_TOTAL',migrationInvestmentBrl:'9300',source:'Private old customer source.',gdHistoryEstimate:'REFERENCE_RATIO_TOTAL_POINT_REDUCTION',checked:true},checked:true}}}});
describe('ACL automatic scenario drafting',()=>{
 it('fills source-backed current tariffs and traces each suggestion',()=>{expect(invoiceTariffDraft(layout(),'newdoc','2026-08')).toMatchObject({values:{peakBrlKwh:'1.7',offPeakBrlKwh:'0.2',demandBrlKw:'21'},pending:[],proof:[{documentId:'newdoc',field:'peakBrlKwh',value:'1.7'},{documentId:'newdoc',field:'offPeakBrlKwh'},{documentId:'newdoc',field:'demandBrlKw'}]});});
 it('does not confuse an explicitly negative GD credit with a consumption tariff',()=>{const l=layout(),credit=row('Energia Atv Inj Fponta TUSD AGO/26','TUSD_ENERGY','0.17');credit.fields.amount=field('-25','-25');l.operations.push(credit);expect(invoiceTariffDraft(l,'doc','2026-08').values.offPeakBrlKwh).toBe('0.2');credit.fields.amount=field('25','25');expect(invoiceTariffDraft(l,'doc','2026-08').values.offPeakBrlKwh).toBe('');});
 it('leaves duplicates, bad arithmetic, missing source and foreign layouts pending instead of copying old rates',()=>{for(const change of [(l:any)=>l.operations.push(l.operations[0]),(l:any)=>l.operations[0].fields.grossRate.spans=[],(l:any)=>l.operations[0].arithmetic.state='DIVERGENT']){const l=layout();change(l);expect(invoiceTariffDraft(l,'doc','2026-08').values.peakBrlKwh).toBe('');}expect(invoiceTariffDraft({...layout(),layoutId:'unknown'},'doc','2026-08').proof).toEqual([]);expect(invoiceTariffDraft(layout(),'doc',null).proof).toEqual([]);});
 it('keeps source-backed suggestions flagged when confidence is missing, but blocks low confidence',()=>{const l=layout();l.operations[0].fields.grossRate.issues=['MISSING_CONFIDENCE'];expect(invoiceTariffDraft(l,'doc','2026-08')).toMatchObject({values:{peakBrlKwh:'1.7'},pending:[expect.stringContaining('confiança')]});l.operations[0].fields.grossRate.issues=['CONFIDENCE_BELOW_45'];expect(invoiceTariffDraft(l,'doc','2026-08').values.peakBrlKwh).toBe('');});
 it('selects taxed demand uniquely and blocks mixed rates without an identified taxed line',()=>{const l=layout();l.operations.push(row('Demanda sem tributos','DEMAND_BILLED','17','kW'));expect(invoiceTariffDraft(l,'doc','2026-08').values.demandBrlKw).toBe('');l.operations[2].fields.icmsBase=field('100','100');l.operations[2].fields.icmsRate=field('18','18');expect(invoiceTariffDraft(l,'doc','2026-08').values.demandBrlKw).toBe('21');});
 it('reuses parameters but never approval, customer text, old rates, results or history',()=>{const m=model(),original=JSON.stringify(m),d=scenarioDraft(m,invoiceTariffDraft(layout(),'newdoc','2026-08'),'newdoc','2026-08');expect(JSON.stringify(m)).toBe(original);expect(d.proposal).toMatchObject({checked:false,energyBasis:{checked:false},costPremises:{checked:false,cceePercent:'9'},distribution:{checked:false,peakBrlKwh:'1.7'}});expect(JSON.stringify(d)).not.toContain('Private');expect(d.reviewRequired).toBe(true);expect(d.pending.join(' ')).toContain('aguarda revisão');expect(d).not.toHaveProperty('savings');expect(d).not.toHaveProperty('rows');});
 it('rejects rejected and malformed models and keeps unavailable tariffs blank',()=>{const m=model();expect(()=>scenarioDraft({...m,review:{decision:'REJECTED'}},null,'doc',null)).toThrow();m.body.result.proposal.energyBasis.icmsPercent='100';expect(()=>scenarioDraft(m,null,'doc',null)).toThrow();expect(scenarioDraft(model(),null,'doc',null).proposal.distribution?.peakBrlKwh).toBe('');});
});
