import {supplierPreview,supplierProposal} from './acl-supplier-preview';
const history=()=>({sourceDocumentId:'invoice',rows:Array.from({length:12},(_,i)=>({month:new Date(Date.UTC(2025,8+i,1)).toISOString().slice(0,7),peakKwh:String(i+1),offPeakKwh:'1000',demandKw:'200',days:30,page:2,source:'table'}))});
const proposal=()=>({supplier:'Fornecedor teste',energyBrlMwh:'220',startMonth:'2026-11',months:12,fixedMonthlyBrl:'990',savingsPercent:'9.5',estimatedMonthlyAclBrl:'350',distribution:null,losses:'PENDING',taxes:'PENDING',source:'Parâmetros informados para simulação interna, sem contratação.',checked:true});
describe('Supplier seasonal preview',()=>{
 it('discounts peak TUSD and measured demand by 50%, keeps off-peak integral and adds the monthly estimate once',()=>{
  const r=supplierPreview(history(),{...proposal(),distribution:{peakBrlKwh:'1',offPeakBrlKwh:'0.1',demandBrlKw:'10',discountPercent:'50',source:'Tarifas-base sem desconto e com fonte revisada.',checked:true}});
  expect(r.rows[0].tusd).toMatchObject({peak:{undiscounted:'3.00',amount:'1.50',discount:'1.50'},offPeak:'100.00',measuredDemand:{undiscounted:'2000.00',amount:'1000.00',discount:'1000.00'}});
  expect(r.rows[0].knownComponentsSubtotal).toBe('2662.16');expect(r.estimatedAdditionalSubtotal).toBe('4200.00');expect(r.knownComponentsSubtotal).toBe('31976.16');expect(r.totalAclCost).toBeNull();expect(r.savings).toBeNull();
 });
 it('allows 100% without discounting commodity energy or off-peak TUSD',()=>{const r=supplierPreview(history(),{...proposal(),distribution:{peakBrlKwh:'1',offPeakBrlKwh:'0.1',demandBrlKw:'10',discountPercent:'100',source:'Tarifas-base anteriores ao desconto informado.',checked:true}});expect(r.rows[0].tusd).toMatchObject({peak:{amount:'0.00'},offPeak:'100.00',measuredDemand:{amount:'0.00'}});expect(r.energySubtotal).toBe('2657.16');expect(r.knownComponentsSubtotal).toBe('19937.16');});
 it('applies discount before rounding and retains nine-place tariffs',()=>{const h=history();h.rows.forEach(v=>v.peakKwh='1');const r=supplierPreview(h,{...proposal(),distribution:{peakBrlKwh:'0.009999999',offPeakBrlKwh:'0',demandBrlKw:'0',discountPercent:'50',source:'Fonte da TUSD para testar arredondamento único.',checked:true}});expect(r.rows[0].tusd?.peak).toMatchObject({undiscounted:'0.01',amount:'0.00'});});
 it.each([{discountPercent:'49.9999'},{discountPercent:'100.0001'},{discountPercent:'1e2'},{checked:false},{offPeakDiscount:'50'},{source:''},{peakBrlKwh:'-1'}])('rejects unsupported discounts and forged off-peak discount %s',change=>expect(()=>supplierProposal({...proposal(),distribution:{peakBrlKwh:'1',offPeakBrlKwh:'0.1',demandBrlKw:'10',discountPercent:'50',source:'Tarifas-base anteriores ao desconto informado.',checked:true,...change}})).toThrow());
 it('keeps distribution pending when missing and rejects nonmonthly/invalid extra costs',()=>{const r=supplierPreview(history(),proposal());expect(r.knownComponentsSubtotal).toBeNull();expect(r.rows[0].tusd).toBeNull();for(const value of [-350,'-350','350,00',null])expect(()=>supplierProposal({...proposal(),estimatedMonthlyAclBrl:value})).toThrow();});
 it('aligns seasonal source months and applies R$/MWh to combined kWh exactly',()=>{const r=supplierPreview(history(),proposal());expect(r.rows[0]).toMatchObject({month:'2026-11',sourceMonth:'2025-11',referenceKwh:'1003.000000',energy:'220.66'});expect(r.rows[11]).toMatchObject({month:'2027-10',sourceMonth:'2025-10'});expect(r.fixedFeeSubtotal).toBe('11880.00');expect(r.energySubtotal).toBe('2657.16');});
 it('rounds the single combined energy line instead of summing rounded periods',()=>{const h=history();h.rows.forEach(r=>{r.peakKwh='0.005';r.offPeakKwh='0.005';});const r=supplierPreview(h,{...proposal(),energyBrlMwh:'1000'});expect(r.rows[0].energy).toBe('0.01');expect(r.energySubtotal).toBe('0.12');});
 it('retains actual zero and nine-decimal prices',()=>{const h=history();h.rows.forEach(r=>{r.peakKwh='0';r.offPeakKwh='0';});const r=supplierPreview(h,{...proposal(),energyBrlMwh:'220.123456789',fixedMonthlyBrl:'0'});expect(r.energySubtotal).toBe('0.00');expect(r.fixedFeeSubtotal).toBe('0.00');});
 it('never treats unknown fees, distribution or taxes as zero or publishes savings/ROI',()=>{const r=supplierPreview(history(),proposal());expect(r.partial).toBe(true);for(const k of ['variableFee','totalAclCost','savings','roi','payback'] as const)expect(r[k]).toBeNull();expect(r.rows.every(v=>v.variableFee===null)).toBe(true);expect(r.pending.join(' ')).toContain('Confirmar se perdas');expect(r.pending.join(' ')).toContain('TUSD');});
 it('included/excluded tax and loss declarations change pending items without inventing uplifts',()=>{const a=supplierPreview(history(),{...proposal(),losses:'EXCLUDED',taxes:'INCLUDED'});expect(a.pending.join(' ')).toContain('Quantificar perdas');expect(a.pending.join(' ')).not.toContain('Confirmar se tributos');expect(a.energySubtotal).toBe('2657.16');expect(a.partial).toBe(true);});
 it.each([{checked:false},{months:13},{months:1.5},{months:0},{startMonth:'2026-13'},{supplier:''},{source:'curta'},{energyBrlMwh:'1e3'},{energyBrlMwh:220},{fixedMonthlyBrl:'990,00'},{savingsPercent:'100.1'},{losses:'0'},{taxes:null},{organizationId:'foreign'},{savings:'1000'}])('rejects invalid, unreviewed or forged parameters %s',change=>expect(()=>supplierProposal({...proposal(),...change})).toThrow());
 it('rejects incomplete and forged histories',()=>{const h=history();h.rows.pop();expect(()=>supplierPreview(h,proposal())).toThrow();const other=history();Object.assign(other.rows[0],{cost:'10'});expect(()=>supplierPreview(other,proposal())).toThrow();});
 it('prices explicit 2.5% losses and 18% ICMS inside exactly, without changing TUSD or extra charges',()=>{
  const d={peakBrlKwh:'1',offPeakBrlKwh:'0.1',demandBrlKw:'10',discountPercent:'50',source:'Tarifas-base já tributadas, sem desconto.',checked:true};
  const basis={baseBrlMwh:'220',lossPercent:'2.5',icmsPercent:'18',method:'LOSS_UPLIFT_ICMS_INSIDE',checked:true};
  const r=supplierPreview(history(),{...proposal(),energyBrlMwh:'275',losses:'INCLUDED',taxes:'INCLUDED',distribution:d,energyBasis:basis});
  const old=supplierPreview(history(),{...proposal(),energyBrlMwh:'275',losses:'INCLUDED',taxes:'INCLUDED',distribution:d});
  expect(r.formulaVersion).toBe('acl-supplier-preview/3');expect(r.rows[0].energy).toBe('275.83');expect(r.energySubtotal).toBe(old.energySubtotal);expect(r.rows[0].tusd).toEqual(old.rows[0].tusd);expect(r.estimatedAdditionalSubtotal).toBe('4200.00');expect(r.proposal.energyBasis).toEqual(basis);expect(r.savings).toBeNull();
 });
 it('rounds the rational monthly energy line only once even when the effective tariff repeats',()=>{
  const h=history();h.rows.forEach(v=>{v.peakKwh='0';v.offPeakKwh='500051';});
  const r=supplierPreview(h,{...proposal(),energyBrlMwh:'0.000009999',losses:'INCLUDED',taxes:'INCLUDED',energyBasis:{baseBrlMwh:'0.000009199',lossPercent:'0',icmsPercent:'8',method:'LOSS_UPLIFT_ICMS_INSIDE',checked:true}});
  // Rounded effective rate would produce 0.005 -> 0.01; exact fraction stays below 0.005.
  expect(r.rows[0].energy).toBe('0.00');expect(r.rows[0].exactEnergy).toBeNull();expect(r.rows[0]).toHaveProperty('energyRational');
 });
 it.each([{icmsPercent:'100'},{icmsPercent:'-18'},{lossPercent:'101'},{lossPercent:2.5},{method:'ICMS_OUTSIDE'},{checked:false},{baseBrlMwh:'1e3'},{extra:'forged'}])('rejects invalid structured energy premises %s',change=>expect(()=>supplierProposal({...proposal(),energyBrlMwh:'275',losses:'INCLUDED',taxes:'INCLUDED',energyBasis:{baseBrlMwh:'220',lossPercent:'2.5',icmsPercent:'18',method:'LOSS_UPLIFT_ICMS_INSIDE',checked:true,...change}})).toThrow());
 it('rejects forged effective prices and ambiguous included/excluded declarations',()=>{
  const b={baseBrlMwh:'220',lossPercent:'2.5',icmsPercent:'18',method:'LOSS_UPLIFT_ICMS_INSIDE',checked:true};
  for(const change of [{energyBrlMwh:'220'},{losses:'EXCLUDED'},{taxes:'PENDING'}])expect(()=>supplierProposal({...proposal(),energyBrlMwh:'275',losses:'INCLUDED',taxes:'INCLUDED',energyBasis:b,...change})).toThrow();
  expect(()=>supplierProposal({...proposal(),energyBasis:null})).toThrow();
 });
});
