import {auditAuthorNames} from './audit-author-names';
function db(data:Record<string,any[]>,fail=false){const calls:any[]=[];return {calls,from:(table:string)=>{const state:any={};const q:any={select:(columns:string)=>{calls.push([table,columns]);return q;},eq:(key:string,value:string)=>{state[key]=value;return q;},in:async(key:string,ids:string[])=>{calls.push([table,key,ids]);if(fail)throw Error('unavailable');return {error:null,data:(data[table]??[]).filter(r=>ids.includes(r[key])&&Object.entries(state).every(([k,v])=>r[k]===v))};}};return q;}};}
const actor=(org:string,id:string,name:string,role='gestor')=>({organization_id:org,user_id:id,display_name:name,roles:{name:role},affiliation_type:'internal'});
describe('audit read identity and historical isolation',()=>{
 it('resolves requester, responsible and event author by distinct original IDs',async()=>{const input={organization_id:'a',created_by:'creator',responsible_id:'owner',actor_id:'editor',requested_by_name:'Nome original'};const [r]=await auditAuthorNames(db({organization_members:[actor('a','creator','Ana'),actor('a','owner','Bruno'),actor('a','editor','Carla')]}),'a',[input]);expect(r.auditIdentities.created_by.currentName).toBe('Ana');expect(r.auditIdentities.responsible_id.currentName).toBe('Bruno');expect(r.auditIdentities.actor_id.currentName).toBe('Carla');expect(r.auditIdentities.created_by.recordedName).toBe('Nome original');});
 it('uses revision owner, not current owner, and does not mutate signed input',async()=>{const r={organization_id:'a',created_by:'creator',responsible_id:'new',body:{payload_hash:'untouched'},snapshot:{organization_id:'a',responsible_id:'old'}};const before=JSON.stringify(r);const [result]=await auditAuthorNames(db({organization_members:[actor('a','new','Novo'),actor('a','old','Anterior')]}),'a',[r]);expect(result.snapshot.auditIdentities.responsible_id.currentName).toBe('Anterior');expect(result.auditIdentities.responsible_id.currentName).toBe('Novo');expect(JSON.stringify(r)).toBe(before);expect(result.body).toBe(r.body);});
 it('separates original recorded name from renamed directory label',async()=>{const [r]=await auditAuthorNames(db({organization_members:[actor('a','id','Novo Nome')]}),'a',[{organization_id:'a',actor_id:'id',actor_name:'Nome Antigo'}]);expect(r.auditIdentities.actor_id).toMatchObject({recordedName:'Nome Antigo',currentName:'Novo Nome'});expect(r.actor_name).toBe('Nome Antigo');});
 it('isolates membership roles for the same user in two organizations',async()=>{const directory=db({organization_members:[actor('a','id','Ana A','gestor'),actor('b','id','Ana B','admin_org')]});const [r]=await auditAuthorNames(directory,'a',[{organization_id:'a',actor_id:'id'}]);expect(r.auditIdentities.actor_id.currentRole).toBe('gestor');expect(JSON.stringify(r)).not.toContain('Ana B');});
 it('never resolves a foreign snapshot or foreign top-level record',async()=>{const directory=db({organization_members:[actor('b','secret','Segredo')]});const [r]=await auditAuthorNames(directory,'a',[{organization_id:'b',actor_id:'secret',snapshot:{organization_id:'a',actor_id:'secret'}}]);expect(directory.calls).toHaveLength(0);expect(r.auditIdentities).toEqual({});expect(r.snapshot.auditIdentities).toEqual({});});
 it('keeps historical record available when the directory is down',async()=>{const [r]=await auditAuthorNames(db({},true),'a',[{organization_id:'a',actor_id:'id',actor_name:'Nome registrado'}]);expect(r.auditIdentities.actor_id).toMatchObject({recordedName:'Nome registrado',currentName:null,lookup:'UNAVAILABLE'});expect(r.actor_id).toBe('id');});
 it('does not substitute role labels for a missing personal name',async()=>{const [r]=await auditAuthorNames(db({}),'a',[{organization_id:'a',actor_id:'id',actor_name:'Consultor'}]);expect(r.auditIdentities.actor_id).toMatchObject({recordedName:null,currentName:null,lookup:'MISSING'});});
 it('does not expose role, affiliation or linked client in client message projections',async()=>{const directory=db({organization_members:[{...actor('a','id','Ana'),exclusive_customer_id:'other'}]});const [r]=await auditAuthorNames(directory,'a',[{organization_id:'a',actor_id:'id',customer_id:'client'}],{includeContext:false});expect(r.auditIdentities.actor_id).toMatchObject({currentName:'Ana',currentRole:null,currentAffiliation:null,currentCustomer:null});expect(directory.calls.some(c=>c[0]==='customers')).toBe(false);expect(r.auditCompany).toBeUndefined();});
 it('does not disclose another client linked to the event actor',async()=>{const [r]=await auditAuthorNames(db({organization_members:[{...actor('a','id','Ana'),exclusive_customer_id:'secret'}],customers:[{organization_id:'a',id:'secret',company_name:'Secret'}]}),'a',[{organization_id:'a',actor_id:'id',customer_id:'authorized'}]);expect(r.auditIdentities.actor_id.currentCustomer).toBeNull();expect(JSON.stringify(r)).not.toContain('Secret');});
});
