import {auditAuthorNames} from './audit-author-names';
const row={organization_id:'org-a',created_by:'author',updated_by:'editor',validated_by:'validator',status:'VALIDATED'};
function directory(members:any[]=[],profiles:any[]=[],fail=false){const calls:any[]=[];return {calls,from:(table:string)=>{const q:any={select:(value:string)=>{calls.push([table,value]);return q;},eq:(key:string,value:string)=>{calls.push([key,value]);return q;},in:async(key:string,ids:string[])=>{calls.push([table,key,ids]);if(fail)throw Error('offline');return {data:table==='organization_members'?members:profiles,error:null};}};return q;}};}
describe('audit author labels',()=>{
 it('uses tenant display name then referenced profile, without emails or foreign names',async()=>{const db=directory([{organization_id:'org-a',user_id:'author',display_name:' Ana '},{organization_id:'org-b',user_id:'editor',display_name:'Foreign'}],[{user_id:'author',name:'Global Ana'},{user_id:'editor',name:'Bruno'},{user_id:'validator',name:'Carla'},{user_id:'stranger',name:'Secret'}]);const [r]=await auditAuthorNames(db,'org-a',[row]);expect(r).toMatchObject({...row,created_by_name:'Ana',updated_by_name:'Bruno',validated_by_name:'Carla'});expect(JSON.stringify(r)).not.toMatch(/Secret|Foreign|Global Ana/);expect(db.calls).toContainEqual(['organization_id','org-a']);expect(db.calls.some(c=>String(c[1]).includes('email'))).toBe(false);});
 it('enriches history without mutating snapshots or actor ids',async()=>{const original={organization_id:'org-a',snapshot:{...row}};const before=JSON.stringify(original);const [event]=await auditAuthorNames(directory([],[{user_id:'author',name:'Ana'}]),'org-a',[original]);expect(event.snapshot.created_by_name).toBe('Ana');expect(event.snapshot.created_by).toBe('author');expect(JSON.stringify(original)).toBe(before);});
 it('does not resolve foreign records or foreign snapshots',async()=>{const db=directory([],[{user_id:'author',name:'Secret'}]);const [event]=await auditAuthorNames(db,'org-a',[{organization_id:'org-b',...{created_by:'author'},snapshot:{...row,organization_id:'org-b'}}]);expect(db.calls).toEqual([]);expect(event.created_by_name).toBeNull();expect(event.snapshot.created_by_name).toBeNull();});
 it('keeps records on lookup failure and missing/deleted users',async()=>{for(const db of [directory([],[],true),directory()]){const [r]=await auditAuthorNames(db,'org-a',[row]);expect(r.created_by).toBe('author');expect(r.created_by_name).toBeNull();expect(r.status).toBe('VALIDATED');}});
 it('supports platform actors without membership and filters unexpected profile ids',async()=>{const [r]=await auditAuthorNames(directory([],[{user_id:'author',name:'Administrador da plataforma'},{user_id:'unrelated',name:'Private'}]),'org-a',[row]);expect(r.created_by_name).toBe('Administrador da plataforma');expect(JSON.stringify(r)).not.toContain('Private');});
 it('batches and de-duplicates names',async()=>{const db=directory();await auditAuthorNames(db,'org-a',Array.from({length:205},(_,i)=>({organization_id:'org-a',created_by:'a'+i,updated_by:'a'+i})));const batches=db.calls.filter(c=>c[0]==='user_profiles'&&Array.isArray(c[2]));expect(batches.map(c=>c[2].length)).toEqual([100,100,5]);});
 it('rejects blank and UUID display names as labels',async()=>{const [r]=await auditAuthorNames(directory([],[{user_id:'author',name:' '},{user_id:'editor',name:'8039dae4-1c8e-4032-8a9a-d647b1644f16'}]),'org-a',[row]);expect(r.created_by_name).toBeNull();expect(r.updated_by_name).toBeNull();});
});
