import {FinancialSettlementsService} from './financial-settlements.service';
import {reviewDigest} from './review-snapshots.service';
import {PERMISSIONS as P} from '../../../common/constants/permissions';
const org='org',customer='c355d5a0-e672-4110-ac17-05c4ce734df7',period={from:'2026-08',to:'2026-08'};
const tenant={organizationId:org,userId:'actor',role:'consulta',roleId:'role',email:'',permissions:[P.DOCUMENTS_REPORTS_VIEW]};
const member={organization_id:org,user_id:'actor',role_id:'role',status:'active',affiliation_type:'external',exclusive_customer_id:customer,roles:{id:'role',name:'consulta',scope:'organization',organization_id:org,permissions:[P.DOCUMENTS_REPORTS_VIEW]}};
function fixture(options:any={}){
 const financial={status:'AVAILABLE',acr:'41944.00',aclBeforeFees:'36142.79',totalFees:'1600.00',aclAfterFees:'37742.79',savingsBeforeFees:'5801.21',savingsAfterFees:'4201.21',units:[{id:'u',name:'Bonfim'}]};
 const payload={formatVersion:'financial-settlement-1.0',sources:{organizationId:org,customerId:customer,month:'2026-08',tables:{customers:[{id:customer,company_name:'Cenourão'}]}},financial,reservations:['INTERNAL OCR/CNPJ audit']};
 const rows:any[]=[{organization_id:org,customer_id:customer,consumer_unit_id:'u',month:'2026-08-01',version_number:2,status:'PUBLISHED',validation_status:'VALIDATED',financial_format:'financial-settlement-1.0',financial_group_id:'group',financial_hash:reviewDigest(payload),financial_payload:payload,financial_reservations:payload.reservations,approved_at:'2026-10-02T15:14:34Z',published_at:'2026-10-02T15:14:52Z',published_by:'manager',publication_note:'INTERNAL publication note'}];
 let members=0;const filters:any[]=[];
 const db={getClient:()=>({from:(table:string)=>{const conditions:any[]=[];const q:any={};for(const m of ['select','order','limit'])q[m]=()=>q;for(const m of ['eq','is','gte','lte'])q[m]=(k:string,v:any)=>{conditions.push([m,k,v]);filters.push([table,m,k,v]);return q;};q.maybeSingle=async()=>({error:null,data:table==='organization_members'?{...member,...options.member,...(++members>1?options.changedMember:{} )}:table==='customers'?{id:customer,organization_id:org,status:'ACTIVE',...options.customer}:null});q.then=(resolve:any)=>Promise.resolve({error:null,data:rows.filter(r=>conditions.every(([m,k,v])=>m==='gte'?r[k]>=v:m==='lte'?r[k]<=v:r[k]===v))}).then(resolve);return q;}})};
 const licenses={requireEntitlement:jest.fn(async()=>{if(options.licenseDenied)throw Error('Licence denied');})};return {service:new FinancialSettlementsService(db as any,licenses as any),filters,licenses};
}
describe('client published financial portal',()=>{
 it('derives customer on server and projects signed figures without internal notes or sources',async()=>{const f=fixture(),r=await f.service.portalFinancial(period,tenant);expect(r).toMatchObject({audience:'client',customerId:customer,publicationCount:1,totals:{acr:'41944.00',savingsAfterFees:'4201.21'}});expect(r.rows[0].publicationNote).toBe('');expect(r.rows[0].reservations[0]).toContain('ressalvas');expect(JSON.stringify(r)).not.toMatch(/INTERNAL|financial_payload|preparations|createdBy/);expect(f.filters).toContainEqual(['monthly_energy_settlements','eq','customer_id',customer]);expect(f.filters).toContainEqual(['monthly_energy_settlements','eq','organization_id',org]);expect(f.filters).toContainEqual(['monthly_energy_settlements','eq','status','PUBLISHED']);expect(f.licenses.requireEntitlement).toHaveBeenCalledWith(org,'free_market_management');});
 it.each([{...period,customerId:customer},{...period,organizationId:'other'},{from:'2026-09',to:'2026-08'}])('rejects scope override or invalid dates %j',async q=>{await expect(fixture().service.portalFinancial(q as any,tenant)).rejects.toThrow();});
 it.each([{user_id:'other'},{organization_id:'other'},{role_id:'other'},{status:'inactive'},{affiliation_type:'internal'},{exclusive_customer_id:null},{roles:{...member.roles,scope:'global'}},{roles:{...member.roles,permissions:[]}}])('denies invalid or revoked member %j',async patch=>{const f=fixture({member:patch});await expect(f.service.portalFinancial(period,tenant)).rejects.toThrow();expect(f.filters.some(r=>r[0]==='monthly_energy_settlements')).toBe(false);});
 it.each([{role:'admin_org'},{permissions:[]},{accessMode:'platform_operation'}])('client endpoint cannot impersonate another audience %j',async patch=>{await expect(fixture().service.portalFinancial(period,{...tenant,...patch} as any)).rejects.toThrow();});
 it.each([{status:'INACTIVE'},{organization_id:'foreign'},{id:'foreign'}])('rejects inactive or foreign customer %j',async customer=>{await expect(fixture({customer}).service.portalFinancial(period,tenant)).rejects.toThrow();});
 it('requires current licence',async()=>{await expect(fixture({licenseDenied:true}).service.portalFinancial(period,tenant)).rejects.toThrow('Licence');});
 it.each([{exclusive_customer_id:'other'},{status:'inactive'},{roles:{...member.roles,permissions:[]}}])('fails closed when binding or permission changes during read %j',async changedMember=>{await expect(fixture({changedMember}).service.portalFinancial(period,tenant)).rejects.toThrow();});
 it.each([{exclusive_customer_id:null},{affiliation_type:'internal'}])('shared or internal consulta remains backoffice %j',async patch=>{expect(await fixture({member:patch}).service.portalAccess(tenant)).toMatchObject({audience:'backoffice'});});
 it('explicit external binding redirects to client portal',async()=>{expect(await fixture().service.portalAccess(tenant)).toMatchObject({audience:'client'});});
 it('manager preview uses same projection without granting access',async()=>{const f=fixture(),r=await f.service.portalPreview({...period,customerId:customer},{...tenant,role:'gestor',permissions:[P.ORGANIZATION_CONTRACTS_VIEW]});expect(r.audience).toBe('client');expect(JSON.stringify(r)).not.toContain('INTERNAL');});
 it.each(['operacional','consulta'])('denies preview to %s',async role=>{await expect(fixture().service.portalPreview({...period,customerId:customer},{...tenant,role,permissions:[P.ORGANIZATION_CONTRACTS_VIEW]})).rejects.toThrow();});
 it('does not preview all customers implicitly',async()=>{await expect(fixture().service.portalPreview(period,{...tenant,role:'gestor'})).rejects.toThrow('Selecione');});
});

