import {Injectable,BadRequestException,NotFoundException,ConflictException,InternalServerErrorException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {ContractsService} from './contracts.service';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {ManagementDto,PricePeriodDto,ServiceAgreementDto} from '../dto/configurations.dto';
@Injectable()
export class ContractConfigurationsService {
 constructor(private db:SupabaseService,private licenses:LicensesService,private contracts:ContractsService){}
 private table(name:string){return this.db.getClient().from(name);}
 private fail(error:any){if(!error)return;if(['23505','P3274'].includes(error.code))throw new ConflictException(error.code==='23505'?'Já existe um contrato com este número.':'Já existe uma vigência para esse período. Não é permitido sobrepor o histórico.');if(error.code==='P3271')throw new ConflictException('O histórico não pode ser sobrescrito. Registre uma nova vigência.');if(error.code==='P3272')throw new NotFoundException('Cliente, unidade ou contrato indisponível nesta organização.');if(['P3273','23514','22003','22P02'].includes(error.code))throw new BadRequestException('Confira os valores e as datas da configuração.');throw new InternalServerErrorException('Não foi possível salvar ou consultar a configuração.');}
 private period(dto:{startDate:string;endDate:string}){if(dto.endDate<dto.startDate)throw new BadRequestException('O término deve ser igual ou posterior ao início.');}
 private async customer(id:string,org:string){const r=await this.table('customers').select('id').eq('id',id).eq('organization_id',org).is('deleted_at',null).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Cliente não encontrado nesta organização.');}
 async listManagement(org:string){await this.licenses.requireEntitlement(org,'free_market_management');const r=await this.table('management_contracts').select('*').eq('organization_id',org);this.fail(r.error);return r.data;}
 async createManagement(input:ManagementDto,org:string){await this.licenses.requireEntitlement(org,'free_market_management');const dto=await validateWriteDto(ManagementDto,input);this.period(dto);if(dto.remunerationModel==='FIXED'&&dto.savingsPercentage!==0)throw new BadRequestException('Honorário fixo deve ter percentual zero.');await this.customer(dto.customerId,org);const r=await this.table('management_contracts').insert([{organization_id:org,customer_id:dto.customerId,contract_number:dto.contractNumber,remuneration_model:dto.remunerationModel,fixed_fee_monthly:dto.fixedFeeMonthly,savings_percentage:dto.savingsPercentage,start_date:dto.startDate,end_date:dto.endDate,application_rules:dto.applicationRules,status:'ACTIVE'}]).select().single();this.fail(r.error);return r.data;}
 async prices(id:string,org:string){await this.contracts.findOne(id,org);const r=await this.table('contract_price_history').select('*').eq('contract_id',id);this.fail(r.error);return r.data;}
 async addPrice(id:string,input:PricePeriodDto,org:string){const dto=await validateWriteDto(PricePeriodDto,input);this.period(dto);const parent=await this.contracts.findOne(id,org);if(!['ACTIVE','APPROVED'].includes(parent.status)||!['ENERGY_PURCHASE','ENERGY_SALE'].includes(parent.contract_type))throw new ConflictException('Ative um contrato de energia antes de registrar preços por vigência.');if(dto.startDate<String(parent.start_date).slice(0,10)||dto.endDate>String(parent.end_date).slice(0,10))throw new BadRequestException('O período de preço deve estar dentro da vigência do contrato.');const r=await this.table('contract_price_history').insert([{contract_id:id,start_date:dto.startDate,end_date:dto.endDate,price_per_mwh:dto.pricePerMwh,reason:dto.reason}]).select().single();this.fail(r.error);return r.data;}
 async listServices(org:string){await this.licenses.requireEntitlement(org,'free_market_management');const r=await this.table('service_agreements').select('*').eq('organization_id',org);this.fail(r.error);return r.data;}
 async createService(input:ServiceAgreementDto,org:string){await this.licenses.requireEntitlement(org,'free_market_management');const dto=await validateWriteDto(ServiceAgreementDto,input);this.period(dto);if(dto.billingBasis!=='CUSTOM'&&dto.agreedValue==null)throw new BadRequestException('Informe o valor contratado para a base de cobrança.');if(dto.billingBasis==='PERCENTAGE'&&(dto.agreedValue??0)>100)throw new BadRequestException('O percentual deve estar entre zero e cem.');await this.customer(dto.customerId,org);if(dto.consumerUnitId){const u=await this.table('consumer_units').select('id').eq('id',dto.consumerUnitId).eq('customer_id',dto.customerId).eq('organization_id',org).maybeSingle();this.fail(u.error);if(!u.data)throw new NotFoundException('Unidade não encontrada neste cliente.');}const r=await this.table('service_agreements').insert([{organization_id:org,customer_id:dto.customerId,consumer_unit_id:dto.consumerUnitId||null,agreement_type:dto.agreementType,contract_number:dto.contractNumber,counterparty:dto.counterparty,description:dto.description,billing_basis:dto.billingBasis,agreed_value:dto.agreedValue??null,application_rules:dto.applicationRules,start_date:dto.startDate,end_date:dto.endDate}]).select().single();this.fail(r.error);return r.data;}
}
