import 'reflect-metadata';
import {costAbsences} from './cost-absence';
import {monthlyCostLedger} from './monthly-cost-ledger';
import {additionalCostSubtotal} from './additional-cost-subtotal';
import {CostAbsenceDto} from '../dto/monthly-costs.dto';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {MonthlyCostsService} from './monthly-costs.service';
import {MonthlyCostsController} from '../controllers/monthly-costs.controller';
import {PERMISSIONS_KEY} from '../../../common/decorators/require-permission.decorator';
import {PERMISSIONS as P} from '../../../common/constants/permissions';
const u={id:'u',organization_id:'o',customer_id:'c',tariff_group:'A',free_market:true};
const item={id:'10000000-0000-4000-8000-000000000001',label:'Ajuste',category:'DISTRIBUTOR_ADJUSTMENT',scenario:'ACL',effect:'CREDIT',amount:'74.53',source:'Fatura original',taxTreatment:'INCLUDED'};
const cost={id:'cost',organization_id:'o',customer_id:'c',consumer_unit_id:'u',month:'2026-08',version:1,revision:2,status:'VALIDATED',validated_at:'2026-10-01',validated_by:'actor',source_reference:'Fatura',unit_context:u,costs:{noCosts:false,items:[item]}};
const d={id:'d',organization_id:'o',customer_id:'c',consumer_unit_id:'u',month:'2026-08',scenario:'ACR',absent:true,version:1,cost_id:'cost',cost_revision:2,unit_context:u,source_reference:'Fatura e biblioteca',reason:'ACR segue biblioteca sem subsídios ACL.',created_by:'actor',created_at:'2026-10-01'};
const read=(costs:any[]=[cost],rows:any[]=[d])=>costAbsences(u,'2026-08',costs,rows);
describe('scenario cost absence',()=>{
 it('preserves ACL credits and declares only ACR zero',()=>{const before=JSON.stringify(cost);const ledger=monthlyCostLedger(u,'2026-08',[cost],'ADDITIONAL',[d]);const result=additionalCostSubtotal(ledger);expect(result.scenarios[0]).toMatchObject({status:'DECLARED_ZERO',balance:'0.00',declaration:{id:'d'}});expect(result.scenarios[1]).toMatchObject({status:'AVAILABLE',balance:'-74.53'});expect(JSON.stringify(cost)).toBe(before);});
 it('does not approve draft supplier or unblock ACL',()=>{const draft={...cost,id:'draft',version:2,revision:1,status:'DRAFT',costs:{noCosts:false,items:[item,{...item,id:'supplier',category:'SUPPLIER_INVOICE',effect:'COST',taxTreatment:'UNSPECIFIED',amount:'46748.42'}]}};const declaration={...d,cost_id:'draft',cost_revision:1};const ledger=monthlyCostLedger(u,'2026-08',[cost,draft],'ADDITIONAL',[declaration]);expect(ledger.status).toBe('BLOCKED');expect(additionalCostSubtotal(ledger).scenarios.map(s=>s.status)).toEqual(['DECLARED_ZERO','BLOCKED']);expect(monthlyCostLedger(u,'2026-08',[cost,draft],'SUPPLIER',[declaration]).absences).toEqual([]);expect(draft.status).toBe('DRAFT');});
 it('allows independent declaration when there are no cost versions',()=>expect(read([],[{...d,cost_id:null,cost_revision:null}])).toHaveLength(1));
 it.each(['organization_id','customer_id','consumer_unit_id','month'])('isolates %s',key=>expect(read([cost],[{...d,[key]:'other'}])).toEqual([]));
 it.each([{cost_revision:3},{cost_id:'other'},{reason:''},{reason:undefined},{created_by:''},{source_reference:''},{unit_context:{...u,free_market:false}},{absent:false},{version:0}])('rejects stale or malformed declaration %p',patch=>expect(read([cost],[{...d,...patch}])).toEqual([]));
 it('does not resurrect a revoked declaration',()=>expect(read([cost],[d,{...d,id:'new',version:2,absent:false}])).toEqual([]));
 it('does not resurrect an older valid declaration when the latest is stale',()=>expect(read([cost],[d,{...d,id:'new',version:2,cost_revision:3}])).toEqual([]));
 it('blocks conflicting ACR entries even zero amounts',()=>expect(read([{...cost,costs:{noCosts:false,items:[{...item,scenario:'ACR',category:'OTHER',amount:'0'}]}}])).toEqual([]));
 it('blocks removal of approved ACR costs through an unapproved draft',()=>{const draft={...cost,id:'draft',version:2,revision:1,status:'DRAFT'};expect(read([{...cost,costs:{noCosts:false,items:[{...item,scenario:'ACR',category:'OTHER'}]}},draft],[{...d,cost_id:'draft',cost_revision:1}])).toEqual([]);});
 it('requires reconfirmation after any cost revision',()=>expect(read([{...cost,revision:3}])).toEqual([]));
 it('does not infer missing scenarios as zero',()=>expect(additionalCostSubtotal(monthlyCostLedger(u,'2026-08',[cost])).scenarios[0].status).toBe('BLOCKED'));
 it('rejects client actor injection',async()=>{await expect(validateWriteDto(CostAbsenceDto,{consumerUnitId:item.id,month:'2026-08',scenario:'ACR',absent:true,sourceReference:'Fatura',reason:d.reason,created_by:'fake'} as any)).rejects.toThrow();});
 it('requires a reviewer role',async()=>{const service=new MonthlyCostsService({} as any,{} as any);await expect(service.declareAbsence({} as any,{role:'operador'} as any)).rejects.toMatchObject({status:403});});
 it('protects write and read routes',()=>{expect(Reflect.getMetadata(PERMISSIONS_KEY,MonthlyCostsController.prototype.declareAbsence)).toEqual([P.ORGANIZATION_CONTRACTS_UPDATE]);expect(Reflect.getMetadata(PERMISSIONS_KEY,MonthlyCostsController.prototype.absences)).toEqual([P.ORGANIZATION_CONTRACTS_VIEW]);});
});
