import {CalculationPreparationService} from './preparation.service';
import {ForbiddenException} from '@nestjs/common';
const org='org',customerId='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',month='2026-08';
function setup(count=1){
 const data:Record<string,any[]>={customers:[{id:customerId,organization_id:org,deleted_at:null}],consumer_units:Array.from({length:count},(_,i)=>({id:i===0?id:'22222222-2222-4222-8222-'+String(i).padStart(12,'0'),organization_id:org,customer_id:customerId,name:'Unidade '+i})),management_contracts:[],management_fee_allocations:[]};const calls:any[]=[];
 const db={getClient:()=>({from:(table:string)=>{const filters:any[]=[];const rows=()=>data[table].filter(r=>filters.every(([k,v])=>r[k]===v));const q:any={select:jest.fn(()=>q),eq:(k:string,v:any)=>{filters.push([k,v]);return q;},is:(k:string,v:any)=>{filters.push([k,v]);return q;},order:()=>q,range:async(start:number,end:number)=>{calls.push({table,filters:[...filters],start,end});return {data:rows().slice(start,end+1),error:null};},maybeSingle:async()=>{calls.push({table,filters:[...filters]});return {data:rows()[0]??null,error:null};}};return q;}})};
 const licenses={requireEntitlement:jest.fn(async()=>undefined)},service=new CalculationPreparationService(db as any,licenses as any);
 const inspect=jest.spyOn(service,'inspect').mockImplementation(async d=>({unit:{id:d.consumerUnitId},month:d.month,checkedAt:'2026-09-01',operationalComposition:{formulaVersion:'operational-composition-1.0',rounding:'SUM_ROUNDED_LINES',warnings:[],scenarios:[]}} as any));
 return {data,calls,service,inspect,licenses};
}
describe('customer preparation scoped orchestration',()=>{
 it('loads every unit using tenant/customer filters and delegates to existing checked unit preparation',async()=>{const x=setup(2);x.data.consumer_units.push({id:'foreign',organization_id:'other',customer_id:customerId});const r=await x.service.inspectCustomer({customerId,month},org);expect(r.unitCount).toBe(2);expect(x.inspect).toHaveBeenCalledTimes(2);expect(x.inspect).toHaveBeenCalledWith({consumerUnitId:id,month},org);for(const c of x.calls){expect(c.filters).toContainEqual(['organization_id',org]);if(c.table!=='customers')expect(c.filters).toContainEqual(['customer_id',customerId]);}expect(x.licenses.requireEntitlement).toHaveBeenCalledWith(org,'free_market_management');});
 it('checks active customer in same organization',async()=>{const x=setup();x.data.customers[0].organization_id='other';await expect(x.service.inspectCustomer({customerId,month},org)).rejects.toThrow('Cliente indisponível');expect(x.inspect).not.toHaveBeenCalled();});
 it('rejects deleted customer',async()=>{const x=setup();x.data.customers[0].deleted_at='2026-08-01';await expect(x.service.inspectCustomer({customerId,month},org)).rejects.toThrow('Cliente indisponível');});
 it('rejects invalid DTO before reads',async()=>{const x=setup();await expect(x.service.inspectCustomer({customerId,month:'2026-13'},org)).rejects.toThrow();expect(x.calls).toHaveLength(0);});
 it('honors license gate before database reads',async()=>{const x=setup();x.licenses.requireEntitlement.mockRejectedValue(new ForbiddenException());await expect(x.service.inspectCustomer({customerId,month},org)).rejects.toThrow();expect(x.calls).toHaveLength(0);});
 it('never emits partial result after unit query failure',async()=>{const x=setup(2);x.inspect.mockRejectedValueOnce(new Error('Fonte indisponível'));await expect(x.service.inspectCustomer({customerId,month},org)).rejects.toThrow('Fonte indisponível');});
 it('detects unit list change while preparing',async()=>{const x=setup();x.inspect.mockImplementation(async d=>{x.data.consumer_units.push({...x.data.consumer_units[0],id:'33333333-3333-4333-8333-333333333333'});return {month:d.month,checkedAt:'2026-09-01',operationalComposition:{scenarios:[]}} as any;});await expect(x.service.inspectCustomer({customerId,month},org)).rejects.toThrow('cadastro de unidades mudou');});
 it('caps synchronous workload without truncating units silently',async()=>{const x=setup(201);await expect(x.service.inspectCustomer({customerId,month},org)).rejects.toThrow('até 100 unidades');expect(x.inspect).not.toHaveBeenCalled();expect(x.calls.filter(c=>c.table==='consumer_units').map(c=>c.start)).toEqual([0,200]);});
 it('empty unit set returns blocked rather than zero',async()=>{const x=setup(0);const r=await x.service.inspectCustomer({customerId,month},org);expect(r.status).toBe('BLOCKED');expect(r.acr).toBeNull();});
});
