import {Injectable,BadRequestException,NotFoundException,ConflictException,InternalServerErrorException,UnauthorizedException,ForbiddenException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {ConsumerUnitsService} from '../../consumer-units/services/consumer-units.service';
import {ContractsService} from './contracts.service';
import {ContractConfigurationsService} from './configurations.service';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {TenantContext} from '../../../common/interfaces/tenant-context.interface';
import {PERMISSIONS as P} from '../../../common/constants/permissions';
import {EntryDraftDto,UpdateEntryDraftDto,EntryRevisionDto} from '../dto/entry-drafts.dto';
import {entryPayload,entryIssues,entryTables} from './entry-drafts';
@Injectable()
export class EntryDraftService {
 constructor(private db:SupabaseService,private licenses:LicensesService,private units:ConsumerUnitsService,private contracts:ContractsService,private configurations:ContractConfigurationsService){}
 private table(name='contract_entry_drafts'){return this.db.getClient().from(name);}
 private fail(e:any){if(!e)return;if(['23505','P3802'].includes(e.code))throw new ConflictException('O lançamento mudou ou já foi registrado. Atualize a lista.');if(['23514','P3801'].includes(e.code))throw new BadRequestException('Confira os dados do lançamento.');throw new InternalServerErrorException('Não foi possível acessar os lançamentos.');}
 private async allowed(t:TenantContext){if(!t.organizationId||!t.userId)throw new UnauthorizedException();await this.licenses.requireEntitlement(t.organizationId,'free_market_management');}
 private writePermission(kind:string,t:TenantContext){if(kind==='distributor'&&!t.permissions.includes(P.ORGANIZATION_CONSUMER_UNITS_CREATE))throw new ForbiddenException('O cadastro de distribuidora exige permissão para criar unidades.');}
 private async customer(id:string,t:TenantContext){const r=await this.table('customers').select('id').eq('id',id).eq('organization_id',t.organizationId).is('deleted_at',null).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Cliente indisponível nesta organização.');}
 private async mapped(d:EntryDraftDto,t:TenantContext){this.writePermission(d.kind,t);await this.customer(d.customerId,t);if(JSON.stringify(d.payload).length>100000)throw new BadRequestException('Lançamento muito extenso.');const payload=entryPayload(d.kind,d.customerId,d.payload);if(payload.consumerUnitId){const r=await this.table('consumer_units').select('id').eq('id',payload.consumerUnitId).eq('customer_id',d.customerId).eq('organization_id',t.organizationId).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Selecione uma unidade deste cliente.');}const deferred_steps=[...new Set(d.deferredSteps||[])];const issues=[...entryIssues(d.kind,payload),...deferred_steps.map(n=>'step:'+n)];return {payload,deferred_steps,issues,status:issues.length?'INCOMPLETE':'DRAFT',updated_by:t.userId};}
 async list(t:TenantContext){await this.allowed(t);const r=await this.table().select('*').eq('organization_id',t.organizationId).neq('status','REGISTERED').order('updated_at',{ascending:false}).range(0,999);this.fail(r.error);if(!Array.isArray(r.data)||r.data.length>=1000)throw new InternalServerErrorException('Consulta extensa; a lista não foi truncada.');return r.data;}
 private async one(id:string,t:TenantContext){await this.allowed(t);const r=await this.table().select('*').eq('id',id).eq('organization_id',t.organizationId).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Lançamento não encontrado.');return r.data;}
 async create(input:EntryDraftDto,t:TenantContext){await this.allowed(t);const d=await validateWriteDto(EntryDraftDto,input),data=await this.mapped(d,t);const r=await this.table().insert([{...data,organization_id:t.organizationId,customer_id:d.customerId,kind:d.kind,created_by:t.userId}]).select().single();this.fail(r.error);return r.data;}
 async update(id:string,input:UpdateEntryDraftDto,t:TenantContext){const d=await validateWriteDto(UpdateEntryDraftDto,input),old=await this.one(id,t);if(old.kind!==d.kind||old.customer_id!==d.customerId||old.status==='REGISTERED')throw new ConflictException('Cliente e tipo são preservados. Registros concluídos não podem ser editados.');const data=await this.mapped(d,t);const r=await this.table().update(data).eq('id',id).eq('organization_id',t.organizationId).eq('revision',d.revision).neq('status','REGISTERED').select().maybeSingle();this.fail(r.error);if(!r.data)throw new ConflictException('O lançamento mudou. Atualize a lista.');return r.data;}
 async register(id:string,input:EntryRevisionDto,t:TenantContext){const d=await validateWriteDto(EntryRevisionDto,input),old=await this.one(id,t);this.writePermission(old.kind,t);await this.customer(old.customer_id,t);if(old.status==='REGISTERED')return old;if(old.revision!==d.revision)throw new ConflictException('O lançamento mudou. Reabra a revisão.');const checked=await this.mapped({customerId:old.customer_id,kind:old.kind,payload:old.payload,deferredSteps:old.deferred_steps},t);if(checked.issues.length)throw new BadRequestException('Complete as pendências antes de registrar.');const link={entry_draft_id:id,entry_draft_revision:d.revision,entry_draft_actor:t.userId};
 // The target INSERT seals the entry in the same database transaction. A retry cannot duplicate it.
 try{if(old.kind==='distributor')await this.units.create(checked.payload as any,t.organizationId,link);else if(old.kind==='supply')await this.contracts.create(checked.payload as any,t.organizationId,link);else if(old.kind==='management')await this.configurations.createManagement(checked.payload as any,t.organizationId,link);else await this.configurations.createService(checked.payload as any,t.organizationId,link);}catch(e){const latest=await this.one(id,t);if(latest.status==='REGISTERED')return latest;throw e;}return this.one(id,t);}
}
