import {Injectable,BadRequestException,ForbiddenException,NotFoundException,ConflictException,ServiceUnavailableException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {TenantContext} from '../../../common/interfaces/tenant-context.interface';
import {auditAuthorNames} from './audit-author-names';
import {feeAdjustmentCycles,feeNotice} from './fee-adjustment';
const uuid=(x:any)=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
export function feeAdjustmentInput(d:any){if(!d||typeof d!=='object'||Array.isArray(d)||Object.keys(d).some(k=>!['effectiveDate','indexName','ratePercent','indexReference','noticeDays','reason','previousId','requestId'].includes(k))||!uuid(d.requestId)||!(d.previousId===null||uuid(d.previousId))||typeof d.effectiveDate!=='string'||!/^\d{4}-\d{2}-01$/.test(d.effectiveDate)||!Number.isFinite(Date.parse(d.effectiveDate))||new Date(d.effectiveDate).toISOString().slice(0,10)!==d.effectiveDate||!Number.isInteger(d.noticeDays)||d.noticeDays<1||d.noticeDays>365||!(d.ratePercent===null||(typeof d.ratePercent==='number'&&Number.isFinite(d.ratePercent)&&d.ratePercent>=-100&&d.ratePercent<=1000&&Math.abs(d.ratePercent*1e6-Math.round(d.ratePercent*1e6))<0.000001)))throw new BadRequestException('Confira data, percentual e antecedência do reajuste.');for(const [key,min,max] of [['indexName',2,80],['indexReference',3,500],['reason',3,1000]] as const)if(typeof d[key]!=='string'||d[key].trim().length<min||d[key].length>max)throw new BadRequestException('Informe índice, período/fonte e justificativa.');return {...d,indexName:d.indexName.trim(),indexReference:d.indexReference.trim(),reason:d.reason.trim()};}
@Injectable()
export class FeeAdjustmentsService{
 constructor(private db:SupabaseService,private licenses:LicensesService){}
 private table(name='commercial_fee_adjustments'){return this.db.getClient().from(name);}
 private fail(e:any){if(!e)return;if(['40001','23505'].includes(e.code))throw new ConflictException('O reajuste mudou. Atualize o histórico.');if(['23514','22003'].includes(e.code))throw new BadRequestException('Confira vigência, intervalo anual e base monetária. Correções preservam a data programada; períodos já aplicados não podem ser reescritos.');throw new ServiceUnavailableException('Não foi possível consultar ou salvar o reajuste.');}
 canWrite(t:TenantContext){return !!t.userId&&(t.accessMode==='platform_operation'||['admin_org','gestor'].includes(t.role));}
 private async parent(kind:string,id:string,t:TenantContext){if(!['management','services'].includes(kind)||!uuid(id))throw new BadRequestException('Cadastro inválido.');await this.licenses.requireEntitlement(t.organizationId,'free_market_management');const r=await this.table(kind==='management'?'management_contracts':'service_agreements').select('*').eq('organization_id',t.organizationId).eq('id',id).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Contrato indisponível nesta organização.');return r.data;}
 async list(kind:string,id:string,t:TenantContext){const contract=await this.parent(kind,id,t);const r=await this.table().select('*').eq('organization_id',t.organizationId).eq('kind',kind).eq('contract_id',id).order('version',{ascending:false}).range(0,999);this.fail(r.error);if(!Array.isArray(r.data)||r.data.length>=1000)throw new ServiceUnavailableException('Histórico extenso ou indisponível.');return {contract,rows:await auditAuthorNames(this.db.getClient(),t.organizationId,r.data),canWrite:this.canWrite(t)};}
 async create(kind:string,id:string,input:any,t:TenantContext){if(!this.canWrite(t))throw new ForbiddenException('O reajuste exige Gestor ou Administrador.');const d=feeAdjustmentInput(input),c=await this.parent(kind,id,t);const row={organization_id:t.organizationId,customer_id:c.customer_id,kind,contract_id:id,effective_date:d.effectiveDate,index_name:d.indexName,rate_percent:d.ratePercent,index_reference:d.indexReference,notice_days:d.noticeDays,reason:d.reason,previous_id:d.previousId,request_id:d.requestId,created_by:t.userId};const old=await this.table().select('*').eq('organization_id',t.organizationId).eq('request_id',d.requestId).maybeSingle();this.fail(old.error);if(old.data){if(Object.entries(row).some(([k,v])=>String(old.data[k])!==String(v)))throw new ConflictException('Solicitação já utilizada.');return old.data;}const r=await this.table().insert(row).select().single();this.fail(r.error);return r.data;}
 async notices(t:TenantContext){await this.licenses.requireEntitlement(t.organizationId,'free_market_management');const m=await this.table('organization_members').select('exclusive_customer_id').eq('organization_id',t.organizationId).eq('user_id',t.userId).eq('status','active').maybeSingle();this.fail(m.error);const customerId=m.data?.exclusive_customer_id;if(!customerId)return {notices:[]};const c=await this.table('customers').select('id').eq('organization_id',t.organizationId).eq('id',customerId).eq('status','ACTIVE').is('deleted_at',null).maybeSingle();this.fail(c.error);if(!c.data)return {notices:[]};const r=await this.table().select('*').eq('organization_id',t.organizationId).eq('customer_id',customerId).order('version',{ascending:false}).range(0,999);this.fail(r.error);if(!Array.isArray(r.data)||r.data.length>=1000)throw new ServiceUnavailableException('Avisos indisponíveis.');const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const groups=new Map<string,any[]>();for(const row of r.data){const key=row.kind+':'+row.contract_id;groups.set(key,[...(groups.get(key)||[]),row]);}return {notices:[...groups.values()].flatMap(feeAdjustmentCycles).filter(row=>feeNotice(row,today)).map(row=>({id:row.id,kind:row.kind,date:row.effective_date,index:row.index_name,rate:row.rate_percent,current:row.base_value,next:row.next_value,reference:row.index_reference}))};}
}
