import {financialAnalytics,compareFinancialAnalytics} from './financial-analytics';
const period={from:'2026-01',to:'2026-03'};
function pub(month='2026-01',version=2):any{
 const units=[{id:'u1',name:'Bonfim',acr:'100.00',aclBeforeFees:'60.00',totalFees:'10.00',aclAfterFees:'70.00',savingsAfterFees:'30.00'},{id:'u2',name:'Outra',acr:'200.00',aclBeforeFees:'180.00',totalFees:'20.00',aclAfterFees:'200.00',savingsAfterFees:'0.00'}];
 const preps=Object.fromEntries(units.map(u=>[u.id,{measurements:{validatedVersion:{measurements:{consumptionTotal:'51.877714',demandPeak:'116',demandOffPeak:'137'},billedDemand:{ACL:{used:'136.92',unused:'23.08',source:'PDF'}}}},findings:[{code:'TAX',severity:'REVIEW',message:'Revisar tributos'}],operationalComposition:{scenarios:[{scenario:'ACL',status:'AVAILABLE',subtotal:u.aclBeforeFees,distributor:u.aclBeforeFees,supplier:'0.00',additional:'0.00',taxes:'0.00',entries:[{id:u.id,revision:2,group:'DISTRIBUTOR',label:'TUSD',amount:u.aclBeforeFees,source:'PDF; imposto embutido'}]}]}}]));
 return {meta:{id:'g'+month+version,customerId:'c',month,version,payloadHash:'a'.repeat(64)},customerName:'Cliente',financial:{status:'AVAILABLE',acr:'300.00',aclBeforeFees:'240.00',totalFees:'30.00',aclAfterFees:'270.00',savingsBeforeFees:'60.00',savingsAfterFees:'30.00',units},preparations:preps,reservations:['Compra sem NF']};
}
describe('financial analytics from immutable publications',()=>{
 it('conserves consolidated fees and cents and separates measured/billed demands',()=>{const p=pub(),before=JSON.stringify(p),r=financialAnalytics('org',period,[p]);expect(r.totals).toMatchObject({acr:'300.00',totalFees:'30.00',savingsAfterFees:'30.00',savingsPercent:'10.00'});expect(r.byUnit![0].amounts!.savingsAfterFees).toBe('30.00');expect(r.composition!.map(c=>c.amount)).toEqual(['240.00','0.00','0.00','0.00','30.00']);expect(r.invoices[0].measurements.billedDemand.ACL.used).toBe('136.92');expect(r.invoices[0].measurements.measurements.demandPeak).toBe('116');expect(JSON.stringify(p)).toBe(before);});
 it('never converts unpublished gaps to zero; cumulative covers only published months',()=>{const r=financialAnalytics('org',period,[pub(),pub('2026-03')]);expect(r.months.map(m=>m.cumulative)).toEqual(['30.00',null,'60.00']);expect(r.months[1].totals).toBeNull();expect(r.coverage).toMatchObject({publishedMonths:2,requestedMonths:3,missingMonths:['2026-02']});expect(r.roi).toBeNull();expect(r.annualProjection).toBeNull();});
 it('uses signed cents for loss and exact graphs',()=>{const p=pub();Object.assign(p.financial,{acr:'260.00',savingsBeforeFees:'20.00',savingsAfterFees:'-10.00'});Object.assign(p.financial.units[0],{acr:'60.00',savingsAfterFees:'-10.00'});const r=financialAnalytics('org',period,[p]);expect(r.totals!.savingsAfterFees).toBe('-10.00');expect(r.months[0].widths!.savings).not.toContain('-');});
 it('selects unit from published rateio without changing group totals',()=>{const r=financialAnalytics('org',period,[pub()],'u1');expect(r.totals).toMatchObject({acr:'100.00',totalFees:'10.00',aclAfterFees:'70.00'});expect(r.invoices.map(i=>i.unitId)).toEqual(['u1']);expect(r.publications[0].amounts.acr).toBe('300.00');});
 it('unit without publication in period stays unavailable',()=>{const r=financialAnalytics('org',period,[pub()],'missing');expect(r.totals).toBeNull();expect(r.invoices).toEqual([]);});
 it.each(['totalFees','aclAfterFees','savingsAfterFees'])('rejects forged published unit %s',k=>{const p=pub();p.financial.units[0][k]='1.00';expect(()=>financialAnalytics('org',period,[p])).toThrow();});
 it('keeps legacy consolidated values while identifying unavailable unit detail',()=>{const p=pub();p.financial.units.forEach((u:any)=>delete u.totalFees);const r=financialAnalytics('org',period,[p]);expect(r.totals!.acr).toBe('300.00');expect(r.byUnit).toBeNull();expect(r.composition).toBeNull();expect(()=>financialAnalytics('org',period,[p],'u1')).toThrow('rateio completo');});
 it('rejects partially captured unit detail, never emits a partial consolidated breakdown',()=>{const p=pub();delete p.financial.units[0].totalFees;expect(()=>financialAnalytics('org',period,[p])).toThrow('parcialmente');});
 it('rejects scenario entries diverging from preserved subtotal',()=>{const p=pub();p.preparations.u1.operationalComposition.scenarios[0].entries[0].amount='59.99';expect(()=>financialAnalytics('org',period,[p])).toThrow('Rubricas');});
 it('represents empty periods as unavailable with no invented charts',()=>{const r=financialAnalytics('org',period,[]);expect(r.totals).toBeNull();expect(r.months.every(m=>m.widths===null)).toBe(true);expect(r.composition).toBeNull();});
 it('compares two units/periods in backend, warning about differing population and coverage',()=>{const a=financialAnalytics('org',period,[pub()],'u1'),b=financialAnalytics('org',{from:'2025-01',to:'2025-01'},[pub('2025-01')],'u2'),r=compareFinancialAnalytics(a,b);expect(r.delta).toMatchObject({acr:'-100.00',savingsAfterFees:'30.00'});expect(r.sameUnits).toBe(false);expect(r.completeCoverage).toBe(false);});
 it('does not invent a delta against an unpublished period',()=>{const a=financialAnalytics('org',period,[pub()]),b=financialAnalytics('org',period,[]);expect(compareFinancialAnalytics(a,b).delta).toBeNull();});
});
