import {Injectable,ForbiddenException,NotFoundException,BadRequestException,ConflictException,InternalServerErrorException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {TenantContext} from '../../../common/interfaces/tenant-context.interface';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {ManagementAllocationDto,ManagementAllocationQueryDto} from '../dto/management-allocation.dto';
import {allocateFee} from './management-fee';
import {monthPeriod} from './preparation';
import {auditAuthorNames} from './audit-author-names';
@Injectable()
export class ManagementAllocationService {
 constructor(private db:SupabaseService,private licenses:LicensesService){}
 canConfigure(t:TenantContext){return t.accessMode==='platform_operation'||['gestor','admin_org'].includes(t.role);}
 private fail(e:any){if(!e)return;if(['P5302','23505'].includes(e.code))throw new ConflictException('A regra mensal foi alterada. Atualize a consulta.');if(['P5301','23514'].includes(e.code))throw new BadRequestException('Confira a competência, as unidades e o total de 100% do rateio.');throw new InternalServerErrorException('Não foi possível consultar ou registrar a regra mensal.');}
 private async context(contractId:string,month:string,t:TenantContext){await this.licenses.requireEntitlement(t.organizationId,'free_market_management');const r=await this.db.getClient().from('management_contracts').select('*').eq('id',contractId).eq('organization_id',t.organizationId).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Contrato não encontrado nesta organização.');const c=await this.db.getClient().from('customers').select('id').eq('id',r.data.customer_id).eq('organization_id',t.organizationId).is('deleted_at',null).maybeSingle();this.fail(c.error);if(!c.data)throw new NotFoundException('Cliente indisponível.');const p=monthPeriod(month);if(r.data.status!=='ACTIVE'||String(r.data.start_date).slice(0,10)>p.start||String(r.data.end_date).slice(0,10)<p.end)throw new BadRequestException('O contrato deve estar ativo e cobrir todo o mês. Não há proporcionalidade automática.');return r.data;}
 async list(input:ManagementAllocationQueryDto,t:TenantContext){const d=await validateWriteDto(ManagementAllocationQueryDto,input),contract=await this.context(d.contractId,d.month,t);const r=await this.db.getClient().from('management_fee_allocations').select('*').eq('organization_id',t.organizationId).eq('contract_id',contract.id).eq('month',d.month).order('version',{ascending:false}).range(0,999);this.fail(r.error);if(!Array.isArray(r.data)||r.data.length>=1000)throw new InternalServerErrorException('Histórico indisponível ou extenso.');return {rows:await auditAuthorNames(this.db.getClient(),t.organizationId,r.data),canConfigure:this.canConfigure(t)};}
 async create(input:ManagementAllocationDto,t:TenantContext){if(!this.canConfigure(t))throw new ForbiddenException('A regra mensal exige Gestor ou Administrador da organização.');const d=await validateWriteDto(ManagementAllocationDto,input),contract=await this.context(d.contractId,d.month,t);const items=d.allocations.map(i=>({...i,consumerUnitId:i.consumerUnitId.toLowerCase()}));try{if(contract.remuneration_model==='HYBRID')allocateFee('0',items);else if(items.length)throw Error('Honorário fixo por unidade não deve ser rateado.');}catch(e){throw new BadRequestException(e instanceof Error?e.message:'Regra mensal inválida.');}
 const r=await this.db.getClient().from('management_fee_allocations').insert([{organization_id:t.organizationId,customer_id:contract.customer_id,contract_id:contract.id,month:d.month,fixed_fee_basis:d.fixedFeeBasis,allocations:items,source:d.source.trim(),reason:d.reason.trim(),previous_id:d.previousId??null,created_by:t.userId}]).select().single();this.fail(r.error);return (await auditAuthorNames(this.db.getClient(),t.organizationId,[r.data]))[0];}
}
