import {allocateFee,feeCents} from './management-fee';
import {managementFeeMemory} from './management-fee-memory';
const unit={id:'a',organization_id:'org',customer_id:'customer'},contract={id:'contract',organization_id:'org',customer_id:'customer',status:'ACTIVE',start_date:'2026-01-01',end_date:'2026-12-31',remuneration_model:'HYBRID',fixed_fee_monthly:'1000.00',savings_percentage:'20',contract_number:'TEST'},rule={id:'rule',organization_id:'org',customer_id:'customer',contract_id:'contract',month:'2026-10',version:1,source:'Contract confirmation',fixed_fee_basis:'PER_UNIT',allocations:[{consumerUnitId:'a',percentage:'25'},{consumerUnitId:'b',percentage:'75'}]};
const memory=(c:any=contract,r:any=rule,u:any=unit)=>managementFeeMemory(u,'2026-10',[c],r?[r]:[]);
describe('Management fee per unit',()=>{
 it('keeps the full fixed fee on each unit despite variable allocation',()=>{expect(memory().fixedUnit).toBe('1000.00');expect(memory(contract,rule,{...unit,id:'b'}).fixedUnit).toBe('1000.00');expect(memory().allocation.percentage).toBe('25');});
 it('charges full fixed fee even at zero variable participation',()=>{const r={...rule,allocations:[{consumerUnitId:'a',percentage:'0'},{consumerUnitId:'b',percentage:'100'}]};expect(memory(contract,r).fixedUnit).toBe('1000.00');});
 it('never invents customer consolidated variable fee or total from an isolated unit',()=>{expect(memory()).toMatchObject({status:'VARIABLE_PENDING',variableFee:null,totalFee:null});});
 it('makes fixed-only available after monthly confirmation without rateio',()=>{expect(memory({...contract,remuneration_model:'FIXED',savings_percentage:0},{...rule,allocations:[]})).toMatchObject({status:'FIXED_AVAILABLE',fixedUnit:'1000.00',variableFee:'0.00',totalFee:'1000.00'});});
 it('blocks legacy rules without the per-unit confirmation',()=>{expect(memory(contract,{...rule,fixed_fee_basis:'CUSTOMER'}).fixedUnit).toBeNull();expect(memory(contract,null).status).toBe('BLOCKED');});
 it.each([{organization_id:'other'},{customer_id:'other'},{contract_id:'other'},{month:'2026-09'}])('ignores out-of-scope rules %o',patch=>expect(memory(contract,{...rule,...patch}).fixedUnit).toBeNull());
 it('blocks incomplete contract coverage and overlaps',()=>{expect(memory({...contract,start_date:'2026-10-02'}).fixedUnit).toBeNull();expect(managementFeeMemory(unit,'2026-10',[contract,contract],[rule]).status).toBe('BLOCKED');});
 it('does not hide malformed rates, duplicates or missing unit',()=>{for(const allocations of [[{consumerUnitId:'a',percentage:'99'}],[{consumerUnitId:'a',percentage:'50'},{consumerUnitId:'a',percentage:'50'}],[{consumerUnitId:'b',percentage:'100'}]])expect(memory(contract,{...rule,allocations}).fixedUnit).toBeNull();});
 it('uses latest immutable correction, leaves input order unchanged',()=>{const corrected={...rule,version:2,allocations:[{consumerUnitId:'a',percentage:'60'},{consumerUnitId:'b',percentage:'40'}]},rows=[rule,corrected];expect(managementFeeMemory(unit,'2026-10',[contract],rows).allocation.percentage).toBe('60');expect(rows[0].version).toBe(1);});
 it('allocates ONLY variable cents using largest remainders deterministically',()=>{const rows=allocateFee('100.01',[{consumerUnitId:'b',percentage:'50'},{consumerUnitId:'a',percentage:'50'}]);expect(rows.find(r=>r.consumerUnitId==='a')?.amount).toBe('50.01');expect(rows.find(r=>r.consumerUnitId==='b')?.amount).toBe('50.00');});
 it('retains all cents including a zero participation',()=>{const rows=allocateFee('999999999999.99',[{consumerUnitId:'a',percentage:'33.3333'},{consumerUnitId:'b',percentage:'66.6667'},{consumerUnitId:'c',percentage:'0'}]);expect(rows.reduce((n,r)=>n+feeCents(r.amount),0n)).toBe(99999999999999n);expect(rows[2].amount).toBe('0.00');});
 it.each(['-1','1e3','NaN','1.001'])('rejects invalid money %s',v=>expect(()=>feeCents(v)).toThrow());
});
