import {auditAuthorNames} from './audit-author-names';
import {Injectable,BadRequestException,NotFoundException,ConflictException,InternalServerErrorException,UnauthorizedException,ForbiddenException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {TenantContext} from '../../../common/interfaces/tenant-context.interface';
import {MonthlyInputDto,MonthlyInputQueryDto,UpdateMonthlyInputDto,MonthlyInputRevisionDto} from '../dto/monthly-inputs.dto';
import {normalizeBilledDemand,billedDemandIssues} from './billed-demand';
import {measurementIssues,normalizeMeasurements} from './monthly-inputs';
@Injectable()
export class MonthlyInputsService {
 constructor(private db:SupabaseService,private licenses:LicensesService){}
 private table(name='calculation_monthly_inputs'){return this.db.getClient().from(name);}
 private fail(e:any){if(!e)return;if(e.code==='P3403')throw new NotFoundException('Unidade ou cliente indisponível.');if(['P3402','23505'].includes(e.code))throw new ConflictException('Já existe um rascunho ou a versão foi alterada. Atualize a consulta.');if(['P3401','23514','23502'].includes(e.code))throw new BadRequestException('Confira competência, medições, fonte e justificativa.');throw new InternalServerErrorException('Não foi possível consultar ou registrar os dados mensais.');}
 private async allowed(t:TenantContext){if(!t.organizationId||!t.userId)throw new UnauthorizedException('Contexto organizacional ausente.');await this.licenses.requireEntitlement(t.organizationId,'free_market_management');}
 canValidate(t:TenantContext){return ['admin_org','gestor'].includes(t.role)||t.accessMode==='platform_operation';}
 private async unit(id:string,t:TenantContext){const r=await this.table('consumer_units').select('*').eq('id',id).eq('organization_id',t.organizationId).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Unidade não encontrada nesta organização.');const c=await this.table('customers').select('id').eq('id',r.data.customer_id).eq('organization_id',t.organizationId).is('deleted_at',null).maybeSingle();this.fail(c.error);if(!c.data)throw new NotFoundException('Cliente indisponível.');return r.data;}
 private context(u:any){return Object.fromEntries(['distributor','tariff_group','tariff_subgroup','tariff_modality','state','free_market'].map(k=>[k,u[k]??null]));}
 private mapped(d:MonthlyInputDto){const issues=[...measurementIssues(d.measurements),...billedDemandIssues(d.billedDemand,null)];if(issues.length)throw new BadRequestException(issues.join(' '));return {measurements:normalizeMeasurements(d.measurements),billed_demand:normalizeBilledDemand(d.billedDemand),source_reference:d.sourceReference.trim(),notes:d.notes.trim(),correction_reason:d.correctionReason.trim()};}
 async list(input:MonthlyInputQueryDto,t:TenantContext){await this.allowed(t);const d=await validateWriteDto(MonthlyInputQueryDto,input);await this.unit(d.consumerUnitId,t);const r=await this.table().select('*').eq('organization_id',t.organizationId).eq('consumer_unit_id',d.consumerUnitId).eq('month',d.month).order('version',{ascending:false}).range(0,999);this.fail(r.error);if(!Array.isArray(r.data)||r.data.length>=1000)throw new InternalServerErrorException('Histórico extenso ou indisponível; a consulta não foi truncada.');return {rows:await auditAuthorNames(this.db.getClient(),t.organizationId,r.data),canValidate:this.canValidate(t)};}
 async one(id:string,t:TenantContext){await this.allowed(t);const r=await this.table().select('*').eq('id',id).eq('organization_id',t.organizationId).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Registro não encontrado nesta organização.');await this.unit(r.data.consumer_unit_id,t);return r.data;}
 async events(id:string,t:TenantContext){await this.one(id,t);const r=await this.table('calculation_monthly_input_events').select('*').eq('input_id',id).eq('organization_id',t.organizationId).order('revision',{ascending:false}).range(0,999);this.fail(r.error);if(!Array.isArray(r.data)||r.data.length>=1000)throw new InternalServerErrorException('Histórico extenso ou indisponível.');return auditAuthorNames(this.db.getClient(),t.organizationId,r.data);}
 async create(input:MonthlyInputDto,t:TenantContext){await this.allowed(t);const d=await validateWriteDto(MonthlyInputDto,input),u=await this.unit(d.consumerUnitId,t);const r=await this.table().insert([{...this.mapped(d),organization_id:t.organizationId,customer_id:u.customer_id,consumer_unit_id:u.id,month:d.month,previous_id:d.previousId??null,unit_context:this.context(u),created_by:t.userId,updated_by:t.userId}]).select().single();this.fail(r.error);return (await auditAuthorNames(this.db.getClient(),t.organizationId,[r.data]))[0];}
 private async write(id:string,revision:number,body:object,t:TenantContext){const r=await this.table().update(body).eq('id',id).eq('organization_id',t.organizationId).eq('revision',revision).eq('status','DRAFT').select().maybeSingle();this.fail(r.error);if(!r.data)throw new ConflictException('O registro mudou. Atualize a consulta antes de continuar.');return (await auditAuthorNames(this.db.getClient(),t.organizationId,[r.data]))[0];}
 async update(id:string,input:UpdateMonthlyInputDto,t:TenantContext){const d=await validateWriteDto(UpdateMonthlyInputDto,input),old=await this.one(id,t);if(old.status!=='DRAFT'||old.consumer_unit_id!==d.consumerUnitId||old.month!==d.month||(old.previous_id??null)!==(d.previousId??null))throw new ConflictException('Edite somente o rascunho da mesma unidade e competência.');return this.write(id,d.revision,{...this.mapped(d),updated_by:t.userId},t);}
 async validate(id:string,input:MonthlyInputRevisionDto,t:TenantContext){if(!this.canValidate(t))throw new ForbiddenException('A validação exige Gestor ou Administrador da organização.');const d=await validateWriteDto(MonthlyInputRevisionDto,input),old=await this.one(id,t);if(old.status!=='DRAFT')throw new ConflictException('A versão já está preservada.');const issues=[...measurementIssues(old.measurements,true),...billedDemandIssues(old.billed_demand,old.unit_context,true)];if(issues.length)throw new BadRequestException(issues.join(' '));return this.write(id,d.revision,{status:'VALIDATED',updated_by:t.userId},t);}
}
