import {monthlyCostLedger} from './monthly-cost-ledger';
const u={id:'u',organization_id:'o',customer_id:'c',tariff_group:'A',tariff_modality:'GREEN'};
const item={id:'10000000-0000-4000-8000-000000000001',label:'Encargo',category:'CCEE',scenario:'ACL',effect:'COST',amount:'0.10',source:'Documento CCEE',taxTreatment:'INCLUDED'};
const row={id:'r',organization_id:'o',customer_id:'c',consumer_unit_id:'u',month:'2026-08',version:1,revision:2,status:'VALIDATED',validated_at:'2026-09-01',validated_by:'actor',source_reference:'Revisão de agosto',unit_context:{tariff_group:'A',tariff_modality:'GREEN'},costs:{noCosts:false,items:[item]}};
const id=(n:number)=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0');
const run=(rows:any[]=[row],unit:any=u)=>monthlyCostLedger(unit,'2026-08',rows);
const items=(values:any[])=>run([{...row,costs:{noCosts:false,items:values}}]);
const blocked=(r:ReturnType<typeof run>)=>{expect(r.status).toBe('BLOCKED');expect(r.groups).toEqual([]);};
describe('monthly cost ledger',()=>{
 it('adds exact decimal cents',()=>{const r=items([item,{...item,id:id(2),amount:'0.20'}]);expect(r.groups[0]).toMatchObject({costs:'0.30',credits:'0.00',balance:'0.30',count:2});});
 it('subtracts credits once and preserves negative net',()=>{const r=items([{...item,amount:'10'},{...item,id:id(2),effect:'CREDIT',amount:'12.50'}]);expect(r.groups[0]).toMatchObject({costs:'10.00',credits:'12.50',balance:'-2.50'});expect(r.groups[0].lines[1].signedAmount).toBe('-12.50');});
 it('accepts explicit zero and does not create negative zero',()=>{const r=items([{...item,effect:'CREDIT',amount:'0'}]);expect(r.groups[0]).toMatchObject({balance:'0.00',credits:'0.00'});expect(r.groups[0].lines[0].signedAmount).toBe('0.00');});
 it('does not combine tax treatments or scenarios',()=>{const r=items(['ACR','ACL'].flatMap((scenario,s)=>['INCLUDED','EXCLUDED','NOT_APPLICABLE'].map((taxTreatment,t)=>({...item,id:id(s*3+t+1),scenario,taxTreatment,amount:String(s*3+t+1)}))));expect(r.groups).toHaveLength(6);expect(r.groups.map(g=>g.balance)).toEqual(['1.00','2.00','3.00','4.00','5.00','6.00']);expect(r).not.toHaveProperty('total');expect(r).not.toHaveProperty('savings');expect(r).not.toHaveProperty('honorarium');});
 it('retains excluded taxes without inventing gross-up',()=>{const r=items([{...item,taxTreatment:'EXCLUDED',amount:'100'}]);expect(r.status).toBe('AVAILABLE');expect(r.groups[0].balance).toBe('100.00');expect(r.groups[0].taxTreatment).toBe('EXCLUDED');});
 it('handles maximum group above Number safe integer cents',()=>{const r=items(Array.from({length:100},(_,n)=>({...item,id:id(n+1),amount:'999999999999.99'})));expect(r.groups[0].costs).toBe('99999999999999.00');});
 it('preserves version, revision, source, category and amount',()=>{const r=run();expect(r.version).toEqual({id:'r',version:1,revision:2,validatedAt:'2026-09-01',source:'Revisão de agosto'});expect(r.groups[0].lines[0]).toMatchObject({id:item.id,label:'Encargo',category:'CCEE',source:'Documento CCEE',amount:'0.10'});});
 it('supports all registered cost categories without a hidden rate',()=>{const r=items(['CCEE','EXPOSURE','CHARGE','OTHER'].map((category,n)=>({...item,id:id(n+1),category,amount:'1'})));expect(r.groups[0].balance).toBe('4.00');});
 it('distinguishes reviewed absence from missing data',()=>{const absent=run([{...row,costs:{noCosts:true,items:[]}}]);expect(absent.status).toBe('NO_COSTS_DECLARED');expect(absent.groups).toEqual([]);expect(absent.version?.id).toBe('r');blocked(run([]));});
 it.each(['organization_id','customer_id','consumer_unit_id','month'])('does not use foreign %s',key=>blocked(run([{...row,[key]:'foreign'}])));
 it('blocks draft instead of emitting a partial balance',()=>blocked(run([{...row,status:'DRAFT'}])));
 it('blocks pending correction even when a valid previous version exists',()=>{const r=run([row,{...row,id:'r2',version:2,status:'DRAFT'}]);blocked(r);expect(r.version?.id).toBe('r');});
 it('uses newest validated version without summing history',()=>{const r=run([row,{...row,id:'r2',version:2,costs:{noCosts:false,items:[{...item,amount:'20'}]}}]);expect(r.groups[0].balance).toBe('20.00');expect(r.version?.id).toBe('r2');});
 it('blocks duplicate history',()=>blocked(run([row,row])));
 it('blocks duplicate item ids rather than double counting',()=>blocked(items([item,item])));
 it('blocks contradictory absence declaration',()=>blocked(run([{...row,costs:{noCosts:true,items:[item]}}])));
 it('blocks empty unreviewed list',()=>blocked(items([])));
 it.each(['UNSPECIFIED','OTHER',''])('blocks invalid tax treatment %s',taxTreatment=>blocked(items([{...item,taxTreatment}])));
 it.each(['','0.001','-1','1,2','1e3','NaN','1000000000000',null,10])('rejects unusable amount %s without partial result',amount=>blocked(items([item,{...item,id:id(2),amount}])));
 it('blocks stale electrical context',()=>blocked(run([row],{...u,state:'SP'})));
 it.each([{validated_by:null},{validated_at:null},{source_reference:' '},{revision:0},{revision:1.5},{revision:null}])('blocks invalid validation evidence %s',patch=>blocked(run([{...row,...patch}])));
 it('blocks unclassified category, effect or scenario',()=>{for(const key of ['category','effect','scenario'])blocked(items([{...item,[key]:'OTHER_INVALID'}]));});
 it('blocks missing line source',()=>blocked(items([{...item,source:''}])));
 it('blocks excessive item list instead of truncating',()=>blocked(items(Array.from({length:101},(_,n)=>({...item,id:id(n+1)})))));
 it('is deterministic and never mutates input',()=>{const second={...item,id:id(2),effect:'CREDIT',amount:'0.01'},before=JSON.stringify(row);expect(items([item,second])).toEqual(items([second,item]));expect(JSON.stringify(row)).toBe(before);});
});
