import {Injectable,BadRequestException,NotFoundException,ConflictException,InternalServerErrorException,UnauthorizedException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {ParameterDto,UpdateParameterDto,ParameterRevisionDto,RetireParameterDto} from '../dto/parameters.dto';
import {parameterIssues} from './parameter-issues';
@Injectable()
export class CalculationParametersService {
 constructor(private db:SupabaseService,private licenses:LicensesService){}
 private table(name='calculation_parameters'){return this.db.getClient().from(name);}
 private fail(e:any){if(!e)return;if(e.code==='P3303')throw new NotFoundException('Unidade ou cliente indisponível nesta organização.');if(['P3302','P3304','23505'].includes(e.code))throw new ConflictException(e.code==='P3304'?'Já existe parâmetro aprovado para esta rubrica, cenário e período. Revise as vigências.':'O registro foi alterado ou está preservado. Atualize a lista.');if(['P3311','P3301','23514','23502','22003','22P02','22007'].includes(e.code))throw new BadRequestException('Confira valor, vigência, base de incidência e tratamento tributário.');throw new InternalServerErrorException('Não foi possível consultar ou salvar os parâmetros.');}
 private actor(actor:string){if(!actor)throw new UnauthorizedException('Sessão sem identificação do autor.');}
 private async allowed(org:string){await this.licenses.requireEntitlement(org,'free_market_management');}
 private async unit(id:string,org:string){const r=await this.table('consumer_units').select('*').eq('id',id).eq('organization_id',org).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Unidade não encontrada nesta organização.');const c=await this.table('customers').select('id').eq('id',r.data.customer_id).eq('organization_id',org).is('deleted_at',null).maybeSingle();this.fail(c.error);if(!c.data)throw new NotFoundException('Cliente indisponível.');return r.data;}
 private context(u:any){return Object.fromEntries(['distributor','tariff_group','tariff_subgroup','tariff_modality','state','consumption_class','free_market'].map(k=>[k,u[k]??null]));}
 private mapped(d:ParameterDto){if(d.endDate<d.startDate)throw new BadRequestException('O término deve ser igual ou posterior ao início.');return {tax_basis:d.taxBasis?{version:1,...(d.taxBasis.interaction?{interaction:d.taxBasis.interaction}:{}),items:d.taxBasis.items.map(i=>({...i,parameterId:i.parameterId.toLowerCase()}))}:null,embedded_tax_codes:d.embeddedTaxCodes??[],kind:d.kind,component_code:d.componentCode,label:d.label.trim(),scenario:d.scenario,time_band:d.timeBand,measure:d.measure,amount_text:d.amount??null,treatment:d.treatment,included_taxes:d.includedTaxes.trim(),base_rule:d.baseRule.trim(),direction:d.direction,source:d.source.trim(),notes:d.notes.trim(),start_date:d.startDate,end_date:d.endDate};}
 async list(org:string){await this.allowed(org);const r=await this.table().select('*').eq('organization_id',org);this.fail(r.error);return r.data;}
 async checks(org:string){const rows=await this.list(org);return rows.filter((p:any)=>p.status!=='RETIRED').map((p:any)=>({id:p.id,revision:p.revision,issues:parameterIssues(p,rows)}));}
 async one(id:string,org:string){await this.allowed(org);const r=await this.table().select('*').eq('id',id).eq('organization_id',org).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Parâmetro não encontrado nesta organização.');return r.data;}
 async events(id:string,org:string){await this.one(id,org);const r=await this.table('calculation_parameter_events').select('*').eq('parameter_id',id).eq('organization_id',org);this.fail(r.error);return r.data;}
 async create(input:ParameterDto,org:string,actor:string){await this.allowed(org);this.actor(actor);const d=await validateWriteDto(ParameterDto,input),u=await this.unit(d.consumerUnitId,org);const r=await this.table().insert([{...this.mapped(d),organization_id:org,customer_id:u.customer_id,consumer_unit_id:u.id,unit_context:this.context(u),created_by:actor,updated_by:actor,status:'DRAFT'}]).select().single();this.fail(r.error);return r.data;}
 async update(id:string,input:UpdateParameterDto,org:string,actor:string){this.actor(actor);const d=await validateWriteDto(UpdateParameterDto,input),old=await this.one(id,org);if(old.status!=='DRAFT'||old.consumer_unit_id!==d.consumerUnitId)throw new ConflictException('Edite somente rascunhos da mesma unidade.');const u=await this.unit(d.consumerUnitId,org);return this.write(id,org,d.revision,{...this.mapped(d),unit_context:this.context(u),updated_by:actor},'DRAFT');}
 private async write(id:string,org:string,revision:number,body:object,status:string){const r=await this.table().update(body).eq('id',id).eq('organization_id',org).eq('revision',revision).eq('status',status).select().maybeSingle();this.fail(r.error);if(!r.data)throw new ConflictException('O registro mudou. Atualize a lista antes de continuar.');return r.data;}
 async approve(id:string,input:ParameterRevisionDto,org:string,actor:string){this.actor(actor);const d=await validateWriteDto(ParameterRevisionDto,input),old=await this.one(id,org);if(old.status!=='DRAFT')throw new ConflictException('Somente rascunhos podem ser aprovados.');const issues=parameterIssues({...old,status:'APPROVED'},await this.list(org));if(issues.length)throw new BadRequestException(issues.join(' '));const u=await this.unit(old.consumer_unit_id,org);return this.write(id,org,d.revision,{status:'APPROVED',updated_by:actor,unit_context:this.context(u)},'DRAFT');}
 async retire(id:string,input:RetireParameterDto,org:string,actor:string){this.actor(actor);const d=await validateWriteDto(RetireParameterDto,input),old=await this.one(id,org);if(old.status==='RETIRED')throw new ConflictException('Este parâmetro já foi retirado de uso.');return this.write(id,org,d.revision,{status:'RETIRED',retirement_reason:d.reason.trim(),updated_by:actor},old.status);}
}
