import {Injectable,BadRequestException,NotFoundException,ConflictException,InternalServerErrorException,UnauthorizedException} from '@nestjs/common';
import {SupabaseService} from '../../../services/supabase.service';
import {LicensesService} from '../../licenses/services/licenses.service';
import {validateWriteDto} from '../../../common/validation/validate-write-dto';
import {ParameterClassReviewDto,ParameterDto,UpdateParameterDto,ParameterRevisionDto,RetireParameterDto} from '../dto/parameters.dto';
import {auditAuthorNames} from './audit-author-names';
import {parameterIssues} from './parameter-issues';
const canonical=(v:any):string=>JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,x[k]])):x);
@Injectable()
export class CalculationParametersService {
 constructor(private db:SupabaseService,private licenses:LicensesService){}
 private table(name='calculation_parameters'){return this.db.getClient().from(name);}
 private fail(e:any){if(!e)return;if(e.code==='P3303')throw new NotFoundException('Unidade ou cliente indisponível nesta organização.');if(['P3302','P3304','23505','40001'].includes(e.code))throw new ConflictException(e.code==='P3304'?'Já existe parâmetro aprovado para esta rubrica, cenário e período. Revise as vigências.':'O registro foi alterado ou está preservado. Atualize a lista.');if(['P3311','P3301','23514','23502','22003','22P02','22007'].includes(e.code))throw new BadRequestException('Confira valor, vigência, base de incidência e tratamento tributário.');throw new InternalServerErrorException('Não foi possível consultar ou salvar os parâmetros.');}
 private actor(actor:string){if(!actor)throw new UnauthorizedException('Sessão sem identificação do autor.');}
 private async allowed(org:string){await this.licenses.requireEntitlement(org,'free_market_management');}
 private async unit(id:string,org:string){const r=await this.table('consumer_units').select('*').eq('id',id).eq('organization_id',org).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Unidade não encontrada nesta organização.');const c=await this.table('customers').select('id').eq('id',r.data.customer_id).eq('organization_id',org).is('deleted_at',null).maybeSingle();this.fail(c.error);if(!c.data)throw new NotFoundException('Cliente indisponível.');return r.data;}
 private context(u:any){return Object.fromEntries(['distributor','tariff_group','tariff_subgroup','tariff_modality','state','consumption_class','free_market'].map(k=>[k,u[k]??null]));}
 private mapped(d:ParameterDto){if(d.amount!=null&&!(d.kind==='TARIFF'&&d.measure==='BRL_KW')&&!/^(0|[1-9][0-9]{0,11})([.][0-9]{1,6})?$/.test(d.amount))throw new BadRequestException('Até nove casas são permitidas somente nas tarifas de demanda em R$/kW.');if(d.endDate<d.startDate)throw new BadRequestException('O término deve ser igual ou posterior ao início.');return {monetary_source:d.monetarySource??null,tax_basis:d.taxBasis?{version:1,...(d.taxBasis.groupCodes?{groupCodes:d.taxBasis.groupCodes}:{}),...(d.taxBasis.taxes?{taxes:d.taxBasis.taxes.map(t=>({...t,parameterId:t.parameterId.toLowerCase()}))}:{}),...(d.taxBasis.interaction?{interaction:d.taxBasis.interaction}:{}),items:d.taxBasis.items.map(i=>({...i,parameterId:i.parameterId.toLowerCase()}))}:null,embedded_tax_codes:d.embeddedTaxCodes??[],kind:d.kind,component_code:d.componentCode,label:d.label.trim(),scenario:d.scenario,time_band:d.timeBand,measure:d.measure,amount_text:d.amount??null,treatment:d.treatment,included_taxes:d.includedTaxes.trim(),base_rule:d.baseRule.trim(),direction:d.direction,source:d.source.trim(),notes:d.notes.trim(),start_date:d.startDate,end_date:d.endDate};}
 async reviewClass(input:ParameterClassReviewDto,org:string,actor:string){await this.allowed(org);this.actor(actor);const d=await validateWriteDto(ParameterClassReviewDto,input);if(d.reason.trim().length<10||!d.parameters.length||new Set(d.parameters.map(p=>p.id)).size!==d.parameters.length)throw new BadRequestException('Informe justificativa e referências únicas para revisão.');await this.unit(d.consumerUnitId,org);const r=await this.db.getClient().rpc('review_parameter_class',{p_org:org,p_unit:d.consumerUnitId,p_month:d.month,p_class:d.consumptionClass,p_refs:d.parameters,p_reason:d.reason.trim(),p_actor:actor});this.fail(r.error);return r.data;}
 async list(org:string){await this.allowed(org);const r=await this.table().select('*').eq('organization_id',org);this.fail(r.error);return r.data;}
 async checks(org:string){const rows=await this.list(org);return rows.filter((p:any)=>p.status!=='RETIRED').map((p:any)=>({id:p.id,revision:p.revision,issues:parameterIssues(p,rows)}));}
 async one(id:string,org:string){await this.allowed(org);const r=await this.table().select('*').eq('id',id).eq('organization_id',org).maybeSingle();this.fail(r.error);if(!r.data)throw new NotFoundException('Parâmetro não encontrado nesta organização.');return r.data;}
 async events(id:string,org:string){await this.one(id,org);const r=await this.table('calculation_parameter_events').select('*').eq('parameter_id',id).eq('organization_id',org);this.fail(r.error);return (await auditAuthorNames(this.db.getClient(),org,r.data??[])).map((e:any)=>e.actor_id==='system:f1.103-lineage'?{...e,actor_id_name:'Sistema — vinculação de versões OCR'}:e);}
 async create(input:ParameterDto,org:string,actor:string){await this.allowed(org);this.actor(actor);const d=await validateWriteDto(ParameterDto,input),u=await this.unit(d.consumerUnitId,org);const r=await this.table().insert([{...this.mapped(d),organization_id:org,customer_id:u.customer_id,consumer_unit_id:u.id,unit_context:this.context(u),created_by:actor,updated_by:actor,status:'DRAFT'}]).select().single();this.fail(r.error);return r.data;}
 // Server-generated identity: retries cannot duplicate a prepared OCR parameter.
 async createPrepared(id:string,input:ParameterDto,org:string,actor:string){
  await this.allowed(org);this.actor(actor);const d=await validateWriteDto(ParameterDto,input),u=await this.unit(d.consumerUnitId,org),mapped=this.mapped(d);
  const existing=await this.table().select('*').eq('id',id).eq('organization_id',org).maybeSingle();this.fail(existing.error);
  const same=(p:any)=>p&&canonical(p.unit_context)===canonical(this.context(u))&&p.customer_id===u.customer_id&&p.consumer_unit_id===u.id&&['DRAFT','APPROVED'].includes(p.status)&&Object.entries(mapped).every(([k,v])=>['start_date','end_date'].includes(k)?String(p[k]).slice(0,10)===v:canonical(p[k])===canonical(v));
  if(existing.data){if(!same(existing.data))throw new ConflictException('O rascunho preparado foi revisado. Seu conteúdo foi preservado.');return existing.data;}
  const r=await this.table().insert([{id,...mapped,organization_id:org,customer_id:u.customer_id,consumer_unit_id:u.id,unit_context:this.context(u),created_by:actor,updated_by:actor,status:'DRAFT'}]).select().single();
  if(r.error?.code==='23505'){const saved=await this.table().select('*').eq('id',id).eq('organization_id',org).maybeSingle();this.fail(saved.error);if(same(saved.data))return saved.data;}
  this.fail(r.error);return r.data;
 }
 async update(id:string,input:UpdateParameterDto,org:string,actor:string){this.actor(actor);const d=await validateWriteDto(UpdateParameterDto,input),old=await this.one(id,org);if(old.status!=='DRAFT'||old.consumer_unit_id!==d.consumerUnitId)throw new ConflictException('Edite somente rascunhos da mesma unidade.');const u=await this.unit(d.consumerUnitId,org);return this.write(id,org,d.revision,{...this.mapped(d),unit_context:this.context(u),updated_by:actor},'DRAFT');}
 private async write(id:string,org:string,revision:number,body:object,status:string){const r=await this.table().update(body).eq('id',id).eq('organization_id',org).eq('revision',revision).eq('status',status).select().maybeSingle();this.fail(r.error);if(!r.data)throw new ConflictException('O registro mudou. Atualize a lista antes de continuar.');return r.data;}
 async approve(id:string,input:ParameterRevisionDto,org:string,actor:string){this.actor(actor);const d=await validateWriteDto(ParameterRevisionDto,input),old=await this.one(id,org);if(old.status!=='DRAFT'&&!(old.supersedes_parameter_id&&old.status==='APPROVED'))throw new ConflictException('Somente rascunhos podem ser aprovados.');if(old.status==='DRAFT'){const issues=parameterIssues({...old,status:'APPROVED'},await this.list(org));if(issues.length)throw new BadRequestException(issues.join(' '));}if(old.supersedes_parameter_id){const r=await this.db.getClient().rpc(old.source?.endsWith(' · exclusões completadas do parâmetro '+old.supersedes_parameter_id)?'approve_bot_tax_exclusion':'approve_parameter_replacement',{p_organization:org,p_parameter:id,p_revision:d.revision,p_actor:actor});this.fail(r.error);if(!r.data)throw new ConflictException('Atualize os parâmetros antes de aprovar.');return r.data;}const u=await this.unit(old.consumer_unit_id,org);return this.write(id,org,d.revision,{status:'APPROVED',updated_by:actor,unit_context:this.context(u)},'DRAFT');}
 async retire(id:string,input:RetireParameterDto,org:string,actor:string){this.actor(actor);const d=await validateWriteDto(RetireParameterDto,input),old=await this.one(id,org);if(old.status==='RETIRED')throw new ConflictException('Este parâmetro já foi retirado de uso.');return this.write(id,org,d.revision,{status:'RETIRED',retirement_reason:d.reason.trim(),updated_by:actor},old.status);}
}
