// Read-only calendar coverage. Never calculates money or authorizes publication.
import {prepareMeasurements} from './preparation-measurements';
import {parameterIssues} from './parameter-issues';
export type Finding={code:string;section:string;severity:'BLOCKER'|'REVIEW';message:string};
type Period={start:string;end:string};
const amountValid=(v:any)=>(typeof v==='number'&&Number.isFinite(v)&&v>=0)||(typeof v==='string'&&/^(0|[1-9][0-9]*)([.][0-9]+)?$/.test(v));
const day=(v:any)=>typeof v==='string'?v.slice(0,10):'';
const next=(d:string)=>{const x=new Date(d+'T00:00:00Z');x.setUTCDate(x.getUTCDate()+1);return x.toISOString().slice(0,10);};
export function monthPeriod(month:string):Period {if(!/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(month))throw new Error('Invalid month');const [y,m]=month.split('-').map(Number);return {start:month+'-01',end:new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)};}
const valid=(d:string)=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T00:00:00Z'))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d;
export function coverage(period:Period, rows:Period[]){const ranges=rows.filter(r=>valid(r.start)&&valid(r.end)&&r.start<=r.end&&r.start<=period.end&&r.end>=period.start).map(r=>({start:r.start<period.start?period.start:r.start,end:r.end>period.end?period.end:r.end})).sort((a,b)=>a.start.localeCompare(b.start)||a.end.localeCompare(b.end));const gaps:Period[]=[];let cursor=period.start,overlap=false;for(const r of ranges){if(r.start<cursor)overlap=true;if(r.start>cursor){const x=new Date(r.start+'T00:00:00Z');x.setUTCDate(x.getUTCDate()-1);gaps.push({start:cursor,end:x.toISOString().slice(0,10)});}if(r.end>=cursor)cursor=next(r.end);}if(cursor<=period.end)gaps.push({start:cursor,end:period.end});return {gaps,overlap,segments:ranges.length};}
const range=(r:any,end:string):Period=>({start:day(r.start_date),end:r.end_date?day(r.end_date):end});
const touches=(r:any,p:Period)=>day(r.start_date)<=p.end&&(!r.end_date||day(r.end_date)>=p.start);
export function prepareMonth(unit:any,month:string,parameters:any[],contracts:any[],prices:any[],management:any[],services:any[],monthly:any[]=[]){
 const period=monthPeriod(month),measurementCheck=prepareMeasurements(unit,month,monthly),{findings:measurementFindings,...measurements}=measurementCheck,findings:Finding[]=[...measurementFindings];
 const add=(code:string,section:string,message:string,severity:Finding['severity']='BLOCKER')=>findings.push({code,section,message,severity});
 if(unit.free_market!==true)add('FREE_MARKET','Unidade',unit.free_market===false?'A unidade está cadastrada fora do Mercado Livre. Confirme o enquadramento para comparar ACL × ACR.':'Informe o enquadramento no Mercado Livre.');
 for(const [key,label] of [['distributor','distribuidora'],['tariff_subgroup','subgrupo tarifário'],['tariff_modality','modalidade tarifária'],['state','UF'],['consumption_class','classe de consumo']])if(!unit[key])add('UNIT_'+key,'Unidade','Complete '+label+' no cadastro elétrico.');
 if(!['A','B'].includes(unit.tariff_group))add('TARIFF_GROUP','Unidade','Revise o grupo tarifário legado para A ou B, com subgrupo separado.');
 const scope=parameters.filter(p=>p.organization_id===unit.organization_id&&p.consumer_unit_id===unit.id),active=scope.filter(p=>p.status==='APPROVED'&&touches(p,period));
 const grouped=new Map<string,any[]>();for(const p of active){const k=[p.scenario,p.kind,p.component_code,p.time_band].join('/');grouped.set(k,[...(grouped.get(k)||[]),p]);}
 const catalog=[...grouped.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,rows])=>{const c=coverage(period,rows.map(r=>range(r,period.end)));if(c.gaps.length)add('PARAMETER_GAP:'+key,'Parâmetros',key+': há dias sem parâmetro aprovado.');if(c.overlap)add('PARAMETER_OVERLAP:'+key,'Parâmetros',key+': há vigências aprovadas sobrepostas.');if(c.segments>1)add('PARAMETER_SPLIT:'+key,'Parâmetros',key+': houve mudança dentro do mês; a apuração exige segmentação por período.','REVIEW');for(const r of rows){for(const issue of parameterIssues(r,scope))add('PARAMETER_ISSUE:'+r.id,'Bases tributárias',r.label+': '+issue);}
 return {key,label:rows[0].label,scenario:rows[0].scenario,kind:rows[0].kind,timeBand:rows[0].time_band,...c,versions:rows.map(r=>({id:r.id,revision:r.revision,start:day(r.start_date),end:day(r.end_date),source:r.source}))};});
 for(const scenario of ['ACR','ACL']){
  if(!active.some(p=>p.scenario===scenario&&p.kind==='TARIFF'))add('TARIFF_MISSING:'+scenario,'Parâmetros','Cadastre tarifas aprovadas para o cenário '+scenario+'.');
  for(const code of ['ICMS','PIS','COFINS','IOF']){const rows=active.filter(p=>p.scenario===scenario&&p.kind==='TAX'&&p.component_code===code);const c=coverage(period,rows.map(r=>range(r,period.end)));if(c.gaps.length)add('TAX_MISSING:'+scenario+':'+code,'Tributos',scenario+' / '+code+': informe o tratamento para todo o mês, inclusive isenção ou não aplicação com justificativa. Isso não presume incidência.');}
 }
 const drafts=scope.filter(p=>p.status==='DRAFT'&&touches(p,period));if(drafts.length)add('DRAFT_PARAMETERS','Parâmetros',drafts.length+' parâmetro(s) em rascunho no período não entram na cobertura.','REVIEW');
 const supply=contracts.filter(c=>c.organization_id===unit.organization_id&&c.consumer_unit_id===unit.id&&c.contract_type==='ENERGY_PURCHASE'&&['ACTIVE','APPROVED'].includes(c.status)&&touches(c,period));
 const supplyCoverage=coverage(period,supply.map(c=>range(c,period.end)));if(supplyCoverage.gaps.length)add('SUPPLY_GAP','Fornecedor','Há dias sem contrato de compra de energia ativo/aprovado.');if(supplyCoverage.overlap)add('MULTIPLE_SUPPLIERS','Fornecedor','Há contratos simultâneos: revisar alocação de volumes para evitar dupla contagem.','REVIEW');
 const suppliers=supply.map(c=>{const cp={start:day(c.start_date)>period.start?day(c.start_date):period.start,end:c.end_date&&day(c.end_date)<period.end?day(c.end_date):period.end};const history=prices.filter(p=>p.contract_id===c.id&&touches(p,cp)&&amountValid(p.price_per_mwh));const annual=Array.isArray(c.annual_prices)?c.annual_prices.filter((p:any)=>p&&valid(p.startDate)&&valid(p.endDate)&&p.startDate<=cp.end&&p.endDate>=cp.start):[];const final=annual.filter((p:any)=>p.priceStatus==='FINAL'&&amountValid(p.pricePerMwh));
 const histories=coverage(cp,history.map(p=>range(p,cp.end)));const annualCoverage=coverage(cp,final.map((p:any)=>({start:p.startDate,end:p.endDate})));const effective=history.length?histories:annualCoverage;
 if(effective.gaps.length)add('PRICE_GAP:'+c.id,'Preços',c.contract_number+': preço final por vigência não cobre todo o período. Preço-base ou valor inicial isolado não substitui confirmação.');if(effective.overlap)add('PRICE_OVERLAP:'+c.id,'Preços',c.contract_number+': preços finais sobrepostos.');
 if(history.length&&annual.length)add('PRICE_SOURCES:'+c.id,'Preços',c.contract_number+': conferir histórico e tabela anual. O diagnóstico usa o histórico quando presente; não combina automaticamente as duas fontes.','REVIEW');
 if(effective.segments>1)add('PRICE_SPLIT:'+c.id,'Preços',c.contract_number+': mudança de preço dentro da competência exige segmentação.','REVIEW');
 if(annual.some((p:any)=>p.priceStatus==='BASE')&&(!history.length||histories.gaps.length))add('INDEX_PENDING:'+c.id,'Preços',c.contract_number+': reajuste possui preço-base pendente de preço final confirmado.');
 add('MONTHLY_VOLUME:'+c.id,'Volumes',c.contract_number+': conferir volume da competência, sazonalidade e flexibilidade; não dividir automaticamente o volume geral por 12.','REVIEW');
 if(c.modulation)add('LOAD_PROFILE:'+c.id,'Volumes',c.contract_number+': conferir a modulação contratada com o perfil medido.','REVIEW');
 return {id:c.id,number:c.contract_number,start:cp.start,end:cp.end,priceSource:history.length?'HISTORY':'ANNUAL',priceCoverage:effective};});
 const fees=management.filter(m=>m.organization_id===unit.organization_id&&m.customer_id===unit.customer_id&&m.status==='ACTIVE'&&touches(m,period));const feeCoverage=coverage(period,fees.map(m=>range(m,period.end)));if(feeCoverage.gaps.length)add('MANAGEMENT_GAP','Honorários','Não há configuração de honorários ativa cobrindo todo o mês. Ausência não equivale a valor zero.');if(feeCoverage.overlap)add('MANAGEMENT_OVERLAP','Honorários','Há configurações de honorários simultâneas para este cliente.');if(fees.length)add('MANAGEMENT_ALLOCATION','Honorários','Honorários pertencem ao cliente: confirmar rateio entre unidades e base líquida antes de aplicar o percentual.','REVIEW');
 const relevantServices=services.filter(s=>s.organization_id===unit.organization_id&&s.customer_id===unit.customer_id&&(!s.consumer_unit_id||s.consumer_unit_id===unit.id)&&touches(s,period));for(const s of relevantServices)add('SERVICE_REVIEW:'+s.id,'Custos adicionais',s.contract_number+': conferir aplicação'+(!s.consumer_unit_id?' e rateio entre unidades':'')+' e evitar duplicidade com rubricas cadastradas.','REVIEW');
 return {mode:'PREPARATION_ONLY',ruleVersion:'preparation-1.1',measurements,month,period,unit:{id:unit.id,name:unit.name||unit.consumer_unit_number,customerId:unit.customer_id},findings,catalog,suppliers,supplyCoverage,feeCoverage,counts:{blockers:findings.filter(f=>f.severity==='BLOCKER').length,reviews:findings.filter(f=>f.severity==='REVIEW').length,approvedParameters:active.length,draftParameters:drafts.length},notChecked:['Conciliação das medições com as faturas, perfil horário e posto intermediário quando aplicável.','CCEE, exposição, créditos e demais custos efetivamente aplicáveis.','Rateios, interação entre tributos e arredondamento monetário.','Memória de cálculo, validação do gestor e publicação de resultados.']};
}
