import {ocrPreparationCandidates} from './preparation-ocr';
const unit={id:'unit',organization_id:'org',customer_id:'customer'};
function setup(){const doc={id:'doc',organization_id:'org',customer_id:'customer',consumer_unit_id:'unit',reference_month:'2026-08-01',file_hash:'hash',file_verified:true,document_type:'INVOICE_DISTRIBUTOR',original_filename:'invoice.pdf'};const assessment={version:'intake-assessment-v1',source:{organizationId:'org',customerId:'customer',unitId:'unit',documentId:'doc',fileHash:'hash',referenceMonth:'2026-08'},intake:{decision:'REVIEW_REQUIRED'}};const data:any={documents:[doc],document_ocr_results:[{organization_id:'org',document_id:'doc',file_hash:'hash',evidence:{assessment},raw_result:{documents:[{fields:{}}],pages:[],content:''}}]};const calls:any[]=[];const db={from:(table:string)=>{const q:any={};for(const op of ['select','eq','gte','lt','order','in'])q[op]=(...args:any[])=>{calls.push([table,op,...args]);return q;};q.limit=async()=>({data:data[table],error:null});return q;}};return {doc,assessment,data,db,calls};}
describe('preparation OCR boundaries',()=>{
 it('scopes documents to organization, customer, unit and reference month and never imports',async()=>{const s=setup();const r=await ocrPreparationCandidates(s.db,unit,'2026-08');for(const k of ['organization_id','customer_id','consumer_unit_id'])expect(s.calls).toContainEqual(['documents','eq',k,(s.doc as any)[k]]);expect(s.calls).toContainEqual(['documents','gte','reference_month','2026-08-01']);expect(s.calls).toContainEqual(['documents','lt','reference_month','2026-09-01']);expect(s.calls).toContainEqual(['document_ocr_results','eq','organization_id','org']);expect(r[0].canImport).toBe(false);expect(r[0]).not.toHaveProperty('raw_result');});
 it.each(['fileHash','organizationId','customerId','unitId','documentId','referenceMonth'])('quarantines wrong assessment %s',async key=>{const s=setup();(s.assessment.source as any)[key]='wrong';expect((await ocrPreparationCandidates(s.db,unit,'2026-08'))[0]).toMatchObject({state:'QUARANTINED',gd:null,measurements:null,preparation:null});});
 it('never returns foreign result content',async()=>{const s=setup();s.data.document_ocr_results[0].organization_id='other';expect((await ocrPreparationCandidates(s.db,unit,'2026-08'))[0]).toMatchObject({gd:null,measurements:null,preparation:null});});
 it('keeps rejection blocked',async()=>{const s=setup();s.assessment.intake.decision='REJECT_AUTOMATION';expect((await ocrPreparationCandidates(s.db,unit,'2026-08'))[0]).toMatchObject({state:'REJECT_AUTOMATION',canImport:false});});
 it('caps rather than silently truncate',async()=>{const s=setup();s.data.documents=Array(101).fill(s.doc);await expect(ocrPreparationCandidates(s.db,unit,'2026-08')).rejects.toThrow('competência');});
 it('returns no candidates without documents',async()=>{const s=setup();s.data.documents=[];expect(await ocrPreparationCandidates(s.db,unit,'2026-08')).toEqual([]);});
 it('fails closed on a query error',async()=>{const db={from:()=>{const q:any={};for(const k of ['select','eq','gte','lt','order'])q[k]=()=>q;q.limit=async()=>({data:null,error:{}});return q;}};await expect(ocrPreparationCandidates(db,unit,'2026-08')).rejects.toThrow();});
});
