import {ReviewSnapshotsService,reviewDigest} from './review-snapshots.service';
import {CalculationPreparationService} from './preparation.service';
const org='org',unit='22222222-2222-4222-8222-222222222222',customer='11111111-1111-4111-8111-111111111111',request='33333333-3333-4333-8333-333333333333';
const tenant:any={organizationId:org,userId:'actor',role:'operador'};
const input={consumerUnitId:unit,month:'2026-08',note:'Revisão inicial',requestId:request};
function setup(){const data:Record<string,any[]>={consumer_units:[{id:unit,organization_id:org,customer_id:customer,name:'Centro'}],customers:[{id:customer,organization_id:org,deleted_at:null}],calculation_review_snapshots:[],organization_members:[{user_id:'actor',organization_id:org,display_name:'Ana'}],user_profiles:[]};const calls:any[]=[];let insertError:any=null;
 const client={from:(table:string)=>{const filters:any[]=[];let insert:any;const rows=()=> (data[table]||[]).filter(r=>filters.every(([k,v,op])=>op==='lt'?r[k]<v:op==='in'?v.includes(r[k]):r[k]===v));const q:any={select:()=>q,eq:(k:string,v:any)=>{filters.push([k,v]);return q;},is:(k:string,v:any)=>{filters.push([k,v]);return q;},lt:(k:string,v:any)=>{filters.push([k,v,'lt']);return q;},in:(k:string,v:any)=>{filters.push([k,v,'in']);return q;},order:()=>q,insert:(r:any)=>{insert=r[0];return q;},range:async(a:number,b:number)=>({data:rows().sort((a,b)=>b.version-a.version).slice(a,b+1),error:null}),maybeSingle:async()=>{calls.push({table,filters});return {data:rows()[0]||null,error:null};},single:async()=>{if(insertError)return {data:null,error:insertError};const row={...insert,id:request,version:data[table].length+1,status:'DRAFT',created_at:'2026-09-01T00:00:00Z'};data[table].push(JSON.parse(JSON.stringify(row)));return {data:row,error:null};},then:(resolve:any)=>Promise.resolve({data:rows(),error:null}).then(resolve)};return q;}};
 const db={getClient:()=>client},licenses={requireEntitlement:jest.fn(async()=>undefined)};
 const inspect=jest.fn(async(d:any,o:any,capture:any)=>{capture({unit:data.consumer_units[0],monthly:[]});return {unit:{id:unit,name:'Centro'},month:d.month,counts:{blockers:1,reviews:0},findings:[{message:'Medição pendente'}],checkedAt:'2026-09-01'};});
 return {data,calls,db,licenses,inspect,service:new ReviewSnapshotsService(db as any,licenses as any,{inspect} as any),setInsertError:(e:any)=>{insertError=e;}};
}
describe('immutable preliminary reviews',()=>{
 it('canonical hash survives JSONB key order and detects changed values',()=>{expect(reviewDigest({b:2,a:{z:1,x:[2,3]}})).toBe(reviewDigest({a:{x:[2,3],z:1},b:2}));expect(reviewDigest({a:[1,2]})).not.toBe(reviewDigest({a:[2,1]}));});
 it('captures on server, preserves blockers, returns named author without raw sources',async()=>{const x=setup();const r=await x.service.create(input,tenant);expect(r.created_by_name).toBe('Ana');expect(r.result.counts.blockers).toBe(1);expect(r.status).toBe('DRAFT');expect(r.payload).toBeUndefined();expect(r.sources).toBeUndefined();expect(x.data.calculation_review_snapshots[0].payload.sources.monthly).toEqual([]);expect(x.inspect).toHaveBeenCalledWith({consumerUnitId:unit,month:input.month},org,expect.any(Function));});
 it('retries same request without recomputing or creating another version',async()=>{const x=setup();await x.service.create(input,tenant);await x.service.create(input,tenant);expect(x.inspect).toHaveBeenCalledTimes(1);expect(x.data.calculation_review_snapshots).toHaveLength(1);});
 it('rejects reused key with another note or actor',async()=>{const x=setup();await x.service.create(input,tenant);await expect(x.service.create({...input,note:'Outro motivo'},tenant)).rejects.toThrow('outra revisão');await expect(x.service.create(input,{...tenant,userId:'other'})).rejects.toThrow('outra revisão');});
 it('stored result does not follow later live edits',async()=>{const x=setup();await x.service.create(input,tenant);x.data.consumer_units[0].name='Changed';expect((await x.service.one(request,tenant)).result.unit.name).toBe('Centro');});
 it('fails closed on corrupted payload',async()=>{const x=setup();await x.service.create(input,tenant);x.data.calculation_review_snapshots[0].payload.result.month='2026-09';await expect(x.service.one(request,tenant)).rejects.toThrow('integridade');});
 it('rejects foreign unit and foreign snapshot',async()=>{const x=setup();await x.service.create(input,tenant);await expect(x.service.one(request,{...tenant,organizationId:'other'})).rejects.toThrow('não encontrada');await expect(x.service.create(input,{...tenant,organizationId:'other'})).rejects.toThrow('não encontrada');});
 it('honors entitlement before database access',async()=>{const x=setup();x.licenses.requireEntitlement.mockRejectedValue(new Error('license'));await expect(x.service.create(input,tenant)).rejects.toThrow('license');expect(x.calls).toHaveLength(0);});
 it('rejects missing identity, invalid month, whitespace and injected output',async()=>{const x=setup();await expect(x.service.create(input,{...tenant,userId:''})).rejects.toThrow();await expect(x.service.create({...input,month:'2026-13'},tenant)).rejects.toThrow();await expect(x.service.create({...input,note:'   '},tenant)).rejects.toThrow();await expect(x.service.create({...input,payload:{result:0}} as any,tenant)).rejects.toThrow();expect(x.inspect).not.toHaveBeenCalled();});
 it('does not insert if capture fails or is missing',async()=>{const x=setup();x.inspect.mockRejectedValueOnce(new Error('source'));await expect(x.service.create(input,tenant)).rejects.toThrow('source');x.inspect.mockImplementationOnce(async()=>({unit:{id:unit},month:input.month}) as any);await expect(x.service.create(input,tenant)).rejects.toThrow('fontes');expect(x.data.calculation_review_snapshots).toHaveLength(0);});
 it('returns persisted result for concurrent duplicate',async()=>{const x=setup();await x.service.create(input,tenant);const row=x.data.calculation_review_snapshots.pop();x.inspect.mockImplementationOnce(async(d,o,c)=>{c({unit:x.data.consumer_units[0]});x.data.calculation_review_snapshots.push(row);return row.payload.result;});x.setInsertError({code:'23505'});expect((await x.service.create(input,tenant)).version).toBe(1);});
 it('paginated history is scoped and has explicit continuation',async()=>{const x=setup();await x.service.create(input,tenant);const row=x.data.calculation_review_snapshots[0];x.data.calculation_review_snapshots=Array.from({length:25},(_,i)=>({...row,version:i+1}));x.data.calculation_review_snapshots.push({...row,organization_id:'other',version:99});const first=await x.service.list({consumerUnitId:unit,month:input.month},tenant);expect(first.rows).toHaveLength(20);expect(first.nextBeforeVersion).toBe('6');const last=await x.service.list({consumerUnitId:unit,month:input.month,beforeVersion:'6'},tenant);expect(last.rows).toHaveLength(5);expect(last.nextBeforeVersion).toBeNull();});
 it('real preparation exposes sources only to internal capture callback',async()=>{const x=setup();const service=new CalculationPreparationService(x.db as any,x.licenses as any);let captured:any;const r=await service.inspect({consumerUnitId:unit,month:input.month},org,s=>{captured=s;});expect(captured.unit.id).toBe(unit);expect(captured.parameters).toEqual([]);expect((r as any).sources).toBeUndefined();expect(r.month).toBe(input.month);});
});
