import {applySpotReconciliation} from './spot-reconciliation';
const u={organization_id:'o',customer_id:'c',id:'u'};
const base=()=>({formulaVersion:'spot-supplier-1.0',status:'BLOCKED',month:'2026-08',contract:{id:'contract'},rule:{id:'rule',version:1},measurements:{id:'m',revision:1,measurements:{consumptionTotal:'111122.200000',consumptionPeak:'11378.640000',consumptionOffPeak:'99743.560000'}},costVersion:{id:'cost',revision:1},invoiceSources:[{id:'item'}],consumedMwh:'111.122200000000',billedMwh:'111.034000000000',pricePerMwh:'151.819983000000',taxTreatment:'GROSS',invoiceAmount:'16857.18',invoiceDifference:'0.00',volumeDifferenceMwh:'0.088200000000',totalAmount:null,bands:[],warnings:[],requirements:[{code:'SPOT_VOLUME_DIFFERENCE'}]});
const doc={...u,id:'doc',consumer_unit_id:'u',organization_id:'o',file_verified:true,file_hash:'abc',reference_month:'2026-08-01'};
const approved=()=>({id:'rec',organization_id:'o',customer_id:'c',consumer_unit_id:'u',contract_id:'contract',month:'2026-08',version:1,status:'APPROVED_NO_COST',reason:'Documentary explanation with no additional cost',created_by:'actor',created_at:'2026-09-28',source_hash:applySpotReconciliation(base(),u,[],[]).reconciliationContext.hash,document_id:'doc',document_sha256:'abc'});
describe('audited spot reconciliation',()=>{
 it('preserves consumption, purchase and cents while releasing only the documented difference',()=>{const r=applySpotReconciliation(base(),u,[approved()],[doc]);expect(r.status).toBe('READY');expect(r.consumedMwh).toBe('111.122200000000');expect(r.billedMwh).toBe('111.034000000000');expect(r.volumeDifferenceMwh).toBe('0.088200000000');expect(r.totalAmount).toBe('16857.18');expect(r.bands.reduce((s:bigint,b:any)=>s+BigInt(b.amount.replace('.','')),0n)).toBe(1685718n);});
 it.each(['organization_id','customer_id','consumer_unit_id','contract_id','month','source_hash','document_id','document_sha256','status'])('rejects incorrect reconciliation %s',key=>expect(applySpotReconciliation(base(),u,[{...approved(),[key]:'foreign'}],[doc]).status).toBe('BLOCKED'));
 it.each(['organization_id','customer_id','consumer_unit_id','reference_month','energy_contract_id','file_hash'])('rejects incorrect document %s',key=>expect(applySpotReconciliation(base(),u,[approved()],[{...doc,[key]:'foreign'}]).status).toBe('BLOCKED'));
 it('requires verified evidence',()=>expect(applySpotReconciliation(base(),u,[approved()],[{...doc,file_verified:false}]).status).toBe('BLOCKED'));
 it('new pending version revokes old approval',()=>expect(applySpotReconciliation(base(),u,[approved(),{...approved(),id:'new',version:2,status:'PENDING'}],[doc]).status).toBe('BLOCKED'));
 it('does not reuse approval after measurement revision',()=>{const r=base();r.measurements.revision=2;expect(applySpotReconciliation(r,u,[approved()],[doc]).status).toBe('BLOCKED');});
 it('does not reuse approval after cost revision',()=>{const r=base();r.costVersion.revision=2;expect(applySpotReconciliation(r,u,[approved()],[doc]).status).toBe('BLOCKED');});
 it('does not bypass unrelated blockers',()=>{const r=base();r.requirements.push({code:'CYCLE_OPEN'});expect(applySpotReconciliation(r,u,[approved()],[doc]).totalAmount).toBeNull();});
 it('never accepts monetary mismatch',()=>expect(applySpotReconciliation({...base(),invoiceDifference:'1.00'},u,[approved()],[doc]).status).toBe('BLOCKED'));
});

describe('tax reservation reconciliation',()=>{
 const reserved=()=>({...base(),taxTreatment:'RESERVED',taxReservation:{reason:'Tax incidence could not be confirmed from the invoice',createdBy:'actor',createdAt:'2026-09-28'},requirements:[{code:'SPOT_VOLUME_DIFFERENCE'},{code:'SPOT_TAX_RESERVATION'}]});
 const approval=(r:any)=>({...approved(),status:'APPROVED_TAX_RESERVATION',source_hash:applySpotReconciliation(r,u,[],[]).reconciliationContext.hash});
 it('preserves documentary cents without declaring taxes included or zero',()=>{const r=reserved();const result=applySpotReconciliation(r,u,[approval(r)],[doc]);expect(result.status).toBe('READY');expect(result.taxTreatment).toBe('RESERVED');expect(result.totalAmount).toBe('16857.18');expect(result.bands.reduce((s:bigint,b:any)=>s+BigInt(b.amount.replace('.','')),0n)).toBe(1685718n);expect(result.warnings.join(' ')).toContain('tributos não confirmados não geram acréscimo presumido');});
 it('cannot close uncertainty under the ordinary approval status',()=>{const r=reserved();expect(applySpotReconciliation(r,u,[{...approval(r),status:'APPROVED_NO_COST'}],[doc]).status).toBe('BLOCKED');});
 it('requires approval even when measured and purchased volume match',()=>{const r={...reserved(),volumeDifferenceMwh:'0.000000000000',requirements:[{code:'SPOT_TAX_RESERVATION'}]};expect(applySpotReconciliation(r,u,[],[]).status).toBe('BLOCKED');expect(applySpotReconciliation(r,u,[approval(r)],[doc]).status).toBe('READY');});
 it('does not waive unrelated blockers',()=>{const r=reserved();r.requirements.push({code:'CYCLE_OPEN'});expect(applySpotReconciliation(r,u,[approval(r)],[doc]).status).toBe('BLOCKED');});
 it('invalidates approval when the tax justification changes',()=>{const r=reserved(),a=approval(r);r.taxReservation.reason='Another source and a revised reason';expect(applySpotReconciliation(r,u,[a],[doc]).status).toBe('BLOCKED');});
 it('does not allow tax reservation to approve known treatment',()=>{const r=base();expect(applySpotReconciliation(r,u,[{...approved(),status:'APPROVED_TAX_RESERVATION'}],[doc]).status).toBe('BLOCKED');});
});
