import {monthlyCostLedger} from './monthly-cost-ledger';
import {additionalCostSubtotal} from './additional-cost-subtotal';
import {supplierCostMemory} from './supplier-cost-memory';
import {costIssues} from './monthly-costs';
const u={id:'u',organization_id:'o',customer_id:'c',tariff_group:'A',tariff_modality:'GREEN'};
const item={id:'10000000-0000-4000-8000-000000000001',label:'Fatura',category:'SUPPLIER_INVOICE',scenario:'ACL',effect:'COST',amount:'100.10',source:'NF 123 - conferida',taxTreatment:'INCLUDED'};
const id=(n:number)=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0');
const row={id:'r',organization_id:'o',customer_id:'c',consumer_unit_id:'u',month:'2026-08',version:1,revision:2,status:'VALIDATED',validated_at:'2026-09-01',validated_by:'actor',source_reference:'Faturas revisadas',unit_context:{tariff_group:'A',tariff_modality:'GREEN'},costs:{noCosts:false,items:[item]}};
const run=(items:any[]=[item],patch:any={})=>{const r={...row,costs:{noCosts:false,items},...patch};const supplier=monthlyCostLedger(u,'2026-08',[r],'SUPPLIER'),additional=monthlyCostLedger(u,'2026-08',[r]);return {supplier:supplierCostMemory(supplier),additional:additionalCostSubtotal(additional),additionalLedger:additional};};
describe('supplier invoices and additional costs',()=>{
 it('uses invoice amount and preserves sources',()=>{const r=run().supplier;expect(r).toMatchObject({status:'AVAILABLE',balance:'100.10',baseInvoice:'100.10',extraPurchases:'0.00'});expect(r.version?.revision).toBe(2);expect(r.entries[0].source).toBe(item.source);});
 it('adds extra purchases and subtracts credits once',()=>expect(run([item,{...item,id:id(2),category:'SUPPLIER_EXTRA_ENERGY',amount:'20.25'},{...item,id:id(3),category:'SUPPLIER_EXTRA_ENERGY',effect:'CREDIT',amount:'5.00'}]).supplier).toMatchObject({costs:'120.35',credits:'5.00',balance:'115.35',baseInvoice:'100.10',extraPurchases:'15.25'}));
 it('separates supplier and CCEE',()=>{const r=run([item,{...item,id:id(2),category:'CCEE',amount:'3.00'}]);expect(r.supplier.balance).toBe('100.10');expect(r.additional.scenarios[1].balance).toBe('3.00');});
 it('does not presume zero in empty scenario',()=>expect(run([{...item,category:'CCEE'}]).additional.scenarios[0].balance).toBeNull());
 it('requires regular invoice with extra-only purchase',()=>expect(run([{...item,category:'SUPPLIER_EXTRA_ENERGY'}]).supplier.balance).toBeNull());
 it('requires invoice with credit-only entry',()=>expect(run([{...item,effect:'CREDIT'}]).supplier.balance).toBeNull());
 it.each(['SUPPLIER_INVOICE','SUPPLIER_EXTRA_ENERGY'])('rejects ACR %s',category=>{expect(costIssues({noCosts:false,items:[{...item,category,scenario:'ACR'}]})).not.toEqual([]);expect(run([{...item,category,scenario:'ACR'}]).supplier.balance).toBeNull();});
 it('blocks tax-excluded invoice',()=>expect(run([{...item,taxTreatment:'EXCLUDED'}]).supplier.balance).toBeNull());
 it('blocks unresolved extra tax',()=>expect(run([item,{...item,id:id(2),category:'SUPPLIER_EXTRA_ENERGY',taxTreatment:'EXCLUDED'}]).supplier.balance).toBeNull());
 it('does not turn old absence into supplier zero',()=>{const r=run([],{costs:{noCosts:true,items:[]}});expect(r.supplier.balance).toBeNull();expect(r.additional.scenarios[1]).toMatchObject({status:'DECLARED_ZERO',balance:'0.00'});});
 it.each(['organization_id','customer_id','consumer_unit_id','month'])('isolates %s',key=>expect(run([item],{[key]:'other'}).supplier.balance).toBeNull());
 it('requires source',()=>expect(run([{...item,source:''}]).supplier.balance).toBeNull());
 it('blocks draft',()=>expect(run([item],{status:'DRAFT'}).supplier.balance).toBeNull());
 it('accepts explicit zero',()=>expect(run([{...item,amount:'0'}]).supplier.balance).toBe('0.00'));
 it('preserves negative credit balance',()=>expect(run([item,{...item,id:id(2),effect:'CREDIT',amount:'200'}]).supplier.balance).toBe('-99.90'));
 it('rejects duplicate ids',()=>expect(run([item,item]).supplier.balance).toBeNull());
 it('keeps exact high precision',()=>expect(run(Array.from({length:100},(_,n)=>({...item,id:id(n+1),amount:'999999999999.99'}))).supplier.balance).toBe('99999999999999.00'));
 it('blocks excluded additional tax independently',()=>{const r=run([item,{...item,id:id(2),category:'CCEE',taxTreatment:'EXCLUDED'}]);expect(r.supplier.balance).toBe('100.10');expect(r.additional.scenarios[1].balance).toBeNull();});
 it('combines compatible additional costs and credits',()=>expect(run([{...item,category:'CCEE',amount:'0.10'},{...item,id:id(2),category:'OTHER',taxTreatment:'NOT_APPLICABLE',amount:'0.20'},{...item,id:id(3),category:'CHARGE',effect:'CREDIT',amount:'0.05'}]).additional.scenarios[1]).toMatchObject({costs:'0.30',credits:'0.05',balance:'0.25'}));
 it('rejects aggregate mismatch',()=>{const l=run([{...item,category:'CCEE'}]).additionalLedger;l.groups[0].costs='999.00';expect(additionalCostSubtotal(l).scenarios[1].balance).toBeNull();});
 it('rejects duplicate ledger ids',()=>{const l=run([{...item,category:'CCEE'}]).additionalLedger;l.groups.push({...l.groups[0]});expect(additionalCostSubtotal(l).scenarios[1].balance).toBeNull();});
});
