import {libraryPlan,validateProfile} from './tariff-library-plan';
import {elektroTariffSeed} from './tariff-library-seed';
const record=()=>({id:'b12ed880-70cf-4410-b502-27b99554c0ac',version:1,profile:structuredClone(elektroTariffSeed)});
const unit={distributor:'Elektro',tariff_group:'A',tariff_subgroup:'A4',tariff_modality:'GREEN',free_market:true,consumption_class:'INDUSTRIAL'};
const settings=():any=>({consumerUnitId:'52eaf99b-ffa6-4836-88af-39b3c8f767f1',startDate:'2026-09-01',endDate:'2026-09-30',scenario:'ACR',includedTaxes:false,selected:['TUSD_DEMAND_USED:ALL','TUSD_DEMAND_UNUSED:ALL'],embeddedCodes:[],taxes:[{code:'ICMS',rate:'18',mode:'INSIDE',included:['TUSD_DEMAND_USED:ALL']},{code:'PIS',rate:'0.65',mode:'OUTSIDE',included:['TUSD_DEMAND_USED:ALL','TUSD_DEMAND_UNUSED:ALL']},{code:'COFINS',rate:'3',mode:'OUTSIDE',included:['TUSD_DEMAND_USED:ALL','TUSD_DEMAND_UNUSED:ALL']}],cip:'137.58',other:'0',otherLabel:'',aclSource:'',reason:'Conferido na fonte e validado para este período.',expiredConfirmed:false,expiredReason:''});
describe('Biblioteca tarifária e aplicação',()=>{
 it('gera demanda em kW, tributos por base e CIP uma vez',()=>{const p=libraryPlan(record(),settings(),unit,'2026-10-01');expect(p.rows).toHaveLength(5);expect(p.rows[0]).toMatchObject({measure:'BRL_KW',amount_text:'25.200000',treatment:'NET',status:'DRAFT'});expect(p.rows[2].tax_basis.items.map((i:any)=>i.operation)).toEqual(['INCLUDE','EXCLUDE']);expect(p.rows[3].tax_basis.items.map((i:any)=>i.operation)).toEqual(['INCLUDE','INCLUDE']);expect(p.monthlyCosts[0]).toMatchObject({category:'OTHER',amount:'137.58',taxTreatment:'INCLUDED'});});
 it('não gera nova cobrança dos tributos embutidos',()=>{const d=settings();d.includedTaxes=true;d.embeddedCodes=['PIS','COFINS'];d.taxes=[];const p=libraryPlan(record(),d,unit,'2026-10-01');expect(p.rows[0].treatment).toBe('GROSS');expect(p.rows.filter(r=>r.kind==='TAX').every(r=>r.treatment==='INCLUDED'&&r.amount_text===null)).toBe(true);});
 it('não aplica a vigência de 27/08 ao agosto completo',()=>{expect(()=>libraryPlan(record(),{...settings(),startDate:'2026-08-01'},unit,'2026-10-01')).toThrow('não cobre');});
 it('não estende vigência mesmo com confirmação',()=>{expect(()=>libraryPlan(record(),{...settings(),endDate:'2027-09-01',expiredConfirmed:true,expiredReason:'uso confirmado'},unit,'2027-10-01')).toThrow('não cobre');});
 it('exige confirmação auditada para uso histórico de tabela vencida',()=>{expect(()=>libraryPlan(record(),settings(),unit,'2027-10-01')).toThrow('vencida');expect(libraryPlan(record(),{...settings(),expiredConfirmed:true,expiredReason:'Reprocessamento histórico'},unit,'2027-10-01').rows[0].notes).toContain('Reprocessamento histórico');});
 it.each([{distributor:'Cemig'},{tariff_subgroup:'A3'},{tariff_modality:'BLUE'}])('bloqueia outro enquadramento %p',patch=>{expect(()=>libraryPlan(record(),settings(),{...unit,...patch},'2026-10-01')).toThrow('enquadramento');});
 it('exige preço ACL documentado quando origem é ACR',()=>{const d={...settings(),scenario:'ACL'};expect(()=>libraryPlan(record(),d,{...unit,free_market:false},'2026-10-01')).toThrow('preço');d.selected=['TE:PEAK'];d.taxes=d.taxes.map((t:any)=>({...t,included:['TE:PEAK']}));const p=libraryPlan(record(),{...d,aclEnergyPrice:'150.25',aclSource:'Proposta simulada fornecedor X'},{...unit,free_market:false},'2026-10-01');expect(p.rows[0]).toMatchObject({amount_text:'150.25',measure:'BRL_MWH',scenario:'ACL'});});
 it('não permite usar cenário igual ao mercado original',()=>{expect(()=>libraryPlan(record(),{...settings(),scenario:'ACL'},unit,'2026-10-01')).toThrow('oposto');});
 it('rejeita componente duplicado e unidade incorreta',()=>{const r=record();r.profile.items.push(r.profile.items[0]);expect(()=>validateProfile(r.profile)).toThrow('duplicados');const q=record();q.profile.items[0].measure='BRL_KW';expect(()=>validateProfile(q.profile)).toThrow('Energia exige');});
 it('não presume alíquota ausente nem componente de base inexistente',()=>{const d=settings();d.taxes.pop();expect(()=>libraryPlan(record(),d,unit,'2026-10-01')).toThrow('individualmente');const e=settings();e.taxes[0].included=['TE:PEAK'];expect(()=>libraryPlan(record(),e,unit,'2026-10-01')).toThrow('não selecionado');});
 it('preserva números do documento A4 Verde',()=>{const r=record().profile;expect(r.items.filter(i=>i.component==='TUSD_ENERGY').map(i=>i.value)).toEqual(['1.707280','0.171900']);expect(r.items.filter(i=>i.component==='TE').map(i=>i.value)).toEqual(['0.496660','0.310680']);expect(r.startDate).toBe('2026-08-27');});
});
