import {taxMemory} from './tax-memory';
import {previewTariffs} from './tariff-preview';
import {normalizeMeasurements} from './monthly-inputs';
const unit={id:'u',organization_id:'o',customer_id:'c',free_market:true,tariff_group:'A',tariff_modality:'GREEN',distributor:'D',state:'SP'};
const measurement={id:'m',organization_id:'o',customer_id:'c',consumer_unit_id:'u',month:'2026-08',version:1,revision:2,status:'VALIDATED',validated_at:'2026-09-01',validated_by:'actor',source_reference:'Fatura revisada',unit_context:{...unit},measurements:normalizeMeasurements({consumptionTotal:'1000',consumptionPeak:'100',consumptionOffPeak:'900',demandSingle:'10',reactiveTotal:'5'})};
const tariff={id:'p',organization_id:'o',customer_id:'c',consumer_unit_id:'u',kind:'TARIFF',component_code:'TE',label:'Energia',scenario:'ACR',time_band:'PEAK',measure:'BRL_KWH',amount_text:'1',direction:'DEBIT',treatment:'NET',status:'APPROVED',revision:2,source:'Tarifa revisada',start_date:'2026-01-01',end_date:'2026-12-31',unit_context:{...unit}};
const tax=()=>({...tariff,id:'t',kind:'TAX',component_code:'ICMS',label:'ICMS',measure:'PERCENT',time_band:'ALL',amount_text:'20',treatment:'INSIDE',base_rule:'Regra aprovada',tax_basis:{version:1,items:[{parameterId:'p',revision:2,operation:'INCLUDE'}]}});
const run=(parameters:any[]=[tariff,tax()],ms:any[]=[measurement],u:any=unit)=>taxMemory(u,'2026-08',parameters,previewTariffs(u,'2026-08',{start:'2026-08-01',end:'2026-08-31'},parameters,ms));
const blocked=(r:ReturnType<typeof run>)=>{expect(r.lines).toEqual([]);expect(r.pending.length).toBeGreaterThan(0);};
describe('configured isolated tax memory',()=>{
 it('grosses up only the explicit net base for inside tax',()=>{expect(run().lines[0]).toMatchObject({base:'100.00',amount:'25.00',exactBase:'100.000000000000000',rate:'20',revision:2,source:'Tarifa revisada'});});
 it('calculates outside tax',()=>expect(run([tariff,{...tax(),treatment:'OUTSIDE'}]).lines[0].amount).toBe('20.00'));
 it('retains exact rational result for recurring fractions',()=>{const r=run([tariff,{...tax(),amount_text:'18'}]).lines[0];expect(r.amount).toBe('21.95');expect(BigInt(r.numerator)*82n).toBe(BigInt(r.denominator)*1800n);});
 it('does not prematurely round the base',()=>{const p={...tariff,amount_text:'0.00005'};const r=run([p,{...tax(),treatment:'OUTSIDE',amount_text:'50'}]).lines[0];expect(r.exactBase).toBe('0.005000000000000');expect(r.base).toBe('0.01');expect(r.amount).toBe('0.00');});
 it('rounds exact half cent upwards',()=>expect(run([{...tariff,amount_text:'0.0001'},{...tax(),treatment:'OUTSIDE',amount_text:'50'}]).lines[0].amount).toBe('0.01'));
 it('excludes references from the sum without double subtraction',()=>{const p={...tariff,id:'excluded',component_code:'TUSD_ENERGY',amount_text:'0.3'};const t=tax();t.tax_basis.items.push({parameterId:'excluded',revision:2,operation:'EXCLUDE'});const r=run([tariff,p,t]).lines[0];expect(r.amount).toBe('25.00');expect(r.references[1].exactAmount).toBeNull();});
 it.each(['organization_id','customer_id','consumer_unit_id'])('isolates tax by %s',key=>expect(run([tariff,{...tax(),[key]:'foreign'}]).lines).toEqual([]));
 it.each(['organization_id','customer_id','consumer_unit_id'])('rejects foreign base %s',key=>blocked(run([{...tariff,[key]:'foreign'},tax()])));
 it.each(['','-1','1e2','NaN','100.000001','100','1.1234567',null,18])('rejects invalid inside rate %s',amount_text=>blocked(run([tariff,{...tax(),amount_text}])));
 it('permits explicit zero rate without treating missing as zero',()=>expect(run([tariff,{...tax(),amount_text:'0'}]).lines[0].amount).toBe('0.00'));
 it('does not recalculate already included tax',()=>blocked(run([tariff,{...tax(),treatment:'INCLUDED'}])));
 it.each(['EXEMPT','NOT_APPLICABLE'])('retains %s declaration without invented monetary result',treatment=>{const r=run([tariff,{...tax(),treatment,amount_text:null,tax_basis:null}]);expect(r.lines).toEqual([]);expect(r.declarations[0].treatment).toBe(treatment);});
 it('rejects exemption with rate',()=>blocked(run([tariff,{...tax(),treatment:'EXEMPT'}])));
 it('blocks unsupported monetary base',()=>blocked(run([{...tariff,kind:'COST'},tax()])));
 it('blocks gross base instead of taxing twice',()=>blocked(run([{...tariff,treatment:'GROSS',embedded_tax_codes:['ICMS']},tax()])));
 it('blocks stale base revision',()=>blocked(run([{...tariff,revision:3},tax()])));
 it('blocks retired base',()=>blocked(run([{...tariff,status:'RETIRED'},tax()])));
 it('blocks missing measurements and pending correction',()=>{blocked(run([tariff,tax()],[]));blocked(run([tariff,tax()],[{...measurement,status:'DRAFT'}]));});
 it('blocks same tax draft correction',()=>blocked(run([tariff,tax(),{...tax(),id:'draft',status:'DRAFT'}])));
 it('blocks interacting taxes on shared base',()=>blocked(run([tariff,tax(),{...tax(),id:'pis',component_code:'PIS',amount_text:'1.65'}])));
 it('does not block unrelated exempt declaration',()=>expect(run([tariff,tax(),{...tax(),id:'pis',component_code:'PIS',treatment:'EXEMPT',amount_text:null}]).lines).toHaveLength(1));
 it('rejects repeated references',()=>{const t=tax();t.tax_basis.items.push(t.tax_basis.items[0]);blocked(run([tariff,t]));});
 it.each([null,{version:2,items:[]},{version:1,items:[]},{version:1,items:[null]},{version:1,items:[{parameterId:'p',revision:2,operation:'EXCLUDE'}]}])('rejects invalid basis %j',tax_basis=>blocked(run([tariff,{...tax(),tax_basis}])));
 it('blocks changed electrical context',()=>blocked(run([tariff,{...tax(),unit_context:{...unit,state:'RJ'}}])));
 it('blocks partial tax period',()=>blocked(run([tariff,{...tax(),start_date:'2026-08-02'}])));
 it('blocks base not covering full tax validity',()=>blocked(run([{...tariff,start_date:'2026-08-01'},tax()])));
 it.each([{source:''},{base_rule:''},{revision:0},{measure:'BRL_MONTH'},{direction:'CREDIT'},{scenario:'UNKNOWN'}])('rejects invalid metadata %j',patch=>blocked(run([tariff,{...tax(),...patch}])));
 it('has no scenario total or savings and does not mutate',()=>{const ps=[tariff,tax()],before=JSON.stringify(ps);const r=run(ps);expect(r).not.toHaveProperty('total');expect(r).not.toHaveProperty('savings');expect(JSON.stringify(ps)).toBe(before);expect(run(ps)).toEqual(r);});
});

it('does not crash on a malformed peer tax reference',()=>{const r=run([tariff,tax(),{...tax(),id:'peer',component_code:'PIS',tax_basis:{version:1,items:[null]}}]);expect(r.pending.some(p=>p.id==='peer')).toBe(true);});
