import {taxMemory} from './tax-memory';
import {previewTariffs} from './tariff-preview';
import {normalizeMeasurements} from './monthly-inputs';
const unit={id:'u',organization_id:'o',customer_id:'c',free_market:true,tariff_group:'A',tariff_modality:'GREEN',distributor:'D',state:'SP'};
const measurement={id:'m',organization_id:'o',customer_id:'c',consumer_unit_id:'u',month:'2026-08',version:1,revision:2,status:'VALIDATED',validated_at:'2026-09-01',validated_by:'actor',source_reference:'Fatura revisada',unit_context:{...unit},measurements:normalizeMeasurements({consumptionTotal:'1000',consumptionPeak:'100',consumptionOffPeak:'900',demandSingle:'10',reactiveTotal:'5'})};
const tariff={id:'p',organization_id:'o',customer_id:'c',consumer_unit_id:'u',kind:'TARIFF',component_code:'TE',label:'Energia',scenario:'ACR',time_band:'PEAK',measure:'BRL_KWH',amount_text:'1',direction:'DEBIT',treatment:'NET',status:'APPROVED',revision:2,source:'Tarifa revisada',start_date:'2026-01-01',end_date:'2026-12-31',unit_context:{...unit}};
const tax=()=>({...tariff,id:'t',kind:'TAX',component_code:'ICMS',label:'ICMS',measure:'PERCENT',time_band:'ALL',amount_text:'20',treatment:'INSIDE',base_rule:'Regra aprovada',tax_basis:{version:1,items:[{parameterId:'p',revision:2,operation:'INCLUDE'}]}});
const run=(parameters:any[]=[tariff,tax()],ms:any[]=[measurement],u:any=unit)=>taxMemory(u,'2026-08',parameters,previewTariffs(u,'2026-08',{start:'2026-08-01',end:'2026-08-31'},parameters,ms));
const blocked=(r:ReturnType<typeof run>)=>{expect(r.lines).toEqual([]);expect(r.pending.length).toBeGreaterThan(0);};
describe('configured isolated tax memory',()=>{
 it('grosses up only the explicit net base for inside tax',()=>{expect(run().lines[0]).toMatchObject({base:'100.00',amount:'25.00',exactBase:'100.000000000000000',rate:'20',revision:2,source:'Tarifa revisada'});});
 it('calculates outside tax',()=>expect(run([tariff,{...tax(),treatment:'OUTSIDE'}]).lines[0].amount).toBe('20.00'));
 it('retains exact rational result for recurring fractions',()=>{const r=run([tariff,{...tax(),amount_text:'18'}]).lines[0];expect(r.amount).toBe('21.95');expect(BigInt(r.numerator)*82n).toBe(BigInt(r.denominator)*1800n);});
 it('does not prematurely round the base',()=>{const p={...tariff,amount_text:'0.00005'};const r=run([p,{...tax(),treatment:'OUTSIDE',amount_text:'50'}]).lines[0];expect(r.exactBase).toBe('0.005000000000000');expect(r.base).toBe('0.01');expect(r.amount).toBe('0.00');});
 it('rounds exact half cent upwards',()=>expect(run([{...tariff,amount_text:'0.0001'},{...tax(),treatment:'OUTSIDE',amount_text:'50'}]).lines[0].amount).toBe('0.01'));
 it('excludes references from the sum without double subtraction',()=>{const p={...tariff,id:'excluded',component_code:'TUSD_ENERGY',amount_text:'0.3'};const t=tax();t.tax_basis.items.push({parameterId:'excluded',revision:2,operation:'EXCLUDE'});const r=run([tariff,p,t]).lines[0];expect(r.amount).toBe('25.00');expect(r.references[1].exactAmount).toBeNull();});
 it.each(['organization_id','customer_id','consumer_unit_id'])('isolates tax by %s',key=>expect(run([tariff,{...tax(),[key]:'foreign'}]).lines).toEqual([]));
 it.each(['organization_id','customer_id','consumer_unit_id'])('rejects foreign base %s',key=>blocked(run([{...tariff,[key]:'foreign'},tax()])));
 it.each(['','-1','1e2','NaN','100.000001','100','1.1234567',null,18])('rejects invalid inside rate %s',amount_text=>blocked(run([tariff,{...tax(),amount_text}])));
 it('permits explicit zero rate without treating missing as zero',()=>expect(run([tariff,{...tax(),amount_text:'0'}]).lines[0].amount).toBe('0.00'));
 it('does not recalculate already included tax',()=>blocked(run([tariff,{...tax(),treatment:'INCLUDED'}])));
 it.each(['EXEMPT','NOT_APPLICABLE'])('retains %s declaration without invented monetary result',treatment=>{const r=run([tariff,{...tax(),treatment,amount_text:null,tax_basis:null}]);expect(r.lines).toEqual([]);expect(r.declarations[0].treatment).toBe(treatment);});
 it('rejects exemption with rate',()=>blocked(run([tariff,{...tax(),treatment:'EXEMPT'}])));
 it('blocks unsupported monetary base',()=>blocked(run([{...tariff,kind:'COST'},tax()])));
 it('blocks gross base instead of taxing twice',()=>blocked(run([{...tariff,treatment:'GROSS',embedded_tax_codes:['ICMS']},tax()])));
 it('blocks stale base revision',()=>blocked(run([{...tariff,revision:3},tax()])));
 it('blocks retired base',()=>blocked(run([{...tariff,status:'RETIRED'},tax()])));
 it('blocks missing measurements and pending correction',()=>{blocked(run([tariff,tax()],[]));blocked(run([tariff,tax()],[{...measurement,status:'DRAFT'}]));});
 it('blocks same tax draft correction',()=>blocked(run([tariff,tax(),{...tax(),id:'draft',status:'DRAFT'}])));
 it('blocks interacting taxes on shared base',()=>blocked(run([tariff,tax(),{...tax(),id:'pis',component_code:'PIS',amount_text:'1.65'}])));
 it('does not block unrelated exempt declaration',()=>expect(run([tariff,tax(),{...tax(),id:'pis',component_code:'PIS',treatment:'EXEMPT',amount_text:null}]).lines).toHaveLength(1));
 it('rejects repeated references',()=>{const t=tax();t.tax_basis.items.push(t.tax_basis.items[0]);blocked(run([tariff,t]));});
 it.each([null,{version:2,items:[]},{version:1,items:[]},{version:1,items:[null]},{version:1,items:[{parameterId:'p',revision:2,operation:'EXCLUDE'}]}])('rejects invalid basis %j',tax_basis=>blocked(run([tariff,{...tax(),tax_basis}])));
 it('blocks changed electrical context',()=>blocked(run([tariff,{...tax(),unit_context:{...unit,state:'RJ'}}])));
 it('blocks partial tax period',()=>blocked(run([tariff,{...tax(),start_date:'2026-08-02'}])));
 it('blocks base not covering full tax validity',()=>blocked(run([{...tariff,start_date:'2026-08-01'},tax()])));
 it.each([{source:''},{base_rule:''},{revision:0},{measure:'BRL_MONTH'},{direction:'CREDIT'},{scenario:'UNKNOWN'}])('rejects invalid metadata %j',patch=>blocked(run([tariff,{...tax(),...patch}])));
 it('has no scenario total or savings and does not mutate',()=>{const ps=[tariff,tax()],before=JSON.stringify(ps);const r=run(ps);expect(r).not.toHaveProperty('total');expect(r).not.toHaveProperty('savings');expect(JSON.stringify(ps)).toBe(before);expect(run(ps)).toEqual(r);});
});

it('does not crash on a malformed peer tax reference',()=>{const r=run([tariff,tax(),{...tax(),id:'peer',component_code:'PIS',tax_basis:{version:1,items:[null]}}]);expect(r.pending.some(p=>p.id==='peer')).toBe(true);});

describe('explicit independent rules per unit and validity',()=>{
 const independent=(overrides:any={})=>({...tax(),...overrides,tax_basis:{...tax().tax_basis,interaction:'INDEPENDENT'}});
 it('calculates independent shared base with inside and outside treatments',()=>{const r=run([tariff,independent(),independent({id:'pis',component_code:'PIS',amount_text:'1.65',treatment:'OUTSIDE'})]);expect(r.pending).toEqual([]);expect(r.lines.map(l=>l.amount).sort()).toEqual(['1.65','25.00']);expect(r.lines[0].interaction).toBe('INDEPENDENT');expect(r.lines[0].peers).toHaveLength(1);expect(r.lines[0].peers![0].revision).toBe(2);});
 it('requires explicit rule on every participating tax',()=>blocked(run([tariff,independent(),{...tax(),id:'pis',component_code:'PIS'}])));
 it('does not accept unsupported interaction',()=>blocked(run([tariff,{...tax(),tax_basis:{...tax().tax_basis,interaction:'AUTO'}}])));
 it('does not infer a combined denominator for two inside taxes',()=>{const r=run([tariff,independent(),independent({id:'pis',component_code:'PIS',amount_text:'5'})]);expect(r.lines.map(l=>l.amount).sort()).toEqual(['25.00','5.26']);});
 it('does not use a rule from another unit or scenario',()=>{const r=run([tariff,tax(),independent({id:'pis',component_code:'PIS',consumer_unit_id:'foreign'})]);expect(r.lines).toHaveLength(1);expect(r.lines[0].peers).toEqual([]);});
 it('does not bypass monthly validity or reference revisions',()=>{const t=independent({start_date:'2026-08-02'});blocked(run([tariff,t]));const s=independent();s.tax_basis.items[0].revision=999;blocked(run([tariff,s]));});
});

describe('sequential tax composition',()=>{
 const ind=(patch:any={})=>({...tax(),...patch,tax_basis:{...tax().tax_basis,interaction:'INDEPENDENT'}});
 const seq=(refs:any[]=[{parameterId:'t',revision:2}],patch:any={})=>({...tax(),id:'b',component_code:'PIS',label:'PIS',amount_text:'10',treatment:'OUTSIDE',...patch,tax_basis:{...tax().tax_basis,interaction:'SEQUENTIAL',taxes:refs}});
 const line=(ps:any[])=>run(ps).lines.find(l=>l.id==='b');
 it('adds only explicitly selected tax to net base',()=>{const r=line([tariff,ind(),seq()]);expect(r?.amount).toBe('12.50');expect(r?.base).toBe('125.00');expect(r?.taxReferences?.[0]).toMatchObject({id:'t',revision:2,amount:'25.00'});});
 it('grosses up own rate after adding selected predecessor',()=>expect(line([tariff,ind(),seq(undefined,{treatment:'INSIDE'})])?.amount).toBe('13.89'));
 it('preserves recurring rational value instead of adding rounded tax',()=>{const r=line([tariff,ind({amount_text:'18'}),seq(undefined,{amount_text:'100'})]);expect(r?.amount).toBe('121.95');expect(BigInt(r!.numerator)*82n).toBe(BigInt(r!.denominator)*10000n);});
 it('resolves reverse input order and multiple dependency levels',()=>{const c={...seq([{parameterId:'b',revision:2}]),id:'c2',component_code:'COFINS'};const r=run([c,seq(),ind(),tariff]);expect(r.lines.find(l=>l.id==='c2')?.amount).toBe('11.25');expect(r).toEqual(run([tariff,ind(),seq(),c]));});
 it.each(['organization_id','customer_id','consumer_unit_id','scenario'])('rejects dependency in foreign %s',key=>expect(line([tariff,ind({[key]:'foreign'}),seq()])).toBeUndefined());
 it.each([{revision:3},{status:'RETIRED'},{status:'DRAFT'},{start_date:'2026-08-02'},{end_date:'2026-08-30'},{unit_context:{state:'RJ'}}])('blocks unavailable dependency %j',patch=>expect(line([tariff,ind(patch),seq()])).toBeUndefined());
 it('requires predecessor validity across the dependent entire validity',()=>expect(line([tariff,ind({start_date:'2026-08-01'}),seq()])).toBeUndefined());
 it('propagates pending measurement/base through chain',()=>{const r=run([tariff,ind(),seq()],[]);expect(r.lines).toEqual([]);});
 it.each([[],[null],[{parameterId:'t',revision:0}],[{parameterId:'t',revision:2},{parameterId:'t',revision:2}],Array.from({length:21},(_,i)=>({parameterId:'x'+i,revision:2}))].map(refs=>({refs})))('rejects malformed dependency list %j',({refs})=>expect(line([tariff,ind(),seq(refs)])).toBeUndefined());
 it('rejects self reference',()=>expect(line([tariff,ind(),seq([{parameterId:'b',revision:2}])])).toBeUndefined());
 it('detects circular references without recursion failure',()=>{const a={...seq([{parameterId:'b',revision:2}]),id:'t',component_code:'ICMS'};const r=run([tariff,a,seq()]);expect(r.lines).toEqual([]);expect(r.pending.some(p=>p.reason.includes('circular'))).toBe(true);});
 it('rejects unconfigured predecessor',()=>expect(line([tariff,tax(),seq()])).toBeUndefined());
 it('does not silently ignore dependencies in independent mode',()=>{const p=ind();p.tax_basis={...p.tax_basis,taxes:[{parameterId:'b',revision:2}]};expect(run([tariff,p]).lines).toEqual([]);});
 it('keeps zero tax as an explicit numeric dependency',()=>expect(line([tariff,ind({amount_text:'0'}),seq()])?.amount).toBe('10.00'));
});
