import {ContractConfigurationsService} from './configurations.service';
import {PERMISSIONS as P} from '../../../common/constants/permissions';
function setup(){const rpc=jest.fn().mockResolvedValue({data:{fixed_fee_monthly:0,savings_percentage:9.8},error:null}),licenses={requireEntitlement:jest.fn(async()=>{})};const service=new ContractConfigurationsService({getClient:()=>({rpc})} as any,licenses as any,{} as any);const tenant:any={organizationId:'org-a',userId:'actor',role:'admin_org',permissions:[P.ORGANIZATION_CONTRACTS_UPDATE]};const body={expectedFixed:0.01,expectedPercentage:9.7998,percentage:9.8,reason:'Administrador confirmou somente variável no contrato.',requestId:'00000000-0000-4000-8000-000000000001'};return {service,rpc,licenses,tenant,body};}
describe('Audited variable-only correction',()=>{
 it('sends server tenant and actor with optimistic values and idempotency key',async()=>{const s=setup();expect(await s.service.correctVariable('contract',s.body,s.tenant)).toEqual({fixed_fee_monthly:0,savings_percentage:9.8});expect(s.rpc).toHaveBeenCalledWith('correct_variable_management_fee',{p_organization:'org-a',p_contract:'contract',p_actor:'actor',p_expected_fixed:0.01,p_expected_percentage:9.7998,p_percentage:9.8,p_reason:s.body.reason,p_request:s.body.requestId});});
 it('rejects unauthorized roles, global scope and missing permissions before writes',async()=>{for(const patch of [{role:'operacional'},{scope:'global'},{organizationId:''},{userId:''},{permissions:[]}]){const s=setup();await expect(s.service.correctVariable('contract',s.body,{...s.tenant,...patch})).rejects.toThrow();expect(s.rpc).not.toHaveBeenCalled();}});
 it('requires license and validates complete positive confirmed values',async()=>{const s=setup();s.licenses.requireEntitlement.mockRejectedValue(Error('expired'));await expect(s.service.correctVariable('contract',s.body,s.tenant)).rejects.toThrow();expect(s.rpc).not.toHaveBeenCalled();for(const patch of [{percentage:0},{percentage:101},{requestId:'bad'},{organizationId:'other'}]){const x=setup();await expect(x.service.correctVariable('contract',{...x.body,...patch},x.tenant)).rejects.toThrow();expect(x.rpc).not.toHaveBeenCalled();}});
 it('reports conflicts without retrying or overriding the current contract',async()=>{const s=setup();s.rpc.mockResolvedValue({data:null,error:{code:'40001'}});await expect(s.service.correctVariable('contract',s.body,s.tenant)).rejects.toThrow('contrato mudou');expect(s.rpc).toHaveBeenCalledTimes(1);});
});
