'use client';
import {useEffect,useState} from 'react';
import {OperationRow,priorityLabels,statusLabels} from '@/app/lib/operations';
type Named={id:string;name:string;consumer_unit_number:string};
export const agendaDay=(value:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
export function agendaOccurs(row:OperationRow,day:string){if(!row.starts_at)return false;const start=agendaDay(row.starts_at),end=row.ends_at?agendaDay(new Date(Date.parse(row.ends_at)-1).toISOString()):start;return start<=day&&end>=day;}
export default function AgendaViews({rows,units,customers,onOpen}:{rows:OperationRow[];units:Named[];customers:{id:string;company_name:string}[];onOpen:(r:OperationRow)=>void}){
 const [now,setNow]=useState(()=>Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);const today=agendaDay(new Date(now).toISOString());const [view,setView]=useState('list'),[month,setMonth]=useState(today.slice(0,7)),[day,setDay]=useState(today),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[unit,setUnit]=useState(''),[search,setSearch]=useState('');
 const filtered=rows.filter(r=>(!status||r.status===status)&&(!priority||r.priority===priority)&&(!unit||r.consumer_unit_id===unit)&&(!search||r.title.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'))));
 const context=(r:OperationRow)=>[customers.find(c=>c.id===r.customer_id)?.company_name,units.find(u=>u.id===r.consumer_unit_id)?.name].filter(Boolean).join(' · ')||'Atividade interna';
 const first=new Date(month+'-01T12:00:00Z');const base=new Date(first);base.setUTCDate(1-first.getUTCDay());const days=Array.from({length:42},(_,i)=>{const d=new Date(base);d.setUTCDate(base.getUTCDate()+i);return d.toISOString().slice(0,10);});
 function shift(n:number){const d=new Date(first);d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7));}
 function exportList(){const csv='\uFEFF'+[['Número','Nome','Início','Término','Prazo','Status','Prioridade','Contexto'],...filtered.map(r=>[String(r.operation_number??r.id),r.title,r.starts_at??'',r.ends_at??'',r.due_at??'',statusLabels[r.status],priorityLabels[r.priority],context(r)])].map(values=>values.map(v=>'"'+(/^[\s\uFEFF]*[=+@-]|^[\t\r\n]/.test(v)?"'":'')+v.replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='agenda-energyos.csv';a.click();URL.revokeObjectURL(url);}
 const selected=filtered.filter(r=>agendaOccurs(r,day));
 return <section aria-label="Visões da agenda" className="agenda-views"><div className="agenda-toolbar"><div role="group" aria-label="Visualização"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>Lista</button><button aria-pressed={view==='calendar'} onClick={()=>setView('calendar')}>Calendário</button></div><button onClick={exportList}>Exportar lista filtrada</button><label>Buscar atividade<input className="ds-input" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Unidade<select className="ds-input" value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Todas</option>{units.map(u=><option key={u.id} value={u.id}>{u.name} · {u.consumer_unit_number}</option>)}</select></label><label>Status<select className="ds-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{Object.entries(statusLabels).filter(([v])=>['OPEN','IN_PROGRESS','WAITING','DONE','CANCELLED'].includes(v)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Prioridade<select className="ds-input" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Todas</option>{Object.entries(priorityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><p>{filtered.length} atividades no recorte consultado. Filtros de data e cliente também se aplicam ao calendário.</p>
 {view==='list'?<div className="agenda-list"><table><thead><tr><th>Nome / número</th><th>Início / prazo</th><th>Status</th><th>Prioridade</th><th>Contexto</th><th>Ações</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.title}<small>#{r.operation_number??r.id}</small></td><td>{r.starts_at?new Date(r.starts_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não informado'}<small>Prazo: {r.due_at?new Date(r.due_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Não informado'}</small></td><td><span className={'operation-badge state-'+r.status}>{statusLabels[r.status]}</span>{r.status!=='DONE'&&r.status!=='CANCELLED'&&r.due_at&&Date.parse(r.due_at)<now?<small>Prazo vencido</small>:null}</td><td><span className={'operation-badge priority-'+r.priority}>{priorityLabels[r.priority]}</span></td><td>{context(r)}</td><td><button onClick={()=>onOpen(r)} aria-label={'Abrir '+r.title}>Abrir</button></td></tr>)}</tbody></table>{!filtered.length?<p>Nenhuma atividade neste filtro.</p>:null}</div>:<><div className="agenda-month-controls"><button onClick={()=>{setMonth(today.slice(0,7));setDay(today);}}>Hoje</button><button aria-label="Mês anterior" onClick={()=>shift(-1)}>←</button><label>Mês do calendário<input className="ds-input" type="month" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value);}}/></label><button aria-label="Próximo mês" onClick={()=>shift(1)}>→</button></div><div className="agenda-calendar-layout"><aside className="operation-panel"><h2>Resumo do dia</h2><p>{new Date(day+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'full'})}</p><strong>{selected.length} atividades</strong><p>{Object.entries(priorityLabels).map(([v,l])=><span className={'operation-badge priority-'+v} key={v}>{l}: {selected.filter(r=>r.priority===v).length} </span>)}</p>{selected.map(r=><button className="agenda-summary-event" key={r.id} onClick={()=>onOpen(r)}>{r.title} · {statusLabels[r.status]}</button>)}{!selected.length?<p>Nenhuma atividade agendada para este dia neste recorte.</p>:null}</aside><div className="agenda-grid" role="group" aria-label="Calendário mensal">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(d=><strong key={d}>{d}</strong>)}{days.map(d=>{const items=filtered.filter(r=>agendaOccurs(r,d));return <button key={d} className={'agenda-day'+(d.slice(0,7)!==month?' agenda-day--outside':'')} aria-pressed={d===day} aria-label={d+' · '+items.length+' atividades'} onClick={()=>setDay(d)}><strong>{Number(d.slice(-2))}</strong>{items.length?<><span>{items.length} atividades</span>{items.slice(0,2).map(r=><small key={r.id} className={'priority-'+r.priority}>{r.title}</small>)}</>:<small>Sem atividades</small>}</button>;})}</div></div></>}
 </section>;
}
