'use client';
import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
type Status={configured:boolean;enabled:boolean;mode:string;automaticImport:boolean};
type Preview={state:string;imported:boolean;organizationId:string;months:{month:string;submarket:string;hours:number;meanBrlMwh:number}[]};
const endpoint='/api/v1/admin/integrations/ccee';
const names:Record<string,string>={SE_CO:'Sudeste / Centro-Oeste',S:'Sul',NE:'Nordeste',N:'Norte'};
export default function CceeIntegration(){
 const active=useRef(false),[status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[month,setMonth]=useState('');
 useEffect(()=>{active.current=true;apiRequest<Status>(endpoint).then(result=>{if(active.current)setStatus(result);}).catch(()=>{if(active.current)setError('Não foi possível consultar a integração CCEE.');});return()=>{active.current=false;};},[]);
 async function run(kind:'status'|'test'|'preview'){
  if(busy)return;setBusy(true);setError('');setMessage('');setPreview(null);
  try{
   if(kind==='status'){const result=await apiRequest<Status>(endpoint);if(active.current)setStatus(result);}
   else if(kind==='test'){const result=await apiRequest<{authenticated:boolean;profileConfirmed:boolean;imported:boolean}>(endpoint+'/test',{method:'POST',body:{}});if(!result.authenticated||!result.profileConfirmed||result.imported)throw new Error('Teste CCEE não confirmado.');if(active.current)setMessage('Autenticação e perfil confirmados pelo backend.');}
   else{const result=await apiRequest<Preview>(endpoint+'/pld-preview',{method:'POST',body:{month}});if(result.state!=='DRAFT'||result.imported||result.months.length!==4)throw new Error('Prévia CCEE incompleta.');if(active.current)setPreview(result);}
  }catch(e){if(active.current)setError(e instanceof Error?e.message:'Consulta CCEE não confirmada.');}finally{if(active.current)setBusy(false);}
 }
 return <Card title="Integração CCEE"><p>Consultas de leitura pelo certificado da plataforma. O teste confirma o perfil autorizado; a prévia do PLD exige todas as horas do mês.</p>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}{status?<Alert>{status.configured?'Certificado e credenciais configurados para leitura.':'Leitura pendente de configuração segura no backend.'}</Alert>:<p>Consultando configuração…</p>}<div style={{display:'flex',gap:12,flexWrap:'wrap',margin:'16px 0'}}><Button variant="secondary" disabled={busy} onClick={()=>void run('status')}>Atualizar configuração</Button><Button disabled={busy||!status?.configured} onClick={()=>void run('test')}>{busy?'Consultando…':'Testar autenticação'}</Button></div><Input label="Mês encerrado para prévia do PLD" type="month" value={month} onChange={e=>{setMonth(e.target.value);setPreview(null);}} disabled={busy}/><Button variant="secondary" disabled={busy||!status?.configured||!month} onClick={()=>void run('preview')}>Consultar prévia mensal</Button>{preview?<><h3>Prévia de {month.split('-').reverse().join('/')}</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Submercado</th><th>PLD médio (R$/MWh)</th><th>Horas conferidas</th></tr></thead><tbody>{preview.months.map(row=><tr key={row.submarket}><td>{names[row.submarket]??row.submarket}</td><td>{row.meanBrlMwh.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:6})}</td><td>{row.hours}</td></tr>)}</tbody></table></div></>:null}<p style={{fontSize:'.85rem',color:'var(--text-muted, #94a3b8)'}}>Fonte: CCEE — média aritmética dos preços horários do mês, em R$/MWh, sem tributos. A prévia não publica valores no dashboard do cliente.</p><details><summary>Configuração e próximas etapas</summary><p>Cadastre as credenciais sistêmicas, o PFX protegido, sua senha e o vínculo organização/perfil diretamente nas variáveis do backend no Railway. Não insira segredos neste painel.</p><p>Depois do teste remoto e da conferência do PLD, a importação e publicação serão integradas aos indicadores. Medições dependem dos vínculos autorizados das unidades.</p><a href="https://github.com/devccee/guia-primeiros-passos" target="_blank" rel="noopener noreferrer">Documentação oficial CCEE</a></details></Card>;
}
