'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
type Config={customerId:string;unitId:string;events:string[];channels:string[];contactIds:string[]};
type Policy={id:string;version:number;state:string;config:Config;customer_id:string;consumer_unit_id:string};
type Contact={id:string;name:string;email?:string;phone?:string;active:boolean;channels:string[]};
type Data={customers:{id:string;name:string;contacts:Contact[]}[];units:{id:string;customerId:string;name:string}[];policies:Policy[];deliveries:{id:string;policyId:string;event:string;channel:string;state:string;reason:string|null;createdAt:string;deliveryStatus:string|null}[];providers:{enabled:boolean;email:boolean;sms:boolean;whatsapp:Record<string,boolean>}};
const events:Record<string,string>={REQUEST:'Solicitações criadas ou atualizadas',AGENDA:'Alterações na agenda',DEADLINE:'Lembrete 24 horas antes do prazo',ACL_PUBLISHED:'Resultado ACL aprovado e publicado'};
const states:Record<string,string>={QUEUED:'Na fila',PREPARING:'Conferindo acesso',TRANSMITTING:'Enviando',ACCEPTED:'Aceita pelo provedor',FAILED:'Falha',UNKNOWN:'Resultado incerto — sem reenvio automático',BLOCKED:'Bloqueada',delivered:'Entregue',read:'Lida',sent:'Enviada',undelivered:'Não entregue',failed:'Falha na entrega',queued:'Na fila do provedor',sending:'Enviando'};
const empty:Config={customerId:'',unitId:'',events:[],channels:[],contactIds:[]};
export default function CustomerNoticeSettings(){
 const [data,setData]=useState<Data|null>(null),[config,setConfig]=useState<Config>(empty),[editing,setEditing]=useState<Policy|null>(null),[review,setReview]=useState<Policy|null>(null),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);const pending=useRef<{key:string;id:string}|null>(null);
 useEffect(()=>{const a=new AbortController();void apiRequest<Data>('/api/v1/customer-notices',{signal:a.signal}).then(d=>{if(!a.signal.aborted)setData(d);}).catch(e=>{if(!a.signal.aborted)setError(e.message);});return()=>a.abort();},[reload]);
 const customer=data?.customers.find(c=>c.id===config.customerId),contacts=customer?.contacts.filter(c=>c.active)??[];
 const toggle=(key:'events'|'channels'|'contactIds',v:string)=>setConfig(c=>{const values=c[key].includes(v)?c[key].filter(x=>x!==v):[...c[key],v];if(key==='channels'&&values.includes('sms')&&!values.includes('email'))values.push('email');return {...c,[key]:values,...key==='channels'?{contactIds:[]}: {}};});
 async function save(p:Policy|null,c:Config,enabled=false){if(busy)return;setBusy(true);setError('');try{const key=JSON.stringify([p?.id,p?.version,c,enabled]),request=pending.current?.key===key?pending.current:{key,id:crypto.randomUUID()};pending.current=request;await apiRequest('/api/v1/customer-notices',{method:'POST',body:{...p?{id:p.id,expectedVersion:p.version}:{},requestId:request.id,config:c,enabled}});pending.current=null;setEditing(null);setConfig(empty);setReview(null);setConfirmed(false);setMessage(enabled?'Configuração ativa para novos eventos. O envio também depende da liberação dos provedores.':'Configuração salva pausada. Revise os contatos antes de ativar.');setReload(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Falha ao configurar avisos.');}finally{setBusy(false);}}
 return <details className="operation-panel"><summary><strong>Avisos aos clientes · e-mail, WhatsApp e SMS</strong></summary><p>Escolha os eventos, destinatários e canais por unidade. Novas configurações começam pausadas. Os avisos não incluem valores financeiros, documentos ou informações internas; o cliente acessa os detalhes autorizados no portal.</p>
 {error?<p role="alert">{error}</p>:null}{message?<p role="status">{message}</p>:null}
 {!data?<p>Consultando configurações…</p>:<><p>Fila de avisos: {data.providers.enabled?'habilitada':'desativada para envios reais'} · E-mail: {data.providers.email?'configurado':'pendente'} · SMS: {data.providers.sms?'liberado':'aguarda credenciais e aprovação Twilio'} · WhatsApp: {Object.values(data.providers.whatsapp).every(Boolean)?'modelos aprovados':'aguarda aprovação dos modelos de avisos'}.</p>
 <form className="operation-form" onSubmit={e=>{e.preventDefault();void save(editing,config);}}><h3>{editing?'Editar configuração':'Preparar configuração'}</h3><div className="operation-filters"><label>Cliente<select required disabled={!!editing||busy} value={config.customerId} onChange={e=>setConfig({...empty,customerId:e.target.value})}><option value="">Selecione</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Unidade<select required disabled={!config.customerId||!!editing||busy} value={config.unitId} onChange={e=>setConfig(c=>({...c,unitId:e.target.value}))}><option value="">Selecione</option>{data.units.filter(u=>u.customerId===config.customerId).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div>
 <fieldset disabled={busy}><legend>Eventos</legend>{Object.entries(events).map(([k,l])=><label key={k}><input type="checkbox" checked={config.events.includes(k)} onChange={()=>toggle('events',k)}/>{l}</label>)}</fieldset><fieldset disabled={busy}><legend>Canais</legend>{['email','whatsapp','sms'].map(c=><label key={c}><input type="checkbox" disabled={c==='email'&&config.channels.includes('sms')} checked={config.channels.includes(c)} onChange={()=>toggle('channels',c)}/>{c==='email'?'E-mail':c==='sms'?'SMS':'WhatsApp'}</label>)}</fieldset><p>SMS acompanha o e-mail. Os contatos precisam autorizar todos os canais selecionados.</p>
 <fieldset disabled={busy}><legend>Contatos ativos do cliente</legend>{contacts.length?contacts.map(c=><label key={c.id}><input type="checkbox" disabled={!config.channels.length||!config.channels.every(channel=>c.channels.includes(channel))} checked={config.contactIds.includes(c.id)} onChange={()=>toggle('contactIds',c.id)}/>{c.name} · {c.email||'Sem e-mail'} · {c.phone||'Sem telefone'} · {c.channels.join(', ')}</label>):<p>Cadastre e autorize os canais no cliente antes de configurar os avisos.</p>}</fieldset>
 <div className="operation-actions"><button className="ds-button ds-button--primary" disabled={busy||!config.events.length||!config.channels.length||!config.contactIds.length||!config.unitId}>Salvar pausada</button>{editing?<button type="button" disabled={busy} onClick={()=>{setEditing(null);setConfig(empty);}}>Cancelar edição</button>:null}</div></form>
 <h3>Configurações por unidade</h3>{!data.policies.length?<p>Nenhuma configuração de avisos. Nenhum envio será gerado.</p>:data.policies.map(p=><article className="operation-panel" key={p.id}><strong>{data.customers.find(c=>c.id===p.config.customerId)?.name} · {data.units.find(u=>u.id===p.config.unitId)?.name}</strong><p>{p.state==='ACTIVE'?'Ativa':'Pausada'} · versão {p.version} · {p.config.channels.join(', ')}</p><p>{p.config.events.map(e=>events[e]).join(' · ')}</p><div className="operation-actions"><button disabled={busy} onClick={()=>{setEditing(p);setConfig(p.config);}}>Editar</button>{p.state==='ACTIVE'?<button disabled={busy} onClick={()=>void save(p,p.config,false)}>Pausar</button>:<button disabled={busy} onClick={()=>{setReview(p);setConfirmed(false);}}>Revisar e ativar</button>}</div></article>)}
 {review?<section className="operation-panel" role="region" aria-label="Revisar ativação de avisos"><h3>Confirmar destinatários e canais</h3><p>{review.config.events.map(e=>events[e]).join(' · ')} · {review.config.channels.join(', ')}</p>{data.customers.find(c=>c.id===review.config.customerId)?.contacts.filter(c=>review.config.contactIds.includes(c.id)).map(c=><p key={c.id}>{c.name} · {c.email} · {c.phone}</p>)}<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Revisei os destinatários e autorizações de recebimento. Novos eventos poderão gerar mensagens e tarifas dos provedores.</label><div className="operation-actions"><button className="ds-button ds-button--primary" disabled={!confirmed||busy} onClick={()=>void save(review,review.config,true)}>Ativar novos avisos</button><button disabled={busy} onClick={()=>setReview(null)}>Voltar</button></div></section>:null}
 <details><summary>Histórico de envios</summary><p>Aceita pelo provedor não confirma entrega. Mensagens com resultado incerto não são reenviadas automaticamente.</p>{!data.deliveries.length?<p>Nenhum aviso enviado.</p>:<div className="operation-table-scroll"><table><thead><tr><th>Data</th><th>Evento</th><th>Canal</th><th>Estado</th></tr></thead><tbody>{data.deliveries.map(d=><tr key={d.id}><td>{new Date(d.createdAt).toLocaleString('pt-BR')}</td><td>{events[d.event]}</td><td>{d.channel}</td><td>{states[d.deliveryStatus??d.state]??d.state}{d.reason==='EXPIRED'?' · Prazo do aviso expirado':d.reason==='ACCESS_OR_CONTACT_CHANGED'?' · Acesso ou contato alterado':''}</td></tr>)}</tbody></table></div>}</details></>}
 </details>;
}
