'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {apiRequest} from '@/app/lib/api/client';
import {priorityLabels} from '@/app/lib/operations';
type Doc={id:string;original_filename:string;file_verified:boolean;customer_id:string;consumer_unit_id:string};
type Owner={id:string;name:string};
type Finding={key:string;section:string;severity:string;message:string;href:string};
type Plan={documentId:string;unitName:string;month:string;token:string;checkedAt:string;findings:Finding[];requests:{id:string;title:string;status:string}[];canManage:boolean;message:string};
export default function DiagnosticRequestForm({docs,owners,actor,onSaved}:{docs:Doc[];owners:Owner[];actor:string;onSaved:()=>void}){
 const [documentId,setDocumentId]=useState(''),[plan,setPlan]=useState<Plan|null>(null),[finding,setFinding]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 const attempt=useRef<{payload:string;id:string}|null>(null);
 useEffect(()=>{const q=new URLSearchParams(window.location.search),id=q.get('ocrDocument');if(id&&q.getAll('ocrDocument').length===1&&/^[a-f0-9-]{36}$/i.test(id)&&docs.some(d=>d.id===id&&d.file_verified))Promise.resolve().then(()=>setDocumentId(id));},[docs]);
 useEffect(()=>{if(!documentId)return;const abort=new AbortController();const load=async()=>{setLoading(true);setPlan(null);setFinding('');setError('');try{const p=await apiRequest<Plan>('/api/v1/operations/diagnostic-documents/'+encodeURIComponent(documentId),{signal:abort.signal});if(!abort.signal.aborted){setPlan(p);setFinding(p.findings[0]?.key??'');}}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Falha ao consultar diagnóstico.');}finally{if(!abort.signal.aborted)setLoading(false);}};void load();return()=>abort.abort();},[documentId,refresh]);
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!plan||!finding||busy||loading)return;const f=new FormData(event.currentTarget);setBusy(true);setError('');try{const values={token:plan.token,findingKey:finding,responsibleId:String(f.get('owner')),dueAt:new Date(String(f.get('due'))).toISOString(),priority:String(f.get('priority')),reason:String(f.get('reason'))};const payload=JSON.stringify([documentId,values]);if(attempt.current?.payload!==payload)attempt.current={payload,id:crypto.randomUUID()};await apiRequest('/api/v1/operations/diagnostic-documents/'+encodeURIComponent(documentId),{method:'POST',body:{...values,requestId:attempt.current!.id}});attempt.current=null;onSaved();}catch(e){setError((e instanceof Error?e.message:'Falha ao salvar.')+' Se o resultado for incerto, consulte os registros antes de repetir.');}finally{setBusy(false);}}
 const selected=plan?.findings.find(f=>f.key===finding);
 return <section className="operation-panel diagnostic-request" aria-label="Solicitação a partir do diagnóstico OCR"><h2>Solicitar revisão de pendência OCR</h2><p>Cliente, unidade, competência e descrição vêm do diagnóstico atual. Escolha responsável e prazo. Nenhum dado financeiro será alterado.</p><label>Fatura de origem<select className="ds-input" value={documentId} disabled={busy} onChange={e=>{setPlan(null);setFinding('');setLoading(false);setError('');setDocumentId(e.target.value);}}><option value="">Selecione uma fatura</option>{docs.filter(d=>d.file_verified&&d.customer_id&&d.consumer_unit_id).map(d=><option key={d.id} value={d.id}>{d.original_filename}</option>)}</select></label>{loading?<p role="status">Consultando as fontes e pendências atuais…</p>:null}{error?<p role="alert">{error}</p>:null}
 {plan?<><p><strong>{plan.unitName} · {plan.month}</strong></p><p>{plan.message}</p><p>Consulta: {new Date(plan.checkedAt).toLocaleString('pt-BR')}</p><button className="ds-button" type="button" disabled={loading||busy} onClick={()=>setRefresh(v=>v+1)}>Atualizar diagnóstico</button>{plan.requests.length?<details><summary>Solicitações já vinculadas ({plan.requests.length}) — confira antes de criar outra</summary><ul>{plan.requests.map(r=><li key={r.id}>{r.title} · {r.status}</li>)}</ul></details>:null}
 {!plan.findings.length?<p role="status">Nenhum bloqueio ou revisão no diagnóstico atual. Isto não comprova aprovação financeira.</p>:<form onSubmit={save} className="operation-form"><fieldset disabled={busy||loading||!plan.canManage}><label>Pendência<select className="ds-input" value={finding} onChange={e=>setFinding(e.target.value)} required>{plan.findings.map(f=><option key={f.key} value={f.key}>{f.severity==='BLOCKER'?'Bloqueio':'Revisão'} · {f.section} · {f.message}</option>)}</select></label>{selected?<><p>{selected.message}</p><Link href={selected.href}>Abrir correção na origem</Link></>:null}<label>Responsável<select className="ds-input" name="owner" required defaultValue={actor}><option value={actor}>Eu</option>{owners.filter(o=>o.id!==actor).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Prazo da solicitação<input className="ds-input" name="due" type="datetime-local" required/></label><label>Prioridade<select className="ds-input" name="priority" defaultValue="NORMAL">{Object.entries(priorityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Motivo e instrução de revisão<textarea className="ds-input" name="reason" required minLength={3} maxLength={500}/></label><p>O backend confere novamente as fontes antes de salvar. Concluir esta solicitação não libera bloqueios da apuração.</p><button className="ds-button" disabled={busy||loading}>Criar solicitação auditada</button></fieldset></form>}</>:null}</section>;
}
