'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {Plan,planModules} from '@/app/lib/api/plans';
export default function LicenseFromPlan({onCreated}:{onCreated:()=>Promise<void>}){
 const [plans,setPlans]=useState<Plan[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;apiRequest<Plan[]>('/api/v1/licenses/plans').then(r=>{if(!cancelled)setPlans(r);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
 const plan=plans.find(p=>p.id===selected);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!plan)return;const form=e.currentTarget,f=new FormData(form);setBusy(true);setError('');setMessage('');try{await apiRequest('/api/v1/licenses/from-plan',{method:'POST',body:{planId:plan.id,version:plan.version,startDate:String(f.get('startDate')),renewalDate:String(f.get('renewalDate')),...(f.get('endDate')?{endDate:String(f.get('endDate'))}:{})}});setMessage('Licença criada com os limites e módulos desta versão do plano.');await onCreated();form.reset();setSelected('');}catch(ex){setError(ex instanceof Error?ex.message:'Não foi possível criar a licença.');}finally{setBusy(false);}}
 return <Card title="Criar licença a partir de um plano">{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}{loading?<p>Consultando catálogo…</p>:!plans.length?<p>Não há planos disponíveis. O administrador da plataforma pode cadastrá-los em Catálogo de planos.</p>:<form className="organizations-create__form" onSubmit={save}><label>Plano<select className="ds-input" required value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}><option value="">Selecione um plano</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — versão {p.version}</option>)}</select></label>{plan?<><p>{plan.max_users} usuários · {plan.max_consumer_units} unidades · {plan.documents_limit} documentos</p><p>{planModules.filter(([key])=>plan[key]).map(([,label])=>label).join(', ')||'Nenhum módulo habilitado'}</p></>:null}<Input label="Início da vigência do plano" name="startDate" type="date" required disabled={busy}/><Input label="Término da vigência do plano" name="endDate" type="date" disabled={busy}/><Input label="Renovação do plano" name="renewalDate" type="date" required disabled={busy}/><p>Os limites serão copiados desta versão. Edições futuras do catálogo não alteram esta licença.</p><Button type="submit" disabled={busy||!plan}>{busy?'Criando…':'Criar licença do plano'}</Button></form>}</Card>;
}
