'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {Plan,planModules} from '@/app/lib/api/plans';
export type PlanLicense={id:string;plan_id:string|null;plan_version:number|null;governance_revision:number;license_type:string;status:string;start_date:string;end_date:string|null;renewal_date:string;max_users:number|null;max_consumer_units:number|null;documents_limit:number;documents_unlimited:boolean;document_management:boolean;advanced_analytics:boolean;report_generation:boolean;free_market_management:boolean};
export default function LicenseFromPlan({onCreated,editing,onCancel}:{onCreated:()=>Promise<void>;editing?:PlanLicense|null;onCancel?:()=>void}){
 const [plans,setPlans]=useState<Plan[]>([]),[selected,setSelected]=useState(editing?.plan_id||''),[chosen,setChosen]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;apiRequest<Plan[]>('/api/v1/licenses/plans').then(r=>{if(cancelled)return;setPlans(r);const p=r.find(p=>p.id===editing?.plan_id);if(p)setChosen(Object.fromEntries(planModules.map(([k])=>[k,p[k]&&Boolean(editing?.[k])])));}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[editing]);
 const plan=plans.find(p=>p.id===selected);
 function select(id:string){setSelected(id);const p=plans.find(p=>p.id===id);setChosen(Object.fromEntries(planModules.map(([k])=>[k,Boolean(p?.[k])])));}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!plan)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');setMessage('');try{await apiRequest('/api/v1/licenses/from-plan',{method:'POST',body:{planId:plan.id,version:plan.version,startDate:String(f.get('startDate')),renewalDate:String(f.get('renewalDate')),endDate:f.get('endDate')?String(f.get('endDate')):undefined,status:String(f.get('status')||'ACTIVE'),modules:Object.fromEntries(planModules.map(([k])=>[k,Boolean(chosen[k])])),...(editing?{licenseId:editing.id,revision:editing.governance_revision}:{})}});setMessage('Licença salva com os limites do plano. O consumo da organização foi preservado.');await onCreated();}catch(ex){setError(ex instanceof Error?ex.message:'Não foi possível salvar a licença.');}finally{setBusy(false);}}
 return <Card title={editing?'Alterar plano, vigência e módulos':'Criar licença a partir de um plano'}>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}{loading?<p>Consultando catálogo…</p>:!plans.length?<p>Cadastre um plano disponível no Catálogo de planos antes de criar a licença.</p>:<form className="organizations-create__form" onSubmit={save}><label>Plano obrigatório<select className="ds-input" required value={selected} onChange={e=>select(e.target.value)} disabled={busy}><option value="">Selecione um plano</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — versão {p.version}</option>)}</select></label>{plan?<><p>{plan.max_users} usuários · {plan.max_consumer_units} unidades · {plan.documents_unlimited?'Documentos ilimitados':plan.documents_limit+' documentos'}</p>{editing&&editing.plan_id===plan.id&&editing.plan_version!==plan.version?<Alert>O catálogo possui uma nova versão. Ao salvar, os limites desta versão serão aplicados.</Alert>:null}<p>Módulos selecionados: {planModules.filter(([k])=>chosen[k]).length} de {planModules.filter(([k])=>plan[k]).length} disponíveis no plano.</p>{planModules.map(([k,label])=><label key={k}><input type="checkbox" checked={Boolean(chosen[k])} disabled={busy||!plan[k]} onChange={e=>setChosen({...chosen,[k]:e.target.checked})}/> {label}{!plan[k]?' — não incluído no plano':''}</label>)}</>:null}<Input label="Início da vigência" name="startDate" type="date" required defaultValue={editing?.start_date||''} disabled={busy}/><Input label="Término da vigência" name="endDate" type="date" defaultValue={editing?.end_date||''} disabled={busy}/><Input label="Renovação" name="renewalDate" type="date" required defaultValue={editing?.renewal_date||''} disabled={busy}/>{editing?<label>Status<select className="ds-input" name="status" defaultValue={editing.status.toUpperCase()} disabled={busy}><option value="ACTIVE">Ativa</option><option value="SUSPENDED">Suspensa</option><option value="EXPIRED">Expirada</option><option value="CANCELLED">Cancelada</option></select></label>:null}<p>Os limites vêm do plano. Edições futuras do catálogo não alteram esta licença automaticamente.</p><Button type="submit" disabled={busy||!plan}>{busy?'Salvando…':'Salvar registro da licença'}</Button>{onCancel?<Button variant="secondary" disabled={busy} onClick={onCancel}>Cancelar</Button>:null}</form>}</Card>;
}
