 'use client';
import {FormEvent,useCallback,useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import AgendaViews from './AgendaViews';
import EvidenceThread from './EvidenceThread';
import DiagnosticRequestForm from './DiagnosticRequestForm';
import CustomerNoticeSettings from './CustomerNoticeSettings';
import {useAuth} from '@/app/providers';
import {apiRequest} from '@/app/lib/api/client';
import {operations,notificationOrigins,notificationStates,nextOperationStatuses,statusLabels,priorityLabels,type OperationKind,type OperationRow,type NotificationRow} from '@/app/lib/operations';
type Customer={id:string;company_name:string};type Unit={id:string;customer_id:string;name:string;consumer_unit_number:string};type Doc={id:string;customer_id:string;consumer_unit_id:string;original_filename:string;file_verified:boolean};type Owner={id:string;name:string};type History={revision:number;action:string;actor_id:string;reason:string;recorded_at:string;snapshot:OperationRow};
const date=(s:string|null)=>s?new Date(s).toLocaleString('pt-BR'):'Sem prazo';
const inputDate=(s:string|null)=>s?new Date(new Date(s).getTime()-new Date(s).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const iso=(v:FormDataEntryValue|null)=>typeof v==='string'&&v?new Date(v).toISOString():undefined;
export default function OperationsWorkspace({area}:{area:OperationKind|'pld'|'notifications'}){
 const {context,hasPermission}=useAuth();const scope=context&&context.scope!=='global'?context.currentOrganization.id:'';
 return <OperationContent key={JSON.stringify([area,scope,context?.user.id,context?.scope==='organization'?context.currentOrganization.permissions:[]])} area={area} hasPermission={hasPermission} actor={context?.user.id??''} organization={scope}/>;
}
function OperationContent({area,hasPermission,actor,organization}:{area:OperationKind|'pld'|'notifications';hasPermission:(v:string)=>boolean;actor:string;organization:string}){
 const lastSave=useRef<{key:string;id:string}|null>(null),lastTransition=useRef<{key:string;id:string}|null>(null);
 const config=area!=='pld'&&area!=='notifications'?operations[area]:null;
 const canView=!!organization&&(config?hasPermission(config.view):area==='pld'?hasPermission('966188be-1b54-4594-bcd1-596ba5ac8fde'):Object.values(operations).some(c=>hasPermission(c.view)));
 const [rows,setRows]=useState<OperationRow[]>([]),[notifications,setNotifications]=useState<NotificationRow[]>([]),[owners,setOwners]=useState<Owner[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[units,setUnits]=useState<Unit[]>([]),[docs,setDocs]=useState<Doc[]>([]);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[canManage,setCanManage]=useState(false),[canPublish,setCanPublish]=useState(false);
 const [activeRecord,setActiveRecord]=useState<OperationRow|null>(null);
 const [diagnosticOpen,setDiagnosticOpen]=useState(false);
 const [notificationOrigin,setNotificationOrigin]=useState(''),[notificationPriority,setNotificationPriority]=useState(''),[notificationRead,setNotificationRead]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[filter,setFilter]=useState(''),[reload,setReload]=useState(0),[editor,setEditor]=useState<OperationRow|'new'|null>(null),[customer,setCustomer]=useState(''),[unit,setUnit]=useState(''),[dirty,setDirty]=useState(false),[history,setHistory]=useState<History[]|null>(null),[transition,setTransition]=useState<{row:OperationRow;status:string}|null>(null),[reason,setReason]=useState('');
 const load=useCallback(async(signal:AbortSignal)=>{if(!canView||area==='pld')return;setLoading(true);setError('');try{
  if(area==='notifications'){const n=await apiRequest<{rows:NotificationRow[]}>('/api/v1/operations/notifications?sources=1',{signal});if(!signal.aborted)setNotifications(n.rows);}
  else{const query=new URLSearchParams({...from?{from}:{},...to?{to}:{},...filter?{customerId:filter}:{}});const r=await apiRequest<{rows:OperationRow[];canManage:boolean;canPublish:boolean}>('/api/v1/operations/'+area+'?'+query,{signal});if(!signal.aborted){setRows(r.rows);setCanManage(r.canManage);setCanPublish(r.canPublish);}}
 }catch(e){if(!signal.aborted)setError(e instanceof Error?e.message:'Falha ao consultar operação.');}finally{if(!signal.aborted)setLoading(false);}},[area,canView,from,to,filter]);
 useEffect(()=>{const abort=new AbortController();void Promise.resolve().then(()=>{if(!abort.signal.aborted)return load(abort.signal);});return()=>abort.abort();},[load,reload]);
 useEffect(()=>{if(!canView||area==='pld'||area==='notifications')return;const abort=new AbortController();const read=async()=>{try{const [cs,us,os,ds]=await Promise.all([hasPermission('cbb2e904-0718-4eec-9396-dba899118cdd')?apiRequest<Customer[]>('/api/v1/customers',{signal:abort.signal}):[],hasPermission('b142bd7b-05a3-45ee-befd-e593066c2775')?apiRequest<Unit[]>('/api/v1/consumer-units',{signal:abort.signal}):[],apiRequest<Owner[]>('/api/v1/operations/responsible',{signal:abort.signal}),hasPermission('8f105b02-4443-49de-b188-847e0284e7ed')?apiRequest<Doc[]>('/api/v1/documents',{signal:abort.signal}):[]]);if(!abort.signal.aborted){setCustomers(cs);setUnits(us);setOwners(os);setDocs(ds);}}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Falha ao conferir vínculos.');}};void read();return()=>abort.abort();},[area,canView,hasPermission]);
 useEffect(()=>{if(area==='requests'&&new URLSearchParams(window.location.search).has('ocrDocument'))Promise.resolve().then(()=>setDiagnosticOpen(true));},[area]);
 function open(row:OperationRow|'new'){setEditor(row);setCustomer(row==='new'?'':row.customer_id??'');setUnit(row==='new'?'':row.consumer_unit_id??'');setDirty(false);setError('');setHistory(null);}
 function close(){if(dirty&&!window.confirm('Descartar as alterações ainda não salvas?'))return;setEditor(null);setDirty(false);}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!config||!editor||busy)return;const form=new FormData(event.currentTarget),row=editor==='new'?null:editor;setBusy(true);setError('');try{const values={revision:row?.revision??0,title:String(form.get('title')),description:String(form.get('description')),priority:String(form.get('priority')),responsibleId:String(form.get('responsible')),reason:String(form.get('reason')),...customer?{customerId:customer}:{},...unit?{unitId:unit}:{},...form.get('document')?{documentId:String(form.get('document'))}:{},...area==='agenda'?{startsAt:iso(form.get('starts')),endsAt:iso(form.get('ends'))}:{},...form.get('due')?{dueAt:iso(form.get('due'))}:{},...area==='requests'?{requestType:String(form.get('type'))}:{},...area==='events'?{tableText:String(form.get('table')??'')}:{}};
 const key=JSON.stringify([row?.id??null,values]);const request=lastSave.current?.key===key?lastSave.current:{key,id:crypto.randomUUID()};lastSave.current=request;const body={...values,requestId:request.id};
 const saved=await apiRequest<OperationRow>('/api/v1/operations/'+area+(row?'/'+row.id:''),{method:row?'PUT':'POST',body});setActiveRecord(saved);lastSave.current=null;setEditor(null);setDirty(false);setNotice('Registro salvo com versão e histórico.');setReload(v=>v+1);window.dispatchEvent(new Event('operations-updated'));
 }catch(e){setError((e instanceof Error?e.message:'Falha ao salvar.')+' Confira o histórico antes de repetir se o resultado for incerto.');}finally{setBusy(false);}}
 async function change(){if(!transition||busy||reason.trim().length<3)return;setBusy(true);setError('');try{const key=JSON.stringify([transition.row.id,transition.row.revision,transition.status,reason]);const request=lastTransition.current?.key===key?lastTransition.current:{key,id:crypto.randomUUID()};lastTransition.current=request;await apiRequest('/api/v1/operations/'+area+'/'+transition.row.id+'/transition',{method:'POST',body:{requestId:request.id,revision:transition.row.revision,status:transition.status,reason}});lastTransition.current=null;setActiveRecord(null);setTransition(null);setReason('');setNotice('Estado atualizado com auditoria.');setReload(v=>v+1);window.dispatchEvent(new Event('operations-updated'));}catch(e){setError(e instanceof Error?e.message:'Falha ao atualizar.');}finally{setBusy(false);}}
 async function showHistory(row:OperationRow){setBusy(true);setError('');try{setHistory(await apiRequest<History[]>('/api/v1/operations/'+area+'/'+row.id+'/history'));}catch(e){setError(e instanceof Error?e.message:'Falha ao consultar histórico.');}finally{setBusy(false);}}
 async function markRead(key:string){setBusy(true);try{await apiRequest('/api/v1/operations/notifications/read',{method:'POST',body:{key}});setReload(v=>v+1);window.dispatchEvent(new Event('operations-updated'));}catch(e){setError(e instanceof Error?e.message:'Falha ao marcar leitura.');}finally{setBusy(false);}}
 if(!canView)return <p role="alert">Acesso indisponível nesta organização ou perfil.</p>;
 if(area==='pld')return <section className="operation-panel"><h1>PLD</h1><p role="status">Aguardando API CCEE</p><p>A integração permanece suspensa até concluir a validação do certificado e habilitar a Plataforma de Integração. Valores de PLD e sincronização serão disponibilizados após essa etapa.</p></section>;
 const label=area==='notifications'?'Notificações':config?.label;
 return <section className="operation-workspace"><header className="operation-heading"><div><p>Operação</p><h1>{label}</h1><p>{area==='notifications'?'Acompanhe solicitações, atividades e eventos da organização.':'Organize a rotina por cliente, unidade, prazo e responsável.'}</p></div><button disabled={loading||busy} onClick={()=>setReload(v=>v+1)}>Atualizar</button>{canManage&&!editor?<button className="ds-button ds-button--primary" onClick={()=>open('new')}>{area==='agenda'?'Nova agenda':'Novo registro'}</button>:null}</header>
 {area==='requests'&&canManage&&hasPermission('8f105b02-4443-49de-b188-847e0284e7ed')&&hasPermission('60f9690a-145b-4dba-b23f-9f945baca296')?<button disabled={!!editor} onClick={()=>setDiagnosticOpen(v=>!v)}>{diagnosticOpen?'Ocultar revisão OCR':'Criar solicitação de pendência OCR'}</button>:null}
 {area==='requests'&&canManage&&diagnosticOpen&&hasPermission('8f105b02-4443-49de-b188-847e0284e7ed')&&hasPermission('60f9690a-145b-4dba-b23f-9f945baca296')?<DiagnosticRequestForm key={organization+actor} docs={docs} owners={owners} actor={actor} onSaved={()=>{setDiagnosticOpen(false);setNotice('Solicitação criada com origem e histórico. O diagnóstico financeiro permanece independente.');setReload(v=>v+1);window.dispatchEvent(new Event('operations-updated'));}}/>:null}
 {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 {area==='notifications'&&hasPermission('51da7cca-8196-4135-84ce-f989be5ee594')?<CustomerNoticeSettings key={organization+actor}/>:null}
 {area==='notifications'?<><p>Notificações internas. Marcar como lida não resolve pendências nem aprova dados financeiros. OCR: últimos 7 dias; prazos: até 30 dias antes/depois. A leitura desta lista não envia mensagens. Os avisos aos clientes usam a configuração independente acima.</p><div className="operation-filters"><label>Origem<select value={notificationOrigin} onChange={e=>setNotificationOrigin(e.target.value)}><option value="">Todas</option>{Object.entries(notificationOrigins).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Prioridade<select value={notificationPriority} onChange={e=>setNotificationPriority(e.target.value)}><option value="">Todas</option>{Object.entries(priorityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Leitura<select value={notificationRead} onChange={e=>setNotificationRead(e.target.value)}><option value="">Todas</option><option value="unread">Não lidas</option><option value="read">Lidas</option></select></label></div><p role="status">{notifications.filter(n=>(!notificationOrigin||n.origin===notificationOrigin)&&(!notificationPriority||n.priority===notificationPriority)&&(!notificationRead||n.read===(notificationRead==='read'))).length} notificações neste filtro.</p>{loading?<p role="status">Consultando notificações…</p>:notifications.length===0&&!error?<p>Nenhuma notificação operacional disponível.</p>:null}<div className="operation-cards">{notifications.filter(n=>(!notificationOrigin||n.origin===notificationOrigin)&&(!notificationPriority||n.priority===notificationPriority)&&(!notificationRead||n.read===(notificationRead==='read'))).map(n=><article className="operation-panel" key={n.key}><p>{notificationOrigins[n.origin]} · {priorityLabels[n.priority]} · {n.read?'Lida':'Não lida'}</p><h2>{n.title}</h2>{n.description?<p>{n.description}</p>:null}<p>{date(n.date)} · {notificationStates[n.status]??n.status}{n.overdue?' · Prazo vencido':''}</p><Link href={n.href}>Abrir origem</Link>{!n.read?<button disabled={busy} onClick={()=>void markRead(n.key)}>Marcar como lida</button>:null}</article>)}</div></>:<>
 <div className="operation-filters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Cliente<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label></div>
 {editor?<form className="operation-panel operation-form operation-accordion" onInvalidCapture={e=>{let d=(e.target as HTMLElement).closest('details');while(d){d.open=true;d=d.parentElement?.closest('details')??null;}}} onSubmit={save} onChange={()=>setDirty(true)} key={editor==='new'?'new':editor.id}><h2>{editor==='new'?'Novo registro':'Editar registro'}</h2><p>O número, solicitante e horário são registrados automaticamente ao salvar. Documentos e respostas ficam disponíveis nos detalhes após o registro.</p><details open><summary>1. Identificação e contexto</summary><label>Título<input name="title" required minLength={3} maxLength={160} defaultValue={editor==='new'?'':editor.title}/></label><label>Descrição<textarea name="description" required minLength={3} maxLength={10000} rows={4} defaultValue={editor==='new'?'':editor.description}/></label><label>Cliente<select value={customer} required={area==='requests'} onChange={e=>{setCustomer(e.target.value);setUnit('');}}><option value="">Atividade interna</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><label>Unidade<select value={unit} disabled={!customer} onChange={e=>setUnit(e.target.value)}><option value="">Todas as unidades do cliente / não vinculada</option>{units.filter(u=>u.customer_id===customer).map(u=><option key={u.id} value={u.id}>{u.name||u.consumer_unit_number}</option>)}</select></label></details><details><summary>2. Responsável e prazos</summary><label>Responsável<select name="responsible" required defaultValue={editor==='new'?actor:editor.responsible_id}><option value={actor}>Eu</option>{owners.filter(o=>o.id!==actor).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Prioridade<select name="priority" defaultValue={editor==='new'?'NORMAL':editor.priority}>{Object.entries(priorityLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 {area==='agenda'?<><label>Início<input type="datetime-local" name="starts" required defaultValue={editor==='new'?'':inputDate(editor.starts_at)}/></label><label>Término<input type="datetime-local" name="ends" defaultValue={editor==='new'?'':inputDate(editor.ends_at)}/></label></>:null}<label>Prazo<input type="datetime-local" name="due" required={area==='requests'} defaultValue={editor==='new'?'':inputDate(editor.due_at)}/></label>
 {area==='requests'?<label>Tipo da solicitação<select name="type" defaultValue={editor==='new'?'INVOICE':editor.request_type??'INVOICE'}><option value="INVOICE">Enviar fatura</option><option value="DOCUMENT">Enviar documento</option><option value="INFORMATION">Enviar informação</option><option value="VALIDATION">Validar informação</option><option value="ACTIVITY">Realizar atividade</option></select></label>:null}
 {area==='events'?<label>Tabela / informação complementar<textarea name="table" rows={4} maxLength={6000} defaultValue={editor==='new'?'':editor.table_text??''}/></label>:null}
 </details><details><summary>3. Documentos e confirmação</summary><label>Documento relacionado<select name="document" defaultValue={editor==='new'?'':editor.document_id??''}><option value="">Sem documento</option>{docs.filter(d=>d.file_verified&&d.customer_id===customer&&(!unit||d.consumer_unit_id===unit)).map(d=><option key={d.id} value={d.id}>{d.original_filename}</option>)}</select></label><label>Motivo e fonte<textarea name="reason" required minLength={3} maxLength={500} rows={2}/></label><p>{area==='events'?'Eventos começam em rascunho. Somente gestor/administrador publica após revisão.':'Gravação operacional com histórico; não altera dados financeiros.'}</p></details><button disabled={busy}>Salvar registro</button><button type="button" disabled={busy} onClick={close}>Cancelar edição</button></form>:null}
 {loading?<p role="status">Consultando registros…</p>:rows.length===0&&!error?<p>Nenhum registro para este recorte. Cadastre a primeira atividade ou ajuste os filtros.</p>:null}<div className="operation-cards">{(area==='agenda'?[]:rows).map(r=><article className="operation-panel" key={r.id}><p>{priorityLabels[r.priority]} · {statusLabels[r.status]} · versão {r.revision}</p><h2>#{r.operation_number??r.id} · {r.title}</h2><p>Solicitado por: {r.requested_by_name??owners.find(o=>o.id===r.created_by)?.name??r.created_by} · Abertura: {date(r.created_at??null)}</p><p>Unidade: {units.find(u=>u.id===r.consumer_unit_id)?.consumer_unit_number??'Não vinculada'} · {units.find(u=>u.id===r.consumer_unit_id)?.name}</p><p className="operation-text">{r.description}</p>{r.table_text?<pre className="operation-table-text">{r.table_text}</pre>:null}<p>{r.starts_at?'Início: '+date(r.starts_at)+' · ':''}Prazo: {date(r.due_at)}</p><p>Responsável: {r.responsible_id===actor?'Eu':owners.find(o=>o.id===r.responsible_id)?.name||'Usuário '+r.responsible_id.slice(0,8)} · Cliente: {customers.find(c=>c.id===r.customer_id)?.company_name||'Atividade interna'}</p>{r.document_id?<><Link href="/backoffice/documents">Consultar documento privado</Link> <Link href={'/backoffice/contracts?ocrDocument='+encodeURIComponent(r.document_id)+'&area=preparation'}>Conferir diagnóstico e correções atuais</Link></>:null}<div className="operation-actions"><button disabled={busy} onClick={()=>setActiveRecord(r)}>Abrir registro e evidências</button><button disabled={busy} onClick={()=>void showHistory(r)}>Histórico</button>{canManage&&!['PUBLISHED','ARCHIVED','DONE','CANCELLED'].includes(r.status)?<button disabled={busy||!!editor} onClick={()=>open(r)}>Editar</button>:null}{canManage?nextOperationStatuses(r.kind,r.status).filter(s=>s!=='PUBLISHED'||canPublish).map(s=><button key={s} disabled={busy} onClick={()=>{setTransition({row:r,status:s});setReason('');}}>{statusLabels[s]}</button>):null}</div></article>)}</div>
 {area==='agenda'?<AgendaViews rows={rows} units={units} customers={customers} onOpen={r=>setActiveRecord(r)}/>:null}
 {activeRecord?<section className="operation-panel" role="region" aria-label="Detalhes do registro"><h2>#{activeRecord.operation_number??activeRecord.id} · {activeRecord.title}</h2><p>{statusLabels[activeRecord.status]} · versão {activeRecord.revision}</p><p>Solicitado por: {activeRecord.requested_by_name??owners.find(o=>o.id===activeRecord.created_by)?.name??activeRecord.created_by} · Abertura: {date(activeRecord.created_at??null)}</p><p>Cliente: {customers.find(c=>c.id===activeRecord.customer_id)?.company_name??'Atividade interna'} · Código: {activeRecord.customer_id??'Não vinculado'}</p><p>Unidade: {units.find(u=>u.id===activeRecord.consumer_unit_id)?.consumer_unit_number??'Não vinculada'} · {units.find(u=>u.id===activeRecord.consumer_unit_id)?.name}</p><p className="operation-text">{activeRecord.description}</p><button onClick={()=>setActiveRecord(null)}>Fechar detalhes</button><button disabled={busy} onClick={()=>void showHistory(activeRecord)}>Histórico</button>{canManage&&!['PUBLISHED','ARCHIVED','DONE','CANCELLED'].includes(activeRecord.status)?<button disabled={busy||!!editor} onClick={()=>open(activeRecord)}>Editar registro</button>:null}{canManage?nextOperationStatuses(activeRecord.kind,activeRecord.status).filter(s=>s!=='PUBLISHED'||canPublish).map(s=><button key={s} disabled={busy} onClick={()=>{setTransition({row:activeRecord,status:s});setReason('');}}>{statusLabels[s]}</button>):null}{activeRecord.customer_id&&activeRecord.consumer_unit_id&&hasPermission('8f105b02-4443-49de-b188-847e0284e7ed')?<EvidenceThread key={activeRecord.id} id={activeRecord.id} kind={activeRecord.kind} documents={docs} canUpload={hasPermission('8f3ff5eb-157a-468a-91af-6f89d92e23a7')}/>:<p>Vincule cliente e unidade e confira a permissão de documentos para a troca de evidências.</p>}</section>:null}
 {transition?<section className="operation-panel" role="region" aria-label="Confirmar alteração de estado"><h2>{statusLabels[transition.status]} · {transition.row.title}</h2><label>Justificativa<textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||reason.trim().length<3} onClick={()=>void change()}>Confirmar alteração</button><button disabled={busy} onClick={()=>setTransition(null)}>Voltar</button></section>:null}
 {history?<section className="operation-panel"><h2>Histórico auditado</h2><button onClick={()=>setHistory(null)}>Fechar histórico</button>{history.map(h=><article key={h.revision}><h3>Versão {h.revision} · {h.action}</h3><p>{date(h.recorded_at)} · Autor: {h.actor_id===actor?'Eu':h.actor_id}</p><p>Motivo: {h.reason}</p><p>{h.snapshot.title} · {statusLabels[h.snapshot.status]}</p><p className="operation-text">{h.snapshot.description}</p></article>)}</section>:null}
 </> }</section>;
}
