 'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Bell} from 'lucide-react';
import {useAuth} from '@/app/providers';
import {apiRequest} from '@/app/lib/api/client';
import {operations,type NotificationRow} from '@/app/lib/operations';
export default function OperationNotificationBell(){const {context,hasPermission}=useAuth();const scope=context&&context.scope!=='global'?context.currentOrganization.id:'';const can=!!scope&&Object.values(operations).some(p=>hasPermission(p.view));return can?<BellCounter key={JSON.stringify([scope,context?.user.id,context?.scope==='organization'?context.currentOrganization.permissions:[]])}/>:null;}
function BellCounter(){const [count,setCount]=useState<number|null>(null),[failed,setFailed]=useState(false);useEffect(()=>{const abort=new AbortController();const load=async()=>{if(document.visibilityState==='hidden')return;try{const n=await apiRequest<{rows:NotificationRow[]}>('/api/v1/operations/notifications',{signal:abort.signal});if(!abort.signal.aborted){setCount(n.rows.filter(r=>!r.read).length);setFailed(false);}}catch{if(!abort.signal.aborted)setFailed(true);}};void load();const interval=window.setInterval(()=>void load(),60000);window.addEventListener('operations-updated',load);document.addEventListener('visibilitychange',load);return()=>{abort.abort();clearInterval(interval);window.removeEventListener('operations-updated',load);document.removeEventListener('visibilitychange',load);};},[]);return <div className="operation-topbar"><Link className="operation-bell" href="/backoffice/operation/notifications" aria-label={failed?'Consultar notificações — atualização indisponível':count===null?'Consultar notificações':'Notificações: '+count+' não lidas'}><Bell size={20}/>{count!==null&&count>0?<span>{count}</span>:null}<span>Notificações</span>{failed?<span aria-hidden="true">!</span>:null}</Link></div>;}
