'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import DocumentDialog from '@/app/backoffice/documents/DocumentDialog';
import {Alert,Button,Card,Input} from './ui';
import {apiRequest} from '@/app/lib/api/client';
import {ClientAddition,loadPortalLicense,PortalLicense,PortalLicenses,PortalModule,portalModules} from '@/app/lib/api/portal-licenses';
import {PlanLicense} from './LicenseFromPlan';
type Customer={id:string;company_name:string;deleted_at?:string|null};
type Editor={kind:'license';row?:PortalLicense}|{kind:'addition';row?:ClientAddition;id:string}|{kind:'policy'};
const legacy:PortalLicenses={available:false,enabled:false,revision:0,licenses:[],additions:[],history:[]};
function moduleIncluded(parent:PlanLicense|null,module:PortalModule){
 if(!parent)return false;
 const reports=parent.report_generation&&parent.free_market_management;
 return module==='reports'||module==='energy_prices'?reports:module==='forecasts'?reports&&parent.advanced_analytics:module==='bot'?reports&&parent.bot_energy_rag:module==='acl'?parent.free_market_management:parent.document_management;
}
export default function PortalLicenseManagement({platform,parent}:{platform:boolean;parent:PlanLicense|null}){
 const [state,setState]=useState<PortalLicenses|null>(null),[customers,setCustomers]=useState<Customer[]>([]),[editor,setEditor]=useState<Editor|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{const value=await loadPortalLicense('/api/v1/licenses/portal',legacy);setState(value);if(value.available&&platform)setCustomers((await apiRequest<Customer[]>('/api/v1/customers')).filter(c=>!c.deleted_at));setError('');}catch(e){setState(null);setError(e instanceof Error?e.message:'Não foi possível conferir as licenças.');}},[platform]);
 useEffect(()=>{void Promise.resolve().then(load);},[load]);
 function open(value:Editor){setError('');setNotice('');setEditor(value);}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editor||!state||busy)return;const f=new FormData(event.currentTarget);let path='/api/v1/licenses/portal';let body:Record<string,unknown>={reason:String(f.get('reason')||'').trim()};
  if(editor.kind==='policy'){path+='/policy';body={...body,revision:state.revision,enabled:!state.enabled};}
  else {body={...body,revision:editor.row?.revision??0,status:String(f.get('status')),starts:String(f.get('starts')),ends:String(f.get('ends'))};if(editor.kind==='license')body={...body,customerId:String(f.get('customerId')),modules:portalModules.filter(([key])=>f.has(key)).map(([key])=>key),maxUsers:Number(f.get('maxUsers')),maxUnits:Number(f.get('maxUnits'))};else{path+='/additions';body={...body,id:editor.id,slots:Number(f.get('slots')),reference:String(f.get('reference')||'').trim()};}}
  setBusy(true);setError('');try{await apiRequest(path,{method:'POST',body});setEditor(null);setNotice('Condições registradas e auditadas. Nenhum convite, cobrança ou mudança de função foi realizado.');await load();}catch(e){setError(e instanceof Error?e.message:'Registro não confirmado.');}finally{setBusy(false);}
 }
 const cap=state?.capacity,name=(id:string)=>customers.find(c=>c.id===id)?.company_name||id;
 const actions={display:'flex',gap:'0.75rem',flexWrap:'wrap' as const,alignItems:'center'};
 return <section aria-label="Licenças do Portal"><h2>Portal do cliente e usuários do plano</h2>{error?<Alert variant="error">{error}</Alert>:null}{notice?<Alert>{notice}</Alert>:null}
 {!state?<p>Conferência das condições do Portal indisponível. <Button variant="secondary" onClick={()=>void load()}>Atualizar</Button></p>:!state.available?<Card title="Implantação com ativação desligada"><p>Os acessos e cadastros existentes continuam com as condições atuais. A equipe deve conferir os limites do plano e as licenças de cada cliente antes da ativação.</p></Card>:<>
 <Card title={state.enabled?'Controle do Portal ativo':'Controle do Portal ainda desligado'}><div style={{overflowX:'auto'}}><table style={{width:'100%'}}><thead><tr><th scope="col">Usuários no plano</th><th scope="col">Contratado</th><th scope="col">Usuários ativos</th><th scope="col">Disponível</th></tr></thead><tbody><tr><td>{cap?.base??'Não definido'}</td><td>{cap?.contracted??'Não definido'}</td><td>{cap?.used??'—'}</td><td>{cap?.available??'—'}</td></tr></tbody></table></div><p>Backoffice e Portal compartilham a quantidade de usuários contratada. Cada vínculo ativo ocupa uma vaga; cadastrar a empresa não consome vaga. A desativação do usuário libera a vaga. Ao atingir o limite, solicite revisão do plano ao administrador da plataforma.</p>{!cap?.configured?<Alert>Regularize o limite de usuários e a licença da organização antes de ativar.</Alert>:null}<div style={actions}><Button variant="secondary" onClick={()=>void load()}>Atualizar</Button>{platform?<><Button disabled={!parent} onClick={()=>open({kind:'license'})}>Inserir licença do Portal</Button><Button variant="secondary" disabled={!cap?.configured&&!state.enabled} onClick={()=>open({kind:'policy'})}>{state.enabled?'Desativar controle':'Revisar ativação'}</Button></>:null}</div></Card>
 {state.licenses.map(row=><Card key={row.id} title={row.customers?.company_name||name(row.customer_id)}><p>{row.status==='ACTIVE'?'Ativa':row.status==='SUSPENDED'?'Suspensa':'Cancelada'} · {row.starts} a {row.ends} · versão {row.revision}</p><p>{row.max_users} usuários externos · {row.max_units} unidades · {portalModules.filter(([key])=>row.modules.includes(key)).map(([,label])=>label).join(', ')||'Nenhum módulo'}</p>{platform?<Button variant="secondary" onClick={()=>open({kind:'license',row})}>Editar licença</Button>:null}</Card>)}

 <details><summary>Histórico de alterações ({state.history.length} mais recentes)</summary>{state.history.map(row=><article key={row.id}><p><strong>{row.actor_name||'Nome não cadastrado'}</strong> · {row.actor_affiliation==='platform'?'Administrador da plataforma':row.actor_affiliation} · {new Date(row.created_at).toLocaleString('pt-BR')}</p><p>{row.kind==='PORTAL_LICENSE'?'Licença do Portal':row.kind==='CLIENT_ADDITION'?'Acréscimo de clientes':'Ativação do controle'}: {row.reason}</p><small>Identificador do responsável: {row.actor_id}</small></article>)}</details>
 </>}
 {editor&&state?.available&&platform?<DocumentDialog label={editor.kind==='license'?'Licença do Portal':editor.kind==='addition'?'Acréscimo de clientes':'Revisar ativação'} busy={busy} onClose={()=>setEditor(null)}><h2>{editor.kind==='license'?'Licença do Portal':editor.kind==='addition'?'Acréscimo de clientes':'Revisar ativação'}</h2><form className="organizations-create__form" onSubmit={save}>
 {editor.kind==='policy'?<p>{state.enabled?'O controle adicional será desligado. As permissões atuais continuarão obrigatórias.':'O backend conferirá a cota compartilhada de usuários e as licenças dos clientes vinculados antes de ativar. Não será criado acesso para usuários.'}</p>:<>
 {editor.kind==='license'?<><label>Cliente<select className="ds-input" name="customerId" required defaultValue={editor.row?.customer_id||''} disabled={busy||!!editor.row}><option value="" disabled>Selecione</option>{customers.filter(c=>editor.row?.customer_id===c.id||!state.licenses.some(l=>l.customer_id===c.id)).map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label>{editor.row?<input type="hidden" name="customerId" value={editor.row.customer_id}/>:null}<Input label="Usuários externos permitidos neste cliente" name="maxUsers" type="number" min={0} max={parent?.max_users??2147483647} step={1} required defaultValue={editor.row?.max_users??0} disabled={busy}/><Input label="Limite de unidades" name="maxUnits" type="number" min={0} max={parent?.max_consumer_units??2147483647} step={1} required defaultValue={editor.row?.max_units??0} disabled={busy}/>{portalModules.map(([key,label])=><label key={key}><input name={key} type="checkbox" defaultChecked={editor.row?.modules.includes(key)??false} disabled={busy||!moduleIncluded(parent,key)}/> {label}{!moduleIncluded(parent,key)?' — não incluído na licença da organização':''}</label>)}<p>Este limite distribui vagas do plano, sem criar vagas adicionais. A licença não concede função nem associa pessoas ao cliente. Os módulos devem estar incluídos na licença da organização.</p></>:<><Input label="Vagas de clientes adicionais" name="slots" type="number" min={1} max={2147483647} step={1} required defaultValue={editor.row?.slots??1} disabled={busy}/><Input label="Referência da aprovação comercial" name="reference" required minLength={3} maxLength={500} defaultValue={editor.row?.reference||''} disabled={busy}/><p>Este registro não gera pagamento, contrato ou cobrança automática.</p></>}
 <Input label="Início da vigência" name="starts" type="date" required min={parent?.start_date} max={parent?.end_date||undefined} defaultValue={editor.row?.starts||''} disabled={busy}/><Input label="Término da vigência" name="ends" type="date" required min={parent?.start_date} max={parent?.end_date||undefined} defaultValue={editor.row?.ends||''} disabled={busy}/><label>Status<select className="ds-input" name="status" defaultValue={editor.row?.status||'ACTIVE'} disabled={busy}><option value="ACTIVE">Ativo</option>{editor.kind==='license'?<option value="SUSPENDED">Suspenso</option>:null}<option value="CANCELLED">Cancelado</option></select></label></>}
 <Input label="Justificativa da alteração" name="reason" required minLength={3} maxLength={1000} disabled={busy}/><div style={actions}><Button type="submit" disabled={busy}>{busy?'Conferindo…':editor.kind==='policy'?'Confirmar condições':'Salvar condições'}</Button><Button type="button" variant="secondary" disabled={busy} onClick={()=>setEditor(null)}>Cancelar</Button></div></form></DocumentDialog>:null}
 </section>;
}
