const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const source=fs.readFileSync('app/backoffice/documents/assistant-inbox.ts','utf8'),compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const mod={exports:{}};new Function('exports',compiled)(mod.exports);
const {inboxScope,readInbox,writeInbox,pendingFields}=mod.exports;
const now=100000000,documentId='7b909de6-6f2a-4523-85d9-90b8257a2c37';
const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};
const context={scope:'organization',user:{id:'actor'},currentOrganization:{id:'org',role:'operacional',permissions:['view','process']}};
const key=inboxScope(context);
writeInbox(storage,key,[{id:documentId,addedAt:now,token:'secret',plan:{value:'private'}}]);
assert.deepEqual(readInbox(storage,key,now),[{id:documentId,addedAt:now}]);
assert.ok(!map.get(key).includes('secret'));assert.ok(!map.get(key).includes('private'));
for(const other of [{...context,user:{id:'other'}},{...context,currentOrganization:{...context.currentOrganization,id:'other'}},{...context,currentOrganization:{...context.currentOrganization,role:'consulta'}},{...context,currentOrganization:{...context.currentOrganization,permissions:[]}}])assert.deepEqual(readInbox(storage,inboxScope(other),now),[]);
assert.equal(inboxScope({scope:'global'}),'');assert.equal(inboxScope(null),'');
map.set(key,JSON.stringify([{id:documentId,addedAt:now},{id:documentId,addedAt:now},{id:'bad',addedAt:now},{id:documentId,addedAt:now+1}]));assert.equal(readInbox(storage,key,now).length,1);
assert.deepEqual(readInbox(storage,key,now+24*60*60*1000+2),[]);
map.set(key,'broken');assert.deepEqual(readInbox(storage,key,now),[]);
assert.deepEqual(readInbox({getItem(){throw Error('blocked');}},key,now),[]);
assert.doesNotThrow(()=>writeInbox({setItem(){throw Error('blocked');}},key,[]));
assert.equal(pendingFields([{confirmed:true,canConfirm:true},{confirmed:false,canConfirm:true},{confirmed:false,canConfirm:false}]),2);
console.log('Inbox: reload pointers only, identity/organization/profile/permission isolation, expiry, duplicates, malformed/storage-denied recovery and pending human fields PASS');
