/* Isolated DOM: real tariff memory and preparation screen, no production writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const {JSDOM}=require('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});
for(const k of ['window','document','HTMLElement','HTMLSelectElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);


const ui={Button:({children,variant,...p})=>React.createElement('button',{'data-variant':variant,...p},children),Input:({label,...p})=>React.createElement('label',null,label,React.createElement('input',p)),Card:({title,children})=>React.createElement('section',null,React.createElement('h2',null,title),children),Alert:({children})=>React.createElement('div',{role:'alert'},children)};
let named=true,calls=[];const record=()=>({id:'record',organization_id:'org',consumer_unit_id:'u',month:'2026-10',version:1,revision:2,status:'VALIDATED',measurements:{consumptionTotal:'100'},costs:{noCosts:true,items:[]},created_by:'id-author',updated_by:'id-editor',validated_by:'id-validator',created_by_name:named?'Ana <Equipe>':null,updated_by_name:named?'Bruno':null,validated_by_name:named?'Carla':null,updated_at:'2026-09-25T12:00:00Z',validated_at:'2026-09-25T12:00:00Z'});
const original=Module._load;Module._load=function(name,parent,main){if(name==='@/app/components/ui')return ui;if(name==='@/app/providers')return {useAuth:()=>({hasPermission:()=>true})};if(name==='@/app/lib/api/client')return {apiRequest:async(url,options)=>{calls.push({url,options});return url.endsWith('/events')?[{id:'event',revision:1,action:'CREATED',recorded_at:'2026-09-25T12:00:00Z',snapshot:{...record(),created_by_name:'Autora histórica'}}]:{rows:[record()],canValidate:true};}};if(name.startsWith('@/app/'))return original.call(this,path.resolve(__dirname,'..',name.slice(2)),parent,main);return original.call(this,name,parent,main);};
const Costs=require('../app/backoffice/contracts/MonthlyCosts.tsx').default,Inputs=require('../app/backoffice/contracts/MonthlyInputs.tsx').default;
const root=createRoot(document.getElementById('root'));let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};const props={customerId:'c',units:[{id:'u',customer_id:'c',name:'Unidade',consumer_unit_number:'001'}],initialContext:{customerId:'c',unitId:'u',month:'2026-10'},onDirty:()=>{}};
(async()=>{try{for(const Component of [Inputs,Costs]){
 named=true;calls=[];await act(async()=>root.render(React.createElement(Component,props)));
 ok(document.body.textContent.includes('Autor: Ana <Equipe>'),'author readable and escaped');ok(document.body.textContent.includes('Última alteração: Bruno')&&document.body.textContent.includes('Validado por Carla'),'editor and validator labels');ok(!document.body.textContent.includes('id-author')&&!!document.querySelector('[title="Identificador de auditoria: id-author"]'),'technical id remains in tooltip');
 await act(async()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.startsWith('Histórico')).click());ok(document.body.textContent.includes('Autora histórica'),'historical snapshot label');ok(calls.every(c=>!c.options),'read-only rendering and history');
 await act(async()=>root.render(React.createElement('div')));named=false;await act(async()=>root.render(React.createElement(Component,props)));ok(document.body.textContent.includes('Nome não disponível')&&!document.body.textContent.includes('id-author'),'explicit fallback');await act(async()=>root.render(React.createElement('div')));
}console.log(checks+' audit author interface checks passed');}finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
