/* Isolated DOM/API: no production writes or financial recalculation in the UI. */
const assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),ts=require('typescript');
const {JSDOM}=require('jsdom'),dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});
for(const k of ['window','document','HTMLElement','HTMLInputElement','HTMLSelectElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,f);
let api;const routes=[];const original=Module._load;Module._load=function(name,parent,main){if(name==='@/app/lib/api/client')return {apiRequest:(p,o)=>api(p,o)};if(name==='next/navigation')return {useRouter:()=>({replace:p=>routes.push(p)})};if(name==='@/app/components/ui')return {Button:({children,variant,...props})=>React.createElement('button',props,children),Card:({title,children})=>React.createElement('section',null,React.createElement('h4',null,title),children),LoadingState:({title})=>React.createElement('p',null,title),Alert:({children})=>React.createElement('div',{role:'alert'},children)};return original.call(this,name,parent,main);};
const {default:Panel,financialDisplay,publishedFinancialCsv}=require('../app/components/PublishedFinancialDashboard.tsx');
const root=createRoot(document.getElementById('root'));let checks=0;const ok=(value,message)=>{assert.ok(value,message);checks++;};
const amounts={acr:'41944.00',aclBeforeFees:'36142.79',totalFees:'1600.00',aclAfterFees:'37742.79',savingsBeforeFees:'5801.21',savingsAfterFees:'4201.21',savingsPercent:'10.02'};
function response(path,org='org',rows=true){const q=new URL('https://test.invalid'+path).searchParams,month=q.get('from');return {organizationId:org,period:{from:month,to:q.get('to'),customerId:q.get('customerId')},updatedAt:'2026-10-03T12:00:00Z',publicationCount:rows?1:0,customerCount:rows?1:0,unitMonthCount:rows?1:0,totals:rows?amounts:null,months:[{month,publicationCount:rows?1:0,totals:rows?amounts:null}],disclosure:'Somente publicações; ausência não é zero.',rows:rows?[{id:'group',customerId:'customer',customerName:'Cenourão',month,version:2,payloadHash:'a'.repeat(64),publishedAt:'2026-10-02T15:14:52Z',publicationNote:'Aprovado com ressalvas.',units:[{id:'u',name:'Bonfim'}],reservations:['Compra sem NF e revisão pela CCEE.'],amounts}]:[]};}
const text=()=>document.body.textContent,button=t=>[...document.querySelectorAll('button')].find(b=>b.textContent===t);
const change=async(el,value)=>act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});
const submit=()=>act(async()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
const {default:Audience}=require('../app/components/BackofficeAudience.tsx');
function clientResponse(p,id='customer'){const r=response(p);r.audience='client';r.customerId=id;r.period.customerId=id;r.rows[0].customerId=id;r.rows[0].publicationNote='';r.rows[0].reservations=['Resultado publicado com ressalvas. Consulte a equipe de gestão.'];return r;}
(async()=>{try{
 let calls=[];api=async(p,o)=>{calls.push([p,o]);return clientResponse(p);};await act(async()=>root.render(React.createElement(Panel,{key:'client',organizationId:'org',organizationName:'Expert',audience:'client'})));
 ok(calls[0][0].startsWith('/api/v1/portal/financial?')&&!calls[0][0].includes('customerId'),'client request never chooses a customer');ok(!document.querySelector('select'),'no other customer selection in client portal');ok(text().includes('4.201,21')&&!text().includes('Compra sem NF'),'published figures with client-only notes');
 api=async p=>({...clientResponse(p),rows:[{...clientResponse(p).rows[0],customerId:'foreign'}]});await submit();ok(!text().includes('4.201,21')&&text().includes('escopo da consulta mudou'),'foreign row cannot render');
 api=async p=>{calls.push([p]);return clientResponse(p,'selected');};await act(async()=>root.render(React.createElement(Panel,{key:'preview',organizationId:'org',organizationName:'Expert',audience:'client',previewCustomerId:'selected'})));ok(calls.at(-1)[0].includes('/portal/preview?')&&calls.at(-1)[0].includes('customerId=selected'),'manager preview requests explicit client projection');ok(text().includes('4.201,21'),'preview displays returned totals');
 api=async p=>clientResponse(p,'foreign');await submit();ok(!text().includes('4.201,21'),'preview response must match selected customer');
 api=async()=>({organizationId:'org',audience:'client'});await act(async()=>root.render(React.createElement(Audience,{key:'gate-client',organizationId:'org'},React.createElement('p',null,'PRIVATE BACKOFFICE'))));ok(routes.includes('/portal')&&!text().includes('PRIVATE BACKOFFICE'),'external linked client redirected without backoffice children');
 api=async()=>({organizationId:'org',audience:'backoffice'});await act(async()=>root.render(React.createElement(Audience,{key:'gate-shared',organizationId:'org'},React.createElement('p',null,'SHARED BACKOFFICE'))));ok(text().includes('SHARED BACKOFFICE'),'shared/internal consulta preserves backoffice');
 api=async()=>({organizationId:'foreign',audience:'backoffice'});await act(async()=>root.render(React.createElement(Audience,{key:'gate-foreign',organizationId:'org'},React.createElement('p',null,'PRIVATE BACKOFFICE'))));ok(!text().includes('PRIVATE BACKOFFICE')&&text().includes('contexto de acesso mudou'),'audience gate rejects foreign scope');
 let release;api=()=>new Promise(resolve=>release=resolve);await act(async()=>root.render(React.createElement(Audience,{key:'gate-old',organizationId:'org'},React.createElement('p',null,'OLD PRIVATE'))));const oldRelease=release;api=async()=>({organizationId:'other',audience:'backoffice'});await act(async()=>root.render(React.createElement(Audience,{key:'gate-new',organizationId:'other'},React.createElement('p',null,'NEW SHARED'))));await act(async()=>oldRelease({organizationId:'org',audience:'backoffice'}));ok(text().includes('NEW SHARED')&&!text().includes('OLD PRIVATE'),'late audience response cannot restore old organization');
 console.log(checks+' client portal UI checks passed');
}finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
