const assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),ts=require('typescript'),{JSDOM}=require('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});for(const k of ['window','document','HTMLElement','HTMLInputElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);const orig=Module._load;Module._load=function(name,parent,main){if(name.endsWith('map.module.css'))return {};return orig.call(this,name,parent,main);};
const D=require('../app/backoffice/energy-map/commercial-map-data.ts'),R=require('../app/backoffice/energy-map/RadiusFilter.tsx').default,C=require('../app/backoffice/energy-map/CommercialSummary.tsx').default,root=createRoot(document.getElementById('root'));let checks=0,applied=[],state='';const ok=v=>{assert.ok(v);checks++;};const group={label:'SP',units:1001,customers:1,confirmed:1},data={coverage:'FULL_FILTER',method:'PORTFOLIO_COUNTS_V1',states:[group],distributors:[{...group,label:'CPFL'}],distributorGroups:1,profiles:[{...group,label:'ACL · GD sim · BESS sim'}]};
const active={radiusLatitude:'',radiusLongitude:'',radiusKm:''},valid={radiusLatitude:'-21',radiusLongitude:'-47',radiusKm:'50'},renderR=(current=active,selected=null)=>act(async()=>root.render(React.createElement(R,{active:current,selected,onApply:v=>applied.push(v)}))),button=t=>[...document.querySelectorAll('button')].find(b=>b.textContent===t),click=t=>act(async()=>button(t).click());
(async()=>{try{
 ok(D.validRadius(valid));for(const patch of [{radiusLatitude:'91'},{radiusLongitude:'181'},{radiusKm:'501'},{radiusKm:'0'},{radiusKm:'1e2'},{radiusLatitude:'NaN'},{radiusKm:'50;SQL'},{radiusLongitude:''}])ok(!D.validRadius({...valid,...patch}));ok(D.validTerritory(data,1001));ok(!D.validTerritory({...data,coverage:'PAGE'},1001));ok(!D.validTerritory(data,1));ok(!D.validTerritory({...data,states:[{...group,confirmed:1002}]},1001));ok(!D.validTerritory({...data,profiles:[{...group,units:1000}]},1001));
 await renderR();ok(applied.length===0&&button('Aplicar raio').disabled&&button('Usar unidade selecionada como centro').disabled);await renderR(active,{latitude:-21,longitude:-47,locationStatus:'STALE'});ok(button('Usar unidade selecionada como centro').disabled);await renderR(active,{latitude:-21,longitude:-47,locationStatus:'CONFIRMED'});await click('Usar unidade selecionada como centro');ok(applied.length===0&&!button('Aplicar raio').disabled);await click('Aplicar raio');ok(applied.length===1&&applied[0].radiusLatitude==='-21.0000000'&&applied[0].radiusKm==='50');await renderR(valid);ok(document.body.textContent.includes('Raio ativo: 50'));await click('Limpar raio');ok(applied.at(-1).radiusKm==='');
 await act(async()=>root.render(React.createElement(C,{data,totalUnits:1001,onState:v=>state=v})));ok(document.body.textContent.includes('1001 unidades')&&document.body.textContent.includes('próximas páginas'));await act(async()=>document.querySelector('button').click());ok(state==='SP');await act(async()=>root.render(React.createElement(C,{data:{...data,states:[{...group,label:'<script>alert(1)</script>'}]},totalUnits:1001,onState:v=>state=v})));ok(!document.querySelector('script')&&document.querySelector('button').disabled);await act(async()=>root.unmount());console.log(checks+' commercial/radius UI checks passed.');
 }catch(e){console.error(e);process.exitCode=1;}finally{dom.window.close();}})();
