const assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),ts=require('typescript'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});for(const k of ['window','document','HTMLElement','HTMLSelectElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);
let api;const original=Module._load;Module._load=function(name,parent,main){if(name==='@/app/lib/api/client')return {apiRequest:(p,o)=>api(p,o)};return original.call(this,name,parent,main);};
const C=require('../app/components/CustomerNoticeSettings.tsx').default,root=createRoot(document.getElementById('root'));let checks=0;const check=v=>{assert.ok(v);checks++;},render=key=>act(async()=>root.render(React.createElement(C,{key})));
const click=async text=>act(async()=>{const el=[...document.querySelectorAll('button')].find(x=>x.textContent===text);assert.ok(el);el.click();});
const checkbox=async text=>act(async()=>{const l=[...document.querySelectorAll('label')].find(x=>x.textContent.includes(text)),el=l?.querySelector('input[type=checkbox]');assert.ok(el);el.click();});
const select=async(i,value)=>act(async()=>{const el=document.querySelectorAll('select')[i];el.value=value;el.dispatchEvent(new dom.window.Event('change',{bubbles:true}));});
const contact={id:'contact',name:'Contato autorizado',email:'test@example.invalid',phone:'+5516999999999',active:true,channels:['email','sms']},config={customerId:'c1',unitId:'u1',events:['REQUEST'],channels:['email'],contactIds:['contact']};
const data={customers:[{id:'c1',name:'Cliente',contacts:[contact]}],units:[{id:'u1',customerId:'c1',name:'Unidade'}],policies:[{id:'policy',version:1,state:'PAUSED',config}],deliveries:[],providers:{enabled:false,email:true,sms:false,whatsapp:{REQUEST:false,AGENDA:false,DEADLINE:false,ACL_PUBLISHED:false}}};
(async()=>{try{
 const calls=[];api=async(p,o)=>{calls.push([p,o]);return data;};await render('o1');check(calls.length===1&&calls[0][0]==='/api/v1/customer-notices');check(!calls.some(x=>x[1]?.method==='POST'));check(document.body.textContent.includes('desativada para envios reais'));
 await click('Revisar e ativar');check([...document.querySelectorAll('button')].find(x=>x.textContent==='Ativar novos avisos').disabled);await checkbox('Revisei os destinatários');check(![...document.querySelectorAll('button')].find(x=>x.textContent==='Ativar novos avisos').disabled);await click('Voltar');
 await select(0,'c1');await select(1,'u1');await checkbox('Solicitações criadas');await checkbox('SMS');const email=[...document.querySelectorAll('label')].find(l=>l.textContent==='E-mail').querySelector('input');check(email.checked&&email.disabled);await checkbox('Contato autorizado');check([...document.querySelectorAll('label')].find(l=>l.textContent.includes('Contato autorizado')).querySelector('input').checked);
 await checkbox('WhatsApp');const disabledContact=[...document.querySelectorAll('label')].find(l=>l.textContent.includes('Contato autorizado')).querySelector('input');check(disabledContact.disabled&&!disabledContact.checked);await checkbox('WhatsApp');await checkbox('Contato autorizado');
 const retries=[];api=async(p,o)=>{if(o?.method==='POST'){retries.push(o.body);if(retries.length===1)throw Error('Resposta indisponível');}return data;};const submit=()=>act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));await submit();await submit();check(retries.length===2&&retries[0].requestId===retries[1].requestId);check(retries.every(b=>b.enabled===false&&!b.id));check(retries[0].config.channels.includes('email')&&retries[0].config.channels.includes('sms'));
 let resolve;api=()=>new Promise(r=>resolve=r);await render('o2');check(!document.body.textContent.includes('test@example.invalid'));api=async()=>({...data,customers:[],units:[],policies:[]});await render('o3');await act(async()=>resolve(data));check(!document.body.textContent.includes('Contato autorizado'));await act(async()=>root.unmount());console.log(checks+' customer notice UI checks passed');
}catch(e){console.error(e);process.exitCode=1;}finally{dom.window.close();}})();
