/* DOM checks without production writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');const {JSDOM}=require('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});for(const k of ['window','document','HTMLElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);
const {SupplierCosts,AdditionalCosts}=require('../app/backoffice/contracts/FinancialCosts.tsx');const root=createRoot(document.getElementById('root'));let checks=0,opened=false;const ok=(x,m)=>{assert.ok(x,m);checks++;};const text=()=>document.body.textContent;const render=async(c,data)=>act(async()=>root.render(React.createElement(c,{data,onCorrect:()=>opened=true})));
const supplier={status:'AVAILABLE',costs:'120.00',credits:'5.00',balance:'115.00',baseInvoice:'100.00',extraPurchases:'15.00',entries:[{id:'1',label:'NF 123',category:'SUPPLIER_INVOICE',amount:'100.00',effect:'COST',source:'Documento revisado'}],version:{version:2,revision:3,source:'Faturas'},blockers:[],warnings:['Não duplicar compra extra.']};
(async()=>{try{
 await render(SupplierCosts,supplier);ok(text().includes('R$ 115,00'),'server supplier balance');ok(text().includes('R$ 100,00')&&text().includes('R$ 15,00'),'regular and extra separated');ok(text().includes('Documento revisado')&&text().includes('Revisão 3'),'evidence preserved');await act(async()=>document.querySelector('button').click());ok(opened,'correction action');
 await render(SupplierCosts,{...supplier,status:'BLOCKED',blockers:['Tributos pendentes']});ok(text().includes('Tributos pendentes')&&!text().includes('R$ 115,00'),'blocked stale balance hidden');
 await render(SupplierCosts,undefined);ok(text().includes('indisponível'),'rolling API');
 await render(SupplierCosts,{...supplier,balance:'NaN'});ok(!text().includes('NaN')&&!text().includes('R$ 115,00'),'invalid money hidden');
 await render(SupplierCosts,{...supplier,balance:'0.00'});ok(text().includes('R$ 0,00'),'legitimate invoice zero');
 const a={scenarios:[{scenario:'ACL',status:'AVAILABLE',costs:'1.00',credits:'3.00',balance:'-2.00',blockers:[]}],warnings:[],version:null};await render(AdditionalCosts,a);ok(text().includes('− R$ 2,00'),'credit sign');ok(text().includes('Aguardando revisão'),'missing scenario not zero');
 await render(AdditionalCosts,{...a,scenarios:[{...a.scenarios[0],status:'BLOCKED',blockers:['Revisar impostos']}]});ok(text().includes('Revisar impostos')&&!text().includes('− R$ 2,00'),'no partial total');
 await render(AdditionalCosts,{...a,scenarios:[{...a.scenarios[0],status:'DECLARED_ZERO',costs:'0.00',credits:'0.00',balance:'0.00'}]});ok(text().includes('Ausência de custos adicionais declarada'),'explicit absence');console.log(checks+' financial cost interface checks passed');
}finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
