/* Isolated DOM: real tariff memory and preparation screen, no production writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const {JSDOM}=require('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});
for(const k of ['window','document','HTMLElement','HTMLSelectElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);


const ui={Button:({children,variant,...p})=>React.createElement('button',{'data-variant':variant,...p},children),Input:({label,...p})=>React.createElement('label',null,label,React.createElement('input',p)),Card:({title,children})=>React.createElement('section',null,React.createElement('h2',null,title),children),Alert:({children})=>React.createElement('div',{role:'alert'},children)};

let calls=[],saved=null;const original=Module._load;Module._load=function(name,parent,main){if(name==='@/app/components/ui')return ui;if(name==='@/app/lib/api/client')return {apiRequest:async(url,options)=>{calls.push({url,options});if(options){saved=options.body;return {id:'rule',version:1,...saved,created_by:'actor',created_by_name:'Gestora',created_at:'2026-10-01T12:00:00Z'};}return {rows:[],canConfigure:true};}};if(name.startsWith('@/app/'))return original.call(this,path.resolve(__dirname,'..',name.slice(2)),parent,main);return original.call(this,name,parent,main);};
const Allocation=require('../app/backoffice/contracts/ManagementAllocation.tsx').default,Memory=require('../app/backoffice/contracts/ManagementFeeMemory.tsx').default;
const root=createRoot(document.getElementById('root'));let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};const props={customerId:'c',units:[{id:'u',customer_id:'c',name:'Unit',consumer_unit_number:'001'}],contracts:[{id:'contract',customer_id:'c',contract_number:'Fees',fixed_fee_monthly:1000,remuneration_model:'FIXED'}],initialContext:{recordId:'contract',month:'2026-10'},onDirty:()=>{}};
(async()=>{try{
await act(async()=>root.render(React.createElement(Allocation,props)));ok(document.querySelector('select').value==='contract'&&document.querySelectorAll('select')[1].value==='10'&&document.querySelectorAll('select')[2].value==='2026','correction context preserved');await act(async()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));ok(calls[0].url.includes('contractId=contract&month=2026-10'),'scope in query');await act(async()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Configurar regra da competência').click());ok(document.querySelector('input[type=checkbox]').required,'explicit per-unit confirmation');ok(!document.body.textContent.includes('Percentual variável ·'),'no fixed allocation fields');ok(document.body.textContent.includes('por unidade'),'fixed per-unit label');
await act(async()=>root.render(React.createElement('div')));await act(async()=>root.render(React.createElement(Allocation,{...props,contracts:[{...props.contracts[0],remuneration_model:'HYBRID'}]})));await act(async()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await act(async()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Configurar regra da competência').click());ok(document.body.textContent.includes('Rateio somente da parcela variável'),'only variable allocated');ok(document.body.textContent.includes('O fixo permanece integral mesmo quando o rateio variável for zero'),'zero share explanation');
const data={status:'VARIABLE_PENDING',formulaVersion:'1',fixedUnit:'1000.00',percentage:'20',variableFee:null,totalFee:null,contract:{id:'contract',number:'Fees',model:'HYBRID'},allocation:{id:'r',version:1,source:'Contract',percentage:'25'},blockers:['Waiting for consolidation'],warnings:['Fixed per unit']};await act(async()=>root.render(React.createElement(Memory,{data})));ok(document.body.textContent.includes('1.000,00'),'full fixed money visible');ok(document.body.textContent.includes('Ainda não apurado')&&document.body.textContent.includes('Aguardando consolidação do cliente'),'no fictitious total');ok(document.body.textContent.includes('participação somente no variável: 25%'),'variable-only rate');await act(async()=>root.render(React.createElement(Memory,{})));ok(document.body.textContent.includes('não está disponível'),'rolling deployment missing memory');console.log(checks+' management fee interface checks passed');
}finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
