/* Mocked APIs and isolated DOM; no production access or financial actions. */
const assert=require('node:assert/strict'),fs=require('node:fs'),Module=require('node:module'),ts=require('typescript'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});for(const key of ['window','document','HTMLElement','Event','MouseEvent'])global[key]=dom.window[key];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);
let context={scope:'organization',currentOrganization:{id:'a'}},permission=true,requests=[],api;const original=Module._load;
Module._load=function(name,parent,main){if(name==='@/app/providers')return {useAuth:()=>({context,hasPermission:()=>permission})};if(name==='@/app/lib/api/client')return {apiRequest:(path,options)=>{requests.push({path,options});return api(path,options);}};if(['@/app/components/BackofficeShell','@/app/components/ProtectedRoute'].includes(name))return {__esModule:true,default:({children})=>children};if(name==='next/link')return {__esModule:true,default:({href,children})=>React.createElement('a',{href},children)};if(name==='../documents/OcrAssistant')return {__esModule:true,default:props=>React.createElement('div',{'data-assistant':props.id},props.openRequest)};return original.call(this,name,parent,main);};
const Page=require('../app/backoffice/ocr-audit/page.tsx').default,root=createRoot(document.getElementById('root'));
const row=(id,version=1)=>({id,original_filename:id+'.pdf',document_type:'INVOICE_DISTRIBUTOR',reference_month:'2026-08-01',customer_id:'client-'+id,consumer_unit_id:'unit-'+id,file_verified:true,customerName:'Cliente '+id,unitName:'Unidade '+id,unitCode:id,code:'DOC-'+id,currentVersion:version===1,catalog:{version}});
const render=()=>act(async()=>root.render(React.createElement(Page)));
(async()=>{try{
 api=async()=>({documents:[row('tennis'),row('fuga'),row('old',2),{...row('nf'),document_type:'INVOICE_SUPPLIER'},{...row('quarantine'),file_verified:false}]});await render();assert.equal(requests.length,1);assert.equal(requests[0].path,'/api/v1/document-catalog');assert.ok(!requests[0].options.method);assert.ok(document.body.textContent.includes('Tennis')===false);assert.equal(document.querySelectorAll('tbody tr').length,3);assert.equal(document.querySelector('[aria-label="Abrir auditoria quarantine.pdf"]').disabled,true);assert.equal(document.querySelector('[data-assistant]'),null);await act(async()=>document.querySelector('[aria-label="Abrir auditoria tennis.pdf"]').click());assert.equal(document.querySelector('[data-assistant]').getAttribute('data-assistant'),'tennis');assert.equal(requests.length,1,'Opening uses the reused assistant, no direct writes from listing');
 const client=document.querySelector('select');await act(async()=>{client.value='client-fuga';client.dispatchEvent(new Event('change',{bubbles:true}));});assert.equal(document.querySelectorAll('tbody tr').length,1);assert.ok(document.querySelector('tbody').textContent.includes('fuga'));
 let resolveOld,resolveNew;api=(_p,o)=>new Promise(resolve=>{if(context.currentOrganization.id==='b')resolveOld=resolve;else resolveNew=resolve;});context={...context,currentOrganization:{id:'b'}};await render();assert.equal(document.querySelector('[data-assistant]'),null);context={...context,currentOrganization:{id:'c'}};await render();await act(async()=>resolveNew({documents:[row('new')]}));await act(async()=>resolveOld({documents:[row('foreign')]}));assert.ok(document.body.textContent.includes('new.pdf'));assert.ok(!document.body.textContent.includes('foreign.pdf'));
 const before=requests.length;context={scope:'global'};await render();assert.equal(requests.length,before);assert.ok(document.querySelector('[role=alert]'));context={scope:'organization',currentOrganization:{id:'d'}};permission=false;await render();assert.equal(requests.length,before);assert.equal(document.querySelector('table'),null);
 console.log('OCR audit UI passed: scoped catalog, customer filtering, quarantine, no bulk writes, and stale tenant isolation.');
 }finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
