const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,f);
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');const C=require('../app/backoffice/documents/OcrPreparationPreview.tsx').default;
const base={canImport:false,message:'Prévia',values:[],pending:[]};
assert.ok(!renderToStaticMarkup(React.createElement(C,{evidence:base})).includes('Demanda: medição'));
const demand={canImport:false,message:'Não somar postos',measured:[{period:'PEAK',decimal:'203',unit:'kW',state:'DISPLAYED_REVIEW',sources:['meter'],message:'Pode estar arredondado'},{period:'OFF_PEAK',decimal:null,unit:'kW',state:'MISSING',sources:[],message:'Ausente'}],billed:[{source:'bill',description:'<img src=x>',decimal:'234.6400',unit:'kW',state:'BILLED_UNCLASSIFIED'}],contracted:{decimal:null,message:'Não inferir'},unused:{decimal:null,message:'Exige conferência'}};
const html=renderToStaticMarkup(React.createElement(C,{evidence:{...base,demand}}));for(const text of ['203 kW','234,6400 kW','A conferir','Classificação pendente','Não inferir','Exige conferência','Importação automática: não liberada'])assert.ok(html.includes(text));assert.ok(!html.includes('<img'));const linked=renderToStaticMarkup(React.createElement(C,{evidence:{...base,demand:{...demand,registration:{state:'BEFORE_ADJUSTMENT',month:'2026-08',adjustmentDate:'2026-09-01',message:'A fatura é anterior ao último ajuste.',values:[{label:'Única',current:'500',lastAdjustment:'500'}]}}}}));for(const text of ['Demanda contratada no cadastro','2026-08','2026-09-01','500 kW','A fatura é anterior'])assert.ok(linked.includes(text));console.log('Demand UI and registration checks passed');

const taxes=[{key:'icmsAmount',label:'ICMS',text:'',decimal:null,state:'MISSING',confidence:null,pages:[],source:'bill.icmsAmount',message:'Valor não identificado. Ausência não significa zero.',confidenceMessage:'Exige conferência.'},{key:'pisAmount',label:'PIS',text:'24,00',decimal:'24.00',state:'POSITIVE',confidence:null,pages:[1],source:'bill.pisAmount',message:'Valor positivo extraído.',confidenceMessage:'Exige conferência.'},{key:'cofinsAmount',label:'Cofins',text:'112,55',decimal:'112.55',state:'POSITIVE',confidence:0.99,pages:[1],source:'bill.cofinsAmount',message:'Valor positivo extraído.',confidenceMessage:'Não aprova.'}];
const withTaxes=renderToStaticMarkup(React.createElement(C,{evidence:{...base,demand:{...demand,billed:[{...demand.billed[0],taxReview:taxes}]}}}));
for(const text of ['ICMS','PIS','Cofins','Não identificado','24,00','112,55','99,0%','bill.pisAmount','Ausência não significa zero.'])assert.ok(withTaxes.includes(text),text);
assert.ok(!withTaxes.includes('<img'));
console.log('Tax evidence display checks passed');
