/* Isolated DOM: real tariff memory and preparation screen, no production writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const {JSDOM}=require('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});
for(const k of ['window','document','HTMLElement','HTMLSelectElement','FormData','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);


const ui={Button:({children,variant,...p})=>React.createElement('button',{'data-variant':variant,...p},children),Input:({label,...p})=>React.createElement('label',null,label,React.createElement('input',p)),Card:({title,children})=>React.createElement('section',null,React.createElement('h2',null,title),children),Alert:({children})=>React.createElement('div',{role:'alert'},children)};

let calls=[],saved=null;const original=Module._load;Module._load=function(name,parent,main){if(name==='@/app/components/ui')return ui;if(name==='@/app/lib/api/client')return {apiRequest:async(url,options)=>{calls.push({url,options});if(options){saved=options.body;return {id:'rule',version:1,...saved,created_by:'actor',created_by_name:'Gestora',created_at:'2026-10-01T12:00:00Z'};}return {rows:[],canConfigure:true};}};if(name.startsWith('@/app/'))return original.call(this,path.resolve(__dirname,'..',name.slice(2)),parent,main);return original.call(this,name,parent,main);};
const Rules=require('../app/backoffice/contracts/SupplierBillingRules.tsx').default,Memory=require('../app/backoffice/contracts/ContractSupplierCost.tsx').default,{comparisonRows}=require('../app/backoffice/contracts/comparison-view.ts');
const root=createRoot(document.getElementById('root'));let checks=0;const ok=(x,m)=>{assert.ok(x,m);checks++;};const change=async(el,value)=>{await act(async()=>{const proto=el.tagName==='SELECT'?HTMLSelectElement.prototype:window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new Event('change',{bubbles:true}));el.dispatchEvent(new Event('input',{bubbles:true}));});};
(async()=>{try{
 await act(async()=>root.render(React.createElement(Rules,{contract:{id:'contract',contract_number:'C1',start_date:'2026-01-01',end_date:'2026-12-31',contracted_volume_mwh:100},onDirty:()=>{}})));
 ok(calls[0].url.endsWith('contractId=contract'),'contract scope');await act(async()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Configurar faturamento automático').click());
 ok(document.body.textContent.includes('Tolerância acima do volume contratado (%)'),'upper tolerance label');ok(document.body.textContent.includes('não 130'),'explains 30 not 130');
 for(const [name,value] of Object.entries({volumeBasis:'MONTHLY',minPercent:'70',maxTolerancePercent:'30',taxTreatment:'GROSS',source:'Cláusula confirmada'}))await change(document.querySelector('[name="'+name+'"]'),value);
 await change(Array.from(document.querySelectorAll('select')).find(s=>Array.from(s.options).some(o=>o.value==='FINAL')),'FINAL');await act(async()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 ok(saved.maxTolerancePercent==='30'&&saved.minPercent==='70','persists distinct percentages');ok(!('maxPercent' in saved),'legacy absolute field not submitted');ok(saved.priceMode==='FINAL'&&!('indexPercent' in saved),'no double index');
 const data={formulaVersion:'contract-supplier-1.0',status:'PENDING',month:'2026-08',contract:{id:'c',number:'C1'},rule:{id:'r',version:1,source:'Contrato'},contractedMwh:'100',consumedMwh:'140',minMwh:'70',maxMwh:'130',billedMwh:'130',minimumUnusedMwh:'0',extraMwh:'10',pricePerMwh:'200',taxTreatment:'GROSS',regularAmount:'26000.00',minimumAmount:'0.00',extraAmount:null,totalAmount:null,invoiceAmount:null,invoiceDifference:null,bands:[{timeBand:'PEAK',volumeMwh:'20',amount:'4000.00'},{timeBand:'OFF_PEAK',volumeMwh:'110',amount:'22000.00'}],requirements:[{code:'EXTRA_PURCHASE',message:'Informe a compra extra',tab:'costs'}],warnings:[]};
 let corrected;await act(async()=>root.render(React.createElement(Memory,{data,onCorrect:(tab,id)=>{corrected={tab,id};}})));ok(document.body.textContent.includes('10 MWh'),'extra volume visible');ok(document.body.textContent.includes('Aguardando dados'),'no premature total');await act(async()=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('Informe a compra extra')).click());ok(corrected.tab==='costs','extra correction opens monthly costs');
 const rows=comparisonRows({catalog:[],contractSupplierCost:data});ok(rows.length===2&&rows.every(r=>r.ACL[0].kind==='SUPPLIER'),'ACL TE has supplier source');ok(rows.map(r=>r.ACL[0].amount).sort().join(',')==='22000.00,4000.00','uses backend amounts without duplicate total');
 await act(async()=>root.render(React.createElement(Memory,{data:{...data,extraMwh:null,bands:[]},onCorrect:()=>{}})));ok(document.body.textContent.includes('Aguardando cálculo do excedente'),'does not request purchase before calculating volume');ok(!document.body.textContent.includes('Informe o valor da compra extra'),'unknown volume is not an extra purchase requirement');
 console.log('Supplier billing UI: '+checks+' checks passed.');
 }finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
