/* Isolated DOM: real tariff memory and preparation screen, no production writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const {JSDOM}=require('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'https://test.invalid'});
for(const k of ['window','document','HTMLElement','HTMLSelectElement','Event','MouseEvent'])global[k]=dom.window[k];global.IS_REACT_ACT_ENVIRONMENT=true;
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,file);
const line={parameterId:'p',revision:2,label:'Energia',scenario:'ACR',timeBand:'PEAK',measure:'BRL_MWH',rate:'250',quantity:'100',quantityUnit:'kWh',exactAmount:'25.000000000000000',amount:'25.00',treatment:'NET',embeddedTaxCodes:[],source:'Tarifa aprovada',formula:'kWh × R$/MWh ÷ 1000',startDate:'2026-01-01',endDate:'2026-12-31'};
const data={formulaVersion:'tariffs-1.0',measurement:{id:'m',version:1,revision:2,source:'Fatura revisada'},lines:[line],pending:[{parameterId:'d',label:'Demanda',scenario:'ACL',reason:'Demanda faturável ainda não calculada.'}],warnings:['Sem economia e sem publicação.']};
let response={tariffPreview:data,unit:{id:'u',name:'Unidade'},month:'2026-08',period:{start:'2026-08-01',end:'2026-08-31'},checkedAt:'2026-09-01T12:00:00Z',counts:{blockers:1,reviews:0,approvedParameters:2},findings:[],catalog:[],suppliers:[],notChecked:[],ruleVersion:'preparation-1.2'},failure=false,calls=[];
const ui={Button:({children,variant,...p})=>React.createElement('button',{'data-variant':variant,...p},children),Card:({title,children})=>React.createElement('section',null,React.createElement('h2',null,title),children),Alert:({children})=>React.createElement('div',{role:'alert'},children)};
const original=Module._load;Module._load=function(name,parent,main){if(name==='@/app/components/ui')return ui;if(name==='@/app/lib/api/client')return {apiRequest:async url=>{calls.push(url);if(failure)throw Error('Consulta indisponível');return response;}};if(name.startsWith('@/app/'))return original.call(this,path.resolve(__dirname,'..',name.slice(2)),parent,main);return original.call(this,name,parent,main);};
const Preview=require('../app/backoffice/contracts/TariffPreview.tsx').default,Preparation=require('../app/backoffice/contracts/CalculationPreparation.tsx').default;
const root=createRoot(document.getElementById('root'));let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};const text=()=>document.body.textContent;
async function render(data){await act(async()=>root.render(React.createElement(Preview,{data})));}
async function select(label,value){const el=Array.from(document.querySelectorAll('label')).find(x=>x.firstChild?.textContent===label).querySelector('select');await act(async()=>{Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(el,value);el.dispatchEvent(new Event('change',{bubbles:true}));});}
async function submit(){await act(async()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));}
(async()=>{try{
 await render(data);ok(text().includes('R$ 25,00'),'server amount rendered');ok(text().includes('kWh × R$/MWh ÷ 1000'),'formula visible in details');ok(text().includes('Tarifa aprovada')&&text().includes('Fatura revisada'),'both sources');ok(text().includes('não foram acrescidos'),'NET tax disclaimer');ok(text().includes('Demanda faturável ainda não calculada'),'pending retained');ok(document.querySelectorAll('th[scope="col"]').length===4,'accessible table');
 await render({...data,lines:[{...line,treatment:'GROSS',embeddedTaxCodes:['ICMS']} ]});ok(text().includes('ICMS')&&text().includes('Nenhum tributo foi acrescido novamente'),'GROSS not double counted');
 await render({...data,lines:[],measurement:null});ok(text().includes('não significa custo zero'),'absence not zero');ok(!document.querySelector('table'),'no artificial amount');
 await render({...data,lines:[{...line,measure:'BRL_KW',quantityUnit:'kW',quantitySource:'Fatura normal ACL p2',formula:'demanda faturável informada × tarifa'}]});ok(text().includes('R$/kW')&&text().includes('Fatura normal ACL p2'),'billing source and unit rendered');
 await render(undefined);ok(text().includes('ainda não está disponível'),'rolling deployment compatibility');
 await act(async()=>root.render(React.createElement(Preparation,{customerId:'c',units:[{id:'u',customer_id:'c',name:'Unidade',consumer_unit_number:'001'},{id:'foreign',customer_id:'other',name:'Outra',consumer_unit_number:'002'}]})));
 ok(!text().includes('Outra'),'customer filtered');await select('Unidade para conferência','u');await select('Mês da competência','08');await select('Ano da competência','2026');await submit();ok(calls[0].includes('consumerUnitId=u&month=2026-08'),'scoped query');ok(text().includes('R$ 25,00'),'memory integrated into real preparation');await select('Mês da competência','09');ok(!text().includes('R$ 25,00'),'changing period clears old result');failure=true;await submit();ok(text().includes('Consulta indisponível')&&!text().includes('R$ 25,00'),'failed query cannot retain financial line');
 console.log(checks+' tariff interface checks passed');
}finally{await act(async()=>root.unmount());dom.window.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
