'use client';
import { useEffect, useRef, useState } from 'react';
import { ApiError, apiRequest } from '@/app/lib/api/client';
import { Alert, Button } from '@/app/components/ui';
import type { WorkDetail } from './WorkControls';
type Closure={performance:null|{id:string;version:number;hash:string;createdAt:string;body:{closedByName:string;modality:string;supplyDate:string;stages:WorkDetail['stages'];evidence:{stageKey:string;reviewerName:string;documents:{id:string}[]}[]}};summary:null|{conclusion:string;publishedAt:string}};
type Command={requestId:string;expectedRevision:number;action:'CLOSE'|'PUBLISH';checkedDocument:true;conclusion?:string;performanceHash?:string};
const names:Record<string,string>={registration:'Cadastro',invoices:'Faturas',feasibility:'Viabilidade',modality:'Modalidade',contracts:'Contratação',termination:'Denúncia',metering:'Medição',custody:'Conta e adesão',technical:'Habilitação técnica','contract-registration':'Registro de contratos',validation:'Validação',supply:'Início do suprimento'};
export default function ClosureControls({detail,canApprove,onUpdated}:{detail:WorkDetail;canApprove:boolean;onUpdated:(v:WorkDetail)=>void}){
 const [value,setValue]=useState<Closure|null>(null),[error,setError]=useState(''),[checked,setChecked]=useState(false),[conclusion,setConclusion]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(false),[cycle,setCycle]=useState(0);
 const alive=useRef(true),flight=useRef(false),pending=useRef<Command|null>(null),base='/acl-admissions/'+encodeURIComponent(detail.id);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{setChecked(false);const abort=new AbortController();setValue(null);(async()=>{try{const result=await apiRequest<Closure>(base+'/closure',{signal:abort.signal});if(!abort.signal.aborted)setValue(result);}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível consultar o encerramento.');}})();return()=>abort.abort();},[base,detail.revision,cycle]);
 async function send(body:Command){if(flight.current)return;flight.current=true;pending.current=body;setBusy(true);setRetry(false);setError('');try{const result=await apiRequest<{admission:WorkDetail;closure:Closure}>(base+'/closure',{method:'POST',body});if(alive.current){pending.current=null;setValue(result.closure);setChecked(false);onUpdated(result.admission);}}
 catch(e){if(alive.current){setError(e instanceof Error?e.message:'Não foi possível confirmar o encerramento.');if(e instanceof ApiError&&e.status<500)pending.current=null;else setRetry(true);}}finally{flight.current=false;if(alive.current)setBusy(false);}}
 async function refresh(){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{const row=await apiRequest<WorkDetail>(base);if(alive.current){pending.current=null;setRetry(false);setChecked(false);onUpdated(row);setCycle(v=>v+1);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{flight.current=false;if(alive.current)setBusy(false);}}
 const ready=detail.stages.every(s=>['COMPLETED','SKIPPED'].includes(s.status)&&!s.active),closed=detail.status==='COMPLETED',p=value?.performance;
 return <section aria-label="Encerramento e resumo do cliente"><h3>Encerramento e resumo do cliente</h3>{error?<Alert>{error}</Alert>:null}
 <p>O encerramento preserva os tempos ativos, as versões documentais e os responsáveis. A publicação posterior mostra ao cliente somente a modalidade, a data de suprimento e a conclusão aprovada.</p>
 {p?<><p>Desempenho · versão {p.version} · encerrado por {p.body.closedByName} em {new Date(p.createdAt).toLocaleString('pt-BR')}.</p><p>Modalidade: {p.body.modality==='RETAIL'?'Varejista':'Agente próprio'} · Suprimento confirmado: {p.body.supplyDate}</p>
 <table><thead><tr><th>Etapa</th><th>Resultado</th><th>Tempo ativo</th><th>Conferência</th></tr></thead><tbody>{p.body.stages.map(s=><tr key={s.key}><td>{names[s.key]}</td><td>{s.status==='SKIPPED'?'Dispensada':'Concluída'}</td><td>{Math.floor(s.elapsedMs/60000)} min</td><td>{p.body.evidence.find(e=>e.stageKey===s.key)?.reviewerName}</td></tr>)}</tbody></table><p>Integridade da versão: <code style={{overflowWrap:'anywhere'}}>{p.hash}</code></p></>:null}
 {value?.summary?<><h4>Resumo publicado no portal</h4><p>{value.summary.conclusion}</p><p>Publicado em {new Date(value.summary.publishedAt).toLocaleString('pt-BR')}.</p></>:closed?<p>Adesão concluída. O resumo final aguarda publicação autorizada.</p>:<p>{ready?'Todas as etapas foram concluídas ou dispensadas. Confira as evidências antes de encerrar.':'Conclua ou obtenha a dispensa autorizada de todas as etapas antes do encerramento.'}</p>}
 {canApprove&&value&&!value.summary?<>{closed&&p?<><label htmlFor="acl-public-conclusion">Conclusão que o cliente verá</label><textarea id="acl-public-conclusion" value={conclusion} maxLength={1000} disabled={busy||retry} onChange={e=>{setConclusion(e.target.value);setChecked(false);}}/><p>Revise o texto para o cliente. Inclua apenas o resumo da adesão desta unidade.</p></>:null}
 <label><input type="checkbox" checked={checked} disabled={busy||retry} onChange={e=>setChecked(e.target.checked)}/> {closed?'Conferi a versão de desempenho e o resumo que será publicado no portal.':'Conferi todas as etapas, evidências aprovadas, dispensas e tempos de atividade.'}</label>
 {closed&&p?<Button disabled={busy||retry||!checked||conclusion.trim().length<10} onClick={()=>void send({requestId:crypto.randomUUID(),expectedRevision:detail.revision,action:'PUBLISH',checkedDocument:true,conclusion:conclusion.trim(),performanceHash:p.hash})}>Publicar resumo no portal</Button>:!closed?<Button disabled={busy||retry||!checked||!ready} onClick={()=>void send({requestId:crypto.randomUUID(),expectedRevision:detail.revision,action:'CLOSE',checkedDocument:true})}>Encerrar adesão e preservar desempenho</Button>:null}</>:null}
 {retry?<Button disabled={busy} onClick={()=>void send(pending.current!)}>Repetir a mesma operação</Button>:null}<Button variant="secondary" disabled={busy} onClick={()=>void refresh()}>Atualizar encerramento</Button>
 </section>;
}
