import styles from './workspace.module.css';
export type FinancialResult={state:string;pending?:string[];investment?:string;acrTotal?:string;aclTotal?:string;operatingSavings?:string;netCash?:string;roiPercent?:string|null;paybackMonths?:string|null;paybackState?:string;horizonMonths?:number;warnings?:string[];rows?:{month:string;sourceMonth:string;acr:string;aclAfterFees:string;saving:string;cumulative:string;ccee:string;gdCredit:string;fixedFee:string;variableFee:string;referenceDocumentary:boolean}[]};
const money=(s:string)=>Number(s).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function FinancialComparison({value}:{value?:FinancialResult|null}){
 if(!value)return null;
 if(value.state!=='COMPLETE_SIMULATED')return <section aria-label="Comparativo financeiro"><h4>Comparativo financeiro pendente</h4>{value.pending?.map(s=><p key={s}>{s}</p>)}</section>;
 const rows=value.rows!,values=[-Number(value.investment),...rows.map(r=>Number(r.cumulative))],min=Math.min(0,...values),max=Math.max(0,...values),span=max-min||1,points=values.map((v,i)=>`${20+i*560/(values.length-1)},${180-(v-min)*150/span}`).join(' '),zero=180-(0-min)*150/span;
 return <section className={styles.panel} aria-label="Comparativo financeiro completo simulado"><h4>Comparativo financeiro completo — simulação</h4><p>Horizonte de {value.horizonMonths} meses. Tarifas fixas, demanda medida e GD estimada; sujeito à revisão independente. Valores negativos de economia indicam custo ACL maior.</p><div className={styles.grid}>
 {[['ACR com GD',value.acrTotal],['ACL após honorários',value.aclTotal],['Economia operacional',value.operatingSavings],['Investimento inicial',value.investment],['Saldo após investimento',value.netCash]].map(([label,v])=><div className={styles.panel} key={label}><strong>{label}</strong><p>{money(v!)}</p></div>)}
 <div className={styles.panel}><strong>ROI do período</strong><p>{value.roiPercent===null?'Não aplicável: investimento zero':Number(value.roiPercent).toLocaleString('pt-BR')+'%'}</p></div><div className={styles.panel}><strong>Payback simples</strong><p>{value.paybackState==='NO_INVESTMENT'?'Não aplicável: investimento zero':value.paybackMonths===null?'Não recuperado na vigência':Number(value.paybackMonths).toLocaleString('pt-BR')+' meses'}</p></div></div>
 <figure><figcaption>Saldo acumulado após investimento — do início ao fim da vigência</figcaption><svg viewBox="0 0 600 210" role="img" aria-label="Evolução do saldo acumulado após o investimento" style={{width:'100%',maxHeight:240}}><line x1="20" x2="580" y1={zero} y2={zero} stroke="#94a3b8" strokeDasharray="5 5"/><polyline points={points} fill="none" stroke="#50c6e0" strokeWidth="3"/><text x="20" y="205" fill="currentColor">Início</text><text x="510" y="205" fill="currentColor">Fim</text></svg></figure>
 <div className={styles.table}><table><caption>Fluxo mensal ACR × ACL e recuperação do investimento</caption><thead><tr>{['Mês','Histórico','ACR com GD','ACL com honorários','Encargos','GD','Fixo','Variável','Economia','Saldo acumulado','Base'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.sourceMonth}</td>{['acr','aclAfterFees','ccee','gdCredit','fixedFee','variableFee','saving','cumulative'].map(k=><td key={k}>{money(r[k as keyof typeof r] as string)}</td>)}<td>{r.referenceDocumentary?'Fatura de referência':'Estimativa'}</td></tr>)}</tbody></table></div><details><summary>Metodologia e limites</summary>{value.warnings?.map(s=><p key={s}>{s}</p>)}</details></section>;
}
