'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {Alert,Button} from '@/app/components/ui';
type Result={annualSubtotal:string;warnings:string[];rows:{month:string;peak:string;offPeak:string;measuredDemandEstimate:string;subtotal:string}[]};
export default function HistorySimulation({admissionId,evidenceId}:{admissionId:string;evidenceId:string}){
 const [tariffs,setTariffs]=useState({peakBrlKwh:'',offPeakBrlKwh:'',demandBrlKw:'',referenceMonth:'',source:''}),[checked,setChecked]=useState(false),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 function change(key:keyof typeof tariffs,value:string){controller.current?.abort();setBusy(false);setTariffs(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 async function simulate(){controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setResult(null);setError('');try{const r=await apiRequest<Result>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/history-simulation',{method:'POST',body:{evidenceId,tariffs:{...tariffs,checked:true}},signal:abort.signal});if(!abort.signal.aborted)setResult(r);}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Simulação indisponível.');}finally{if(!abort.signal.aborted)setBusy(false);}}
 return <section aria-label="Simulação do histórico com tarifas fixas"><h4>Simulação dos 12 meses com as mesmas tarifas</h4><p>Informe as tarifas da fatura de referência, incluindo o tratamento tributário escolhido. Este subtotal é uma estimativa parcial de energia e demanda medida; não representa custos pagos nem economia líquida. GD/créditos, encargos e demanda faturável precisam de análise complementar.</p>
 <fieldset disabled={busy}><legend>Tarifas de referência — aplicadas a todos os meses</legend>{([['peakBrlKwh','Energia na ponta (R$/kWh)'],['offPeakBrlKwh','Energia fora de ponta (R$/kWh)'],['demandBrlKw','Demanda medida — estimativa (R$/kW)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode="decimal" value={tariffs[key]} onChange={e=>change(key,e.target.value)} placeholder="Decimal com ponto"/></label>)}<label>Competência das tarifas<input type="month" value={tariffs.referenceMonth} onChange={e=>change('referenceMonth',e.target.value)}/></label><label>Fonte e tratamento tributário das tarifas<textarea maxLength={500} value={tariffs.source} onChange={e=>change('source',e.target.value)}/></label><label><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setResult(null);}}/> Conferi as tarifas, as unidades e o tratamento tributário. Autorizo usar este conjunto fixo nos 12 meses para simulação.</label></fieldset>
 <Button disabled={busy||!checked||Object.values(tariffs).some(v=>!v.trim())} onClick={()=>void simulate()}>Simular histórico</Button>{error?<Alert>{error}</Alert>:null}{result?<><p>Subtotal anual simulado (parcial): R$ {result.annualSubtotal}</p>{result.warnings.map(w=><p key={w}>{w}</p>)}<table><caption>Valores simulados com tarifas fixas — R$</caption><thead><tr><th>Mês</th><th>Energia ponta</th><th>Energia fora de ponta</th><th>Demanda medida estimada</th><th>Subtotal parcial</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.peak}</td><td>{r.offPeak}</td><td>{r.measuredDemandEstimate}</td><td>{r.subtotal}</td></tr>)}</tbody></table></>:null}</section>;
}
