'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {Alert,Button} from '@/app/components/ui';
import styles from './workspace.module.css';
export type ScenarioDraft={schemaVersion:string;reviewRequired:true;evidenceId:string;template:{studyId:string;version:number;hash:string;review:string};proposal:{supplier:string;energyBrlMwh:string;startMonth:string;months:number;fixedMonthlyBrl:string;savingsPercent:string;estimatedMonthlyAclBrl:string;losses:string;taxes:string;source:string;distribution:null|{peakBrlKwh:string;offPeakBrlKwh:string;demandBrlKw:string;discountPercent:string;source:string};energyBasis?:{baseBrlMwh:string;lossPercent:string;icmsPercent:string};costPremises?:{additionalCostDescription:string;cceePercent:string;migrationInvestmentBrl:string;source:string;gdHistoryEstimate?:string}};pending:string[];tariffProof:{field:string;documentId:string;month:string|null;source:string;pages:number[];value:string}[]};
type Model={id:string;version:number;review:null|{decision:string};body:{result:{proposal:{supplier:string}}}};
export default function ScenarioAutofill({admissionId,evidenceId,disabled,onFilled,onBusy}:{admissionId:string;evidenceId:string;disabled:boolean;onFilled:(v:ScenarioDraft)=>void;onBusy:(v:boolean)=>void}){
 const [processes,setProcesses]=useState<{id:string;customerName:string;unitName:string}[]>([]),[process,setProcess]=useState(admissionId),[models,setModels]=useState<Model[]>([]),[model,setModel]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[after,setAfter]=useState<string|null>(null);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{const abort=new AbortController();apiRequest<{rows:typeof processes;nextCursor:string|null}>('/api/v1/acl-admissions',{signal:abort.signal}).then(r=>{if(!abort.signal.aborted){setProcesses(r.rows);setAfter(r.nextCursor);}}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Modelos indisponíveis.');});return()=>abort.abort();},[admissionId]);
 useEffect(()=>{controller.current?.abort();const abort=new AbortController();controller.current=abort;setModels([]);setModel('');setError('');setBusy(true);apiRequest<{rows:Model[]}>('/api/v1/acl-admissions/'+encodeURIComponent(process)+'/simulations',{signal:abort.signal}).then(r=>{if(!abort.signal.aborted){const rows=r.rows.filter(v=>v.review?.decision!=='REJECTED').sort((a,b)=>b.version-a.version);setModels(rows);setModel(rows[0]?.id??'');}}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Versões indisponíveis.');}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[process,admissionId]);
 async function more(){if(!after||busy)return;setBusy(true);try{const r=await apiRequest<{rows:typeof processes;nextCursor:string|null}>('/api/v1/acl-admissions?after='+encodeURIComponent(after));setProcesses(old=>[...old,...r.rows]);setAfter(r.nextCursor);}catch(e){setError(e instanceof Error?e.message:'Processos indisponíveis.');}finally{setBusy(false);}}
 async function fill(){onBusy(true);controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setError('');try{const r=await apiRequest<ScenarioDraft>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/scenario-draft',{method:'POST',body:{evidenceId,templateAdmissionId:process,templateStudyId:model},signal:abort.signal});if(!abort.signal.aborted)onFilled(r);}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Preenchimento indisponível.');}finally{if(!abort.signal.aborted){setBusy(false);onBusy(false);}}}
 return <div className={styles.panel}><h5>Preencher pela fatura e por um modelo</h5><p>A leitura OCR interpreta a fatura atual. O modelo reutiliza as premissas comerciais; as tarifas e os consumos pertencem à unidade atual. Confira as sugestões antes de simular.</p><fieldset disabled={disabled||busy}><legend>Modelo de cenário autorizado</legend><label>Processo de origem do modelo<select value={process} onChange={e=>setProcess(e.target.value)}><option value={admissionId}>Este processo</option>{processes.filter(v=>v.id!==admissionId).map(v=><option key={v.id} value={v.id}>{v.customerName} — {v.unitName}</option>)}</select></label><label>Versão de origem<select value={model} onChange={e=>setModel(e.target.value)}><option value="">Selecione uma versão</option>{models.map(v=><option key={v.id} value={v.id}>Versão {v.version} · {v.body.result.proposal.supplier} · {v.review?.decision==='REVIEWED'?'Premissas revisadas':'Aguardando revisão'}</option>)}</select></label><Button disabled={!model||!evidenceId} onClick={()=>void fill()}>Preencher cenário automaticamente</Button>{after?<Button onClick={()=>void more()}>Mais processos de origem</Button>:null}</fieldset>{error?<Alert>{error}</Alert>:null}</div>;
}
