'use client';
import {useEffect,useRef,useState} from 'react';
import {ApiError,apiRequest} from '@/app/lib/api/client';
import {Alert,Button} from '@/app/components/ui';
import type {WorkDetail} from './WorkControls';
import GdReferenceComparison,{type CostPremises,type GdComparison,type GdHistory} from './GdReferenceComparison';
import styles from './workspace.module.css';
type Study={id:string;version:number;hash:string;createdBy:string;actorName:string;createdAt:string;review:null|{decision:string;reason:string;actorName:string;reviewedAt:string};body:{source:{evidenceId:string;documents:{id:string;fileHash:string;version:number}[]};result:{gdComparison?:GdComparison;gdHistory?:GdHistory|null;formulaVersion:string;energySubtotal:string;knownComponentsSubtotal:string|null;pending:string[];warnings:string[];location:{label:string|null;address:string|null};proposal:{costPremises?:CostPremises;supplier:string;energyBrlMwh:string;energyBasis?:{baseBrlMwh:string;lossPercent:string;icmsPercent:string};startMonth:string;months:number;fixedMonthlyBrl:string;savingsPercent:string;estimatedMonthlyAclBrl:string;losses:string;taxes:string;source:string;distribution:null|{peakBrlKwh:string;offPeakBrlKwh:string;demandBrlKw:string;discountPercent:string;source:string}};rows:{month:string;sourceMonth:string;referenceKwh:string;measuredDemandKw:string;energy:string;knownComponentsSubtotal:string|null}[]}}};
type Page={rows:Study[];nextCursor:string|null};
type Command={requestId:string;expectedRevision:number;action:'REVIEW'|'REJECT';studyId:string;hash:string;reason:string;checkedDocument:true};
const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function StudyVersions({detail,actorId,canApprove,onUpdated}:{detail:WorkDetail;actorId:string;canApprove:boolean;onUpdated:(v:WorkDetail)=>void}){
 const [page,setPage]=useState<Page>({rows:[],nextCursor:null}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[retry,setRetry]=useState(false);
 const alive=useRef(true),flight=useRef(false),pending=useRef<Command|null>(null),base='/api/v1/acl-admissions/'+encodeURIComponent(detail.id);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{const abort=new AbortController();setPage({rows:[],nextCursor:null});apiRequest<Page>(base+'/simulations',{signal:abort.signal}).then(v=>{if(!abort.signal.aborted)setPage(v);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Versões indisponíveis.');});return()=>abort.abort();},[base,detail.revision]);
 async function send(body:Command){if(flight.current)return;flight.current=true;setBusy(true);setError('');pending.current=body;setRetry(false);try{const r=await apiRequest<{admission:WorkDetail}>(base+'/simulations/review',{method:'POST',body});if(alive.current){pending.current=null;setSelected('');setReason('');setChecked(false);onUpdated(r.admission);}}catch(e){if(alive.current){setError(e instanceof Error?e.message:'Revisão indisponível.');if(e instanceof ApiError&&e.status<500)pending.current=null;else setRetry(true);}}finally{flight.current=false;if(alive.current)setBusy(false);}}
 async function refresh(){if(flight.current)return;flight.current=true;setBusy(true);try{const r=await apiRequest<WorkDetail>(base);if(alive.current){pending.current=null;setRetry(false);setSelected('');setChecked(false);setReason('');setError('');onUpdated(r);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Atualização indisponível.');}finally{flight.current=false;if(alive.current)setBusy(false);}}
 async function more(){if(!page.nextCursor||flight.current)return;flight.current=true;setBusy(true);try{const r=await apiRequest<Page>(base+'/simulations?after='+encodeURIComponent(page.nextCursor));if(alive.current)setPage(old=>({...r,rows:[...old.rows,...r.rows]}));}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Versões indisponíveis.');}finally{flight.current=false;if(alive.current)setBusy(false);}}
 const chosen=page.rows.find(v=>v.id===selected),running=detail.stages.find(s=>s.key==='feasibility')?.status==='RUNNING';
 return <section aria-label="Versões do estudo econômico"><h3>Estudo econômico — versões internas</h3><p>Versões preservam fonte, fórmula, tarifas e condições. “Premissas revisadas” não aprova viabilidade, economia, contratação ou início do suprimento. Fontes podem ser substituídas após o registro; a revisão verifica sua vigência novamente.</p>
 {!page.rows.length?<p>Nenhuma versão registrada neste processo.</p>:null}
 {[...page.rows].sort((a,b)=>b.version-a.version).map(v=>{const r=v.body.result,p=r.proposal;return <details className={styles.panel} key={v.id}><summary>Versão {v.version} · {p.supplier} · {v.review?.decision==='REVIEWED'?'Premissas revisadas':v.review?.decision==='REJECTED'?'Rejeitada':'Aguardando revisão'} · Estudo parcial</summary><p>Registrada por {v.actorName} em {new Date(v.createdAt).toLocaleString('pt-BR')}. Fórmula: {r.formulaVersion}.</p><p>Vigência simulada: {p.startMonth}, {p.months} meses. Energia: {p.energyBrlMwh} R$/MWh. Fixo mensal: {money(p.fixedMonthlyBrl)} + {p.savingsPercent}% da economia positiva antes dos honorários. Custo ACL adicional estimado: {money(p.estimatedMonthlyAclBrl)}/mês.</p><p>Perdas: {p.losses==='INCLUDED'?'declaradas incluídas':p.losses==='EXCLUDED'?'excluídas, valor pendente':'pendentes'}. Tributos: {p.taxes==='INCLUDED'?'declarados incluídos':p.taxes==='EXCLUDED'?'excluídos, valor pendente':'pendentes'}.</p>{p.energyBasis?<p>Memória da energia: preço-base {p.energyBasis.baseBrlMwh} R$/MWh × (1 + {p.energyBasis.lossPercent}% perdas) ÷ (1 − {p.energyBasis.icmsPercent}% ICMS por dentro). Fração exata por linha, arredondada em centavos; TUSD sem reaplicação destes percentuais.</p>:null}<p>Fonte da proposta: {p.source}</p>{p.distribution?<><p>Tarifas-base: ponta {p.distribution.peakBrlKwh} R$/kWh, fora ponta {p.distribution.offPeakBrlKwh} R$/kWh, demanda {p.distribution.demandBrlKw} R$/kW. Desconto {p.distribution.discountPercent}% na ponta e demanda; fora ponta integral.</p><p>Fonte TUSD: {p.distribution.source}</p></>:<p>TUSD não informada.</p>}<p>Submercado sugerido: {r.location.label??'Pendente'}. Endereço fonte: {r.location.address??'Pendente'}.</p><p>Subtotal energético: {money(r.energySubtotal)}. Subtotal dos componentes simulados: {r.knownComponentsSubtotal===null?'Pendente':money(r.knownComponentsSubtotal)}. Economia, custo ACL completo, honorário variável, ROI e payback: pendentes.</p><GdReferenceComparison costs={p.costPremises} comparison={r.gdComparison} history={r.gdHistory}/><ul>{r.pending.map(p=><li key={p}>{p}</li>)}</ul><details><summary>Memória mensal e rastreabilidade</summary><div className={styles.table}><table><thead><tr><th>Mês</th><th>Mês fonte</th><th>Consumo kWh</th><th>Demanda medida kW</th><th>Energia</th><th>Subtotal parcial</th></tr></thead><tbody>{r.rows.map(m=><tr key={m.month}><td>{m.month}</td><td>{m.sourceMonth}</td><td>{m.referenceKwh}</td><td>{m.measuredDemandKw}</td><td>{money(m.energy)}</td><td>{m.knownComponentsSubtotal===null?'Pendente':money(m.knownComponentsSubtotal)}</td></tr>)}</tbody></table></div><p>Hash da versão: {v.hash}</p>{v.body.source.documents.map(d=><p key={d.id}>Documento {d.id}, versão {d.version}, SHA-256 {d.fileHash}.</p>)}{r.warnings.map(w=><p key={w}>{w}</p>)}</details>{v.review?<p>{v.review.actorName} · {new Date(v.review.reviewedAt).toLocaleString('pt-BR')}: {v.review.reason}</p>:null}
 {canApprove&&running&&v.createdBy!==actorId&&!v.review?<Button disabled={busy||retry} onClick={()=>{setSelected(v.id);setReason('');setChecked(false);}}>Conferir versão {v.version}</Button>:null}</details>;})}
 {chosen?<fieldset disabled={busy||retry}><legend>Revisão da versão {chosen.version}</legend><label>Parecer sobre as premissas<textarea maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);setChecked(false);}}/></label><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> Conferi esta versão e suas fontes. O estudo permanece parcial, com as pendências indicadas.</label>{(['REVIEW','REJECT'] as const).map(action=><Button key={action} disabled={!checked||reason.trim().length<20||!running||busy||retry} onClick={()=>void send({requestId:crypto.randomUUID(),expectedRevision:detail.revision,studyId:chosen.id,hash:chosen.hash,reason:reason.trim(),checkedDocument:true,action})}>{action==='REVIEW'?'Confirmar revisão das premissas':'Rejeitar versão'}</Button>)}</fieldset>:null}
 {error?<Alert>{error}</Alert>:null}{retry?<Button disabled={busy} onClick={()=>pending.current&&void send(pending.current)}>Repetir a mesma revisão</Button>:null}<Button disabled={busy} onClick={()=>void refresh()}>Atualizar versões e processo</Button>{page.nextCursor?<Button disabled={busy||retry} onClick={()=>void more()}>Mais versões</Button>:null}</section>;
}
