'use client';
import {useEffect,useRef,useState} from 'react';
import {ApiError,apiRequest} from '@/app/lib/api/client';
import {Alert,Button} from '@/app/components/ui';
import GdReferenceComparison,{type CostPremises,type GdComparison,type GdHistory} from './GdReferenceComparison';
import styles from './workspace.module.css';
import ScenarioAutofill,{type ScenarioDraft} from './ScenarioAutofill';
import type {WorkDetail} from './WorkControls';
type Result={gdComparison?:GdComparison;gdHistory?:GdHistory|null;proposal:{costPremises?:CostPremises;energyBrlMwh:string;energyBasis?:{baseBrlMwh:string;lossPercent:string;icmsPercent:string}};location:{address:string|null;uf:string|null;code:string|null;label:string|null;documentId:string;status:string};energySubtotal:string;fixedFeeSubtotal:string;estimatedAdditionalSubtotal:string;knownComponentsSubtotal:string|null;feeFormula:string;pending:string[];warnings:string[];rows:{month:string;sourceMonth:string;referenceKwh:string;energy:string;fixedFee:string;estimatedAdditional:string;knownComponentsSubtotal:string|null;tusd:{peak:{amount:string};offPeak:string;measuredDemand:{amount:string}}|null}[]};
export default function SupplierPreview({admissionId,evidenceId,detail,canSave,onUpdated}:{admissionId:string;evidenceId:string;detail:WorkDetail;canSave:boolean;onUpdated:(v:WorkDetail)=>void}){
 const [proposal,setProposal]=useState({supplier:'',energyBrlMwh:'',startMonth:'',months:'12',fixedMonthlyBrl:'',savingsPercent:'',estimatedMonthlyAclBrl:'350',losses:'PENDING',taxes:'PENDING',source:''}),[checked,setChecked]=useState(false),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [distribution,setDistribution]=useState({peakBrlKwh:'',offPeakBrlKwh:'',demandBrlKw:'',discountPercent:'50',source:''}),[includeDistribution,setIncludeDistribution]=useState(true);
 const [retry,setRetry]=useState(false);
 const [structuredEnergy,setStructuredEnergy]=useState(false),[basis,setBasis]=useState({baseBrlMwh:'',lossPercent:'2.5',icmsPercent:'18'});
 const [includeCosts,setIncludeCosts]=useState(false),[estimateGd,setEstimateGd]=useState(false),[gdMethod,setGdMethod]=useState('REFERENCE_RATIO_TOTAL_POINT_REDUCTION'),[costs,setCosts]=useState({additionalCostDescription:'Contribuição associativa',cceePercent:'9',migrationInvestmentBrl:'9300',source:''});
 const [autofill,setAutofill]=useState<ScenarioDraft|null>(null);
 function applyDraft(d:ScenarioDraft){controller.current?.abort();setResult(null);setChecked(false);setError('');const p=d.proposal;setProposal({supplier:p.supplier,energyBrlMwh:p.energyBrlMwh,startMonth:p.startMonth,months:String(p.months),fixedMonthlyBrl:p.fixedMonthlyBrl,savingsPercent:p.savingsPercent,estimatedMonthlyAclBrl:p.estimatedMonthlyAclBrl,losses:p.losses,taxes:p.taxes,source:p.source});setStructuredEnergy(!!p.energyBasis);setBasis(p.energyBasis?{baseBrlMwh:p.energyBasis.baseBrlMwh,lossPercent:p.energyBasis.lossPercent,icmsPercent:p.energyBasis.icmsPercent}:{baseBrlMwh:'',lossPercent:'2.5',icmsPercent:'18'});setIncludeDistribution(!!p.distribution);setDistribution(p.distribution?{peakBrlKwh:p.distribution.peakBrlKwh,offPeakBrlKwh:p.distribution.offPeakBrlKwh,demandBrlKw:p.distribution.demandBrlKw,discountPercent:p.distribution.discountPercent,source:p.distribution.source}:{peakBrlKwh:'',offPeakBrlKwh:'',demandBrlKw:'',discountPercent:'50',source:''});setIncludeCosts(!!p.costPremises);setCosts(p.costPremises?{additionalCostDescription:p.costPremises.additionalCostDescription,cceePercent:p.costPremises.cceePercent,migrationInvestmentBrl:p.costPremises.migrationInvestmentBrl,source:p.costPremises.source}:{additionalCostDescription:'Contribuição associativa',cceePercent:'9',migrationInvestmentBrl:'9300',source:''});setEstimateGd(!!p.costPremises?.gdHistoryEstimate);setGdMethod(p.costPremises?.gdHistoryEstimate??'REFERENCE_RATIO_TOTAL_POINT_REDUCTION');setAutofill(d);}
 function changeCost(key:keyof typeof costs,value:string){controller.current?.abort();setBusy(false);setCosts(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 function changeBasis(key:keyof typeof basis,value:string){controller.current?.abort();setBusy(false);setBasis(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 function register(){try{void save({requestId:crypto.randomUUID(),expectedRevision:detail.revision,evidenceId,proposal:payloadProposal(),checkedDocument:true});}catch(e){setError(e instanceof Error?e.message:'Confira as premissas.');}}
 function payloadProposal(){
  const common={...proposal,...(includeCosts?{costPremises:{...costs,cceeBase:'REFERENCE_INVOICE_TOTAL',checked:true,...(estimateGd?{gdHistoryEstimate:gdMethod}:{})}}:{}),months:Number(proposal.months),distribution:includeDistribution?{...distribution,checked:true}:null,checked:true};
  if(!structuredEnergy)return common;
  if(!/^(0|[1-9][0-9]{0,8})(\.[0-9]{1,9})?$/.test(basis.baseBrlMwh)||!['lossPercent','icmsPercent'].every(k=>/^(100(\.0{1,4})?|[0-9]{1,2}(\.[0-9]{1,4})?)$/.test(basis[k as keyof typeof basis])))throw Error('Confira os decimais de preço-base, perdas e ICMS.');
  const units=(v:string)=>{const [a,f='']=v.split('.');return BigInt(a)*BigInt('10000')+BigInt(f.padEnd(4,'0'));};
  const tax=units(basis.icmsPercent);if(tax>=BigInt('1000000'))throw Error('ICMS deve ser inferior a 100%.');
  const [a,f='']=basis.baseBrlMwh.split('.'),den=BigInt('1'+'0'.repeat(f.length))*(BigInt('1000000')-tax),num=BigInt(a+f)*(BigInt('1000000')+units(basis.lossPercent));
  const n=((num*BigInt('1000000000')+den/BigInt('2'))/den).toString().padStart(10,'0'),rate=(n.slice(0,-9)+'.'+n.slice(-9)).replace(/\.?0+$/,'')||'0';
  return {...common,energyBrlMwh:rate,losses:'INCLUDED',taxes:'INCLUDED',energyBasis:{...basis,method:'LOSS_UPLIFT_ICMS_INSIDE',checked:true}};
 }
 const pending=useRef<Record<string,unknown>|null>(null),flight=useRef(false),alive=useRef(true);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 function change(key:keyof typeof proposal,value:string){controller.current?.abort();setBusy(false);setProposal(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 function changeDistribution(key:keyof typeof distribution,value:string){controller.current?.abort();setBusy(false);setDistribution(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 async function simulate(){controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setResult(null);setError('');try{const r=await apiRequest<Result>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/supplier-preview',{method:'POST',body:{evidenceId,proposal:payloadProposal()},signal:abort.signal});if(!abort.signal.aborted)setResult(r);}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Prévia comercial indisponível.');}finally{if(!abort.signal.aborted)setBusy(false);}}
 async function save(body:Record<string,unknown>){if(flight.current)return;flight.current=true;setBusy(true);setError('');setRetry(false);pending.current=body;try{const r=await apiRequest<{admission:WorkDetail}>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/simulations',{method:'POST',body});if(alive.current){pending.current=null;onUpdated(r.admission);}}catch(e){if(alive.current){setError(e instanceof Error?e.message:'Versão indisponível.');if(e instanceof ApiError&&e.status<500)pending.current=null;else setRetry(true);}}finally{flight.current=false;if(alive.current)setBusy(false);}}
 async function refresh(){if(flight.current)return;flight.current=true;setBusy(true);try{const r=await apiRequest<WorkDetail>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId));if(alive.current){pending.current=null;setRetry(false);setResult(null);setChecked(false);setError('');onUpdated(r);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Atualização indisponível.');}finally{flight.current=false;if(alive.current)setBusy(false);}}
 const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <section aria-label="Prévia comercial ACL"><h4>Proposta comercial — prévia parcial</h4><p>Reutiliza o consumo do mesmo mês do histórico aprovado como referência sazonal. Os valores não são previsão de consumo, custo ACL completo ou economia. Esta prévia é temporária; a proposta e sua aprovação documental continuam pendentes.</p>
 <ScenarioAutofill admissionId={admissionId} evidenceId={evidenceId} disabled={busy||retry} onFilled={applyDraft} onBusy={setBusy}/>
 {autofill?<div className={styles.panel}><h5>Sugestões preenchidas — conferir antes de simular</h5><p>Modelo: versão {autofill.template.version}, estudo {autofill.template.studyId}. Hash {autofill.template.hash}. Estado: {autofill.template.review==='REVIEWED'?'Premissas revisadas':'Aguardando revisão'}. Editar campos altera as sugestões; a conferência abaixo permanece obrigatória.</p><ul>{autofill.pending.map(v=><li key={v}>{v}</li>)}</ul>{autofill.tariffProof.map(v=><p key={v.field}>Tarifa sugerida {({peakBrlKwh:'TUSD ponta',offPeakBrlKwh:'TUSD fora de ponta',demandBrlKw:'TUSD demanda'} as Record<string,string>)[v.field]??v.field}: {v.value}. Fatura {v.documentId}, competência {v.month}, página {v.pages.join(', ')}, fonte {v.source}.</p>)}</div>:null}
 <fieldset disabled={busy||retry}><legend>Parâmetros informados pelo Consultor</legend>
 {([['supplier','Comercializadora'],['energyBrlMwh','Preço de energia (R$/MWh)'],['fixedMonthlyBrl','Honorário fixo mensal (R$)'],['savingsPercent','Honorário sobre economia positiva antes dos honorários (%)'],['estimatedMonthlyAclBrl','Custo ACL adicional estimado mensal (R$)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode={key==='supplier'?'text':'decimal'} value={proposal[key]} disabled={structuredEnergy&&key==='energyBrlMwh'} onChange={e=>change(key,e.target.value)} placeholder={key==='supplier'?'Nome da comercializadora':'Decimal com ponto'} maxLength={key==='supplier'?120:30}/></label>)}
 <label><input type="checkbox" checked={structuredEnergy} onChange={e=>{controller.current?.abort();setBusy(false);setStructuredEnergy(e.target.checked);setChecked(false);setResult(null);setError('');}}/> Calcular energia com perdas e ICMS por dentro</label>{structuredEnergy?<fieldset><legend>Premissas de energia separadas</legend><p>Preço efetivo = preço-base × (1 + perdas/100) ÷ (1 − ICMS/100). Os percentuais são premissas editáveis do cenário, sujeitas à conferência. A TUSD não recebe esses acréscimos.</p>{([['baseBrlMwh','Preço-base da energia sem perdas e ICMS (R$/MWh)'],['lossPercent','Acréscimo de perdas (%)'],['icmsPercent','ICMS por dentro (%)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode="decimal" value={basis[key]} onChange={e=>changeBasis(key,e.target.value)}/></label>)}</fieldset>:null}
 <label><input type="checkbox" checked={includeCosts} onChange={e=>{controller.current?.abort();setBusy(false);setIncludeCosts(e.target.checked);setChecked(false);setResult(null);}}/> Incluir encargos estimados, investimento e comparação GD</label>{includeCosts?<fieldset><legend>Custos estimados do cenário</legend><p>ERR+ERCAP incidem sobre o total da fatura de referência. Não são cobrança efetiva da CCEE e podem variar com sazonalidade e mercado. Investimento não integra o custo mensal.</p>{([['additionalCostDescription','Composição do custo ACL adicional'],['cceePercent','Encargos ERR+ERCAP estimados (%)'],['migrationInvestmentBrl','Investimento de homologação estimado (R$)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" value={costs[key]} onChange={e=>changeCost(key,e.target.value)}/></label>)}<label>Fonte das premissas de custos e GD<textarea maxLength={500} value={costs.source} onChange={e=>changeCost('source',e.target.value)}/></label><label><input type="checkbox" checked={estimateGd} onChange={e=>{controller.current?.abort();setBusy(false);setEstimateGd(e.target.checked);setChecked(false);setResult(null);}}/> Estimar GD histórica pela proporção da fatura aplicada ao consumo total</label>{estimateGd?<label>Ajuste do percentual GD por consumo mensal<select value={gdMethod} onChange={e=>{controller.current?.abort();setBusy(false);setGdMethod(e.target.value);setChecked(false);setResult(null);}}><option value="REFERENCE_RATIO_TOTAL_POINT_REDUCTION">Subtrair a queda de consumo em pontos percentuais</option><option value="REFERENCE_RATIO_TOTAL_CONSERVATIVE_CAP">Limitar pelo consumo relativo ao mês de referência</option><option value="REFERENCE_RATIO_TOTAL_PROPORTIONAL">Reduzir proporcionalmente ao consumo relativo</option><option value="REFERENCE_RATIO_TOTAL">Proporção de referência sem ajuste mensal</option></select></label>:null}<p>GD da referência ÷ consumo fora de ponta da referência × consumo total de cada mês histórico. Usa as mesmas tarifas de crédito GD; valores estimados para comparação econômica, sem comprovação de créditos disponíveis.</p></fieldset>:null}
 <label>Início da vigência (mês)<input type="month" value={proposal.startMonth} onChange={e=>change('startMonth',e.target.value)}/></label><label>Vigência (meses, até 12)<input type="number" min={1} max={12} step={1} value={proposal.months} onChange={e=>change('months',e.target.value)}/></label>
 {([['losses','Perdas no preço informado'],['taxes','Tributos no preço informado']] as const).map(([key,label])=><label key={key}>{label}<select disabled={structuredEnergy} value={structuredEnergy?'INCLUDED':proposal[key]} onChange={e=>change(key,e.target.value)}><option value="PENDING">Ainda não confirmado</option><option value="INCLUDED">Incluídos, conforme proposta</option><option value="EXCLUDED">Excluídos, valores ainda pendentes</option></select></label>)}
 <p>O custo ACL adicional é uma estimativa mensal separada de energia, TUSD e honorários. Informe sua composição na fonte para evitar duplicidade.</p><label>Fonte, versão e condições da proposta<textarea maxLength={500} value={proposal.source} onChange={e=>change('source',e.target.value)}/></label><label><input type="checkbox" checked={includeDistribution} onChange={e=>{controller.current?.abort();setBusy(false);setIncludeDistribution(e.target.checked);setChecked(false);setResult(null);}}/> Incluir cenário TUSD com desconto</label>
 {includeDistribution?<fieldset><legend>TUSD — tarifas-base anteriores ao desconto</legend><p>Desconto aplicado somente na ponta e na demanda. Fora de ponta permanece integral. A demanda do histórico é medida e será tratada como estimativa.</p>{([['peakBrlKwh','TUSD ponta (R$/kWh)'],['offPeakBrlKwh','TUSD fora de ponta integral (R$/kWh)'],['demandBrlKw','TUSD demanda (R$/kW)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode="decimal" value={distribution[key]} onChange={e=>changeDistribution(key,e.target.value)} placeholder="Tarifa-base sem desconto, decimal com ponto"/></label>)}<label>Desconto sobre TUSD ponta e demanda (%)<input type="number" min={50} max={100} step="0.0001" value={distribution.discountPercent} onChange={e=>changeDistribution('discountPercent',e.target.value)}/></label><label>Fonte, competência e tratamento tributário da TUSD<textarea maxLength={500} value={distribution.source} onChange={e=>changeDistribution('source',e.target.value)}/></label></fieldset>:null}
 <label><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setResult(null);}}/> Conferi fornecedor, valores, vigência, tarifas-base TUSD e condições declaradas para esta prévia interna.</label></fieldset>
 <Button disabled={busy||retry||!checked||Object.entries(proposal).some(([k,v])=>!(structuredEnergy&&['energyBrlMwh','losses','taxes'].includes(k))&&!v.trim())||structuredEnergy&&Object.values(basis).some(v=>!v.trim())||includeDistribution&&Object.values(distribution).some(v=>!v.trim())||includeCosts&&Object.values(costs).some(v=>!v.trim())} onClick={()=>void simulate()}>Simular proposta comercial</Button>{error?<Alert>{error}</Alert>:null}
 {retry?<><Button disabled={busy} onClick={()=>pending.current&&void save(pending.current)}>Repetir o mesmo registro</Button><Button disabled={busy} onClick={()=>void refresh()}>Atualizar processo antes de continuar</Button></>:null}
 {result?<><p>Para preservar esta prévia, inicie a atividade Viabilidade. O registro cria uma versão interna imutável, ainda parcial e sujeita à revisão independente.</p><Button disabled={busy||retry||!canSave} onClick={register}>Registrar versão do estudo parcial</Button><div className={styles.panel}><p>Submercado pelo endereço da fatura: <strong>{result.location.label??"Pendente de identificação"}</strong> · UF {result.location.uf??"não identificada"}</p>{result.location.address?<p>Endereço da UC na fonte: {result.location.address}</p>:null}<p>Documento: {result.location.documentId}. Sugestão por UF sujeita à revisão do Consultor; não altera o cadastro nem confirma a modelagem CCEE.</p>{result.proposal?.energyBasis?<p>Energia: base {result.proposal.energyBasis.baseBrlMwh} R$/MWh × (1 + {result.proposal.energyBasis.lossPercent}% perdas) ÷ (1 − {result.proposal.energyBasis.icmsPercent}% ICMS). Preço efetivo de referência: {result.proposal.energyBrlMwh} R$/MWh. O cálculo mensal usa a fração exata, com arredondamento final em centavos.</p>:null}<p>Energia na vigência (parcial): <strong>{money(result.energySubtotal)}</strong></p><p>Honorário fixo na vigência: <strong>{money(result.fixedFeeSubtotal)}</strong></p><p>Custo ACL adicional estimado na vigência: <strong>{money(result.estimatedAdditionalSubtotal)}</strong></p>{result.knownComponentsSubtotal!==null?<p>Subtotal dos componentes simulados (parcial): <strong>{money(result.knownComponentsSubtotal)}</strong></p>:null}<p>Honorário variável, economia líquida, ROI e payback: pendentes.</p></div><GdReferenceComparison costs={result.proposal.costPremises} comparison={result.gdComparison} history={result.gdHistory}/><p>{result.feeFormula}</p><h5>Pendências para viabilidade completa</h5><ul>{result.pending.map(p=><li key={p}>{p}</li>)}</ul>{result.warnings.map(w=><p key={w}>{w}</p>)}<div className={styles.table}><table><caption>Referência sazonal por mês — componentes parciais</caption><thead><tr><th>Mês da vigência</th><th>Mês fonte</th><th>Consumo de referência (kWh)</th><th>Energia</th><th>TUSD ponta descontada</th><th>TUSD fora de ponta integral</th><th>Demanda medida descontada (estimativa)</th><th>Fixo mensal</th><th>Custo ACL estimado</th><th>Subtotal parcial</th><th>Variável</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.sourceMonth}</td><td>{Number(r.referenceKwh).toLocaleString('pt-BR',{maximumFractionDigits:6})}</td><td>{money(r.energy)}</td><td>{r.tusd?money(r.tusd.peak.amount):"Pendente"}</td><td>{r.tusd?money(r.tusd.offPeak):"Pendente"}</td><td>{r.tusd?money(r.tusd.measuredDemand.amount):"Pendente"}</td><td>{money(r.fixedFee)}</td><td>{money(r.estimatedAdditional)}</td><td>{r.knownComponentsSubtotal!==null?money(r.knownComponentsSubtotal):"Pendente"}</td><td>Pendente</td></tr>)}</tbody></table></div></>:null}</section>;
}
