'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {Alert,Button} from '@/app/components/ui';
import styles from './workspace.module.css';
type Result={energySubtotal:string;fixedFeeSubtotal:string;feeFormula:string;pending:string[];warnings:string[];rows:{month:string;sourceMonth:string;referenceKwh:string;energy:string;fixedFee:string}[]};
export default function SupplierPreview({admissionId,evidenceId}:{admissionId:string;evidenceId:string}){
 const [proposal,setProposal]=useState({supplier:'',energyBrlMwh:'',startMonth:'',months:'12',fixedMonthlyBrl:'',savingsPercent:'',losses:'PENDING',taxes:'PENDING',source:''}),[checked,setChecked]=useState(false),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 function change(key:keyof typeof proposal,value:string){controller.current?.abort();setBusy(false);setProposal(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 async function simulate(){controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setResult(null);setError('');try{const r=await apiRequest<Result>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/supplier-preview',{method:'POST',body:{evidenceId,proposal:{...proposal,months:Number(proposal.months),checked:true}},signal:abort.signal});if(!abort.signal.aborted)setResult(r);}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Prévia comercial indisponível.');}finally{if(!abort.signal.aborted)setBusy(false);}}
 const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <section aria-label="Prévia comercial ACL"><h4>Proposta comercial — prévia parcial</h4><p>Reutiliza o consumo do mesmo mês do histórico aprovado como referência sazonal. Os valores não são previsão de consumo, custo ACL completo ou economia. Esta prévia é temporária; a proposta e sua aprovação documental continuam pendentes.</p>
 <fieldset disabled={busy}><legend>Parâmetros informados pelo Consultor</legend>
 {([['supplier','Comercializadora'],['energyBrlMwh','Preço de energia (R$/MWh)'],['fixedMonthlyBrl','Honorário fixo mensal (R$)'],['savingsPercent','Honorário sobre economia positiva antes dos honorários (%)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode={key==='supplier'?'text':'decimal'} value={proposal[key]} onChange={e=>change(key,e.target.value)} placeholder={key==='supplier'?'Nome da comercializadora':'Decimal com ponto'} maxLength={key==='supplier'?120:30}/></label>)}
 <label>Início da vigência (mês)<input type="month" value={proposal.startMonth} onChange={e=>change('startMonth',e.target.value)}/></label><label>Vigência (meses, até 12)<input type="number" min={1} max={12} step={1} value={proposal.months} onChange={e=>change('months',e.target.value)}/></label>
 {([['losses','Perdas no preço informado'],['taxes','Tributos no preço informado']] as const).map(([key,label])=><label key={key}>{label}<select value={proposal[key]} onChange={e=>change(key,e.target.value)}><option value="PENDING">Ainda não confirmado</option><option value="INCLUDED">Incluídos, conforme proposta</option><option value="EXCLUDED">Excluídos, valores ainda pendentes</option></select></label>)}
 <label>Fonte, versão e condições da proposta<textarea maxLength={500} value={proposal.source} onChange={e=>change('source',e.target.value)}/></label><label><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setResult(null);}}/> Conferi fornecedor, valores, vigência e condições declaradas para esta prévia interna.</label></fieldset>
 <Button disabled={busy||!checked||Object.values(proposal).some(v=>!v.trim())} onClick={()=>void simulate()}>Simular proposta comercial</Button>{error?<Alert>{error}</Alert>:null}
 {result?<><div className={styles.panel}><p>Energia na vigência (parcial): <strong>{money(result.energySubtotal)}</strong></p><p>Honorário fixo na vigência: <strong>{money(result.fixedFeeSubtotal)}</strong></p><p>Honorário variável, economia líquida, ROI e payback: pendentes.</p></div><p>{result.feeFormula}</p><h5>Pendências para viabilidade completa</h5><ul>{result.pending.map(p=><li key={p}>{p}</li>)}</ul>{result.warnings.map(w=><p key={w}>{w}</p>)}<div className={styles.table}><table><caption>Referência sazonal por mês — componentes parciais</caption><thead><tr><th>Mês da vigência</th><th>Mês fonte</th><th>Consumo de referência (kWh)</th><th>Energia</th><th>Fixo mensal</th><th>Variável</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.sourceMonth}</td><td>{Number(r.referenceKwh).toLocaleString('pt-BR',{maximumFractionDigits:6})}</td><td>{money(r.energy)}</td><td>{money(r.fixedFee)}</td><td>Pendente</td></tr>)}</tbody></table></div></>:null}</section>;
}
