'use client';
import {useEffect,useRef,useState} from 'react';
import {ApiError,apiRequest} from '@/app/lib/api/client';
import {Alert,Button} from '@/app/components/ui';
import styles from './workspace.module.css';
import type {WorkDetail} from './WorkControls';
type Result={location:{address:string|null;uf:string|null;code:string|null;label:string|null;documentId:string;status:string};energySubtotal:string;fixedFeeSubtotal:string;estimatedAdditionalSubtotal:string;knownComponentsSubtotal:string|null;feeFormula:string;pending:string[];warnings:string[];rows:{month:string;sourceMonth:string;referenceKwh:string;energy:string;fixedFee:string;estimatedAdditional:string;knownComponentsSubtotal:string|null;tusd:{peak:{amount:string};offPeak:string;measuredDemand:{amount:string}}|null}[]};
export default function SupplierPreview({admissionId,evidenceId,detail,canSave,onUpdated}:{admissionId:string;evidenceId:string;detail:WorkDetail;canSave:boolean;onUpdated:(v:WorkDetail)=>void}){
 const [proposal,setProposal]=useState({supplier:'',energyBrlMwh:'',startMonth:'',months:'12',fixedMonthlyBrl:'',savingsPercent:'',estimatedMonthlyAclBrl:'350',losses:'PENDING',taxes:'PENDING',source:''}),[checked,setChecked]=useState(false),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [distribution,setDistribution]=useState({peakBrlKwh:'',offPeakBrlKwh:'',demandBrlKw:'',discountPercent:'50',source:''}),[includeDistribution,setIncludeDistribution]=useState(true);
 const [retry,setRetry]=useState(false);
 const pending=useRef<Record<string,unknown>|null>(null),flight=useRef(false),alive=useRef(true);
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;controller.current?.abort();};},[]);
 function change(key:keyof typeof proposal,value:string){controller.current?.abort();setBusy(false);setProposal(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 function changeDistribution(key:keyof typeof distribution,value:string){controller.current?.abort();setBusy(false);setDistribution(old=>({...old,[key]:value}));setChecked(false);setResult(null);setError('');}
 async function simulate(){controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(true);setResult(null);setError('');try{const r=await apiRequest<Result>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/supplier-preview',{method:'POST',body:{evidenceId,proposal:{...proposal,months:Number(proposal.months),distribution:includeDistribution?{...distribution,checked:true}:null,checked:true}},signal:abort.signal});if(!abort.signal.aborted)setResult(r);}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Prévia comercial indisponível.');}finally{if(!abort.signal.aborted)setBusy(false);}}
 async function save(body:Record<string,unknown>){if(flight.current)return;flight.current=true;setBusy(true);setError('');setRetry(false);pending.current=body;try{const r=await apiRequest<{admission:WorkDetail}>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId)+'/simulations',{method:'POST',body});if(alive.current){pending.current=null;onUpdated(r.admission);}}catch(e){if(alive.current){setError(e instanceof Error?e.message:'Versão indisponível.');if(e instanceof ApiError&&e.status<500)pending.current=null;else setRetry(true);}}finally{flight.current=false;if(alive.current)setBusy(false);}}
 async function refresh(){if(flight.current)return;flight.current=true;setBusy(true);try{const r=await apiRequest<WorkDetail>('/api/v1/acl-admissions/'+encodeURIComponent(admissionId));if(alive.current){pending.current=null;setRetry(false);setResult(null);setChecked(false);setError('');onUpdated(r);}}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Atualização indisponível.');}finally{flight.current=false;if(alive.current)setBusy(false);}}
 const money=(v:string)=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <section aria-label="Prévia comercial ACL"><h4>Proposta comercial — prévia parcial</h4><p>Reutiliza o consumo do mesmo mês do histórico aprovado como referência sazonal. Os valores não são previsão de consumo, custo ACL completo ou economia. Esta prévia é temporária; a proposta e sua aprovação documental continuam pendentes.</p>
 <fieldset disabled={busy||retry}><legend>Parâmetros informados pelo Consultor</legend>
 {([['supplier','Comercializadora'],['energyBrlMwh','Preço de energia (R$/MWh)'],['fixedMonthlyBrl','Honorário fixo mensal (R$)'],['savingsPercent','Honorário sobre economia positiva antes dos honorários (%)'],['estimatedMonthlyAclBrl','Custo ACL adicional estimado mensal (R$)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode={key==='supplier'?'text':'decimal'} value={proposal[key]} onChange={e=>change(key,e.target.value)} placeholder={key==='supplier'?'Nome da comercializadora':'Decimal com ponto'} maxLength={key==='supplier'?120:30}/></label>)}
 <label>Início da vigência (mês)<input type="month" value={proposal.startMonth} onChange={e=>change('startMonth',e.target.value)}/></label><label>Vigência (meses, até 12)<input type="number" min={1} max={12} step={1} value={proposal.months} onChange={e=>change('months',e.target.value)}/></label>
 {([['losses','Perdas no preço informado'],['taxes','Tributos no preço informado']] as const).map(([key,label])=><label key={key}>{label}<select value={proposal[key]} onChange={e=>change(key,e.target.value)}><option value="PENDING">Ainda não confirmado</option><option value="INCLUDED">Incluídos, conforme proposta</option><option value="EXCLUDED">Excluídos, valores ainda pendentes</option></select></label>)}
 <p>O custo ACL adicional é uma estimativa mensal separada de energia, TUSD e honorários. Informe sua composição na fonte para evitar duplicidade.</p><label>Fonte, versão e condições da proposta<textarea maxLength={500} value={proposal.source} onChange={e=>change('source',e.target.value)}/></label><label><input type="checkbox" checked={includeDistribution} onChange={e=>{controller.current?.abort();setBusy(false);setIncludeDistribution(e.target.checked);setChecked(false);setResult(null);}}/> Incluir cenário TUSD com desconto</label>
 {includeDistribution?<fieldset><legend>TUSD — tarifas-base anteriores ao desconto</legend><p>Desconto aplicado somente na ponta e na demanda. Fora de ponta permanece integral. A demanda do histórico é medida e será tratada como estimativa.</p>{([['peakBrlKwh','TUSD ponta (R$/kWh)'],['offPeakBrlKwh','TUSD fora de ponta integral (R$/kWh)'],['demandBrlKw','TUSD demanda (R$/kW)']] as const).map(([key,label])=><label key={key}>{label}<input type="text" inputMode="decimal" value={distribution[key]} onChange={e=>changeDistribution(key,e.target.value)} placeholder="Tarifa-base sem desconto, decimal com ponto"/></label>)}<label>Desconto sobre TUSD ponta e demanda (%)<input type="number" min={50} max={100} step="0.0001" value={distribution.discountPercent} onChange={e=>changeDistribution('discountPercent',e.target.value)}/></label><label>Fonte, competência e tratamento tributário da TUSD<textarea maxLength={500} value={distribution.source} onChange={e=>changeDistribution('source',e.target.value)}/></label></fieldset>:null}
 <label><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setResult(null);}}/> Conferi fornecedor, valores, vigência, tarifas-base TUSD e condições declaradas para esta prévia interna.</label></fieldset>
 <Button disabled={busy||retry||!checked||Object.values(proposal).some(v=>!v.trim())||includeDistribution&&Object.values(distribution).some(v=>!v.trim())} onClick={()=>void simulate()}>Simular proposta comercial</Button>{error?<Alert>{error}</Alert>:null}
 {retry?<><Button disabled={busy} onClick={()=>pending.current&&void save(pending.current)}>Repetir o mesmo registro</Button><Button disabled={busy} onClick={()=>void refresh()}>Atualizar processo antes de continuar</Button></>:null}
 {result?<><p>Para preservar esta prévia, inicie a atividade Viabilidade. O registro cria uma versão interna imutável, ainda parcial e sujeita à revisão independente.</p><Button disabled={busy||retry||!canSave} onClick={()=>void save({requestId:crypto.randomUUID(),expectedRevision:detail.revision,evidenceId,proposal:{...proposal,months:Number(proposal.months),distribution:includeDistribution?{...distribution,checked:true}:null,checked:true},checkedDocument:true})}>Registrar versão do estudo parcial</Button><div className={styles.panel}><p>Submercado pelo endereço da fatura: <strong>{result.location.label??"Pendente de identificação"}</strong> · UF {result.location.uf??"não identificada"}</p>{result.location.address?<p>Endereço da UC na fonte: {result.location.address}</p>:null}<p>Documento: {result.location.documentId}. Sugestão por UF sujeita à revisão do Consultor; não altera o cadastro nem confirma a modelagem CCEE.</p><p>Energia na vigência (parcial): <strong>{money(result.energySubtotal)}</strong></p><p>Honorário fixo na vigência: <strong>{money(result.fixedFeeSubtotal)}</strong></p><p>Custo ACL adicional estimado na vigência: <strong>{money(result.estimatedAdditionalSubtotal)}</strong></p>{result.knownComponentsSubtotal!==null?<p>Subtotal dos componentes simulados (parcial): <strong>{money(result.knownComponentsSubtotal)}</strong></p>:null}<p>Honorário variável, economia líquida, ROI e payback: pendentes.</p></div><p>{result.feeFormula}</p><h5>Pendências para viabilidade completa</h5><ul>{result.pending.map(p=><li key={p}>{p}</li>)}</ul>{result.warnings.map(w=><p key={w}>{w}</p>)}<div className={styles.table}><table><caption>Referência sazonal por mês — componentes parciais</caption><thead><tr><th>Mês da vigência</th><th>Mês fonte</th><th>Consumo de referência (kWh)</th><th>Energia</th><th>TUSD ponta descontada</th><th>TUSD fora de ponta integral</th><th>Demanda medida descontada (estimativa)</th><th>Fixo mensal</th><th>Custo ACL estimado</th><th>Subtotal parcial</th><th>Variável</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.sourceMonth}</td><td>{Number(r.referenceKwh).toLocaleString('pt-BR',{maximumFractionDigits:6})}</td><td>{money(r.energy)}</td><td>{r.tusd?money(r.tusd.peak.amount):"Pendente"}</td><td>{r.tusd?money(r.tusd.offPeak):"Pendente"}</td><td>{r.tusd?money(r.tusd.measuredDemand.amount):"Pendente"}</td><td>{money(r.fixedFee)}</td><td>{money(r.estimatedAdditional)}</td><td>{r.knownComponentsSubtotal!==null?money(r.knownComponentsSubtotal):"Pendente"}</td><td>Pendente</td></tr>)}</tbody></table></div></>:null}</section>;
}
