import {createHmac} from 'node:crypto';
import {validSignature,validChallenge,statusEvents} from './whatsapp-delivery';
import {WhatsappWebhookController} from './whatsapp-delivery.controller';
describe('Meta delivery verification',()=>{
 const raw=Buffer.from('{"sample":true}'),secret='test-only-secret';
 const signature='sha256='+createHmac('sha256',secret).update(raw).digest('hex');
 const payload={object:'whatsapp_business_account',entry:[{id:'waba',changes:[{field:'messages',value:{metadata:{phone_number_id:'phone'},contacts:[{private:'excluded'}],messages:[{text:'excluded'}],statuses:[{id:'wamid.test',status:'failed',timestamp:'1791380000',recipient_id:'private',errors:[{code:131026,message:'private provider description'}]}]}}]}]};
 it('accepts the exact signed bytes and rejects tampering, missing config and malformed signatures',()=>{expect(validSignature(raw,signature,secret)).toBe(true);for(const args of [[Buffer.from('{}'),signature,secret],[raw,'sha256=00',secret],[raw,signature,undefined],[undefined,signature,secret]])expect(validSignature(...args as [Buffer|undefined,unknown,string|undefined])).toBe(false);});
 it('validates challenges only with matching configured token',()=>{expect(validChallenge('secret','secret')).toBe(true);expect(validChallenge('secret','different')).toBe(false);expect(validChallenge('',undefined)).toBe(false);});
 it('isolates account and sender and stores only status metadata',()=>{const events=statusEvents(payload,'waba','phone');expect(events).toHaveLength(1);expect(events[0].error_codes).toEqual([131026]);expect(JSON.stringify(events)).not.toMatch(/private|excluded/);expect(statusEvents(payload,'other','phone')).toEqual([]);expect(statusEvents(payload,'waba','other')).toEqual([]);expect(statusEvents(payload,undefined,'phone')).toEqual([]);});
 it('rejects unsupported statuses and invalid ids or timestamps',()=>{for(const patch of [{status:'accepted'},{id:'other'},{timestamp:'bad'}]){const p=JSON.parse(JSON.stringify(payload));Object.assign(p.entry[0].changes[0].value.statuses[0],patch);expect(statusEvents(p,'waba','phone')).toEqual([]);}});
 it('never persists unsigned callbacks',async()=>{const upsert=jest.fn();const controller=new WhatsappWebhookController({getClient:()=>({from:()=>({upsert})})} as any);await expect(controller.receive({headers:{},body:payload} as any)).rejects.toThrow('signature rejected');expect(upsert).not.toHaveBeenCalled();});
 it('requests provider retry on storage failure and deduplicates callbacks',async()=>{const old={...process.env};Object.assign(process.env,{WHATSAPP_APP_SECRET:secret,WHATSAPP_BUSINESS_ACCOUNT_ID:'waba',WHATSAPP_PHONE_NUMBER_ID:'phone'});try{const upsert=jest.fn().mockResolvedValue({error:{message:'unavailable'}});const controller=new WhatsappWebhookController({getClient:()=>({from:()=>({upsert})})} as any);const request={rawBody:raw,headers:{'x-hub-signature-256':signature},body:payload} as any;await expect(controller.receive(request)).rejects.toThrow('persistence unavailable');upsert.mockResolvedValue({error:null});await expect(controller.receive(request)).resolves.toEqual({received:true});expect(upsert).toHaveBeenLastCalledWith(statusEvents(payload,'waba','phone'),{onConflict:'event_key',ignoreDuplicates:true});}finally{process.env=old;}});
});
