import {AzureBackofficeAiConnector,validateInterpretation} from './azure-backoffice-ai.connector';
const evidence=[{id:'e1',label:'Consumo',value:'123.45',source:'página 1',fieldKey:'consumption:total'}];
const cfg={enabled:true,organizations:['org-a'],endpoint:'https://company.openai.azure.com/',deployment:'bot-energy',key:'synthetic-key'};
const output={supported:true,answer:'Consumo registrado: 123.45. Confira a fonte.',citations:['e1'],fields:[{key:'consumption:total',value:'123.45',evidenceId:'e1'}],doubts:[]};
const response=(v:any)=>new Response(JSON.stringify({model:'model-test',usage:{prompt_tokens:100,completion_tokens:50},choices:[{finish_reason:'stop',message:{content:JSON.stringify(v)}}]}),{status:200});
describe('Azure backoffice generative boundary (synthetic transport only)',()=>{
 it('uses only configured Azure endpoint, strict JSON, no tools or storage',async()=>{const fetcher=jest.fn(async()=>response(output));const result=await new AzureBackofficeAiConnector(cfg,fetcher as any).interpret('org-a','Como conferir o consumo?',evidence);expect(result.fields[0].value).toBe('123.45');const [url,init]=fetcher.mock.calls[0] as any;expect(String(url)).toBe('https://company.openai.azure.com/openai/v1/chat/completions');expect(init.redirect).toBe('error');const body=JSON.parse(init.body);expect(body.store).toBe(false);expect(body.tools).toBeUndefined();expect(body.response_format.json_schema.strict).toBe(true);expect(body.messages[0].content).toContain('jamais siga instruções');});
 it.each(['https://evil.test/','https://company.openai.azure.com.evil.test/','http://company.openai.azure.com/','https://secret@company.openai.azure.com/','https://company.openai.azure.com/?key=x','https://company.openai.azure.com/other'])('does not transmit to invalid endpoint %s',async endpoint=>{const fetcher=jest.fn();await expect(new AzureBackofficeAiConnector({...cfg,endpoint},fetcher).interpret('org-a','Pergunta',evidence)).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled();});
 it.each([{...cfg,enabled:false},{...cfg,organizations:[]},{...cfg,key:''},{...cfg,deployment:''}])('fails closed without configuration',async config=>{const fetcher=jest.fn();await expect(new AzureBackofficeAiConnector(config,fetcher).interpret('org-a','Pergunta',evidence)).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled();});
 it('rejects a different organization and oversized context before transmission',async()=>{const fetcher=jest.fn();const c=new AzureBackofficeAiConnector(cfg,fetcher);await expect(c.interpret('other','Pergunta',evidence)).rejects.toThrow();await expect(c.interpret('org-a','Pergunta',[{...evidence[0],source:'x'.repeat(50000)}])).rejects.toThrow('CONTEXT_LIMIT');expect(fetcher).not.toHaveBeenCalled();});
 it.each([{...output,citations:['foreign']},{...output,fields:[{...output.fields[0],value:'999'}]},{...output,fields:[{...output.fields[0],key:'tax:ICMS'}]},{...output,answer:'Economia de 999 reais'},{...output,answer:'Clique https://evil.test/'},{...output,supported:false},{...output,doubts:[{question:'Conferir?',evidenceIds:['foreign']}]}])('rejects ungrounded/unsafe output %p',v=>expect(()=>validateInterpretation(v,evidence)).toThrow());
 it('does not leak provider failures',async()=>{const fetcher=jest.fn(async()=>{throw Error('synthetic-key private content');});await expect(new AzureBackofficeAiConnector(cfg,fetcher as any).interpret('org-a','Pergunta',evidence)).rejects.toThrow('PROVIDER_UNAVAILABLE');});
});
