import {completionAnswer} from './bot-energy-completion';
describe('Evidence-based completion guidance',()=>{
 const plan=()=>({unit:'Tennis',month:'2026-08',counts:{blockers:14,reviews:3},rates:[{label:'TUSD',state:'PRESERVED',status:'DRAFT',amount:'981.92265',measure:'BRL_MWH',source:'page 1 row 6'}],taxes:[{code:'ICMS',bases:7,existing:[{status:'DRAFT',bot:false}]}],monthly:{source:'verified invoice',prepared:true,changes:[],demandSuggestion:{value:'256'},demand:[{label:'Fora ponta',meter:{decimal:'256',source:'meter row 4'},history:{decimal:'255',source:'history Aug'}}]},costs:{prepared:true,documents:[{name:'NFe.pdf'}],supplierPresent:false,suggestedInvoiceAmount:'11772.43',volumeDifferenceMwh:'-0.053020000000'}});
 it('shows prepared values, specific confirmations and navigable tasks instead of fourteen unrelated messages',()=>{const r=completionAnswer(plan());expect(r.items.find(i=>i.label.includes('Tarifas'))?.value).toContain('981.92265');expect(r.items.find(i=>i.label.includes('Tributos'))?.value).toContain('7 bases');expect(r.items.find(i=>i.label.includes('Demanda'))?.value).toContain('histórico 255');expect(r.items.find(i=>i.label.includes('Nota'))?.value).toContain('ainda não comprovado');expect(r.actions.map(a=>a.target)).toEqual(expect.arrayContaining(['review','monthly','costs','approval','reconciliation']));expect(r.answer).toContain('14 bloqueio');});
 it('does not invent a missing NF, amount, measurement or declare a zero difference resolved',()=>{const p=plan();p.monthly.demand=[];p.costs.documents=[];p.costs.suggestedInvoiceAmount=null as any;p.costs.volumeDifferenceMwh='0.000';const r=completionAnswer(p);expect(r.items.find(i=>i.label.includes('Nota'))?.value).toContain('Nenhuma NF');expect(r.actions.some(a=>a.target==='reconciliation')).toBe(false);expect(r.items.some(i=>i.value.includes('R$ null'))).toBe(false);});
 it('distinguishes validated costs from the current ICMS revision and links to the existing approval form',()=>{
  const p:any=plan();p.approvalReady=false;p.monthly.status='VALIDATED';p.monthly.record={version:6,revision:2};p.costs.status='VALIDATED';p.costs.record={version:8,revision:2};p.costs.source='Cost revision source';p.taxes[0].existing=[{status:'APPROVED',bot:true},{status:'DRAFT',bot:true}];
  const r=completionAnswer(p);expect(r.items.find(i=>i.label==='Custos mensais já validados')?.value).toContain('versão 8');expect(r.items.find(i=>i.label==='Custos mensais já validados')?.value).toContain('não é necessário validar novamente');expect(r.actions.some(a=>a.target==='parameter-records')).toBe(true);expect(r.actions.some(a=>a.target==='approval')).toBe(false);expect(r.items.find(i=>i.label.includes('Próxima decisão'))?.value).toContain('ICMS');
 });
 it('does not claim absent costs are already validated',()=>{const p:any=plan();p.costs.status=null;const r=completionAnswer(p);expect(r.items.some(i=>i.label==='Custos mensais já validados')).toBe(false);});
});
