import {cdeReviewCandidates} from './ocr-cde-review.service';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
jest.mock('./cpfl-paulista-layout',()=>({extractCpflPaulistaLayout:jest.fn()}));
function fixture(){const source={jobId:'job',doc:{id:'doc',customer_id:'customer',consumer_unit_id:'unit',reference_month:'2026-08-01',file_hash:'a'.repeat(64)},raw:{}};const row:any={source:'tables[3].row[7]',row:7,role:'CHARGE',component:'CDE_WATER_SCARCITY',period:'PEAK',fields:{description:{text:'CDE Escassez Hídrica Ponta AGO/26',pages:[1],spans:[{offset:1,length:31}],confidence:null,transcription:{state:'VERIFIED_WORDS',confidence:.299},issues:['MISSING_CONFIDENCE']},amount:{decimal:'57.19'}},issues:[]};const layout={layoutId:'cpfl-paulista-a',version:'v1',operations:[row]};(extractCpflPaulistaLayout as jest.Mock).mockReturnValue(layout);return {source,row,layout};}
describe('CDE review source binding',()=>{
 it('allows reviewing low-confidence sourced descriptions without changing OCR',()=>{const {source,row}=fixture();const before=JSON.stringify(row),c=cdeReviewCandidates('org',source)[0];expect(c.field.state).toBe('EXTRACTED_DESCRIPTION');expect(c.field.description.transcription?.confidence).toBe(.299);expect(JSON.stringify(row)).toBe(before);});
 it('binds review to tenant, job, document, month, values and layout version',()=>{for(const change of [(s:any,l:any)=>s.jobId='new-job',(s:any,l:any)=>s.doc.id='other',(s:any,l:any)=>s.doc.reference_month='2026-09-01',(s:any,l:any)=>s.doc.consumer_unit_id='other',(s:any,l:any)=>l.version='v2',(s:any,l:any)=>l.operations[0].fields.amount.decimal='57.20']){const {source,layout}=fixture(),hash=cdeReviewCandidates('org',source)[0].sourceHash;change(source,layout);expect(cdeReviewCandidates('org',source)[0].sourceHash).not.toBe(hash);}const {source}=fixture();expect(cdeReviewCandidates('org',source)[0].sourceHash).not.toBe(cdeReviewCandidates('other',source)[0].sourceHash);});
 it('blocks duplicate posts and unverifiable descriptions',()=>{const {source,row,layout}=fixture();layout.operations.push({...row,source:'other'});expect(cdeReviewCandidates('org',source).every(c=>c.field.state==='CONFLICT')).toBe(true);layout.operations=[row];row.fields.description.issues.push('UNVERIFIED_SOURCE');expect(cdeReviewCandidates('org',source)[0].field.state).toBe('CONFLICT');});
 it('does not offer other distributors, components or credits for CDE review',()=>{const {source,row,layout}=fixture();row.role='CREDIT';expect(cdeReviewCandidates('org',source)).toEqual([]);row.role='CHARGE';layout.layoutId='another';expect(cdeReviewCandidates('org',source)).toEqual([]);});
});
