import {classSuccessorId,classReviewedBasis} from './class-parameter-successor';
const p={id:'old',status:'RETIRED',kind:'TARIFF',revision:3,organization_id:'o',customer_id:'c',consumer_unit_id:'u',source:'OCR evidence',amount_text:'25.2',tax_basis:null,unit_context:{state:'SP',consumption_class:null}};
const n={...p,id:'new',status:'APPROVED',revision:2,supersedes_parameter_id:'old',unit_context:{state:'SP',consumption_class:'INDUSTRIAL'}};
describe('class completion OCR lineage',()=>{
 it('uses approved successor without changing original source',()=>{expect(classSuccessorId('old',[p,n])).toBe('new');expect(p.status).toBe('RETIRED');expect(classReviewedBasis({version:1,items:[{parameterId:'old',revision:2,operation:'EXCLUDE'}]},[p,n]).items).toEqual([{parameterId:'new',revision:2,operation:'EXCLUDE'}]);});
 it.each([{status:'DRAFT'},{amount_text:'26'},{organization_id:'foreign'},{source:'other'},{unit_context:{state:'MG',consumption_class:'INDUSTRIAL'}},{embedded_tax_codes:['ICMS']}])('rejects changed evidence %p',patch=>expect(classSuccessorId('old',[p,{...n,...patch}])).toBe('old'));
 it('rejects ambiguous successor and changes of previously specified class',()=>{expect(classSuccessorId('old',[p,n,{...n,id:'n2'}])).toBe('old');expect(classSuccessorId('old',[{...p,unit_context:{state:'SP',consumption_class:'COMMERCIAL'}},n])).toBe('old');});
 it('resolves tax only when every remapped basis preserves operation',()=>{const t={...p,id:'tax-old',kind:'TAX',tax_basis:{version:1,items:[{parameterId:'old',revision:2,operation:'EXCLUDE'}]}},next={...t,id:'tax-new',supersedes_parameter_id:'tax-old',status:'APPROVED',revision:2,unit_context:n.unit_context,tax_basis:{version:1,items:[{parameterId:'new',revision:2,operation:'EXCLUDE'}]}};expect(classSuccessorId('tax-old',[p,n,t,next])).toBe('tax-new');expect(classSuccessorId('tax-old',[p,n,t,{...next,tax_basis:{version:1,items:[{parameterId:'new',revision:2,operation:'INCLUDE'}]}}])).toBe('tax-old');});
});
