import {cpflInvoiceAdjustments} from './cpfl-invoice-adjustments';
const rows=[["REACTIVE_ENERGY","CHARGE","0.35"],["REACTIVE_ENERGY","CHARGE","45.65"],["DEMAND_BILLED","CHARGE","2512.76"],["DEMAND_BILLED","CHARGE","2330.22"],["TUSD_ENERGY","CHARGE","21211.15"],["TUSD_ENERGY","CHARGE","11172.94"],["ACL_DISTRIBUTOR_INFORMATION","CHARGE","5128.70"],["ACL_DISTRIBUTOR_INFORMATION","CHARGE","29092.21"],["CDE_WATER_SCARCITY","CHARGE","57.19"],["CDE_WATER_SCARCITY","CHARGE","501.34"],["TARIFF_SUBSIDY","CHARGE","11261.11"],["TARIFF_SUBSIDY","CHARGE","2329.22"],["SUBTOTAL","TOTAL","85642.84"],["TOTAL_DISTRIBUIDORA","TOTAL","85642.84"],["REFUND","CREDIT","-89.83"],["ACL_ENERGY_DISCOUNT","CREDIT","-5128.70"],["ACL_ENERGY_DISCOUNT","CREDIT","-29092.21"],["PUBLIC_LIGHTING","CHARGE","137.58"],["ADJUSTMENTS_SUBTOTAL","TOTAL","-34173.16"],["SUBSIDY_CREDIT","CREDIT","-10885.72"],["TOTAL_A_PAGAR","TOTAL","40583.96"],["INFORMATIVE_ADJUSTMENT","INFORMATION","-89.83"],["UNLABELLED_TOTAL_REPEAT","INFORMATION","40583.96"]];
const fixture=()=>rows.map(([component,role,decimal],index)=>({source:'row'+index,component,role,fields:{description:{text:component,issues:[]},amount:{decimal,issues:[]}},issues:[]} as any));
describe('CPFL monetary reconciliation',()=>{
 it('reconciles real operation values and excludes summaries and informational duplicates',()=>{const r=cpflInvoiceAdjustments(fixture());expect(r).toMatchObject({state:'RECONCILED',total:'40583.96',tariffs:'37831.60',cip:'137.58'});expect(r.items).toHaveLength(4);expect(r.items.map(i=>i.amount)).toEqual(['11261.11','2329.22','89.83','10885.72']);});
 it('rejects missing credit instead of silently emitting a partial total',()=>{expect(cpflInvoiceAdjustments(fixture().filter(o=>o.component!=='SUBSIDY_CREDIT')).state).toBe('REVIEW_REQUIRED');});
 it('rejects changed total',()=>{const f=fixture();f.find(o=>o.component==='TOTAL_A_PAGAR').fields.amount.decimal='40583.95';expect(cpflInvoiceAdjustments(f).state).toBe('REVIEW_REQUIRED');});
 it('rejects positive credits',()=>{const f=fixture();f.find(o=>o.component==='REFUND').fields.amount.decimal='89.83';expect(cpflInvoiceAdjustments(f).state).toBe('REVIEW_REQUIRED');});
 it('rejects duplicated operation sources',()=>{const f=fixture();f.push(f[0]);expect(cpflInvoiceAdjustments(f).state).toBe('REVIEW_REQUIRED');});
 it('rejects unsupported charges',()=>{const f=fixture();f[0].component='UNSUPPORTED';expect(cpflInvoiceAdjustments(f).state).toBe('REVIEW_REQUIRED');});
 it('rejects unverified evidence',()=>{const f=fixture();f[0].fields.amount.issues=['UNVERIFIED_SOURCE'];expect(cpflInvoiceAdjustments(f).state).toBe('REVIEW_REQUIRED');});
 it('rejects multiple totals',()=>{const f=fixture();f.push({...f.find(o=>o.component==='TOTAL_A_PAGAR'),source:'other'});expect(cpflInvoiceAdjustments(f).state).toBe('REVIEW_REQUIRED');});
});
