import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {extractGdEvidence} from './gd-evidence';
import {classifyElectricalLine,electricalField} from './electrical-evidence';
const columns=['Descrição da operação','Unid.Med.','Quant.Faturada','Tarifa ANEEL','Tarifa com tributos R$','Valor total da operação R$','Base Cálc.ICMS','Alíq.ICMS %','ICMS','PIS 1,03%','COFINS 4,83%'];
function fixture(){
 const raw:any={content:'',documents:[{fields:{VendorName:{content:'CPFL Paulista'}}}],pages:[{pageNumber:1,lines:[]}],tables:[],keyValuePairs:[{key:{content:'Classificação'},value:{content:'Tarifa Verde Livre-A4 Industrial'}}]};
 const field=(content:string,confidence?:number)=>{const offset=raw.content.length;raw.content+=content+'\n';return {content,confidence,spans:content?[{offset,length:content.length}]:[],boundingRegions:[{pageNumber:1}]};};
 const table=(rows:string[][])=>{const t={cells:rows.flatMap((row,rowIndex)=>row.map((s,columnIndex)=>({...field(s),rowIndex,columnIndex})))};raw.tables.push(t);return t;};
 const operation=(description='Tusd Enc Cons F Ponta [kWh] AGO/26')=>table([columns,[description,'kWh','1.000,0000','0,10000000','0,12345678','123,46','123,46','18','22,22','1,04','4,89']]);
 return {raw,field,table,operation};
}
describe('CPFL Paulista layout library',()=>{
 it.each(['Energia ACL Fora de Ponta','Tusd Enc Cons F Ponta','TUSD Fora Ponta'])('keeps off-peak alias %s off-peak',s=>expect(classifyElectricalLine(s).period).toBe('OFF_PEAK'));
 it('does not assign a combined peak/off-peak label',()=>expect(classifyElectricalLine('TUSD F Ponta e Ponta').period).toBe('UNSPECIFIED'));
 it('does not invent confidence for empty values',()=>{const {raw,field}=fixture();expect(electricalField(raw,field('',.999)).confidence).toBeNull();});
 it('maps all eleven independent columns and exact tariff precision',()=>{const {raw,operation}=fixture();operation();const r=extractCpflPaulistaLayout(raw);expect(r.operations).toHaveLength(1);expect(r.operations[0]).toMatchObject({component:'TUSD_ENERGY',period:'OFF_PEAK',arithmetic:{state:'MATCH_WITHIN_ONE_CENT'}});expect(r.operations[0].fields.aneelRate.decimal).toBe('0.10000000');expect(r.operations[0].fields.grossRate.decimal).toBe('0.12345678');expect(r.operations[0].fields.icmsBase.decimal).toBe('123.46');expect(r.operations[0].fields.pisAmount.decimal).toBe('1.04');expect(r.operations[0].fields.cofinsAmount.decimal).toBe('4.89');expect(r.coverage[2].mapped).toBe(11);expect(r.canImport).toBe(false);});
 it('does not combine generic Items with operation rows',()=>{const {raw,operation}=fixture();operation();raw.documents[0].fields.Items={valueArray:[{valueObject:{Description:{content:'duplicated'}}}]};expect(extractCpflPaulistaLayout(raw).operations).toHaveLength(1);});
 it('flags quantity-times-tariff disagreement',()=>{const {raw,operation}=fixture();const t=operation();t.cells.find(c=>c.rowIndex===1&&c.columnIndex===5)!.content='150,00';expect(extractCpflPaulistaLayout(raw).operations[0].arithmetic).toEqual({state:'DIVERGENT',differenceCents:'-2654'});});
 it('does not treat source mismatch as approved',()=>{const {raw,operation}=fixture();const t=operation();t.cells.find(c=>c.rowIndex===1&&c.columnIndex===5)!.content='999,00';expect(extractCpflPaulistaLayout(raw).operations[0].fields.amount.issues).toContain('UNVERIFIED_SOURCE');});
 it.each([['CPFL Piratininga'],['CPFL Santa Cruz'],['Cemig'],['CPFL']])('does not apply Paulista mapping to issuer %s',issuer=>{const {raw,operation}=fixture();operation();raw.documents[0].fields.VendorName.content=issuer;expect(extractCpflPaulistaLayout(raw)).toMatchObject({layoutId:null,operations:[],canImport:false});});
 it('requires one invoice',()=>{const {raw,operation}=fixture();operation();raw.documents.push(raw.documents[0]);expect(extractCpflPaulistaLayout(raw).issues).toContain('INVOICE_COUNT_NOT_ONE');});
 it('rejects duplicated tariff headers',()=>{const {raw,operation}=fixture();const t=operation();t.cells.find(c=>c.rowIndex===0&&c.columnIndex===3)!.content='Tarifa com tributos R$';expect(extractCpflPaulistaLayout(raw).operations).toHaveLength(0);});
 it('flags merged cells rather than borrowing a neighbour',()=>{const {raw,operation}=fixture();const t=operation();Object.assign(t.cells.find(c=>c.rowIndex===1&&c.columnIndex===5)!,{columnSpan:2});const r=extractCpflPaulistaLayout(raw).operations[0];expect(r.issues).toContain('MERGED_OR_DUPLICATE_CELL');expect(r.fields.amount).toBeUndefined();});
 it('keeps unknown components for review',()=>{const {raw,operation}=fixture();operation('Serviço novo');expect(extractCpflPaulistaLayout(raw).operations[0]).toMatchObject({component:'OTHER',role:'UNKNOWN'});});
 it.each([['USD Consumo Reativo Fora Ponta','REACTIVE_ENERGY','CHARGE'],['CDE Escassez Hídrica F Ponta','CDE_WATER_SCARCITY','CHARGE'],['Subvenção Tarifaria - TUSD - Com ICMS','TARIFF_SUBSIDY','CHARGE'],['Desc Energia ACL Fora Ponta','ACL_ENERGY_DISCOUNT','CREDIT'],['Devol. TUSD Mês MAI/26','REFUND','CREDIT'],['Crédito Subvenção Tarifaria - TUSD','SUBSIDY_CREDIT','CREDIT'],['Contribuição Custeio IP-CIP','PUBLIC_LIGHTING','CHARGE'],['Energia ACL Ponta','ACL_DISTRIBUTOR_INFORMATION','CHARGE'],['Ajuste Subvenção','INFORMATIVE_ADJUSTMENT','INFORMATION'],['Subtotal','SUBTOTAL','TOTAL'],['Total a Pagar','TOTAL_A_PAGAR','TOTAL']])('classifies %s without aggregating it',(description,component,role)=>{const {raw,operation}=fixture();operation(description);expect(extractCpflPaulistaLayout(raw).operations[0]).toMatchObject({component,role});});
 it('does not infer measured/unused demand from repeated descriptions',()=>{const {raw,table}=fixture();table([columns,['Uso Sist. Distr.49,99 Desc','kW','200','16,53','10,00','2.000,00'],['Uso Sist. Distr.49,99 Desc','kW','300','16,53','8,00','2.400,00']]);const r=extractCpflPaulistaLayout(raw);expect(r.operations.map(o=>o.component)).toEqual(['DEMAND_BILLED','DEMAND_BILLED']);expect(r.operations.every(o=>o.issues.includes('DEMAND_MEASURED_UNUSED_SPLIT_REQUIRES_CONTEXT'))).toBe(true);});
 it('maps month and due date from their own columns',()=>{const {raw,table}=fixture();table([['Ref: mês/ano','Vencimento','Total a pagar'],['AGO/2026','15/09/2026','R$ 10,00']]);const r=extractCpflPaulistaLayout(raw);expect(r.fields.find(f=>f.name==='reference')?.value.text).toBe('AGO/2026');expect(r.fields.find(f=>f.name==='dueDate')?.value.text).toBe('15/09/2026');});
 it('preserves conflicting candidates and does not choose by expected customer',()=>{const {raw,field,table}=fixture();raw.documents[0].fields.DueDate=field('16/09/2026',.99);table([['Vencimento'],['15/09/2026']]);expect(extractCpflPaulistaLayout(raw).issues).toContain('CONFLICTING_DUEDATE');});
 it('does not infer invoice number from operation reference',()=>{const {raw,operation}=fixture();const t=operation();t.cells[0].content='Descrição da operação Nº 12345678';expect(extractCpflPaulistaLayout(raw).fields.some(f=>f.name==='invoiceNumber')).toBe(false);});
 it('keeps history and GD headers out of current operations',()=>{const {raw,table}=fixture();table([['Consumo Ponta kWh','Consumo Fora Ponta kWh'],['AGO26 100,00','AGO26 900,00']]);table([['Bandeiras Tarifárias','Micro e Mini Geração'],['Amarela 31 Dias','']]);const r=extractCpflPaulistaLayout(raw);expect(r.blocks.map(b=>b.kind)).toEqual(['HISTORY','FLAGS_GD']);expect(r.operations).toHaveLength(0);});
 it('does not extract campaign and bank-slip tables as energy operations',()=>{const {raw,table}=fixture();table([['Campanha','Valor'],['Promoção','100']]);table([['Beneficiário','Nosso Número'],['Banco','123']]);expect(extractCpflPaulistaLayout(raw).blocks).toHaveLength(0);expect(extractCpflPaulistaLayout(raw).operations).toHaveLength(0);});
 it('reports new layouts as planned, never homologated',()=>{const r=extractCpflPaulistaLayout(fixture().raw);expect(r.library.filter(l=>!['cpfl-paulista-a','neoenergia-elektro-verde'].includes(l.id)).every(l=>l.status==='PLANNED')).toBe(true);expect(r.library.find(l=>l.id==='neoenergia-elektro-verde')?.status).toBe('IN_HOMOLOGATION');expect(r.status).toBe('IN_HOMOLOGATION');expect(r.library.find(l=>l.id==='cpfl-paulista-a')?.status).toBe('SAMPLE_VALIDATED');expect(r.canImport).toBe(false);});
});

it('does not apply the A layout to group B',()=>{const {raw,operation}=fixture();operation();raw.keyValuePairs[0].value.content='B3 Comercial';expect(extractCpflPaulistaLayout(raw)).toMatchObject({layoutId:null,operations:[],issues:['TARIFF_GROUP_NOT_IDENTIFIED_AS_A']});});
it('numeric value attached to a GD header does not prove GD',()=>{const {raw,field}=fixture();raw.keyValuePairs.push({key:field('Micro e Mini Geração'),value:field('202,00'),confidence:.99});expect(extractGdEvidence(raw)).toMatchObject({detected:false,records:[],issues:['GD_PARTICIPATION_VALUE_AMBIGUOUS']});});

it('does not interpret meter counter as a reading date or bank label as due date',()=>{const {raw,table}=fixture();table([['Medidor','Leitura Atual','Leitura Anterior'],['999','088082','084831']]);table([['Vencimento','15/09/2026'],['Agência/Código do Beneficiário','123']]);expect(extractCpflPaulistaLayout(raw).fields.filter(f=>['currentReading','previousReading','dueDate'].includes(f.name))).toHaveLength(0);});
it('keeps bank reference separate from explicit fiscal number',()=>{const {raw,field}=fixture();raw.documents[0].fields.InvoiceId=field('90000001',.99);raw.keyValuePairs.push({key:field('NOTA FISCAL Nº'),value:field('70000002'),confidence:.98});const r=extractCpflPaulistaLayout(raw);expect(r.fields.find(f=>f.name==='invoiceNumber')?.value.text).toBe('70000002');expect(r.fields.find(f=>f.name==='documentReference')?.value.text).toBe('90000001');});
it('parses CPFL trailing minus without changing source text',()=>{const {raw,table}=fixture();table([columns,['Devol. TUSD Mês MAI/26','','','','','10,00-']]);const f=extractCpflPaulistaLayout(raw).operations[0].fields.amount;expect(f.text).toBe('10,00-');expect(f.decimal).toBe('-10.00');expect(f.issues).not.toContain('INVALID_DECIMAL');});
it('does not add a subtotal of adjustments twice',()=>{const {raw,table}=fixture();const row=(d:string,a:string)=>[d,'','','','',a];table([columns,row('TUSD Fora Ponta','100,00'),row('Subtotal','100,00'),row('Total Distribuidora','100,00'),row('Devol. TUSD','10,00-'),row('Desc Energia ACL Ponta','20,00-'),row('Contribuição Custeio IP-CIP','5,00'),row('Devolução','25,00-'),row('Crédito Subvenção Tarifaria - TUSD','5,00-'),row('Total a Pagar','70,00'),row('Ajuste Subvenção','10,00-')]);const r=extractCpflPaulistaLayout(raw);expect(r.reconciliation.state).toBe('MATCH');expect(r.reconciliation.checks).toHaveLength(4);expect(r.canImport).toBe(false);});
it('fails reconciliation on a mismatching total instead of changing it',()=>{const {raw,table}=fixture();const row=(d:string,a:string)=>[d,'','','','',a];table([columns,row('TUSD Ponta','100,00'),row('Subtotal','100,00'),row('Total Distribuidora','100,00'),row('Devol. TUSD','10,00-'),row('Devolução','10,00-'),row('Total a Pagar','95,00')]);expect(extractCpflPaulistaLayout(raw).reconciliation.state).toBe('DIVERGENT');});
it('does not choose a distributor CNPJ as the customer CNPJ',()=>{const {raw,field}=fixture();const pair=(k:string,v:string)=>({key:field(k),value:field(v),confidence:.99});raw.keyValuePairs.push(pair('CNPJ','11.111.111/0001-11'),pair('Número da UC','123'),pair('CNPJ','22.222.222/0001-22'),pair('NOTA FISCAL Nº','900'),pair('CNPJ','33.333.333/0001-33'));const r=extractCpflPaulistaLayout(raw);expect(r.fields.filter(f=>f.name==='customerTaxId').map(f=>f.value.text)).toEqual(['22.222.222/0001-22']);});

describe('CPFL printed tax summary integration',()=>{it('projects an exact check from operation and summary tables',()=>{const {raw,operation,table}=fixture();operation();table([['Tributo','Base de Cálc. (R$)','Alíquota (%)','Valor (R$)'],['ICMS','123,46','18,00','22,22'],['PIS/PASEP','100,97','1,03','1,04'],['COFINS','100,97','4,83','4,89']]);const result=extractCpflPaulistaLayout(raw);expect(result.taxReconciliation.checks.map(c=>c.state)).toEqual(['MATCH_EXTRACTED','MATCH_EXTRACTED','MATCH_EXTRACTED']);expect(result.canImport).toBe(false);});});

it('recognizes classification from a page line when Azure omitted key-value classification',()=>{const {raw,field,operation}=fixture();raw.keyValuePairs=[];const line=field('Classificação: Tarifa Verde Livre-A4 Comercial Atacadista / Varejista');delete (line as any).boundingRegions;raw.pages[0].lines.push(line);operation();const r=extractCpflPaulistaLayout(raw);expect(r.layoutId).toBe('cpfl-paulista-a');expect(r.operations).toHaveLength(1);const f=r.fields.find(f=>f.name==='classification')!;expect(f.value.pages).toEqual([1]);expect(f.value.issues).not.toContain('UNVERIFIED_SOURCE');expect(f.value.confidence).toBeNull();});
it('does not use a later-page classification to recognize CPFL group A',()=>{const {raw,field}=fixture();raw.keyValuePairs=[];raw.pages.push({pageNumber:2,lines:[field('Classificação: Tarifa Verde Livre-A4')]});expect(extractCpflPaulistaLayout(raw).layoutId).toBeNull();});
it('does not use incidental group A text as classification',()=>{const {raw,field}=fixture();raw.keyValuePairs=[];raw.pages[0].lines.push(field('Campanha A4 para clientes'));expect(extractCpflPaulistaLayout(raw).layoutId).toBeNull();});

it('extracts fiscal identifiers and address only inside the anchored UC block',()=>{const {raw,field}=fixture();const add=(s:string)=>raw.pages[0].lines.push(field(s));add('CNPJ: 11.111.111/0001-11');add('Número da UC');add('CLIENTE TESTE');add('RDV TESTE, 100');add('Próxima Leitura 30/09/2026');add('BAIRRO TESTE - SP');add('14000-000');add('INSC.EST: 123 / CNPJ: 22.222.222/0001-22');add('NOTA FISCAL Nº 012345678 - SÉRIE 0 / DATA DE EMISSÃO:');const r=extractCpflPaulistaLayout(raw);expect(r.fields.find(f=>f.name==='invoiceNumber')?.value.text).toBe('012345678');const series=r.fields.find(f=>f.name==='series')!;expect(series.value.text).toBe('0');expect(series.value.spans[0].offset).toBe(raw.content.indexOf('SÉRIE 0')+6);expect(r.fields.filter(f=>f.name==='customerTaxId').map(f=>f.value.text)).toEqual(['22.222.222/0001-22']);expect(r.fields.find(f=>f.name==='serviceAddress')?.value.issues).not.toContain('UNVERIFIED_SOURCE');expect(r.fields.find(f=>f.name==='serviceAddress')?.value.text).not.toContain('Leitura');});
it('does not extract fiscal/customer line fallbacks without the UC anchor',()=>{const {raw,field}=fixture();raw.pages[0].lines.push(field('CNPJ: 11.111.111/0001-11'),field('NOTA FISCAL Nº 012345678 - SÉRIE 0'));expect(extractCpflPaulistaLayout(raw).fields.filter(f=>['invoiceNumber','series','customerTaxId'].includes(f.name))).toHaveLength(0);});
