import {classifyElectricalLine,decimalFromInvoice,extractElectricalEvidence} from './electrical-evidence';
function fixture(lines:Record<string,string>[]){
 const raw:any={content:'',documents:[{fields:{Items:{valueArray:[]}}}],pages:[{pageNumber:1}]};
 const field=(content:string)=>{const offset=raw.content.length;raw.content+=content+'\n';return {content,confidence:0.99,spans:[{offset,length:content.length}],boundingRegions:[{pageNumber:1}]};};
 for(const line of lines){const valueObject=Object.fromEntries(Object.entries(line).map(([key,value])=>[key,field(value)]));raw.documents[0].fields.Items.valueArray.push({valueObject});}
 return {raw,field};
}
const energy={Description:'Energia TE Fora Ponta',Quantity:'1.000,50',Unit:'kWh',UnitPrice:'0,123456789',Amount:'123,52'};
describe('electricity evidence',()=>{
 it.each([['1.234,56','1234.56'],['0,123456789','0.123456789'],['R$ 10,00','10.00'],['-12,50','-12.50'],['0001','1'],['1.000','1000'],['0','0']])('parses pt-BR text %s without floats',(input,expected)=>expect(decimalFromInvoice(input)).toBe(expected));
 it.each(['1,234.56','1.23','1e3','10%','1,1234567890','abc','1 000,00','1.00,50','','999999999999999999999999999999'])('rejects malformed or unsupported decimal %s',input=>expect(decimalFromInvoice(input)).toBeNull());
 it.each([
 ['Energia TE Ponta','TE','PEAK'],['Energia TE Fora Ponta','TE','OFF_PEAK'],['TUSD Fora Ponta','TUSD_ENERGY','OFF_PEAK'],['TE + TUSD Ponta','OTHER','PEAK'],
 ['Demanda contratada ponta','DEMAND_CONTRACTED','PEAK'],['Demanda registrada fora ponta','DEMAND_MEASURED','OFF_PEAK'],['Demanda não utilizada','DEMAND_UNUSED','UNSPECIFIED'],['Ultrapassagem de demanda','DEMAND_EXCESS','UNSPECIFIED'],['Demanda contratada e registrada','OTHER','UNSPECIFIED'],['TUSD Demanda','DEMAND_BILLED','UNSPECIFIED'],['Energia reativa excedente','REACTIVE_ENERGY','UNSPECIFIED'],['Multa por atraso','PENALTY','UNSPECIFIED'],['Juros','INTEREST','UNSPECIFIED'],['ICMS','ICMS','UNSPECIFIED'],['PIS COFINS','OTHER','UNSPECIFIED'],['PIS','PIS','UNSPECIFIED'],['Consumo energia','OTHER','UNSPECIFIED'],['TUSD fora ponta e ponta','TUSD_ENERGY','UNSPECIFIED']
 ])('classifies only explicit candidate %s',(description,component,period)=>expect(classifyElectricalLine(description)).toEqual({component,period}));
 it('keeps TE and TUSD as distinct rows without summing consumption',()=>{const {raw}=fixture([energy,{...energy,Description:'TUSD Fora Ponta'}]);const result=extractElectricalEvidence(raw);expect(result.rows).toHaveLength(2);expect(result.rows.map(r=>r.quantity.decimal)).toEqual(['1000.50','1000.50']);expect(result).not.toHaveProperty('totalConsumption');expect(result.canImport).toBe(false);});
 it('preserves all tariff decimal places and original source',()=>{const {raw}=fixture([energy]);const result=extractElectricalEvidence(raw);expect(result.rows[0].unitPrice).toMatchObject({text:'0,123456789',decimal:'0.123456789',pages:[1],confidence:0.99,issues:[]});});
 it('never replaces absent source text with provider float',()=>{const {raw}=fixture([energy]);raw.documents[0].fields.Items.valueArray[0].valueObject.Quantity={valueNumber:1000,confidence:0.99};const f=extractElectricalEvidence(raw).rows[0].quantity;expect(f.decimal).toBeNull();expect(f.issues).toContain('MISSING_VALUE');});
 it('checks that spans actually contain the extracted value',()=>{const {raw}=fixture([energy]);raw.documents[0].fields.Items.valueArray[0].valueObject.Amount.spans=[{offset:0,length:6}];expect(extractElectricalEvidence(raw).rows[0].amount.issues).toContain('UNVERIFIED_SOURCE');});
 it('does not invent missing confidence',()=>{const {raw}=fixture([energy]);delete raw.documents[0].fields.Items.valueArray[0].valueObject.Unit.confidence;expect(extractElectricalEvidence(raw).rows[0].confidence).toBeNull();});
 it.each([[0.44,'CONFIDENCE_BELOW_45'],[0.45,'CONFIDENCE_REQUIRES_REVIEW'],[0.85,'CONFIDENCE_REQUIRES_REVIEW']])('applies master confidence threshold %s',(confidence,issue)=>{const {raw}=fixture([energy]);raw.documents[0].fields.Items.valueArray[0].valueObject.Quantity.confidence=confidence;expect(extractElectricalEvidence(raw).rows[0].quantity.issues).toContain(issue);});
 it('keeps repeated descriptions and flags negative credits',()=>{const {raw}=fixture([energy,{...energy,Amount:'-10,00'}]);const result=extractElectricalEvidence(raw);expect(result.rows).toHaveLength(2);expect(result.rows[1].issues).toContain('CREDIT_REQUIRES_REVIEW');});
 it('flags incompatible units without converting them',()=>{const {raw}=fixture([{...energy,Unit:'kW'}]);expect(extractElectricalEvidence(raw).rows[0].issues).toContain('ENERGY_UNIT_UNVERIFIED');});
 it('flags explicit foreign currency',()=>{const {raw}=fixture([energy]);raw.documents[0].fields.Items.valueArray[0].valueObject.Amount.valueCurrency={currencyCode:'USD',amount:123};expect(extractElectricalEvidence(raw).rows[0].amount.issues).toContain('NON_BRL_CURRENCY');});
 it('does not merge multiple invoices',()=>{const {raw}=fixture([energy]);raw.documents.push(raw.documents[0]);expect(extractElectricalEvidence(raw)).toMatchObject({rows:[],canImport:false,issues:['INVOICE_COUNT_NOT_ONE']});});
 it('preserves unmapped line items',()=>{const {raw}=fixture([{...energy,Description:'Serviço não identificado'}]);expect(extractElectricalEvidence(raw).rows[0].component).toBe('OTHER');});
 it('does not guess tax identity or inclusion in tariff',()=>{const {raw,field}=fixture([energy]);raw.documents[0].fields.TaxDetails={valueArray:[{valueObject:{Amount:field('18,00'),Rate:field('18%')}}]};expect(extractElectricalEvidence(raw).taxDetails[0]).toMatchObject({tax:'UNIDENTIFIED',basis:'UNVERIFIED',amount:{decimal:'18.00'},rate:{text:'18%'}});});
 it('uses explicit table headers only when Items are absent, without invented confidence',()=>{const {raw,field}=fixture([]);const headers=['Descrição','Quantidade','Unidade','Tarifa','Valor'];const values=Object.values(energy);raw.tables=[{cells:[...headers.map((h,columnIndex)=>({...field(h),rowIndex:0,columnIndex})),...values.map((v,columnIndex)=>({...field(v),rowIndex:1,columnIndex}))]}];const result=extractElectricalEvidence(raw);expect(result.rows[0]).toMatchObject({component:'TE',source:'tables[0].row[1]',confidence:null});expect(result.rows[0].amount.issues).toContain('MISSING_CONFIDENCE');});
 it('does not double count raw tables alongside Items',()=>{const {raw}=fixture([energy]);raw.tables=[{cells:[]}];const result=extractElectricalEvidence(raw);expect(result.rows).toHaveLength(1);expect(result.issues).toContain('TABLES_REQUIRE_COVERAGE_REVIEW');});
 it('rejects ambiguous duplicate amount columns',()=>{const {raw,field}=fixture([]);raw.tables=[{cells:['Descrição','Valor','Total'].map((h,columnIndex)=>({...field(h),rowIndex:0,columnIndex}))}];expect(extractElectricalEvidence(raw).issues).toContain('UNMAPPED_TABLE');});
 it('makes truncation explicit and never allows import',()=>{const {raw}=fixture(Array.from({length:501},()=>energy));const result=extractElectricalEvidence(raw);expect(result.rows).toHaveLength(500);expect(result.issues).toContain('ITEM_LIMIT_REACHED');expect(result.canImport).toBe(false);});
});
