import {extractGdEvidence,gdKind} from './gd-evidence';
import {classifyElectricalLine} from './electrical-evidence';
function fixture(){const raw:any={content:'',documents:[{fields:{}}],pages:[{pageNumber:1}],keyValuePairs:[]};const field=(content:string)=>{const offset=raw.content.length;raw.content+=content+'\n';return {content,confidence:0.99,spans:[{offset,length:content.length}],boundingRegions:[{pageNumber:1}]};};const pair=(key:string,value:string,confidence=0.99)=>raw.keyValuePairs.push({key:field(key),value:field(value),confidence});return {raw,field,pair};}
describe('GD evidence without financial inference',()=>{
 it.each([['Energia injetada (kWh)','INJECTED'],['Energia compensada','COMPENSATED'],['Saldo anterior de créditos','CREDIT_OPENING'],['Saldo atual de créditos (MWh)','CREDIT_CLOSING'],['Créditos recebidos','CREDIT_RECEIVED'],['Créditos utilizados','CREDIT_USED'],['Créditos expirados','CREDIT_EXPIRED'],['Rateio GD (%)','ALLOCATION_PERCENT']])('maps explicit %s',(s,k)=>expect(gdKind(s)).toBe(k));
 it.each(['Crédito Subvenção Tarifária - TUSD','Crédito tributário','Saldo a pagar','Ficha de compensação','Consumo Fora Ponta','Desconto TE'])('does not invent GD from %s',s=>expect(gdKind(s)).toBeNull());
 it('preserves decimal energy and source without calculating savings',()=>{const f=fixture();f.pair('Energia compensada (kWh)','1.234,56789');const r=extractGdEvidence(f.raw);expect(r.records[0]).toMatchObject({kind:'COMPENSATED',unit:'KWH',value:{decimal:'1234.56789',pages:[1],confidence:0.99}});expect(r.canImport).toBe(false);expect(r).not.toHaveProperty('savings');});
 it('accepts explicit value units and percent without changing original text',()=>{const f=fixture();f.pair('Energia injetada','100,50 kWh');f.pair('Rateio GD','25,00%');const r=extractGdEvidence(f.raw);expect(r.records.map(x=>[x.value.text,x.value.decimal,x.unit])).toEqual([['100,50 kWh','100.50','KWH'],['25,00%','25.00','%']]);});
 it('requires units instead of assuming kWh',()=>{const f=fixture();f.pair('Energia injetada','100');expect(extractGdEvidence(f.raw).records[0].issues).toContain('GD_UNIT_UNVERIFIED');});
 it('flags incompatible or contradictory units',()=>{const f=fixture();f.pair('Energia injetada (kWh)','1 MWh');expect(extractGdEvidence(f.raw).records[0].unit).toBeNull();});
 it.each([0.44,0.45,0.85])('retains confidence %s without auto approval',c=>{const f=fixture();f.pair('Energia injetada (kWh)','100',c);const r=extractGdEvidence(f.raw);expect(r.records[0].issues).toContain(c<0.45?'CONFIDENCE_BELOW_45':'CONFIDENCE_REQUIRES_REVIEW');expect(r.canImport).toBe(false);});
 it('rejects invented source spans',()=>{const f=fixture();f.pair('Energia injetada (kWh)','100');f.raw.keyValuePairs[0].value.spans=[{offset:0,length:3}];expect(extractGdEvidence(f.raw).records[0].issues).toContain('UNVERIFIED_SOURCE');});
 it('keeps balances in tables alongside Items, with unknown confidence',()=>{const f=fixture();f.raw.documents[0].fields.Items={valueArray:[{valueObject:{Description:f.field('Energia compensada'),Quantity:f.field('10'),Unit:f.field('kWh')}}]};f.raw.tables=[{cells:[{...f.field('Saldo atual de créditos (kWh)'),rowIndex:0,columnIndex:0},{...f.field('20'),rowIndex:0,columnIndex:1}]}];const r=extractGdEvidence(f.raw);expect(r.records).toHaveLength(2);expect(r.records[1].value.confidence).toBeNull();});
 it('does not sum repeated balances or TE/TUSD credit quantities',()=>{const f=fixture();f.pair('Energia compensada (kWh)','10');f.pair('Energia compensada (kWh)','10');const r=extractGdEvidence(f.raw);expect(r.records).toHaveLength(2);expect(r.issues).toContain('GD_MULTIPLE_CANDIDATES_NO_SUM');expect(r).not.toHaveProperty('total');});
 it('does not treat energy credit or subsidy as billed TE/TUSD',()=>{for(const s of ['Energia compensada TE','Energia injetada TUSD','Crédito TUSD','Subvenção tarifária TUSD','Desc Energia ACL TE'])expect(classifyElectricalLine(s).component).toBe('OTHER');});
 it('does not treat a negative profile declaration or blank field as participation',()=>{const f=fixture();f.pair('Micro e Mini Geração','Não');expect(extractGdEvidence(f.raw).detected).toBe(false);});
 it('flags rateio beyond 100 and negative balance',()=>{const f=fixture();f.pair('Rateio GD (%)','101');f.pair('Saldo atual de créditos (kWh)','-10');const r=extractGdEvidence(f.raw);expect(r.records[0].issues).toContain('GD_PERCENT_OUT_OF_RANGE');expect(r.records[1].issues).toContain('GD_SIGN_REVIEW');});
 it('does not merge invoices',()=>{const f=fixture();f.raw.documents.push({fields:{}});expect(extractGdEvidence(f.raw).records).toEqual([]);});
 it('reports truncated inputs explicitly',()=>{const f=fixture();for(let i=0;i<501;i++)f.pair('Energia injetada (kWh)','1');expect(extractGdEvidence(f.raw).issues).toContain('GD_LIMIT_REACHED');});
});
