import {captureInvoiceAssessment} from './invoice-assessment';
function setup(){const data:any={documents:{id:'doc',organization_id:'org',customer_id:'customer',consumer_unit_id:'unit',reference_month:'2026-08-01',file_hash:'hash',document_type:'INVOICE_DISTRIBUTOR',file_verified:true},customers:{company_name:'Customer',document:'12345678000195'},consumer_units:{consumer_unit_number:'001',address:'Rua A',free_market:true}};const queries:any[]=[];const db={from:(table:string)=>{const q:any={table};for(const op of ['select','eq','is','neq'])q[op]=jest.fn(()=>q);q.maybeSingle=jest.fn(async()=>({data:data[table],error:null}));q.limit=jest.fn(async()=>({data:[],error:null}));queries.push(q);return q;}};return {data,queries,db};}
const job={organization_id:'org',document_id:'doc',file_hash:'hash'};
describe('snapshot capture',()=>{
 it('records scoped source and registration with no financial approval',async()=>{const s=setup();const result=await captureInvoiceAssessment(s.db,job,{});expect(result.registration.customer).toEqual(s.data.customers);expect(result.source.fileHash).toBe('hash');expect(result.intake.canImport).toBe(false);for(const q of s.queries)expect(q.eq).toHaveBeenCalledWith('organization_id','org');expect(s.queries.find(q=>q.table==='consumer_units').eq).toHaveBeenCalledWith('customer_id','customer');});
 it('rejects absent linked customer without inventing identity',async()=>{const s=setup();s.data.customers=null;const r=await captureInvoiceAssessment(s.db,job,{});expect(r.intake.decision).toBe('REJECT_AUTOMATION');expect(r.intake.checks.find(c=>c.field==='registration')?.state).toBe('MISMATCH');});
 it('rejects absent linked unit',async()=>{const s=setup();s.data.consumer_units=null;expect((await captureInvoiceAssessment(s.db,job,{})).intake.decision).toBe('REJECT_AUTOMATION');});
 it('does not assess changed bytes',async()=>{const s=setup();s.data.documents.file_hash='new';await expect(captureInvoiceAssessment(s.db,job,{})).rejects.toThrow('OCR_SOURCE_ASSESSMENT_PENDING');});
});
