import {invoiceReadout,ocrReadoutSummary} from './invoice-readout';
const field=(content:string,confidence?:number,page=1)=>({content,confidence,boundingRegions:[{pageNumber:page}],spans:[{offset:0,length:content.length}]});
function fixture(){return {content:'Energia 100 kWh\nCampanha de doação\nCentral de atendimento\nTarifa 0,50',pages:[{pageNumber:1,lines:[{content:'Energia 100 kWh'},{content:'Campanha de doação'}]},{pageNumber:2,lines:[{content:'Tarifa 0,50'},{content:'Central de atendimento'}]}],documents:[{fields:{InvoiceTotal:field('100',.99),VendorPhoneNumber:field('0800',.99),Items:{valueArray:[{valueObject:{Description:field('Energia TE',.9),Amount:field('100',.8)}}]}}}],keyValuePairs:[{key:field('Consumo',.9),value:field('100 kWh',.9),confidence:.9},{key:field('Central de atendimento'),value:field('0800'),confidence:.99}],tables:[{boundingRegions:[{pageNumber:2}],cells:[{rowIndex:0,columnIndex:0,content:'Tarifa'},{rowIndex:1,columnIndex:0,content:'0,50'}]},{cells:[{rowIndex:0,columnIndex:0,content:'Notícias'}]}]};}
describe('technical invoice readout',()=>{
 it('keeps technical nested values and suppresses contact fields',()=>{const r=invoiceReadout(fixture(),{page:1,section:'fields',offset:0});expect(r.rows.map(x=>x.text)).toEqual(['100','Energia TE','100']);expect(r.rows[2].confidence).toBe(.8);});
 it('selects technical labels without customer service content',()=>{const r=invoiceReadout(fixture(),{page:1,section:'pairs',offset:0});expect(r.rows).toHaveLength(1);expect(r.rows[0].key.text).toBe('Consumo');});
 it('preserves table coordinates and numeric rows on subsequent pages',()=>{const r=invoiceReadout(fixture(),{page:2,section:'tables',offset:0});expect(r.rows).toHaveLength(2);expect(r.rows[1].cells[0]).toMatchObject({text:'0,50',column:0,confidence:null,sourceVerified:false});});
 it('does not include campaign or support lines in technical excerpts',()=>{expect(invoiceReadout(fixture(),{page:0,section:'text',offset:0}).text).toBe('Energia 100 kWh\nTarifa 0,50');});
 it('keeps numeric continuations while stopping at campaign content',()=>{const raw={content:'Tarifa\n0,50\nCampanha\n1000',pages:[]};expect(invoiceReadout(raw,{page:0,section:'text',offset:0}).text).toBe('Tarifa\n0,50');});
 it('never interprets missing confidence as zero or high',()=>{const r=ocrReadoutSummary(fixture(),[{field:'customer',confidence:.99,state:'MATCH'}]);expect(r.criticalConfidence).toMatchObject({known:1,missing:5,complete:false,minimumAll:null,matched:1});expect(r.automaticApproval).toBe(false);});
 it('retains exact boundary classification',()=>{const raw={documents:[{fields:Object.fromEntries([.449,.45,.85,.851,NaN,2].map((c,i)=>['InvoiceTotal'+i,{...field('Energia',c)}]))}]};expect(ocrReadoutSummary(raw).fieldConfidence).toMatchObject({low:1,review:2,high:1,missing:2});});
 it('requires valid page and matching text span before declaring source located',()=>{const raw={content:'Energia',pages:[{pageNumber:1}],documents:[{fields:{InvoiceTotal:field('Energia',.9)}}]};expect(invoiceReadout(raw,{page:1,section:'fields',offset:0}).rows[0].sourceVerified).toBe(true);raw.content='Outroxx';expect(invoiceReadout(raw,{page:1,section:'fields',offset:0}).rows[0].sourceVerified).toBe(false);expect(()=>invoiceReadout(raw,{page:2,section:'fields',offset:0})).toThrow('PAGE_NOT_FOUND');});
 it('paginates technical rows without dropping duplicates',()=>{const raw=fixture();raw.keyValuePairs=Array.from({length:60},()=>raw.keyValuePairs[0]);const pages=[0,25,50].map(offset=>invoiceReadout(raw,{page:1,section:'pairs',offset}));expect(pages.flatMap(p=>p.rows)).toHaveLength(60);expect(pages[2].nextOffset).toBeNull();expect(pages[1].previousOffset).toBe(0);});
 it('does not expose provider URLs or opaque metadata',()=>{const raw={...fixture(),operationUrl:'secret',apiKey:'secret'};expect(JSON.stringify(invoiceReadout(raw,{page:1,section:'fields',offset:0}))).not.toContain('secret');});
});
