import {OcrCalculationContextService} from './ocr-calculation-context.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
function setup(){const source={doc:{consumer_unit_id:'unit',customer_id:'customer',reference_month:'2026-08-01'}};
 const queue={reviewSource:jest.fn(async()=>source)},record={status:'DRAFT_PENDING',draftCount:1,validatedCount:0,validatedVersion:null};
 const result={unit:{id:'unit',customerId:'customer',name:'Del Rei'},month:'2026-08',checkedAt:'now',counts:{blockers:3,reviews:1,approvedParameters:2,draftParameters:1},findings:[{code:'COSTS_DRAFT',section:'Custos mensais',severity:'BLOCKER',message:'Validar custos'}],measurements:record,costs:{...record}};
 const preparation={inspect:jest.fn(async()=>result)},service=new OcrCalculationContextService(queue as any,preparation as any);
 const tenant:any={userId:'actor',organizationId:'org',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW]};return {service,queue,preparation,tenant,result,source};}
describe('OCR calculation context',()=>{
 it('derives unit/month from the scoped document and reuses preparation rules',async()=>{const s=setup(),r=await s.service.inspect('doc',s.tenant);expect(s.queue.reviewSource).toHaveBeenCalledWith('org','doc');expect(s.preparation.inspect).toHaveBeenCalledWith({consumerUnitId:'unit',month:'2026-08'},'org');expect(r.counts.approvedParameters).toBe(2);expect(r.costs.status).toBe('DRAFT_PENDING');expect(r.findings).toEqual(s.result.findings);expect(r.canImport).toBe(false);expect(r.homologated).toBe(false);});
 it('shows validated records without labeling them imported',async()=>{const s=setup();s.result.costs={status:'VALIDATED',draftCount:0,validatedCount:1,validatedVersion:{id:'cost',version:2,revision:3,costs:{sensitive:'not returned'}}} as any;const r=await s.service.inspect('doc',s.tenant);expect(r.costs.validatedVersion).toEqual({id:'cost',version:2,revision:3});expect(r.message).toContain('não comprova importação');});
 it.each(['userId','organizationId','permissions'])('denies missing %s before reading the document',async key=>{const s=setup();await expect(s.service.inspect('doc',{...s.tenant,[key]:key==='permissions'?[]:''})).rejects.toThrow();expect(s.queue.reviewSource).not.toHaveBeenCalled();});
 it.each([P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW])('requires both read permissions',async permission=>{const s=setup();await expect(s.service.inspect('doc',{...s.tenant,permissions:[permission]})).rejects.toThrow();expect(s.preparation.inspect).not.toHaveBeenCalled();});
 it('propagates missing document/license instead of querying another unit',async()=>{const s=setup();s.queue.reviewSource.mockRejectedValueOnce(new Error('blocked'));await expect(s.service.inspect('doc',s.tenant)).rejects.toThrow('blocked');expect(s.preparation.inspect).not.toHaveBeenCalled();});
 it('propagates calculation entitlement or unavailable records instead of partial success',async()=>{const s=setup();s.preparation.inspect.mockRejectedValueOnce(new Error('license'));await expect(s.service.inspect('doc',s.tenant)).rejects.toThrow('license');});
 it.each(['unit','customer','month'])('rejects a changed %s binding',async field=>{const s=setup();if(field==='month')s.result.month='2026-09';else if(field==='unit')s.result.unit.id='other';else s.result.unit.customerId='other';await expect(s.service.inspect('doc',s.tenant)).rejects.toThrow('vínculo');});
});
