import {OcrCdeTaxIntegrationService} from './ocr-cde-tax-integration.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {componentTaxHighlights} from './cde-tax-highlights';
import {validateWriteDto} from '../../common/validation/validate-write-dto';
import {UpdateParameterDto} from '../contracts/dto/parameters.dto';
jest.mock('./cpfl-paulista-layout',()=>({extractCpflPaulistaLayout:jest.fn()}));
jest.mock('./cde-tax-highlights',()=>({componentTaxHighlights:jest.fn()}));
const uuid=(n:number)=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
function setup(){
 const doc='doc',org='org',unit=uuid(10),customer='customer',codes=['ICMS','PIS','COFINS'];
 const source={doc:{file_hash:'f'.repeat(64),customer_id:customer},jobId:'job',raw:{}},period={start:'2026-08-01',end:'2026-08-31'},provenance='OCR CPFL · documento '+doc+' · SHA-256 '+source.doc.file_hash;
 const a:any={source,unit:{id:unit},sourceReady:true,period,ids:[uuid(1),uuid(2)],taxIds:[uuid(5),uuid(6),uuid(7)],preview:{token:'a',month:'2026-08',candidates:['PEAK','OFF_PEAK'].map(band=>({band,source:band,rateMwh:'212.65684'}))}};
 const b:any={...a,ids:[uuid(3),uuid(4)],preview:{token:'b',month:'2026-08',candidates:['PEAK','OFF_PEAK'].map(band=>({band,source:'CDE-'+band,rateMwh:'5.02609'})),taxHighlights:{taxes:codes.map((code,i)=>({code,total:['100.53','4.71','22.13'][i]}))}}};
 const rows:any[]=[a,b].flatMap((s,j)=>s.ids.map((id:string,i:number)=>({id,organization_id:org,customer_id:customer,consumer_unit_id:unit,scenario:'ACL',start_date:period.start,end_date:period.end,status:'APPROVED',revision:2,kind:'TARIFF',component_code:j?'CDE_WATER_SCARCITY':'TUSD_ENERGY',time_band:s.preview.candidates[i].band,measure:'BRL_MWH',amount_text:s.preview.candidates[i].rateMwh,treatment:'GROSS',embedded_tax_codes:codes,direction:'DEBIT',source:provenance+' · '+s.preview.candidates[i].source})));
 rows.push(...codes.map((code,i)=>({id:a.taxIds[i],organization_id:org,customer_id:customer,consumer_unit_id:unit,scenario:'ACL',start_date:period.start,end_date:period.end,status:'DRAFT',revision:1,kind:'TAX',component_code:code,label:code+' incluído na TUSD da fatura',time_band:'ALL',measure:'PERCENT',amount_text:null,treatment:'INCLUDED',embedded_tax_codes:[],direction:'DEBIT',source:provenance,notes:'Evidência anterior preservada.',base_rule:'Somente TUSD.',included_taxes:'',tax_basis:{version:1,items:a.ids.map((id:string)=>({parameterId:id,revision:2,operation:'INCLUDE'}))}})));
 const insert=jest.fn((input:any[])=>{const saved=input.map(p=>({...p,revision:1}));rows.push(...saved);return {select:()=>({single:async()=>({data:saved[0],error:null})})};});
 const calls:any[]=[],db:any={getClient:()=>({from:(table:string)=>{const q:any={insert};for(const m of ['select','eq','range'])q[m]=(...args:any[])=>{calls.push([table,m,...args]);return q;};q.then=(resolve:any)=>resolve({data:rows,error:null});return q;}})};
 const writer={update:jest.fn(async(id:string,d:any)=>{await validateWriteDto(UpdateParameterDto,d);const p=rows.find(p=>p.id===id);p.tax_basis=d.taxBasis;p.notes=d.notes;p.base_rule=d.baseRule;p.revision++;return p;})};
 const tusd={taxIntegrationSource:jest.fn(async()=>a)},cde={taxIntegrationSource:jest.fn(async()=>b)};
 (extractCpflPaulistaLayout as jest.Mock).mockReturnValue({operations:[]});(componentTaxHighlights as jest.Mock).mockReturnValue({taxes:codes.map((code,i)=>({code,total:['5829.14','273.52','1282.61'][i]}))});
 const service=new OcrCdeTaxIntegrationService(db,tusd as any,cde as any,writer as any),t:any={organizationId:org,userId:'actor',role:'gestor',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_UPDATE]};
 return {service,t,rows,a,b,writer,tusd,cde,calls,insert};
}
describe('CDE extension of existing tax declarations',()=>{
 it('sums exact included highlights and never adds a new tax or rate',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);expect(p.amounts.map(v=>v.total)).toEqual(['5929.67','278.23','1304.74']);expect(p.declarations.every(d=>d.canUpdate)).toBe(true);expect(s.calls).toContainEqual(['calculation_parameters','eq','organization_id','org']);expect(s.calls).toContainEqual(['calculation_parameters','eq','consumer_unit_id',uuid(10)]);});
 it('edits only one draft through audited service with real actor and four exact revisions',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);const out=await s.service.update('doc',s.t,{token:p.token,code:'ICMS'});expect(out).toEqual({alreadyUpdated:false,parameterId:uuid(5),revision:2});expect(s.writer.update).toHaveBeenCalledTimes(1);const [id,d,org,actor]=s.writer.update.mock.calls[0] as any;expect([id,org,actor]).toEqual([uuid(5),'org','actor']);expect(d).toMatchObject({amount:null,treatment:'INCLUDED',revision:1});expect(d.taxBasis.items).toEqual([1,2,3,4].map(n=>({parameterId:uuid(n),revision:2,operation:'INCLUDE'})));expect(d.notes).toContain('Evidência anterior preservada.');expect(d.notes).toContain('5929.67');expect(s.rows[4].status).toBe('DRAFT');expect(s.rows[5].revision).toBe(1);await s.service.update('doc',s.t,{token:p.token,code:'ICMS'});expect(s.writer.update).toHaveBeenCalledTimes(1);});
 it('refreshes after each independent tax and converges without duplicates',async()=>{const s=setup();for(const code of ['ICMS','PIS','COFINS']){const p=await s.service.preview('doc',s.t);await s.service.update('doc',s.t,{token:p.token,code});}expect((await s.service.preview('doc',s.t)).declarations.every(d=>d.state==='LINKED'&&!d.canUpdate)).toBe(true);expect(s.rows.length).toBe(7);});
 it.each(['DRAFT','RETIRED'])('blocks CDE base status %s',async(status)=>{const s=setup();s.rows[2].status=status;const p=await s.service.preview('doc',s.t);expect(p.declarations.every(d=>!d.canUpdate)).toBe(true);await expect(s.service.update('doc',s.t,{token:p.token,code:'ICMS'})).rejects.toThrow();expect(s.writer.update).not.toHaveBeenCalled();});
 it.each(['amount_text','customer_id','organization_id','consumer_unit_id','source','scenario','start_date','treatment'])('blocks mismatched base %s',async(key)=>{const s=setup();s.rows[2][key]='changed';expect((await s.service.preview('doc',s.t)).declarations.every(d=>!d.canUpdate)).toBe(true);});
 it('blocks revoked evidence and inconsistent snapshots',async()=>{const s=setup();s.b.sourceReady=false;expect((await s.service.preview('doc',s.t)).evidenceReady).toBe(false);s.b.sourceReady=true;s.b.source={...s.b.source,jobId:'other'};expect((await s.service.preview('doc',s.t)).declarations.every(d=>!d.canUpdate)).toBe(true);});
 it('keeps missing tax evidence unknown and blocks update',async()=>{const s=setup();s.b.preview.taxHighlights.taxes[0].total=null;const p=await s.service.preview('doc',s.t);expect(p.amounts[0].total).toBeNull();expect(p.declarations.every(d=>!d.canUpdate)).toBe(true);});
 it('preserves approved taxes, manual bases and overlapping declarations',async()=>{const s=setup();s.rows[4].status='APPROVED';s.rows[5].tax_basis.items.push({parameterId:uuid(99),revision:1,operation:'INCLUDE'});s.rows.push({...s.rows[6],id:uuid(98)});expect((await s.service.preview('doc',s.t)).declarations.map(d=>d.state)).toEqual(['REVISION_READY','MANUAL_REVIEW','CONFLICT']);expect(s.writer.update).not.toHaveBeenCalled();});
 it('does not overwrite stale base revisions or tax edits',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);s.rows[4].notes='New note';await expect(s.service.update('doc',s.t,{token:p.token,code:'ICMS'})).rejects.toThrow();s.rows[0].revision++;expect((await s.service.preview('doc',s.t)).declarations.every(d=>!d.canUpdate)).toBe(true);expect(s.writer.update).not.toHaveBeenCalled();});
 it('does not truncate previous notes',async()=>{const s=setup();s.rows[4].notes='x'.repeat(4000);const p=await s.service.preview('doc',s.t);await expect(s.service.update('doc',s.t,{token:p.token,code:'ICMS'})).rejects.toThrow('truncada');expect(s.writer.update).not.toHaveBeenCalled();});
 it('denies forged fields, roles and missing read/write permissions',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);for(const body of [{token:p.token,code:'ICMS',actor:'other'},{token:p.token,code:'IOF'},null])await expect(s.service.update('doc',s.t,body)).rejects.toThrow();await expect(s.service.update('doc',{...s.t,role:'cliente'},{token:p.token,code:'ICMS'})).rejects.toThrow();await expect(s.service.preview('doc',{...s.t,permissions:[]})).rejects.toThrow();await expect(s.service.update('doc',{...s.t,permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW]},{token:p.token,code:'ICMS'})).rejects.toThrow();expect(s.writer.update).not.toHaveBeenCalled();});
 it('propagates source license/access denial and revision conflicts',async()=>{const s=setup();s.tusd.taxIntegrationSource.mockRejectedValueOnce(new Error('License'));await expect(s.service.preview('doc',s.t)).rejects.toThrow('License');const p=await s.service.preview('doc',s.t);s.writer.update.mockRejectedValueOnce(new Error('Revision changed'));await expect(s.service.update('doc',s.t,{token:p.token,code:'ICMS'})).rejects.toThrow('Revision changed');});
});

describe('New CDE tax revision from an approved declaration',()=>{
 const approved=()=>{const s=setup();s.t.permissions.push(P.ORGANIZATION_CONTRACTS_CREATE);s.rows[4].status='APPROVED';return s;};
 it('creates an idempotent proposed draft while preserving the approved original',async()=>{const s=approved(),original=JSON.stringify(s.rows[4]),p=await s.service.preview('doc',s.t);expect(p.declarations[0].canCreateRevision).toBe(true);expect(p.declarations[0].canUpdate).toBe(false);const result=await s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token});expect(result.alreadyCreated).toBe(false);expect(s.insert).toHaveBeenCalledTimes(1);const row=s.insert.mock.calls[0][0][0];expect(row).toMatchObject({organization_id:'org',customer_id:'customer',consumer_unit_id:uuid(10),status:'DRAFT',created_by:'actor',updated_by:'actor',treatment:'INCLUDED',amount_text:null});expect(row.tax_basis.items).toHaveLength(4);expect(row.source).toContain(uuid(5));expect(row.notes).toContain('5929.67');expect(JSON.stringify(s.rows[4])).toBe(original);expect(s.writer.update).not.toHaveBeenCalled();const again=await s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token});expect(again.alreadyCreated).toBe(true);expect(s.insert).toHaveBeenCalledTimes(1);expect((await s.service.preview('doc',s.t)).declarations[0].state).toBe('REVISION_CREATED');});
 it('requires create permission as well as update and approved compatible bases',async()=>{const s=approved();s.t.permissions=s.t.permissions.filter((p:string)=>p!==P.ORGANIZATION_CONTRACTS_CREATE);let p=await s.service.preview('doc',s.t);expect(p.declarations[0].canCreateRevision).toBe(false);await expect(s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token})).rejects.toThrow();s.t.permissions.push(P.ORGANIZATION_CONTRACTS_CREATE);s.rows[3].status='DRAFT';p=await s.service.preview('doc',s.t);await expect(s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token})).rejects.toThrow();expect(s.insert).not.toHaveBeenCalled();});
 it('preserves a proposed revision with manual changes and refuses another copy',async()=>{const s=approved(),p=await s.service.preview('doc',s.t);await s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token});s.rows[7].tax_basis.items.pop();const next=await s.service.preview('doc',s.t);expect(next.declarations[0].state).toBe('MANUAL_REVIEW');await expect(s.service.createRevision('doc',s.t,{code:'ICMS',token:next.token})).rejects.toThrow();expect(s.insert).toHaveBeenCalledTimes(1);});
 it('keeps the same proposed revision after the old one is retired',async()=>{const s=approved(),p=await s.service.preview('doc',s.t);await s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token});s.rows[4].status='RETIRED';s.rows[4].revision++;expect((await s.service.preview('doc',s.t)).declarations[0].state).toBe('REVISION_CREATED');expect(s.insert).toHaveBeenCalledTimes(1);});
 it('rejects stale previews and injected financial fields',async()=>{const s=approved(),p=await s.service.preview('doc',s.t);await expect(s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token,amount:'1'})).rejects.toThrow();s.rows[4].revision++;await expect(s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token})).rejects.toThrow();expect(s.insert).not.toHaveBeenCalled();});
});

describe('approved demand successor in CDE preview',()=>{it('shows the audited successor instead of a false conflict and never enables old writes',async()=>{const s=setup();s.t.permissions.push(P.ORGANIZATION_CONTRACTS_CREATE);s.rows[4].status='APPROVED';let p=await s.service.preview('doc',s.t);await s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token});const previous=s.rows[7];s.rows[4].status='RETIRED';previous.status='RETIRED';const scope=Object.fromEntries(['organization_id','customer_id','consumer_unit_id','scenario','start_date','end_date'].map(k=>[k,previous[k]]));for(const n of [8,9])s.rows.push({...scope,id:uuid(n),status:'APPROVED',revision:2,kind:'TARIFF',component_code:n===8?'TUSD_DEMAND_USED':'TUSD_DEMAND_UNUSED',time_band:'ALL',measure:'BRL_KW',treatment:'GROSS',direction:'DEBIT',embedded_tax_codes:n===8?['ICMS','PIS','COFINS']:['PIS','COFINS']});s.rows.push({...previous,id:uuid(20),status:'APPROVED',revision:2,supersedes_parameter_id:previous.id,source:previous.source+' · versão ampliada do parâmetro '+previous.id,tax_basis:{version:1,items:[...previous.tax_basis.items,{parameterId:uuid(8),revision:2,operation:'INCLUDE'},{parameterId:uuid(9),revision:2,operation:'EXCLUDE'}]}});p=await s.service.preview('doc',s.t);expect(p.declarations[0]).toMatchObject({state:'SUPERSEDED',canUpdate:false,canCreateRevision:false,successor:{id:uuid(20),status:'APPROVED',linkedBaseCount:6}});await expect(s.service.update('doc',s.t,{code:'ICMS',token:p.token})).rejects.toThrow();await expect(s.service.createRevision('doc',s.t,{code:'ICMS',token:p.token})).rejects.toThrow();s.rows.push({...s.rows[s.rows.length-1],id:uuid(21)});expect((await s.service.preview('doc',s.t)).declarations[0].state).toBe('CONFLICT');});});
