import {OcrCipIntegrationService} from './ocr-cip-integration.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {cipCostCandidate} from './cip-cost-candidate';
jest.mock('./cpfl-paulista-layout',()=>({extractCpflPaulistaLayout:jest.fn()}));
jest.mock('./cip-cost-candidate',()=>({cipCostCandidate:jest.fn()}));
function setup(){
 (extractCpflPaulistaLayout as jest.Mock).mockReturnValue({operations:[]});
 (cipCostCandidate as jest.Mock).mockReturnValue({ready:true,source:'table.row',amount:'137.58',description:'CIP AGO/26',amountConfidence:.995,descriptionConfidence:.977,pages:[1]});
 const c:any={sourceReady:true,unit:{id:'unit',status:'ACTIVE',free_market:true,tariff_group:'A'},preview:{month:'2026-08',token:'source'},source:{doc:{customer_id:'customer',file_hash:'a'.repeat(64)},jobId:'job'}};
 const data:any={customers:{id:'customer',status:'ACTIVE',deleted_at:null},calculation_monthly_costs:[]},calls:any[]=[],insert=jest.fn((row:any)=>{data.calculation_monthly_costs=[{...row,version:1,revision:1}];return {select:async()=>({data:[{id:row.id}],error:null})};});
 let error:any=null;const from=(table:string)=>{const q:any={insert};for(const method of ['select','eq','order','limit'])q[method]=(...args:any[])=>{calls.push([table,method,...args]);return q;};q.maybeSingle=async()=>({data:data[table],error});q.then=(resolve:any)=>resolve({data:data[table],error});return q;};
 const source={taxIntegrationSource:jest.fn(async()=>c)},s=new OcrCipIntegrationService({getClient:()=>({from})} as any,source as any),t:any={organizationId:'org',userId:'actor',role:'gestor',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_CREATE]};
 return {s,t,c,data,insert,calls,source,setError:(v:any)=>error=v};
}
describe('CIP integration',()=>{
 it('creates only a sourced draft with actual actor and unspecified taxes; retries are idempotent',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);expect(p.canCreate).toBe(true);const r=await x.s.create('doc',x.t,{token:p.token});const row=x.insert.mock.calls[0][0];expect(row).toMatchObject({id:r.inputId,organization_id:'org',customer_id:'customer',consumer_unit_id:'unit',origin:'OCR_CIP',month:'2026-08',status:'DRAFT',created_by:'actor',updated_by:'actor',costs:{noCosts:false,items:[{amount:'137.58',scenario:'ACL',effect:'COST',category:'CHARGE',taxTreatment:'UNSPECIFIED'}]}});expect(row.source_reference).toContain('a'.repeat(64));expect(row.notes).toContain(p.token);expect(x.calls).toContainEqual(['calculation_monthly_costs','eq','organization_id','org']);expect(x.calls).toContainEqual(['calculation_monthly_costs','eq','customer_id','customer']);await expect(x.s.create('doc',x.t,{token:p.token})).resolves.toMatchObject({alreadyCreated:true,inputId:r.inputId});expect(x.insert).toHaveBeenCalledTimes(1);});
 it('does not replace existing draft or validated costs',async()=>{for(const status of ['DRAFT','VALIDATED']){const x=setup();x.data.calculation_monthly_costs=[{id:'manual',status,revision:1}];const p=await x.s.preview('doc',x.t);expect(p.state).toBe('EXISTING_RECORD');await expect(x.s.create('doc',x.t,{token:p.token})).rejects.toThrow();expect(x.insert).not.toHaveBeenCalled();}});
 it('blocks stale source, inactive/deleted customer and incomplete confirmations',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.c.preview.token='changed';await expect(x.s.create('doc',x.t,{token:p.token})).rejects.toThrow('prévia mudou');x.data.customers.status='INACTIVE';expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);x.data.customers.status='ACTIVE';x.data.customers.deleted_at='now';expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);x.data.customers.deleted_at=null;x.c.sourceReady=false;expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);expect(x.insert).not.toHaveBeenCalled();});
 it('rejects browser supplied values and unauthorized writers',async()=>{const x=setup();for(const body of [null,{},[],{token:'a'.repeat(64),amount:'0'},{token:1}])await expect(x.s.create('doc',x.t,body)).rejects.toThrow();for(const t of [{...x.t,role:'operador'},{...x.t,permissions:[]},{...x.t,userId:''}])await expect(x.s.create('doc',t,{token:'a'.repeat(64)})).rejects.toThrow();expect(x.insert).not.toHaveBeenCalled();});
 it('propagates licensed scoped source denial and sanitizes DB failures',async()=>{const x=setup();x.source.taxIntegrationSource.mockRejectedValueOnce(new Error('scope/license'));await expect(x.s.preview('doc',x.t)).rejects.toThrow('scope/license');x.setError({message:'private'});await expect(x.s.preview('doc',x.t)).rejects.toThrow('Não foi possível');});
 it('blocks low confidence candidates',async()=>{const x=setup();(cipCostCandidate as jest.Mock).mockReturnValue({ready:false,amount:'137.58'});expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);});
 it('resolves concurrent same-document duplicate without creating a second item',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.insert.mockImplementationOnce((row:any)=>{x.data.calculation_monthly_costs=[row];return {select:async()=>({data:null,error:{code:'23505'}})} as any;});await expect(x.s.create('doc',x.t,{token:p.token})).resolves.toMatchObject({alreadyCreated:true});});
 it('preserves a concurrently created different record',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.insert.mockImplementationOnce(()=>{x.data.calculation_monthly_costs=[{id:'other'}];return {select:async()=>({data:null,error:{code:'P3602'}})} as any;});await expect(x.s.create('doc',x.t,{token:p.token})).rejects.toThrow('Os custos mudaram');});
});
