import {Injectable,BadRequestException,ConflictException,ForbiddenException,ServiceUnavailableException} from '@nestjs/common';
import {TenantContext} from '../../common/interfaces/tenant-context.interface';
import {PERMISSIONS as P} from '../../common/constants/permissions';
import {SupabaseService} from '../../services/supabase.service';
import {LicensesService} from '../licenses/services/licenses.service';
import {CalculationPreparationService} from '../contracts/services/preparation.service';
import {CalculationParametersService} from '../contracts/services/parameters.service';
import {MonthlyInputsService} from '../contracts/services/monthly-inputs.service';
import {MonthlyCostsService} from '../contracts/services/monthly-costs.service';
import {ParameterDto} from '../contracts/dto/parameters.dto';
import {OcrQueueService} from './ocr-queue.service';
import {OcrIdentityReviewService} from './ocr-identity-review.service';
import {OcrReviewService,ocrReviewDigest} from './ocr-review.service';
import {OcrTusdIntegrationService} from './ocr-tusd-integration.service';
import {OcrCdeIntegrationService} from './ocr-cde-integration.service';
import {OcrMonthlyIntegrationService} from './ocr-monthly-integration.service';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {reactiveParameterCandidates} from './reactive-parameter-candidates';
import {loadDemandFinancialMemory} from '../contracts/services/demand-financial-memory';
import {homologationProgress} from './homologation-progress';
import {combinedTaxLayout,operationTaxCodes,reviewedLayoutSupported} from './reviewed-layout-support';
import {cpflReference} from './cpfl-measurements';
import {cipCostCandidate} from './cip-cost-candidate';
import {monthPeriod} from '../contracts/services/preparation';
import {normalizeBilledDemand} from '../contracts/services/billed-demand';
import {resolutionId,resolutionRateState,resolutionGroups} from './ocr-resolution-plan';
import {ocrDraftPermission,ocrDraftRole} from './ocr-draft-access';
import {inspectOnce} from './ocr-read-scope';

const codes=['ICMS','PIS','COFINS'];
const numeric=(v:any)=>typeof v==='string'&&/^(0|[1-9][0-9]{0,11})([.]\d{1,9})?$/.test(v);
const quantityEqual=(a:string,b:string)=>{const scale=(s:string)=>{const [w,f='']=s.split('.');return BigInt(w)*1000000000n+BigInt(f.padEnd(9,'0'));};return numeric(a)&&numeric(b)&&scale(a)===scale(b);};
@Injectable()
export class OcrResolutionService {
 constructor(private db:SupabaseService,private licenses:LicensesService,private queue:OcrQueueService,private identities:OcrIdentityReviewService,private reviews:OcrReviewService,private preparation:CalculationPreparationService,private parameters:CalculationParametersService,private inputs:MonthlyInputsService,private costs:MonthlyCostsService,private tusd:OcrTusdIntegrationService,private cde:OcrCdeIntegrationService,private monthly:OcrMonthlyIntegrationService){}
 private async allowed(t:TenantContext,write=false){if(!t.userId||!t.organizationId||(t.scope as string)==='global'||![P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW].every(p=>t.permissions?.includes(p)))throw new ForbiddenException('Selecione a organização e um perfil autorizado.');if(write&&(!ocrDraftRole(t)||!ocrDraftPermission(t)||!t.permissions.includes(P.ENERGIA_OCR_PROCESS)))throw new ForbiddenException('Preparação exige perfil backoffice, contratos e OCR.');await this.licenses.requireEntitlement(t.organizationId,'document_management');await this.licenses.requireEntitlement(t.organizationId,'free_market_management');}
 private context(document:string,t:TenantContext){return inspectOnce(()=>this.loadContext(document,t));}
 private async loadContext(document:string,t:TenantContext){
  await this.allowed(t);const source=await this.queue.reviewSource(t.organizationId,document),layout=extractCpflPaulistaLayout(source.raw),month=String(source.doc.reference_month).slice(0,7),period=monthPeriod(month);let captured:any;
  const [identity,consumption,diagnosis,tusd,cde,technical,memory,documents]=await Promise.all([this.identities.list(t.organizationId,document),this.reviews.list(t.organizationId,document),this.preparation.inspect({consumerUnitId:source.doc.consumer_unit_id,month},t.organizationId,s=>{captured=s;}),this.tusd.preview(document,t),this.cde.preview(document,t),this.monthly.measurementReadiness(document,t),loadDemandFinancialMemory(this.db.getClient(),source.doc,source.jobId,layout),this.db.getClient().from('documents').select('id,document_type,original_filename,file_hash,file_verified,customer_id,consumer_unit_id,organization_id,reference_month').eq('organization_id',t.organizationId).eq('customer_id',source.doc.customer_id).eq('consumer_unit_id',source.doc.consumer_unit_id).eq('reference_month',month+'-01').eq('document_type','INVOICE_SUPPLIER').eq('file_verified',true).limit(101)]);
  if(!captured||documents.error||!Array.isArray(documents.data)||documents.data.length>100)throw new ServiceUnavailableException('Não foi possível conferir todas as fontes da competência.');
  const unit=captured.unit,rows=captured.parameters.filter((p:any)=>p.start_date<=period.end&&p.end_date>=period.start),groups=homologationProgress(identity.fields,consumption.fields,[]).groups,refs=[...new Set(layout.fields.filter(f=>f.name==='reference').map(f=>cpflReference(f.value.text)))];
  const ready=groups[0].complete&&groups[1].complete&&unit.id===source.doc.consumer_unit_id&&unit.customer_id===source.doc.customer_id&&unit.status==='ACTIVE'&&unit.free_market===true&&unit.tariff_group==='A'&&unit.tariff_modality==='GREEN'&&reviewedLayoutSupported(layout.layoutId)&&layout.reconciliation.state==='MATCH'&&refs.length===1&&refs[0]===month;
  const provenance='OCR · documento '+document+' · SHA-256 '+source.doc.file_hash;
  const candidates:any[]=[];
  const add=(component:string,band:string,amount:string|null,measure:string,line:string|null,label:string)=>{const operation=layout.operations.find(r=>r.source===line),taxCodes=operationTaxCodes(operation,combinedTaxLayout(layout));if(!numeric(amount)||!line||!taxCodes.length)return;candidates.push({component,band,amount,measure,line,label,taxCodes,source:provenance+' · '+line});};
  for(const [component,preview] of [['TUSD_ENERGY',tusd],['CDE_WATER_SCARCITY',cde]] as const){for(const v of preview.candidates){const f=consumption.fields.find(f=>f.key===(v.band==='PEAK'?'consumptionPeakKwh':'consumptionOffPeakKwh'));if(v.ready&&v.quantity&&f?.decimal&&quantityEqual(v.quantity,f.decimal))add(component,v.band,v.rateMwh,'BRL_MWH',v.source,(component==='TUSD_ENERGY'?'TUSD energia':'CDE')+' · '+(v.band==='PEAK'?'ponta':'fora ponta'));}}
  const reactive=reactiveParameterCandidates(layout.operations,layout.layoutId);if(reactive.length&&reactive.every(v=>v.ready))for(const v of reactive)add('REACTIVE',v.band,v.rateMwh,'BRL_MWH',v.source,'Reativo faturado · '+(v.band==='PEAK'?'ponta':'fora ponta'));
  if(memory?.state==='RECONCILED'&&memory.rows.length===2&&['USED','UNUSED'].every(c=>memory.rows.filter(r=>r.classification===c).length===1))for(const v of memory.rows)add('TUSD_DEMAND_'+v.classification,'ALL',v.rate,'BRL_KW',v.source,'Demanda '+(v.classification==='USED'?'utilizada':'não utilizada'));
  const rates=candidates.map(c=>({...c,...resolutionRateState(c,rows,period.start,period.end,unit)}));
  const input=[...captured.monthly].sort((a:any,b:any)=>b.version-a.version)[0]??null,cost=[...captured.monthlyCosts].sort((a:any,b:any)=>b.version-a.version)[0]??null;
  const taxes=codes.map(code=>({code,existing:rows.filter((p:any)=>p.kind==='TAX'&&p.scenario==='ACL'&&p.component_code===code&&p.status!=='RETIRED'),bases:rates.filter(r=>r.state==='PRESERVED'&&r.taxCodes.includes(code)).map(r=>({parameterId:r.existing.id,revision:r.existing.revision,operation:'INCLUDE'}))}));
  const marker='bot-energy · '+document+' · '+source.doc.file_hash;
  const billed=input?JSON.parse(JSON.stringify(input.billed_demand??{})):{};
  if(memory?.state==='RECONCILED'&&memory.rows.length===2){const used=memory.rows.find(r=>r.classification==='USED')?.quantity,unused=memory.rows.find(r=>r.classification==='UNUSED')?.quantity;if(numeric(used)&&numeric(unused)){const scaled=(v:string)=>{const [w,f='']=v.split('.');return BigInt(w)*1000000000n+BigInt(f.padEnd(9,'0'));};const total=(scaled(used!)+scaled(unused!)).toString().padStart(10,'0');const single=(total.slice(0,-9)+'.'+total.slice(-9)).replace(/0+$/,'').replace(/[.]$/,'');billed.ACL={single,peak:null,offPeak:null,used,unused,source:provenance};}}
  const measurements=input?{...input.measurements}:Object.fromEntries(consumption.fields.map(f=>[{consumptionPeakKwh:'consumptionPeak',consumptionOffPeakKwh:'consumptionOffPeak',consumptionTotalKwh:'consumptionTotal'}[f.key],f.decimal]).filter(([k])=>k));
  for(const f of consumption.fields){const key={consumptionPeakKwh:'consumptionPeak',consumptionOffPeakKwh:'consumptionOffPeak',consumptionTotalKwh:'consumptionTotal'}[f.key];if(key&&numeric(f.decimal))measurements[key]=f.decimal;}
  for(const v of reactive)if(v.ready&&v.quantity)measurements[v.band==='PEAK'?'reactiveBilledPeakKwh':'reactiveBilledOffPeakKwh']=v.quantity;
  const monthlyChanges=Object.keys(measurements).filter(k=>measurements[k]!==input?.measurements?.[k]).map(k=>({label:k,before:input?.measurements?.[k]??null,after:measurements[k]}));
  if(JSON.stringify(normalizeBilledDemand(billed)?.ACL)!==JSON.stringify(normalizeBilledDemand(input?.billed_demand)?.ACL))monthlyChanges.push({label:'Parcelas faturadas ACL (separadas da demanda medida)',before:input?.billed_demand?.ACL??null,after:billed.ACL});
  const cip=cipCostCandidate(layout.operations,month),items=cost?.costs?.items??[],cipPresent=items.some((i:any)=>i.scenario==='ACL'&&i.source?.includes(document)&&i.amount===cip.amount),supplierPresent=items.some((i:any)=>i.scenario==='ACL'&&i.category==='SUPPLIER_INVOICE');
  const token=ocrReviewDigest({format:'resolution-1',actor:t.userId,org:t.organizationId,source:source.doc,job:source.jobId,raw:source.raw,captured,identity,consumption,memory,documents:documents.data,rates,technical});
  const evidenceToken=ocrReviewDigest({source:source.doc,job:source.jobId,raw:source.raw,unit,identity,consumption,memory,technicalDemand:technical.demand,documents:documents.data});
  return {evidenceToken,source,unit,period,month,ready,rows,rates,taxes,input,cost,marker,provenance,measurements,billed,technical,monthlyChanges,cip,cipPresent,supplierPresent,documents:documents.data,diagnosis,token,groups:resolutionGroups(diagnosis.findings)};
 }
 private parameter(c:any,r:any):ParameterDto{return {consumerUnitId:c.unit.id,kind:'TARIFF',componentCode:r.component,label:r.label,scenario:'ACL',timeBand:r.band,measure:r.measure,amount:r.amount,treatment:'GROSS',embeddedTaxCodes:r.taxCodes,includedTaxes:'Tributos destacados nesta linha já incluídos no preço final; sem nova cobrança.',baseRule:'',direction:'DEBIT',source:r.source,notes:c.marker+' · tarifa bruta da linha '+r.line+' · conferências atuais de identidade, consumo e classificação da demanda preservadas.',startDate:c.period.start,endDate:c.period.end};}
 private tax(c:any,v:any):ParameterDto{return {consumerUnitId:c.unit.id,kind:'TAX',componentCode:v.code,label:v.code+' já incluído nas linhas ACL',scenario:'ACL',timeBand:'ALL',measure:'PERCENT',amount:null,treatment:'INCLUDED',taxBasis:{version:1,items:v.bases},embeddedTaxCodes:[],includedTaxes:'',baseRule:'Declaração das bases OCR com tributo embutido. Não aplicar a alíquota novamente.',direction:'DEBIT',source:c.provenance,notes:c.marker+' · declaração limitada às rubricas vinculadas. Não presume isenção do fornecedor ou incidência em outros cenários.',startDate:c.period.start,endDate:c.period.end};}
 private automatic(c:any){return {monthly:c.ready&&!!c.monthlyChanges?.length&&c.input?.status!=='DRAFT',costs:c.ready&&c.cip.ready&&!c.cipPresent&&c.cost?.status!=='DRAFT'&&!(c.cost?.costs?.items??[]).some((i:any)=>i.scenario==='ACL'&&i.category==='OTHER')};}
 private demandSuggestion(c:any){
  for(const source of ['meter','history']){const values=(c.technical.demand??[]).map((d:any)=>d[source]?.decimal);if(values.length!==2||values.some((v:any)=>!numeric(v)))continue;const scaled=(v:string)=>{const [w,f='']=v.split('.');return BigInt(w)*1000000000n+BigInt(f.padEnd(9,'0'));};return {source,value:scaled(values[0])>=scaled(values[1])?values[0]:values[1],reason:'Maior demanda medida entre postos desta fonte. Proposta para confirmação; divergências com o histórico são preservadas.'};}
  return {source:'keep',value:null,reason:'Não há fonte completa para propor demanda medida.'};
 }
 private publicPlan(c:any,t:TenantContext){return {token:c.token,ready:c.ready,canPrepare:c.ready&&ocrDraftRole(t)&&ocrDraftPermission(t)&&t.permissions.includes(P.ENERGIA_OCR_PROCESS),approvalReady:c.rates.every((r:any)=>r.state==='PRESERVED')&&c.taxes.every((v:any)=>v.existing.length===1&&v.existing[0].source===c.provenance&&v.existing[0].notes?.startsWith(c.marker)&&v.existing[0].treatment==='INCLUDED'),canRepair:t.permissions.includes(P.ORGANIZATION_CONTRACTS_UPDATE)&&ocrDraftRole(t),canApprove:(['gestor','admin_org'].includes(t.role)||t.accessMode==='platform_operation')&&t.permissions.includes(P.ORGANIZATION_CONTRACTS_UPDATE),unit:c.unit.name,month:c.month,rates:c.rates.map((r:any)=>({label:r.label,component:r.component,band:r.band,amount:r.amount,measure:r.measure,source:r.source,state:r.state,status:r.existing?.status??null})),taxes:c.taxes.map((v:any)=>({code:v.code,bases:v.bases.length,existing:v.existing.map((p:any)=>({id:p.id,status:p.status,treatment:p.treatment,amount:p.amount_text,bot:p.source===c.provenance&&p.notes?.startsWith(c.marker)}))})),automatic:this.automatic(c),monthly:{billedDemand:c.input?.billed_demand??null,proposedBilledDemand:c.billed,prepared:c.input?.status==='DRAFT'&&!!c.input.source_reference?.startsWith(c.marker),values:c.input?.measurements??c.measurements,demandSuggestion:this.demandSuggestion(c),status:c.input?.status??null,source:c.provenance,changes:c.monthlyChanges,demand:c.technical.demand,existingMeasurements:c.input?.measurements??null},costs:{prepared:c.cost?.status==='DRAFT'&&!!c.cost.source_reference?.startsWith(c.marker),status:c.cost?.status??null,cip:c.cip.ready&&!c.cipPresent?{amount:c.cip.amount,source:c.provenance+' · '+c.cip.source}:null,supplierPresent:c.supplierPresent,documents:c.documents.map((d:any)=>({id:d.id,name:d.original_filename})),suggestedInvoiceAmount:c.diagnosis.contractSupplierCost?.regularAmount??null,volumeDifferenceMwh:c.diagnosis.contractSupplierCost?.volumeDifferenceMwh??null},groups:c.groups,counts:c.diagnosis.counts,message:'Tarifas, dados mensais e CIP comprovados são preparados em rascunhos. As decisões restantes já têm propostas para conferir em lote. O valor do fornecedor é uma sugestão contratual; confirme na NF. A aprovação financeira é exclusiva do gestor/administrador.'};}
 async inspect(document:string,t:TenantContext){return this.publicPlan(await this.context(document,t),t);}
 private body(body:any,keys:string[]){if(!body||Array.isArray(body)||Object.keys(body).sort().join(',')!==keys.sort().join(',')||typeof body.token!=='string'||!/^[a-f0-9]{64}$/.test(body.token))throw new BadRequestException('Atualize o plano de resolução.');}
 async prepare(document:string,t:TenantContext,body:any){
  await this.allowed(t,true);this.body(body,['token']);let c=await this.context(document,t);if(!c.ready||c.token!==body.token)throw new ConflictException('Conferências ou fontes mudaram; nenhum novo lote foi iniciado.');const evidenceToken=c.evidenceToken,receipts:any[]=[];
  // Only absent rates. Never overwrite an existing draft or an approved rate.
  const missing=c.rates.filter((r:any)=>r.state==='MISSING');
  const results=await Promise.allSettled(missing.map((r:any)=>this.parameters.createPrepared(resolutionId([t.organizationId,document,c.source.doc.file_hash,r.component,r.band]),this.parameter(c,r),t.organizationId,t.userId)));
  results.forEach((result,i)=>receipts.push({label:missing[i].label,state:result.status==='fulfilled'?'SAVED_DRAFT':'VERIFY_REQUIRED',...(result.status==='fulfilled'?{id:result.value.id}:{})}));
  if(results.some(r=>r.status==='rejected'))return {receipts,current:await this.inspect(document,t),canPublish:false};
  c=await this.context(document,t);
  if(!c.ready||c.evidenceToken!==evidenceToken){receipts.push({label:'As fontes mudaram durante a preparação; conferir rascunhos',state:'VERIFY_REQUIRED'});return {receipts,current:this.publicPlan(c,t),canPublish:false};}
  for(const v of c.taxes.filter((v:any)=>!v.existing.length&&v.bases.length)){try{const saved=await this.parameters.createPrepared(resolutionId([t.organizationId,document,c.source.doc.file_hash,'TAX',v.code]),this.tax(c,v),t.organizationId,t.userId);receipts.push({label:v.code,state:'SAVED_DRAFT',id:saved.id});}catch{receipts.push({label:v.code,state:'VERIFY_REQUIRED'});break;}}
  if(receipts.some(r=>r.state==='VERIFY_REQUIRED'))return {receipts,current:await this.inspect(document,t),canPublish:false};
  // Source-backed revisions are drafts only. Never edit an existing draft during automatic preparation.
  // Database guards serialize versions, preserve validated records and permit only one draft.
  for(const kind of ['monthly','costs'] as const){
   c=await this.context(document,t);
   if(!c.ready||c.evidenceToken!==evidenceToken){receipts.push({label:'Fonte alterada; atualizar antes de continuar',state:'VERIFY_REQUIRED'});break;}
   if(!this.automatic(c)[kind])continue;
   const note='Proposta automática com fonte OCR atual; aguarda conferência do operador. Demanda medida e comparativo ACR existentes preservados.';
   try{let saved:any;
    if(kind==='monthly')saved=await this.inputs.create({consumerUnitId:c.unit.id,month:c.month,measurements:c.measurements,billedDemand:c.billed,sourceReference:c.marker+' · '+c.provenance,notes:note,correctionReason:note,previousId:c.input?.id??null},t);
    else {const items=JSON.parse(JSON.stringify(c.cost?.costs?.items??[]));items.push({id:resolutionId([document,'CIP']),label:'CIP da fatura ACL',scenario:'ACL',category:'OTHER',effect:'COST',amount:c.cip.amount,taxTreatment:'INCLUDED',source:c.provenance+' · '+c.cip.source});saved=await this.costs.create({consumerUnitId:c.unit.id,month:c.month,costs:{items,noCosts:false},sourceReference:c.marker,notes:note,correctionReason:note,previousId:c.cost?.id??null},t);}
    receipts.push({label:kind==='monthly'?'Dados mensais previamente preenchidos':'CIP previamente preenchida; custos anteriores preservados',state:'SAVED_DRAFT',id:saved.id});
   }catch{receipts.push({label:'Preparação mensal interrompida; conferir o histórico antes de repetir',state:'VERIFY_REQUIRED'});break;}
  }
  return {receipts,current:await this.inspect(document,t),canPublish:false};
 }
 async repair(document:string,t:TenantContext,body:any){
  await this.allowed(t,true);if(!t.permissions.includes(P.ORGANIZATION_CONTRACTS_UPDATE))throw new ForbiddenException('Correção exige permissão de contratos.');this.body(body,['token','checkedPdf','note','taxes','monthly','costs','supplier','demandSource','copyDemandToAcr']);if((body.supplier!==null&&!body.costs)||(body.copyDemandToAcr&&!body.monthly)||(body.demandSource!=='keep'&&!body.monthly))throw new BadRequestException('Selecione a revisão correspondente às alterações.');if(body.checkedPdf!==true||typeof body.note!=='string'||body.note.trim().length<10||body.note.length>500||![body.taxes,body.monthly,body.costs,body.copyDemandToAcr].every(v=>typeof v==='boolean')||!['keep','meter','history'].includes(body.demandSource))throw new BadRequestException('Confira fontes, alterações e justificativa.');
  const c=await this.context(document,t);if(!c.ready||c.token!==body.token)throw new ConflictException('O plano mudou; consulte antes de corrigir.');const receipts:any[]=[];
  try{
   if(body.taxes)for(const v of c.taxes){if(v.existing.length!==1||v.existing[0].status!=='DRAFT'||!v.bases.length)continue;const old=v.existing[0];if(old.start_date!==c.period.start||old.end_date!==c.period.end)throw new ConflictException('O rascunho tributário cobre outra vigência. Revise sem encurtar seu período automaticamente.');await this.parameters.update(old.id,{...this.tax(c,v),notes:this.tax(c,v).notes+' · Revisão do operador: '+body.note.trim(),revision:old.revision},t.organizationId,t.userId);receipts.push({label:v.code+' · bases e tratamento corrigidos',state:'SAVED_DRAFT'});}
   if(body.monthly){if(c.input?.status==='DRAFT'&&!c.input.source_reference?.startsWith(c.marker))throw new ConflictException('Existe rascunho mensal de outra origem.');const measurements={...c.measurements};if(body.demandSource!=='keep'){const values=c.technical.demand.map((d:any)=>d[body.demandSource]);if(values.length!==2||values.some((v:any)=>!v||!numeric(v.decimal)))throw new BadRequestException('Demandas da fonte selecionada não estão completas.');const [a,b]=values.map((v:any)=>v.decimal as string);const n=(s:string)=>{const [w,f='']=s.split('.');return BigInt(w)*1000000000n+BigInt(f.padEnd(9,'0'));};measurements.demandSingle=n(a)>=n(b)?a:b;measurements.demandPeak=null;measurements.demandOffPeak=null;}
    const billed=JSON.parse(JSON.stringify(c.billed));if(body.copyDemandToAcr){if(!billed.ACL?.used||!billed.ACL?.unused)throw new BadRequestException('Classificação faturada incompleta.');billed.ACR={...billed.ACL,source:c.provenance+' · Comparação ACR confirmada pelo operador'};}
    const dto={consumerUnitId:c.unit.id,month:c.month,measurements,billedDemand:billed,sourceReference:c.marker+' · '+c.provenance,notes:body.note.trim(),correctionReason:'Revisão bot-energy: '+body.note.trim(),previousId:c.input?.status==='DRAFT'?c.input.previous_id:c.input?.id??null};
    const saved=c.input?.status==='DRAFT'?await this.inputs.update(c.input.id,{...dto,revision:c.input.revision},t):await this.inputs.create(dto,t);receipts.push({label:'Nova revisão de dados mensais',state:'SAVED_DRAFT',id:saved.id});
   }
   if(body.costs){if(c.cost?.status==='DRAFT'&&!c.cost.source_reference?.startsWith(c.marker))throw new ConflictException('Existe rascunho de custos de outra origem.');const items=JSON.parse(JSON.stringify(c.cost?.costs?.items??[]));if(c.cip.ready&&!c.cipPresent&&!items.some((i:any)=>i.scenario==='ACL'&&i.category==='OTHER'))items.push({id:resolutionId([document,'CIP']),label:'CIP da fatura ACL',scenario:'ACL',category:'OTHER',effect:'COST',amount:c.cip.amount,taxTreatment:'INCLUDED',source:c.provenance+' · '+c.cip.source});
    if(body.supplier!==null){const s=body.supplier;if(c.supplierPresent||!s||Array.isArray(s)||Object.keys(s).sort().join(',')!=='amount,documentId,taxTreatment'||typeof s.amount!=='string'||!/^(0|[1-9][0-9]{0,11})[.]\d{2}$/.test(s.amount)||!['INCLUDED','EXCLUDED','RESERVED'].includes(s.taxTreatment)||s.taxTreatment==='RESERVED')throw new BadRequestException('Confira valor documental, tratamento e ausência de nota duplicada. Ressalvas devem usar o fluxo específico.');const doc=c.documents.find((d:any)=>d.id===s.documentId);if(!doc)throw new BadRequestException('Selecione a NF privada desta unidade e competência.');items.push({id:resolutionId([document,'supplier',doc.id]),label:'Nota da compra pontual · '+doc.original_filename,scenario:'ACL',category:'SUPPLIER_INVOICE',effect:'COST',amount:s.amount,taxTreatment:s.taxTreatment,source:'Documento '+doc.id+' · SHA-256 '+doc.file_hash+' · conferido pelo operador: '+body.note.trim()});}
    const dto={consumerUnitId:c.unit.id,month:c.month,costs:{items,noCosts:false},sourceReference:c.marker,notes:body.note.trim(),correctionReason:'Revisão bot-energy: '+body.note.trim(),previousId:c.cost?.status==='DRAFT'?c.cost.previous_id:c.cost?.id??null};const saved=c.cost?.status==='DRAFT'?await this.costs.update(c.cost.id,{...dto,revision:c.cost.revision},t):await this.costs.create(dto,t);receipts.push({label:'Nova revisão de custos (itens anteriores preservados)',state:'SAVED_DRAFT',id:saved.id});
   }
  }catch(e){receipts.push({label:'Confira o histórico antes de repetir',state:'VERIFY_REQUIRED',message:e instanceof Error?e.message:'Resultado incerto.'});}
  return {receipts,current:await this.inspect(document,t),canPublish:false};
 }
 async approve(document:string,t:TenantContext,body:any){
  await this.allowed(t,true);if(!(['gestor','admin_org'].includes(t.role)||t.accessMode==='platform_operation')||!t.permissions.includes(P.ORGANIZATION_CONTRACTS_UPDATE))throw new ForbiddenException('Aprovação exige Gestor ou Administrador.');this.body(body,['token','acknowledged']);if(body.acknowledged!==true)throw new BadRequestException('Confirme a revisão financeira dos parâmetros.');let c=await this.context(document,t);if(!c.ready||c.token!==body.token)throw new ConflictException('O plano mudou.');const receipts:any[]=[];
  try{if(c.taxes.some((v:any)=>v.existing.length!==1||v.existing[0].source!==c.provenance||!v.existing[0].notes?.startsWith(c.marker)||v.existing[0].treatment!=='INCLUDED'))throw new ConflictException('Revise primeiro os rascunhos tributários no lote do operador.');if(c.rates.some((r:any)=>r.state!=='PRESERVED'))throw new ConflictException('Conclua as tarifas sem conflito antes de aprovar.');for(const r of c.rates){if(r.existing.status==='DRAFT'){await this.parameters.approve(r.existing.id,{revision:r.existing.revision},t.organizationId,t.userId);receipts.push({label:r.label,state:'APPROVED'});}}
   c=await this.context(document,t);for(const v of c.taxes){const p=v.existing[0];if(v.existing.length!==1||!p||p.source!==c.provenance||!p.notes?.startsWith(c.marker)||p.treatment!=='INCLUDED')throw new ConflictException('Revise os rascunhos tributários no lote do operador.');if(p.status==='DRAFT'){const saved=await this.parameters.update(p.id,{...this.tax(c,v),notes:p.notes,revision:p.revision},t.organizationId,t.userId);await this.parameters.approve(p.id,{revision:saved.revision},t.organizationId,t.userId);receipts.push({label:v.code,state:'APPROVED'});}}
  }catch(e){receipts.push({label:'Aprovação interrompida; confira etapas concluídas',state:'VERIFY_REQUIRED',message:e instanceof Error?e.message:'Resultado incerto.'});}
  return {receipts,current:await this.inspect(document,t),canPublish:false};
 }
}
