import {OcrDemandTaxIntegrationService} from './ocr-demand-tax-integration.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
const codes=['ICMS','PIS','COFINS'];
function setup(){
 const provenance='OCR CPFL · documento doc · SHA-256 '+'a'.repeat(64),period={start:'2026-08-01',end:'2026-08-31'},common={organization_id:'org',customer_id:'customer',consumer_unit_id:'unit',scenario:'ACL',start_date:period.start,end_date:period.end,status:'APPROVED',revision:2,direction:'DEBIT',amount_text:null,embedded_tax_codes:[],unit_context:{}};
 const baseItems=[1,2,3,4].map(i=>({parameterId:'base'+i,revision:2,operation:'INCLUDE'}));
 const rows:any[]=[...baseItems.map((v,i)=>({...common,id:v.parameterId,kind:'TARIFF',component_code:i<2?'TUSD_ENERGY':'CDE_WATER_SCARCITY'})),...codes.map(code=>({...common,id:code,kind:'TAX',component_code:code,time_band:'ALL',measure:'PERCENT',treatment:'INCLUDED',source:provenance,tax_basis:{version:1,items:baseItems}})),...['USED','UNUSED'].map(k=>({...common,id:k,kind:'TARIFF',component_code:'TUSD_DEMAND_'+k,time_band:'ALL',measure:'BRL_KW',amount_text:'10',treatment:'GROSS',source:provenance+' · '+k,embedded_tax_codes:k==='USED'?codes:['PIS','COFINS']}))];
 const source={jobId:'job',doc:{file_hash:'a'.repeat(64),customer_id:'customer',consumer_unit_id:'unit'}};
 const a:any={rows,baseItems,provenance,bases:rows.slice(0,4),a:{source,unit:{id:'unit'},period},preview:{token:'a',month:'2026-08',evidenceReady:true,bases:baseItems.map(v=>({...v,approved:true})),declarations:codes.map(code=>({code,id:code}))}};
 const b:any={source,ready:true,candidates:['USED','UNUSED'].map(k=>({classification:k,rate:'10',source:k,taxCodes:k==='USED'?codes:['PIS','COFINS']})),preview:{token:'b',state:'INTEGRATED',month:'2026-08',parameterIds:['USED','UNUSED']}};
 const insert=jest.fn((input:any[])=>{rows.push(...input.map(r=>({...r,revision:1})));return {select:()=>({single:async()=>({data:{id:input[0].id},error:null})})};});
 const reactiveContext:any={ready:true,source,candidates:[],evidence:[],preview:{state:'INTEGRATED',month:'2026-08',parameterIds:[],token:'r'}},reactive={taxIntegrationSource:jest.fn(async()=>reactiveContext)};
 const cde={taxIntegrationSource:jest.fn(async()=>a)},demand={taxIntegrationSource:jest.fn(async()=>b)},s=new OcrDemandTaxIntegrationService({getClient:()=>({from:()=>({insert})})} as any,cde as any,demand as any,undefined,reactive as any),t:any={organizationId:'org',userId:'actor',role:'gestor',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_CREATE,P.ORGANIZATION_CONTRACTS_UPDATE]};return {s,t,a,b,rows,insert,cde,demand,reactiveContext};
}
describe('Demand tax integration',()=>{
 it('prepares ICMS with five included bases and explicit unused exclusion; no amounts or rates',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);expect(p.evidenceReady).toBe(true);expect(p.declarations[0]).toMatchObject({included:5,excluded:1,canCreate:true});const before=JSON.stringify(x.rows[4]);await x.s.create('doc',x.t,{code:'ICMS',token:p.token});const row=x.insert.mock.calls[0][0][0];expect(row).toMatchObject({status:'DRAFT',supersedes_parameter_id:'ICMS',created_by:'actor',updated_by:'actor',amount_text:null,treatment:'INCLUDED'});expect(row.tax_basis.items[5]).toEqual({parameterId:'UNUSED',revision:2,operation:'EXCLUDE'});expect(JSON.stringify(x.rows[4])).toBe(before);await x.s.create('doc',x.t,{code:'ICMS',token:p.token});expect(x.insert).toHaveBeenCalledTimes(1);});
 it.each(['PIS','COFINS'])('includes both demand parcels for %s',async code=>{const x=setup(),p=await x.s.preview('doc',x.t);await x.s.create('doc',x.t,{code,token:p.token});expect(x.insert.mock.calls[0][0][0].tax_basis.items.every((i:any)=>i.operation==='INCLUDE')).toBe(true);});
 it.each(['amount_text','source','customer_id','organization_id','consumer_unit_id','start_date','status','measure','time_band','treatment'])('blocks incompatible demand tariff %s',async key=>{const x=setup();x.rows[7][key]='changed';const p=await x.s.preview('doc',x.t);expect(p.declarations.every(d=>!d.canCreate)).toBe(true);await expect(x.s.create('doc',x.t,{code:'ICMS',token:p.token})).rejects.toThrow();});
 it('blocks changed tax codes, extra tariffs and stale sources',async()=>{for(const kind of ['codes','extra','job','hash','review','approved','integration']){const x=setup();if(kind==='codes')x.rows[8].embedded_tax_codes=codes;if(kind==='extra')x.rows.push({...x.rows[7],id:'other'});if(kind==='job')x.b.source={...x.b.source,jobId:'changed'};if(kind==='hash')x.b.source={...x.b.source,doc:{...x.b.source.doc,file_hash:'changed'}};if(kind==='review')x.b.ready=false;if(kind==='approved')x.a.preview.bases[0].approved=false;if(kind==='integration')x.b.preview.state='READY';expect((await x.s.preview('doc',x.t)).declarations.every(d=>!d.canCreate)).toBe(true);}});
 it('preserves manual basis and conflicting tax declarations',async()=>{const x=setup();x.rows[4].tax_basis={version:1,items:[]};x.rows.push({...x.rows[5],id:'other'});const p=await x.s.preview('doc',x.t);expect(p.declarations[0].state).toBe('DECLARATION_REQUIRED');expect(p.declarations[1].state).toBe('CONFLICT');});
 it('blocks stale token, browser amounts and unauthorized writer',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.rows[4].notes='changed';await expect(x.s.create('doc',x.t,{code:'ICMS',token:p.token})).rejects.toThrow();await expect(x.s.create('doc',x.t,{code:'ICMS',token:p.token,amount:'1'})).rejects.toThrow();await expect(x.s.create('doc',{...x.t,permissions:[]},{code:'ICMS',token:p.token})).rejects.toThrow();await expect(x.s.create('doc',{...x.t,role:'operador'},{code:'ICMS',token:p.token})).rejects.toThrow();expect(x.insert).not.toHaveBeenCalled();});
 it('propagates source authorization and rejects altered proposed basis',async()=>{const x=setup();x.cde.taxIntegrationSource.mockRejectedValueOnce(Error('scope'));await expect(x.s.preview('doc',x.t)).rejects.toThrow('scope');const p=await x.s.preview('doc',x.t);await x.s.create('doc',x.t,{code:'ICMS',token:p.token});x.rows.at(-1).tax_basis.items[5].operation='INCLUDE';expect((await x.s.preview('doc',x.t)).declarations[0].state).toBe('REVIEW_REQUIRED');});
});

describe('CPFL reactive tax bases',()=>{
 function withReactive(){const x=setup();for(const band of ['PEAK','OFF_PEAK']){const id='reactive-'+band,source='reactive-row-'+band;x.rows.push({...x.rows[7],id,component_code:'REACTIVE',time_band:band,measure:'BRL_MWH',source:x.a.provenance+' · '+source});x.reactiveContext.candidates.push({band,source,rateMwh:'10'});x.reactiveContext.evidence.push({band,source,icms:'1.00',pis:'0.10',cofins:'0.20'});x.reactiveContext.preview.parameterIds.push(id);}return x;}
 it('adds both approved reactive bases without changing values or billing twice',async()=>{const x=withReactive(),p=await x.s.preview('doc',x.t);expect(p.declarations[0]).toMatchObject({canCreate:true,included:7,excluded:1});await x.s.create('doc',x.t,{code:'ICMS',token:p.token});expect(x.insert.mock.calls[0][0][0].tax_basis.items).toHaveLength(8);});
 it.each(['source','amount_text','status','measure','organization_id'])('rejects incompatible reactive %s',async key=>{const x=withReactive();x.rows[9][key]='wrong';expect((await x.s.preview('doc',x.t)).declarations.every(d=>!d.canCreate)).toBe(true);});
 it.each(['job','hash','evidence','integration','ready','ids'])('rejects missing/current reactive evidence %s',async key=>{const x=withReactive();if(key==='job')x.reactiveContext.source={...x.b.source,jobId:'other'};if(key==='hash')x.reactiveContext.source={...x.b.source,doc:{...x.b.source.doc,file_hash:'other'}};if(key==='evidence')x.reactiveContext.evidence[0].icms=null;if(key==='integration')x.reactiveContext.preview.state='READY';if(key==='ready')x.reactiveContext.ready=false;if(key==='ids')x.reactiveContext.preview.parameterIds=[];expect((await x.s.preview('doc',x.t)).declarations.every(d=>!d.canCreate)).toBe(true);});
});

it('accepts generic reactive OCR label only for the same document/hash/row',async()=>{const x=setup(),source='reactive-row';x.rows.push({...x.rows[7],id:'react',component_code:'REACTIVE',time_band:'PEAK',measure:'BRL_MWH',source:x.a.provenance.replace('OCR CPFL ·','OCR ·')+' · '+source});x.reactiveContext.candidates=[{band:'PEAK',source,rateMwh:'10'}];x.reactiveContext.evidence=[{band:'PEAK',source,icms:'1.00',pis:'0.10',cofins:'0.20'}];x.reactiveContext.preview.parameterIds=['react'];expect((await x.s.preview('doc',x.t)).declarations[0].canCreate).toBe(true);x.rows.at(-1).source+='wrong';expect((await x.s.preview('doc',x.t)).declarations[0].canCreate).toBe(false);});
