import {OcrDemandIntegrationService} from './ocr-demand-integration.service';
function setup(){
 const hash='a'.repeat(64);const reviews:any={fields:[{key:'a'.repeat(64),source:'row1',label:'Usada',period:'UNSPECIFIED',state:'BILLED_UNCLASSIFIED',unit:'kW',decimal:'234.64',sourceHash:hash,history:[{id:'review1',sourceHash:hash,decision:'USED'}]},{key:'b'.repeat(64),source:'row2',label:'Não usada',period:'UNSPECIFIED',state:'BILLED_UNCLASSIFIED',unit:'kW',decimal:'265.36',sourceHash:hash,history:[{id:'review2',sourceHash:hash,decision:'UNUSED'}]}]};
 const data:any={document_ocr_demand_integrations:null,document_ocr_monthly_integrations:{input_id:'monthly',source_snapshot:{month:'2026-08',measurements:{consumptionTotal:'1'}}},calculation_monthly_inputs:{id:'monthly',status:'DRAFT',revision:1,billed_demand:null,measurements:{consumptionTotal:'1'},unit_context:{tariff_group:'A',tariff_modality:'GREEN',free_market:true}}};const calls:any[]=[];
 const from=(table:string)=>{const q:any={};for(const method of ['select','eq'])q[method]=(...args:any[])=>{calls.push([table,method,...args]);return q;};q.maybeSingle=async()=>({data:data[table],error:null});return q;};
 const rpc:any=jest.fn(async()=>({data:{inputId:'monthly',alreadyIntegrated:false},error:null}));const monthly={preview:jest.fn(async()=>({})),canWrite:jest.fn(()=>true)};
 const service=new OcrDemandIntegrationService({getClient:()=>({from,rpc})} as any,monthly as any,{list:async()=>reviews} as any);const t:any={organizationId:'org',userId:'actor'};return {service,t,data,calls,rpc,reviews,monthly};
}
describe('Billed demand OCR integration',()=>{
 it('sends only server scope, review references and optimistic revision',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);expect(p.canCreate).toBe(true);expect(p.usedKw).toBe('234.6400');expect(p.unusedKw).toBe('265.3600');await s.service.create('doc',s.t,{token:p.token});expect(s.rpc).toHaveBeenCalledWith('integrate_ocr_billed_demand',{p_org:'org',p_document:'doc',p_actor:'actor',p_refs:expect.any(Object),p_revision:1});for(const table of Object.keys(s.data))expect(s.calls).toContainEqual([table,'eq','organization_id','org']);});
 it('honors permissions and entitlements before loading demand',async()=>{const s=setup();s.monthly.preview.mockRejectedValueOnce(new Error('license or permission'));await expect(s.service.preview('doc',s.t)).rejects.toThrow('license');s.monthly.canWrite.mockReturnValue(false);await expect(s.service.create('doc',s.t,{token:'a'.repeat(64)})).rejects.toThrow();expect(s.rpc).not.toHaveBeenCalled();});
 it.each(['BLUE','CONVENTIONAL'])('blocks unsupported modality %s',async tariff_modality=>{const s=setup();s.data.calculation_monthly_inputs.unit_context.tariff_modality=tariff_modality;expect((await s.service.preview('doc',s.t)).state).toBe('UNSUPPORTED');});
 it('preserves existing billed values, validated records and edited measurements',async()=>{for(const change of [{billed_demand:{}},{status:'VALIDATED'},{measurements:{consumptionTotal:'2'}}]){const s=setup();Object.assign(s.data.calculation_monthly_inputs,change);const p=await s.service.preview('doc',s.t);expect(p.state).toBe('RECORD_PRESERVED');await expect(s.service.create('doc',s.t,{token:p.token})).rejects.toThrow('substituído');expect(s.rpc).not.toHaveBeenCalled();}});
 it('requires prior consumption integration',async()=>{const s=setup();s.data.document_ocr_monthly_integrations=null;expect((await s.service.preview('doc',s.t)).state).toBe('CONSUMPTION_REQUIRED');});
 it('refuses stale evidence, pending decisions, invalid precision and time bands',async()=>{for(const change of [{sourceHash:'b'.repeat(64)},{history:[]},{decimal:'1.0000001'},{period:'PEAK'}]){const s=setup();Object.assign(s.reviews.fields[0],change);expect((await s.service.preview('doc',s.t)).canCreate).toBe(false);}});
 it('detects changed revision after preview',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);s.data.calculation_monthly_inputs.revision++;await expect(s.service.create('doc',s.t,{token:p.token})).rejects.toThrow('prévia mudou');expect(s.rpc).not.toHaveBeenCalled();});
 it('does not repeat a completed integration',async()=>{const s=setup();s.data.document_ocr_demand_integrations={input_id:'monthly'};expect(await s.service.create('doc',s.t,{token:'a'.repeat(64)})).toEqual({inputId:'monthly',alreadyIntegrated:true});expect(s.rpc).not.toHaveBeenCalled();});
 it('rejects browser values and actor',async()=>{const s=setup();for(const extra of [{value:'500'},{p_actor:'fake'},{revision:3}])await expect(s.service.create('doc',s.t,{token:'a'.repeat(64),...extra})).rejects.toThrow();expect(s.rpc).not.toHaveBeenCalled();});
 it('reports atomic conflict without claiming success',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);s.rpc.mockResolvedValueOnce({error:{code:'P4091'}});await expect(s.service.create('doc',s.t,{token:p.token})).rejects.toThrow('nenhum valor');});
});
