import {OcrResolutionService} from './ocr-resolution.service';
import {resolutionGroups,resolutionId,resolutionRateState} from './ocr-resolution-plan';
import {PERMISSIONS as P} from '../../common/constants/permissions';
function setup(){
 const t:any={userId:'operator',organizationId:'org-a',role:'operacional',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_UPDATE,P.ENERGIA_OCR_PROCESS]};
 const parameters={createPrepared:jest.fn(async(id:string,_dto:any,_org:string,_actor:string)=>({id})),update:jest.fn(async(id:string,d:any)=>({id,revision:d.revision+1})),approve:jest.fn(async()=>({}))},inputs={create:jest.fn(async(_dto:any,_tenant:any)=>({id:'new-monthly'})),update:jest.fn()},costs={create:jest.fn(async(_dto:any,_tenant:any)=>({id:'new-costs'})),update:jest.fn()},licenses={requireEntitlement:jest.fn(async()=>{})};
 const service=new OcrResolutionService({} as any,licenses as any,{} as any,{} as any,{} as any,{} as any,parameters as any,inputs as any,costs as any,{} as any,{} as any,{} as any);
 const c:any={token:'a'.repeat(64),evidenceToken:'b'.repeat(64),ready:true,source:{doc:{file_hash:'c'.repeat(64)}},unit:{id:'unit-a'},period:{start:'2026-08-01',end:'2026-08-31'},month:'2026-08',rates:[{label:'TUSD',state:'MISSING',component:'TUSD_ENERGY',band:'PEAK',amount:'981.92265',measure:'BRL_MWH',taxCodes:['ICMS','PIS','COFINS'],source:'verified OCR',line:'row6'}],taxes:[],provenance:'verified OCR',marker:'bot-energy source',input:{id:'validated-v2',status:'VALIDATED',revision:2},cost:{id:'cost-v2',status:'VALIDATED',revision:2,costs:{items:[{id:'acr-cip',scenario:'ACR',category:'OTHER',amount:'137.58'}]}},monthlyChanges:[{label:'reactiveBilledOffPeakKwh',before:'2320.1629',after:'2320.4823'}],measurements:{consumptionTotal:'77488.9800',demandSingle:'500',reactiveBilledOffPeakKwh:'2320.4823'},billed:{ACL:{used:'255.6000',unused:'244.4000',source:'verified OCR'},ACR:{used:'244.4',unused:'255.6',source:'manual'}},technical:{demand:[{meter:{decimal:'253.1123'}},{meter:{decimal:'255.6789'}}]},cip:{ready:true,amount:'137.58',source:'row11'},cipPresent:false,supplierPresent:false,documents:[{id:'nf-a',original_filename:'NFe.pdf',file_hash:'d'.repeat(64)}]};
 const context=jest.spyOn(service as any,'context').mockImplementation(async()=>c);jest.spyOn(service as any,'publicPlan').mockImplementation(()=>({token:c.token}));jest.spyOn(service,'inspect').mockImplementation(async()=>({token:c.token}) as any);
 const repair={token:c.token,checkedPdf:true,note:'Conferido no documento, página 1',taxes:false,monthly:true,costs:false,supplier:null,demandSource:'keep',copyDemandToAcr:false};
 return {service,c,t,parameters,inputs,costs,licenses,context,repair};
}
describe('Audited OCR resolution',()=>{
 it('denies other roles, global scope, missing permissions and expired licenses before writes',async()=>{for(const patch of [{role:'cliente'},{scope:'global'},{permissions:[]},{userId:''}]){const s=setup();await expect(s.service.prepare('doc',{...s.t,...patch},{token:s.c.token})).rejects.toThrow();expect(s.parameters.createPrepared).not.toHaveBeenCalled();}const s=setup();s.licenses.requireEntitlement.mockRejectedValueOnce(new Error('expired'));await expect(s.service.prepare('doc',s.t,{token:s.c.token})).rejects.toThrow('expired');});
 it('rejects stale tokens and browser supplied rates',async()=>{const s=setup();await expect(s.service.prepare('doc',s.t,{token:'f'.repeat(64)})).rejects.toThrow();await expect(s.service.prepare('doc',s.t,{token:s.c.token,amount:'0'})).rejects.toThrow();expect(s.parameters.createPrepared).not.toHaveBeenCalled();});
 it('automatically prepares only missing drafts with stable IDs and evidence; never approves',async()=>{const s=setup();s.c.rates.push({...s.c.rates[0],state:'CONFLICT',label:'Manual'}, {...s.c.rates[0],state:'PRESERVED',label:'Approved'});const result=await s.service.prepare('doc',s.t,{token:s.c.token});expect(s.parameters.createPrepared).toHaveBeenCalledTimes(1);expect(s.parameters.createPrepared).toHaveBeenCalledWith(resolutionId(['org-a','doc',s.c.source.doc.file_hash,'TUSD_ENERGY','PEAK']),expect.objectContaining({amount:'981.92265',treatment:'GROSS',embeddedTaxCodes:['ICMS','PIS','COFINS'],source:'verified OCR'}),'org-a','operator');expect(result.canPublish).toBe(false);expect(s.parameters.approve).not.toHaveBeenCalled();expect(s.inputs.create).toHaveBeenCalledWith(expect.objectContaining({previousId:'validated-v2',measurements:expect.objectContaining({demandSingle:'500',reactiveBilledOffPeakKwh:'2320.4823'}),notes:expect.stringContaining('aguarda conferência')}),s.t);expect(s.costs.create.mock.calls[0][0].costs.items).toHaveLength(2);expect(s.costs.create.mock.calls[0][0].costs.items.some((i:any)=>i.category==='SUPPLIER_INVOICE')).toBe(false);expect(s.inputs.update).not.toHaveBeenCalled();expect(s.costs.update).not.toHaveBeenCalled();});
 it('stops on partial failure and does not create taxes or retry uncertain writes',async()=>{const s=setup();s.parameters.createPrepared.mockRejectedValueOnce(new Error('timeout'));s.c.taxes=[{code:'COFINS',existing:[],bases:[{parameterId:'rate',revision:1,operation:'INCLUDE'}]}];const result=await s.service.prepare('doc',s.t,{token:s.c.token});expect(result.receipts).toContainEqual(expect.objectContaining({state:'VERIFY_REQUIRED'}));expect(s.parameters.createPrepared).toHaveBeenCalledTimes(1);});
 it('stops when evidence changes during a batch',async()=>{const s=setup();s.context.mockResolvedValueOnce(s.c).mockResolvedValueOnce({...s.c,evidenceToken:'changed'});const result=await s.service.prepare('doc',s.t,{token:s.c.token});expect(result.receipts.some((r:any)=>r.state==='VERIFY_REQUIRED')).toBe(true);});
 it('links included taxes only to fresh pinned bases, without an additional rate',async()=>{const s=setup();s.c.rates=[];s.c.taxes=[{code:'COFINS',existing:[],bases:[{parameterId:'approved-or-draft-rate',revision:2,operation:'INCLUDE'}]},{code:'ICMS',existing:[{id:'manual'}],bases:[{parameterId:'x',revision:1}]}];await s.service.prepare('doc',s.t,{token:s.c.token});expect(s.parameters.createPrepared).toHaveBeenCalledTimes(1);expect(s.parameters.createPrepared.mock.calls[0][1]).toMatchObject({kind:'TAX',componentCode:'COFINS',amount:null,treatment:'INCLUDED',taxBasis:{items:s.c.taxes[0].bases}});});
 it('does not overwrite existing monthly or cost drafts during automatic preparation',async()=>{const s=setup();s.c.input.status='DRAFT';s.c.cost.status='DRAFT';await s.service.prepare('doc',s.t,{token:s.c.token});expect(s.inputs.create).not.toHaveBeenCalled();expect(s.inputs.update).not.toHaveBeenCalled();expect(s.costs.create).not.toHaveBeenCalled();expect(s.costs.update).not.toHaveBeenCalled();});
 it('refreshes scope after preparation and stops a monthly failure before cost creation',async()=>{const s=setup();s.inputs.create.mockRejectedValueOnce(new Error('concurrent draft'));const r=await s.service.prepare('doc',s.t,{token:s.c.token});expect(r.receipts.some((v:any)=>v.state==='VERIFY_REQUIRED')).toBe(true);expect(s.costs.create).not.toHaveBeenCalled();});
 it('skips already prepared revisions on a fresh retry',async()=>{const s=setup();await s.service.prepare('doc',s.t,{token:s.c.token});s.c.input.status='DRAFT';s.c.cost.status='DRAFT';s.c.rates=[];await s.service.prepare('doc',s.t,{token:s.c.token});expect(s.inputs.create).toHaveBeenCalledTimes(1);expect(s.costs.create).toHaveBeenCalledTimes(1);});
 it('requires human evidence confirmation and preserves validated originals and ACR',async()=>{const s=setup();await expect(s.service.repair('doc',s.t,{...s.repair,checkedPdf:false})).rejects.toThrow();await s.service.repair('doc',s.t,s.repair);const dto=s.inputs.create.mock.calls[0][0];expect(dto.previousId).toBe('validated-v2');expect(dto.measurements.demandSingle).toBe('500');expect(dto.billedDemand.ACR).toEqual(s.c.billed.ACR);expect(s.inputs.update).not.toHaveBeenCalled();expect(s.c.input.status).toBe('VALIDATED');expect(s.parameters.approve).not.toHaveBeenCalled();});
 it('uses the highest measured value only on explicit selection; ACR copy remains explicit',async()=>{const s=setup();await s.service.repair('doc',s.t,{...s.repair,demandSource:'meter',copyDemandToAcr:true});expect(s.inputs.create.mock.calls[0][0]).toMatchObject({measurements:{demandSingle:'255.6789',demandPeak:null,demandOffPeak:null},billedDemand:{ACR:{used:'255.6000',unused:'244.4000'}}});const bad=setup();bad.c.technical.demand[1].meter=null;const result=await bad.service.repair('doc',bad.t,{...bad.repair,demandSource:'meter'});expect(result.receipts[0].state).toBe('VERIFY_REQUIRED');expect(bad.inputs.create).not.toHaveBeenCalled();});
 it('preserves other manual drafts and annual tax periods',async()=>{const s=setup();s.c.input.status='DRAFT';s.c.input.source_reference='manual';await s.service.repair('doc',s.t,s.repair);expect(s.inputs.update).not.toHaveBeenCalled();const tax=setup();tax.c.taxes=[{code:'ICMS',bases:[{parameterId:'r',revision:1}],existing:[{id:'tax',status:'DRAFT',start_date:'2026-01-01',end_date:'2026-12-31'}]}];await tax.service.repair('doc',tax.t,{...tax.repair,taxes:true});expect(tax.parameters.update).not.toHaveBeenCalled();expect(tax.inputs.create).not.toHaveBeenCalled();});
 it('preserves existing costs; only a confirmed same-unit NF can add supplier cost',async()=>{const s=setup();await s.service.repair('doc',s.t,{...s.repair,monthly:false,costs:true,supplier:{documentId:'nf-a',amount:'11772.90',taxTreatment:'EXCLUDED'}});const dto=s.costs.create.mock.calls[0][0];expect(dto.previousId).toBe('cost-v2');expect(dto.costs.items[0]).toEqual(s.c.cost.costs.items[0]);expect(dto.costs.items).toHaveLength(3);expect(dto.costs.items[2].source).toContain('conferido pelo operador');expect(s.costs.update).not.toHaveBeenCalled();for(const documentId of ['foreign-nf','']){const x=setup();await x.service.repair('doc',x.t,{...x.repair,monthly:false,costs:true,supplier:{documentId,amount:'11772.90',taxTreatment:'EXCLUDED'}});expect(x.costs.create).not.toHaveBeenCalled();}});
 it('does not invent supplier costs when the operator has not selected the NF',async()=>{const s=setup();await s.service.repair('doc',s.t,{...s.repair,monthly:false,costs:true});expect(s.costs.create.mock.calls[0][0].costs.items.some((i:any)=>i.category==='SUPPLIER_INVOICE')).toBe(false);});
 it('rejects operator approval even with all contract permissions',async()=>{const s=setup();await expect(s.service.approve('doc',s.t,{token:s.c.token,acknowledged:true})).rejects.toThrow('Gestor');expect(s.parameters.approve).not.toHaveBeenCalled();});
 it('manager approval requires repaired taxes before any rate is approved',async()=>{const s=setup();s.t.role='gestor';s.t.permissions.push(P.ORGANIZATION_CONTRACTS_CREATE);s.c.rates[0]={...s.c.rates[0],state:'PRESERVED',existing:{id:'rate',revision:1,status:'DRAFT'}};s.c.taxes=[{code:'ICMS',existing:[{status:'DRAFT',source:'manual',treatment:'INSIDE'}]}];const result=await s.service.approve('doc',s.t,{token:s.c.token,acknowledged:true});expect(result.receipts[0].state).toBe('VERIFY_REQUIRED');expect(s.parameters.approve).not.toHaveBeenCalled();});
 it('manager approves reviewed parameters with refreshed revisions; never publishes settlement',async()=>{const s=setup();s.t.role='gestor';s.t.permissions.push(P.ORGANIZATION_CONTRACTS_CREATE);s.c.rates[0]={...s.c.rates[0],state:'PRESERVED',existing:{id:'rate',revision:1,status:'DRAFT'}};s.c.taxes=[{code:'ICMS',bases:[{parameterId:'rate',revision:2,operation:'INCLUDE'}],existing:[{id:'tax',status:'DRAFT',revision:1,source:s.c.provenance,notes:s.c.marker,treatment:'INCLUDED'}]}];await s.service.approve('doc',s.t,{token:s.c.token,acknowledged:true});expect(s.parameters.approve.mock.calls).toEqual([['rate',{revision:1},'org-a','operator'],['tax',{revision:2},'org-a','operator']]);expect(s.inputs.create).not.toHaveBeenCalled();expect(s.costs.create).not.toHaveBeenCalled();});
});
describe('Resolution source preservation',()=>{
 const candidate={component:'TUSD_ENERGY',band:'PEAK',amount:'981.92265',measure:'BRL_MWH',source:'original SHA row6',taxCodes:['ICMS']};
 const row={kind:'TARIFF',scenario:'ACL',component_code:'TUSD_ENERGY',time_band:'PEAK',amount_text:'981.92265',measure:'BRL_MWH',source:candidate.source,embedded_tax_codes:['ICMS'],treatment:'GROSS',start_date:'2026-08-01',end_date:'2026-08-31',status:'APPROVED',unit_context:{state:'SP'}};
 it('recognizes only exact source, period, unit context and tax content; conflicts are preserved',()=>{expect(resolutionRateState(candidate,[],'2026-08-01','2026-08-31').state).toBe('MISSING');expect(resolutionRateState(candidate,[row],'2026-08-01','2026-08-31',{state:'SP'}).state).toBe('PRESERVED');for(const patch of [{source:'other'},{end_date:'2026-12-31'},{amount_text:'0'},{unit_context:{state:'RJ'}}])expect(resolutionRateState(candidate,[{...row,...patch}],'2026-08-01','2026-08-31',{state:'SP'}).state).toBe('CONFLICT');expect(resolutionRateState(candidate,[row,row],'2026-08-01','2026-08-31').state).toBe('CONFLICT');});
 it('retains every finding, including symptoms, in grouped UI',()=>{const findings=Array.from({length:14},(_,i)=>({code:String(i),section:['Parâmetros','Medições','Custos mensais','Other'][i%4]}));expect(resolutionGroups(findings).flatMap(g=>g.findings)).toHaveLength(14);expect(new Set(resolutionGroups(findings).flatMap(g=>g.findings.map(f=>f.code))).size).toBe(14);});
});

describe('Automatic omitted exclusion revision',()=>{
 it('creates an audited linked draft and leaves the approved tax unchanged',async()=>{
  const s=setup();s.c.rates=[{state:'PRESERVED',component:'TUSD_DEMAND_UNUSED',existing:{id:'unused',revision:3}}];s.c.input.status='DRAFT';s.c.cost.status='DRAFT';
  const old={id:'tax',revision:4,status:'APPROVED',source:s.c.provenance,notes:s.c.marker,treatment:'INCLUDED',start_date:s.c.period.start,end_date:s.c.period.end,tax_basis:{version:1,items:[{parameterId:'used',revision:2,operation:'INCLUDE'}]}};
  s.c.taxes=[{code:'ICMS',existing:[old],bases:[...old.tax_basis.items,{parameterId:'unused',revision:3,operation:'EXCLUDE'}]}];
  const insert=jest.fn((_rows:any[])=>({select:()=>({single:async()=>({data:{id:'next'},error:null})})}));(s.service as any).db={getClient:()=>({from:()=>({insert})})};
  const before=JSON.stringify(old),result=await s.service.prepare('doc',s.t,{token:s.c.token});
  expect(insert.mock.calls[0][0][0]).toMatchObject({supersedes_parameter_id:'tax',status:'DRAFT',created_by:'operator',treatment:'INCLUDED',tax_basis:{items:s.c.taxes[0].bases}});
  expect(JSON.stringify(old)).toBe(before);expect(result.canPublish).toBe(false);expect(s.parameters.approve).not.toHaveBeenCalled();expect(result.receipts[0].state).toBe('SAVED_DRAFT');
 });
});
