import {resolutionTaxBases,missingTaxExclusions,currentResolutionTaxes} from './ocr-resolution-plan';
describe('Complete embedded tax declarations without inventing incidence',()=>{
 const rates=[{state:'PRESERVED',existing:{id:'used',revision:2},taxCodes:['ICMS','PIS','COFINS']},{state:'PRESERVED',component:'TUSD_DEMAND_UNUSED',existing:{id:'unused',revision:3},taxCodes:['PIS','COFINS']},{state:'CONFLICT',existing:{id:'manual',revision:1},taxCodes:['ICMS']}];
 const c={rates,provenance:'OCR source',marker:'bot document hash',period:{start:'2026-08-01',end:'2026-08-31'}};
 const old={id:'tax',status:'APPROVED',source:c.provenance,notes:c.marker,treatment:'INCLUDED',start_date:c.period.start,end_date:c.period.end,tax_basis:{version:1,items:[{parameterId:'used',revision:2,operation:'INCLUDE'}]}};
 const bases=resolutionTaxBases('ICMS',rates);
 it('excludes unused demand explicitly and preserves PIS/COFINS inclusion',()=>{expect(bases).toEqual([{parameterId:'used',revision:2,operation:'INCLUDE'},{parameterId:'unused',revision:3,operation:'EXCLUDE'}]);expect(resolutionTaxBases('PIS',rates).every(b=>b.operation==='INCLUDE')).toBe(true);});
 it('proposes only missing exclusions on bot-owned, unchanged approved sources',()=>{expect(missingTaxExclusions({code:'ICMS',existing:[old],bases},c)).toBe(true);for(const patch of [{amount_text:'18'},{source:'manual'},{status:'DRAFT'},{end_date:'2026-12-31'},{tax_basis:{version:1,items:[{parameterId:'used',revision:1,operation:'INCLUDE'}]}}])expect(missingTaxExclusions({code:'ICMS',existing:[{...old,...patch}],bases},c)).toBe(false);expect(missingTaxExclusions({code:'ICMS',existing:[old,old],bases},c)).toBe(false);expect(missingTaxExclusions({code:'ICMS',existing:[old],bases:[...bases,{parameterId:'new-taxable',revision:1,operation:'INCLUDE'}]},c)).toBe(false);});
 it('recognizes the exact successor draft, preserving manual conflicts and duplicate declarations',()=>{const draft={...old,id:'next',status:'DRAFT',supersedes_parameter_id:old.id,source:c.provenance+' · exclusões completadas do parâmetro '+old.id,tax_basis:{version:1,items:bases}};expect(currentResolutionTaxes([old,draft],bases,c.provenance,c.marker)).toEqual([draft]);for(const patch of [{supersedes_parameter_id:'foreign'},{source:'manual'},{tax_basis:{version:1,items:[bases[0]]}}])expect(currentResolutionTaxes([old,{...draft,...patch}],bases,c.provenance,c.marker)).toHaveLength(2);expect(currentResolutionTaxes([old,draft,draft],bases,c.provenance,c.marker)).toHaveLength(3);expect(old.status).toBe('APPROVED');});
});
