import {OcrMonthlyIntegrationService} from './ocr-monthly-integration.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
function setup(){
 const f=(key:string)=>({key,label:key,state:'EXTRACTED_REVIEW',sourceHash:'a'.repeat(64),decimal:'1',unit:'kWh',history:[{id:key,sourceHash:'a'.repeat(64),decision:'CONFIRMED',version:1,author:'Reviewer',createdAt:'2026-09-27'}]});
 const identity={fields:['customer','taxId','unit','address','period','market'].map(f)},consumption={fields:['consumptionPeakKwh','consumptionOffPeakKwh','consumptionTotalKwh'].map(f)};
 const data:any={document_ocr_monthly_integrations:null,calculation_monthly_inputs:[]};const calls:any[]=[];
 const from=(table:string)=>{const q:any={};for(const method of ['select','eq','order','limit'])q[method]=jest.fn((...args:any[])=>{calls.push([table,method,...args]);return q;});q.maybeSingle=async()=>({data:data[table],error:null});q.then=(resolve:any)=>resolve({data:data[table],error:null});return q;};
 const rpc:any=jest.fn(async()=>({data:{inputId:'monthly',status:'DRAFT',alreadyIntegrated:false},error:null}));
 const license={requireEntitlement:jest.fn(async()=>{})};const source={doc:{id:'doc',consumer_unit_id:'unit',reference_month:'2026-08-01',file_hash:'a'.repeat(64)},jobId:'job'};
 const queue={reviewSource:jest.fn(async()=>source)};const service=new OcrMonthlyIntegrationService({getClient:()=>({from,rpc})} as any,license as any,queue as any,{list:async()=>identity} as any,{list:async()=>consumption} as any);
 const t:any={organizationId:'org',userId:'actor',role:'gestor',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_CREATE]};return {service,t,data,calls,rpc,identity,consumption,license,queue};
}
describe('OCR monthly integration',()=>{
 it('uses current reviews and server scope, never browser values',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);expect(p.canCreate).toBe(true);await s.service.create('doc',s.t,{token:p.token});expect(s.rpc).toHaveBeenCalledWith('integrate_ocr_monthly',expect.objectContaining({p_org:'org',p_document:'doc',p_actor:'actor'}));expect(s.rpc.mock.calls[0][1]).not.toHaveProperty('measurements');for(const table of ['document_ocr_monthly_integrations','calculation_monthly_inputs'])expect(s.calls).toContainEqual([table,'eq','organization_id','org']);});
 it('refuses changed evidence after preview',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);s.consumption.fields[0].sourceHash='b'.repeat(64);await expect(s.service.create('doc',s.t,{token:p.token})).rejects.toThrow('prévia mudou');expect(s.rpc).not.toHaveBeenCalled();});
 it('preserves existing manual drafts and validated records',async()=>{for(const status of ['DRAFT','VALIDATED']){const s=setup();s.data.calculation_monthly_inputs=[{id:'existing',status}];const p=await s.service.preview('doc',s.t);expect(p.state).toBe('EXISTING_RECORD');await expect(s.service.create('doc',s.t,{token:p.token})).rejects.toThrow('Já existe');expect(s.rpc).not.toHaveBeenCalled();}});
 it('returns existing integration without another write',async()=>{const s=setup();s.data.document_ocr_monthly_integrations={input_id:'existing',created_at:'2026-09-27'};expect(await s.service.create('doc',s.t,{token:'b'.repeat(64)})).toEqual({inputId:'existing',alreadyIntegrated:true});expect(s.rpc).not.toHaveBeenCalled();});
 it('denies operator, missing permission and missing scope',async()=>{const s=setup();for(const t of [{...s.t,role:'operador'},{...s.t,permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW]},{...s.t,organizationId:''}])await expect(s.service.create('doc',t,{token:'a'.repeat(64)})).rejects.toThrow();expect(s.rpc).not.toHaveBeenCalled();});
 it('enforces read permission and license',async()=>{const s=setup();await expect(s.service.preview('doc',{...s.t,permissions:[P.DOCUMENTS_VIEW]})).rejects.toThrow();s.license.requireEntitlement.mockRejectedValueOnce(new Error('license'));await expect(s.service.preview('doc',s.t)).rejects.toThrow('license');});
 it.each(['NEEDS_CORRECTION','UNKNOWN'])('blocks %s decision',async decision=>{const s=setup();s.identity.fields[0].history[0].decision=decision;expect((await s.service.preview('doc',s.t)).canCreate).toBe(false);});
 it('rejects client supplied measurements or scope',async()=>{const s=setup();for(const extra of [{measurements:{}},{organizationId:'other'},{actor:'fake'}])await expect(s.service.create('doc',s.t,{token:'a'.repeat(64),...extra})).rejects.toThrow();expect(s.rpc).not.toHaveBeenCalled();});
 it('surfaces transactional conflict',async()=>{const s=setup(),p=await s.service.preview('doc',s.t);s.rpc.mockResolvedValueOnce({data:null,error:{code:'P4090'}});await expect(s.service.create('doc',s.t,{token:p.token})).rejects.toThrow('conferências mudaram');});
});

describe('Measurement readiness access',()=>{it('reuses entitlements and organization/unit/month scope without writes',async()=>{const s=setup();const r=await s.service.measurementReadiness('doc',s.t);expect(r.canImport).toBe(false);expect(r.monthly).toBeNull();expect(s.calls).toContainEqual(['calculation_monthly_inputs','eq','organization_id','org']);expect(s.calls).toContainEqual(['calculation_monthly_inputs','eq','consumer_unit_id','unit']);expect(s.calls).toContainEqual(['calculation_monthly_inputs','eq','month','2026-08']);expect(s.rpc).not.toHaveBeenCalled();});it('denies missing contract permissions',async()=>{const s=setup();await expect(s.service.measurementReadiness('doc',{...s.t,permissions:[P.DOCUMENTS_VIEW]})).rejects.toThrow();expect(s.queue.reviewSource).not.toHaveBeenCalled();});});
