import {OcrIdentityReviewService,identityReviewInput,identityReviewDigest} from './ocr-identity-review.service';
import {OcrController} from './ocr.controller';
import {PERMISSIONS_KEY} from '../../common/decorators/require-permission.decorator';
import {PERMISSIONS} from '../../common/constants/permissions';
import 'reflect-metadata';
const input=()=>({fieldKey:'address',sourceHash:'a'.repeat(64),decision:'CONFIRMED',note:'Conferido no PDF',expectedReviewId:null,requestId:'00000000-0000-4000-8000-000000000001',checkedPdf:true});
describe('OCR review validation',()=>{
 it('requires write permission independently of view',()=>{expect(Reflect.getMetadata(PERMISSIONS_KEY,OcrController.prototype.identityReviewCreate)).toEqual([PERMISSIONS.ENERGIA_OCR_PROCESS]);expect(Reflect.getMetadata(PERMISSIONS_KEY,OcrController.prototype.identityReviewList)).toEqual([PERMISSIONS.DOCUMENTS_VIEW]);});
 it('accepts explicit PDF confirmation',()=>expect(identityReviewInput(input()).decision).toBe('CONFIRMED'));
 it.each([{checkedPdf:false},{fieldKey:'taxRate'},{requestId:'invalid'},{sourceHash:'bad'},{expectedReviewId:'bad'},{decision:'APPROVED'},{note:23},{note:'a'.repeat(501)},{organizationId:'foreign'}])('rejects invalid input %j',patch=>expect(()=>identityReviewInput({...input(),...patch})).toThrow());
 it('requires a correction reason',()=>{expect(()=>identityReviewInput({...input(),decision:'NEEDS_CORRECTION',note:' '})).toThrow();expect(identityReviewInput({...input(),decision:'NEEDS_CORRECTION',note:' Conferir unidade ',checkedPdf:true}).note).toBe('Conferir unidade');});
 it('hashes canonical JSON including decimal precision',()=>{expect(identityReviewDigest({b:2,a:1})).toBe(identityReviewDigest({a:1,b:2}));expect(identityReviewDigest({value:'1.00'})).not.toBe(identityReviewDigest({value:'1.01'}));});
});
function setup(){const q:any={select:jest.fn(()=>q),eq:jest.fn(()=>q),order:jest.fn(()=>q),limit:jest.fn(async()=>({data:[],error:null})),maybeSingle:jest.fn(async()=>({data:null,error:null})),single:jest.fn(),insert:jest.fn(()=>q)};const client={from:jest.fn(()=>q)};const service=new OcrIdentityReviewService({getClient:()=>client} as any,{} as any);const snapshot={field:{key:'address',decimal:'12.00',unit:'kWh',state:'EXTRACTED_REVIEW'}};const hash=identityReviewDigest(snapshot);const context={doc:{id:'doc',file_hash:'f'.repeat(64)},jobId:'00000000-0000-4000-8000-000000000002',fields:[{field:snapshot.field,snapshot,sourceHash:hash}]};jest.spyOn(service as any,'context').mockResolvedValue(context);const row:any={id:'00000000-0000-4000-8000-000000000003',organization_id:'org',document_id:'doc',field_key:'address',source_hash:hash,source_snapshot:snapshot,decision:'CONFIRMED',note:'Conferido no PDF',created_by:'actor',version:1,created_at:'2026-09-26T00:00:00Z'};q.single.mockResolvedValue({data:row,error:null});return {service,q,client,context,row,data:{...input(),sourceHash:hash}};}
describe('OCR review persistence boundaries',()=>{
 it('allows operator field validation without financial approval',async()=>{const s=setup();await s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'operacional'},s.data);expect(s.q.insert).toHaveBeenCalledWith(expect.objectContaining({created_by:'actor',decision:'CONFIRMED'}));});
 it('saves server snapshot and authenticated actor, never a supplied value',async()=>{const s=setup();const result=await s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data);expect(s.q.insert).toHaveBeenCalledWith(expect.objectContaining({organization_id:'org',created_by:'actor',source_snapshot:s.context.fields[0].snapshot}));expect(result.canImport).toBe(false);});
 it('rejects stale preview without writes',async()=>{const s=setup();await expect(s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},{...s.data,sourceHash:'b'.repeat(64)})).rejects.toThrow('prévia mudou');expect(s.q.insert).not.toHaveBeenCalled();});
 it('rejects confirming a conflicting candidate',async()=>{const s=setup();s.context.fields[0].field.state='CONFLICT';await expect(s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data)).rejects.toThrow('divergente');});
 it('keeps idempotent replay without duplicate insertion',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValue({data:s.row,error:null});await s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data);expect(s.q.insert).not.toHaveBeenCalled();});
 it('rejects reusing request for another actor',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValue({data:s.row,error:null});await expect(s.service.create('org','doc',{userId:'other',organizationId:'org',role:'gestor'},s.data)).rejects.toThrow('outra conferência');});
 it('rejects altered stored evidence',async()=>{const s=setup();s.row.source_snapshot.field.decimal='99';await expect(s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data)).rejects.toThrow('integridade');});
 it('reports concurrent update without pretending success',async()=>{const s=setup();s.q.single.mockResolvedValue({data:null,error:{code:'40001'}});await expect(s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data)).rejects.toThrow('Outro usuário');});
 it('handles unique-request race as idempotent replay',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValueOnce({data:null,error:null}).mockResolvedValueOnce({data:s.row,error:null});s.q.single.mockResolvedValue({data:null,error:{code:'23505'}});expect((await s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data)).review.id).toBe(s.row.id);});
 it('fails closed if source cannot be verified',async()=>{const s=setup();(s.service as any).context.mockRejectedValue(new Error('source'));await expect(s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data)).rejects.toThrow('source');expect(s.q.insert).not.toHaveBeenCalled();});
 it('scopes history by organization, document and field',async()=>{const s=setup();await s.service.list('org','doc');for(const pair of [['organization_id','org'],['document_id','doc'],['field_key','address']])expect(s.q.eq).toHaveBeenCalledWith(...pair);});
});

describe('identity review eligibility and source binding',()=>{
 const setupContext=(patch:any={})=>{
 const base={key:'address',label:'Endereço',expected:'Rua Um 10',comparison:'EQUAL',state:'REVIEW',message:'Conferir',candidates:[{text:'RUA UM 10',source:'page1',pages:[1],confidence:null,issues:['MISSING_CONFIDENCE']}]};
 const identity={context:jest.fn(async()=>({source:{doc:{id:'doc',customer_id:'c',consumer_unit_id:'u',reference_month:'2026-08-01',file_hash:'a'.repeat(64)},jobId:'job'},registration:{customer:{company_name:'A'},unit:{address:'Rua Um 10'}},preview:{registrationAvailable:true,duplicate:false,checks:[base],...patch}}))};
 return {identity,service:new OcrIdentityReviewService({} as any,identity as any),base};
 };
 it('permits explicit human review of equal text with missing OCR confidence',async()=>{const s=setupContext();const c=await (s.service as any).context('org','doc');expect(c.fields[0].field.state).toBe('EXTRACTED_REVIEW');expect(c.fields[0].field.check.candidates[0].confidence).toBeNull();expect(c.fields[0].snapshot.registration.unit.address).toBe('Rua Um 10');});
 it.each(['MISMATCH','AMBIGUOUS','MISSING','REGISTRATION_MISSING'])('blocks %s',async state=>{const s=setupContext();s.base.state=state;const c=await(s.service as any).context('org','doc');expect(c.fields[0].field.state).toBe('BLOCKED');});
 it('blocks duplicate documents',async()=>{const s=setupContext({duplicate:true});expect((await(s.service as any).context('org','doc')).fields[0].field.state).toBe('BLOCKED');});
 it.each(['UNVERIFIED_SOURCE','CONFIDENCE_BELOW_45','MISSING_VALUE'])('blocks unresolved issue %s',async issue=>{const s=setupContext();s.base.candidates[0].issues=[issue];expect((await(s.service as any).context('org','doc')).fields[0].field.state).toBe('BLOCKED');});
 it('blocks missing page evidence',async()=>{const s=setupContext();s.base.candidates[0].pages=[];expect((await(s.service as any).context('org','doc')).fields[0].field.state).toBe('BLOCKED');});
 it('changes digest when current registration changes',async()=>{const s=setupContext();const a=await(s.service as any).context('org','doc');s.identity.context.mockImplementation(async()=>({...await setupContext().identity.context(),registration:{customer:{company_name:'B'},unit:{address:'Rua Um 10'}}}));const b=await(s.service as any).context('org','doc');expect(a.fields[0].sourceHash).not.toBe(b.fields[0].sourceHash);});
 it('rejects disallowed role and foreign tenant before any source query',async()=>{const s=setupContext();for(const t of [{userId:'a',organizationId:'org',role:'cliente'},{userId:'a',organizationId:'other',role:'gestor'}])await expect(s.service.create('org','doc',t,input())).rejects.toThrow('Gestor');expect(s.identity.context).not.toHaveBeenCalled();});
});

function cpflIdentityFixture(){const candidate=(text:string,confidence:number|null=null,issues:string[]=['MISSING_CONFIDENCE'])=>({text,confidence,issues,source:'page1',pages:[1]});const tax={key:'taxId',expected:'11222333000181',comparison:'EQUAL',state:'REVIEW',candidates:[candidate('11.222.333/0001-81',0.431,['CONFIDENCE_BELOW_45']),candidate('11.222.333/0001-81')]};return {layoutId:'cpfl-paulista-a',registrationAvailable:true,duplicate:false,checks:[tax,...['customer','unit','address','period','market'].map(key=>({key,comparison:'EQUAL',state:'REVIEW',expected:'fixture',candidates:[candidate('fixture')]}))]};}

describe('CPFL CNPJ review service integration',()=>{
 it('binds all identity anchors and original confidence into the audit hash',async()=>{const p=cpflIdentityFixture();const identity={context:jest.fn(async()=>({source:{doc:{id:'doc',customer_id:'c',consumer_unit_id:'u',reference_month:'2026-08-01',file_hash:'a'.repeat(64)},jobId:'job'},registration:{customer:{document:'11222333000181'},unit:{}},preview:p}))};const service=new OcrIdentityReviewService({} as any,identity as any);const a=await(service as any).context('org','doc');expect(a.fields[0].field.state).toBe('EXTRACTED_REVIEW');expect(a.fields[0].field.check.candidates[0].confidence).toBe(.431);expect(a.fields[0].field.attestation.policy).toBe('cpfl-complete-tax-id-attestation-v1');p.checks[1].candidates[0].source='page2';const b=await(service as any).context('org','doc');expect(b.fields[0].sourceHash).not.toBe(a.fields[0].sourceHash);});
 it('requires a substantial justification for attested confirmation',async()=>{const s=setup();(s.context.fields[0].field as any).attestation={mode:'COMPLETE_TAX_ID_LOW_CONFIDENCE'};await expect(s.service.create('org','doc',{userId:'actor',organizationId:'org',role:'gestor'},s.data)).rejects.toThrow('20 caracteres');expect(s.q.insert).not.toHaveBeenCalled();});
});
