import {OcrResolutionService} from './ocr-resolution.service';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {reactiveParameterCandidates} from './reactive-parameter-candidates';
import {loadDemandFinancialMemory} from '../contracts/services/demand-financial-memory';
import {cipCostCandidate} from './cip-cost-candidate';
import {PERMISSIONS as P} from '../../common/constants/permissions';
jest.mock('./cpfl-paulista-layout',()=>({extractCpflPaulistaLayout:jest.fn()}));
jest.mock('./reactive-parameter-candidates',()=>({reactiveParameterCandidates:jest.fn()}));
jest.mock('./cip-cost-candidate',()=>({cipCostCandidate:jest.fn()}));
jest.mock('../contracts/services/demand-financial-memory',()=>({loadDemandFinancialMemory:jest.fn()}));
function setup(){
 const field=(key:string,decimal='11807.0400')=>({key,decimal,state:'EXTRACTED_REVIEW',sourceHash:'f'.repeat(64),history:[{version:1,sourceHash:'f'.repeat(64),decision:'CONFIRMED'}]});
 const identity={fields:['customer','taxId','unit','address','period','market'].map(k=>field(k))},consumption={fields:['consumptionPeakKwh','consumptionOffPeakKwh','consumptionTotalKwh'].map(k=>field(k))};
 const highlight={decimal:'1.00',issues:[]};
 const operations=['tusd','cde','reactive','used','unused'].map(source=>({source,fields:{pisAmount:highlight,cofinsAmount:highlight,...(source!=='unused'?{icmsAmount:highlight}:{})}}));
 (extractCpflPaulistaLayout as jest.Mock).mockReturnValue({layoutId:'cpfl-paulista-a',fields:[{name:'reference',value:{text:'AGO/2026'}}],operations,reconciliation:{state:'MATCH'}});
 (reactiveParameterCandidates as jest.Mock).mockReturnValue([{ready:true,band:'OFF_PEAK',rateMwh:'375.93047',quantity:'2320.4823',source:'reactive'}]);
 (cipCostCandidate as jest.Mock).mockReturnValue({ready:true,amount:'137.58',source:'cip'});
 (loadDemandFinancialMemory as jest.Mock).mockResolvedValue({state:'RECONCILED',rows:[{classification:'USED',rate:'10.70899844',quantity:'255.6000',source:'used'},{classification:'UNUSED',rate:'8.78138298',quantity:'244.4000',source:'unused'}]});
 const unit={id:'unit',customer_id:'customer',status:'ACTIVE',free_market:true,tariff_group:'A',tariff_modality:'GREEN',distributor:'CPFL',state:'SP'},captured:any={unit,parameters:[],monthly:[{id:'v2',version:2,status:'VALIDATED',measurements:{demandSingle:'500',reactiveBilledOffPeakKwh:'2320.1629'},billed_demand:{ACR:{used:'244.4',unused:'255.6'}}}],monthlyCosts:[{version:2,status:'VALIDATED',costs:{items:[{scenario:'ACR',category:'OTHER',amount:'137.58'}]}}]},calls:any[]=[];
 const documents=[{id:'nf',document_type:'INVOICE_SUPPLIER',file_verified:true,file_hash:'d'.repeat(64),original_filename:'NFe.pdf'}];
 const from=(table:string)=>{const q:any={};for(const k of ['select','eq','limit'])q[k]=(...a:any[])=>{calls.push([table,k,...a]);return q;};q.then=(resolve:any)=>resolve({data:documents,error:null});return q;};
 const source={doc:{id:'doc',consumer_unit_id:'unit',customer_id:'customer',file_hash:'a'.repeat(64),reference_month:'2026-08-01'},jobId:'job',raw:{}};
 const preview=(source:string)=>({state:'EXISTING_RECORD',candidates:[{ready:true,band:'PEAK',quantity:'11807.0400',rateMwh:'981.92265',source}]});
 const parameters={createPrepared:jest.fn(async(id:string,d:any)=>{captured.parameters.push({id,revision:1,status:'DRAFT',unit_context:{distributor:'CPFL',state:'SP',tariff_group:'A',tariff_modality:'GREEN',free_market:true,tariff_subgroup:null,consumption_class:null},kind:d.kind,scenario:d.scenario,component_code:d.componentCode,time_band:d.timeBand,amount_text:d.amount,measure:d.measure,treatment:d.treatment,source:d.source,notes:d.notes,embedded_tax_codes:d.embeddedTaxCodes,start_date:d.startDate,end_date:d.endDate,tax_basis:d.taxBasis});return {id};})};
 const service=new OcrResolutionService({getClient:()=>({from})} as any,{requireEntitlement:async()=>{}} as any,{reviewSource:async()=>source} as any,{list:async()=>identity} as any,{list:async()=>consumption} as any,{inspect:async(_x:any,_org:any,capture:any)=>{capture(captured);return {counts:{blockers:14,reviews:2},findings:[],contractSupplierCost:{regularAmount:'11772.90',volumeDifferenceMwh:'-0.05302'}};}} as any,parameters as any,{} as any,{} as any,{preview:async()=>preview('tusd')} as any,{preview:async()=>preview('cde')} as any,{measurementReadiness:async()=>({demand:[]})} as any);
 const t:any={organizationId:'org',userId:'operator',role:'operacional',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_UPDATE,P.ENERGIA_OCR_PROCESS]};
 return {service,t,parameters,captured,consumption,identity,calls,source};
}
describe('Resolution evidence assembly',()=>{
 it('builds source-backed missing ACL rates despite existing manual monthly data, scopes private NF, and pins only each line tax codes',async()=>{const s=setup(),before=await s.service.inspect('doc',s.t);expect(before.ready).toBe(true);expect(before.rates).toHaveLength(5);expect(before.monthly.changes).toContainEqual({label:'reactiveBilledOffPeakKwh',before:'2320.1629',after:'2320.4823'});const result=await s.service.prepare('doc',s.t,{token:before.token});expect(s.parameters.createPrepared).toHaveBeenCalledTimes(8);const unused=s.parameters.createPrepared.mock.calls.find(([,d])=>d.componentCode==='TUSD_DEMAND_UNUSED')![1];expect(unused.embeddedTaxCodes).toEqual(['PIS','COFINS']);const icms=s.parameters.createPrepared.mock.calls.find(([,d])=>d.kind==='TAX'&&d.componentCode==='ICMS')![1];expect(icms.amount).toBeNull();expect(icms.taxBasis.items).toHaveLength(4);expect(result.current.rates.every((r:any)=>r.state==='PRESERVED')).toBe(true);expect(result.current.costs.supplierPresent).toBe(false);expect(s.calls).toContainEqual(['documents','eq','organization_id','org']);expect(s.calls).toContainEqual(['documents','eq','consumer_unit_id','unit']);expect(s.calls).toContainEqual(['documents','eq','reference_month','2026-08-01']);expect(s.captured.monthly[0].measurements.demandSingle).toBe('500');const again=await s.service.prepare('doc',s.t,{token:result.current.token});expect(s.parameters.createPrepared).toHaveBeenCalledTimes(8);expect(again.receipts).toHaveLength(0);});
 it('blocks auto-writing if human reviews are missing or their source changes',async()=>{for(const stale of [false,true]){const s=setup();if(stale)s.identity.fields[0].history[0].sourceHash='changed';else s.consumption.fields[0].history=[];const p=await s.service.inspect('doc',s.t);expect(p.ready).toBe(false);await expect(s.service.prepare('doc',s.t,{token:p.token})).rejects.toThrow();expect(s.parameters.createPrepared).not.toHaveBeenCalled();}});
 it('does not build a tariff from a mismatched billed quantity or missing tax evidence',async()=>{const s=setup();s.consumption.fields[0].decimal='1';const p=await s.service.inspect('doc',s.t);expect(p.rates.some((r:any)=>r.component==='TUSD_ENERGY')).toBe(false);expect(p.rates.some((r:any)=>r.component==='CDE_WATER_SCARCITY')).toBe(false);});
});
