import {OcrCipIntegrationService} from './ocr-cip-integration.service';
import {OcrCipIntegrationController} from './ocr-cip-integration.controller';
import {PERMISSIONS_KEY} from '../../common/decorators/require-permission.decorator';
import {PERMISSIONS as P} from '../../common/constants/permissions';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {cipCostCandidate} from './cip-cost-candidate';
jest.mock('./cpfl-paulista-layout',()=>({extractCpflPaulistaLayout:jest.fn()}));
jest.mock('./cip-cost-candidate',()=>({cipCostCandidate:jest.fn()}));
function setup(){
 (extractCpflPaulistaLayout as jest.Mock).mockReturnValue({operations:[]});
 (cipCostCandidate as jest.Mock).mockReturnValue({ready:true,source:'table.row',amount:'137.58',description:'CIP AGO/26',amountConfidence:.995,descriptionConfidence:.977,pages:[1]});
 const c:any={sourceReady:true,unit:{id:'unit',status:'ACTIVE',free_market:true,tariff_group:'A'},preview:{month:'2026-08',token:'source'},source:{doc:{customer_id:'customer',file_hash:'a'.repeat(64)},jobId:'job'}};
 const data:any={customers:{id:'customer',status:'ACTIVE',deleted_at:null},calculation_monthly_costs:[]},calls:any[]=[],insert=jest.fn((row:any)=>{data.calculation_monthly_costs=[{...row,id:row.id??"new",version:1,revision:1}];return {select:async()=>({data:[{id:row.id??"new"}],error:null})};});
 const updates:any[]=[];let concurrent=false;let error:any=null;const from=(table:string)=>{const q:any={insert};let patch:any=null;q.update=(v:any)=>{patch=v;updates.push(v);return q;};for(const method of ['select','eq','order','limit'])q[method]=(...args:any[])=>{calls.push([table,method,...args]);return q;};q.maybeSingle=async()=>{if(patch){if(concurrent)return {data:null,error:null};const row={...data[table][0],...patch,revision:data[table][0].revision+1};data[table]=[row];return {data:row,error};}return {data:data[table],error};};q.then=(resolve:any)=>resolve({data:data[table],error});return q;};
 const source={taxIntegrationSource:jest.fn(async()=>c)},s=new OcrCipIntegrationService({getClient:()=>({from})} as any,source as any),t:any={organizationId:'org',userId:'actor',role:'gestor',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_CONTRACTS_CREATE]};
 return {s,t,c,data,insert,calls,source,updates,race:()=>concurrent=true,setError:(v:any)=>error=v};
}
describe('CIP integration',()=>{
 it('creates only a sourced draft with actual actor and final billed amount; retries are idempotent',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);expect(p.canCreate).toBe(true);const r=await x.s.create('doc',x.t,{token:p.token});const row=x.insert.mock.calls[0][0];expect(row).toMatchObject({id:r.inputId,organization_id:'org',customer_id:'customer',consumer_unit_id:'unit',origin:'OCR_CIP',month:'2026-08',status:'DRAFT',created_by:'actor',updated_by:'actor',costs:{noCosts:false,items:[{amount:'137.58',scenario:'ACL',effect:'COST',category:'CHARGE',taxTreatment:'INCLUDED'}]}});expect(row.source_reference).toContain('a'.repeat(64));expect(row.notes).toContain(p.token);expect(x.calls).toContainEqual(['calculation_monthly_costs','eq','organization_id','org']);expect(x.calls).toContainEqual(['calculation_monthly_costs','eq','customer_id','customer']);await expect(x.s.create('doc',x.t,{token:p.token})).resolves.toMatchObject({alreadyCreated:true,inputId:r.inputId});expect(x.insert).toHaveBeenCalledTimes(1);});
 it('does not replace existing draft or validated costs',async()=>{for(const status of ['DRAFT','VALIDATED']){const x=setup();x.data.calculation_monthly_costs=[{id:'manual',status,revision:1}];const p=await x.s.preview('doc',x.t);expect(p.state).toBe('EXISTING_RECORD');await expect(x.s.create('doc',x.t,{token:p.token})).rejects.toThrow();expect(x.insert).not.toHaveBeenCalled();}});
 it('blocks stale source, inactive/deleted customer and incomplete confirmations',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.c.preview.token='changed';await expect(x.s.create('doc',x.t,{token:p.token})).rejects.toThrow('prévia mudou');x.data.customers.status='INACTIVE';expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);x.data.customers.status='ACTIVE';x.data.customers.deleted_at='now';expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);x.data.customers.deleted_at=null;x.c.sourceReady=false;expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);expect(x.insert).not.toHaveBeenCalled();});
 it('rejects browser supplied values and unauthorized writers',async()=>{const x=setup();for(const body of [null,{},[],{token:'a'.repeat(64),amount:'0'},{token:1}])await expect(x.s.create('doc',x.t,body)).rejects.toThrow();for(const t of [{...x.t,role:'operador'},{...x.t,permissions:[]},{...x.t,userId:''}])await expect(x.s.create('doc',t,{token:'a'.repeat(64)})).rejects.toThrow();expect(x.insert).not.toHaveBeenCalled();});
 it('propagates licensed scoped source denial and sanitizes DB failures',async()=>{const x=setup();x.source.taxIntegrationSource.mockRejectedValueOnce(new Error('scope/license'));await expect(x.s.preview('doc',x.t)).rejects.toThrow('scope/license');x.setError({message:'private'});await expect(x.s.preview('doc',x.t)).rejects.toThrow('Não foi possível');});
 it('blocks low confidence candidates',async()=>{const x=setup();(cipCostCandidate as jest.Mock).mockReturnValue({ready:false,amount:'137.58'});expect((await x.s.preview('doc',x.t)).canCreate).toBe(false);});
 it('resolves concurrent same-document duplicate without creating a second item',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.insert.mockImplementationOnce((row:any)=>{x.data.calculation_monthly_costs=[row];return {select:async()=>({data:null,error:{code:'23505'}})} as any;});await expect(x.s.create('doc',x.t,{token:p.token})).resolves.toMatchObject({alreadyCreated:true});});
 it('preserves a concurrently created different record',async()=>{const x=setup(),p=await x.s.preview('doc',x.t);x.insert.mockImplementationOnce(()=>{x.data.calculation_monthly_costs=[{id:'other'}];return {select:async()=>({data:null,error:{code:'P3602'}})} as any;});await expect(x.s.create('doc',x.t,{token:p.token})).rejects.toThrow('Os custos mudaram');});

 async function legacy(){const x=setup();const p=await x.s.preview('doc',x.t);await x.s.create('doc',x.t,{token:p.token});x.data.calculation_monthly_costs[0].costs.items[0].taxTreatment='UNSPECIFIED';x.t.permissions.push(P.ORGANIZATION_CONTRACTS_UPDATE);return x;}
 async function body(x:any){const p=await x.s.preview('doc',x.t);return {token:p.token,inputId:x.data.calculation_monthly_costs[0].id,revision:x.data.calculation_monthly_costs[0].revision};}
 it('prepares legacy CIP with actor, reason and revision but never validates or changes money',async()=>{const x=await legacy();const before=structuredClone(x.data.calculation_monthly_costs[0]);const result=await x.s.prepareReview('doc',x.t,await body(x));expect(result.adjusted).toBe(true);expect(result.row).toMatchObject({status:'DRAFT',revision:2,updated_by:'actor',costs:{items:[{amount:'137.58',taxTreatment:'INCLUDED'}]}});expect(result.row.correction_reason).toContain('Ajuste automático OCR CIP');expect(result.row.source_reference).toBe(before.source_reference);expect(x.updates[0]).not.toHaveProperty('status');expect(x.calls).toContainEqual(['calculation_monthly_costs','eq','revision',1]);await expect(x.s.prepareReview('doc',x.t,await body(x))).resolves.toMatchObject({adjusted:false});expect(x.updates).toHaveLength(1);});
 it('preserves other manual items and explicit classifications',async()=>{const x=await legacy();const row=x.data.calculation_monthly_costs[0];const other={...row.costs.items[0],id:'manual',label:'Outro',taxTreatment:'UNSPECIFIED'};row.costs.items.push(other);await x.s.prepareReview('doc',x.t,await body(x));expect(x.data.calculation_monthly_costs[0].costs.items[1]).toEqual(other);row.costs.items[0].taxTreatment='EXCLUDED';});
 it.each(['EXCLUDED','NOT_APPLICABLE','INCLUDED'])('does not replace explicit %s treatment',async tax=>{const x=await legacy();x.data.calculation_monthly_costs[0].costs.items[0].taxTreatment=tax;await expect(x.s.prepareReview('doc',x.t,await body(x))).resolves.toMatchObject({adjusted:false});expect(x.updates).toHaveLength(0);});
 it.each(['amount','source','category','scenario','effect','id','label'])('preserves altered CIP %s',async key=>{const x=await legacy();x.data.calculation_monthly_costs[0].costs.items[0][key]='changed';await expect(x.s.prepareReview('doc',x.t,await body(x))).rejects.toThrow('diverge');expect(x.updates).toHaveLength(0);});
 it('blocks changed preview, revision, reviewed evidence, inactive customer and validated record',async()=>{for(const kind of ['token','revision','source','customer','validated','unit']){const x=await legacy(),b=await body(x);if(kind==='token')b.token='b'.repeat(64);if(kind==='revision')b.revision++;if(kind==='source')x.c.sourceReady=false;if(kind==='customer')x.data.customers.status='INACTIVE';if(kind==='validated')x.data.calculation_monthly_costs[0].status='VALIDATED';if(kind==='unit')x.data.calculation_monthly_costs[0].unit_context.state='changed';await expect(x.s.prepareReview('doc',x.t,b)).rejects.toThrow();expect(x.updates).toHaveLength(0);}});
 it('blocks unauthorized writers and client supplied fields',async()=>{const x=await legacy(),b=await body(x);for(const t of [{...x.t,role:'operador'},{...x.t,permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW]},{...x.t,userId:''}])await expect(x.s.prepareReview('doc',t,b)).rejects.toThrow();await expect(x.s.prepareReview('doc',x.t,{...b,amount:'0'})).rejects.toThrow();expect(x.updates).toHaveLength(0);});
 it('rejects concurrent modification and protects update route',async()=>{const x=await legacy(),b=await body(x);x.race();await expect(x.s.prepareReview('doc',x.t,b)).rejects.toThrow('durante');expect(Reflect.getMetadata(PERMISSIONS_KEY,OcrCipIntegrationController.prototype.prepareReview)).toEqual([P.ORGANIZATION_CONTRACTS_UPDATE]);});

 describe('invoice adjustment revision',()=>{
  async function current(){const x=setup();x.t.permissions.push(P.ORGANIZATION_CONTRACTS_UPDATE);const p=await x.s.preview('doc',x.t);await x.s.create('doc',x.t,{token:p.token});const row=x.data.calculation_monthly_costs[0];row.status='VALIDATED';row.costs.items.push({id:'supplier',label:'Fornecedor',category:'SUPPLIER_INVOICE',scenario:'ACL',effect:'COST',amount:'16857.18',source:'Nota original',taxTreatment:'RESERVED',taxReservationReason:'Tributos ainda não confirmados.'});
   const operations=[['TUSD_ENERGY','CHARGE','100.00'],['PUBLIC_LIGHTING','CHARGE','137.58'],['TARIFF_SUBSIDY','CHARGE','20.00'],['REFUND','CREDIT','-10.00'],['TOTAL_A_PAGAR','TOTAL','247.58']].map(([component,role,decimal],i)=>({source:component==='PUBLIC_LIGHTING'?'table.row':'op'+i,component,role,fields:{description:{text:component,issues:[]},amount:{decimal,issues:[]}},issues:[]}));
   (extractCpflPaulistaLayout as jest.Mock).mockReturnValue({operations});return x;
  }
  async function request(x:any){const p=await x.s.preview('doc',x.t),r=x.data.calculation_monthly_costs[0];return {token:p.token,inputId:r.id,revision:r.revision,reason:'Integrar ajustes conciliados com a fatura original.'};}
  it('creates a new draft preserving supplier, predecessor and author',async()=>{const x=await current(),old=structuredClone(x.data.calculation_monthly_costs[0]);const result=await x.s.integrateAdjustments('doc',x.t,await request(x));const row=x.insert.mock.calls[1][0];expect(result.alreadyCreated).toBe(false);expect(row).toMatchObject({status:'DRAFT',previous_id:old.id,created_by:'actor',updated_by:'actor',origin:'MANUAL'});expect(row.costs.items).toHaveLength(4);expect(row.costs.items[1]).toEqual(old.costs.items[1]);expect(row.costs.items[3]).toMatchObject({effect:'CREDIT',amount:'10.00',category:'DISTRIBUTOR_ADJUSTMENT'});expect(old.costs.items).toHaveLength(2);
   await expect(x.s.integrateAdjustments('doc',x.t,await request(x))).resolves.toMatchObject({alreadyCreated:true});expect(x.insert).toHaveBeenCalledTimes(2);
  });
  it('rejects stale versions, incorrect amounts, missing permission and client amounts',async()=>{for(const kind of ['stale','cip','source','permission','amount']){const x=await current(),body:any=await request(x);if(kind==='stale')body.revision++;if(kind==='cip')x.data.calculation_monthly_costs[0].costs.items[0].amount='1.00';if(kind==='source')x.c.sourceReady=false;if(kind==='permission')x.t.permissions=[];if(kind==='amount')body.amount='0';await expect(x.s.integrateAdjustments('doc',x.t,body)).rejects.toThrow();expect(x.insert).toHaveBeenCalledTimes(1);}});
  it('protects the revision route with both permissions',()=>expect(Reflect.getMetadata(PERMISSIONS_KEY,OcrCipIntegrationController.prototype.integrateAdjustments)).toEqual([P.ORGANIZATION_CONTRACTS_CREATE,P.ORGANIZATION_CONTRACTS_UPDATE]));
 });
});
