import {demandTaxConfidence} from './demand-tax-confidence';
import {reviewedDemandSummary} from './reviewed-demand-summary';
import {Injectable,BadRequestException,ConflictException,ServiceUnavailableException,NotFoundException,ForbiddenException} from '@nestjs/common';
import {createHash} from 'node:crypto';
import {SupabaseService} from '../../services/supabase.service';
import {OcrQueueService} from './ocr-queue.service';
import {extractCpflPaulistaLayout} from './cpfl-paulista-layout';
import {auditAuthorNames} from '../contracts/services/audit-author-names';

const uuid=(v:any)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
export function demandReviewDigest(value:any):string{const canonical=(v:any):any=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;return createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}
export function demandReviewInput(input:any){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['fieldKey','sourceHash','decision','note','expectedReviewId','requestId','checkedPdf'].includes(k))||typeof input.fieldKey!=='string'||!/^[a-f0-9]{64}$/.test(input.fieldKey)||!uuid(input.requestId)||!(input.expectedReviewId===null||uuid(input.expectedReviewId))||typeof input.sourceHash!=='string'||!/^[a-f0-9]{64}$/.test(input.sourceHash)||!['USED','UNUSED','NEEDS_CORRECTION'].includes(input.decision)||typeof input.note!=='string'||input.note.length>500||input.checkedPdf!==true&&input.checkedPdf!==false)throw new BadRequestException('Dados de conferência inválidos.');const note=input.note.trim();if(input.checkedPdf!==true)throw new BadRequestException('Confirme a conferência do campo no PDF original.');if(note.length<3)throw new BadRequestException('Informe a evidência da classificação ou a correção necessária.');return {...input,note};}
@Injectable()
export class OcrDemandReviewService{
 constructor(private db:SupabaseService,private queue:OcrQueueService){}
 private fail(error:any){if(error)throw new ServiceUnavailableException('Não foi possível consultar ou salvar a conferência. Atualize o histórico antes de tentar novamente.');}
 canReview(org:string,t:any){return !!t?.userId&&t.organizationId===org&&(['admin_org','gestor'].includes(t.role)||t.accessMode==='platform_operation');}
 private async context(org:string,document:string){const source=await this.queue.reviewSource(org,document);const layout=extractCpflPaulistaLayout(source.raw);const rows=layout.preparation?.demand?.billed??[];const fields=rows.map((row:any,index:number)=>{const unique=rows.filter((r:any)=>r.source===row.source).length===1;const field={...row,key:demandReviewDigest(row.source),label:'Parcela de demanda '+(index+1),state:unique?row.state:'CONFLICT'};const snapshot={format:'ocr-demand-review-v1',layoutVersion:layout.version,jobId:source.jobId,document:{id:source.doc.id,organizationId:org,customerId:source.doc.customer_id,unitId:source.doc.consumer_unit_id,month:String(source.doc.reference_month).slice(0,7),fileHash:source.doc.file_hash},field};return {field,snapshot,sourceHash:demandReviewDigest(snapshot)};});return {...source,taxDiagnostics:rows.map(row=>{const matches=layout.operations.filter(operation=>operation.source===row.source);return {key:demandReviewDigest(row.source),fields:matches.length===1?demandTaxConfidence(matches[0]):[]};}),fields:fields.filter((c:any,i:number)=>fields.findIndex((v:any)=>v.field.key===c.field.key)===i)};}
 private table(){return this.db.getClient().from('document_ocr_demand_reviews');}
 private async present(rows:any[],org:string){if(rows.some(r=>r.organization_id!==org||demandReviewDigest(r.source_snapshot)!==r.source_hash))throw new ServiceUnavailableException('A integridade do histórico requer conferência.');const named=await auditAuthorNames(this.db.getClient(),org,rows);return named.map(r=>({id:r.id,fieldKey:r.field_key,sourceHash:r.source_hash,version:r.version,decision:r.decision,note:r.note,createdAt:r.created_at,author:r.created_by_name??'Autor sem nome cadastrado',value:r.source_snapshot.field.decimal,unit:r.source_snapshot.field.unit}));}
 async list(org:string,document:string){const source=await this.context(org,document);const fields=await Promise.all(source.fields.map(async c=>{const r=await this.table().select('*').eq('organization_id',org).eq('document_id',document).eq('field_key',c.field.key).order('version',{ascending:false}).limit(11);this.fail(r.error);if(!Array.isArray(r.data))this.fail(true);return {...c.field,sourceHash:c.sourceHash,history:await this.present(r.data.slice(0,10),org),hasOlder:r.data.length>10};}));return {canImport:false,taxDiagnostics:source.taxDiagnostics??[],summary:reviewedDemandSummary(fields),fields,message:'Classificação humana da parcela faturada. Não aprova tributos, identidade ou apuração e não altera medições.'};}
 async create(org:string,document:string,t:any,input:any){if(!this.canReview(org,t))throw new ForbiddenException('A classificação exige Gestor ou Administrador da organização.');const actor=t.userId;const d=demandReviewInput(input);if(!actor?.trim())throw new BadRequestException('Autor obrigatório.');const source=await this.context(org,document);const candidate=source.fields.find(c=>c.field.key===d.fieldKey);if(!candidate)throw new NotFoundException('Campo não disponível para conferência neste layout.');
 const lookup=async()=>{const r=await this.table().select('*').eq('organization_id',org).eq('request_id',d.requestId).maybeSingle();this.fail(r.error);return r.data;};
 const replay=async(r:any)=>{if(r.document_id!==document||r.field_key!==d.fieldKey||r.source_hash!==d.sourceHash||r.created_by!==actor||r.decision!==d.decision||r.note!==d.note)throw new ConflictException('Esta solicitação já pertence a outra conferência.');return {canImport:false,review:(await this.present([r],org))[0]};};
 const existing=await lookup();if(existing)return replay(existing);
 if(candidate.sourceHash!==d.sourceHash)throw new ConflictException('A prévia mudou. Atualize e confira o campo novamente.');
 if(d.decision!=='NEEDS_CORRECTION'&&(candidate.field.state!=='BILLED_UNCLASSIFIED'||candidate.field.decimal===null))throw new BadRequestException('Campo ausente ou conflitante não pode ser confirmado.');
 const r=await this.table().insert({organization_id:org,document_id:document,job_id:source.jobId,file_hash:source.doc.file_hash,field_key:d.fieldKey,source_hash:candidate.sourceHash,source_snapshot:candidate.snapshot,decision:d.decision,note:d.note,checked_pdf:true,expected_review_id:d.expectedReviewId,request_id:d.requestId,created_by:actor}).select('*').single();
 if(r.error?.code==='23505'){const saved=await lookup();if(saved)return replay(saved);}
 if(r.error?.code==='40001')throw new ConflictException('Outro usuário atualizou a conferência. Atualize o histórico antes de salvar.');this.fail(r.error);return {canImport:false,review:(await this.present([r.data],org))[0]};
 }
}
