import {OcrAddressService,addressInput,addressEligibility} from './ocr-address.service';
import {identityReviewDigest} from './ocr-identity-review.service';
import {PERMISSIONS} from '../../common/constants/permissions';
import {MAP_VIEW,MAP_CUSTOMERS,MAP_MANAGE} from '../energy-map/energy-map.validation';
const input=()=>({address:'Rua Nova 100',city:'Ribeirão Preto',state:'SP',reason:'Endereço conferido no PDF original.',checkedPdf:true,checkedUnit:true,sourceHash:'a'.repeat(64),expectedVersion:0,requestId:'11111111-1111-4111-8111-111111111111'});
const preview=()=>({registrationAvailable:true,duplicate:false,layoutId:'cpfl-paulista-a',checks:['unit','taxId','address'].map(key=>({key,comparison:key==='address'?'MISMATCH':'EQUAL',state:'REVIEW',candidates:[{text:key==='address'?'Rua Nova 100':'identidade',source:'page1',pages:[1],confidence:null,issues:['MISSING_CONFIDENCE']}]}))});
describe('reviewed OCR cadastral address',()=>{
 it.each([{checkedPdf:false},{checkedUnit:false},{requestId:'bad'},{sourceHash:null},{expectedVersion:1.5},{expectedVersion:-1},{state:'XX'},{city:''},{address:'Rua\nNova'},{reason:'curto'},{organizationId:'other'}])('rejects unsafe payload %j',patch=>expect(()=>addressInput({...input(),...patch})).toThrow());
 it('normalizes explicit structured values',()=>expect(addressInput({...input(),state:' sp ',city:' Cidade '})).toMatchObject({state:'SP',city:'Cidade'}));
 it('accepts sourced divergent address only when identity is equal',()=>expect(addressEligibility(preview())).toBe(true));
 it.each(['PARTIAL','DIFFERENT','MISSING'])('rejects unresolved identity %s',comparison=>{const p=preview();p.checks[1].comparison=comparison;expect(addressEligibility(p)).toBe(false);});
 it('rejects duplicates, unknown layouts and ambiguous addresses',()=>{expect(addressEligibility({...preview(),duplicate:true})).toBe(false);expect(addressEligibility({...preview(),layoutId:'unknown'})).toBe(false);const p=preview();p.checks[2].candidates.push({...p.checks[2].candidates[0],text:'another address'});expect(addressEligibility(p)).toBe(false);});
 it.each(['UNVERIFIED_SOURCE','MISSING_VALUE'])('rejects source issue %s',issue=>{const p=preview();p.checks[2].candidates[0].issues=[issue];expect(addressEligibility(p)).toBe(false);});
 it('rejects missing page and malformed preview',()=>{const p=preview();p.checks[0].candidates[0].pages=[];expect(addressEligibility(p)).toBe(false);expect(addressEligibility(null)).toBe(false);});
});
function setup(){const q:any={select:jest.fn(()=>q),eq:jest.fn(()=>q),maybeSingle:jest.fn(async()=>({data:null,error:null}))};const client={from:jest.fn(()=>q),rpc:jest.fn(async(...args:any[])=>({data:{id:'u'},error:null}))};const service=new OcrAddressService({getClient:()=>client} as any,{} as any,{get:()=> 'org'} as any,{requireEntitlement:async()=>true} as any);const snapshot={unit:{id:'u',edit_version:0}};const c={snapshot,sourceHash:identityReviewDigest(snapshot),eligible:true};jest.spyOn(service as any,'context').mockResolvedValue(c);const tenant={organizationId:'org',userId:'actor',role:'gestor',permissions:[MAP_VIEW,MAP_CUSTOMERS,MAP_MANAGE,PERMISSIONS.DOCUMENTS_VIEW,PERMISSIONS.ENERGIA_OCR_PROCESS]};return {service,q,client,c,tenant,data:{...input(),sourceHash:c.sourceHash}};}
describe('address write boundaries',()=>{
 it('uses current server snapshot and authenticated identity',async()=>{const s=setup();await s.service.save('doc',s.tenant,s.data);expect(s.client.rpc).toHaveBeenCalledWith('save_reviewed_unit_address',expect.objectContaining({p_org:'org',p_actor:'actor',p_snapshot:s.c.snapshot}));});
 it('rejects missing permission, tenant or client role before source reads',async()=>{const s=setup();for(const t of [{...s.tenant,role:'consulta'},{...s.tenant,permissions:[]},{...s.tenant,organizationId:'other'}])await expect(s.service.save('doc',t,s.data)).rejects.toThrow();expect((s.service as any).context).not.toHaveBeenCalled();});
 it('checks SQL current actor before idempotent replay',async()=>{const s=setup();s.client.rpc.mockResolvedValue({data:null,error:{code:'42501'}} as any);await expect(s.service.save('doc',s.tenant,s.data)).rejects.toThrow();expect(s.q.maybeSingle).not.toHaveBeenCalled();});
 it('rejects stale hash and version without writes',async()=>{const s=setup();for(const patch of [{sourceHash:'b'.repeat(64)},{expectedVersion:1}])await expect(s.service.save('doc',s.tenant,{...s.data,...patch})).rejects.toThrow('mudou');expect(s.client.rpc.mock.calls.every(call=>call[0]!=='save_reviewed_unit_address')).toBe(true);});
 it('rejects unresolved source',async()=>{const s=setup();s.c.eligible=false;await expect(s.service.save('doc',s.tenant,s.data)).rejects.toThrow('vínculo');});
 it('replays same request without stale source recomputation',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValue({data:{document_id:'doc',created_by:'actor',input:s.data,result:{id:'u'}},error:null});expect(await s.service.save('doc',s.tenant,s.data)).toEqual({id:'u'});expect((s.service as any).context).not.toHaveBeenCalled();});
 it('rejects replay from another actor or changed input',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValue({data:{document_id:'doc',created_by:'other',input:s.data,result:{}},error:null});await expect(s.service.save('doc',s.tenant,s.data)).rejects.toThrow('outra');});
 it('reports transaction concurrency failure',async()=>{const s=setup();s.client.rpc.mockResolvedValueOnce({data:null,error:null} as any).mockResolvedValueOnce({data:null,error:{code:'40001'}} as any);await expect(s.service.save('doc',s.tenant,s.data)).rejects.toThrow('mudou');});
});
