import {OcrAutofillService} from './ocr-autofill.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
const doc='11111111-1111-4111-a111-111111111111',unit='22222222-2222-4222-a222-222222222222',lib='33333333-3333-4333-a333-333333333333';
function fixture(){
 const t:any={organizationId:'org-a',userId:'operator',role:'operacional',permissions:[P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ENERGIA_OCR_PROCESS,P.ORGANIZATION_CONTRACTS_UPDATE]};
 const library={apply:jest.fn(async()=>({parameter_ids:['draft']}))},licenses={requireEntitlement:jest.fn(async()=>{})};
 const service=new OcrAutofillService({} as any,licenses as any,{} as any,library as any);
 const filled={token:'a'.repeat(64),month:'2026-08',unitId:unit,library:{id:lib,scenario:'ACR'},source:'document · SHA-256 exact'};
 jest.spyOn(service,'inspect').mockResolvedValue(filled as any);
 const settings={consumerUnitId:unit,startDate:'2026-08-01',endDate:'2026-08-31',scenario:'ACR',includedTaxes:true,selected:['TE:PEAK'],embeddedCodes:['ICMS'],taxes:[],cip:'0',other:'0',otherLabel:'',aclSource:'',reason:'Conferido no documento.',expiredConfirmed:false,expiredReason:''};
 const body={token:filled.token,libraryId:lib,checkedPdf:true,acknowledged:true,settings};
 return {service,t,body,library};
}
describe('source-scoped assistant library drafts',()=>{
 function reads(){const f=fixture();(f.service.inspect as jest.Mock).mockRestore();const related={id:lib,organization_id:'org-a',customer_id:'customer',consumer_unit_id:unit,reference_month:'2026-08-01',original_filename:'Invoice A.pdf',document_type:'INVOICE_SUPPLIER',file_verified:true,file_hash:'relatedhash',intake_state:'NOT_APPLICABLE'};const queries:Record<string,any>={};const tables:any={consumer_units:{id:unit},tariff_library_versions:[],documents_with_intake:[related]};const db={getClient:()=>({from:(name:string)=>{const q:any={};for(const key of ['select','eq','or','order','limit','maybeSingle'])q[key]=jest.fn(()=>q);q.then=(resolve:any)=>Promise.resolve({data:tables[name],error:null}).then(resolve);queries[name]=q;return q;}})};(f.service as any).db=db;(f.service as any).queue={reviewSource:jest.fn(async()=>({doc:{id:doc,customer_id:'customer',consumer_unit_id:unit,reference_month:'2026-08-01',file_hash:'hash'},raw:{},jobId:'job'}))};return {...f,related,queries,tables};}
 it('retrieves related evidence only for the same organization, customer, unit and relevant period',async()=>{const f=reads(),p=await f.service.inspect(doc,f.t);for(const args of [['organization_id','org-a'],['customer_id','customer'],['consumer_unit_id',unit]])expect(f.queries.documents_with_intake.eq).toHaveBeenCalledWith(...args);expect(f.queries.documents_with_intake.or).toHaveBeenCalledWith('reference_month.eq.2026-08-01,document_type.in.(CONTRACT_ENERGY,CONTRACT_MANAGEMENT)');expect(p.relatedDocuments[0]).toMatchObject({name:'Invoice A.pdf',fileVerified:true});expect(p.relatedDocuments[0].message).toContain('não comprovam validação');expect(p.relatedDocuments[0]).not.toHaveProperty('amount');});
 it.each(['organization_id','customer_id','consumer_unit_id'])('rejects a related source with mismatched %s',async key=>{const f=reads();(f.related as any)[key]='foreign';await expect(f.service.inspect(doc,f.t)).rejects.toThrow('evidências relacionadas');});
 it('does not call missing receipt a verified file and invalidates a plan when evidence changes',async()=>{const f=reads(),a=await f.service.inspect(doc,f.t);f.related.file_verified=false;const b=await f.service.inspect(doc,f.t);expect(b.relatedDocuments[0].message).toContain('recebimento verificado ainda não comprovado');expect(b.token).not.toBe(a.token);});
 it('fails closed when the related evidence list would be truncated',async()=>{const f=reads();f.tables.documents_with_intake=Array.from({length:100},()=>f.related);await expect(f.service.inspect(doc,f.t)).rejects.toThrow('evidências relacionadas');});
 it('allows an authorized operator to prepare drafts through the existing audited library service',async()=>{const f=fixture();await f.service.applyLibrary(doc,f.t,f.body);expect(f.library.apply).toHaveBeenCalledWith(lib,expect.objectContaining({consumerUnitId:unit,reason:expect.stringContaining('SHA-256 exact')}),'org-a','operator');});
 it.each([{token:'old'},{libraryId:unit},{checkedPdf:false},{acknowledged:false},{organizationId:'org-b'}])('rejects stale evidence or missing attestation before writes: %p',async patch=>{const f=fixture();await expect(f.service.applyLibrary(doc,f.t,{...f.body,...patch})).rejects.toThrow();expect(f.library.apply).not.toHaveBeenCalled();});
 it.each([{consumerUnitId:doc},{scenario:'ACL'},{startDate:'2026-07-01'},{cip:'137.58'},{other:'5.00'}])('rejects changed scope or copied costs: %p',async patch=>{const f=fixture();await expect(f.service.applyLibrary(doc,f.t,{...f.body,settings:{...f.body.settings,...patch}})).rejects.toThrow();expect(f.library.apply).not.toHaveBeenCalled();});
 it('denies a client and an operator missing OCR permission',async()=>{const f=fixture();f.t.role='cliente';await expect(f.service.applyLibrary(doc,f.t,f.body)).rejects.toThrow();f.t.role='operacional';f.t.permissions=f.t.permissions.filter((p:string)=>p!==P.ENERGIA_OCR_PROCESS);await expect(f.service.applyLibrary(doc,f.t,f.body)).rejects.toThrow();expect(f.library.apply).not.toHaveBeenCalled();});
});
