import {OcrReviewService,reviewInput,ocrReviewDigest} from './ocr-review.service';
import {OcrController} from './ocr.controller';
import {PERMISSIONS_KEY} from '../../common/decorators/require-permission.decorator';
import {PERMISSIONS} from '../../common/constants/permissions';
import 'reflect-metadata';
const input=()=>({fieldKey:'consumptionPeakKwh',sourceHash:'a'.repeat(64),decision:'CONFIRMED',note:'',expectedReviewId:null,requestId:'00000000-0000-4000-8000-000000000001',checkedPdf:true});
describe('OCR review validation',()=>{
 it('requires write permission independently of view',()=>{expect(Reflect.getMetadata(PERMISSIONS_KEY,OcrController.prototype.reviewCreate)).toEqual([PERMISSIONS.ENERGIA_OCR_PROCESS]);expect(Reflect.getMetadata(PERMISSIONS_KEY,OcrController.prototype.reviewList)).toEqual([PERMISSIONS.DOCUMENTS_VIEW]);});
 it('accepts explicit PDF confirmation',()=>expect(reviewInput(input()).decision).toBe('CONFIRMED'));
 it.each([{checkedPdf:false},{fieldKey:'taxRate'},{requestId:'invalid'},{sourceHash:'bad'},{expectedReviewId:'bad'},{decision:'APPROVED'},{note:23},{note:'a'.repeat(501)},{organizationId:'foreign'}])('rejects invalid input %j',patch=>expect(()=>reviewInput({...input(),...patch})).toThrow());
 it('requires a correction reason',()=>{expect(()=>reviewInput({...input(),decision:'NEEDS_CORRECTION',note:' '})).toThrow();expect(reviewInput({...input(),decision:'NEEDS_CORRECTION',note:' Conferir unidade ',checkedPdf:false}).note).toBe('Conferir unidade');});
 it('hashes canonical JSON including decimal precision',()=>{expect(ocrReviewDigest({b:2,a:1})).toBe(ocrReviewDigest({a:1,b:2}));expect(ocrReviewDigest({value:'1.00'})).not.toBe(ocrReviewDigest({value:'1.01'}));});
});
function setup(){const q:any={select:jest.fn(()=>q),eq:jest.fn(()=>q),order:jest.fn(()=>q),limit:jest.fn(async()=>({data:[],error:null})),maybeSingle:jest.fn(async()=>({data:null,error:null})),single:jest.fn(),insert:jest.fn(()=>q)};const client={from:jest.fn(()=>q)};const service=new OcrReviewService({getClient:()=>client} as any,{} as any);const snapshot={field:{key:'consumptionPeakKwh',decimal:'12.00',unit:'kWh',state:'EXTRACTED_REVIEW'}};const hash=ocrReviewDigest(snapshot);const context={doc:{id:'doc',file_hash:'f'.repeat(64)},jobId:'00000000-0000-4000-8000-000000000002',fields:[{field:snapshot.field,snapshot,sourceHash:hash}]};jest.spyOn(service as any,'context').mockResolvedValue(context);const row:any={id:'00000000-0000-4000-8000-000000000003',organization_id:'org',document_id:'doc',field_key:'consumptionPeakKwh',source_hash:hash,source_snapshot:snapshot,decision:'CONFIRMED',note:'',created_by:'actor',version:1,created_at:'2026-09-26T00:00:00Z'};q.single.mockResolvedValue({data:row,error:null});return {service,q,client,context,row,data:{...input(),sourceHash:hash}};}
describe('OCR review persistence boundaries',()=>{
 it('saves server snapshot and authenticated actor, never a supplied value',async()=>{const s=setup();const result=await s.service.create('org','doc','actor',s.data);expect(s.q.insert).toHaveBeenCalledWith(expect.objectContaining({organization_id:'org',created_by:'actor',source_snapshot:s.context.fields[0].snapshot}));expect(result.canImport).toBe(false);});
 it('rejects stale preview without writes',async()=>{const s=setup();await expect(s.service.create('org','doc','actor',{...s.data,sourceHash:'b'.repeat(64)})).rejects.toThrow('prévia mudou');expect(s.q.insert).not.toHaveBeenCalled();});
 it('rejects confirming a conflicting candidate',async()=>{const s=setup();s.context.fields[0].field.state='CONFLICT';await expect(s.service.create('org','doc','actor',s.data)).rejects.toThrow('conflitante');});
 it('keeps idempotent replay without duplicate insertion',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValue({data:s.row,error:null});await s.service.create('org','doc','actor',s.data);expect(s.q.insert).not.toHaveBeenCalled();});
 it('rejects reusing request for another actor',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValue({data:s.row,error:null});await expect(s.service.create('org','doc','other',s.data)).rejects.toThrow('outra conferência');});
 it('rejects altered stored evidence',async()=>{const s=setup();s.row.source_snapshot.field.decimal='99';await expect(s.service.create('org','doc','actor',s.data)).rejects.toThrow('integridade');});
 it('reports concurrent update without pretending success',async()=>{const s=setup();s.q.single.mockResolvedValue({data:null,error:{code:'40001'}});await expect(s.service.create('org','doc','actor',s.data)).rejects.toThrow('Outro usuário');});
 it('handles unique-request race as idempotent replay',async()=>{const s=setup();s.q.maybeSingle.mockResolvedValueOnce({data:null,error:null}).mockResolvedValueOnce({data:s.row,error:null});s.q.single.mockResolvedValue({data:null,error:{code:'23505'}});expect((await s.service.create('org','doc','actor',s.data)).review.id).toBe(s.row.id);});
 it('fails closed if source cannot be verified',async()=>{const s=setup();(s.service as any).context.mockRejectedValue(new Error('source'));await expect(s.service.create('org','doc','actor',s.data)).rejects.toThrow('source');expect(s.q.insert).not.toHaveBeenCalled();});
 it('scopes history by organization, document and field',async()=>{const s=setup();await s.service.list('org','doc');for(const pair of [['organization_id','org'],['document_id','doc'],['field_key','consumptionPeakKwh']])expect(s.q.eq).toHaveBeenCalledWith(...pair);});
});
