'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import WhatsappTemplates from '@/app/components/WhatsappTemplates';
import './communications.css';
type Row={id:string;organization_name:string|null;flow:string;processing:string;receipt:string|null;created_at:string;delivery:string;event_count:number;last_at:string|null;errors:number[][];association:string};
type Data={rows:Row[];total:number;messages:number;organizations:{id:string;name:string}[]};
const flows={REPORT:'Relatórios',REQUEST:'Solicitações',AGENDA:'Agenda',DEADLINE:'Prazos',ACL_PUBLISHED:'Adesão ACL',UNASSOCIATED:'Sem fluxo associado'};
const processing={QUEUED:'Na fila',PREPARING:'Preparando',TRANSMITTING:'Transmitindo',ACCEPTED:'Aceito pelo provedor',FAILED:'Falhou',UNKNOWN:'Resultado incerto',BLOCKED:'Bloqueado',UNREGISTERED:'Sem registro de envio'};
const deliveries={sent:'Enviada',delivered:'Entregue',read:'Lida',failed:'Falhou',PENDING:'Sem retorno'};
const associations={LINKED:'Associado',UNASSOCIATED:'Não associado',CONFLICT:'Vínculo conflitante'};
function Select({name,label,options}:{name:string;label:string;options:Record<string,string>}){return <label className="ds-field"><span className="ds-label">{label}</span><select className="ds-input" name={name}><option value="">Todos</option>{Object.entries(options).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;}
const label=(options:Record<string,string>,value:string)=>options[value]??value;
const date=(value:string)=>new Date(value).toLocaleString('pt-BR',{timeZone:'UTC'})+' UTC';
export default function CommunicationsWorkspace(){
 const today=new Date().toISOString().slice(0,10);
 const [filters,setFilters]=useState(''),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[organizations,setOrganizations]=useState<Data['organizations']>([]);
 useEffect(()=>{let current=true;const params=new URLSearchParams(filters);params.set('page',String(page));void apiRequest<Data>('/api/v1/admin/platform-communications?'+params).then(result=>{if(current){setData(result);setOrganizations(result.organizations);setError('');}}).catch(e=>{if(current){setData(null);setError(e instanceof Error?e.message:'Consulta indisponível.');}});return()=>{current=false;};},[filters,page,refresh]);
 function search(event:FormEvent<HTMLFormElement>){event.preventDefault();const params=new URLSearchParams();new FormData(event.currentTarget).forEach((value,key)=>{if(String(value))params.set(key,String(value));});setData(null);setError('');setPage(0);setFilters(params.toString());setRefresh(n=>n+1);}
 function turn(next:number){setData(null);setError('');setPage(next);}
 return <><Card title="Fluxos e entregas por organização"><p>Uma linha por envio interno ou recibo sem vínculo. Aceitação pela API não confirma entrega. O período filtra a data do envio; para recibos não associados, o primeiro evento. Datas em UTC.</p><form onSubmit={search}><div className="communications__grid"><Input label="De" type="date" name="start" required defaultValue={today.slice(0,7)+'-01'}/><Input label="Até" type="date" name="end" required defaultValue={today}/><label className="ds-field"><span className="ds-label">Organização</span><select className="ds-input" name="organization"><option value="">Todas</option>{organizations.map(org=><option key={org.id} value={org.id}>{org.name}</option>)}</select></label><Select name="flow" label="Fluxo" options={flows}/></div><details className="communications__filters"><summary>Filtros avançados</summary><div className="communications__grid"><Select name="processing" label="Processamento" options={processing}/><Select name="delivery" label="Entrega" options={deliveries}/><Select name="association" label="Vínculo do recibo" options={associations}/><Input label="Recibo original — busca exata" name="receipt" maxLength={510}/></div></details><div className="communications__actions"><Button type="submit">Filtrar</Button><Button variant="secondary" onClick={()=>{setData(null);setRefresh(n=>n+1);}}>Atualizar</Button></div></form>
 {error?<Alert variant="error">{error}</Alert>:!data?<p role="status">Consultando registros…</p>:<><p>{data.total} registros · {data.messages} recibos únicos sem conflito no período. Vários eventos da mesma mensagem não representam vários envios.</p>{data.rows.length?<div className="communications__table"><table><thead><tr><th>Organização / fluxo</th><th>Envio</th><th>Processamento</th><th>Entrega</th><th>Detalhes</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><td>{row.organization_name??(row.association==='CONFLICT'?'Vínculo conflitante':'Não associada')}<small>{label(flows,row.flow)}</small></td><td>{date(row.created_at)}</td><td>{label(processing,row.processing)}</td><td>{label(deliveries,row.delivery)}</td><td><details><summary>Conferir</summary><dl><dt>Recibo original</dt><dd>{row.receipt||'Ainda não registrado'}</dd><dt>Vínculo</dt><dd>{label(associations,row.association)}</dd><dt>Eventos</dt><dd>{row.event_count}</dd><dt>Último evento</dt><dd>{row.last_at?date(row.last_at):'Sem retorno'}</dd><dt>Erros Meta</dt><dd>{row.errors.flat().join(', ')||'Nenhum código registrado'}</dd><dt>Modelo utilizado no envio</dt><dd>Não preservado neste histórico. A configuração atual não identifica o modelo antigo.</dd><dt>Custo</dt><dd>Não apurado. Entrega não comprova cobrança.</dd></dl></details></td></tr>)}</tbody></table></div>:<p>Nenhum registro corresponde aos filtros.</p>}<div className="communications__actions"><Button variant="secondary" disabled={page===0} onClick={()=>turn(page-1)}>Anterior</Button><span>Página {page+1}</span><Button variant="secondary" disabled={(page+1)*25>=data.total} onClick={()=>turn(page+1)}>Próxima</Button></div></>}
 </Card><Card title="Modelos e configuração na Meta"><WhatsappTemplates/></Card></>;
}
