import {cnpj,validateTrading} from './trading-validation';
import {compareTrading} from './trading-comparison';
import {TradingHubService,TRADING_VIEW} from './trading-hub.service';
describe('Trading Hub boundaries and calculations',()=>{
 const supplier={legalName:'Empresa de teste',tradeName:'Teste',cnpj:'11222333000181',phone:'16999990000',administrativeEmail:'admin@example.test',administrativeContact:'Admin',quotationContacts:[{name:'Comercial',email:'cotacao@example.test'}],address:'Endereço teste',city:'Ribeirão Preto',state:'SP'};
 const op={title:'Cotação teste',customerId:'c',unitId:'u',distributor:'CPFL',submarket:'SE_CO',averageMwhMonth:100,energyType:'CONVENTIONAL',startMonth:'2027-01',months:12,expiresAt:new Date(Date.now()+86400000).toISOString()};
 it('validates CNPJ digits and disallows repeated digits',()=>{expect(cnpj('11.222.333/0001-81')).toBe(true);expect(cnpj('11111111111111')).toBe(false);expect(cnpj('11222333000182')).toBe(false);});
 it('normalizes contacts and rejects unauthorized tenant/status fields',()=>{expect(validateTrading('supplier',supplier).cnpj).toBe('11222333000181');expect(()=>validateTrading('supplier',{...supplier,organization_id:'other'})).toThrow();expect(()=>validateTrading('opportunity',{...op,status:'OPEN'})).toThrow();});
 it('rejects invalid quotation contact, modality and past expiry',()=>{expect(()=>validateTrading('supplier',{...supplier,quotationContacts:[{name:'A',email:'bad'}]})).toThrow();expect(()=>validateTrading('opportunity',{...op,energyType:'INVALID'})).toThrow();expect(()=>validateTrading('opportunity',{...op,expiresAt:'2020-01-01'})).toThrow();});
 it('requires documented full scenario costs before savings',()=>{expect(()=>validateTrading('opportunity',{...op,acrMonthlyBrl:100})).toThrow();});
 const proposal=(id:string,price:number,type='CONVENTIONAL',status='RECEIVED')=>({id,status,data:{supplierId:id,priceBrlMwh:price,energyType:type,validUntil:'2099-01-01'}});
 it('does not fabricate savings, NPV or payback when inputs are missing',()=>{const r=compareTrading({data:op},[proposal('a',145)])[0];expect(r.estimatedSavingBrl).toBeNull();expect(r.npvBrl).toBeNull();expect(r.paybackMonths).toBeNull();});
 it('ranks only matching modality/valid proposals; equal prices share rank',()=>{const r=compareTrading({data:op},[proposal('a',145),proposal('b',145),proposal('c',151),proposal('x',1,'INCENTIVIZED_50'),proposal('z',1,'CONVENTIONAL','REJECTED')]);expect(r.map(v=>v.rank)).toEqual([1,1,3]);});
 it('includes other ACL charges and computes documented cashflow',()=>{const r=compareTrading({data:{...op,acrMonthlyBrl:20000,aclOtherMonthlyBrl:5000,comparisonBasis:'Documented same month',investmentBrl:6000,discountAnnualPercent:0}},[proposal('a',145)])[0];expect(r.estimatedSavingBrl).toBe(500);expect(r.npvBrl).toBe(0);expect(r.paybackMonths).toBe(12);});
 it.each(['consulta','anonymous'])('denies %s even with contract read permission',async role=>{const license={requireEntitlement:jest.fn()};const s=new TradingHubService({getClient:jest.fn()} as any,license as any);await expect(s.allowed({organizationId:'org',userId:'a',role,permissions:[TRADING_VIEW]} as any)).rejects.toThrow();expect(license.requireEntitlement).not.toHaveBeenCalled();});
 it('fails closed on absent/expired plan entitlement',async()=>{const license={requireEntitlement:jest.fn().mockRejectedValue(new Error('not licensed'))};const s=new TradingHubService({getClient:jest.fn()} as any,license as any);await expect(s.allowed({organizationId:'org',userId:'a',role:'gestor',permissions:[TRADING_VIEW]} as any)).rejects.toThrow('not licensed');expect(license.requireEntitlement).toHaveBeenCalledWith('org','trading_hub');});
});
