import {licenseRequestAuthors} from './license-request-authors';
const rows=[{id:'r1',organization_id:'org-a',requested_by:'actor',note:'Existing request'},{id:'r2',organization_id:'org-b',requested_by:'other',note:'Another authorized organization'}];
function fixture(members:any[],profiles:any[],fail=false){const calls:any[]=[];const client={from:(table:string)=>{calls.push(table);const q:any={select:(fields:string)=>{calls.push(fields);return q;},in:(field:string,ids:string[])=>{calls.push([field,ids]);return q;},then:(resolve:any)=>Promise.resolve(fail?{error:{message:'Unavailable'},data:null}:{error:null,data:table==='organization_members'?members:profiles}).then(resolve)};return q;}};return{client,calls};}
describe('License request author labels',()=>{
 it('uses only matching organization/actor pairs and preserves the request',async()=>{const f=fixture([{organization_id:'org-a',user_id:'actor',display_name:'Ana Maria de Souza',affiliation_type:'external'},{organization_id:'foreign',user_id:'actor',display_name:'Foreign person',affiliation_type:'internal'}],[]);const [r]=await licenseRequestAuthors(f.client,[rows[0]],'org-a');expect(r).toMatchObject({...rows[0],requested_by_name:'Ana Maria de Souza',requested_by_affiliation:'external'});expect(f.calls).toContainEqual(['organization_id',['org-a']]);expect(JSON.stringify(r)).not.toContain('Foreign person');expect(f.calls.some(c=>typeof c==='string'&&/email|phone|permissions/.test(c))).toBe(false);});
 it('resolves referenced profile names only, retaining undefined affiliation for former actors',async()=>{const f=fixture([],[{user_id:'actor',name:'Bruno Silva'},{user_id:'stranger',name:'Secret person'}]);const [r]=await licenseRequestAuthors(f.client,[rows[0]],'org-a');expect(r.requested_by_name).toBe('Bruno Silva');expect(r.requested_by_affiliation).toBeNull();expect(JSON.stringify(r)).not.toContain('Secret person');expect(f.calls).toContainEqual(['user_id',['actor']]);});
 it('does not consult a foreign organization for a scoped caller',async()=>{const f=fixture([{organization_id:'org-b',user_id:'other',display_name:'Not authorized'}],[]);const result=await licenseRequestAuthors(f.client,rows,'org-a');expect(result[1].requested_by_name).toBeNull();expect(f.calls).toContainEqual(['organization_id',['org-a']]);});
 it('keeps pending requests and actor IDs when directories fail',async()=>{const f=fixture([],[],true);const [r]=await licenseRequestAuthors(f.client,[rows[0]],'org-a');expect(r).toEqual({...rows[0],requested_by_name:null,requested_by_affiliation:null});});
 it('does not query the directory for an empty request set',async()=>{const f=fixture([],[]);expect(await licenseRequestAuthors(f.client,[])).toEqual([]);expect(f.calls).toHaveLength(0);});
});
