import {geocodeAddress,geocodeCandidates,GeocodeFailure,MapboxGeocodingProvider} from './geocoding.provider';
import {EnergyMapGeocodingService} from './geocoding.service';
import {MAP_MANAGE} from './energy-map.validation';
const feature=(lat=-21,lng=-47)=>({geometry:{type:'Point',coordinates:[lng,lat]},properties:{feature_type:'address',mapbox_id:'id',full_address:'Rua Um, Ribeirão Preto',coordinates:{accuracy:'interpolated'},context:{place:{name:'Ribeirão Preto'},region:{region_code_full:'BR-SP'},country:{country_code:'br'}}}});
describe('geocoding security',()=>{
 it('rejects malformed input before provider dispatch',()=>{expect(()=>geocodeAddress({address:'Rua; DROP',city:'Cidade',state:'SP'})).toThrow(GeocodeFailure);expect(()=>geocodeAddress({address:'Rua Um',city:'Cidade',state:'XX'})).toThrow(GeocodeFailure);});
 it('filters foreign and invalid coordinates, marks interpolation approximate',()=>{const raw={type:'FeatureCollection',features:[feature(),feature(99),feature(-21,999)]};const rows=geocodeCandidates(raw,{city:'Ribeirao Preto',state:'SP'});expect(rows).toHaveLength(1);expect(rows[0].precision).toBe('STREET');expect(geocodeCandidates(raw,{city:'Rio',state:'RJ'})).toHaveLength(0);});
 it('never treats missing token or permanent authorization as configured',()=>{expect(new MapboxGeocodingProvider({get:()=>undefined} as any).configured()).toBe(false);});
 const t={organizationId:'o1',userId:'a1',permissions:[MAP_MANAGE]} as any;
 function setup(enabled=true){const rpc=jest.fn(),locate=jest.fn();const service=new EnergyMapGeocodingService({access:jest.fn().mockResolvedValue({enabled:true})} as any,{getClient:()=>({rpc})} as any,{get:()=>enabled?'o1':''} as any,{configured:()=>true,locate} as any);return {service,rpc,locate};}
 it('does not dispatch when feature disabled',async()=>{const {service,rpc,locate}=setup(false);await expect(service.locate('u1',{addressHash:'a'.repeat(32)},t)).rejects.toThrow();expect(rpc).not.toHaveBeenCalled();expect(locate).not.toHaveBeenCalled();});
 it('denies write permission and injected address',async()=>{const {service,rpc}=setup();await expect(service.locate('u1',{addressHash:'a'.repeat(32)},{...t,permissions:[]})).rejects.toThrow();await expect(service.locate('u1',{addressHash:'a'.repeat(32),address:'forged'},t)).rejects.toThrow();expect(rpc).not.toHaveBeenCalled();});
 it('reuses durable request without a second paid dispatch',async()=>{const {service,rpc,locate}=setup();rpc.mockResolvedValue({data:{dispatch:false},error:null});await service.locate('u1',{addressHash:'a'.repeat(32)},t);expect(locate).not.toHaveBeenCalled();expect(rpc.mock.calls[0][1]).toMatchObject({p_daily:10,p_monthly:100,p_actor:'a1',p_org:'o1'});});
 it('only sends canonical address returned by private claim',async()=>{const {service,rpc,locate}=setup();rpc.mockResolvedValueOnce({data:{dispatch:true,jobId:'job',leaseId:'lease',address:{address:'Rua Um 100',city:'Ribeirão Preto',state:'SP'}}}).mockResolvedValue({data:null});locate.mockResolvedValue([]);await service.locate('u1',{addressHash:'a'.repeat(32)},t);expect(locate).toHaveBeenCalledWith({address:'Rua Um 100',city:'Ribeirão Preto',state:'SP'});expect(rpc.mock.calls[1][1]).toMatchObject({p_candidates:[],p_error:null});});
 it('propagates revoked membership before provider call',async()=>{const {service,rpc,locate}=setup();rpc.mockResolvedValue({error:{code:'42501'}});await expect(service.locate('u1',{addressHash:'a'.repeat(32)},t)).rejects.toThrow();expect(locate).not.toHaveBeenCalled();});
});
