'use client';
import styles from './report-workspace.module.css';
export type ClimateSummary={version:string;applied:boolean;reason:string;sensitivity?:string;readingAlignment?:string;climateMaeKwh?:string;baselineMaeKwh?:string;baselineMethod?:string;improvementPercent?:number|null;winningOrigins?:number;originCount?:number;predictions?:number;byHorizon?:{horizon:number;climateMaeKwh:string;baselineMaeKwh:string;predictions:number}[]};
export type ClimateAssessment={version:string;applied:boolean;reason:string;context?:{sensitivity?:string;readingAlignment?:string};comparison?:{climateMaeKwh:string;bestBaselineMaeKwh:string;baselineMethod:string;improvementPercent:number|null;winningOrigins:number;originCount:number;predictions:number;byHorizon:NonNullable<ClimateSummary['byHorizon']>}};
const number=(v:string|number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(Number(v));
export default function ClimateDiagnostics({summary,assessment}:{summary?:ClimateSummary;assessment?:ClimateAssessment}){
 const c=assessment?.comparison;
 const s=summary??(assessment?.version==='climate-cycle/2.0'?{version:assessment.version,applied:assessment.applied,reason:assessment.reason,...assessment.context,...(c?{climateMaeKwh:c.climateMaeKwh,baselineMaeKwh:c.bestBaselineMaeKwh,baselineMethod:c.baselineMethod,improvementPercent:c.improvementPercent,winningOrigins:c.winningOrigins,originCount:c.originCount,predictions:c.predictions,byHorizon:c.byHorizon}:{})}:undefined);
 if(!s)return null;
 return <section aria-label="Avaliação do ajuste climático" className={styles.forecastMethod}><h4>Clima e precisão da previsão</h4><p><strong>{s.applied?'Ajuste climático aplicado':'Referência sem clima preservada'}</strong> · {s.reason}.</p>
 {s.sensitivity==='LOW'?<p>Baixa influência da temperatura informada para esta unidade. Não foi presumido consumo com aquecimento ou refrigeração.</p>:null}
 <p>{s.readingAlignment==='DOCUMENTED'?'Temperatura alinhada aos períodos de leitura documentados, sujeitos à conferência das premissas.':s.readingAlignment==='CALENDAR_APPROXIMATION'?'Datas de leitura ainda não documentadas: a avaliação utiliza meses civis como aproximação; não aplica clima à previsão.':'Períodos ou temperaturas ainda precisam de conferência.'}</p>
 {s.climateMaeKwh&&s.baselineMaeKwh?<><div className={styles.metrics}><div className={styles.metric}><span>Erro médio com cenário climático</span><strong>{number(s.climateMaeKwh)} kWh</strong></div><div className={styles.metric}><span>Erro da melhor referência sem clima</span><strong>{number(s.baselineMaeKwh)} kWh</strong></div><div className={styles.metric}><span>Ganho de precisão no teste</span><strong>{s.improvementPercent===null||s.improvementPercent===undefined?'Indisponível':`${number(s.improvementPercent)}%`}</strong></div></div><p>Erro menor representa melhor precisão. Ganho negativo significa que o clima piorou a previsão. Melhora em {s.winningOrigins}/{s.originCount} origens cronológicas; ciclo anual completo. Critério: ganho superior a 10% e melhora em pelo menos 8 de 12 origens, além das datas documentadas.</p>
 <details><summary>Conferir desempenho por horizonte</summary><table className={styles.table}><thead><tr><th>Meses à frente</th><th>Erro com clima (kWh)</th><th>Erro sem clima (kWh)</th><th>Previsões avaliadas</th></tr></thead><tbody>{s.byHorizon?.map(h=><tr key={h.horizon}><td>{h.horizon}</td><td>{number(h.climateMaeKwh)}</td><td>{number(h.baselineMaeKwh)}</td><td>{h.predictions}</td></tr>)}</tbody></table><p>{s.predictions} previsões sobrepostas não são amostras independentes. Este critério é uma política de aceitação, não um teste formal de significância estatística.</p><p>Temperatura futura usa cenário histórico, escolhido apenas nos dados de treinamento entre ano anterior e média dos mesmos meses. Não é previsão meteorológica nem normal climatológica. Sem intervalo de previsão calibrado.</p></details></>:null}
 </section>;
}
