'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api';
import {Button,Alert} from '@/app/components/ui';
import FlowModal from '../acl-admissions/FlowModal';
import styles from './report-workspace.module.css';
import {useOriginalInvoice} from '../documents/OcrOriginalInvoice';
export type HistoryRow={month:string;consumptionKwh:string;days:number;page:number;source:string};
export type ForecastDocument={id:string;original_filename:string;reference_month:string|null};
type HistoryDraft={sourceHash:string;rows:HistoryRow[];message:string};
export default function ForecastHistoryEditor({documents,onSaved}:{documents:ForecastDocument[];onSaved:()=>Promise<void>}){
 const [document,setDocument]=useState(''),[draft,setDraft]=useState<HistoryDraft|null>(null),[rows,setRows]=useState<HistoryRow[]>([]),[note,setNote]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const request=useRef<string|null>(null),version=useRef(0);
 const original=useOriginalInvoice(document||undefined);
 useEffect(()=>()=>{version.current++;},[]);
 // Parent keys this editor by organization; cleanup suppresses responses from a previous scope.
 const resetRequest=()=>{request.current=null;};
 const load=async()=>{const n=++version.current;setBusy(true);setError('');try{const d=await apiRequest<HistoryDraft>(`/api/v1/energy-forecasts/documents/${document}/draft`);if(n!==version.current)return;setDraft(d);setRows(d.rows);setNote('');setChecked(false);resetRequest();}catch(e){if(n===version.current)setError(e instanceof Error?e.message:'Leitura indisponível.');}finally{if(n===version.current)setBusy(false);}};
 const close=()=>{if(busy)return;version.current++;setDraft(null);};
 const save=async()=>{setBusy(true);setError('');request.current??=crypto.randomUUID();const n=version.current;try{await apiRequest('/api/v1/energy-forecasts/histories',{method:'POST',body:{requestId:request.current,documentId:document,sourceHash:draft!.sourceHash,rows,note,checkedPdf:checked}});if(n!==version.current)return;setDraft(null);resetRequest();await onSaved();}catch(e){if(n===version.current)setError(e instanceof Error?e.message:'Histórico indisponível.');}finally{if(n===version.current)setBusy(false);}};
 const update=(i:number,key:keyof HistoryRow,v:string)=>{resetRequest();setRows(a=>a.map((r,n)=>n===i?{...r,[key]:key==='days'||key==='page'?Number(v):v}:r));};
 return <><h3>Histórico de faturas · sem vínculo obrigatório com Adesão ACL</h3><label>Fatura cadastrada<select disabled={busy} value={document} onChange={e=>{version.current++;setDocument(e.target.value);setDraft(null);}}><option value="">Selecione uma fatura</option>{documents.map(d=><option key={d.id} value={d.id}>{d.original_filename} · {String(d.reference_month??'').slice(0,7)}</option>)}</select></label><Button variant="secondary" disabled={busy||!document} onClick={()=>void load()}>Conferir histórico OCR + IA</Button>{!draft&&error?<Alert variant="error">{error}</Alert>:null}
 <FlowModal open={Boolean(draft)} title="Conferir histórico de consumo" onClose={close}><div className={styles.workspace}><p>{draft?.message}</p><Button variant="secondary" onClick={()=>void original.open?.()}>Abrir fatura original para conferir</Button>{error?<Alert variant="error">{error}</Alert>:null}
 <table className={styles.table}><caption>Informe apenas os meses presentes nesta fatura. A demanda não é obrigatória para esta previsão.</caption><thead><tr><th>Competência</th><th>Consumo kWh</th><th>Dias faturados</th><th>Página PDF</th><th>Fonte</th><th>Ação</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><input aria-label={`Competência ${i+1}`} type="month" disabled={busy} value={r.month} onChange={e=>update(i,'month',e.target.value)}/></td><td><input aria-label={`Consumo ${i+1}`} inputMode="decimal" disabled={busy} value={r.consumptionKwh} onChange={e=>update(i,'consumptionKwh',e.target.value.replace(',','.'))}/></td><td><input aria-label={`Dias ${i+1}`} type="number" min="1" max="62" disabled={busy} value={r.days||''} onChange={e=>update(i,'days',e.target.value)}/></td><td><input aria-label={`Página ${i+1}`} type="number" min="1" max="1000" disabled={busy} value={r.page||''} onChange={e=>update(i,'page',e.target.value)}/></td><td><input aria-label={`Fonte ${i+1}`} maxLength={180} disabled={busy} value={r.source} onChange={e=>update(i,'source',e.target.value)}/></td><td><Button variant="secondary" disabled={busy||rows.length===1} onClick={()=>{resetRequest();setRows(a=>a.filter((_,n)=>n!==i));}}>Remover mês</Button></td></tr>)}</tbody></table>
 <Button variant="secondary" disabled={busy||rows.length>=36} onClick={()=>{resetRequest();setRows(a=>[...a,{month:'',consumptionKwh:'',days:0,page:0,source:''}]);}}>Adicionar mês</Button><label>Justificativa da conferência e ajustes<textarea disabled={busy} minLength={20} maxLength={1000} value={note} onChange={e=>{resetRequest();setNote(e.target.value);}}/></label><label><input type="checkbox" disabled={busy} checked={checked} onChange={e=>{resetRequest();setChecked(e.target.checked);}}/>Conferi os valores, competências, dias e páginas no PDF original.</label><Button disabled={busy||!checked||note.trim().length<20} onClick={()=>void save()}>Salvar para validação</Button><p>O salvamento registra uma nova versão para revisão; ainda não habilita o uso na previsão.</p></div></FlowModal>{original.viewer}</>;
}
