'use client';
import {useEffect,useRef,useState} from 'react';
import {FileDown,FileSpreadsheet,ShieldCheck,TrendingUp} from 'lucide-react';
import {useAuth} from '@/app/providers';
import {apiRequest} from '@/app/lib/api';
import {Alert,Button,Card} from '@/app/components/ui';
const cash=(v:unknown)=>typeof v==='string'?`R$ ${v.replace('.',',').replace(/\B(?=(\d{3})+(?!\d))/g,'.')}`:'Indisponível';
export default function ReportWorkspace({kind}:{kind:'OPERATIONAL'|'EXECUTIVE'}){
 const {context,hasPermission}=useAuth(),org=context&&context.scope!=='global'?context.currentOrganization.id:'';
 const currentOrg=useRef(org);currentOrg.current=org;
 const today=new Date(),[from,setFrom]=useState(`${today.getFullYear()}-01`),[to,setTo]=useState(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`);
 const [sources,setSources]=useState<any>(null),[customer,setCustomer]=useState(''),[unit,setUnit]=useState(''),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const allowed=Boolean(org)&&hasPermission('3ebadd32-6f30-459e-8ed3-0d2843d89946')&&hasPermission('60f9690a-145b-4dba-b23f-9f945baca296'),canCreate=hasPermission('9541a7bb-c20a-4c4d-9f4c-2185262c8e9c');
 useEffect(()=>{let cancelled=false;setBusy(false);setError('');setRows([]);setSelected(null);setSources(null);setCustomer('');setUnit('');if(allowed)apiRequest<any[]>('/api/v1/reports').then(r=>{if(!cancelled)setRows(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[org,allowed]);
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){if(currentOrg.current===org)setError(e instanceof Error?e.message:'Consulta indisponível.');}finally{if(currentOrg.current===org)setBusy(false);}};
 const consult=()=>action(async()=>{setSelected(null);setCustomer('');setUnit('');setSources(null);const q=new URLSearchParams({from,to});const r=await apiRequest<any>('/api/v1/financial-settlements/reports?'+q);if(currentOrg.current===org)setSources(r.primary);});
 const create=()=>action(async()=>{const r=await apiRequest<any>('/api/v1/reports',{method:'POST',body:{kind,customerId:customer,unitId:unit,from,to,requestId:crypto.randomUUID()}});if(currentOrg.current!==org)return;setSelected(r);const list=await apiRequest<any[]>('/api/v1/reports');if(currentOrg.current===org)setRows(list);});
 const open=(id:string)=>action(async()=>{const r=await apiRequest<any>(`/api/v1/reports/${id}`);if(currentOrg.current===org)setSelected(r);});
 const download=(id:string,format:'pdf'|'excel')=>action(async()=>{const blob=await apiRequest<Blob>(`/api/v1/reports/${id}/${format}`,{responseType:'blob'});if(currentOrg.current!==org)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`EnergyOS-${id}.${format==='pdf'?'pdf':'xlsx'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const changePeriod=(f:()=>void)=>{f();setSources(null);setCustomer('');setUnit('');setSelected(null);};
 const customers=Array.from(new Map<string,string>((sources?.publications??[]).map((p:any)=>[p.customerId,p.customerName])).entries());
 const b=selected?.body;
 if(!allowed)return <Alert variant="error">Relatórios exigem acesso autorizado à organização ativa.</Alert>;
 return <section><h1>Relatórios · {kind==='OPERATIONAL'?'Operacional':'Executivo'}</h1><p>PDF e Excel da unidade, com resultados publicados, versão, cobertura e fontes preservadas. A geração não envia mensagens.</p>{error?<Alert variant="error">{error}</Alert>:null}
 <Card title="Período e unidade"><div className="form-grid"><label>De<input type="month" value={from} disabled={busy} onChange={e=>changePeriod(()=>setFrom(e.target.value))}/></label><label>Até<input type="month" value={to} disabled={busy} onChange={e=>changePeriod(()=>setTo(e.target.value))}/></label></div><Button disabled={busy||!from||!to} onClick={consult}>Consultar publicações</Button>
 {sources?<><p>{sources.coverage.publishedMonths}/{sources.coverage.requestedMonths} meses publicados. Sem publicação: {sources.coverage.missingMonths.join(', ')||'nenhum'}.</p><div className="form-grid"><label>Cliente<select value={customer} disabled={busy} onChange={e=>{setCustomer(e.target.value);setUnit('');setSelected(null);}}><option value="">Selecione um cliente publicado</option>{customers.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>Unidade<select value={unit} disabled={busy||!customer} onChange={e=>{setUnit(e.target.value);setSelected(null);}}><option value="">Selecione a unidade</option>{sources.units.filter((u:any)=>u.customerId===customer).map((u:any)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label></div><Button disabled={busy||!canCreate||!unit} onClick={create}>Gerar versão do relatório</Button>{!canCreate?<p>Seu perfil pode consultar relatórios; a geração exige permissão adicional.</p>:null}</>:null}</Card>
 {b?<Card title={`${b.header.customerName} · ${b.header.unitName}`}><p><ShieldCheck size={16}/> {b.formatVersion} · {new Date(b.generatedAt).toLocaleString('pt-BR')} · {b.period.from} a {b.period.to}</p><p>{b.context}</p><div className="form-grid"><Card title="Economia publicada"><TrendingUp size={20}/><strong>{cash(b.totals.savingsAfterFees)}</strong></Card><Card title="Score de economia publicado"><strong>{b.totals.savingsPercent===null?'Indisponível':b.totals.savingsPercent.replace('.',',')+'%'}</strong></Card><Card title="Custo ACR"><strong>{cash(b.totals.acr)}</strong></Card><Card title="ACL com honorários"><strong>{cash(b.totals.aclAfterFees)}</strong></Card></div><p>Cobertura: {b.coverage.publishedMonths}/{b.coverage.requestedMonths}. Meses ausentes não representam zero.</p><ul>{b.unavailable.map((s:string)=><li key={s}>{s}</li>)}</ul><p>{b.disclosure}</p><Button disabled={busy} onClick={()=>download(selected.id,'pdf')}><FileDown size={16}/> Baixar PDF</Button> <Button disabled={busy} onClick={()=>download(selected.id,'excel')}><FileSpreadsheet size={16}/> Baixar Excel</Button></Card>:null}
 <Card title="Versões preservadas"><p>Últimas 100 versões da organização ativa. Cada versão permanece vinculada às publicações usadas na geração.</p>{rows.filter(r=>r.kind===kind).length?rows.filter(r=>r.kind===kind).map(r=><div key={r.id} style={{padding:'12px 0',borderBottom:'1px solid #dbe4ed'}}><strong>{r.customer_name} · {r.unit_name}</strong><p>{r.period.from} a {r.period.to} · {new Date(r.created_at).toLocaleString('pt-BR')}</p><Button variant="secondary" disabled={busy} onClick={()=>open(r.id)}>Abrir versão</Button> <Button variant="secondary" disabled={busy} onClick={()=>download(r.id,'pdf')}>PDF</Button> <Button variant="secondary" disabled={busy} onClick={()=>download(r.id,'excel')}>Excel</Button></div>):<p>Nenhuma versão gerada para este tipo.</p>}</Card></section>;
}
