'use client';
import BotEnergyReports from '@/app/components/BotEnergyReports';
import styles from './report-workspace.module.css';
import PublishedReportPresentation from './PublishedReportPresentation';
import ForecastWorkspace from './ForecastWorkspace';
import FlowModal from '../acl-admissions/FlowModal';
import AnnualForecastPresentation from './AnnualForecastPresentation';
import {useEffect,useRef,useState} from 'react';
import {FileDown,FileSpreadsheet,ShieldCheck} from 'lucide-react';
import {useAuth} from '@/app/providers';
import {apiRequest} from '@/app/lib/api';
import {Alert,Button,Card} from '@/app/components/ui';
export default function ReportWorkspace({kind,financial=false}:{kind:'OPERATIONAL'|'EXECUTIVE';financial?:boolean}){
 const {context,hasPermission}=useAuth(),org=context&&context.scope!=='global'?context.currentOrganization.id:'';
 const currentOrg=useRef(org);
 const today=new Date(),[from,setFrom]=useState(`${today.getFullYear()}-01`),[to,setTo]=useState(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`);
 const [sources,setSources]=useState<any>(null),[customer,setCustomer]=useState(''),[unit,setUnit]=useState(''),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const allowed=Boolean(org)&&hasPermission('3ebadd32-6f30-459e-8ed3-0d2843d89946')&&hasPermission('60f9690a-145b-4dba-b23f-9f945baca296'),canCreate=hasPermission('9541a7bb-c20a-4c4d-9f4c-2185262c8e9c');
 useEffect(()=>{let cancelled=false;setBusy(false);setError('');setRows([]);setSelected(null);setSources(null);setCustomer('');setUnit('');if(allowed)apiRequest<any>('/api/v1/reports/selection').then(r=>{if(!cancelled)setSources(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[org,allowed]);
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){if(currentOrg.current===org)setError(e instanceof Error?e.message:'Consulta indisponível.');}finally{if(currentOrg.current===org)setBusy(false);}};
 const selectionKey=org+'|'+customer+'|'+unit+'|'+from+'|'+to;const activeSelection=useRef(selectionKey);
 useEffect(()=>{currentOrg.current=org;activeSelection.current=selectionKey;},[org,selectionKey]);
 const consult=()=>action(async()=>{const key=selectionKey;setSelected(null);setRows([]);const q=new URLSearchParams({from,to,customerId:customer,unitId:unit,kind});const r=await apiRequest<any[]>('/api/v1/reports?'+q);if(activeSelection.current===key)setRows(r);});
 const create=()=>action(async()=>{const r=await apiRequest<any>('/api/v1/reports',{method:'POST',body:{kind,customerId:customer,unitId:unit,from,to,requestId:crypto.randomUUID()}});if(activeSelection.current!==selectionKey)return;setSelected(r);const q=new URLSearchParams({from,to,customerId:customer,unitId:unit,kind});const list=await apiRequest<any[]>('/api/v1/reports?'+q);if(activeSelection.current===selectionKey)setRows(list);});
 const open=(id:string)=>action(async()=>{const r=await apiRequest<any>(`/api/v1/reports/${id}`);if(activeSelection.current===selectionKey&&r.customer_id===customer&&r.consumer_unit_id===unit&&r.kind===kind&&r.body.period.from>=from&&r.body.period.to<=to)setSelected(r);});
 const download=(id:string,format:'pdf'|'excel')=>action(async()=>{const blob=await apiRequest<Blob>(`/api/v1/reports/${id}/${format}`,{responseType:'blob'});if(activeSelection.current!==selectionKey)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`EnergyOS-${id}.${format==='pdf'?'pdf':'xlsx'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 const changePeriod=(f:()=>void)=>{f();setRows([]);setSelected(null);setForecastOpen(false);};
 const customers=(sources?.customers??[]).map((c:any)=>[c.id,c.company_name]);
 const [forecastOpen,setForecastOpen]=useState(false);
 const b=selected?.body;
 if(!allowed)return <Alert variant="error">Relatórios exigem acesso autorizado à organização ativa.</Alert>;
 return <section className={`backoffice-page ${styles.workspace}`}><h1 className="backoffice-page__title">Relatórios · {financial?'Financeiro':kind==='OPERATIONAL'?'Operacional':'Executivo'}</h1>{financial?<p>Visão financeira das versões executivas existentes. Exportações preservam o formato original. Para consultar, abra uma versão abaixo.</p>:null}<p>PDF e Excel da unidade, com resultados publicados, versão, cobertura e fontes preservadas. A geração não envia mensagens.</p>{error?<Alert variant="error">{error}</Alert>:null}
 <Card title="Escolher empresa, período e unidade"><div className="form-grid"><label>Empresa<select value={customer} onChange={e=>{changePeriod(()=>setCustomer(e.target.value));setUnit('');}}><option value="">Selecione a empresa</option>{customers.map(([id,name]:string[])=><option value={id} key={id}>{name}</option>)}</select></label><label>Unidade<select value={unit} disabled={!customer} onChange={e=>changePeriod(()=>setUnit(e.target.value))}><option value="">Selecione a unidade</option>{(sources?.units??[]).filter((u:any)=>u.customer_id===customer).map((u:any)=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><label>De<input type="month" value={from} onChange={e=>changePeriod(()=>setFrom(e.target.value))}/></label><label>Até<input type="month" value={to} onChange={e=>changePeriod(()=>setTo(e.target.value))}/></label></div><Button disabled={busy||!unit||!from||!to||from>to} onClick={consult}>Consultar versões preservadas</Button> {!financial?<Button variant="secondary" disabled={busy||!canCreate||!unit||from>to} onClick={create}>Gerar nova versão</Button>:null} {kind==='OPERATIONAL'&&!financial?<Button variant="secondary" disabled={!unit} onClick={()=>setForecastOpen(true)}>Preparar e validar previsão</Button>:null}</Card>
 <FlowModal open={forecastOpen} title={'Previsão · '+(sources?.customers??[]).find((c:any)=>c.id===customer)?.company_name+' · '+(sources?.units??[]).find((u:any)=>u.id===unit)?.name} onClose={()=>setForecastOpen(false)}>{forecastOpen&&customer&&unit?<ForecastWorkspace key={selectionKey} canCreate={canCreate} customerId={customer} unitId={unit}/>:null}</FlowModal>
 {b?<Card title={`${b.header.customerName} · ${b.header.unitName}`}><p><ShieldCheck size={16}/> {b.formatVersion} · {new Date(b.generatedAt).toLocaleString('pt-BR')} · {b.period.from} a {b.period.to}</p><p>{b.context}</p><PublishedReportPresentation key={org+'|'+selected.id} report={selected} organizationId={org} view={financial?'FINANCIAL':kind}/>{kind==='OPERATIONAL'&&!financial&&b.annualProjection?<AnnualForecastPresentation forecast={b.annualProjection}/>:null}<BotEnergyReports key={org+'|'+selected.id+'|'+financial} audience="backoffice" reportId={selected.id} kind={financial?'FINANCIAL':kind}/><p>Cobertura: {b.coverage.publishedMonths}/{b.coverage.requestedMonths}. Meses ausentes não representam zero.</p><ul>{b.unavailable.filter((s:string)=>!s.startsWith('ROI:')&&!s.startsWith('Projeção anual:')&&!s.startsWith('Desperdícios:')).map((s:string)=><li key={s}>{s}</li>)}</ul><p>{b.disclosure}</p><p>PDF e Excel preservam o formato publicado original; a apresentação desta tela não modifica as exportações.</p><Button disabled={busy} onClick={()=>download(selected.id,'pdf')}><FileDown size={16}/> Baixar PDF</Button> <Button disabled={busy} onClick={()=>download(selected.id,'excel')}><FileSpreadsheet size={16}/> Baixar Excel</Button></Card>:null}
 <Card title="Versões preservadas"><p>Até 100 versões da empresa e unidade com período contido no intervalo selecionado. Cada versão preserva as publicações usadas na geração.</p>{rows.filter(r=>r.kind===kind).length?rows.filter(r=>r.kind===kind).map(r=><div key={r.id} style={{padding:'12px 0',borderBottom:'1px solid #dbe4ed'}}><strong>{r.customer_name} · {r.unit_name}</strong><p>{r.period.from} a {r.period.to} · {new Date(r.created_at).toLocaleString('pt-BR')}</p><Button variant="secondary" disabled={busy} onClick={()=>open(r.id)}>Abrir versão</Button> <Button variant="secondary" disabled={busy} onClick={()=>download(r.id,'pdf')}>PDF</Button> <Button variant="secondary" disabled={busy} onClick={()=>download(r.id,'excel')}>Excel</Button></div>):<p>Selecione a empresa, unidade e período e consulte as versões preservadas.</p>}</Card></section>;
}
