'use client';
import type {Dispatch,SetStateAction} from 'react';
import styles from './report-workspace.module.css';
type Periods=Record<string,{previousReading:string;currentReading:string;page:string}>;
type Props={sensitivity:'LOW'|'UNKNOWN';setSensitivity:Dispatch<SetStateAction<'LOW'|'UNKNOWN'>>;note:string;setNote:Dispatch<SetStateAction<string>>;documented:boolean;setDocumented:Dispatch<SetStateAction<boolean>>;periods:Periods;setPeriods:Dispatch<SetStateAction<Periods>>;rows?:{month:string;billedDays?:number}[];reset:()=>void};
export default function WeatherCyclePremises(p:Props){
 return <><label>Influência da temperatura na unidade<select value={p.sensitivity} onChange={e=>{p.reset();p.setSensitivity(e.target.value as 'LOW'|'UNKNOWN');}}><option value="UNKNOWN">Ainda não caracterizada</option><option value="LOW">Baixa influência da temperatura</option></select></label>
 <label>Justificativa da premissa climática<textarea maxLength={1000} value={p.note} onChange={e=>{p.reset();p.setNote(e.target.value);}}/></label>
 <p>A avaliação anual requer 36 meses e compara cenário do ano anterior com média histórica dos mesmos meses, usando somente dados anteriores a cada teste. Ganho insuficiente preserva a referência sem clima. Datas estimadas não se tornam leituras documentadas.</p>
 <label><input type="checkbox" checked={p.documented} disabled={!p.rows?.length} onChange={e=>{p.reset();p.setDocumented(e.target.checked);}}/>Informar datas de leitura conferidas nas fontes da versão aberta</label>
 {!p.rows?.length?<p>Para conferir datas, abra uma versão desta unidade. Sem datas documentadas, a nova avaliação informa o desempenho, mas preserva a previsão sem clima.</p>:null}
 {p.documented?<details open><summary>Datas documentadas por competência</summary><p>Preencha apenas datas presentes nos documentos das fontes selecionadas. Leitura anterior exclusiva; leitura atual inclusiva. Os dias devem corresponder ao histórico e os períodos devem ser consecutivos. As referências serão conferidas junto à previsão.</p><div style={{overflowX:'auto'}}><table className={styles.table}><thead><tr><th>Competência</th><th>Dias faturados</th><th>Leitura anterior</th><th>Leitura atual</th><th>Página da fonte</th></tr></thead><tbody>{p.rows?.map(r=><tr key={r.month}><td>{r.month}</td><td>{r.billedDays}</td>{(['previousReading','currentReading','page'] as const).map(field=><td key={field}><input aria-label={`${field==='previousReading'?'Leitura anterior':field==='currentReading'?'Leitura atual':'Página'} ${r.month}`} type={field==='page'?'number':'date'} min={field==='page'?1:undefined} max={field==='page'?1000:undefined} value={p.periods[r.month]?.[field]??''} onChange={e=>{p.reset();p.setPeriods(a=>({...a,[r.month]:{...(a[r.month]??{previousReading:'',currentReading:'',page:''}),[field]:e.target.value}}));}}/></td>)}</tr>)}</tbody></table></div></details>:null}</>;
}
