'use client';
import {FormEvent,useEffect,useState} from 'react';
import DocumentDialog from './DocumentDialog';
import {apiRequest} from '@/app/lib/api/client';
export const documentTags=[['DRAFT','Rascunho'],['APPROVED','Aprovado'],['MODEL','Modelo'],['SIGNING','Assinatura'],['RELEASED','Liberado'],['OBSOLETE','Obsoleto'],['REVIEWED','Revisado']];
export type CatalogDocument={id:string;original_filename:string;document_type:string;reference_month:string;customer_id:string;consumer_unit_id:string;file_verified:boolean;customerName:string;unitName:string;unitCode:string;code:string;favorite:boolean;currentVersion:boolean;created_at?:string;catalog:{document_id:string;series_id:string;previous_id:string|null;version:number;revision:number;tag:string;reason:string;actor_id:string;updated_at:string}};
function Icon({kind}:{kind:'view'|'download'|'star'|'edit'|'history'}){return <svg width="18" height="18" viewBox="0 0 24 24" fill={kind==='star'?'currentColor':'none'} stroke="currentColor" strokeWidth="1.7" aria-hidden="true">{kind==='view'?<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>:kind==='download'?<><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></>:kind==='star'?<path d="m12 2 3 6.5 7 .9-5 5 1.2 7.1-6.2-3.4-6.2 3.4L7 14.4l-5-5 7-.9Z"/>:kind==='history'?<><path d="M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v5l3 2"/></>:<><path d="m4 16 12-12 4 4L8 20H4Z"/></>}</svg>;}
export default function DocumentCatalog({documents,types,onNew,onPreview,onDownload,onOcr,onVersion,onReload,canUpload,canEdit,canApprove}:{documents:CatalogDocument[];types:string[][];onNew:()=>void;onPreview:(id:string)=>void;onDownload:(id:string)=>void;onOcr:(id:string)=>void;onVersion:(d:CatalogDocument)=>void;onReload:()=>void;canUpload:boolean;canEdit:boolean;canApprove:boolean}){
 const [tag,setTag]=useState(''),[search,setSearch]=useState(''),[type,setType]=useState(''),[customer,setCustomer]=useState(''),[unit,setUnit]=useState(''),[favorites,setFavorites]=useState(false),[allVersions,setAllVersions]=useState(false),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<CatalogDocument|null>(null),[history,setHistory]=useState<CatalogDocument|null>(null),[historyData,setHistoryData]=useState<{versions:CatalogDocument['catalog'][];events:{revision:number;actor_id:string;reason:string;recorded_at:string;snapshot:CatalogDocument['catalog']}[]}|null>(null);
 const rows=documents.filter(d=>(allVersions||d.currentVersion)&&(!tag||d.catalog.tag===tag)&&(!search||[d.code,d.original_filename,d.customerName,d.unitName,d.unitCode].join(' ').toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')))&&(!type||d.document_type===type)&&(!customer||d.customer_id===customer)&&(!unit||d.consumer_unit_id===unit)&&(!favorites||d.favorite));
 const pages=Math.max(1,Math.ceil(rows.length/20)),currentPage=Math.min(page,pages),visible=rows.slice((currentPage-1)*20,currentPage*20);
 useEffect(()=>{if(!history)return;const abort=new AbortController();apiRequest<typeof historyData>('/api/v1/document-catalog/'+encodeURIComponent(history.id)+'/history',{signal:abort.signal}).then(r=>{if(!abort.signal.aborted)setHistoryData(r);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Histórico indisponível.');});return()=>abort.abort();},[history]);
 async function favorite(d:CatalogDocument){if(busy)return;setBusy(true);setError('');try{await apiRequest('/api/v1/document-catalog/'+encodeURIComponent(d.id)+'/favorite',{method:'PUT',body:{favorite:!d.favorite}});onReload();}catch(e){setError(e instanceof Error?e.message:'Favorito não salvo.');}finally{setBusy(false);}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing||busy)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');try{await apiRequest('/api/v1/document-catalog/'+encodeURIComponent(editing.id),{method:'PUT',body:{revision:editing.catalog.revision,tag:form.get('tag'),reason:form.get('reason'),checkedDocument:form.get('checkedDocument')==='on'}});setEditing(null);onReload();}catch(e){setError(e instanceof Error?e.message:'Classificação não salva.');}finally{setBusy(false);}}
 function resetPage(){setPage(1);}
 return <section className="document-manager" aria-label="Gerenciamento de documentos">
 <header className="document-manager__toolbar"><div><h2>Biblioteca de documentos</h2><p>{rows.length} documento(s) · arquivos privados · classificação documental separada da aprovação financeira</p></div><button className="ds-button ds-button--primary" disabled={!canUpload||busy} onClick={onNew}>＋ Inserir novo</button></header>
 <div className="document-manager__tabs" aria-label="Filtrar por tag"><button aria-pressed={!tag} onClick={()=>{setTag('');resetPage();}}>Todos</button>{documentTags.map(([value,label])=><button key={value} aria-pressed={tag===value} onClick={()=>{setTag(value);resetPage();}}>{label}</button>)}</div>
 <div className="document-manager__filters"><label>Buscar<input className="ds-input" placeholder="Código, nome, cliente ou unidade" value={search} onChange={e=>{setSearch(e.target.value);resetPage();}}/></label><label>Tipo<select className="ds-input" value={type} onChange={e=>{setType(e.target.value);resetPage();}}><option value="">Todos os tipos</option>{types.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Cliente<select className="ds-input" value={customer} onChange={e=>{setCustomer(e.target.value);setUnit('');resetPage();}}><option value="">Todos os clientes</option>{Array.from(new Map(documents.map(d=>[d.customer_id,d.customerName]))).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Unidade<select className="ds-input" value={unit} onChange={e=>{setUnit(e.target.value);resetPage();}}><option value="">Todas as unidades</option>{Array.from(new Map(documents.filter(d=>!customer||d.customer_id===customer).map(d=>[d.consumer_unit_id,d.unitName+' · '+d.unitCode]))).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></div>
 <div className="document-manager__options"><label><input type="checkbox" checked={favorites} onChange={e=>{setFavorites(e.target.checked);resetPage();}}/> Meus favoritos</label><label><input type="checkbox" checked={allVersions} onChange={e=>{setAllVersions(e.target.checked);resetPage();}}/> Incluir versões anteriores</label><button disabled={busy} onClick={onReload}>Atualizar biblioteca</button></div>
 {error?<p role="alert">{error}</p>:null}<div className="document-manager__table"><table><thead><tr><th>Código / nome</th><th>Cliente / unidade</th><th>Tipo / competência</th><th>Tag</th><th>Versão</th><th>Ações</th></tr></thead><tbody>{visible.map(d=><tr key={d.id}><td><small>{d.code}</small><strong>{d.original_filename}</strong></td><td>{d.customerName}<small>{d.unitName} · {d.unitCode}</small></td><td>{types.find(([v])=>v===d.document_type)?.[1]??d.document_type}<small>{d.reference_month.slice(0,7)}</small></td><td><span className={'document-tag document-tag--'+d.catalog.tag.toLowerCase()}>{documentTags.find(([v])=>v===d.catalog.tag)?.[1]}</span>{!d.file_verified?<small>Arquivo não verificado</small>:null}</td><td>v{String(d.catalog.version).padStart(2,'0')}<small>{d.currentVersion?'Atual':'Histórica'}</small></td><td><div className="document-manager__actions"><button title="Visualizar" aria-label={'Visualizar '+d.original_filename} disabled={!d.file_verified} onClick={()=>onPreview(d.id)}><Icon kind="view"/></button><button title="Baixar" aria-label={'Baixar '+d.original_filename} disabled={!d.file_verified} onClick={()=>onDownload(d.id)}><Icon kind="download"/></button><button aria-label={(d.favorite?'Retirar favorito ':'Favoritar ')+d.original_filename} aria-pressed={d.favorite} disabled={busy} onClick={()=>void favorite(d)}><Icon kind="star"/></button><button title="Histórico e versões" aria-label={'Histórico '+d.original_filename} onClick={()=>{setHistoryData(null);setHistory(d);}}><Icon kind="history"/></button>{canEdit&&d.file_verified?<button disabled={!canApprove&&['APPROVED','RELEASED'].includes(d.catalog.tag)} title="Classificar documento (aprovados e liberados exigem gestor)" aria-label={'Classificar '+d.original_filename} onClick={()=>{setError('');setEditing(d);}}><Icon kind="edit"/></button>:null}</div>{d.document_type==='INVOICE_DISTRIBUTOR'&&d.file_verified?<button className="document-manager__ocr" onClick={()=>onOcr(d.id)}>bot-energy · conferir fatura</button>:null}{canUpload&&d.currentVersion&&d.file_verified?<button onClick={()=>onVersion(d)}>Nova versão</button>:null}</td></tr>)}</tbody></table></div>{!rows.length?<p>Nenhum documento corresponde aos filtros.</p>:null}
 <footer className="document-manager__pagination"><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Anterior</button><span>{currentPage} / {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Próxima</button></footer>
 {editing?<DocumentDialog label="Classificar documento" busy={busy} onClose={()=>setEditing(null)}><button disabled={busy} onClick={()=>setEditing(null)}>Fechar</button><h2>Classificar {editing.original_filename}</h2><p>A tag organiza o arquivo. Não verifica assinatura digital, não altera OCR, não aprova apuração e não disponibiliza o documento ao cliente automaticamente.</p><form onSubmit={save}><label>Tag<select className="ds-input" name="tag" defaultValue={editing.catalog.tag} disabled={busy}>{documentTags.map(([v,l])=><option key={v} value={v} disabled={['APPROVED','RELEASED'].includes(v)&&!canApprove}>{l}</option>)}</select></label><label>Justificativa e referência no documento<textarea className="ds-input" name="reason" required minLength={20} maxLength={1000} disabled={busy}/></label><label><input type="checkbox" name="checkedDocument" required disabled={busy}/> Conferi o arquivo e a classificação. Em documentos assinados, conferi as assinaturas e a versão correspondente.</label>{error?<p role="alert">{error}</p>:null}<button className="ds-button ds-button--primary" disabled={busy}>{busy?'Salvando…':'Salvar classificação auditada'}</button></form></DocumentDialog>:null}
 {history?<DocumentDialog label="Histórico documental" onClose={()=>setHistory(null)}><button onClick={()=>setHistory(null)}>Fechar</button><h2>Histórico · {history.original_filename}</h2>{historyData?<><h3>Versões do mesmo documento</h3>{historyData.versions.map(v=><p key={v.document_id}>v{v.version} · {documentTags.find(([k])=>k===v.tag)?.[1]} · <button onClick={()=>onPreview(v.document_id)}>Visualizar versão</button></p>)}<h3>Classificações preservadas</h3>{historyData.events.map(e=><article key={e.revision}><strong>Revisão {e.revision} · {documentTags.find(([k])=>k===e.snapshot.tag)?.[1]}</strong><p>{e.reason}</p><small>{new Date(e.recorded_at).toLocaleString('pt-BR')} · Autor {e.actor_id}</small></article>)}</>:<p role="status">Consultando histórico…</p>}</DocumentDialog>:null}
 </section>;
}
