'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers/AuthProvider';
type Preview={organizationId:string;documentId:string;unitId:string;canCorrect:boolean;sourceHash:string;expectedVersion:number;current:{address:string|null;city:string|null;state:string|null};evidence:{text:string;source:string;pages:number[];confidence:number|null}[];message:string};
export default function OcrAddressCorrection({id,onSaved}:{id:string;onSaved:()=>void}){
 const {context,hasPermission}=useAuth();const org=context?.scope==='organization'?context.currentOrganization.id:'';
 const allowed=!!org&&['8f105b02-4443-49de-b188-847e0284e7ed','92e1b670-ab10-483a-b825-c6e16799496d','0f2e539d-03f9-4168-bc8c-55ac3a371628'].every(hasPermission);
 return allowed?<Correction key={JSON.stringify([org,id,context?.user.id])} org={org} id={id} onSaved={onSaved}/>:null;
}
function Correction({org,id,onSaved}:{org:string;id:string;onSaved:()=>void}){
 const [data,setData]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const [address,setAddress]=useState(''),[city,setCity]=useState(''),[state,setState]=useState(''),[reason,setReason]=useState(''),[pdf,setPdf]=useState(false),[unit,setUnit]=useState(false);
 const pending=useRef<AbortController|null>(null),retry=useRef<{body:string;id:string}|null>(null);
 const path='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/address-correction';
 useEffect(()=>()=>pending.current?.abort(),[]);
 async function load(){if(busy)return;pending.current?.abort();const a=new AbortController();pending.current=a;setBusy(true);setError('');setData(null);setDone(false);setPdf(false);setUnit(false);setReason('');retry.current=null;
  try{const d=await apiRequest<Preview>(path,{signal:a.signal,cache:'no-store'});if(a.signal.aborted)return;if(d.organizationId!==org||d.documentId!==id||!d.unitId||!/^[a-f0-9]{64}$/.test(d.sourceHash)||!Number.isSafeInteger(d.expectedVersion)||!Array.isArray(d.evidence))throw Error('Atualize o documento e a organização.');setData(d);setAddress(d.current.address??'');setCity(d.current.city??'');setState(d.current.state??'');}catch(e){if(!a.signal.aborted)setError(e instanceof Error?e.message:'Conferência indisponível.');}finally{if(!a.signal.aborted)setBusy(false);}
 }
 const valid=!!data?.canCorrect&&pdf&&unit&&address.trim().length>=5&&address.length<=180&&city.trim().length>0&&city.length<=60&&reason.trim().length>=20&&reason.length<=500&&!/[\x00-\x1f;]/.test(address+city+reason)&&'AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ').includes(state.trim().toUpperCase())&&[address.trim(),city.trim(),state.trim().toUpperCase()].some((v,i)=>v!==[data.current.address??'',data.current.city??'',data.current.state??''][i]);
 async function save(){if(busy||!valid||!data)return;const fields={address:address.trim(),city:city.trim(),state:state.trim().toUpperCase(),reason:reason.trim(),checkedPdf:pdf,checkedUnit:unit,sourceHash:data.sourceHash,expectedVersion:data.expectedVersion};const signature=JSON.stringify(fields);if(retry.current?.body!==signature)retry.current={body:signature,id:crypto.randomUUID()};const a=new AbortController();pending.current=a;setBusy(true);setError('');
  try{await apiRequest(path,{method:'POST',signal:a.signal,cache:'no-store',body:{...fields,requestId:retry.current.id}});if(!a.signal.aborted){setDone(true);setData(null);onSaved();}}catch(e){if(!a.signal.aborted)setError(e instanceof Error?e.message:'Correção não confirmada. Atualize a conferência.');}finally{if(!a.signal.aborted)setBusy(false);}
 }
 return <section aria-label="Correção cadastral pelo PDF"><h3>Corrigir endereço cadastral conferido no PDF</h3><p>Confira se o PDF pertence à unidade. A correção registra a origem e o histórico; a confiança original do OCR permanece preservada.</p><button type="button" disabled={busy} onClick={()=>void load()}>Comparar endereço para correção</button>{busy&&<p role="status">Processando conferência…</p>}{error&&<p role="alert">{error}</p>}{done&&<p role="status">Endereço cadastral corrigido. Atualize a unidade no mapa e solicite uma nova localização; a sugestão exige conferência.</p>}{data&&<><p>{data.message}</p><p>Cadastro: {data.current.address||'não informado'} · {data.current.city||'cidade ausente'}/{data.current.state||'UF ausente'}</p>{data.evidence.map((e,i)=><div key={i}><p style={{whiteSpace:'pre-wrap'}}>Na fatura: {e.text}</p><small>Origem: {e.source} · página(s): {e.pages.join(', ')} · confiança: {e.confidence===null?'não informada':(e.confidence*100).toFixed(1)+'%'}</small></div>)}{data.canCorrect&&<><fieldset disabled={busy}><legend>Dados cadastrais após conferência</legend><label>Endereço conferido<input value={address} maxLength={180} onChange={e=>setAddress(e.target.value)}/></label><label>Cidade conferida<input value={city} maxLength={60} onChange={e=>setCity(e.target.value)}/></label><label>UF conferida<input value={state} maxLength={2} onChange={e=>setState(e.target.value.toUpperCase())}/></label><label>Justificativa da correção<textarea value={reason} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={pdf} onChange={e=>setPdf(e.target.checked)}/> Conferi o endereço no PDF original.</label><label><input type="checkbox" checked={unit} onChange={e=>setUnit(e.target.checked)}/> Conferi o CNPJ e a UC vinculados ao documento.</label></fieldset><p>Justifique com pelo menos 20 caracteres. A localização anterior ficará pendente se o endereço mudar.</p><button type="button" disabled={busy||!valid} onClick={()=>void save()}>Salvar correção cadastral auditada</button></>}</>}</section>;
}
