'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {ocrContractLink} from '../contracts/ocr-navigation';
type Candidate={ready:boolean;reason:string;description:string|null;source:string|null;amount:string|null;descriptionConfidence:number|null;amountConfidence:number|null;pages:number[]};
type Data={token:string;month:string;state:string;canCreate:boolean;message:string;candidate:Candidate;existing:null|{status:string;version:number;revision:number}};
const percent=(v:number|null)=>v===null?'Não disponível':(v*100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
export function CipEvidence({candidate:c}:{candidate:Candidate}){return <article><h4>Iluminação pública — CIP</h4><p>{c.description??'Descrição não identificada'}</p><p>Valor extraído: <strong>{c.amount===null?'Não identificado':'R$ '+c.amount.replace('.',',')}</strong></p><p>Confiança da descrição: {percent(c.descriptionConfidence)} · Confiança do valor: {percent(c.amountConfidence)}</p><p>{c.reason}</p><small>Origem: {c.source??'Não identificada'} · Página(s): {c.pages.join(', ')||'Não identificadas'}</small></article>;}
export default function OcrCipIntegration({id,onCreated}:{id:string;onCreated:()=>void}){
 const request=useRef(0),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 const url='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/cip-integration';
 async function load(){const n=++request.current;setBusy(true);setData(null);setError('');try{const next=await apiRequest<Data>(url);if(n===request.current)setData(next);}catch{if(n===request.current)setError('Não foi possível consultar a integração CIP. Atualize para conferir a situação.');}finally{if(n===request.current)setBusy(false);}}
 useEffect(()=>{setReceipt('');void load();return()=>{request.current++;};},[id]);
 async function create(){if(!data?.canCreate||busy)return;const n=++request.current;setBusy(true);setError('');try{await apiRequest(url,{method:'POST',body:{token:data.token}});if(n!==request.current)return;setReceipt('CIP registrada em rascunho, com autor e histórico nos custos mensais.');onCreated();await load();}catch{if(n===request.current){setData(null);setError('Não foi possível confirmar a integração. Atualize para verificar se o rascunho foi registrado antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 return <section aria-label="Integração CIP da fatura" style={{marginTop:24,border:'1px solid #405873',borderRadius:12,padding:20}}><h3>CIP da fatura → Custos mensais</h3><p>A contribuição de iluminação pública pode preencher o primeiro rascunho ACL desta unidade e competência. Os registros existentes são preservados.</p><button type="button" disabled={busy} onClick={()=>void load()}>Atualizar integração CIP</button>{busy&&<p role="status">Consultando ou registrando CIP…</p>}{error&&<p role="alert">{error}</p>}{receipt&&<p role="status">{receipt}</p>}{data&&<><p><strong>{data.month}</strong> · {data.message}</p><CipEvidence candidate={data.candidate}/>{data.existing&&<p>Custos mensais: versão {data.existing.version} · revisão {data.existing.revision} · {data.existing.status==='VALIDATED'?'Validada':'Rascunho'}</p>}{data.canCreate&&<button type="button" disabled={busy} onClick={()=>void create()}>Integrar CIP nos custos mensais</button>}<p>Importação parcial: somente CIP. O tratamento tributário fica pendente; confira os demais custos e créditos antes da validação. TE ACL, descontos informativos, subtotais, devoluções e subvenção não são lançados nesta etapa.</p><a href={ocrContractLink(id,'costs')}>Consultar custos mensais e histórico desta unidade</a></>}</section>;
}
