'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {ocrContractLink} from '../contracts/ocr-navigation';
type Data={token:string;month:string;message:string;evidenceReady:boolean;bases:{id:string;component:string;band:string;status:string;approved:boolean;compatible:boolean}[];amounts:{code:string;tusd:string|null;cde:string|null;total:string|null}[];declarations:{id:string;code:string;status:string;revision:number|null;state:string;canUpdate:boolean;canCreateRevision?:boolean;replacement?:{id:string;status:string;revision:number}|null;message:string;linkedBaseCount:number}[]};
export default function OcrCdeTaxes({id,sourceToken,onUpdated}:{id:string;sourceToken:string;onUpdated:()=>void}){
 const request=useRef(0),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 const url='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/cde-tax-integration';
 async function load(){const n=++request.current;setBusy(true);setData(null);setError('');try{const d=await apiRequest<Data>(url);if(n===request.current)setData(d);}catch{if(n===request.current)setError('Não foi possível consultar a conciliação tributária. Atualize antes de tentar novamente.');}finally{if(n===request.current)setBusy(false);}}
 useEffect(()=>{setReceipt('');void load();return()=>{request.current++;};},[id,sourceToken]);
 async function createRevision(code:string){if(busy||!data?.declarations.some(d=>d.code===code&&d.canCreateRevision))return;const n=++request.current;setBusy(true);setError('');try{const result=await apiRequest<{alreadyCreated:boolean;revision:number}>(url+'/revision',{method:'POST',body:{code,token:data.token}});if(n!==request.current)return;setReceipt(code+': '+(result.alreadyCreated?'nova versão já registrada':'nova versão preparada em rascunho')+'. Declaração aprovada preservada. Revise a substituição nos parâmetros.');onUpdated();await load();}catch{if(n===request.current){setData(null);setError('Não foi possível confirmar a nova versão. Atualize para verificar os registros antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 async function update(code:string){if(busy||!data?.declarations.some(d=>d.code===code&&d.canUpdate))return;const n=++request.current;setBusy(true);setError('');try{const result=await apiRequest<{alreadyUpdated:boolean;revision:number}>(url,{method:'POST',body:{code,token:data.token}});if(n!==request.current)return;setReceipt(code+': '+(result.alreadyUpdated?'vínculo já registrado':'bases CDE acrescentadas')+' na revisão '+result.revision+'. Autor e histórico preservados; aprovação separada.');onUpdated();await load();}catch{if(n===request.current){setData(null);setError('Não foi possível confirmar a alteração. Atualize para verificar a revisão antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 const status=(s:string)=>({DRAFT:'Rascunho',APPROVED:'Aprovado',RETIRED:'Retirado de uso',MISSING:'Não registrado'}[s]??s);
 return <section aria-label="Conciliação tributária TUSD e CDE" style={{marginTop:20,padding:16,border:'1px solid #405873',borderRadius:12}}><h4>Vincular CDE aos tributos da distribuidora</h4><p>Acrescente as bases CDE às declarações já cadastradas de ICMS, PIS e Cofins. Os valores abaixo estão incluídos nas tarifas brutas.</p><button type="button" disabled={busy} onClick={()=>void load()}>Atualizar conciliação tributária</button>{busy&&<p role="status">Consultando ou atualizando bases tributárias…</p>}{error&&<p role="alert">{error}</p>}{receipt&&<p role="status">{receipt}</p>}{data&&<><p>{data.month} · {data.message}</p><ul>{data.bases.map(b=><li key={b.id}>{b.component==='TUSD_ENERGY'?'TUSD':'CDE'} {b.band==='PEAK'?'ponta':'fora ponta'}: {status(b.status)}{!b.compatible?' — verificar compatibilidade com a fatura':''}</li>)}</ul>{!data.evidenceReady&&<p>As evidências da fatura precisam de conferência atual antes da integração.</p>}<table><thead><tr><th>Tributo</th><th>TUSD (R$)</th><th>CDE (R$)</th><th>Total já incluído (R$)</th></tr></thead><tbody>{data.amounts.map(v=><tr key={v.code}><td>{v.code}</td><td>{v.tusd??'Conferência necessária'}</td><td>{v.cde??'Conferência necessária'}</td><td>{v.total??'Conferência necessária'}</td></tr>)}</tbody></table>{data.declarations.map(d=><article key={d.code}><h5>{d.code} — {status(d.status)}{d.revision!==null?' · revisão '+d.revision:''}</h5><p>{d.linkedBaseCount} bases vinculadas. {d.message}</p>{d.replacement&&<p>Versão proposta: {status(d.replacement.status)} · revisão {d.replacement.revision}.</p>}{d.canCreateRevision&&<button type="button" disabled={busy} onClick={()=>void createRevision(d.code)}>Preparar nova versão de {d.code} com CDE</button>}{d.canUpdate&&<button type="button" disabled={busy} onClick={()=>void update(d.code)}>Incluir CDE na declaração de {d.code}</button>}</article>)}<a href={ocrContractLink(id,'parameters')}>Revisar e aprovar parâmetros desta unidade</a></>}</section>;
}
