'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
type Preview={token:string;canCreate:boolean;state:string;inputId:string|null;month:string|null;usedKw:string|null;unusedKw:string|null;message:string};
const labels:Record<string,string>={INTEGRATED:'Demanda faturada integrada',READY:'Pronto para integrar demanda faturada',CONSUMPTION_REQUIRED:'Integração dos consumos necessária',UNSUPPORTED:'Enquadramento ainda não contemplado',RECORD_PRESERVED:'Registro mensal preservado',REVIEWS_PENDING:'Classificações pendentes'};
export default function OcrDemandIntegration({id}:{id:string}){
 const {hasPermission}=useAuth(),allowed=hasPermission('60f9690a-145b-4dba-b23f-9f945baca296');
 const [data,setData]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');const request=useRef(0);
 const path='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/demand-integration';
 useEffect(()=>{if(!allowed)return;const n=++request.current;let disposed=false;setData(null);setError('');setReceipt('');setBusy(true);apiRequest<Preview>(path).then(r=>{if(!disposed&&n===request.current)setData(r);}).catch(()=>{if(!disposed&&n===request.current)setError('Não foi possível consultar a integração. Atualize antes de continuar.');}).finally(()=>{if(!disposed&&n===request.current)setBusy(false);});return()=>{disposed=true;request.current++;};},[path,allowed]);
 async function refresh(){const n=++request.current;setData(null);setError('');setBusy(true);try{const r=await apiRequest<Preview>(path);if(n===request.current)setData(r);}catch{if(n===request.current)setError('Não foi possível consultar a integração. Atualize antes de continuar.');}finally{if(n===request.current)setBusy(false);}}
 async function integrate(){if(!data?.canCreate||busy)return;const n=++request.current;setBusy(true);setError('');try{const r=await apiRequest<{inputId:string;alreadyIntegrated:boolean}>(path,{method:'POST',body:{token:data.token}});if(n!==request.current)return;setReceipt(r.alreadyIntegrated?'Demanda faturada já integrada. Nenhum registro duplicado.':'Demanda faturada integrada no mesmo rascunho mensal, com autor e histórico.');setData({...data,canCreate:false,state:'INTEGRATED',inputId:r.inputId,message:'Consulte a demanda faturável ACL e o histórico em Contratos → Dados mensais.'});}catch(e){if(n===request.current){setData(null);setError(e instanceof Error?e.message:'Não foi possível confirmar a integração. Consulte a situação antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 return <section aria-label="Integração da demanda faturada" style={{border:'1px solid #405873',borderRadius:12,padding:20,marginTop:20}}><h3>Demanda faturada → Dados mensais</h3>{!allowed?<p>A consulta exige acesso aos contratos da organização.</p>:<><button type="button" disabled={busy} onClick={()=>void refresh()}>Atualizar integração da demanda</button>{busy&&<p role="status">Consultando ou registrando integração…</p>}{receipt&&<p role="status">{receipt}</p>}{error&&<p role="alert">{error}</p>}{data&&<><p><strong>{labels[data.state]??'Consulte a situação da integração'}</strong></p><p>{data.message}</p>{data.month&&<p>Competência: {data.month}</p>}<dl><dt>Parcelas classificadas como utilizadas</dt><dd>{data.usedKw?.replace('.',',')??'Pendente'} kW</dd><dt>Parcelas classificadas como não utilizadas</dt><dd>{data.unusedKw?.replace('.',',')??'Pendente'} kW</dd></dl>{data.canCreate&&<button type="button" disabled={busy} onClick={()=>void integrate()}>Integrar demanda faturada nos dados mensais</button>}{data.state==='INTEGRATED'&&<p>Consulte a versão em <a href="/backoffice/contracts">Contratos → Dados mensais</a>. A validação das medições permanece separada.</p>}</>}</>}<p>Grupo A Verde no ACL: soma das parcelas faturadas conferidas, com classificação preservada na auditoria. A demanda medida e contratada não são preenchidas por essa soma. Tributos, custos e apuração financeira continuam sujeitos à reconciliação.</p></section>;
}
