'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {ocrContractLink} from '../contracts/ocr-navigation';
type Data={token:string;month:string;evidenceReady:boolean;declarations:{code:string;state:string;canCreate:boolean;included:number;excluded:number;proposed:null|{id:string;status:string;revision:number}}[]};
export default function OcrDemandTaxes({documentId}:{documentId:string}){
 const request=useRef(0),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 const url='/api/v1/documents/'+encodeURIComponent(documentId)+'/ocr/demand-tax-integration';
 async function load(){const n=++request.current;setBusy(true);setData(null);setError('');try{const d=await apiRequest<Data>(url);if(n===request.current)setData(d);}catch{if(n===request.current)setError('Não foi possível consultar os tributos da demanda. Atualize a situação.');}finally{if(n===request.current)setBusy(false);}}
 useEffect(()=>{setReceipt('');void load();return()=>{request.current++;};},[documentId]);
 async function create(code:string){if(busy||!data?.declarations.some(d=>d.code===code&&d.canCreate))return;const n=++request.current;setBusy(true);setError('');try{await apiRequest(url,{method:'POST',body:{code,token:data.token}});if(n!==request.current)return;setReceipt(code+': nova versão preparada, com autor e histórico. Revise e aprove nos parâmetros para substituir a anterior.');await load();}catch{if(n===request.current){setData(null);setError('Não foi possível confirmar a versão. Atualize antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 const labels:Record<string,string>={CREATED:'Versão já preparada',READY:'Disponível para preparar',DECLARATION_REQUIRED:'Aprove a declaração tributária compatível com as bases da fatura',BASE_REVIEW_REQUIRED:'Confira evidências e aprovação das tarifas de demanda',CONFLICT:'Há declarações conflitantes; confira os parâmetros',REVIEW_REQUIRED:'A versão proposta precisa de revisão'};
 return <section aria-label='Tributos das parcelas de demanda'><h4>Integrar demanda às declarações tributárias</h4><p>Preenche as bases das tarifas aprovadas, sem cobrar tributos novamente. A parcela sem ICMS destacado fica fora da declaração de ICMS; isso não presume isenção.</p><button type='button' disabled={busy} onClick={()=>void load()}>Atualizar tributos da demanda</button>{busy&&<p role='status'>Consultando tributos da demanda…</p>}{error&&<p role='alert'>{error}</p>}{receipt&&<p role='status'>{receipt}</p>}{data&&<><p>Competência {data.month}</p>{data.declarations.map(d=><article key={d.code}><h5>{d.code}</h5><p>{labels[d.state]??'Conferência necessária'} · {d.included} bases incluídas · {d.excluded} excluídas</p>{d.proposed&&<p>Nova versão: {d.proposed.status==='APPROVED'?'Aprovada':'Rascunho'} · revisão {d.proposed.revision}</p>}{d.canCreate&&<button type='button' disabled={busy} onClick={()=>void create(d.code)}>Preparar {d.code} com demanda</button>}</article>)}<a href={ocrContractLink(documentId,'parameters')}>Revisar e aprovar declarações tributárias</a></>}</section>;
}
