'use client';
type Field={text:string;decimal:string|null;confidence:number|null;pages:number[];issues:string[]};
type Row={index:number;source:string;component:string;period:string;description:Field;quantity:Field;unit:Field;unitPrice:Field;amount:Field;confidence:number|null;issues:string[]};
export type ElectricalEvidence={version:string;canImport:false;rows:Row[];issues:string[];taxDetails:{index:number;amount:Field;rate:Field;tax:string;basis:string}[]};
const components:Record<string,string>={TE:'Energia — TE',TUSD_ENERGY:'Uso da rede — TUSD',DEMAND_CONTRACTED:'Demanda contratada',DEMAND_MEASURED:'Demanda registrada',DEMAND_UNUSED:'Demanda não utilizada',DEMAND_EXCESS:'Ultrapassagem de demanda',DEMAND_BILLED:'Demanda faturada — conferir natureza',REACTIVE_ENERGY:'Energia reativa',PENALTY:'Multa',INTEREST:'Juros',ICMS:'ICMS',PIS:'PIS',COFINS:'COFINS',IOF:'IOF',OTHER:'Componente não identificado'};
const messages:Record<string,string>={MISSING_VALUE:'Valor ausente',UNVERIFIED_SOURCE:'Origem do trecho não confirmada',MISSING_CONFIDENCE:'Confiança não informada',CONFIDENCE_BELOW_45:'Abaixo de 45%: automação rejeitada',CONFIDENCE_REQUIRES_REVIEW:'Conferência humana obrigatória',INVALID_DECIMAL:'Formato numérico requer conferência',NON_BRL_CURRENCY:'Moeda diferente de BRL',UNMAPPED_COMPONENT:'Classificação não identificada',ENERGY_UNIT_UNVERIFIED:'Confirmar unidade kWh ou MWh',DEMAND_UNIT_UNVERIFIED:'Confirmar unidade kW',REACTIVE_UNIT_UNVERIFIED:'Confirmar unidade kVArh',TARIFF_PERIOD_UNSPECIFIED:'Posto tarifário não identificado ou ambíguo',CREDIT_REQUIRES_REVIEW:'Valor negativo: conferir crédito ou estorno',FIELD_REVIEW_REQUIRED:'Existem campos que precisam de conferência',ITEM_LIMIT_REACHED:'Quantidade de linhas excede o limite desta visualização',TABLES_REQUIRE_COVERAGE_REVIEW:'Conferir se todas as tabelas estão representadas nos itens extraídos',UNMAPPED_TABLE:'Há tabela sem estrutura reconhecida',AMBIGUOUS_TABLE_ROW:'Há linha de tabela ambígua',TABLE_LIMIT_REACHED:'Quantidade de tabelas excede o limite desta visualização',NO_ITEM_ROWS:'Nenhuma linha de cobrança reconhecida',UNMAPPED_ITEMS:'Há componentes não identificados',TAX_LIMIT_REACHED:'Quantidade de tributos excede o limite desta visualização',INVOICE_COUNT_NOT_ONE:'Não foi identificada exatamente uma fatura'};
function Value({label,field}:{label:string;field:Field}){return <div style={{padding:'8px 0',borderBottom:'1px solid var(--color-border, #334155)'}}><dt style={{fontWeight:600}}>{label}</dt><dd style={{margin:0,overflowWrap:'anywhere'}}>{field.text||'Não identificado'}{field.decimal!==null&&<small style={{display:'block'}}>Valor interpretado: {field.decimal}</small>}<small style={{display:'block'}}>Confiança: {field.confidence===null?'não informada':(field.confidence*100).toFixed(0)+'%'} · Página(s): {field.pages.join(', ')||'não confirmada'}</small>{field.issues.length>0&&<small>{field.issues.map(i=>messages[i]??'Conferência necessária').join(' · ')}</small>}</dd></div>;}
export default function OcrElectricalEvidence({evidence}:{evidence:ElectricalEvidence}){return <details style={{marginTop:12}}><summary>Componentes extraídos ({evidence.rows.length}) — conferir</summary>
 <p>Valores candidatos, sem aprovação ou lançamento financeiro. TE e TUSD permanecem separados; seus consumos não são somados. A tarifa pode conter tributos: a base ainda precisa ser conferida.</p>
 {evidence.issues.length>0&&<ul>{evidence.issues.map(i=><li key={i}>{messages[i]??'Conferência necessária'}</li>)}</ul>}
 {evidence.rows.map(row=><details key={row.source} style={{padding:12,marginTop:8,border:'1px solid var(--color-border, #334155)',borderRadius:8}}><summary>{row.index+1}. {components[row.component]??'Componente não identificado'} · {row.period==='PEAK'?'Ponta':row.period==='OFF_PEAK'?'Fora ponta':'Posto a conferir'}</summary><dl><Value label="Descrição original" field={row.description}/><Value label="Quantidade" field={row.quantity}/><Value label="Unidade" field={row.unit}/><Value label="Tarifa / preço unitário" field={row.unitPrice}/><Value label="Valor da linha" field={row.amount}/></dl>{row.issues.length>0&&<ul>{row.issues.map(i=><li key={i}>{messages[i]??'Conferência necessária'}</li>)}</ul>}</details>)}
 {evidence.taxDetails.length>0&&<details><summary>Tributos sem identificação confirmada ({evidence.taxDetails.length})</summary><p>Não atribuímos estes valores a ICMS, PIS, Cofins ou IOF sem evidência. Não são somados novamente ao total da fatura.</p>{evidence.taxDetails.map(t=><dl key={t.index}><Value label="Valor do tributo" field={t.amount}/><Value label="Alíquota registrada" field={t.rate}/></dl>)}</details>}
 </details>;}
