'use client';
import {useOriginalInvoice} from './OcrOriginalInvoice';
import {useRef,useState} from 'react';
import {apiRequest,ApiError} from '@/app/lib/api/client';
type Review={id:string;version:number;sourceHash:string;decision:string;note:string;author:string;createdAt:string;value:string|null;unit:string};
type Field={key:string;label:string;unit:string;decimal:string|null;state:string;sourceHash:string;history:Review[];hasOlder:boolean};
type Data={canImport:false;message:string;fields:Field[]};
function FieldReview({field:f,id,canReview,onSaved}:{field:Field;id:string;canReview:boolean;onSaved:()=>Promise<void>}){
 const [decision,setDecision]=useState(''),[note,setNote]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const attempt=useRef<{body:unknown;key:string}|null>(null);const last=f.history[0];
 async function save(){if(busy)return;setBusy(true);setError('');setSuccess('');const draft={fieldKey:f.key,sourceHash:f.sourceHash,decision,note,expectedReviewId:last?.id??null,checkedPdf:checked};const key=JSON.stringify(draft);if(attempt.current?.key!==key)attempt.current={key,body:{...draft,requestId:crypto.randomUUID()}};
 try{await apiRequest('/api/v1/documents/'+encodeURIComponent(id)+'/ocr/reviews',{method:'POST',body:attempt.current.body});attempt.current=null;setSuccess('Conferência salva. O cálculo permanece sem alteração.');setDecision('');setChecked(false);setNote('');await onSaved();}catch(e){setError(e instanceof ApiError?e.message:'Não foi possível confirmar o salvamento. Consulte o histórico; ao repetir sem alterar os dados, a mesma solicitação será usada.');}finally{setBusy(false);}}
 return <article style={{border:'1px solid #40516b',borderRadius:10,padding:16,margin:'16px 0'}}><h3>{f.label}</h3><p style={{fontSize:24}}>{f.decimal===null?'Valor a conferir':f.decimal.replace('.',',')+' '+f.unit}</p><p>{last?last.sourceHash!==f.sourceHash?'A prévia mudou desde a última conferência.':last.decision==='CONFIRMED'?'Conferido no PDF — não é aprovação financeira':'Correção solicitada':'Ainda sem conferência registrada.'}</p>
 {canReview&&<fieldset disabled={busy}><legend>Registrar conferência deste campo</legend><label>Resultado<select aria-label={'Resultado — '+f.label} value={decision} onChange={e=>setDecision(e.target.value)}><option value="">Selecione</option><option value="CONFIRMED" disabled={f.state!=='EXTRACTED_REVIEW'||f.decimal===null}>Conferido no PDF original</option><option value="NEEDS_CORRECTION">Precisa de correção</option></select></label>{decision==='CONFIRMED'&&<label style={{display:'block',margin:'12px 0'}}><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Conferi este valor no PDF original da unidade e competência.</label>}<label style={{display:'block'}}>Observação {decision==='NEEDS_CORRECTION'?'(obrigatória)':'(opcional)'}<textarea aria-label={'Observação — '+f.label} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} style={{display:'block',width:'100%'}}/></label><button type="button" disabled={busy||!decision||(decision==='CONFIRMED'&&!checked)||(decision==='NEEDS_CORRECTION'&&note.trim().length<3)} onClick={()=>void save()}>{busy?'Salvando…':'Salvar conferência'}</button></fieldset>}
 {error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
 <details><summary>Histórico deste campo ({f.history.length}{f.hasOlder?' mais recentes':''})</summary>{f.history.map(r=><article key={r.id}><p><strong>Versão {r.version} · {r.decision==='CONFIRMED'?'Conferido no PDF':'Precisa de correção'}</strong></p><p>{r.author} · {new Date(r.createdAt).toLocaleString('pt-BR')}</p><p>Valor da época: {r.value===null?'Não definido':r.value.replace('.',',')+' '+r.unit}</p>{r.note&&<p>{r.note}</p>}</article>)}{!f.history.length&&<p>Nenhum registro.</p>}{f.hasOlder&&<p>Mostrando os dez registros mais recentes; versões anteriores permanecem preservadas.</p>}</details></article>;
}
export default function OcrFieldReviews({id,canReview}:{id:string;canReview:boolean}){
 const original=useOriginalInvoice(id);
 const dialog=useRef<HTMLDialogElement>(null);const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');try{setData(await apiRequest<Data>('/api/v1/documents/'+encodeURIComponent(id)+'/ocr/reviews'));}catch{setError('Não foi possível carregar a conferência. Os registros anteriores permanecem preservados.');}finally{setBusy(false);}}
 return <section><button type="button" onClick={()=>{dialog.current?.showModal();void load();}}>Conferir consumo no PDF</button><dialog ref={dialog} aria-label="Conferência dos campos de consumo" style={{width:'min(1000px,94vw)',maxHeight:'90vh',overflow:'auto',background:'#101b2c',color:'#f0f5ff',border:'1px solid #536984',borderRadius:16,padding:24}}><button type="button" onClick={()=>dialog.current?.close()}>Fechar conferência</button><h2>Conferência dos campos de consumo</h2><p>Confira cada valor no arquivo original antes de registrar. Isso não altera o cadastro nem aprova a apuração.</p><button type="button" onClick={()=>void original.open?.()}>Abrir fatura original para conferir</button><button type="button" disabled={busy} onClick={()=>void load()}>Atualizar histórico</button>{busy&&<p role="status">Carregando…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.message}</p>{!data.fields.length&&<p>Este layout ainda não possui campos de consumo disponíveis para conferência.</p>}{data.fields.map(f=><FieldReview key={f.key} field={f} id={id} canReview={canReview&&!busy&&!error} onSaved={load}/>)}</>}</dialog>{original.viewer}</section>;
}
