'use client';
type Field={text:string;decimal:string|null;confidence:number|null;pages:number[];issues:string[]};
export type GdEvidence={version:string;detected:boolean;canImport:false;records:{source:string;kind:string;label:Field;value:Field;unit:string|null;issues:string[]}[];issues:string[]};
const labels:Record<string,string>={CONSUMED:'Consumo GD',INJECTED:'Energia injetada',COMPENSATED:'Energia compensada',CREDIT_OPENING:'Saldo anterior de créditos',CREDIT_CLOSING:'Saldo de créditos',CREDIT_RECEIVED:'Créditos recebidos',CREDIT_USED:'Créditos utilizados',CREDIT_EXPIRED:'Créditos expirados',ALLOCATION_PERCENT:'Percentual de rateio'};
const messages:Record<string,string>={GD_PARTICIPATION_VALUE_AMBIGUOUS:'O valor associado ao cabeçalho GD é ambíguo; não comprova geração ou compensação.',GD_VALUES_NOT_RECONCILED:'Os valores ainda precisam ser conciliados com a fatura completa.',GD_PROFILE_AND_VALIDITY_REQUIRE_REVIEW:'Confirmar perfil GD, unidade geradora/beneficiária e vigência.',GD_MULTIPLE_CANDIDATES_NO_SUM:'Há mais de uma ocorrência da mesma informação. Elas não foram somadas.',GD_LIMIT_REACHED:'Extração parcial: limite de leitura atingido.',GD_UNIT_UNVERIFIED:'Unidade de medida não confirmada.',GD_SIGN_REVIEW:'Conferir sinal do crédito ou estorno.',GD_PERCENT_OUT_OF_RANGE:'Percentual fora de 0 a 100%.',MISSING_VALUE:'Valor não identificado.',UNVERIFIED_SOURCE:'Origem do trecho não confirmada.',MISSING_CONFIDENCE:'Confiança não informada.',CONFIDENCE_BELOW_45:'Confiança abaixo de 45%: rejeitar automação.',CONFIDENCE_REQUIRES_REVIEW:'Confiança exige conferência pelo Expert.',INVALID_DECIMAL:'Número precisa de conferência.',INVOICE_COUNT_NOT_ONE:'Não foi identificada exatamente uma fatura.'};
export default function OcrGdEvidence({evidence}:{evidence:GdEvidence}){return <details style={{marginTop:12}}><summary>GD — compensação, créditos e rateio ({evidence.records.length})</summary>
 <p>{evidence.detected?'Há indícios de GD que precisam de conferência.':'Nenhum campo GD reconhecido com os rótulos disponíveis. Isso não confirma ausência de GD.'}</p>
 <p>Os candidatos abaixo não alteram o cadastro ou o cálculo. Créditos em energia e valores em reais são tratados separadamente. Rateio de GD é diferente do rateio de honorários.</p>
 {evidence.issues.length>0&&<ul>{evidence.issues.map(i=><li key={i}>{messages[i]??'Conferência necessária.'}</li>)}</ul>}
 {evidence.records.map(r=><div key={r.source} style={{border:'1px solid var(--color-border, #334155)',padding:12,marginTop:8,borderRadius:8}}><strong>{labels[r.kind]??r.kind}</strong><p>{r.label.text}: {r.value.text||'Não identificado'}</p><p>Valor interpretado: {r.value.decimal??'não confirmado'} · Unidade: {r.unit??'não confirmada'}</p><p>Confiança: {r.value.confidence===null?'não informada':(r.value.confidence*100).toFixed(0)+'%'} · Página(s): {r.value.pages.join(', ')||'não confirmada'}</p>{r.issues.length>0&&<ul>{r.issues.map(i=><li key={i}>{messages[i]??'Conferência necessária.'}</li>)}</ul>}</div>)}
 </details>;}
