'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import OcrAddressCorrection from './OcrAddressCorrection';
import OcrIdentityReviews from './OcrIdentityReviews';
import {useOriginalInvoice} from './OcrOriginalInvoice';
type Data={canImport:false;checkedAt:string;historicalCheckedAt:string;matched:number;total:number;registrationAvailable:boolean;duplicate:boolean;message:string;checks:{key:string;label:string;expected:string|null;state:string;comparison:string;message:string;candidates:{text:string;source:string;pages:number[];confidence:number|null;issues:string[]}[]}[]};
const labels:Record<string,string>={MATCH:'Compatível com o cadastro atual',MISMATCH:'Divergência identificada',REVIEW:'Conferência necessária',MISSING:'Campo não localizado',AMBIGUOUS:'Origem ambígua ou conflitante',REGISTRATION_MISSING:'Cadastro incompleto',UNSUPPORTED:'Layout não suportado nesta comparação'};
export default function OcrIdentityPreview({id}:{id:string}){
 const dialog=useRef<HTMLDialogElement>(null),original=useOriginalInvoice(id);const [revision,setRevision]=useState(0),[result,setResult]=useState<{key:string;data:Data|null;error:string}|null>(null);const requestKey=JSON.stringify([id,revision]),active=result?.key===requestKey,data=active?result.data:null,error=active?result.error:'',busy=revision>0&&!active;
 useEffect(()=>{if(!revision)return;let current=true;apiRequest<Data>('/api/v1/documents/'+encodeURIComponent(id)+'/ocr/identity-preview').then(d=>{if(current){if(d.canImport!==false||!Array.isArray(d.checks))throw new Error('Invalid preview');setResult({key:requestKey,data:d,error:''});}}).catch(()=>{if(current)setResult({key:requestKey,data:null,error:'Não foi possível comparar o cadastro atual. Atualize a consulta; a conferência histórica permanece preservada.'});});return ()=>{current=false;};},[id,revision,requestKey]);
 return <section><button type="button" onClick={()=>{setRevision(v=>v+1);dialog.current?.showModal();}}>Conferir identidade e competência</button><dialog ref={dialog} aria-label="Identidade e competência da fatura" style={{width:'min(1100px,94vw)',maxHeight:'90vh',overflow:'auto',background:'#101b2c',color:'#f0f5ff',border:'1px solid #536984',borderRadius:16,padding:24}}><button type="button" onClick={()=>dialog.current?.close()}>Fechar identidade</button><h2>Identidade e competência da fatura</h2><p>Compare os campos extraídos com o cliente e a unidade vinculados ao documento. Não ajuste o cadastro apenas para fazê-lo coincidir com uma fatura de outra unidade.</p><button type="button" onClick={()=>void original.open?.()}>Abrir PDF para conferir identidade</button><button type="button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>Atualizar comparação cadastral</button>{busy&&<p role="status">Consultando cadastro atual…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.message}</p><p>{data.matched} de {data.total} campos compatíveis com origem e confiança suficientes para esta comparação. Isso não é uma taxa de precisão do OCR.</p><p>Cadastro consultado em {new Date(data.checkedAt).toLocaleString('pt-BR')} · diagnóstico histórico de {new Date(data.historicalCheckedAt).toLocaleString('pt-BR')}</p>{!data.registrationAvailable&&<p role="alert">Cliente ou unidade vinculada indisponível.</p>}<p>{data.duplicate?'Existe outro documento da distribuidora nesta unidade e competência. Conferir duplicidade ou reemissão.':'Nenhum outro documento da distribuidora encontrado nesta unidade e competência nesta consulta.'}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16}}>{data.checks.map(c=><article key={c.key} style={{border:'1px solid #40516b',borderRadius:12,padding:16}}><h3>{c.label}</h3><strong>{labels[c.state]??'Conferência necessária'}</strong><p>{c.message}</p><p><strong>Cadastro atual:</strong> {c.expected||'Não informado'}</p><strong>Na fatura:</strong>{c.candidates.length?c.candidates.map((f,i)=><div key={f.source+i}><p style={{whiteSpace:'pre-wrap'}}>{f.text}</p><small>Confiança do campo: {f.confidence===null?'não informada':(f.confidence*100).toFixed(1)+'%'} · Página(s): {f.pages.join(', ')||'não identificada'}</small><details><summary>Origem na leitura</summary><p>{f.source}</p></details></div>):<p>Não localizado com origem reconhecida.</p>}</article>)}</div><OcrAddressCorrection id={id} onSaved={()=>setRevision(v=>v+1)}/><OcrIdentityReviews key={id+revision} id={id}/><p>Importação automática continua bloqueada até a conclusão das validações do layout e da apuração.</p></>}</dialog>{original.viewer}</section>;
}
