'use client';
import {useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import OcrReviewField,{type ReviewField} from './OcrReviewField';
type Data={canReview:boolean;canImport:false;message:string;fields:ReviewField[]};
export default function OcrIdentityReviews({id}:{id:string}){
 const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[session,setSession]=useState(0);const request=useRef(0);
 async function load(){const version=++request.current;setBusy(true);setError('');try{const next=await apiRequest<Data>('/api/v1/documents/'+encodeURIComponent(id)+'/ocr/identity-reviews');if(next.canImport!==false||!Array.isArray(next.fields))throw new Error('Invalid response');if(version===request.current)setData(next);}catch{if(version===request.current)setError('Não foi possível consultar as conferências de identidade. Tente atualizar; registros anteriores permanecem preservados.');}finally{if(version===request.current)setBusy(false);}}
 return <section aria-label="Conferência auditável da identidade"><h3>Registrar conferência de identidade e competência</h3><p>Gestor ou Administrador pode registrar a conferência no PDF, com justificativa. A confiança original do OCR permanece preservada. Divergências cadastrais e duplicidade impedem confirmação.</p><button type="button" disabled={busy} onClick={()=>{setSession(s=>s+1);void load();}}>{data?'Atualizar histórico de identidade':'Carregar campos para conferência'}</button>{busy&&<p role="status">Consultando conferências…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.message}</p><p><strong>{data.fields.filter(f=>f.history[0]?.sourceHash===f.sourceHash&&f.history[0]?.decision==='CONFIRMED').length} de {data.fields.length} campos com conferência humana vigente.</strong> Essa contagem não representa a precisão do OCR.</p>{!data.canReview&&<p>Somente Gestor ou Administrador pode registrar esta conferência.</p>}{data.fields.map(f=><OcrReviewField key={id+f.key+f.sourceHash} identity session={session} field={f} id={id} canReview={data.canReview&&!busy&&!error} onSaved={load}/>)}</>}</section>;
}
