'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
type Preview={token:string;canCreate:boolean;state:string;inputId:string|null;integratedAt:string|null;existingStatus:string|null;month:string;values:{label:string;decimal:string|null;unit:string}[];message:string};
export default function OcrMonthlyIntegration({id}:{id:string}){
 const {hasPermission}=useAuth(),allowed=hasPermission('60f9690a-145b-4dba-b23f-9f945baca296');
 const [data,setData]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');const request=useRef(0);
 const path='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/monthly-integration';
 useEffect(()=>{if(!allowed)return;const n=++request.current;let disposed=false;setBusy(true);apiRequest<Preview>(path).then(r=>{if(!disposed&&n===request.current)setData(r);}).catch(()=>{if(!disposed&&n===request.current)setError('Não foi possível consultar a integração. Atualize antes de continuar.');}).finally(()=>{if(!disposed&&n===request.current)setBusy(false);});return()=>{disposed=true;request.current++;};},[path,allowed]);
 async function refresh(){const n=++request.current;setData(null);setError('');setBusy(true);try{const r=await apiRequest<Preview>(path);if(n===request.current)setData(r);}catch{if(n===request.current)setError('Não foi possível consultar a integração. Atualize antes de continuar.');}finally{if(n===request.current)setBusy(false);}}
 async function integrate(){if(!data?.canCreate||busy)return;setBusy(true);setError('');try{const r=await apiRequest<{inputId:string;alreadyIntegrated:boolean}>(path,{method:'POST',body:{token:data.token}});setReceipt(r.alreadyIntegrated?'Consumos já integrados. Nenhum registro duplicado.':'Consumos integrados e rascunho mensal salvo com histórico.');setData({...data,canCreate:false,state:'INTEGRATED',inputId:r.inputId,message:'Consulte o rascunho e o histórico em Contratos → Dados mensais.'});}catch(e){setData(null);setError(e instanceof Error?e.message:'Não foi possível confirmar a integração. Consulte a situação antes de tentar novamente.');}finally{setBusy(false);}}
 return <section aria-label="Integração dos consumos" style={{border:'1px solid #405873',borderRadius:12,padding:20,marginTop:20}}><h3>Consumos → Dados mensais</h3>{!allowed?<p>A consulta exige acesso aos contratos da organização.</p>:<><button type="button" disabled={busy} onClick={()=>void refresh()}>Atualizar integração dos consumos</button>{busy&&<p role="status">Consultando ou registrando integração…</p>}{receipt&&<p role="status">{receipt}</p>}{error&&<p role="alert">{error}</p>}{data&&<><p><strong>{data.state==='INTEGRATED'?'Consumos integrados':data.state==='READY'?'Pronto para criar rascunho':data.state==='EXISTING_RECORD'?'Registro mensal existente — preservado':'Conferências pendentes'}</strong></p><p>{data.message}</p><p>Competência: {data.month}</p><ul>{data.values.map(v=><li key={v.label}>{v.label}: {v.decimal?.replace('.',',')??'Não informado'} {v.unit}</li>)}</ul>{data.canCreate&&<button type="button" disabled={busy} onClick={()=>void integrate()}>Integrar consumos nos dados mensais</button>}{data.state==='INTEGRATED'&&<p>Abra <a href="/backoffice/contracts">Contratos</a>, selecione o cliente e consulte a unidade e a competência em <strong>Dados mensais</strong>. A validação das medições é uma etapa separada.</p>}</>}</>}<p>Esta integração preenche somente os três consumos conferidos. Demanda medida, energia reativa, tarifas e custos não são inferidos. Nenhuma apuração é aprovada automaticamente.</p></section>;
}
