'use client';
type Field={text:string;decimal:string|null;confidence:number|null;pages:number[];issues:string[]};
export type MeasurementEvidence={canImport:false;issues:string[];meterReadings:{source:string;kind:string;period:string;unit:string|null;fields:Record<string,Field>;issues:string[]}[];history:{source:string;reference:string|null;metric:string;period:string;unit:string;decimal:string|null;days:number|null;evidence:Field[];issues:string[]}[]};
const cell={padding:12,textAlign:'left' as const,verticalAlign:'top' as const,borderBottom:'1px solid #40516b'};
const period=(p:string)=>p==='PEAK'?'Ponta':p==='OFF_PEAK'?'Fora ponta':'Posto a conferir';
const number=(v:string|null)=>v===null?'A conferir':v.replace('.',',');
function Source({fields}:{fields:Field[]}){const present=fields.filter(f=>f.text.trim());const known=present.filter(f=>f.confidence!==null);const pages=Array.from(new Set(present.flatMap(f=>f.pages)));return <small>Confiança: {known.length===present.length&&known.length?(Math.min(...known.map(f=>f.confidence!))*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'% (menor valor informado)':'não informada para todos os campos'} · {pages.length?'p. '+pages.join(', '):'página a conferir'}</small>;}
export default function OcrMeasurements({evidence:e}:{evidence:MeasurementEvidence}){
 const refs=Array.from(new Set(e.history.flatMap(r=>r.reference?[r.reference]:[]))).sort().reverse();
 const series=[['CONSUMPTION','PEAK','Consumo ponta (kWh)'],['CONSUMPTION','OFF_PEAK','Consumo fora ponta (kWh)'],['DEMAND','PEAK','Demanda ponta (kW)'],['DEMAND','OFF_PEAK','Demanda fora ponta (kW)']];
 return <section aria-label="Medições e histórico estruturados"><h3>Leituras dos medidores</h3><p>Valores transcritos do quadro de medição. Podem estar arredondados; não substituem automaticamente os valores faturados nem as medições validadas.</p>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><caption>Equipamentos, postos e leituras da fatura</caption><thead><tr>{['Grandeza / posto','Medidor','Leitura anterior','Leitura atual','Constante','Valor apresentado','Conferência'].map(h=><th style={cell} scope="col" key={h}>{h}</th>)}</tr></thead><tbody>{e.meterReadings.map(r=><tr key={r.source}><th style={cell} scope="row">{r.fields.quantityKind?.text||'Grandeza a conferir'}<br/>{period(r.period)}</th>{['meter','previous','current','constant'].map(k=><td style={cell} key={k}>{r.fields[k]?.text||'Não identificado'}</td>)}<td style={cell}>{r.fields.reading?.text||'Não identificado'} {r.unit??'· unidade a conferir'}</td><td style={cell}><Source fields={Object.values(r.fields)}/><p>{r.issues.length?'Revisão necessária':'Aguarda homologação'}</p></td></tr>)}</tbody></table></div>{!e.meterReadings.length&&<p>Quadro de medição não reconhecido.</p>}
 <h3>Histórico de consumo e demanda</h3><p>{refs.length} competências identificadas. O histórico é informativo e mantém os arredondamentos da fatura. Valores repetidos ou ambíguos exigem conferência.</p>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><caption>Histórico mensal por posto horário</caption><thead><tr><th style={cell} scope="col">Competência</th>{series.map(([m,p,label])=><th style={cell} scope="col" key={m+p}>{label}</th>)}</tr></thead><tbody>{refs.map(ref=><tr key={ref}><th style={cell} scope="row">{ref.slice(5)+'/'+ref.slice(0,4)}</th>{series.map(([m,p])=>{const candidates=e.history.filter(r=>r.reference===ref&&r.metric===m&&r.period===p);const r=candidates.length===1?candidates[0]:null;return <td style={cell} key={m+p}>{r?<><strong>{number(r.decimal)}</strong><br/><small>{r.days===null?'Dias a conferir':r.days+' dias faturados'}</small><br/><Source fields={r.evidence}/>{r.issues.length>0&&<p><small>Conferir evidência</small></p>}</>:candidates.length?'Múltiplos valores — conferir':'Não identificado'}</td>;})}</tr>)}</tbody></table></div>
 <details><summary>Evidências e pendências do histórico ({e.history.length} registros)</summary>{e.history.map(r=><article key={r.source} style={{padding:12,borderBottom:'1px solid #40516b'}}><strong>{r.reference??'Competência a conferir'} · {r.metric==='CONSUMPTION'?'Consumo':'Demanda'} · {period(r.period)}</strong><p style={{whiteSpace:'pre-wrap'}}>{r.evidence.map(f=>f.text).join(' | ')}</p><Source fields={r.evidence}/><p>{r.issues.some(i=>i!=='HISTORY_FIELD_REVIEW_REQUIRED')?'Revisão necessária: competência, valor, dias ou duplicidade. Consulte o trecho original.':r.issues.length?'Confiança ou origem requer conferência.':'Aguarda homologação.'}</p></article>)}</details>
 {e.issues.length>0&&<p role="status">Parte do quadro exige revisão de estrutura ou excede o limite de leitura.</p>}
 </section>;
}
