'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
type Value={decimal:string|null;unit:string;source:string};
type Data={month:string;message:string;demand:{key:string;label:string;state:string;meter:Value|null;history:Value|null;message:string}[];reactive:{state:string;targetUnit:string;sources:{source:string;period:string;decimal:string|null;unit:string|null}[];message:string};monthly:null|{version:number;revision:number;status:string;measurements:Record<string,string|null>}};
const labels:Record<string,string>={SCOPE_REVIEW:'Conferir layout e competência',AMBIGUOUS:'Mais de uma origem candidata',MISSING:'Valor não identificado',SOURCE_REVIEW:'Origem exige conferência',DIFFERENT_REPRESENTATIONS:'Valores diferentes no quadro e no histórico',REVIEW_REQUIRED:'Precisão e finalidade exigem conferência',UNIT_REVIEW:'Unidade da cobrança diferente do campo mensal'};
const number=(v:string|null|undefined)=>v==null?'Não informado':v.replace('.',',');
export default function OcrMeasurementReadiness({id}:{id:string}){
 const {hasPermission}=useAuth(),allowed=hasPermission('60f9690a-145b-4dba-b23f-9f945baca296');const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef(0);const path='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/measurement-readiness';
 useEffect(()=>{if(!allowed)return;let active=true;const n=++request.current;setData(null);setError('');setBusy(true);apiRequest<Data>(path).then(d=>{if(active&&request.current===n)setData(d);}).catch(()=>{if(active&&request.current===n)setError('Não foi possível consultar as pendências das medições.');}).finally(()=>{if(active&&request.current===n)setBusy(false);});return()=>{active=false;request.current++;};},[path,allowed]);
 async function refresh(){const n=++request.current;setData(null);setError('');setBusy(true);try{const d=await apiRequest<Data>(path);if(request.current===n)setData(d);}catch{if(request.current===n)setError('Não foi possível consultar as pendências das medições.');}finally{if(request.current===n)setBusy(false);}}
 return <section aria-label="Demanda medida e reativo para integração" style={{border:'1px solid #405873',borderRadius:12,padding:20,marginTop:20}}><h3>Demanda medida e reativo — pendências específicas</h3>{!allowed?<p>A consulta exige acesso aos contratos da organização.</p>:<><button type="button" disabled={busy} onClick={()=>void refresh()}>Atualizar pendências das medições</button>{busy&&<p role="status">Consultando evidências e dados mensais…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.message}</p><p>Competência: {data.month}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,260px),1fr))',gap:16}}>{data.demand.map(d=><article key={d.key}><h4>{d.label}</h4><strong>{labels[d.state]}</strong><p>Quadro de medição: {number(d.meter?.decimal)}{d.meter?' kW':''}</p><p>Histórico da mesma competência: {number(d.history?.decimal)}{d.history?' kW':''}</p><p>{d.message}</p><details><summary>Origens da conferência</summary><p>Quadro: {d.meter?.source??'Não identificado'}</p><p>Histórico: {d.history?.source??'Não identificado'}</p></details></article>)}</div><h4>Energia reativa excedente</h4><strong>{labels[data.reactive.state]}</strong><p>{data.reactive.message}</p><ul>{data.reactive.sources.map((s,i)=><li key={s.source+'-'+i}>{s.period==='PEAK'?'Ponta':s.period==='OFF_PEAK'?'Fora ponta':'Posto não definido'}: {number(s.decimal)} {s.unit??'unidade não identificada'} · origem {s.source}</li>)}</ul><h4>Valores presentes nos dados mensais</h4>{data.monthly?<><p>Versão {data.monthly.version} · Revisão {data.monthly.revision} · {data.monthly.status==='VALIDATED'?'Validada':'Rascunho'}</p><dl>{Object.entries({demandSingle:'Demanda medida única (kW)',demandPeak:'Demanda medida na ponta (kW)',demandOffPeak:'Demanda medida fora ponta (kW)',reactiveTotal:'Reativo excedente (kVArh)'}).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{number(data.monthly!.measurements[key])}</dd></div>)}</dl></>:<p>Nenhum registro mensal nesta unidade e competência.</p>}<p>Para resolver: confira uma fonte que identifique a grandeza, a unidade e a precisão. Em <a href="/backoffice/contracts">Contratos → Dados mensais</a>, selecione a mesma unidade e competência e use Editar medições. O complemento manual de um rascunho OCR exige justificativa e fica no histórico com o autor. Não use a demanda faturada como medição.</p></>}</>}</section>;
}
