'use client';
import {Eye,SquareArrowOutUpRight} from 'lucide-react';
import type {OcrAutofill} from '../contracts/ocr-autofill';
import type {OcrDestination} from '../contracts/ocr-navigation';
import type {ReadoutSummary} from './OcrReadout';
type Props={unit:string;month:string;confidence:ReadoutSummary;prefilled?:OcrAutofill;fields:{kind:string;key:string;label:string;value:string|null;unit:string;source:string;confirmed:boolean}[];values:{key:string;label:string;value:string|null;unit:string}[];onReview:()=>void;onOpen:(area:OcrDestination)=>void;disabled:boolean};
export default function OcrOverview({unit,month,confidence,prefilled,fields,values,onReview,onOpen,disabled}:Props){
 const pending=fields.filter(f=>!f.confirmed),stats=confidence.fieldConfidence;
 const cards=[{key:'consumption',title:'Consumo e demanda',area:'monthly' as const},{key:'costs',title:'Valores e tributos da fatura',area:'costs' as const},{key:'market',title:'Mercado livre',area:'supply' as const},{key:'audit',title:'Auditoria e conferência',area:'preparation' as const}];
 return <section aria-label="Resumo da inteligência energética" className="bot-overview"><header><div><h3>{unit}</h3><p>Competência {month} · valores extraídos e propostas para conferência</p></div><p>{pending.length} campo(s) a conferir · {fields.filter(f=>f.confirmed).length} conferência(s) salva(s)</p></header><details><summary>Identificação da fatura e fontes</summary>{fields.filter(f=>f.kind==='identity').map(f=><p key={f.key}><strong>{f.label}:</strong> {f.value??'Não identificado'} · {f.confirmed?'Conferido':'Conferência pendente'}<small>{f.source||'Fonte não identificada'}</small></p>)}</details><div className="bot-overview-grid">{cards.map(card=><article key={card.key} className="bot-overview-card"><header><h4>{card.title}</h4><div className="bot-overview-actions"><button type="button" aria-label={'Conferir '+card.title} title={'Conferir '+card.title} disabled={disabled} onClick={onReview}><Eye size={18} aria-hidden="true"/></button><button type="button" aria-label={'Abrir '+card.title} title={'Abrir '+card.title} disabled={disabled} onClick={()=>onOpen(card.area)}><SquareArrowOutUpRight size={18} aria-hidden="true"/></button></div></header>{card.key==='consumption'?<><dl>{values.filter(v=>/consumption|demand|reactive/i.test(v.key)).map(v=><div key={v.key}><dt>{v.label}</dt><dd>{v.value??'Não identificado'} {v.unit}</dd></div>)}</dl><p>Demanda medida e demanda faturada são conferidas separadamente.</p></>:card.key==='costs'?<><dl>{(prefilled?.taxes??[]).map(t=><div key={t.code}><dt>{t.code}</dt><dd>{t.rate}%<small>{t.source}</small></dd></div>)}</dl><p>{prefilled?.costs.length??0} custo(s) identificado(s). Valores salvos e documentos estão na conferência dos registros abaixo.</p><p>Tributos embutidos nas tarifas não são cobrados novamente.</p></>:card.key==='market'?<><p>Contrato e compra de energia: confira a vigência, a nota e o volume no registro do fornecedor.</p><p>PLD/CCEE: integração aguardando habilitação.</p><p>Comparação ACL × ACR: abrir auditoria para consultar a memória de cálculo do backend. Economia depende dos registros validados.</p></>:<><p>{pending.length?`${pending.length} campo(s) aguardam conferência. Valores disponíveis já aparecem nas propostas.`:'Conferências dos campos salvas. Consulte as validações de registros e as decisões restantes abaixo.'}</p><p>Confiança OCR: alta {stats.high} · revisão {stats.review} · baixa {stats.low} · sem informação {stats.missing}.</p><p>A confirmação pelo Expert mantém a confiança original. A aprovação financeira pertence ao gestor/administrador.</p></>}</article>)}</div></section>;
}
