'use client';
import type {LayoutEvidence} from './OcrLayoutEvidence';
import {operationTaxSummary,columnsForOperations,isSupplierTaxReference} from './operation-tax-summary';
import OcrTranscription from './OcrTranscription';
export default function OcrOperationTaxes({operations,onOpenOriginal}:{operations:LayoutEvidence['operations'];onOpenOriginal?:(page?:number)=>void}){
 const groups=operationTaxSummary(operations),taxColumns=columnsForOperations(operations);
 return <section aria-label="Tributos de todas as componentes" style={{border:'1px solid #40516b',borderRadius:12,padding:16,margin:'16px 0'}}><h3>Tributos de todas as componentes</h3>{operations.some(r=>r.fields.pisCofinsAmount)&&<p>PIS/Cofins está impresso em conjunto neste layout. A soma conjunta é preservada, sem estimar valores individuais por parcela.</p>}<p>ICMS, PIS e Cofins das linhas de TUSD, CDE e demais componentes. São valores destacados para conferência: não são acrescentados novamente ao valor da operação com tributos.</p><p>Subtotais e totais da fatura não entram nesta soma. Créditos e descontos ficam separados, com os sinais originais. Valores ausentes ou ambíguos tornam a soma parcial; isto não aprova a apuração.</p>
 {groups.filter(g=>g.rows.length).map(g=><div key={g.role}><h4>{g.role==='CHARGE'?'Cobranças — tributos extraídos':'Créditos e descontos — tributos extraídos'}</h4><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}>{g.totals.map(t=><article key={t.key} style={{padding:16,background:'#172438',borderRadius:10}}><strong>{t.label}</strong><p style={{fontSize:24}}>{t.value===null?'Não identificado':'R$ '+t.value}</p><p>{t.partial?'Soma parcial':'Soma das linhas extraídas'} · {t.count} de {t.expected} linhas</p></article>)}</div>
 {g.referenceCount>0&&<p>{g.referenceCount} linha(s) de Energia ACL sem destaque tributário: conferir os tributos na nota fiscal do fornecedor. Essas linhas não contam como campos faltantes da distribuidora.</p>}<details><summary>Ver tributos por componente ({g.rows.length})</summary>{g.rows.map((r,i)=><article key={r.source+':'+i} style={{padding:12,borderBottom:'1px solid #40516b'}}><strong>{r.fields.description?.text||'Componente a conferir'}</strong>{isSupplierTaxReference(r)&&<p>Energia fornecida no Mercado Livre. Os tributos devem ser conferidos na nota fiscal do fornecedor; não serão estimados a partir desta linha da distribuidora.</p>}<p>{r.period==='PEAK'?'Ponta':r.period==='OFF_PEAK'?'Fora ponta':'Posto não identificado'} · Valor da operação: {r.fields.amount?.text||'não identificado'}</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}>{taxColumns.map(([key,label])=>{const f=r.fields[key];return <section key={key}><strong>{label}</strong><p>{f?.text.trim()||(isSupplierTaxReference(r)?'Sem destaque nesta fatura — conferir NF do fornecedor':'Não identificado — não equivale a zero')}</p>{f?.text.trim()&&<><small>Confiança do campo: {f.confidence===null?'não informada':(f.confidence*100).toFixed(1).replace('.',',')+'%'} · Conferência necessária</small><OcrTranscription evidence={f.transcription}/></>}{onOpenOriginal&&!isSupplierTaxReference(r)&&<p><button type="button" onClick={()=>onOpenOriginal(f?.pages.length===1?f.pages[0]:1)}>Conferir {label} no PDF</button></p>}</section>;})}</div><small>Origem: {r.source}</small></article>)}</details></div>)}
 {!groups.some(g=>g.rows.length)&&<p>Nenhuma operação disponível para esta conferência.</p>}
 {operations.some(r=>r.role==='UNKNOWN')&&<p>Há componentes sem classificação; seus valores não foram incluídos nos cartões.</p>}
 </section>;
}
