'use client';
import {useRef,useState} from 'react';
import {apiRequest,ApiError} from '@/app/lib/api/client';
export type Review={confirmationMode?:string|null;id:string;fieldKey:string;version:number;sourceHash:string;decision:string;note:string;author:string;createdAt:string;value:string|null;unit:string};
export type ReviewField={attestation?:{mode:string};key:string;label:string;unit:string;decimal:string|null;state:string;sourceHash:string;history:Review[];hasOlder:boolean;description?:string;source?:string;taxReview?:{key:string;label:string;text:string;message:string}[]};
const decisions:Record<string,string>={CONFIRMED:'Conferido no PDF',USED:'Demanda utilizada',UNUSED:'Demanda não utilizada',NEEDS_CORRECTION:'Precisa de correção'};
export default function OcrReviewField({field:f,id,canReview,onSaved,demand=false,identity=false,cde=false,session=0}:{field:ReviewField;id:string;canReview:boolean;onSaved:()=>Promise<void>;demand?:boolean;identity?:boolean;cde?:boolean;session?:number}){
 const [decision,setDecision]=useState(''),[note,setNote]=useState(''),[checked,setChecked]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<Review|null>(null),[editingId,setEditingId]=useState<string|null>(null);
 const pending=useRef(false),attempt=useRef<{body:unknown;key:string}|null>(null);
 const history=[...(receipt&&!f.history.some(r=>r.id===receipt.id)?[receipt]:[]),...f.history].sort((a,b)=>b.version-a.version);
 const last=history[0],current=last?.sourceHash===f.sourceHash?last:null,editing=editingId!==null&&editingId===session+':'+current?.id,locked=!!current&&!editing;
 const missing=f.attestation&&decision==='CONFIRMED'&&note.trim().length<20?'Justifique o vínculo confirmado (mínimo de 20 caracteres).':!decision?'Selecione o resultado da conferência.':(demand||identity||cde||decision==='CONFIRMED')&&!checked?'Marque a confirmação de conferência no PDF original.':(demand||identity||cde||decision==='NEEDS_CORRECTION')&&note.trim().length<3?'Informe a evidência ou correção necessária (mínimo de 3 caracteres).':'';
 async function save(){
  if(pending.current||!canReview||locked||missing)return;
  pending.current=true;setBusy(true);setError('');
  const draft={fieldKey:f.key,sourceHash:f.sourceHash,decision,note,expectedReviewId:last?.id??null,checkedPdf:checked},key=JSON.stringify(draft);
  if(attempt.current?.key!==key)attempt.current={key,body:{...draft,requestId:crypto.randomUUID()}};
  try{
   const result=await apiRequest<{canImport:false;review?:Review}>('/api/v1/documents/'+encodeURIComponent(id)+'/ocr/'+(cde?'cde-reviews':identity?'identity-reviews':demand?'demand-reviews':'reviews'),{method:'POST',body:attempt.current.body});
   const saved=result.review;
   if(result.canImport!==false||!saved||typeof saved.id!=='string'||!saved.id||saved.fieldKey!==f.key||saved.sourceHash!==f.sourceHash||saved.decision!==decision||!Number.isInteger(saved.version)||saved.version<1||typeof saved.author!=='string'||!Number.isFinite(Date.parse(saved.createdAt)))throw new Error('Missing receipt');
   setReceipt(saved);setEditingId(null);setDecision('');setChecked(false);setNote('');attempt.current=null;
   await onSaved();
  }catch(e){setError(e instanceof ApiError?e.message:'Não foi possível confirmar o salvamento. Atualize o histórico antes de tentar novamente; ao repetir sem alterar os dados, a mesma solicitação será usada.');}
  finally{pending.current=false;setBusy(false);}
 }
 return <article style={{border:'1px solid #40516b',borderRadius:10,padding:16,margin:'16px 0'}}><h3>{f.label}</h3>{f.description&&<p>{f.description}</p>}{f.source&&<small>Origem: {f.source}</small>}<p style={{fontSize:24}}>{f.decimal===null?'Valor a conferir':(identity||cde)?f.decimal:f.decimal.replace('.',',')+' '+f.unit}</p>{f.taxReview&&<ul>{f.taxReview.map(t=><li key={t.key}>{t.label}: {t.text||'Sem destaque — não equivale a zero'} · {t.message}</li>)}</ul>}
 {current?<div role="status" style={{padding:12,background:'#123b36',borderRadius:8}}><strong>{editing?'Última conferência registrada — nova revisão ainda não salva.':receipt?.id===current.id?'Conferência salva com sucesso.':'Conferência registrada.'} {current.confirmationMode&&current.decision==='CONFIRMED'?'Vínculo confirmado com justificativa':decisions[current.decision]}</strong><p>{current.author} · {new Date(current.createdAt).toLocaleString('pt-BR')} · Versão {current.version}</p><p>Registro preservado no histórico. A conferência deste campo não aprova a apuração.</p></div>:<p>{last?(identity?'A leitura ou o cadastro mudou desde a última conferência. Confira novamente; o histórico anterior está preservado.':'A leitura mudou desde a última conferência. Confira novamente; o histórico anterior está preservado.'):'Ainda sem conferência registrada.'}</p>}
 {locked?<><label style={{display:'block',margin:'12px 0'}}><input type="checkbox" checked disabled/>Registro salvo no histórico deste campo.</label>{canReview&&<button type="button" disabled={busy} onClick={()=>{setEditingId(current?session+':'+current.id:null);setDecision('');setChecked(false);setNote('');setError('');}}>Registrar nova revisão</button>}</>:canReview&&<fieldset disabled={busy}><legend>{current?'Nova revisão — preserva a versão anterior':'Registrar conferência deste campo'}</legend><label>Resultado<select aria-label={'Resultado — '+f.label} value={decision} onChange={e=>setDecision(e.target.value)}><option value="">Selecione</option>{demand?<><option value="USED" disabled={f.state!=='BILLED_UNCLASSIFIED'||f.decimal===null}>Demanda utilizada</option><option value="UNUSED" disabled={f.state!=='BILLED_UNCLASSIFIED'||f.decimal===null}>Demanda não utilizada</option></>:<option value="CONFIRMED" disabled={f.state!=='EXTRACTED_REVIEW'||f.decimal===null}>{f.attestation?'Vínculo confirmado com justificativa':'Conferido no PDF original'}</option>}<option value="NEEDS_CORRECTION">Precisa de correção</option></select></label>
 {(demand||identity||cde||decision==='CONFIRMED')&&<label style={{display:'block',margin:'12px 0'}}><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>{f.attestation?'Conferi a fatura e o cadastro vinculado. Confirmo o vínculo e justifico abaixo o CNPJ parcial, nome equivalente ou ambiente cadastral, conforme este campo.':cde?'Conferi a descrição CDE e o posto (ponta ou fora ponta) no PDF original da unidade e competência.':'Conferi este valor no PDF original da unidade e competência.'}</label>}
 <label style={{display:'block'}}>{demand||identity||cde?'Evidência no PDF ou correção necessária (obrigatória)':'Observação '+(decision==='NEEDS_CORRECTION'?'(obrigatória)':'(opcional)')}<textarea aria-label={'Observação — '+f.label} maxLength={500} value={note} onChange={e=>setNote(e.target.value)} style={{display:'block',width:'100%'}}/></label>
 {missing&&<p>{missing} O registro ainda não foi salvo.</p>}<button type="button" disabled={busy||!!missing} onClick={()=>void save()}>{busy?'Salvando…':'Salvar conferência'}</button>{editing&&<button type="button" disabled={busy} onClick={()=>setEditingId(null)}>Cancelar nova revisão</button>}</fieldset>}
 {error&&<p role="alert">{error}</p>}
 <details open={!!current}><summary>Histórico deste campo ({history.length}{f.hasOlder?' mais recentes':''})</summary>{history.map(r=><article key={r.id}><p><strong>Versão {r.version} · {r.confirmationMode&&r.decision==='CONFIRMED'?'Vínculo confirmado com justificativa':decisions[r.decision]??'Conferência'}</strong></p><p>{r.author} · {new Date(r.createdAt).toLocaleString('pt-BR')}</p><p>{cde?'Descrição da época: ':'Valor da época: '}{r.value===null?'Não definido':(identity||cde)?r.value:r.value.replace('.',',')+' '+r.unit}</p>{r.note&&<p>{r.note}</p>}</article>)}{!history.length&&<p>Nenhum registro.</p>}{f.hasOlder&&<p>Mostrando os registros recentes; versões anteriores permanecem preservadas.</p>}</details></article>;
}
