'use client';
import OcrDemandTaxConfidence,{type TaxDiagnostics} from './OcrDemandTaxConfidence';
import {useEffect,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
export type ReviewedDemand={canImport:false;state:string;usedKw:string|null;unusedKw:string|null;reviewed:number;total:number;message:string;rows:{key:string;label:string;source:string;decimal:string|null;state:string;review:{id:string;version:number;author:string;createdAt:string}|null}[]};
const labels:Record<string,string>={USED:'Utilizada — conferida',UNUSED:'Não utilizada — conferida',PENDING:'Conferência pendente',STALE:'Leitura alterada — conferir novamente',CONFLICT:'Origem ou quantidade conflitante',NEEDS_CORRECTION:'Correção solicitada'};
const value=(v:string|null)=>v===null?'Pendente':v.replace('.',',')+' kW';
export default function OcrReviewedDemand({documentId,revision}:{documentId:string;revision:number}){
 const [refresh,setRefresh]=useState(0),[result,setResult]=useState<{key:string;data:(ReviewedDemand&{taxDiagnostics?:TaxDiagnostics})|null;error:string}|null>(null);
 const requestKey=JSON.stringify([documentId,revision,refresh]);const active=result?.key===requestKey;const data=active?result.data:null,error=active?result.error:'',busy=revision>0&&!active;
 useEffect(()=>{if(!revision)return;let current=true;apiRequest<{summary:ReviewedDemand;taxDiagnostics?:TaxDiagnostics}>('/api/v1/documents/'+encodeURIComponent(documentId)+'/ocr/demand-reviews').then(r=>{if(current){if(!r.summary||r.summary.canImport!==false)throw new Error('Invalid summary');setResult({key:requestKey,data:{...r.summary,taxDiagnostics:r.taxDiagnostics},error:''});}}).catch(()=>{if(current)setResult({key:requestKey,data:null,error:'Não foi possível consultar a classificação vigente. Nenhum total conferido está disponível; atualize para tentar novamente.'});});return ()=>{current=false;};},[documentId,revision,requestKey]);
 return <section aria-label="Demanda faturada após conferência" style={{border:'1px solid #48bfd4',borderRadius:12,padding:20,margin:'16px 0',background:'#102637'}}><h3>Demanda faturada após conferência</h3><button type="button" disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Atualizar classificação conferida</button>{busy&&<p role="status">Consultando histórico vigente…</p>}{error&&<p role="alert">{error}</p>}{data&&<><p>{data.reviewed} de {data.total} parcelas com classificação vigente. {data.state==='COMPLETE'?'Classificação concluída — apuração ainda depende das demais validações.':data.state==='EMPTY'?'Nenhuma parcela disponível neste layout.':'Resolva as pendências antes de utilizar os totais.'}</p><div style={{display:'flex',gap:16,flexWrap:'wrap'}}><article><strong>Parcela utilizada</strong><p style={{fontSize:24}}>{value(data.usedKw)}</p></article><article><strong>Parcela não utilizada</strong><p style={{fontSize:24}}>{value(data.unusedKw)}</p></article></div><p>{data.message}</p>{data.rows.map(r=><article key={r.key} style={{padding:12,borderTop:'1px solid #40516b'}}><strong>{r.label}: {labels[r.state]??'Conferência pendente'}</strong><p>Quantidade da linha: {value(r.decimal)}</p>{r.review&&<p>Último registro: {r.review.author} · {new Date(r.review.createdAt).toLocaleString('pt-BR')} · versão {r.review.version}</p>}{data.taxDiagnostics?.find(t=>t.key===r.key)&&<OcrDemandTaxConfidence fields={data.taxDiagnostics.find(t=>t.key===r.key)!.fields}/>}</article>)}<p>Para registrar ou corrigir a classificação, use “Classificar parcelas de demanda” na consulta OCR.</p></>}</section>;
}
