'use client';
import {useEffect,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
type Preview={token:string;state:string;canCreate:boolean;message:string;targetVersion:number;inputId:string|null;parameterIds:string[];candidates?:{band:string;quantity:string|null;amount:string|null;ready:boolean;reason:string}[]};
export default function OcrReactiveIntegration({documentId,onIntegrated}:{documentId:string;onIntegrated?:()=>Promise<void>}){
 const [data,setData]=useState<Preview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const url='/api/v1/documents/'+encodeURIComponent(documentId)+'/ocr/reactive-integration';
 const refresh=async()=>{setBusy(true);setError('');try{setData(await apiRequest<Preview>(url));}catch{setError('Não foi possível consultar a integração das reativos. Atualize a situação.');}finally{setBusy(false);}};
 useEffect(()=>{let active=true;setData(null);setError('');setMessage('');apiRequest<Preview>(url).then(v=>{if(active)setData(v);}).catch(()=>{if(active)setError('Não foi possível consultar a integração das reativos. Atualize a situação.');});return()=>{active=false;};},[url]);
 const integrate=async()=>{if(!data?.canCreate||busy)return;setBusy(true);setError('');try{await apiRequest(url,{method:'POST',body:{token:data.token}});setMessage('Integração salva: reativos mensais e duas tarifas em rascunho. Histórico e versão anterior preservados.');setData(await apiRequest<Preview>(url));await onIntegrated?.();}catch{setError('A integração não foi confirmada. Atualize a situação antes de tentar novamente; o sistema evita duplicidade.');}finally{setBusy(false);}};
 return <section aria-label='Integração das reativos OCR'><h4>Integrar reativos por posto e tarifas</h4><p>{data?.message??'Consultando integração…'}</p>{data&&<p>Versão mensal de destino: {data.targetVersion}. Os registros ficam sujeitos à validação e aprovação.</p>}{data?.candidates?.map(c=><p key={c.band}>{c.band==='PEAK'?'Ponta':'Fora ponta'}: {c.quantity??'Não identificado'} kWh da fatura · R$ {c.amount??'Não identificado'}{!c.ready?' · '+c.reason:''}</p>)}<p>O comparativo ACR usa as mesmas quantidades com as suas tarifas aprovadas. Tributos sem destaque não são tratados como zero.</p>{error&&<p role='alert'>{error}</p>}{message&&<p role='status'>{message}</p>}<button type='button' disabled={busy} onClick={refresh}>Atualizar integração das reativos</button>{data?.canCreate&&<button type='button' disabled={busy} onClick={integrate}>{busy?'Integrando…':'Integrar reativos e tarifas automaticamente'}</button>}{data?.state==='INTEGRATED'&&<p>Integração registrada · {data.parameterIds.length} tarifas. Consulte Dados mensais e Parâmetros de cálculo, a situação de Preparar apuração é atualizada após a integração.</p>}</section>;
}
