'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {ocrContractLink} from '../contracts/ocr-navigation';
type Data={token:string;month:string;state:string;canCreate:boolean;message:string;amounts:{combined?:boolean;code:string;peak:string|null;offPeak:string|null;amount:string|null}[]};
export default function OcrTusdTaxes({id,onCreated}:{id:string;onCreated:()=>void}){
 const request=useRef(0),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 const url='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/tusd-taxes';
 async function load(){const n=++request.current;setBusy(true);setData(null);setError('');try{const d=await apiRequest<Data>(url);if(n===request.current)setData(d);}catch{if(n===request.current)setError('Não foi possível consultar a integração TUSD. Atualize antes de tentar novamente.');}finally{if(n===request.current)setBusy(false);}}
 useEffect(()=>{setReceipt('');void load();return()=>{request.current++;};},[id]);
 async function create(){if(!data?.canCreate||busy)return;const n=++request.current;setBusy(true);setError('');try{await apiRequest(url,{method:'POST',body:{token:data.token}});if(n!==request.current)return;setReceipt('As três declarações tributárias foram registradas com autor e histórico. Aprovação pendente.');onCreated();await load();}catch{if(n===request.current){setData(null);setError('Não foi possível confirmar a criação. Atualize a consulta para verificar os registros antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 return <section aria-label="Tributos incluídos na TUSD" style={{marginTop:24,border:'1px solid #405873',borderRadius:12,padding:20}}><h3>ICMS, PIS e Cofins → Declarações de tributos incluídos</h3><p>Destaques tributários somente das duas linhas TUSD da fatura. A base deve estar aprovada. As declarações serão criadas em rascunho, sem nova cobrança e sem inferir alíquotas.</p><button type="button" disabled={busy} onClick={()=>void load()}>Atualizar tributos TUSD</button>{busy&&<p role="status">Consultando ou registrando TUSD…</p>}{error&&<p role="alert">{error}</p>}{receipt&&<p role="status">{receipt}</p>}{data&&<><p><strong>{data.month}</strong> · {data.message}</p><div style={{display:'flex',flexWrap:'wrap',gap:16}}>{data.amounts.map(c=><article key={c.code} style={{flex:'1 1 200px',background:'#19273a',padding:16,borderRadius:12}}><h4>{c.code}</h4>{c.combined?<p>PIS/Cofins em coluna conjunta. Valor individual não separado; declaração de inclusão sem nova cobrança.</p>:<><p>Ponta: {c.peak===null?'Não identificado':'R$ '+c.peak}</p><p>Fora ponta: {c.offPeak===null?'Não identificado':'R$ '+c.offPeak}</p><p>Total destacado na TUSD: <strong>{c.amount===null?'Pendente':'R$ '+c.amount}</strong></p></>}</article>)}</div>{data.canCreate&&<button type="button" disabled={busy} onClick={()=>void create()}>Criar declarações de tributos incluídos</button>}<p>ICMS, PIS e Cofins destacados não serão somados novamente à tarifa bruta. Esta etapa não integra energia do fornecedor, demanda ou outros encargos.</p><a href={ocrContractLink(id,'parameters')}>Consultar parâmetros e histórico desta unidade</a></>}</section>;
}
