'use client';
import OcrTariffRecordStatus from './OcrTariffRecordStatus';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {ocrContractLink} from '../contracts/ocr-navigation';
type Data={existing?:{id:string;band:string;status:string;revision:number}[];token:string;month:string;state:string;canCreate:boolean;message:string;candidates:{band:string;ready:boolean;reason:string;rateKwh:string|null;rateMwh:string|null;quantity:string|null;amount:string|null}[]};
export default function OcrTusdIntegration({id,onCreated}:{id:string;onCreated:()=>void}){
 const request=useRef(0),[data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 const url='/api/v1/documents/'+encodeURIComponent(id)+'/ocr/tusd-integration';
 async function load(){const n=++request.current;setBusy(true);setData(null);setError('');try{const d=await apiRequest<Data>(url);if(n===request.current)setData(d);}catch{if(n===request.current)setError('Não foi possível consultar a integração TUSD. Atualize antes de tentar novamente.');}finally{if(n===request.current)setBusy(false);}}
 useEffect(()=>{setReceipt('');void load();return()=>{request.current++;};},[id]);
 async function create(){if(!data?.canCreate||busy)return;const n=++request.current;setBusy(true);setError('');try{await apiRequest(url,{method:'POST',body:{token:data.token}});if(n!==request.current)return;setReceipt('Os dois rascunhos TUSD foram registrados com autor e histórico. Aprovação pendente.');onCreated();await load();}catch{if(n===request.current){setData(null);setError('Não foi possível confirmar a criação. Atualize a consulta para verificar os registros antes de tentar novamente.');}}finally{if(n===request.current)setBusy(false);}}
 return <section aria-label="Integração TUSD da fatura" style={{marginTop:24,border:'1px solid #405873',borderRadius:12,padding:20}}><h3>TUSD da fatura → Parâmetros de cálculo</h3><p>Tarifas ACL com tributos já incluídos. A conversão de R$/kWh para R$/MWh preserva todas as casas decimais. Os rascunhos valem somente para a competência da fatura e exigem aprovação.</p><button type="button" disabled={busy} onClick={()=>void load()}>Atualizar integração TUSD</button>{busy&&<p role="status">Consultando ou registrando TUSD…</p>}{error&&<p role="alert">{error}</p>}{receipt&&<p role="status">{receipt}</p>}{data&&<><p><strong>{data.month}</strong> · {data.message}</p><div style={{display:'flex',flexWrap:'wrap',gap:16}}>{data.candidates.map(c=><article key={c.band} style={{flex:'1 1 260px',background:'#19273a',padding:16,borderRadius:12}}><h4>{c.band==='PEAK'?'Ponta':'Fora ponta'}</h4>{c.ready&&<><p>Fatura: {c.rateKwh} R$/kWh</p><p>Parâmetro: <strong>{c.rateMwh} R$/MWh</strong></p><p>{c.quantity} kWh · R$ {c.amount}</p></>}<OcrTariffRecordStatus band={c.band} records={data.existing} reason={c.reason} ready={c.ready}/></article>)}</div>{data.canCreate&&<button type="button" disabled={busy} onClick={()=>void create()}>Criar rascunhos TUSD nos parâmetros</button>}<p>ICMS, PIS e Cofins destacados não serão somados novamente à tarifa bruta. Esta etapa não integra energia do fornecedor, demanda ou outros encargos.</p><a href={ocrContractLink(id,'parameters')}>Consultar parâmetros e histórico desta unidade</a></>}</section>;
}
