export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  ANALYZING = 'ANALYZING',
  EXTRACTING = 'EXTRACTING',
  PARSED = 'PARSED',
  VALIDATING = 'VALIDATING',
  COMPLETED = 'COMPLETED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  APPROVED = 'APPROVED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
}
