'use client';
import {FormEvent,useEffect,useState} from 'react';
import {RadiusValues,validRadius} from './commercial-map-data';
const empty={radiusLatitude:'',radiusLongitude:'',radiusKm:''};
const inputStyle={minWidth:0,width:'100%',boxSizing:'border-box' as const,padding:10,minHeight:42,border:'1px solid #40516b',borderRadius:8,background:'#17263a',color:'#f0f5ff'};
export default function RadiusFilter({active,selected,onApply}:{active:RadiusValues;selected:{latitude:number|null;longitude:number|null;locationStatus:string}|null;onApply:(radius:RadiusValues)=>void}){
 const [values,setValues]=useState({...active,radiusKm:active.radiusKm||'50'});
 useEffect(()=>setValues({...active,radiusKm:active.radiusKm||'50'}),[active.radiusLatitude,active.radiusLongitude,active.radiusKm]);
 const center=selected?.locationStatus==='CONFIRMED'&&typeof selected.latitude==='number'&&Number.isFinite(selected.latitude)&&typeof selected.longitude==='number'&&Number.isFinite(selected.longitude);
 function apply(e:FormEvent){e.preventDefault();if(validRadius(values))onApply(values);}
 return <section aria-label="Consulta por raio" style={{border:'1px solid #40516b',borderRadius:12,padding:16,margin:'16px 0'}}><details open={!!active.radiusKm}><summary>Explorar unidades por raio</summary><p>Distância geográfica aproximada em linha reta, a partir de coordenadas conferidas. Endereços pendentes ou desatualizados e clientes sem unidade ficam fora da busca. A precisão da localização continua indicada nos detalhes.</p><form onSubmit={apply}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12}}>{[['radiusLatitude','Latitude do centro'],['radiusLongitude','Longitude do centro'],['radiusKm','Raio em km (1–500)']].map(([key,label])=><label key={key} style={{display:'grid',gap:6,minWidth:0}}>{label}<input style={inputStyle} inputMode="decimal" value={values[key as keyof RadiusValues]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><button style={{...inputStyle,width:'auto'}} type="button" disabled={!center} onClick={()=>{if(center&&selected)setValues(v=>({...v,radiusLatitude:selected.latitude!.toFixed(7),radiusLongitude:selected.longitude!.toFixed(7)}));}}>Usar unidade selecionada como centro</button><button style={{...inputStyle,width:'auto'}} disabled={!validRadius(values)}>Aplicar raio</button><button style={{...inputStyle,width:'auto'}} type="button" disabled={!active.radiusKm} onClick={()=>onApply(empty)}>Limpar raio</button></div></form>{active.radiusKm&&<p role="status">Raio ativo: {active.radiusKm} km · centro {active.radiusLatitude}, {active.radiusLongitude}. Toda a seleção e suas agregações respeitam esse recorte.</p>}</details></section>;
}
