'use client';
import {FormEvent,useEffect,useState} from 'react';
import BackofficeShell from '@/app/components/BackofficeShell';
import ProtectedRoute from '@/app/components/ProtectedRoute';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {useAuth} from '@/app/providers';
import {apiRequest} from '@/app/lib/api/client';
import WorkflowModal from '../contracts/WorkflowModal';
import './team.css';
const manage='82e7fc71-479a-4dd6-8b22-4fba6eaa6841';
const profiles={OWNER:'Owner',ADMINISTRATOR:'Administrador',FINANCE:'Financeiro',SUPPORT:'Suporte'};
type Profile=keyof typeof profiles;
type Member={userId:string;profile:Profile;firstName:string|null;lastName:string|null;registeredName:string|null;email:string|null;active:boolean;revision:number};
type History={id:string;at:string;actorId:string;targetId:string;changes:{actorNameAtTime?:string;actorProfileAtTime?:string;reason?:string;before?:unknown;after?:unknown}};
type Data={rows:Member[];total:number;ownerCount:number;history:History[]};
function displayName(row:Member){return [row.firstName,row.lastName].filter(Boolean).join(' ')||row.registeredName||'Nome não disponível';}
function Workspace(){
 const [data,setData]=useState<Data|null>(null),[page,setPage]=useState(0),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState<Member|'new'|null>(null),[modalError,setModalError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let current=true;void apiRequest<Data>('/api/v1/admin/platform-team?page='+page).then(d=>{if(current){setData(d);setError('');}}).catch(e=>{if(current){setData(null);setError(e instanceof Error?e.message:'Consulta indisponível.');}});return()=>{current=false;};},[page,version]);
 const open=(row:Member|'new')=>{setModalError('');setModal(row);};
 async function save(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(!modal)return;setBusy(true);setModalError('');
  const form=new FormData(event.currentTarget),value=(key:string)=>String(form.get(key)||'').trim();
  const definition={firstName:value('first'),lastName:value('last'),profile:value('profile'),reason:value('reason'),...(modal==='new'?{email:value('email')}:{active:form.get('active')==='on',revision:modal.revision})};
  try{await apiRequest('/api/v1/admin/platform-team'+(modal==='new'?'':'/'+modal.userId),{method:modal==='new'?'POST':'PATCH',body:definition});setModal(null);setVersion(v=>v+1);setNotice('Cadastro confirmado. A alteração de perfil será conferida nas próximas chamadas autenticadas.');}
  catch(e){setModalError(e instanceof Error?e.message:'Alteração não confirmada. Confira o cadastro antes de repetir.');}finally{setBusy(false);}
 }
 return <section className="backoffice-page platform-team"><header className="backoffice-page__header"><h1 className="backoffice-page__title">Equipe da plataforma</h1><p>Perfis internos da plataforma. Clientes e usuários de organizações são gerenciados em seus próprios ambientes.</p></header>
 {error?<Alert variant="error">{error}</Alert>:null}{notice?<Alert>{notice}</Alert>:null}
 <Card title="Acesso da equipe"><div className="platform-team__actions"><Button onClick={()=>open('new')}>Inserir</Button><Button variant="secondary" onClick={()=>setVersion(v=>v+1)}>Atualizar</Button><span>Owners ativos: {data?.ownerCount??'—'} / 2</span></div><p>Somente Owners gerenciam planos, licenças, configurações e perfis globais. O último Owner ativo é protegido.</p>
 {!data&&!error?<p role="status">Carregando cadastro…</p>:null}
 {data?<><div className="platform-team__table"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.userId}><td>{displayName(row)}</td><td>{row.email||'E-mail não disponível'}</td><td>{profiles[row.profile]}</td><td>{row.active?'Ativo':'Inativo'}</td><td><Button variant="secondary" onClick={()=>open(row)}>Editar</Button></td></tr>)}</tbody></table></div><div className="platform-team__actions"><Button variant="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Anterior</Button><span>Página {page+1} · {data.total} registros</span><Button variant="secondary" disabled={(page+1)*25>=data.total} onClick={()=>setPage(p=>p+1)}>Próxima</Button></div></>:null}</Card>
 <Card title="Permissões dos perfis"><dl><dt>Owner</dt><dd>Administração completa, planos, licenças, equipe, gastos e integrações. Até dois ativos.</dd><dt>Administrador</dt><dd>Cadastro e consulta de organizações. Sem planos, licenças, perfis ou credenciais.</dd><dt>Financeiro</dt><dd>Consulta de consumo e gastos. Sem alterações de acesso ou dados operacionais.</dd><dt>Suporte</dt><dd>Consulta técnica de modelos e entrega de mensagens. Sem dados financeiros ou concessão de acesso.</dd></dl></Card>
 {data?<Card title="Auditoria"><details><summary>Últimas 20 alterações</summary>{data.history.length?<div className="platform-team__table"><table><thead><tr><th>Data</th><th>Autor registrado na época</th><th>Perfil na época</th><th>Usuário alvo</th><th>Justificativa</th></tr></thead><tbody>{data.history.map(h=><tr key={h.id}><td>{new Date(h.at).toLocaleString('pt-BR')}</td><td>{h.changes.actorNameAtTime||'Nome não disponível'}<small>{h.actorId}</small></td><td>{h.changes.actorProfileAtTime||'Perfil não disponível'}</td><td>{typeof h.changes.after==='object'&&h.changes.after?[(h.changes.after as Record<string,unknown>).firstName,(h.changes.after as Record<string,unknown>).lastName].filter(Boolean).join(' ')||'Nome não disponível':'Nome não disponível'}<small>{h.targetId}</small></td><td>{h.changes.reason||'Justificativa não disponível'}</td></tr>)}</tbody></table></div>:<p>Nenhuma alteração registrada.</p>}</details></Card>:null}
 {modal?<WorkflowModal title={modal==='new'?'Inserir usuário da plataforma':'Editar acesso da equipe'} onClose={()=>{if(!busy)setModal(null);}}><form onSubmit={e=>void save(e)} className="platform-team__form">{modalError?<Alert variant="error">{modalError}</Alert>:null}<p>O cadastro não concede acesso à Meta ou ao Railway. Novas contas recebem convite para criar a própria senha.</p><div className="platform-team__grid"><Input label="Primeiro nome" name="first" required maxLength={80} defaultValue={modal==='new'?'':modal.firstName??''} disabled={busy}/><Input label="Sobrenome" name="last" required maxLength={120} defaultValue={modal==='new'?'':modal.lastName??''} disabled={busy}/><Input label="E-mail" name="email" type="email" required maxLength={254} defaultValue={modal==='new'?'':modal.email??''} disabled={busy||modal!=='new'}/><label className="ds-field"><span className="ds-label">Perfil</span><select name="profile" className="ds-input" defaultValue={modal==='new'?'SUPPORT':modal.profile} disabled={busy}>{Object.entries(profiles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>{modal!=='new'?<label><input type="checkbox" name="active" defaultChecked={modal.active} disabled={busy}/> Acesso ativo</label>:null}<label className="ds-field"><span className="ds-label">Justificativa da alteração</span><textarea className="ds-input" name="reason" required minLength={5} maxLength={1000} rows={3} disabled={busy}/></label><p>Nome da equipe e perfil ficam auditados. Identidade de login, IDs e histórico existente são preservados.</p><div className="platform-team__actions"><Button type="submit" disabled={busy}>{busy?'Confirmando…':modal==='new'?'Cadastrar e conceder perfil':'Salvar acesso'}</Button><Button variant="secondary" disabled={busy} onClick={()=>setModal(null)}>Cancelar</Button></div></form></WorkflowModal>:null}
 </section>;
}
export default function Page(){const {context,hasPermission}=useAuth();return <ProtectedRoute><BackofficeShell>{context?.scope==='global'&&hasPermission(manage)?<Workspace key={context.user.id}/>:<Alert>Acesso exclusivo a Owner da plataforma.</Alert>}</BackofficeShell></ProtectedRoute>;}
