'use client';
import {useEffect,useRef,useState} from 'react';
import {CalendarClock,Mail,MessageSquare,ShieldCheck} from 'lucide-react';
import {useAuth} from '@/app/providers';
import {apiRequest} from '@/app/lib/api';
import {Alert,Button,Card} from '@/app/components/ui';
type Config={name:string;customerId:string;unitId:string;frequency:'MONTHLY'|'FORTNIGHTLY';days:number[];hour:number;monthlyLimit:number;kinds:string[];formats:string[];channels:string[];contactIds:string[]};
const fresh=():Config=>({name:'',customerId:'',unitId:'',frequency:'MONTHLY',days:[5],hour:9,monthlyLimit:1,kinds:['OPERATIONAL'],formats:['pdf'],channels:['email'],contactIds:[]});
const names:Record<string,string>={ACTIVE:'Ativa',PAUSED:'Pausada',BLOCKED:'Bloqueada',QUEUED:'Na fila',PREPARING:'Preparando',WAITING_PUBLICATION:'Aguardando publicação',READY:'Versões preparadas',CANCELLED:'Cancelada',CONTACT_CHANGED:'Contato alterado: revise o cadastro e salve a configuração',ACCESS_REVOKED:'Acesso ou licença revogados',POLICY_CHANGED:'Configuração alterada',SCOPE_INACTIVE:'Cliente ou unidade inativos',CONTACT_UNAVAILABLE:'Contato ou canal indisponível',PREPARATION_LIMIT:'Limite de tentativas de preparação',PREPARATION_UNAVAILABLE:'Preparação indisponível'};
export default function ReportConfiguration(){
 const {context,hasPermission}=useAuth(),org=context&&context.scope!=='global'?context.currentOrganization.id:'',currentOrg=useRef(org),pendingRequest=useRef<{key:string;id:string}|null>(null);currentOrg.current=org;
 const allowed=!!org&&['3ebadd32-6f30-459e-8ed3-0d2843d89946','9541a7bb-c20a-4c4d-9f4c-2185262c8e9c','60f9690a-145b-4dba-b23f-9f945baca296','51da7cca-8196-4135-84ce-f989be5ee594'].every(hasPermission);
 const [data,setData]=useState<any>(null),[config,setConfig]=useState<Config>(fresh),[editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[review,setReview]=useState(''),[search,setSearch]=useState('');
 useEffect(()=>{let cancelled=false;pendingRequest.current=null;setData(null);setConfig(fresh());setEditing(null);setBusy(false);setError('');setNotice('');setReview('');setSearch('');if(allowed)apiRequest<any>('/api/v1/report-configuration').then(r=>{if(!cancelled)setData(r);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[org,allowed]);
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(currentOrg.current===org)setError(e instanceof Error?e.message:'Configuração indisponível.');}finally{if(currentOrg.current===org)setBusy(false);}};
 const reload=async()=>{const d=await apiRequest<any>('/api/v1/report-configuration');if(currentOrg.current===org)setData(d);};
 const requestId=(command:unknown)=>{const key=org+'|'+JSON.stringify(command);if(pendingRequest.current?.key!==key)pendingRequest.current={key,id:crypto.randomUUID()};return pendingRequest.current.id;};
 const save=()=>action(async()=>{await apiRequest('/api/v1/report-configuration',{method:'POST',body:{...(editing?{id:editing.id,expectedVersion:editing.version}:{}),requestId:requestId({action:'save',id:editing?.id,version:editing?.version,config}),config}});if(currentOrg.current!==org)return;setEditing(null);setConfig(fresh());setReview('');setNotice('Configuração salva e pausada. Revise os destinatários antes de ativar.');await reload();});
 const state=(p:any,enabled:boolean)=>action(async()=>{await apiRequest(`/api/v1/report-configuration/${p.id}/state`,{method:'POST',body:{expectedVersion:p.version,requestId:requestId({action:'state',id:p.id,version:p.version,enabled}),enabled}});if(currentOrg.current!==org)return;pendingRequest.current=null;setReview('');setNotice(enabled?'Recorrência ativada para a próxima data futura. Canais dependem dos provedores configurados.':'Recorrência pausada. Preparações pendentes foram canceladas.');await reload();});
 const set=<K extends keyof Config>(key:K,value:Config[K])=>setConfig(c=>({...c,[key]:value}));
 const choice=(key:'kinds'|'formats'|'channels'|'contactIds',value:string,checked:boolean)=>setConfig(c=>{let values=checked?[...c[key],value]:c[key].filter(x=>x!==value);if(key==='channels'&&values.includes('sms')&&!values.includes('email'))values.push('email');return {...c,[key]:values,...(key==='channels'?{contactIds:[]}: {})};});
 const customer=data?.customers.find((c:any)=>c.id===config.customerId),contacts=customer?.contacts??[];
 const eligible=(c:any)=>c.active&&config.channels.every(ch=>c.channels.includes(ch));
 const disabled=busy||!config.name.trim()||!config.unitId||!config.contactIds.length||!config.kinds.length||!config.formats.length||!config.channels.length;
 if(!allowed)return <Alert variant="error">Configurações exigem permissões de relatórios, contratos e notificações na organização ativa.</Alert>;
 return <section className="backoffice-page"><h1 className="backoffice-page__title">Relatórios · Configurações</h1><p>Defina o calendário e selecione os contatos cadastrados do cliente. Cada configuração começa pausada; alterações exigem nova revisão.</p>{error?<Alert variant="error">{error}</Alert>:null}{notice?<Alert>{notice}</Alert>:null}
 <Card title={editing?'Editar configuração · v'+editing.version:'Nova configuração'}><div className="form-grid"><label>Nome da configuração<input value={config.name} maxLength={100} disabled={busy} onChange={e=>set('name',e.target.value)}/></label><label>Cliente<select value={config.customerId} disabled={busy} onChange={e=>setConfig(c=>({...c,customerId:e.target.value,unitId:'',contactIds:[]}))}><option value="">Selecione</option>{data?.customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Unidade<select value={config.unitId} disabled={busy||!customer} onChange={e=>set('unitId',e.target.value)}><option value="">Selecione</option>{customer?.units.map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div>
 <p>At� 200 clientes por consulta. Para localizar outros, busque pelo nome.</p><label>Buscar cliente pelo nome<input maxLength={100} disabled={busy} value={search} onChange={e=>setSearch(e.target.value)}/></label><Button variant="secondary" disabled={busy} onClick={()=>action(async()=>{const d=await apiRequest<any>('/api/v1/report-configuration?search='+encodeURIComponent(search));if(currentOrg.current!==org)return;setData(d);setConfig(c=>({...c,customerId:'',unitId:'',contactIds:[]}));setEditing(null);})}>Buscar clientes</Button>{data?.customerLimitReached?<p>H� mais clientes; refine a busca.</p>:null}<h3><CalendarClock size={18}/> Calendário em São Paulo</h3><div className="form-grid"><label>Recorrência<select disabled={busy} value={config.frequency} onChange={e=>setConfig(c=>({...c,frequency:e.target.value as Config['frequency'],days:e.target.value==='MONTHLY'?[c.days[0]]:[5,20],monthlyLimit:e.target.value==='MONTHLY'?1:2}))}><option value="MONTHLY">Mensal</option><option value="FORTNIGHTLY">Quinzenal · duas datas mensais</option></select></label>{config.days.map((d,i)=><label key={i}>Dia {i+1} do mês<select value={d} disabled={busy} onChange={e=>set('days',config.days.map((x,n)=>n===i?Number(e.target.value):x))}>{Array.from({length:31},(_,n)=><option key={n+1} value={n+1}>{n+1}</option>)}</select></label>)}<label>Horário<select value={config.hour} disabled={busy} onChange={e=>set('hour',Number(e.target.value))}>{Array.from({length:24},(_,n)=><option key={n} value={n}>{String(n).padStart(2,'0')}:00</option>)}</select></label><label>Máximo de ocorrências por mês<select value={config.monthlyLimit} disabled={busy} onChange={e=>set('monthlyLimit',Number(e.target.value))}><option value={1}>1</option>{config.frequency==='FORTNIGHTLY'?<option value={2}>2</option>:null}</select></label></div>
 <p>Dias 29–31 usam o último dia quando o mês é mais curto; datas coincidentes geram uma ocorrência. Cada ocorrência reúne os tipos e formatos selecionados. O período usa o mês anterior completo, somente se publicado. A frequência quinzenal não divide medições mensais.</p>
 <div className="form-grid"><fieldset><legend>Tipos de relatório</legend>{[['OPERATIONAL','Operacional'],['EXECUTIVE','Executivo']].map(([v,label])=><label key={v}><input type="checkbox" disabled={busy} checked={config.kinds.includes(v)} onChange={e=>choice('kinds',v,e.target.checked)}/>{label}</label>)}</fieldset><fieldset><legend>Formatos</legend>{[['pdf','PDF'],['excel','Excel']].map(([v,label])=><label key={v}><input type="checkbox" disabled={busy} checked={config.formats.includes(v)} onChange={e=>choice('formats',v,e.target.checked)}/>{label}</label>)}</fieldset><fieldset><legend>Canais</legend>{[['email','E-mail'],['whatsapp','WhatsApp'],['sms','SMS · aviso do e-mail']].map(([v,label])=><label key={v}><input type="checkbox" disabled={busy||v==='email'&&config.channels.includes('sms')} checked={config.channels.includes(v)} onChange={e=>choice('channels',v,e.target.checked)}/>{label}</label>)}</fieldset></div>
 <p><Mail size={16}/> E-mail: arquivos privados enviados apenas aos contatos escolhidos. <MessageSquare size={16}/> SMS: aviso genérico, sem valores ou anexos, após aceite do e-mail pelo provedor. SMS está pendente de contratação; WhatsApp exige modelo aprovado específico.</p>
 <h3>Contatos e departamentos</h3><p>Até 10 contatos por configuração. O cadastro deve autorizar todos os canais selecionados. Mudanças de destino bloqueiam a fila até revisão.</p>{contacts.length?contacts.map((c:any)=><label key={c.id} style={{display:'block',padding:'8px 0'}}><input type="checkbox" disabled={busy||!eligible(c)} checked={config.contactIds.includes(c.id)} onChange={e=>choice('contactIds',c.id,e.target.checked)}/> {c.name} · {c.department||'Sem departamento'} · {c.email||'Sem e-mail'} · {c.phone||'Sem telefone'} {!eligible(c)?'— inativo ou sem autorização para estes canais':''}</label>):<p>Selecione um cliente e cadastre contatos adicionais em Clientes e unidades, incluindo os canais autorizados.</p>}
 <Button disabled={disabled} onClick={save}>Salvar configuração pausada</Button> {editing?<Button variant="secondary" disabled={busy} onClick={()=>{setEditing(null);setConfig(fresh());}}>Cancelar edição</Button>:null}</Card>
 <Card title="Recorrências e revisão de destinatários"><p><ShieldCheck size={18}/> A fila revalida licença, permissões, cliente, unidade, versão e contatos. Operação temporária do administrador da plataforma depende da sessão vigente; configure uma responsabilidade da organização para recorrência contínua.</p>{data?.policies.length?data.policies.map((p:any)=><div key={p.id} style={{padding:'16px 0',borderBottom:'1px solid #dbe4ed'}}><h3>{p.config.name} · {names[p.state]??p.state} · v{p.version}</h3><p>Dias {p.config.days.join(' e ')} às {String(p.config.hour).padStart(2,'0')}:00 · limite {p.config.monthlyLimit}/mês · {p.config.kinds.join(', ')} · {p.config.formats.join(', ')} · {p.config.channels.join(', ')}</p><p>Próxima data: {p.next_run?new Date(p.next_run).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'aguarda ativação'}{p.reason?' · '+(names[p.reason]??p.reason):''}</p><ul>{p.contacts.map((c:any)=><li key={c.id}>{c.name} · {c.department||'Sem departamento'} · {c.email} · {c.phone}</li>)}</ul><Button variant="secondary" disabled={busy} onClick={()=>{setEditing(p);setConfig(p.config);setReview('');}}>Editar e revisar</Button> {p.state==='ACTIVE'?<Button variant="secondary" disabled={busy} onClick={()=>state(p,false)}>Pausar recorrência</Button>:<><label style={{display:'block',padding:'8px 0'}}><input type="checkbox" disabled={busy} checked={review===p.id} onChange={e=>setReview(e.target.checked?p.id:'')}/> Revisei os contatos, canais e calendário desta versão.</label><Button disabled={busy||review!==p.id} onClick={()=>state(p,true)}>Ativar recorrência revisada</Button></>}</div>):<p>Nenhuma recorrência cadastrada. Nenhum envio será feito sem configuração e ativação.</p>}</Card>
 <Card title="Fila e histórico"><p>Versões preparadas não comprovam envio ou entrega. Aceite pelo provedor também não comprova chegada à caixa postal.</p>{data?.jobs.map((j:any)=><p key={j.id}>{new Date(j.slot).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · dados {j.month} · {names[j.state]??j.state} {j.reason?'· '+(names[j.reason]??j.reason):''} · {j.report_ids.length} versões preservadas</p>)}{!data?.jobs.length?<p>Nenhuma preparação agendada.</p>:null}<details><summary>Últimas alterações auditadas</summary>{data?.history.map((h:any)=><p key={h.id}>{new Date(h.created_at).toLocaleString('pt-BR')} · {h.action==='SAVE'?'Configuração salva':h.action==='STATE'?'Estado alterado':'Bloqueio automático'} · v{h.version} · ator {h.actor_id}</p>)}</details><Button variant="secondary" disabled={busy} onClick={()=>action(reload)}>Atualizar estado</Button></Card></section>;
}
