import {checkPortalInvite} from './portal-invite';
describe('Licensed exclusive Portal invitation before identity or email provisioning',()=>{
 const env={...process.env},id='11111111-1111-4111-8111-111111111111';
 beforeEach(()=>{process.env.CLIENT_PORTAL_LICENSES_ENABLED='true';});afterEach(()=>{process.env={...env};});
 function setup(patch:any={}){const results:any={organization_members:[],customers:{id,organization_id:'org',status:'ACTIVE',deleted_at:null},client_portal_policies:{enabled:true},client_portal_licenses:{id,organization_id:'org',customer_id:id,status:'ACTIVE',starts:'2020-01-01',ends:'2099-12-31',max_users:1},...patch};const filters:any[]=[];const client={from:jest.fn((table:string)=>{const q:any={select:()=>q,eq:(k:string,v:string)=>{filters.push([table,k,v]);return q;},maybeSingle:async()=>({data:results[table],error:null}),then:(resolve:any)=>Promise.resolve({data:results[table],count:results[table]?.length??null,error:null}).then(resolve)};return q;}),rpc:jest.fn(async()=>({data:{configured:true,shared:true,resource:'users',available:1},error:null}))};return {client,filters};}
 it('keeps existing Backoffice invitations unchanged and makes no new queries',async()=>{const f=setup();await checkPortalInvite(f.client,{affiliationType:'internal'},{name:'gestor'},'org');expect(f.client.from).not.toHaveBeenCalled();expect(f.client.rpc).not.toHaveBeenCalled();});
 it.each(['false','TRUE','1',undefined])('does not allow a Portal enrollment under disabled flag %s',async flag=>{process.env.CLIENT_PORTAL_LICENSES_ENABLED=flag as any;if(flag===undefined)delete process.env.CLIENT_PORTAL_LICENSES_ENABLED;const f=setup();await expect(checkPortalInvite(f.client,{customerId:id,affiliationType:'external'},{name:'consulta'},'org')).rejects.toMatchObject({status:403});expect(f.client.from).not.toHaveBeenCalled();});
 it.each([['internal','consulta'],['external','gestor'],['external','admin_org']])('rejects wrong binding/role %s %s',async(affiliationType,name)=>{const f=setup();await expect(checkPortalInvite(f.client,{customerId:id,affiliationType},{name},'org')).rejects.toMatchObject({status:400});expect(f.client.from).not.toHaveBeenCalled();});
 it('checks current customer, policy, license and shared quota only inside the authenticated organization',async()=>{const f=setup();await checkPortalInvite(f.client,{customerId:id,affiliationType:'external'},{name:'consulta'},'org');expect(f.filters).toContainEqual(['customers','organization_id','org']);expect(f.filters).toContainEqual(['client_portal_licenses','organization_id','org']);expect(f.filters).toContainEqual(['client_portal_licenses','customer_id',id]);expect(f.client.rpc).toHaveBeenCalledWith('client_capacity',{org:'org'});});
 it.each([{customers:{id,organization_id:'foreign',status:'ACTIVE',deleted_at:null}},{customers:{id,organization_id:'org',status:'INACTIVE',deleted_at:null}},{client_portal_policies:{enabled:false}},{client_portal_licenses:null},{client_portal_licenses:{id,organization_id:'org',customer_id:id,status:'ACTIVE',starts:'2020-01-01',ends:'2020-12-31'}}])('blocks missing/foreign/inactive/expired scope %p',async patch=>{const f=setup(patch);await expect(checkPortalInvite(f.client,{customerId:id,affiliationType:'external'},{name:'consulta'},'org')).rejects.toMatchObject({status:403});});
 it('blocks full or unconfirmed quotas before provisioning',async()=>{for(const data of [{configured:true,shared:true,resource:'users',available:0},{configured:true,available:2},null]){const f=setup();f.client.rpc.mockResolvedValue({data,error:null} as any);await expect(checkPortalInvite(f.client,{customerId:id,affiliationType:'external'},{name:'consulta'},'org')).rejects.toMatchObject({status:409});}});
 it('fails closed on database errors',async()=>{const f=setup();f.client.rpc.mockResolvedValue({data:null,error:{code:'XX'}} as any);await expect(checkPortalInvite(f.client,{customerId:id,affiliationType:'external'},{name:'consulta'},'org')).rejects.toMatchObject({status:500});});
 it('rejects a fully allocated client before sending mail',async()=>{const f=setup({organization_members:[{id:'current'}]});await expect(checkPortalInvite(f.client,{customerId:id,affiliationType:'external'},{name:'consulta'},'org')).rejects.toMatchObject({status:409});});
});
