import {BadRequestException,ConflictException,ForbiddenException,InternalServerErrorException,NotFoundException,ValidationPipe} from '@nestjs/common';
import {PERMISSIONS} from '../../../../common/constants/permissions';
import {UpdateMembershipStatusDto} from '../dto/update-membership-status.dto';
import {UsersService} from './users.service';
describe('Membership status F1.23',()=>{
 const actor='11111111-1111-4111-8111-111111111111',target='22222222-2222-4222-8222-222222222222';
 const context={actorUserId:actor,organizationId:'org-a',actorPermissions:[PERMISSIONS.ORGANIZATION_USERS_DELETE,PERMISSIONS.ORGANIZATION_USERS_UPDATE],platformOperation:false};
 function setup(status='active') {const rpc=jest.fn().mockResolvedValue({data:true,error:null});const s=new UsersService({getClient:()=>({rpc})} as any,{} as any);jest.spyOn(s,'findOne').mockResolvedValue({userId:target,membershipStatus:status,role:{id:'role-a',name:'operacional'}} as any);jest.spyOn(s,'assertAssignable').mockResolvedValue(undefined);return {s,rpc};}
 it.each(['active','inactive'] as const)('changes to %s with tenant context',async status=>{const {s,rpc}=setup(status==='active'?'inactive':'active');await expect(s.setMembershipStatus(target,status,context)).resolves.toEqual({userId:target,membershipStatus:status});expect(s.findOne).toHaveBeenCalledWith(target,'org-a');expect(s.assertAssignable).toHaveBeenCalledWith('role-a','org-a',context.actorPermissions,false);expect(rpc).toHaveBeenCalledWith('set_organization_member_status',expect.objectContaining({actor_user_id:actor,target_organization_id:'org-a',target_user_id:target,target_status:status,expected_role_id:'role-a'}));});
 it('legacy DELETE uses same atomic method',async()=>{const {s}=setup();const spy=jest.spyOn(s,'setMembershipStatus');await s.deactivate(target,context);expect(spy).toHaveBeenCalledWith(target,'inactive',context);});
 it.each(['active','inactive'] as const)('rejects self change %s',async status=>{const {s,rpc}=setup();await expect(s.setMembershipStatus(actor,status,context)).rejects.toBeInstanceOf(BadRequestException);expect(rpc).not.toHaveBeenCalled();});
 it.each([['active',PERMISSIONS.ORGANIZATION_USERS_DELETE],['inactive',PERMISSIONS.ORGANIZATION_USERS_UPDATE]] as const)('rejects opposite permission for %s',async(status,permission)=>{const {s,rpc}=setup();await expect(s.setMembershipStatus(target,status,{...context,actorPermissions:[permission]})).rejects.toBeInstanceOf(ForbiddenException);expect(rpc).not.toHaveBeenCalled();});
 it('missing permissions fail closed',async()=>{const {s,rpc}=setup();await expect(s.deactivate(target,{...context,actorPermissions:undefined})).rejects.toBeInstanceOf(ForbiddenException);expect(rpc).not.toHaveBeenCalled();});
 it('rejects role outside hierarchy',async()=>{const {s,rpc}=setup();jest.spyOn(s,'assertAssignable').mockRejectedValue(new BadRequestException());await expect(s.deactivate(target,context)).rejects.toBeInstanceOf(BadRequestException);expect(rpc).not.toHaveBeenCalled();});
 it('rejects missing membership',async()=>{const {s,rpc}=setup();jest.spyOn(s,'findOne').mockRejectedValue(new NotFoundException());await expect(s.deactivate(target,context)).rejects.toBeInstanceOf(NotFoundException);expect(rpc).not.toHaveBeenCalled();});
 it('rejects stale status',async()=>{const {s,rpc}=setup('inactive');await expect(s.deactivate(target,context)).rejects.toBeInstanceOf(ConflictException);expect(rpc).not.toHaveBeenCalled();});
 it.each([['42501',ForbiddenException],['P3230',NotFoundException],['P3231',ConflictException],['P3232',BadRequestException],['P3152',BadRequestException],['XX000',InternalServerErrorException]] as const)('maps database error %s',async(code,klass)=>{const {s,rpc}=setup();rpc.mockResolvedValue({data:null,error:{code}});await expect(s.deactivate(target,context)).rejects.toBeInstanceOf(klass);});
 it('does not report success without result',async()=>{const {s,rpc}=setup();rpc.mockResolvedValue({data:null,error:null});await expect(s.deactivate(target,context)).rejects.toBeInstanceOf(InternalServerErrorException);});
 it.each([{status:'deleted'},{status:'active',organizationId:'other'},{status:'active',actorUserId:target},{}])('rejects invalid body %p',async body=>{const pipe=new ValidationPipe({transform:true,whitelist:true,forbidNonWhitelisted:true});await expect(pipe.transform(body,{type:'body',metatype:UpdateMembershipStatusDto})).rejects.toBeInstanceOf(BadRequestException);});
});
