import {inspectDocument} from './document-file';
function zip(entries:{name:string;data:Buffer}[]){let offset=0;const locals:Buffer[]=[],central:Buffer[]=[];for(const e of entries){const n=Buffer.from(e.name),local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt32LE(e.data.length,18);local.writeUInt32LE(e.data.length,22);local.writeUInt16LE(n.length,26);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt32LE(e.data.length,20);c.writeUInt32LE(e.data.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);locals.push(local,n,e.data);central.push(c,n);offset+=30+n.length+e.data.length;}const cs=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(cs.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,cs,end]);}
describe('evidence format boundary',()=>{const entries=['[Content_Types].xml','xl/workbook.xml','xl/worksheets/sheet1.xml'].map(name=>({name,data:Buffer.from('<xml/>')}));const mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';const f=(buffer:Buffer,name='test.xlsx',mimetype=mime)=>({buffer,originalname:name,mimetype,size:buffer.length});
 it('accepts bounded XLSX container only for OTHER/evidence',()=>{expect(inspectDocument(f(zip(entries)),true).extension).toBe('xlsx');expect(()=>inspectDocument(f(zip(entries)))).toThrow();});
 it('rejects macros, external links, traversal, duplicate entries and truncated ZIP',()=>{for(const name of ['xl/vbaProject.bin','xl/externalLinks/externalLink1.xml','../secret','xl/workbook.xml'])expect(()=>inspectDocument(f(zip([...entries,{name,data:Buffer.from('x')}])),true)).toThrow();expect(()=>inspectDocument(f(zip(entries).subarray(0,-1)),true)).toThrow();});
 it('rejects non-Office ZIP disguised as XLSX and oversized expansion',()=>{expect(()=>inspectDocument(f(zip([{name:'test.txt',data:Buffer.from('x')}])),true)).toThrow();const b=zip(entries);const e=b.length-22;const start=b.readUInt32LE(e+16);b.writeUInt32LE(30*1024*1024,start+24);expect(()=>inspectDocument(f(b),true)).toThrow();});
 it('accepts UTF-8 CSV as inert attachment but never OCR input',()=>{const file=f(Buffer.from('\ufeffnome;valor\nabc;123'),'evidence.csv','text/csv');expect(inspectDocument(file,true).mime).toBe('text/csv');expect(()=>inspectDocument(file)).toThrow();});
 it('rejects binary, malformed UTF-8, empty CSV and wrong MIME',()=>{for(const bytes of [Buffer.from([0,1]),Buffer.from([255,255]),Buffer.from(' ')])expect(()=>inspectDocument(f(bytes,'test.csv','text/csv'),true)).toThrow();expect(()=>inspectDocument(f(Buffer.from('a,b'),'test.csv','application/pdf'),true)).toThrow();});
});
