import {searchRegistrations} from './registration-search';
function fixture(){const calls:any[]=[];const b:any={};for(const k of ['from','select','eq','or','ilike','order'])b[k]=(...args:any[])=>{calls.push([k,...args]);return b;};b.range=jest.fn(async(...args:any[])=>{calls.push(['range',...args]);return {data:[{id:'one'}],count:73,error:null};});return {b,calls};}
describe('registration search',()=>{
 it('scopes and pages customers with deterministic sorting',async()=>{const {b,calls}=fixture();const r=await searchRegistrations(b,'org','customers',{page:'2',size:'20',status:'INACTIVE',q:'Fuga'});expect(r).toMatchObject({total:73,page:2,size:20});expect(calls).toContainEqual(['eq','organization_id','org']);expect(calls).toContainEqual(['eq','status','INACTIVE']);expect(calls).toContainEqual(['range',20,39]);expect(calls).toContainEqual(['order','id',{ascending:true}]);});
 it('applies combined unit filters without removing tenant scope',async()=>{const {b,calls}=fixture();await searchRegistrations(b,'org','consumer_units',{city:'Jales',distributor:'Elektro',size:'50'});expect(calls).toContainEqual(['eq','organization_id','org']);expect(calls).toContainEqual(['ilike','city','%Jales%']);expect(calls).toContainEqual(['ilike','distributor','%Elektro%']);expect(calls).toContainEqual(['range',0,49]);});
 it.each([{page:'0'},{size:'1000'},{page:'1.5'},{page:['1','2']},{status:'oops'},{organization_id:'other'},{sort:'delete'}])('rejects invalid query %j',async(q)=>{const {b}=fixture();await expect(searchRegistrations(b,'org','customers',q)).rejects.toThrow();});
 it('does not allow filter syntax in a name to change the query',async()=>{const {b,calls}=fixture();await searchRegistrations(b,'org','customers',{q:'Fuga,status.eq.INACTIVE'});expect(calls.find(c=>c[0]==='or')[1]).not.toContain('Fuga,status');});
 it('searches full CPF/CNPJ with or without punctuation',async()=>{const {b,calls}=fixture();await searchRegistrations(b,'org','customers',{document:'91.302.349/0014-58'});expect(calls).toContainEqual(['or','document.ilike.*91302349001458*,document.ilike.*91.302.349/0014-58*']);});
 it('reports errors rather than claiming an empty result',async()=>{const {b}=fixture();b.range.mockResolvedValue({data:null,count:null,error:{}});await expect(searchRegistrations(b,'org','customers')).rejects.toThrow('consultar');});
});
