'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import styles from '../backoffice/trading-hub/trading.module.css';
type Portal={kind:'SUPPLIER'|'CLIENT';email:string;expiresAt:string;opportunity:{title:string;customer:string;distributor:string;submarket:string;averageMwhMonth:number;energyType:string;months:number;startMonth:string;documents:string[]};proposal:Record<string,any>|null;dashboard:{pending:number;responded:number}};
const reasons=[['INSUFFICIENT_VOLUME','Volume insuficiente'],['REGION','Região não atendida'],['RISK','Risco comercial'],['UNAVAILABLE','Indisponibilidade'],['OTHER','Outro motivo']];
export default function Page(){
 const token=useRef(''),session=useRef('');const [valid,setValid]=useState(false),[challenged,setChallenged]=useState(false),[data,setData]=useState<Portal|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false),[decline,setDecline]=useState(false),[files,setFiles]=useState<{id:string;filename:string}[]>([]);
 useEffect(()=>{if(token.current)return;token.current=window.location.hash.slice(1);setValid(/^[a-f0-9]{64}$/.test(token.current));history.replaceState(null,'',window.location.pathname);},[]);
 function request<T>(path:string,method='GET',body?:unknown,useToken=false){return apiRequest<T>('/api/v1/trading-portal'+path,{method,body,authenticated:false,cache:'no-store',headers:{[useToken?'x-trading-token':'x-trading-session']:useToken?token.current:session.current}});}
 async function run(task:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await task();}catch(e){setError(e instanceof Error?e.message:'Operação indisponível.');}finally{setBusy(false);}}
 async function verify(e:FormEvent<HTMLFormElement>){e.preventDefault();const code=String(new FormData(e.currentTarget).get('code'));await run(async()=>{const r=await request<{session:string}>('/verify','POST',{code},true);session.current=r.session;setData(await request<Portal>(''));token.current='';});}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{let body:unknown;if(data?.kind==='CLIENT')body={action:'APPROVE',data:{confirmed:f.get('confirmed')==='on'},reason:String(f.get('reason'))};else if(decline)body={action:'DECLINE',data:{declineReason:String(f.get('declineReason'))},reason:String(f.get('reason'))};else{const d:Record<string,any>={energyType:data?.opportunity.energyType,documents:files.map(x=>x.id)};for(const k of ['priceBrlMwh','flexibility','modulation','guarantees','conditions','validUntil'])d[k]=String(f.get(k));d.priceBrlMwh=Number(d.priceBrlMwh);body={action:'RESPOND',data:d};}await request('/reply','POST',body);session.current='';setData(null);setDone(true);});}
 async function download(id:string){await run(async()=>{const r=await request<{url:string}>('/documents/'+encodeURIComponent(id));const a=document.createElement('a');a.href=r.url;a.rel='noopener noreferrer';a.click();});}
 return <main className="backoffice-page" style={{maxWidth:1000,margin:'auto',padding:24}}><h1>Trading Hub · Expert Energy</h1><p>Portal de cotações ACL</p>{error?<Alert variant="error">{error}</Alert>:null}{done?<Card title="Resposta registrada"><p>Sua resposta foi salva com data, identidade verificada e histórico. Este acesso foi encerrado.</p></Card>:!data?<Card title="Acesso por convite"><p>O código será enviado ao mesmo e-mail que recebeu o convite. O link expira na data da cotação.</p>{!valid?<p>Abra o link completo recebido por e-mail. Para retomar um acesso, abra o convite novamente.</p>:<><Button disabled={busy} onClick={()=>void run(async()=>{await request('/challenge','POST',undefined,true);setChallenged(true);})}>{challenged?'Enviar outro código':'Enviar código ao meu e-mail'}</Button>{challenged?<form onSubmit={verify}><Input label="Código de seis dígitos" name="code" required pattern="[0-9]{6}" inputMode="numeric" autoComplete="one-time-code" maxLength={6} disabled={busy}/><Button type="submit" disabled={busy}>Verificar e acessar</Button></form>:null}</>}</Card>:<>
 <div className={styles.grid}><Card title="Pendentes"><strong>{data.dashboard.pending}</strong></Card><Card title="Respondidas"><strong>{data.dashboard.responded}</strong></Card></div>
 <Card title={data.opportunity.title}><p>Cliente: {data.opportunity.customer} · {data.opportunity.distributor} · {data.opportunity.submarket}</p><p>{data.opportunity.averageMwhMonth} MWh/mês · {data.opportunity.months} meses a partir de {data.opportunity.startMonth}</p><p>Modalidade: {data.opportunity.energyType}</p><p>Acesso de {data.email} · expira em {new Date(data.expiresAt).toLocaleString('pt-BR')}</p>{data.opportunity.documents.map((id,i)=><Button key={id} variant="secondary" disabled={busy} onClick={()=>void download(id)}>Baixar documento {i+1}</Button>)}</Card>
 {data.kind==='CLIENT'?<Card title="Decisão sobre a proposta"><p>Esta proposta recebeu aprovação interna do gestor.</p><p>Preço: R$ {Number(data.proposal?.priceBrlMwh).toLocaleString('pt-BR')}/MWh · validade {data.proposal?.validUntil}</p>{[['flexibility','Flexibilidade'],['modulation','Modulação'],['guarantees','Garantias'],['conditions','Condições comerciais']].map(([k,l])=><p key={k}><strong>{l}:</strong> {data.proposal?.[k]}</p>)}{(data.proposal?.documents??[]).map((id:string,i:number)=><Button key={id} variant="secondary" disabled={busy} onClick={()=>void download(id)}>Baixar proposta PDF {i+1}</Button>)}<p>A aprovação registra sua decisão comercial. A contratação será registrada pelo backoffice após a formalização.</p><form onSubmit={submit}><label><input name="confirmed" type="checkbox" required disabled={busy}/> Li e aprovo esta proposta comercial.</label><Input label="Justificativa da decisão" name="reason" required minLength={3} maxLength={500} disabled={busy}/><Button type="submit" disabled={busy}>Registrar aprovação comercial</Button></form></Card>:<Card title={decline?'Não participar':'Enviar proposta'}><div className={styles.actions}><Button variant="secondary" disabled={busy} onClick={()=>setDecline(false)}>Apresentar proposta</Button><Button variant="secondary" disabled={busy} onClick={()=>setDecline(true)}>Não participar</Button></div><form key={decline?'decline':'proposal'} className={styles.form} onSubmit={submit}>{decline?<><label>Motivo<select name="declineReason" className="ds-input" required disabled={busy}>{reasons.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><Input label="Justificativa obrigatória" name="reason" required minLength={3} maxLength={500} disabled={busy}/></>:<><Input label="Preço de energia (R$/MWh)" name="priceBrlMwh" type="number" min="0.01" step="0.01" required disabled={busy}/>{[['flexibility','Flexibilidade'],['modulation','Modulação'],['guarantees','Garantias'],['conditions','Condições comerciais']].map(([k,l])=><Input key={k} label={l} name={k} required maxLength={4000} disabled={busy}/>)}<Input label="Validade da proposta" name="validUntil" type="date" required disabled={busy}/><label>Anexar proposta em PDF (até 10 MB)<input type="file" accept="application/pdf,.pdf" disabled={busy||files.length>=10} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>{if(file.size>10485760)throw new Error('PDF excede 10 MB.');const f=new FormData();f.append('file',file);const r=await request<{id:string;filename:string}>('/files','POST',f);setFiles(old=>[...old,r]);});}}/></label><ul>{files.map(f=><li key={f.id}>{f.filename}</li>)}</ul></>}<Button type="submit" disabled={busy}>{busy?'Registrando…':decline?'Registrar não participação':'Enviar proposta'}</Button></form></Card>}
 </>}</main>;
}
