'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import LicenseFromPlan,{PlanLicense} from '@/app/components/LicenseFromPlan';
import BackofficeShell from '@/app/components/BackofficeShell';
import ProtectedRoute from '@/app/components/ProtectedRoute';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {planModules} from '@/app/lib/api/plans';
import {useAuth} from '@/app/providers';
type Upgrade={id:string;note:string;created_at:string};
type Usage={used:{users:number;units:number;documents:number};license:PlanLicense|null;requests:Upgrade[];updatedAt:string};
function Licenses(){
 const {context,hasPermission}=useAuth();const platform=context?.scope!=='global'&&context?.accessMode==='platform_operation';
 const view=hasPermission('8c5673e4-115c-4ab7-bb11-3b410eddcad3');
 const [rows,setRows]=useState<PlanLicense[]>([]),[usage,setUsage]=useState<Usage|null>(null),[editing,setEditing]=useState<PlanLicense|null>(null),[creating,setCreating]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(()=>Promise.all([apiRequest<PlanLicense[]>('/api/v1/licenses'),apiRequest<Usage>('/api/v1/licenses/usage')]).then(([r,u])=>{setRows(r);setUsage(u);setError('');}).catch(e=>{setUsage(null);setError(e instanceof Error?e.message:'Não foi possível consultar o consumo.');}),[]);
 useEffect(()=>{if(!view)return;void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);const timer=window.setInterval(refresh,30000);return()=>{window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);window.clearInterval(timer);};},[view,load]);
 async function request(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const note=String(new FormData(e.currentTarget).get('note')||'');setBusy(true);setError('');try{await apiRequest('/api/v1/licenses/upgrade-requests',{method:'POST',body:{note}});setMessage('Solicitação registrada para o administrador da plataforma.');await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao solicitar upgrade.');}finally{setBusy(false);}}
 if(!view)return <p>Acesso à licença não autorizado.</p>;
 const l=usage?.license;
 return <section className="backoffice-page"><h1>{platform?'Licença e módulos':'Meu plano e consumo'}</h1><p>Planos, limites e módulos são definidos exclusivamente pelo administrador da plataforma.</p>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}<Button variant="secondary" onClick={()=>void load()}>Atualizar consumo</Button>
 {usage?<Card title={l?l.license_type:'Sem licença vigente'}>{l&&!l.plan_id?<Alert>Licença anterior ao catálogo. O administrador da plataforma deve selecionar um plano para permitir novos cadastros. Os registros existentes foram preservados.</Alert>:null}{!l?<p>Solicite ao administrador da plataforma uma licença vigente para novos cadastros.</p>:null}<table><thead><tr><th>Recurso</th><th>Contratado</th><th>Utilizado</th><th>Disponível</th></tr></thead><tbody>{([['users','Usuários ativos',l?.max_users,false],['units','Unidades cadastradas',l?.max_consumer_units,false],['documents','Documentos mantidos',l?.documents_limit,l?.documents_unlimited]] as const).map(([key,label,cap,unlimited])=><tr key={key}><td>{label}</td><td>{unlimited?'Ilimitado':cap??'Não definido'}</td><td>{usage.used[key]}</td><td>{unlimited?'Ilimitado':cap==null?'—':Math.max(0,cap-usage.used[key])}</td></tr>)}</tbody></table><p>Usuários internos e externos com vínculo ativo ocupam vaga. Unidades inativas continuam contabilizadas. Documentos não têm renovação mensal.</p>{l?<p>Módulos liberados: {planModules.filter(([k])=>l[k]).map(([,name])=>name).join(', ')||'Nenhum'}</p>:null}<p>Atualizado em {new Date(usage.updatedAt).toLocaleString('pt-BR')}.</p></Card>:null}
 {usage?.requests.map(r=><Card key={r.id} title="Upgrade solicitado — aguardando análise"><p>{r.note}</p><p>{new Date(r.created_at).toLocaleString('pt-BR')}</p></Card>)}
 {!platform&&usage&&!usage.requests.length?<Card title="Solicitar upgrade"><form onSubmit={request} className="organizations-create__form"><Input label="O que sua organização precisa ampliar?" name="note" required minLength={3} maxLength={2000} disabled={busy}/><Button type="submit" disabled={busy}>Enviar solicitação</Button></form></Card>:null}
 {platform?<><Button disabled={busy} onClick={()=>{setEditing(null);setCreating(true);}}>Criar licença com plano</Button>{creating||editing?<LicenseFromPlan key={editing?.id||'new'} editing={editing} onCancel={()=>{setCreating(false);setEditing(null);}} onCreated={async()=>{setCreating(false);setEditing(null);await load();}}/>:null}</>:null}
 <h2>Licenças da organização</h2>{rows.map(row=><Card key={row.id} title={row.license_type}><p>{row.plan_id?'Plano aplicado — versão '+row.plan_version:'Regularização de plano pendente'} · {row.status}</p><p>Vigência: {row.start_date} a {row.end_date||'sem término definido'}</p>{platform?<Button variant="secondary" onClick={()=>{setCreating(false);setEditing(row);}}>{row.plan_id?'Alterar plano / licença':'Selecionar plano e regularizar'}</Button>:null}</Card>)}</section>;
}
export default function Page(){const {context}=useAuth();const id=context&&context.scope!=='global'?context.currentOrganization.id:'';return <ProtectedRoute><BackofficeShell>{id?<Licenses key={id}/>:<p>Selecione uma organização na administração da plataforma.</p>}</BackofficeShell></ProtectedRoute>;}
