export const operations={agenda:{label:'Agenda',view:'cb949e2a-e01d-4cf0-8c69-6ca74fe4d627',manage:'6da45eb4-810c-4e40-9933-d9cda66a8841'},requests:{label:'Solicitações',view:'1479c0b7-9608-4e95-bd83-7e6899255a78',manage:'d1f1b3be-a842-41e7-aeb1-45fefeb2f4c1'},events:{label:'Eventos',view:'489e6387-d5fc-4cb0-81f9-d7a76269dca5',manage:'d617b0f0-0fba-42f8-8707-811070346ef0'}} as const;
export type OperationKind=keyof typeof operations;
export type OperationRow={auditIdentities?:Record<string,import("@/app/components/AuditIdentity").Identity>;auditCompany?:{id:string;currentName:string|null};id:string;operation_number?:number;requested_by_name?:string;created_at?:string;kind:OperationKind;title:string;description:string;status:string;priority:string;customer_id:string|null;consumer_unit_id:string|null;responsible_id:string;due_at:string|null;starts_at:string|null;ends_at:string|null;document_id:string|null;request_type:string|null;table_text:string|null;revision:number;updated_at:string;created_by:string};
export type NotificationRow={key:string;id:string;title:string;priority:string;date:string;dueAt:string|null;overdue:boolean;origin:OperationKind|'ocr'|'energy'|'management'|'license';description?:string;status:string;read:boolean;href:string};
export const statusLabels:Record<string,string>={OPEN:'Aberta',DRAFT:'Rascunho',IN_PROGRESS:'Em andamento',WAITING:'Aguardando retorno',DONE:'Concluída',CANCELLED:'Cancelada',REVIEW:'Em revisão',PUBLISHED:'Publicado',ARCHIVED:'Arquivado'};
export const priorityLabels:Record<string,string>={LOW:'Baixa',NORMAL:'Normal',HIGH:'Alta',URGENT:'Urgente'};
export function nextOperationStatuses(kind:OperationKind,status:string):string[]{const choices:Record<string,string[]>=(kind==='events'?{DRAFT:['REVIEW'],REVIEW:['DRAFT','PUBLISHED'],PUBLISHED:['ARCHIVED']}:{OPEN:['IN_PROGRESS','WAITING','DONE','CANCELLED'],IN_PROGRESS:['WAITING','DONE','CANCELLED'],WAITING:['IN_PROGRESS','DONE','CANCELLED']});return choices[status]??[];}

export const notificationOrigins:Record<string,string>={agenda:'Agenda',requests:'Solicitações',events:'Eventos',ocr:'OCR / documentos',energy:'Contratos de energia',management:'Honorários',license:'Licença'};
export const notificationStates:Record<string,string>={...statusLabels,SUCCEEDED:'Extração concluída',FAILED:'Falha de processamento',SUBMISSION_UNKNOWN:'Envio com resultado incerto',EXPIRING:'Prazo próximo',OVERDUE:'Prazo ultrapassado'};
