'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import BackofficeShell from '@/app/components/BackofficeShell';
import ProtectedRoute from '@/app/components/ProtectedRoute';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
type Summary={total_cost_brl_cents:number|null;projected_cost_brl_cents:number|null;infrastructure_brl_cents:number|null;month:string;policy:any;totals:any;daily:any[];modules:any[];companies:any[];infrastructure:any[];runtime:any[];alerts:any[];database:any;providers:any;global_ceiling_micro_usd:number;projection_micro_usd:number|null;costBasis:string;allocationBasis:string};
const usd=(micro:unknown)=>micro==null?'Não disponível':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'USD',maximumFractionDigits:4}).format(Number(micro)/1e6);
const brl=(cents:unknown)=>cents==null?'Não informado':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents)/100);
const number=(v:unknown)=>v==null?'Não disponível':Number(v).toLocaleString('pt-BR');
const bytes=(v:unknown)=>v==null?'Não conectado':(Number(v)/1024**3).toFixed(2)+' GB';
const moduleNames:Record<string,string>={OCR:'OCR + interpretação IA',BOT_ENERGY:'Bot-Energy',CHAT:'Chat',AUDITORIA:'Auditoria',ANALISES:'Análises',RAG:'Busca RAG',INDEXACAO:'Indexação da base',UNCLASSIFIED:'Histórico sem módulo identificado'};
const cell={textAlign:'left' as const,padding:'12px',borderBottom:'1px solid #334155'};
function Table({head,rows}:{head:string[];rows:(string|number)[][]}){return <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{head.map(h=><th key={h} scope="col" style={cell}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} style={cell}>{v}</td>)}</tr>):<tr><td style={cell} colSpan={head.length}>Sem registros para esta competência.</td></tr>}</tbody></table></div>;}
function Costs(){
 const {hasPermission}=useAuth(),manage=hasPermission('af285642-16b0-405a-982c-58de1a10f987');
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[company,setCompany]=useState('');
 const load=useCallback(async()=>{try{const r=await apiRequest<Summary>('/api/v1/admin/platform-costs?month='+month);setData(r);setError('');}catch(e){setData(null);setError(e instanceof Error?e.message:'Falha ao consultar dados completos.');}},[month]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},60000);return()=>clearInterval(timer);},[load]);
 async function save(e:FormEvent<HTMLFormElement>,kind:'policy'|'infrastructure'){
  e.preventDefault();if(busy||!data)return;const f=new FormData(e.currentTarget);let body:Record<string,unknown>;
  if(kind==='policy'){body={revision:data.policy.revision,platform_ai_micro_usd:Math.round(Number(f.get('platform_usd'))*1e6),monthly_cost_limit_brl_cents:String(f.get('cost_limit_brl')||'')?Math.round(Number(f.get('cost_limit_brl'))*100):undefined,email_enabled:f.has('email_enabled'),email:String(f.get('email')||'')||undefined,whatsapp:String(f.get('whatsapp')||'')||undefined,usd_brl_rate:String(f.get('fx')||'')?Number(f.get('fx')):undefined,fx_date:String(f.get('fx_date')||'')||undefined};}
  else{body={month:month+'-01',provider:String(f.get('provider')),service:String(f.get('service')),category:String(f.get('category')),organization_id:String(f.get('org')||'')||undefined,amount_minor:Math.round(Number(f.get('amount'))*100),currency:String(f.get('currency')),basis:String(f.get('basis')),source:String(f.get('source'))};}
  setBusy(true);setError('');try{await apiRequest('/api/v1/admin/platform-costs/'+kind,{method:kind==='policy'?'PATCH':'POST',body});setMessage(kind==='policy'?'Política e alertas salvos com auditoria.':'Custo registrado com origem e competência.');await load();}catch(e){setError(e instanceof Error?e.message:'Alteração não confirmada.');}finally{setBusy(false);}
 }
 const companies=data?.companies.filter(c=>!company||c.organization_id===company)??[];
 return <section className="backoffice-page"><h1>Painel Administrativo de Custos e Performance da Plataforma</h1><p>Custos estimados de IA, capacidade, infraestrutura e contribuição por empresa licenciada. Os valores não substituem as faturas dos provedores.</p><div style={{display:'flex',gap:16,flexWrap:'wrap',alignItems:'end'}}><Input label="Competência (UTC)" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><Button disabled={busy} variant="secondary" onClick={()=>void load()}>Atualizar painel</Button></div>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}{!data&&!error?<p>Carregando indicadores…</p>:null}
 {data?<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:16,marginTop:20}}><Card title="Tokens do mês"><strong>{number(Number(data.totals.input_tokens??0)+Number(data.totals.output_tokens??0))}</strong><p>Entrada + saída identificadas pelo provedor</p></Card><Card title="Custo estimado de IA"><strong>{usd(data.totals.actual_micro_usd)}</strong><p>Reservas pendentes: {usd(data.totals.reserved_micro_usd)}</p></Card><Card title="Projeção mensal"><strong>{usd(data.projection_micro_usd)}</strong><p>Ritmo médio desde o início do mês; disponível após 24 horas</p></Card><Card title="Capacidade de IA contratada"><strong>{usd(data.global_ceiling_micro_usd)}</strong><p>Cotas vigentes, compromissos do mês e verba administrativa</p></Card></div>
 <Card title="1. Consumo de tokens e custos"><p>{data.costBasis}. USD preservado; BRL usa apenas o câmbio cadastrado: {data.policy.usd_brl_rate??'não informado'} {data.policy.fx_date?'em '+data.policy.fx_date:''}.</p><h3>Por módulo</h3><Table head={['Módulo','Entrada','Saída','Chamadas','Custo estimado']} rows={data.modules.map(r=>[moduleNames[r.module]??r.module,number(r.input_tokens),number(r.output_tokens),number(r.calls),usd(r.actual_micro_usd)])}/><p>{data.providers.ocr} Módulos sem registro não são apresentados como consumo zero.</p><h3>Por dia</h3><Table head={['Dia (UTC)','Entrada','Saída','Custo estimado']} rows={data.daily.map(r=>[r.day,number(r.input_tokens),number(r.output_tokens),usd(r.actual_micro_usd)])}/></Card>
 <Card title="2. Servidores, banco e tempo de resposta"><Table head={['Serviço / instância','CPU','RAM','Disco utilizado','Rede recebida / enviada','Resposta média','Última coleta']} rows={data.runtime.map(r=>[r.service+' · '+r.instance.slice(0,12),r.metrics.cpuPercent==null?'Não disponível':Number(r.metrics.cpuPercent).toFixed(1)+'% (1 núcleo)',bytes(r.metrics.containerMemoryBytes??r.metrics.rssBytes),bytes(r.metrics.diskUsedBytes),bytes(r.metrics.networkRxBytes)+' / '+bytes(r.metrics.networkTxBytes),r.metrics.responseAverageMs==null?'Sem chamadas':Number(r.metrics.responseAverageMs).toFixed(1)+' ms',new Date(r.observed_at).toLocaleString('pt-BR')])}/><p>Banco PostgreSQL: {bytes(data.database.databaseBytes)}. RAM/CPU do PostgreSQL e métricas do frontend: não conectadas. Rede é acumulada desde o início do container; disco refere-se ao filesystem da API. Sem amostra nos últimos 10 minutos: telemetria indisponível.</p></Card>
 <Card title="3. Custo de infraestrutura"><p>Total registrado: <strong>{brl(data.total_cost_brl_cents)}</strong> · Projeção com IA: <strong>{brl(data.projected_cost_brl_cents)}</strong>. Totais dependem do câmbio para valores em USD.</p><p>Registre faturas ou estimativas com origem. Custos compartilhados permanecem separados até um rateio explícito.</p><Table head={['Serviço','Provedor','Categoria','Valor','Base','Origem']} rows={data.infrastructure.map(r=>[r.service,r.provider,r.category,r.currency==='BRL'?brl(r.amount_minor):usd(Number(r.amount_minor)*10000),r.basis==='INVOICE'?'Fatura':'Estimativa',r.source])}/>{manage?<form onSubmit={e=>void save(e,'infrastructure')} className="organizations-create__form"><h3>Registrar custo da competência</h3><Input label="Provedor" name="provider" required maxLength={80} disabled={busy}/><Input label="Serviço" name="service" required maxLength={120} disabled={busy}/><label>Categoria<select className="ds-input" name="category">{['SERVER','DATABASE','STORAGE','BACKUP','OCR','OTHER'].map(k=><option key={k}>{k}</option>)}</select></label><label>Atribuição<select className="ds-input" name="org"><option value="">Compartilhado — sem rateio</option>{data.companies.map(c=><option key={c.organization_id} value={c.organization_id}>{c.name}</option>)}</select></label><Input label="Valor" name="amount" type="number" min={0} step={.01} required disabled={busy}/><label>Moeda<select className="ds-input" name="currency"><option>BRL</option><option>USD</option></select></label><label>Base<select className="ds-input" name="basis"><option value="INVOICE">Fatura</option><option value="ESTIMATE">Estimativa</option></select></label><Input label="Referência da fatura ou estimativa" name="source" required minLength={3} maxLength={1000} disabled={busy}/><Button type="submit" disabled={busy}>Registrar custo com auditoria</Button></form>:null}</Card>
 <Card title="4. Consumo e rentabilidade por empresa"><label>Empresa licenciada<select className="ds-input" value={company} onChange={e=>setCompany(e.target.value)}><option value="">Todas</option>{data.companies.map(c=><option key={c.organization_id} value={c.organization_id}>{c.name}</option>)}</select></label><Table head={['Empresa','Tokens','Custo IA','Reservas','Cota / mês','Projeção','Infra direta (R$)','Receita (R$)','Contribuição (R$)','Alerta']} rows={companies.map(c=>[c.name,number(Number(c.input_tokens)+Number(c.output_tokens)),usd(c.actual_micro_usd),usd(c.reserved_micro_usd),usd(c.quota_micro_usd),usd(c.projection_micro_usd),brl(c.direct_infra_brl_cents),brl(c.revenue_brl_cents),brl(c.contribution_brl_cents),c.level??'Dentro da cota'])}/><p>{data.allocationBasis} Receita vem da mensalidade informada na licença; ausência não é receita zero.</p></Card>
 <Card title="Alertas automáticos"><p>Avisos em 80%, 95%, limite atingido e projeção acima da cota, além de risco de capacidade da API. Reservas sem confirmação continuam consumindo o limite até conciliação.</p><p>E-mail: {data.policy.email_enabled?data.policy.email:'Desativado'} — {data.providers.email==='CONFIGURED'?'provedor configurado':'aguardando configuração do provedor'} · WhatsApp: {data.policy.whatsapp||'Não definido'} — {data.providers.whatsapp==='CONFIGURED'?'provedor configurado':'aguardando provedor e template aprovado'}</p><Table head={['Criado','Nível','Canal','Situação','Mensagem']} rows={data.alerts.map(a=>[new Date(a.created_at).toLocaleString('pt-BR'),a.level,a.channel,a.state,a.message])}/>{manage?<form key={data.policy.revision} onSubmit={e=>void save(e,'policy')} className="organizations-create__form"><Input label="Verba mensal administrativa de IA (US$)" name="platform_usd" type="number" min={0} max={1000000} step={.01} required defaultValue={Number(data.policy.platform_ai_micro_usd)/1e6} disabled={busy}/><p>A capacidade global acompanha as cotas das licenças vigentes. A cota de cada empresa continua independente; saldo não acumula. Aumentar verba não compra capacidade do provedor.</p><Input label="Limite mensal de custo total (R$) — opcional" name="cost_limit_brl" type="number" min={0.01} step={.01} defaultValue={data.policy.monthly_cost_limit_brl_cents==null?'':Number(data.policy.monthly_cost_limit_brl_cents)/100} disabled={busy}/><Input label="E-mail dos alertas" name="email" type="email" defaultValue={data.policy.email} disabled={busy}/><label><input type="checkbox" name="email_enabled" defaultChecked={data.policy.email_enabled}/> Enviar alertas por e-mail</label><Input label="WhatsApp com DDI" name="whatsapp" defaultValue={data.policy.whatsapp} disabled={busy}/><Input label="Câmbio USD para BRL — informado pelo administrador" name="fx" type="number" min={.000001} max={10000} step={.000001} defaultValue={data.policy.usd_brl_rate??''} disabled={busy}/><Input label="Data do câmbio" name="fx_date" type="date" defaultValue={data.policy.fx_date??''} disabled={busy}/><Button type="submit" disabled={busy}>Salvar política e destinatários</Button></form>:null}</Card></>:null}</section>;
}
export default function Page(){const {context,hasPermission}=useAuth();return <ProtectedRoute><BackofficeShell>{context?.scope==='global'&&hasPermission('e23a5c98-8b68-4ed2-aef8-70a7166407e4')?<Costs/>:<p>Acesso exclusivo ao administrador da plataforma.</p>}</BackofficeShell></ProtectedRoute>;}
