'use client';
import type {ContractSupplierData} from './ContractSupplierCost';
import type {ManagementFeeData} from './ManagementFeeMemory';
import type {SupplierCostsData,AdditionalCostsData} from './FinancialCosts';
import type {DistributorSubtotalData} from './DistributorSubtotal';
import ScenarioComparison from './ScenarioComparison';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Card} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {Unit,date} from './types';
import TariffPreview,{TariffPreviewData} from './TariffPreview';
import MonthlyCostLedger,{MonthlyCostLedgerData} from './MonthlyCostLedger';
import {CorrectionContext,correctionTarget} from './preparation-navigation';
import SupplyReference,{SupplyReferenceData} from './SupplyReference';
import TaxMemory,{TaxMemoryData} from './TaxMemory';
type Period={start:string;end:string};
type Coverage={gaps:Period[];overlap:boolean;segments:number};
type CostSummary={status:string;draftCount:number;validatedCount:number;validatedVersion:{version:number;revision:number;validatedAt:string;source:string;costs:{noCosts:boolean;items:{id:string;label:string;category:string;scenario:string;effect:string;amount:string;source:string;taxTreatment:string}[]}}|null};
type Result={contractSupplierCost?:ContractSupplierData;managementFeeMemory?:ManagementFeeData;supplierCostMemory?:SupplierCostsData;additionalCostSubtotal?:AdditionalCostsData;distributorSubtotal?:DistributorSubtotalData;taxMemory?:TaxMemoryData;supplyReference?:SupplyReferenceData;costLedger?:MonthlyCostLedgerData;tariffPreview?:TariffPreviewData;costs?:CostSummary;measurements?:{status:string;draftCount:number;validatedCount:number;validatedVersion:{id:string;version:number;revision:number;validatedAt:string;source:string;measurements:Record<string,string|null>}|null};mode:string;ruleVersion:string;checkedAt:string;month:string;period:Period;unit:{id:string;name:string};counts:{blockers:number;reviews:number;approvedParameters:number;draftParameters:number};findings:{code:string;section:string;severity:string;message:string}[];catalog:({key:string;label:string;scenario:string;kind:string;timeBand:string;versions:{id:string;revision:number;start:string;end:string;source:string}[]}&Coverage)[];suppliers:{id:string;number:string;start:string;end:string;priceSource:string;priceCoverage:Coverage}[];notChecked:string[]};
export default function CalculationPreparation({customerId,units,initialContext,onCorrect}:{customerId:string;units:Unit[];initialContext?:CorrectionContext;onCorrect?:(context:CorrectionContext)=>void}){
 const [unitId,setUnit]=useState(initialContext?.unitId||''),[monthNumber,setMonthNumber]=useState(initialContext?.month.slice(5,7)||''),[year,setYear]=useState(initialContext?.month.slice(0,4)||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);const version=useRef(0);
 useEffect(()=>()=>{version.current++;},[]);
 function change(action:()=>void){version.current++;setResult(null);setError('');action();}
 async function inspect(e:FormEvent){e.preventDefault();const month=year+'-'+monthNumber;if(!unitId||!/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(month)){setError('Selecione a unidade, o mês e um ano entre 2000 e 2199.');return;}const request=++version.current;setBusy(true);setError('');setResult(null);try{const r=await apiRequest<Result>('/api/v1/calculation-preparation?consumerUnitId='+encodeURIComponent(unitId)+'&month='+encodeURIComponent(month));if(version.current===request)setResult(r);}catch(e){if(version.current===request)setError(e instanceof Error?e.message:'Não foi possível consultar a competência.');}finally{if(version.current===request)setBusy(false);}}
 const available=units.filter(u=>!customerId||u.customer_id===customerId);
 function showCoverage(c:Coverage){return <>{c.gaps.length?<ul>{c.gaps.map(g=><li key={g.start}>Sem cobertura de {date(g.start)} a {date(g.end)}</li>)}</ul>:<p>Vigências cobrem o período consultado.</p>}{c.overlap?<p>Há vigências simultâneas. Revise as fontes.</p>:null}</>;}
 return <section className='backoffice-page ee-preparation'><header className='ee-preparation-title'><span>INTELIGÊNCIA ENERGÉTICA</span><h2>Comparativo ACL × ACR</h2><p>Escolha a unidade e a competência para explorar os componentes calculados e revisar o que falta para a apuração.</p></header>
 <Card title='Unidade e competência'><form onSubmit={inspect} className='organizations-create__form'><fieldset disabled={busy}><div className='organizations-create__form'><label>Unidade para conferência<select className='ds-input' required value={unitId} onChange={e=>change(()=>setUnit(e.target.value))}><option value=''>Selecione</option>{available.map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label><label>Mês da competência<select className='ds-input' required value={monthNumber} onChange={e=>change(()=>setMonthNumber(e.target.value))}><option value=''>Selecione</option>{['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'].map((name,i)=><option key={name} value={String(i+1).padStart(2,'0')}>{name}</option>)}</select></label><label>Ano da competência<select className='ds-input' required autoComplete='off' value={year} onChange={e=>change(()=>setYear(e.target.value))}><option value=''>Selecione o ano</option>{Array.from({length:200},(_,i)=>String(2000+i)).map(y=><option key={y} value={y}>{y}</option>)}</select></label><Button type='submit'>{busy?'Conferindo competência...':'Conferir competência'}</Button></div></fieldset></form></Card>
 {error?<Alert variant='error'>{error}</Alert>:null}
 {result?<><ScenarioComparison key={result.unit.id+result.month+result.checkedAt} data={result} customerId={units.find(u=>u.id===result.unit.id)?.customer_id} onCorrect={onCorrect}/><details className='ee-preparation-detail'><summary>Conferência cadastral e dados de origem</summary><Card title={'Conferência de '+result.unit.name+' · '+result.month}><p>De {date(result.period.start)} a {date(result.period.end)} · consultado em {new Date(result.checkedAt).toLocaleString('pt-BR')}</p><p><strong>{result.counts.blockers} pendência(s) de cadastro</strong> · {result.counts.reviews} ponto(s) de revisão · {result.counts.approvedParameters} parâmetro(s) aprovado(s) no mês.</p><Alert>Diagnóstico cadastral. Mesmo sem pendências nesta consulta, faturas, medições, custos e regras de apuração ainda precisam ser conferidos antes de gerar ou publicar resultados.</Alert></Card>
 <Card title='Medições da competência'>{result.measurements?<><p><strong>{{MISSING:'Medições não cadastradas',DRAFT_PENDING:'Rascunho aguardando validação',VALIDATED:'Versão validada disponível',INVALID:'Medições exigem revisão'}[result.measurements.status]||'Revisão necessária'}</strong></p><p>{result.measurements.draftCount} rascunho(s) · {result.measurements.validatedCount} versão(ões) validada(s).</p>{result.measurements.validatedVersion?<><p>Última versão validada: {result.measurements.validatedVersion.version} · revisão {result.measurements.validatedVersion.revision} · {new Date(result.measurements.validatedVersion.validatedAt).toLocaleString('pt-BR')}</p><p>Fonte: {result.measurements.validatedVersion.source}</p><dl>{Object.entries({consumptionTotal:'Consumo total (kWh)',consumptionPeak:'Consumo de ponta (kWh)',consumptionOffPeak:'Consumo fora ponta (kWh)',demandSingle:'Demanda medida única (kW)',demandPeak:'Demanda medida de ponta (kW)',demandOffPeak:'Demanda medida fora ponta (kW)',reactiveTotal:'Energia reativa excedente (kVArh)'}).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{result.measurements?.validatedVersion?.measurements[key]??'Não informado'}</dd></div>)}</dl></>:null}<p>Use a aba Dados mensais para preencher ou corrigir as medições. Uma versão validada ainda pode apresentar pendências para a apuração, listadas abaixo.</p></>:<p>A conferência de medições ainda não está disponível nesta resposta. Atualize a consulta após a publicação da API.</p>}</Card>
 <Card title='Custos e créditos da competência'>{result.costs?<><p><strong>{{MISSING:'Custos ainda não revisados',DRAFT_PENDING:'Rascunho de custos aguardando validação',VALIDATED:'Versão validada de custos disponível',NO_COSTS_DECLARED:'Ausência de custos adicionais declarada e validada',INVALID:'Custos exigem revisão'}[result.costs.status]||'Revisão necessária'}</strong></p><p>{result.costs.draftCount} rascunho(s) · {result.costs.validatedCount} versão(ões) validada(s).</p>{result.costs.validatedVersion?<><p>Última versão validada: {result.costs.validatedVersion.version} · revisão {result.costs.validatedVersion.revision} · {new Date(result.costs.validatedVersion.validatedAt).toLocaleString('pt-BR')}</p><p>Fonte da revisão: {result.costs.validatedVersion.source}</p>{result.costs.validatedVersion.costs.noCosts?<p>Foi declarada ausência de custos e créditos adicionais para esta unidade e competência.</p>:<details><summary>Ver lançamentos validados e fontes</summary>{result.costs.validatedVersion.costs.items.map(i=><article className='ds-card' key={i.id}><h3>{i.label}</h3><p>{i.scenario} · {i.effect==='CREDIT'?'Crédito':'Custo'} · R$ {i.amount}</p><p>{{SUPPLIER_INVOICE:'Fatura do fornecedor',SUPPLIER_EXTRA_ENERGY:'Compra extra de energia',CCEE:'CCEE',EXPOSURE:'Exposição / curto prazo',CHARGE:'Encargos',OTHER:'Outros ajustes'}[i.category]||i.category} · {{INCLUDED:'Tributos incluídos',EXCLUDED:'Tributos excluídos',NOT_APPLICABLE:'Tributos não aplicáveis',UNSPECIFIED:'Classificação tributária pendente'}[i.taxTreatment]||i.taxTreatment}</p><p>Fonte: {i.source}</p></article>)}</details>}</>:null}<p>Preencha ou corrija na aba Custos mensais. Esta conferência não soma os lançamentos ao custo ACL/ACR nem calcula tributos ou economia.</p></>:<p>A conferência de custos ainda não está disponível nesta resposta. Atualize após a publicação da API.</p>}</Card>
 </details><details className='ee-preparation-detail'><summary>Memórias de cálculo, fórmulas e fontes</summary>
 <MonthlyCostLedger data={result.costLedger}/>
 {!result.contractSupplierCost?<SupplyReference data={result.supplyReference}/>:null}
 <TariffPreview data={result.tariffPreview}/>
 <TaxMemory data={result.taxMemory} onCorrect={onCorrect?id=>{const owner=units.find(u=>u.id===result.unit.id)?.customer_id;if(owner)onCorrect({customerId:owner,unitId:result.unit.id,month:result.month,tab:"parameters",kind:"TAX",recordId:id,message:"Revise a configuração e as referências indicadas na memória tributária."});}:undefined}/>
 </details><div id='preparation-findings' className='ee-preparation-findings'><Card title='Pendências e pontos de revisão'>{result.findings.length?<ul>{result.findings.map((f,i)=><li key={f.code+'-'+i} style={{marginBottom:12}}>{onCorrect&&correctionTarget(f,{customerId,unitId:result.unit.id,month:result.month})?<button type='button' className='preparation-finding-link' onClick={()=>{const owner=units.find(u=>u.id===result.unit.id)?.customer_id;if(!owner)return;const target=correctionTarget(f,{customerId:owner,unitId:result.unit.id,month:result.month,message:f.message});if(target)onCorrect(target);}}><strong>{f.section} · {f.severity==='BLOCKER'?'Pendência':'Revisão'}:</strong> {f.message} <span aria-hidden='true'>→</span></button>:<><strong>{f.section} · {f.severity==='BLOCKER'?'Pendência':'Revisão'}:</strong> {f.message}</>}</li>)}</ul>:<p>Sem pendências nas verificações cadastrais executadas.</p>}</Card>
 </div><details className='ee-preparation-detail'><summary>Vigências, contratos e verificações complementares</summary><Card title='Cobertura dos parâmetros aprovados'>{result.catalog.length?result.catalog.map(c=><details key={c.key} className='ds-card'><summary>{c.label} · {c.scenario} · {{ALL:'Todos os postos',PEAK:'Ponta',OFF_PEAK:'Fora ponta'}[c.timeBand]||c.timeBand}</summary>{showCoverage(c)}{c.versions.map(v=><p key={v.id}>Revisão {v.revision} · {date(v.start)} a {date(v.end)} · Fonte: {v.source}</p>)}</details>):<p>Nenhum parâmetro aprovado com vigência na competência.</p>}</Card>
 <Card title='Contratos de fornecimento no período'>{result.suppliers.length?result.suppliers.map(s=><article className='ds-card' key={s.id}><h3>{s.number}</h3><p>{date(s.start)} a {date(s.end)} · Fonte dos preços: {s.priceSource==='HISTORY'?'histórico por vigência':'tabela anual'}</p>{showCoverage(s.priceCoverage)}</article>):<p>Nenhum contrato de compra ativo/aprovado no período.</p>}</Card>
 <Card title='Ainda não verificado nesta etapa'><ul>{result.notChecked.map(item=><li key={item}>{item}</li>)}</ul><p>Esta consulta não afirma ausência desses dados; eles ainda não estão integrados ao diagnóstico. Versão das verificações: {result.ruleVersion}.</p></Card></details></>:null}</section>;
}
