'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {Unit,PERM,date} from './types';
import TaxIncidenceEditor from './TaxIncidenceEditor';
import {incidenceProblem,incidenceText} from './tax-incidence';
import {CorrectionContext} from './preparation-navigation';
type BaseItem={parameterId:string;revision:number;operation:string};
type Basis={interaction?:'INDEPENDENT';version:1;items:BaseItem[]};
type Check={id:string;revision:number;issues:string[]};
type Draft={taxBasis:Basis|null;embeddedTaxCodes:string[];consumerUnitId:string;kind:string;componentCode:string;label:string;scenario:string;timeBand:string;measure:string;amount:string|null;treatment:string;includedTaxes:string;baseRule:string;direction:string;source:string;notes:string;startDate:string;endDate:string};
type Row={tax_basis?:Basis|null;embedded_tax_codes?:string[];id:string;customer_id:string;consumer_unit_id:string;kind:string;component_code:string;label:string;scenario:string;time_band:string;measure:string;amount_text:string|null;treatment:string;included_taxes:string;base_rule:string;direction:string;source:string;notes:string;start_date:string;end_date:string;status:string;revision:number;approved_at?:string;retirement_reason?:string;unit_context:Record<string,unknown>};
type Audit={id:string;revision:number;action:string;recorded_at:string;snapshot:Row};
const kinds:Record<string,string>={TARIFF:'Tarifas',TAX:'Tributos',COST:'Custos e créditos'};
const components:Record<string,Record<string,string>>={TARIFF:{TE:'Energia (TE)',TUSD_ENERGY:'TUSD — energia',TUSD_DEMAND:'TUSD — demanda',REACTIVE:'Energia reativa',OTHER:'Outra rubrica'},TAX:{ICMS:'ICMS',PIS:'PIS',COFINS:'Cofins',IOF:'IOF',OTHER:'Outro tributo'},COST:{SUPPLIER:'Fornecedor',CCEE:'CCEE',CHARGES:'Encargos',INTERMEDIATION:'Intermediação',GUARANTEE:'Garantia / financiamento',OTHER:'Outro custo'}};
const measures:Record<string,string>={BRL_KWH:'R$/kWh',BRL_MWH:'R$/MWh',BRL_KW:'R$/kW',BRL_KVARH:'R$/kVArh',BRL_MONTH:'R$/mês',PERCENT:'%'};
const treatments:Record<string,string>={NET:'Sem tributos embutidos',GROSS:'Com tributos embutidos',INSIDE:'Por dentro',OUTSIDE:'Por fora',INCLUDED:'Já incluído no valor de origem',EXEMPT:'Isento',NOT_APPLICABLE:'Não aplicável'};
const statuses:Record<string,string>={DRAFT:'Rascunho',APPROVED:'Aprovado',RETIRED:'Retirado de uso'};
const bands:Record<string,string>={ALL:'Todos / sem distinção',PEAK:'Ponta',OFF_PEAK:'Fora ponta'};
const seed=():Draft=>({taxBasis:null,embeddedTaxCodes:[],consumerUnitId:'',kind:'TARIFF',componentCode:'TE',label:'Energia (TE)',scenario:'ACR',timeBand:'ALL',measure:'BRL_KWH',amount:'',treatment:'NET',includedTaxes:'',baseRule:'',direction:'DEBIT',source:'',notes:'',startDate:'',endDate:''});
const fromRow=(r:Row):Draft=>({taxBasis:r.tax_basis??null,embeddedTaxCodes:r.embedded_tax_codes??[],consumerUnitId:r.consumer_unit_id,kind:r.kind,componentCode:r.component_code,label:r.label,scenario:r.scenario,timeBand:r.time_band,measure:r.measure,amount:r.amount_text,treatment:r.treatment,includedTaxes:r.included_taxes,baseRule:r.base_rule,direction:r.direction,source:r.source,notes:r.notes,startDate:r.start_date.slice(0,10),endDate:r.end_date.slice(0,10)});
export default function CalculationParameters({customerId,units,onDirty,initialContext}:{initialContext?:CorrectionContext;customerId:string;units:Unit[];onDirty:(dirty:boolean)=>void}){
 const {hasPermission}=useAuth(),create=hasPermission(PERM.create),update=hasPermission(PERM.update);
 const [showEditor,setShowEditor]=useState(!initialContext);
 const [contextFilter,setContextFilter]=useState(!!initialContext);
 const [checks,setChecks]=useState<Check[]|null>(null),[checking,setChecking]=useState(false);
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [draft,setDraft]=useState<Draft>(seed),[editing,setEditing]=useState<Row|null>(null),[dirty,setDirty]=useState(false),[pending,setPending]=useState<(()=>void)|null>(null);
 const [kindFilter,setKindFilter]=useState(initialContext?.kind||''),[unitFilter,setUnitFilter]=useState(initialContext?.unitId||''),[statusFilter,setStatusFilter]=useState(initialContext?.drafts?'DRAFT':''),[confirm,setConfirm]=useState<{row:Row;action:'approve'|'retire'}|null>(null),[reason,setReason]=useState(''),[history,setHistory]=useState<{id:string;events:Audit[]}|null>(null);const working=useRef(false);
 useEffect(()=>{let cancelled=false;apiRequest<Row[]>('/api/v1/calculation-parameters').then(r=>{if(!cancelled){setRows(r);setFailed(false);}}).catch(e=>{if(!cancelled){setError(e.message);setFailed(true);}}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
 function mark(){setChecks(null);setDirty(true);onDirty(true);}function patch(p:Partial<Draft>){setDraft(d=>({...d,...p}));mark();}
 function reset(){setChecks(null);setDraft(seed());setEditing(null);setDirty(false);onDirty(false);setPending(null);}
 function choose(action:()=>void){if(dirty)setPending(()=>action);else action();}
 async function reload(){setChecks(null);setLoading(true);setError('');try{setRows(await apiRequest<Row[]>('/api/v1/calculation-parameters'));setFailed(false);}catch(e){setError(e instanceof Error?e.message:'Falha na consulta.');setFailed(true);}finally{setLoading(false);}}
 function kind(value:string){patch({taxBasis:null,embeddedTaxCodes:[],kind:value,componentCode:value==='TAX'?'ICMS':value==='COST'?'CCEE':'TE',label:value==='TAX'?'ICMS':value==='COST'?'CCEE':'Energia (TE)',measure:value==='TAX'?'PERCENT':value==='COST'?'BRL_MONTH':'BRL_KWH',treatment:value==='TAX'?'INSIDE':'NET',amount:'',timeBand:'ALL',direction:'DEBIT',includedTaxes:'',baseRule:''});}
 async function save(e:FormEvent){e.preventDefault();if(working.current)return;setError('');setMessage('');
 const baseProblem=draft.kind==='TAX'?incidenceProblem(draft.baseRule,draft.componentCode):null;if(baseProblem){setError(baseProblem);return;}
 if(draft.endDate<draft.startDate){setError('Revise as datas da vigência.');return;}if(!units.some(u=>u.id===draft.consumerUnitId&&u.customer_id===customerId)){setError('Selecione uma unidade deste cliente.');return;}
 const body={...draft,taxBasis:tax&&!['EXEMPT','NOT_APPLICABLE'].includes(draft.treatment)?draft.taxBasis:null,embeddedTaxCodes:draft.treatment==='GROSS'?draft.embeddedTaxCodes:[],amount:['EXEMPT','NOT_APPLICABLE'].includes(draft.treatment)?null:draft.amount,includedTaxes:draft.treatment==='GROSS'?draft.includedTaxes:''};
 working.current=true;setBusy(true);try{const row=await apiRequest<Row>('/api/v1/calculation-parameters'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:editing?{...body,revision:editing.revision}:body});setRows(old=>[row,...old.filter(r=>r.id!==row.id)]);reset();setMessage('Rascunho salvo. Confira fonte, vigência e valores antes de aprovar.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{working.current=false;setBusy(false);}}
 async function transition(){if(!confirm||working.current)return;working.current=true;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Row>('/api/v1/calculation-parameters/'+confirm.row.id+'/'+confirm.action,{method:'POST',body:{revision:confirm.row.revision,...(confirm.action==='retire'?{reason}: {})}});setRows(old=>old.map(r=>r.id===row.id?row:r));setConfirm(null);setHistory(null);setChecks(null);if(editing?.id===row.id)reset();setMessage(row.status==='APPROVED'?'Parâmetro aprovado e preservado no histórico.':'Parâmetro retirado de uso. O histórico foi preservado.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar.');}finally{working.current=false;setBusy(false);}}
 async function audit(row:Row){setError('');try{setHistory({id:row.id,events:await apiRequest<Audit[]>('/api/v1/calculation-parameters/'+row.id+'/events')});}catch(e){setError(e instanceof Error?e.message:'Não foi possível consultar o histórico.');}}
 async function inspect(){setChecking(true);setError('');try{setChecks(await apiRequest<Check[]>('/api/v1/calculation-parameters/checks'));}catch(e){setError(e instanceof Error?e.message:'Falha na verificação.');}finally{setChecking(false);}}
 function basisItem(r:Row,operation:string){patch({taxBasis:{...draft.taxBasis,version:1,items:[...(draft.taxBasis?.items||[]).filter(i=>i.parameterId!==r.id),...(operation?[{parameterId:r.id,revision:r.revision,operation}]:[])]}});}
 const basisOptions=rows.filter(r=>r.consumer_unit_id===draft.consumerUnitId&&r.scenario===draft.scenario&&r.kind!=='TAX'&&r.status==='APPROVED');
 const embeddedOptions=Array.from(new Set(['ICMS','PIS','COFINS','IOF',...draft.embeddedTaxCodes,...rows.filter(r=>r.kind==='TAX'&&r.consumer_unit_id===draft.consumerUnitId).map(r=>r.component_code)]));
 function basisDetails(r:Row){return <>{r.tax_basis?.interaction==='INDEPENDENT'?<p>Interação: cálculo independente, sem incidência entre tributos.</p>:r.kind==='TAX'?<p>Interação entre tributos: não definida.</p>:null}{r.embedded_tax_codes?.length?<p>Tributos embutidos: {r.embedded_tax_codes.join(', ')}</p>:null}{r.tax_basis?.items.map(i=><p key={i.parameterId}>{i.operation==='INCLUDE'?'Incluída':'Excluída'}: {rows.find(x=>x.id===i.parameterId)?.label||'Rubrica indisponível'} · revisão {i.revision}</p>)}</>;}
 const available=units.filter(u=>!customerId||u.customer_id===customerId),unit=units.find(u=>u.id===draft.consumerUnitId),tax=draft.kind==='TAX';
 const filtered=rows.filter(r=>(!contextFilter||!initialContext||((!initialContext.scenario||r.scenario===initialContext.scenario)&&(!initialContext.component||r.component_code===initialContext.component)&&(!initialContext.recordId||r.id===initialContext.recordId)))&&(!customerId||r.customer_id===customerId)&&(!kindFilter||r.kind===kindFilter)&&(!unitFilter||r.consumer_unit_id===unitFilter)&&(!statusFilter||r.status===statusFilter)).sort((a,b)=>b.start_date.localeCompare(a.start_date));
 return <section className="backoffice-page"><h2>Parâmetros de cálculo</h2><p>Cadastre tarifas, tributos e custos por unidade, cenário e vigência. Esta etapa prepara os dados; a apuração ACL × ACR ainda não está disponível.</p>
 {contextFilter?<Alert>Exibindo os parâmetros relacionados à pendência. Confira se as vigências cobrem {initialContext?.month} e aprove os rascunhos adequados.<Button variant='secondary' onClick={()=>{setContextFilter(false);setKindFilter('');setUnitFilter('');setStatusFilter('');}}>Mostrar todos os parâmetros deste cliente</Button></Alert>:null}
 {error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 <Button variant="secondary" disabled={busy||loading} onClick={()=>void reload()}>Atualizar parâmetros</Button><Button variant='secondary' disabled={busy||loading||checking||dirty||failed} onClick={()=>void inspect()}>{checking?'Verificando...':'Verificar cadastro'}</Button>{checks?<p role='status'>Verificação cadastral concluída. As pendências aparecem nos parâmetros abaixo. Esta verificação não substitui os dados das faturas nem calcula o resultado ACL × ACR.</p>:null}
 {pending?<div role="alert" className="ds-card"><p>Existem campos não salvos neste formulário.</p><Button type="button" onClick={()=>{setDirty(false);onDirty(false);pending();setPending(null);}}>Descartar formulário e continuar</Button><Button variant="secondary" onClick={()=>setPending(null)}>Continuar preenchendo</Button></div>:null}
 {initialContext&&create&&customerId&&!showEditor&&!editing?<Button disabled={loading||failed} onClick={()=>{setShowEditor(true);setDraft(d=>{const k=initialContext.kind||d.kind,c=initialContext.component||(k==='TAX'?'ICMS':k==='TARIFF'?'TE':'CCEE');return {...d,consumerUnitId:initialContext.unitId,scenario:initialContext.scenario||d.scenario,kind:k,componentCode:c,label:components[k]?.[c]||c,measure:k==='TAX'?'PERCENT':k==='TARIFF'?'BRL_KWH':'BRL_MONTH',treatment:k==='TAX'?'INSIDE':'NET'};});}}>Cadastrar parâmetro faltante</Button>:null}
 {customerId&&(editing||(create&&showEditor))&&!loading&&!failed?<Card title={editing?'Editar parâmetro em rascunho':'Novo parâmetro'}><form onSubmit={save} className="organizations-create__form"><fieldset disabled={busy}><div className="organizations-create__form">
 <label>Unidade do parâmetro<select className="ds-input" required value={draft.consumerUnitId} disabled={!!editing} onChange={e=>patch({consumerUnitId:e.target.value,taxBasis:null})}><option value="">Selecione</option>{available.map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label>
 {unit?<p>{unit.distributor} · Grupo {unit.tariff_group} · {unit.tariff_subgroup||'Subgrupo não informado'} · Mercado Livre: {unit.free_market===true?'Sim':unit.free_market===false?'Não':'Não informado'}</p>:null}
 <label>Categoria do parâmetro<select className="ds-input" value={draft.kind} onChange={e=>kind(e.target.value)}>{Object.entries(kinds).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Rubrica<select className="ds-input" value={Object.hasOwn(components[draft.kind],draft.componentCode)?draft.componentCode:'OTHER'} onChange={e=>patch({componentCode:e.target.value==='OTHER'?'OTHER_':e.target.value,label:e.target.value==='OTHER'?'':components[draft.kind][e.target.value]})}>{Object.entries(components[draft.kind]).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 {draft.componentCode.startsWith('OTHER_')?<Input label="Identificador da rubrica adicional" required maxLength={40} pattern="OTHER_[A-Z0-9_]+" value={draft.componentCode} onChange={e=>patch({componentCode:e.target.value.toUpperCase()})}/>:null}
 <Input label="Descrição do parâmetro" required maxLength={200} value={draft.label} onChange={e=>patch({label:e.target.value})}/>
 <label>Cenário<select className="ds-input" value={draft.scenario} onChange={e=>patch({scenario:e.target.value,taxBasis:null})}><option value="ACR">ACR — mercado cativo de referência</option><option value="ACL">ACL — mercado livre</option></select></label>
 {!tax?<><label>Posto tarifário<select className="ds-input" value={draft.timeBand} onChange={e=>patch({timeBand:e.target.value})}>{Object.entries(bands).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Unidade de medida<select className="ds-input" value={draft.measure} onChange={e=>patch({measure:e.target.value})}>{Object.entries(measures).filter(([v])=>v!=='PERCENT'&&(draft.kind==='COST'||v!=='BRL_MONTH')).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></>:null}
 <label>Tratamento tributário<select className="ds-input" value={draft.treatment} onChange={e=>patch({treatment:e.target.value,taxBasis:null,embeddedTaxCodes:[],amount:['EXEMPT','NOT_APPLICABLE'].includes(e.target.value)?null:(draft.amount||''),includedTaxes:''})}>{Object.entries(treatments).filter(([v])=>tax?!['NET','GROSS'].includes(v):['NET','GROSS'].includes(v)).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 {!['EXEMPT','NOT_APPLICABLE'].includes(draft.treatment)?<Input label={tax?'Alíquota (%)':'Valor ('+measures[draft.measure]+')'} type="number" min="0" max={tax?(draft.treatment==='INSIDE'?'99.999999':'100'):'999999999999.999999'} step="0.000001" required value={draft.amount??''} onChange={e=>patch({amount:e.target.value})}/>:<p>A alíquota fica não aplicável; ela não será registrada como zero.</p>}
 {draft.treatment==='GROSS'?<fieldset><legend>Tributos embutidos no valor</legend>{embeddedOptions.map(code=><label key={code}><input type='checkbox' checked={draft.embeddedTaxCodes.includes(code)} onChange={e=>patch({embeddedTaxCodes:e.target.checked?[...draft.embeddedTaxCodes,code]:draft.embeddedTaxCodes.filter(c=>c!==code)})}/>{code} </label>)}</fieldset>:null}
 {draft.treatment==='GROSS'?<Input label="Quais tributos estão incluídos no valor?" required maxLength={500} value={draft.includedTaxes} onChange={e=>patch({includedTaxes:e.target.value})}/>:null}
 {tax?<TaxIncidenceEditor key={(editing?.id||'new')+draft.componentCode} tax={draft.componentCode} value={draft.baseRule} onChange={baseRule=>patch({baseRule})}/>:draft.kind==='COST'?<label>Regra de aplicação do custo ou crédito<textarea className='ds-input' required maxLength={4096} value={draft.baseRule} onChange={e=>patch({baseRule:e.target.value})}/></label>:null}
 {tax&&!['EXEMPT','NOT_APPLICABLE'].includes(draft.treatment)?<fieldset><legend>Rubricas da base tributária</legend><p>Selecione parâmetros aprovados desta unidade e cenário. A vigência de cada rubrica deve cobrir todo o período do tributo. Excluir registra que a rubrica não integra a base; não gera uma segunda dedução. Créditos incluídos mantêm sua natureza de dedução.</p>{basisOptions.length===0?<p>Aprove primeiro as tarifas e os custos que compõem esta base.</p>:basisOptions.map(r=><label key={r.id}>{r.label} · {bands[r.time_band]} · {r.direction==='CREDIT'?'Crédito':'Débito'} · {treatments[r.treatment]} · {date(r.start_date)} a {date(r.end_date)}<select className='ds-input' value={draft.taxBasis?.items.find(i=>i.parameterId===r.id)?.operation||''} onChange={e=>basisItem(r,e.target.value)}><option value=''>Não selecionar</option><option value='INCLUDE'>Incluir na base</option><option value='EXCLUDE'>Excluir expressamente da base</option></select></label>)}{draft.taxBasis?.items.filter(i=>!basisOptions.some(r=>r.id===i.parameterId)).map(i=><p key={i.parameterId}>Referência indisponível · revisão {i.revision} <Button type='button' variant='secondary' onClick={()=>patch({taxBasis:{...draft.taxBasis,version:1,items:draft.taxBasis!.items.filter(x=>x.parameterId!==i.parameterId)}})}>Remover referência indisponível</Button></p>)}<p>Para tributos por dentro ou por fora, utilize rubricas sem impostos. Para tributo já incluído, selecione valores com esse tributo declarado como embutido.</p></fieldset>:null}
 {tax&&['INSIDE','OUTSIDE'].includes(draft.treatment)?<fieldset><legend>Interação entre tributos</legend><label>Regra para esta unidade e vigência<select className="ds-input" value={draft.taxBasis?.interaction||''} onChange={e=>patch({taxBasis:{version:1,items:draft.taxBasis?.items||[],...(e.target.value?{interaction:'INDEPENDENT' as const}:{})}})}><option value="">Não definida / outra composição</option><option value="INDEPENDENT">Cálculo independente — sem incidência entre tributos</option></select></label><p>Selecione somente quando cada tributo utiliza suas próprias rubricas, sem incluir valores de outros tributos. Por dentro continua considerando a própria alíquota. Não representa um denominador conjunto de ICMS, PIS e Cofins. Registre a fundamentação no campo Fonte.</p><p>Se houver base compartilhada, todos os tributos envolvidos precisam dessa declaração aprovada. Outras composições permanecem pendentes na conferência.</p></fieldset>:null}
 {tax?<p>Informe a regra e a fonte aplicáveis ao período. Para IOF, descreva a operação que justifica a incidência ou a não aplicação. O tratamento por dentro será utilizado pelo motor após sua implantação e validação.</p>:null}
 {draft.kind==='COST'?<><label>Natureza<select className="ds-input" value={draft.direction} onChange={e=>patch({direction:e.target.value})}><option value="DEBIT">Custo / débito</option><option value="CREDIT">Crédito / dedução</option></select></label><p>Registre valores desta unidade. Honorários de gestão ficam no contrato próprio; evite cadastrar novamente o mesmo custo.</p></>:null}
 <Input label="Vigência inicial do parâmetro" type="date" required value={draft.startDate} onChange={e=>patch({startDate:e.target.value})}/><Input label="Vigência final do parâmetro" type="date" required value={draft.endDate} onChange={e=>patch({endDate:e.target.value})}/>
 <label>Fonte ou documento de referência<textarea className="ds-input" required maxLength={2000} value={draft.source} onChange={e=>patch({source:e.target.value})}/></label>
 <label>Observações do parâmetro<textarea className="ds-input" maxLength={4096} value={draft.notes} onChange={e=>patch({notes:e.target.value})}/></label>
 <Button type="submit">{busy?'Salvando...':'Salvar parâmetro em rascunho'}</Button><Button type="button" variant="secondary" onClick={()=>choose(reset)}>Limpar formulário</Button>
 </div></fieldset></form></Card>:!customerId?<p>Selecione um cliente para cadastrar parâmetros de suas unidades.</p>:null}
 <Card title="Parâmetros cadastrados"><div className="organizations-create__form"><label>Filtrar categoria<select className="ds-input" value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="">Todas</option>{Object.entries(kinds).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Filtrar unidade<select className="ds-input" value={unitFilter} onChange={e=>setUnitFilter(e.target.value)}><option value="">Todas</option>{available.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Filtrar situação<select className="ds-input" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todas</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
 {loading?<p>Carregando parâmetros...</p>:filtered.length===0?<p>{failed?'Consulta indisponível.':'Nenhum parâmetro cadastrado para este filtro.'}</p>:filtered.map(r=><article className="ds-card" key={r.id}><h3>{r.label} · {statuses[r.status]}</h3><p>{units.find(u=>u.id===r.consumer_unit_id)?.name||'Unidade vinculada'} · {r.scenario} · {kinds[r.kind]} · {bands[r.time_band]}</p><p>{r.amount_text===null?'Alíquota não aplicável':r.amount_text.replace('.',',')+' '+measures[r.measure]} · {treatments[r.treatment]}{r.direction==='CREDIT'?' · Crédito':''}</p><p>{date(r.start_date)} a {date(r.end_date)}</p><details><summary>Fonte, regras e contexto</summary><p>{r.source}</p><p style={{whiteSpace:'pre-wrap'}}>{incidenceText(r.base_rule)}</p><p>{r.included_taxes}</p>{basisDetails(r)}<p>{r.notes}</p><p>Distribuidora: {String(r.unit_context.distributor||'Não informada')} · Grupo: {String(r.unit_context.tariff_group||'Não informado')} · UF: {String(r.unit_context.state||'Não informada')}</p>{r.retirement_reason?<p>Retirada: {r.retirement_reason}</p>:null}</details>
 {checks?.filter(c=>c.id===r.id&&c.revision===r.revision).map(c=><div key={c.id}><h4>Verificação cadastral</h4>{c.issues.length?<ul>{c.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p>Sem pendências nas referências deste parâmetro. A apuração ainda depende dos dados da competência.</p>}</div>)}
 {r.status==='DRAFT'&&update&&customerId?<Button variant="secondary" disabled={busy} onClick={()=>choose(()=>{setDraft(fromRow(r));setEditing(r);setDirty(false);onDirty(false);setConfirm(null);})}>Editar rascunho</Button>:null}
 {create&&customerId?<Button variant="secondary" disabled={busy} onClick={()=>choose(()=>{setShowEditor(true);setDraft({...fromRow(r),startDate:'',endDate:''});setEditing(null);mark();setConfirm(null);})}>Nova vigência</Button>:null}
 {update&&r.status!=='RETIRED'?<>{r.status==='DRAFT'?<Button disabled={busy||dirty} onClick={()=>{setConfirm({row:r,action:'approve'});setReason('');}}>Revisar e aprovar</Button>:null}<Button variant="secondary" disabled={busy||dirty} onClick={()=>{setConfirm({row:r,action:'retire'});setReason('');}}>Retirar de uso</Button></>:null}
 <Button variant="secondary" disabled={busy} onClick={()=>void audit(r)}>Ver histórico</Button>
 {confirm?.row.id===r.id?<div className="ds-card"><p>{confirm.action==='approve'?'Confirme que revisou o valor, a fonte, a base e a vigência. Após aprovação, o conteúdo será preservado.':'A retirada preserva o histórico e impede o uso em novas apurações. Ela não modifica resultados já registrados.'}</p>{confirm.action==='retire'?<label>Justificativa da retirada<textarea className="ds-input" maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>:null}<Button disabled={busy||(confirm.action==='retire'&&!reason.trim())} onClick={()=>void transition()}>Confirmar {confirm.action==='approve'?'aprovação':'retirada'}</Button><Button variant="secondary" disabled={busy} onClick={()=>setConfirm(null)}>Cancelar</Button></div>:null}
 {history?.id===r.id?<details open><summary>Histórico de revisões</summary>{[...history.events].sort((a,b)=>b.revision-a.revision).map(e=><details key={e.id}><summary>{new Date(e.recorded_at).toLocaleString('pt-BR')} · {{CREATED:'Criado',UPDATED:'Atualizado',APPROVED:'Aprovado',RETIRED:'Retirado de uso'}[e.action]||e.action} · revisão {e.revision} · {e.snapshot.amount_text??'Não aplicável'} · {date(e.snapshot.start_date)} a {date(e.snapshot.end_date)}</summary><p>{e.snapshot.label} · {treatments[e.snapshot.treatment]}</p><p>Fonte: {e.snapshot.source}</p><p style={{whiteSpace:'pre-wrap'}}>{incidenceText(e.snapshot.base_rule)}</p><p>{e.snapshot.included_taxes}</p>{basisDetails(e.snapshot)}<p>{e.snapshot.notes}</p><p>{e.snapshot.retirement_reason}</p></details>)}</details>:null}</article>)}
 </Card></section>;
}
