'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {Unit,date} from './types';
type Period={start:string;end:string};
type Coverage={gaps:Period[];overlap:boolean;segments:number};
type Result={mode:string;ruleVersion:string;checkedAt:string;month:string;period:Period;unit:{id:string;name:string};counts:{blockers:number;reviews:number;approvedParameters:number;draftParameters:number};findings:{code:string;section:string;severity:string;message:string}[];catalog:({key:string;label:string;scenario:string;kind:string;timeBand:string;versions:{id:string;revision:number;start:string;end:string;source:string}[]}&Coverage)[];suppliers:{id:string;number:string;start:string;end:string;priceSource:string;priceCoverage:Coverage}[];notChecked:string[]};
export default function CalculationPreparation({customerId,units}:{customerId:string;units:Unit[]}){
 const [unitId,setUnit]=useState(''),[month,setMonth]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);const version=useRef(0);
 useEffect(()=>()=>{version.current++;},[]);
 function change(action:()=>void){version.current++;setResult(null);setError('');action();}
 async function inspect(e:FormEvent){e.preventDefault();const request=++version.current;setBusy(true);setError('');setResult(null);try{const r=await apiRequest<Result>('/api/v1/calculation-preparation?consumerUnitId='+encodeURIComponent(unitId)+'&month='+encodeURIComponent(month));if(version.current===request)setResult(r);}catch(e){if(version.current===request)setError(e instanceof Error?e.message:'Não foi possível consultar a competência.');}finally{if(version.current===request)setBusy(false);}}
 const available=units.filter(u=>!customerId||u.customer_id===customerId);
 function showCoverage(c:Coverage){return <>{c.gaps.length?<ul>{c.gaps.map(g=><li key={g.start}>Sem cobertura de {date(g.start)} a {date(g.end)}</li>)}</ul>:<p>Vigências cobrem o período consultado.</p>}{c.overlap?<p>Há vigências simultâneas. Revise as fontes.</p>:null}</>;}
 return <section className='backoffice-page'><h2>Preparar apuração mensal</h2><p>Confira os cadastros necessários por unidade e competência. A consulta não grava resultados nem calcula economia.</p>
 <Card title='Unidade e competência'><form onSubmit={inspect} className='organizations-create__form'><fieldset disabled={busy}><div className='organizations-create__form'><label>Unidade para conferência<select className='ds-input' required value={unitId} onChange={e=>change(()=>setUnit(e.target.value))}><option value=''>Selecione</option>{available.map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label><Input label='Competência para conferência' type='month' required min='2000-01' max='2199-12' value={month} onChange={e=>change(()=>setMonth(e.target.value))}/><Button type='submit'>{busy?'Conferindo competência...':'Conferir competência'}</Button></div></fieldset></form></Card>
 {error?<Alert variant='error'>{error}</Alert>:null}
 {result?<><Card title={'Conferência de '+result.unit.name+' · '+result.month}><p>De {date(result.period.start)} a {date(result.period.end)} · consultado em {new Date(result.checkedAt).toLocaleString('pt-BR')}</p><p><strong>{result.counts.blockers} pendência(s) de cadastro</strong> · {result.counts.reviews} ponto(s) de revisão · {result.counts.approvedParameters} parâmetro(s) aprovado(s) no mês.</p><Alert>Diagnóstico cadastral. Mesmo sem pendências nesta consulta, faturas, medições, custos e regras de apuração ainda precisam ser conferidos antes de gerar ou publicar resultados.</Alert></Card>
 <Card title='Pendências e pontos de revisão'>{result.findings.length?<ul>{result.findings.map((f,i)=><li key={f.code+'-'+i} style={{marginBottom:12}}><strong>{f.section} · {f.severity==='BLOCKER'?'Pendência':'Revisão'}:</strong> {f.message}</li>)}</ul>:<p>Sem pendências nas verificações cadastrais executadas.</p>}</Card>
 <Card title='Cobertura dos parâmetros aprovados'>{result.catalog.length?result.catalog.map(c=><details key={c.key} className='ds-card'><summary>{c.label} · {c.scenario} · {{ALL:'Todos os postos',PEAK:'Ponta',OFF_PEAK:'Fora ponta'}[c.timeBand]||c.timeBand}</summary>{showCoverage(c)}{c.versions.map(v=><p key={v.id}>Revisão {v.revision} · {date(v.start)} a {date(v.end)} · Fonte: {v.source}</p>)}</details>):<p>Nenhum parâmetro aprovado com vigência na competência.</p>}</Card>
 <Card title='Contratos de fornecimento no período'>{result.suppliers.length?result.suppliers.map(s=><article className='ds-card' key={s.id}><h3>{s.number}</h3><p>{date(s.start)} a {date(s.end)} · Fonte dos preços: {s.priceSource==='HISTORY'?'histórico por vigência':'tabela anual'}</p>{showCoverage(s.priceCoverage)}</article>):<p>Nenhum contrato de compra ativo/aprovado no período.</p>}</Card>
 <Card title='Ainda não verificado nesta etapa'><ul>{result.notChecked.map(item=><li key={item}>{item}</li>)}</ul><p>Esta consulta não afirma ausência desses dados; eles ainda não estão integrados ao diagnóstico. Versão das verificações: {result.ruleVersion}.</p></Card></>:null}</section>;
}
