'use client';
import type {CorrectionContext} from './preparation-navigation';
import ManagementAllocation from './ManagementAllocation';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {PERM,Customer,Unit,date,money} from './types';
type Row={id:string;customer_id:string;consumer_unit_id?:string;contract_number:string;start_date:string;end_date:string;remuneration_model?:string;fixed_fee_monthly?:number;savings_percentage?:number;application_rules?:string;agreement_type?:string;counterparty?:string;description?:string;billing_basis?:string;agreed_value?:number};
const basis:Record<string,string>={FIXED_MONTHLY:'Valor mensal (R$)',PER_MWH:'Preço por MWh (R$/MWh)',PERCENTAGE:'Percentual (%)',CUSTOM:'Regra contratual específica'};
export default function CommercialTerms({kind,customerId,units,customers,onDirty,initialContext,allowNew=true}:{initialContext?:CorrectionContext;allowNew?:boolean;kind:'management'|'services';customerId:string;units:Unit[];customers:Customer[];onDirty:(dirty:boolean)=>void}){
 const {hasPermission}=useAuth(),management=kind==='management';
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[model,setModel]=useState('FIXED'),[billing,setBilling]=useState('FIXED_MONTHLY'),[confirmation,setConfirmation]=useState<Record<string,unknown>|null>(null);
 const pending=useRef(false),formRef=useRef<HTMLFormElement>(null),path='/api/v1/contract-configurations/'+kind;
 useEffect(()=>{let cancelled=false;apiRequest<Row[]>(path).then(r=>{if(!cancelled)setRows(r);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[path]);
 function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),text=(k:string)=>String(f.get(k)||'').trim();const body:Record<string,unknown>={customerId,contractNumber:text('contractNumber'),startDate:text('startDate'),endDate:text('endDate'),applicationRules:text('applicationRules')};
 if(String(body.endDate)<String(body.startDate)){setError('Confira o início e o término da vigência.');return;}
 if(management)Object.assign(body,{remunerationModel:model,fixedFeeMonthly:Number(text('fixedFeeMonthly')),savingsPercentage:model==='HYBRID'?Number(text('savingsPercentage')):0});
 else{Object.assign(body,{agreementType:text('agreementType'),counterparty:text('counterparty'),description:text('description'),billingBasis:billing});if(text('consumerUnitId'))body.consumerUnitId=text('consumerUnitId');if(text('agreedValue'))body.agreedValue=Number(text('agreedValue'));}
 setError('');setConfirmation(body);}
 async function save(){if(!confirmation||pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{const r=await apiRequest<Row>(path,{method:'POST',body:confirmation});setRows(old=>[r,...old]);setConfirmation(null);formRef.current?.reset();setModel('FIXED');setBilling('FIXED_MONTHLY');onDirty(false);setMessage('Vigência registrada e preservada no histórico.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.');}finally{pending.current=false;setBusy(false);}}
 const visible=rows.filter(r=>!customerId||r.customer_id===customerId).sort((a,b)=>b.start_date.localeCompare(a.start_date));
 return <section><h2>{management?'Honorários da gestão':'Intermediação e outros serviços'}</h2>
 <p>{management?'Configure o honorário fixo por unidade e, no híbrido, o percentual sobre a economia consolidada do cliente. Confirme a regra mensal abaixo; somente a parcela variável será rateada. Cada vigência é preservada.':'Registre a contraparte, o escopo e a regra comercial. Estes registros não geram cobrança nem entram automaticamente nos cálculos de economia.'}</p>
 {error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 {allowNew&&hasPermission(PERM.create)&&customerId?<Card title={management?'Nova vigência de honorários':'Novo contrato de serviço'}><form ref={formRef} onSubmit={review} onChange={()=>{setConfirmation(null);onDirty(true);}} className="organizations-create__form"><fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:16}}>
 <Input label="Número / referência desta vigência" name="contractNumber" maxLength={management?50:100} required/>
 {management?<><label>Modelo de honorário<select className="ds-input" value={model} onChange={e=>setModel(e.target.value)}><option value="FIXED">Fixo mensal</option><option value="HYBRID">Híbrido: fixo + percentual sobre economia consolidada antes dos honorários</option></select></label><Input label="Honorário fixo mensal por unidade (R$)" name="fixedFeeMonthly" type="number" min="0" step="0.01" required/>{model==='HYBRID'?<Input label="Percentual sobre economia líquida (%)" name="savingsPercentage" type="number" min="0" max="100" step="0.0001" required/>:null}<p>A apuração da economia líquida e dos honorários será feita pelo motor de cálculo com a configuração válida para cada período.</p></>:<>
 <label>Natureza do contrato<select className="ds-input" name="agreementType"><option value="INTERMEDIATION">Intermediação</option><option value="OTHER">Outro serviço</option></select></label>
 <Input label="Intermediário / prestador contratado" name="counterparty" maxLength={255} required/><Input label="Objeto do contrato" name="description" maxLength={2000} required/>
 <label>Abrangência<select className="ds-input" name="consumerUnitId"><option value="">Cliente como um todo</option>{units.filter(u=>u.customer_id===customerId).map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label>
 <label>Base de cobrança<select className="ds-input" value={billing} onChange={e=>setBilling(e.target.value)}>{Object.entries(basis).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <Input label={billing==='PERCENTAGE'?'Percentual contratado (%)':billing==='PER_MWH'?'Preço contratado (R$/MWh)':'Valor contratado (R$)'} name="agreedValue" type="number" min="0" max={billing==='PERCENTAGE'?100:undefined} step="any" required={billing!=='CUSTOM'}/></>}
 <Input label="Início da vigência" type="date" name="startDate" required/><Input label="Término da vigência" type="date" name="endDate" required/>
 <label>Regras de aplicação e condições comerciais<textarea className="ds-input" name="applicationRules" maxLength={4096} required placeholder={management?'Descreva a aplicação do honorário, a base da economia e as condições do contrato.':'Descreva a base de incidência, periodicidade, condições e exceções.'}/></label>
 <Button type="submit">Revisar cadastro</Button>
 {confirmation?<div role="status"><p>Registrar a vigência de {date(String(confirmation.startDate))} a {date(String(confirmation.endDate))}? Confira os campos acima. Este registro será preservado e não poderá ser sobrescrito.</p><Button type="button" disabled={busy} onClick={()=>void save()}>{busy?'Registrando...':'Confirmar vigência'}</Button><Button type="button" variant="secondary" disabled={busy} onClick={()=>setConfirmation(null)}>Voltar à revisão</Button></div>:null}
 </fieldset></form></Card>:<p>{!customerId?'Selecione um cliente para registrar uma nova vigência.':'Consulta das vigências cadastradas.'}</p>}
 <Card title="Vigências registradas">{loading?<p>Carregando...</p>:!visible.length?<p>{error?'Consulta não concluída.':'Nenhuma vigência registrada.'}</p>:visible.map(r=><article className="ds-card" key={r.id}><h3>{r.contract_number}</h3><p>{customers.find(c=>c.id===r.customer_id)?.company_name||'Cliente vinculado'}</p><p>{date(r.start_date)} a {date(r.end_date)}</p>{management?<p>{r.remuneration_model==='HYBRID'?'Híbrido':r.remuneration_model==='FIXED'?'Fixo':r.remuneration_model} · R$ {money(r.fixed_fee_monthly||0)}/mês{r.remuneration_model==='HYBRID'?' + '+money(r.savings_percentage||0)+'% sobre economia líquida':''}</p>:<><p>{r.agreement_type==='INTERMEDIATION'?'Intermediação':'Outro serviço'} · {r.counterparty}</p><p>{r.description}</p><p>Abrangência: {r.consumer_unit_id?units.find(u=>u.id===r.consumer_unit_id)?.name||'Unidade vinculada':'Cliente como um todo'}</p><p>{basis[r.billing_basis||'']}: {r.agreed_value==null?'Conforme regras':money(r.agreed_value)}</p></>}<p style={{whiteSpace:'pre-wrap'}}>{r.application_rules||'Registro anterior sem regras detalhadas.'}</p></article>)}</Card>{management?<ManagementAllocation initialContext={initialContext} customerId={customerId} units={units} contracts={rows} onDirty={onDirty}/>:null}</section>;
}
