'use client';
import {useEffect,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {Button,Card} from '@/app/components/ui';
import {useAuth} from '@/app/providers';
import BotEnergyHelp from '@/app/components/BotEnergyHelp';
import OcrAssistant from '../documents/OcrAssistant';
import type {OcrAutofill} from './ocr-autofill';
import type {CorrectionContext} from './preparation-navigation';
const labels:Record<string,string>={consumptionTotal:'Consumo total (kWh)',consumptionPeak:'Consumo na ponta (kWh)',consumptionOffPeak:'Consumo fora ponta (kWh)',demandSingle:'Demanda medida (kW)'};
type Source={id:string;customer_id:string;consumer_unit_id:string;original_filename:string;reference_month:string};
export default function ContractSourceAssistant({customerId,onAccept}:{customerId:string;onAccept:(context:CorrectionContext,fields:OcrAutofill)=>void}){
 const {hasPermission}=useAuth();
 const [sources,setSources]=useState<Source[]>([]),[selected,setSelected]=useState(''),[opened,setOpened]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[proposal,setProposal]=useState<OcrAutofill|null>(null);
 useEffect(()=>{const abort=new AbortController();apiRequest<{documents:Source[]}>('/api/v1/documents/bot-energy/context',{signal:abort.signal}).then(r=>setSources(r.documents.filter(d=>d.customer_id===customerId))).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[customerId]);
 const source=sources.find(s=>s.id===selected);
 async function propose(){if(!source||busy)return;setBusy(true);setError('');setProposal(null);try{const p=await apiRequest<OcrAutofill>('/api/v1/documents/'+encodeURIComponent(source.id)+'/ocr/assistant/autofill');if(p.documentId!==source.id||p.unitId!==source.consumer_unit_id||p.month!==source.reference_month.slice(0,7))throw Error('O vínculo da fatura mudou. Atualize o contexto.');setProposal(p);}catch(e){setError(e instanceof Error?e.message:'Não foi possível conferir a fatura. Faça a leitura e preparação primeiro.');}finally{setBusy(false);}}
 function accept(tab:string){if(!source||!proposal)return;onAccept({customerId,unitId:proposal.unitId,month:proposal.month,tab,message:'Proposta aceita pelo operador para preencher um novo rascunho. Confira o PDF e os valores antes de salvar e validar.'},proposal);}
 return <Card title="Bot-Energy · preencher a partir da fatura"><p>Escolha a fatura deste cliente. Leia e prepare os campos, confira as fontes e aceite a proposta para abrir o formulário da unidade e competência corretas.</p>{error&&<p role="alert">{error}</p>}<label>Fatura de origem<select className="ds-input" value={selected} disabled={busy} onChange={e=>{setSelected(e.target.value);setProposal(null);setError('');setOpened(false);}}><option value="">Selecione unidade, competência e arquivo</option>{sources.map(s=><option key={s.id} value={s.id}>{s.reference_month.slice(0,7)} · {s.original_filename}</option>)}</select></label>{source&&<><Button disabled={busy} onClick={()=>setOpened(true)}>Ler fatura e preparar preenchimentos</Button><Button variant="secondary" disabled={busy} onClick={()=>void propose()}>{busy?'Conferindo…':'Conferir propostas para preencher formulário'}</Button><BotEnergyHelp key={source.id} documentId={source.id}/></>}{proposal&&<section aria-label="Propostas de preenchimento com fontes"><p>{proposal.message}</p><dl>{Object.entries(proposal.measurements).map(([field,value])=><div key={field}><dt>{labels[field]??field}</dt><dd>{value}</dd></div>)}</dl>{proposal.taxes.map(t=><p key={t.code}>{t.code}: {t.rate}% · {t.source}</p>)}{proposal.tariffs.map(t=><p key={t.component+t.band}>{t.component} · {t.band}: {t.rateMwh??'Sem valor comprovado'} R$/MWh · {t.reason} · {t.source}</p>)}<details><summary>Fonte documental e biblioteca</summary><p style={{overflowWrap:'anywhere'}}>{proposal.source}</p><p>{({MATCHED:'Versão aplicável encontrada',AMBIGUOUS:'Mais de uma versão aplicável; conferir',MISSING:'Sem versão aplicável'} as Record<string,string>)[proposal.libraryState]??'Conferir disponibilidade'} · {proposal.library?.source??'Biblioteca sem versão aplicável. Nenhum preço oficial será presumido.'}</p></details><p>Aceitar preenche novos rascunhos; registros existentes preservam seus valores e validações.</p><Button disabled={!hasPermission('beb6ec90-8ba8-40ce-a156-aeef6cc75cce')} onClick={()=>accept('monthly')}>Aceitar proposta e abrir Dados mensais</Button><Button variant="secondary" disabled={!hasPermission('beb6ec90-8ba8-40ce-a156-aeef6cc75cce')} onClick={()=>accept('parameters')}>Aceitar proposta e abrir Parâmetros</Button><Button variant="secondary" disabled={!hasPermission('beb6ec90-8ba8-40ce-a156-aeef6cc75cce')} onClick={()=>accept('costs')}>Aceitar proposta e abrir Custos mensais</Button></section>}{opened&&source&&<OcrAssistant key={source.id} id={source.id} canProcess={hasPermission('92e1b670-ab10-483a-b825-c6e16799496d')} openRequest={1}/>}</Card>;
}
