'use client';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import type {Result} from './CalculationPreparation';
import type {Unit} from './types';
import {contractReadiness} from './contract-readiness';
import {correctionTarget,type CorrectionContext} from './preparation-navigation';
const colors=['#54cee7','#8da8ff','#c59bff','#f2c76c','#6fdeb0','#f58eaa'];
export default function ContractReadiness({customerId,units,revision,onOpen}:{customerId:string;units:Unit[];revision:number;onOpen:(context:CorrectionContext)=>void}){
 const available=units.filter(u=>u.customer_id===customerId);
 const [unitId,setUnit]=useState(available.length===1?available[0].id:''),[month,setMonth]=useState(''),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);const generation=useRef(0);
 const unit=available.find(u=>u.id===unitId);
 useEffect(()=>{const seq=++generation.current;setResult(null);setError('');setBusy(false);if(!unit||!/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(month))return;setBusy(true);apiRequest<Result>('/api/v1/calculation-preparation/combined?consumerUnitId='+encodeURIComponent(unit.id)+'&month='+encodeURIComponent(month)).then(r=>{if(seq===generation.current){if(r.unit.id!==unit.id||r.month!==month)throw new Error('A resposta não corresponde à unidade e competência selecionadas.');setResult(r);}}).catch(e=>{if(seq===generation.current)setError(e.message||'Falha ao consultar pendências.');}).finally(()=>{if(seq===generation.current)setBusy(false);});return()=>{generation.current++;};},[unitId,month,customerId,revision,refresh]); // eslint-disable-line react-hooks/exhaustive-deps
 const progress=unit?contractReadiness(unit,result):null;
 function open(tab:string,message?:string){if(unit)onOpen({customerId,unitId:unit.id,month,tab,message});}
 return <section aria-label="Progresso da configuração" className="ds-card"><h2>O que falta para preparar a apuração?</h2><p>Selecione a unidade e a competência. Cada camada representa uma etapa; os percentuais contam verificações atendidas, incluindo aprovação e vigência.</p><div style={{display:'flex',flexWrap:'wrap',gap:16,alignItems:'end'}}><label>Unidade do progresso<select className="ds-input" value={unitId} onChange={e=>setUnit(e.target.value)}><option value="">Selecione</option>{available.map(u=><option value={u.id} key={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label><label>Competência do progresso<input className="ds-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="ds-button" type="button" disabled={busy||!unit||!month} onClick={()=>setRefresh(v=>v+1)}>Atualizar progresso</button></div>
 {error&&<p role="alert">{error} Nenhuma conclusão de prontidão foi emitida.</p>}{busy&&<p role="status">Conferindo cadastros e validações da competência…</p>}
 {!month?<p>Informe o mês para consultar o progresso. Sem competência, não é possível confirmar vigências.</p>:null}
 {progress&&result&&!busy&&!error?<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:24,alignItems:'center',marginTop:20}}><div><svg viewBox="0 0 260 260" role="img" aria-label={'Progresso das verificações: '+progress.percent+'%'} style={{width:'100%',maxWidth:300,display:'block',margin:'auto'}}>{progress.stages.map((s,i)=>{const radius=118-i*13,c=2*Math.PI*radius;return <g key={s.id}><circle cx="130" cy="130" r={radius} fill="none" stroke="#24364d" strokeWidth="8"/><circle cx="130" cy="130" r={radius} fill="none" stroke={colors[i]} strokeWidth="8" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={c*(1-s.percent/100)} transform="rotate(-90 130 130)"/></g>;})}<text x="130" y="130" textAnchor="middle" fill="currentColor" fontSize="25" fontWeight="700">{progress.percent}%</text><text x="130" y="149" textAnchor="middle" fill="currentColor" fontSize="10">das verificações</text></svg><p role="status" style={{textAlign:'center',fontWeight:700}}>{progress.ready?'Pronto para preparar apuração':'Configuração em andamento'}</p></div><div style={{display:'grid',gap:12}}>{progress.stages.map((s,i)=><button key={s.id} type="button" onClick={()=>open(s.id,s.pending.join('; '))} style={{textAlign:'left',padding:14,border:'1px solid #405571',borderRadius:10,background:'#142237',color:'inherit',cursor:'pointer'}}><span style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{s.label}</strong><strong style={{color:colors[i]}}>{s.percent}%</strong></span><span style={{display:'block',height:5,background:'#24364d',borderRadius:8,margin:'8px 0'}}><span style={{display:'block',height:'100%',width:s.percent+'%',background:colors[i],borderRadius:8}}/></span><small>{s.passed}/{s.total} verificações · {s.pending[0]||'Etapa conferida'} · Abrir etapa</small></button>)}</div></div>
 <p>100% indica prontidão para a preparação, não publicação ou aprovação financeira. Intermediação e outros são tratados quando aplicáveis. Consulta: {new Date(result.checkedAt).toLocaleString('pt-BR')}.</p>
 <button type="button" className="ds-button" onClick={()=>open('preparation')}>{progress.ready?'Pronto — preparar apuração':'Ver diagnóstico da apuração'}</button>
 {!!result.findings.length&&<details><summary>{result.findings.length} pendências e pontos de revisão — direcionar ajustes</summary><ul>{result.findings.map((f,i)=>{const target=correctionTarget(f,{customerId,unitId:unit!.id,month});return <li key={f.code+i} style={{margin:'12px 0'}}>{f.message} <button type="button" className="ds-button" onClick={()=>target?onOpen({...target,message:f.message}):open('preparation',f.message)}>Abrir {target?'ajuste':'diagnóstico'}</button></li>;})}</ul></details>}
 </>:null}{!available.length&&<p>Cadastre uma unidade para iniciar as verificações deste cliente.</p>}</section>;
}
