'use client';
import {FormEvent,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {Customer,Unit} from './types';
const modalities:Record<string,string>={BLUE:'Azul',GREEN:'Verde',WHITE:'Branca',CONVENTIONAL:'Convencional'};
export default function Distributor({customerId,units,customers,onUnits,onDirty}:{customerId:string;units:Unit[];customers:Customer[];onUnits:(units:Unit[])=>void;onDirty:(dirty:boolean)=>void}){
 const {hasPermission}=useAuth();const [editing,setEditing]=useState<Unit|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const pending=useRef(false);
 const canCreate=hasPermission('05613764-311a-4e71-ac99-475ad1dfe87a'),canEdit=hasPermission('0f2e539d-03f9-4168-bc8c-55ac3a371628'),canView=hasPermission('b142bd7b-05a3-45ee-befd-e593066c2775');
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current)return;const form=e.currentTarget,f=new FormData(form);const body:Record<string,unknown>={};for(const [k,v] of Array.from(f.entries()))if(String(v).trim()!=='')body[k]=k==='contractedDemand'?Number(v):String(v).trim();if(!editing)body.customerId=customerId;
 pending.current=true;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Unit>('/api/v1/consumer-units'+(editing?'/'+encodeURIComponent(editing.id):''),{method:editing?'PUT':'POST',body});onUnits([row,...units.filter(u=>u.id!==row.id)]);setEditing(null);form.reset();onDirty(false);setMessage('Configuração da unidade salva.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{pending.current=false;setBusy(false);}}
 if(!canView)return <p>Você não tem permissão para consultar unidades.</p>;
 return <section><h2>Distribuidora e unidades consumidoras</h2><p>Configuração técnica da instalação. Estes campos pertencem à unidade consumidora e são compartilhados com Clientes e unidades.</p>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 {customerId&&((!editing&&canCreate)||(editing&&canEdit))?<Card title={editing?'Editar configuração da unidade':'Nova unidade e distribuidora'}><form key={editing?.id||'new'} onSubmit={save} onChange={()=>onDirty(true)} className="organizations-create__form"><fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:16}}>
 <Input label="Nome da unidade" name="name" maxLength={255} defaultValue={editing?.name} required/><Input label="Código da instalação / unidade" name="code" maxLength={20} defaultValue={editing?.consumer_unit_number} required/>
 <Input label="Distribuidora" name="distributor" maxLength={50} defaultValue={editing?.distributor} required/><Input label="Grupo tarifário" name="tariffGroup" maxLength={10} defaultValue={editing?.tariff_group} required/>
 <label>Modalidade tarifária<select className="ds-input" name="tariffModality" defaultValue={editing?.tariff_modality||''}><option value="">Não informada</option>{Object.entries(modalities).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <Input label="Demanda contratada (kW)" name="contractedDemand" type="number" min="0" step="any" defaultValue={editing?.contracted_demand??''}/><Input label="Tensão / classe de tensão" name="voltageClass" maxLength={20} defaultValue={editing?.voltage||''}/>
 <Input label="Endereço da instalação" name="address" maxLength={1000} defaultValue={editing?.address||''}/><Input label="Cidade" name="city" maxLength={255} defaultValue={editing?.city||''}/><Input label="Estado" name="state" maxLength={50} defaultValue={editing?.state||''}/>
 <Button type="submit">{busy?'Salvando...':'Salvar configuração'}</Button>{editing?<Button type="button" variant="secondary" onClick={()=>{setEditing(null);onDirty(false);}}>Cancelar edição</Button>:null}</fieldset></form></Card>:<p>Selecione um cliente para cadastrar ou editar sua estrutura energética.</p>}
 <Card title="Estrutura energética cadastrada">{!units.some(u=>!customerId||u.customer_id===customerId)?<p>Nenhuma unidade cadastrada para esta seleção.</p>:null}{units.filter(u=>!customerId||u.customer_id===customerId).map(u=><article key={u.id} className="ds-card"><h3>{u.name||u.consumer_unit_number}</h3><p>{customers.find(c=>c.id===u.customer_id)?.company_name||'Cliente vinculado'}</p><p>{u.distributor} · Instalação {u.consumer_unit_number}</p><p>Grupo {u.tariff_group} · {modalities[u.tariff_modality||'']||'Modalidade não informada'}</p><p>Demanda: {u.contracted_demand??'Não informada'} kW · Tensão: {u.voltage||'Não informada'}</p><p>{u.address} {u.city} {u.state}</p>{canEdit&&customerId?<Button variant="secondary" disabled={busy} onClick={()=>{setEditing(u);setError('');window.scrollTo({top:0,behavior:'smooth'});}}>Editar configuração</Button>:null}</article>)}</Card></section>;
}
