'use client';
import {FormEvent,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {Customer,Unit,date} from './types';
const modalities:Record<string,string>={BLUE:'Azul',GREEN:'Verde',WHITE:'Branca',CONVENTIONAL:'Convencional'};
const subgroups:Record<string,string>={"A1":"A1 (>230 kV)","A2":"A2 (88 a 138 kV)","A3":"A3 (69 kV)","A3a":"A3a (30 a 44 kV)","A4":"A4 (2,3 a 25 kV)","AS":"AS (Subterrâneo)","B1":"B1 Residencial","B2":"B2 Rural","B3":"B3 Comercial/Industrial de pequeno porte","B4":"B4 Iluminação Pública"};
const classes:Record<string,string>={"INDUSTRIAL":"Industrial","COMMERCIAL":"Comercial","RURAL":"Rural","PUBLIC_AUTHORITY":"Poder Público","PUBLIC_SERVICE":"Serviço Público","RESIDENTIAL":"Residencial"};
const numbers:Record<string,string>={"contractedDemandPeak":"contracted_demand_peak","contractedDemandOffPeak":"contracted_demand_off_peak","demandTariff":"demand_tariff","demandTariffPeak":"demand_tariff_peak","demandTariffOffPeak":"demand_tariff_off_peak","energyTariffPeak":"energy_tariff_peak","energyTariffOffPeak":"energy_tariff_off_peak","reactiveEnergyTariff":"reactive_energy_tariff","lastDemandValue":"last_demand_value","lastDemandPeak":"last_demand_peak","lastDemandOffPeak":"last_demand_off_peak"};
const textFields:Record<string,string>={tariffSubgroup:'tariff_subgroup',consumptionClass:'consumption_class',lastDemandAdjustmentDate:'last_demand_adjustment_date'};
export default function Distributor({customerId,units,customers,onUnits,onDirty,allowNew=true}:{allowNew?:boolean;customerId:string;units:Unit[];customers:Customer[];onUnits:(units:Unit[])=>void;onDirty:(dirty:boolean)=>void}){
 const {hasPermission}=useAuth();const [editing,setEditing]=useState<Unit|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[group,setGroup]=useState(''),[modality,setModality]=useState(''),[version,setVersion]=useState(0);const pending=useRef(false);
 const canCreate=hasPermission('05613764-311a-4e71-ac99-475ad1dfe87a'),canEdit=hasPermission('0f2e539d-03f9-4168-bc8c-55ac3a371628'),canView=hasPermission('b142bd7b-05a3-45ee-befd-e593066c2775');
 const blue=modality==='BLUE';
 function reset(){setEditing(null);setGroup('');setModality('');setVersion(v=>v+1);onDirty(false);}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current)return;const f=new FormData(e.currentTarget),body:Record<string,unknown>={};
 for(const [k,v] of Array.from(f.entries()))if(String(v).trim()!=='')body[k]=String(v).trim();
 for(const k of [...Object.keys(numbers),'contractedDemand'])body[k]=f.get(k)!==null&&String(f.get(k)).trim()!==''?Number(f.get(k)):null;
 for(const k of Object.keys(textFields))body[k]=String(f.get(k)||'').trim()||null;
 body.freeMarket=f.get('freeMarket')==='true'?true:f.get('freeMarket')==='false'?false:null;
 if(!modality)delete body.tariffModality;
 if(!editing)body.customerId=customerId;
 pending.current=true;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Unit>('/api/v1/consumer-units'+(editing?'/'+encodeURIComponent(editing.id):''),{method:editing?'PUT':'POST',body});onUnits([row,...units.filter(u=>u.id!==row.id)]);reset();setMessage('Configuração elétrica salva.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{pending.current=false;setBusy(false);}}
 function num(name:string,label:string,required=false){const column=numbers[name]||'contracted_demand';return <Input key={name} label={label} name={name} type="number" min="0" step="any" defaultValue={editing?.[column as keyof Unit] as number??''} required={required}/>;}
 if(!canView)return <p>Você não tem permissão para consultar unidades.</p>;
 return <section><h2>Distribuidora e unidades consumidoras</h2><p>Dados elétricos por instalação. Tarifas são informadas conforme o contrato ou a fatura da distribuidora.</p>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 {customerId&&((!editing&&canCreate&&allowNew)||(editing&&canEdit))?<Card title={editing?'Editar configuração da unidade':'Nova unidade e distribuidora'}><form key={(editing?.id||'new')+version} onSubmit={save} onChange={()=>onDirty(true)} className="organizations-create__form"><fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:16}}>
 <Input label="Nome da unidade" name="name" maxLength={255} defaultValue={editing?.name} required/><Input label="Código da instalação / unidade" name="code" maxLength={20} defaultValue={editing?.consumer_unit_number} required/>
 <Input label="Distribuidora" name="distributor" maxLength={50} defaultValue={editing?.distributor} required/>
 <h3>Dados elétricos</h3>
 {editing&&!['A','B'].includes(editing.tariff_group)?<Alert>Grupo anterior: {editing.tariff_group}. Confirme o grupo e o subgrupo antes de salvar.</Alert>:null}
 <label>Grupo tarifário<select className="ds-input" name="tariffGroup" value={group} onChange={e=>{setGroup(e.target.value);setModality('');}} required><option value="">Selecione</option><option value="A">A</option><option value="B">B</option></select></label>
 <label>Subgrupo tarifário<select key={group} className="ds-input" name="tariffSubgroup" defaultValue={editing?.tariff_subgroup||''} required><option value="">Selecione</option>{Object.entries(subgroups).filter(([k])=>k.startsWith(group)&&!!group).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Modalidade tarifária<select className="ds-input" name="tariffModality" value={modality} onChange={e=>setModality(e.target.value)} required><option value="">Selecione</option>{Object.entries(modalities).filter(([v])=>group==='A'?['BLUE','GREEN'].includes(v):group==='B'?['WHITE','CONVENTIONAL'].includes(v):true).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Classe de consumo<select className="ds-input" name="consumptionClass" defaultValue={editing?.consumption_class||''}><option value="">Não informada</option>{Object.entries(classes).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label>Cadastrada no Mercado Livre<select className="ds-input" name="freeMarket" defaultValue={editing?.free_market==null?'':String(editing.free_market)}><option value="">Não informado</option><option value="true">Sim</option><option value="false">Não</option></select></label>
 <Input label="Tensão / classe de tensão" name="voltageClass" maxLength={20} defaultValue={editing?.voltage||''}/>
 <h3>Demanda contratada e tarifas</h3>
 {blue?<>{num('contractedDemandPeak','Demanda contratada de ponta (kW)',true)}{num('contractedDemandOffPeak','Demanda contratada fora ponta (kW)',true)}{num('demandTariffPeak','Tarifa de demanda de ponta (R$/kW)')}{num('demandTariffOffPeak','Tarifa de demanda fora ponta (R$/kW)')}</>:<>{num('contractedDemand','Demanda contratada (kW)')}{num('demandTariff','Tarifa de demanda (R$/kW)')}</>}
 {num('energyTariffPeak','Tarifa de energia de ponta (R$/kWh)')}{num('energyTariffOffPeak','Tarifa de energia fora ponta (R$/kWh)')}{num('reactiveEnergyTariff','Tarifa de energia reativa (R$/kVArh)')}
 <h3>Último ajuste de demanda</h3><Input label="Data do último ajuste de demanda" name="lastDemandAdjustmentDate" type="date" defaultValue={editing?.last_demand_adjustment_date?.slice(0,10)||''}/>
 {num('lastDemandValue','Demanda única contratada no último ajuste (kW)')}{num('lastDemandPeak','Demanda de ponta contratada no último ajuste (kW)')}{num('lastDemandOffPeak','Demanda fora ponta contratada no último ajuste (kW)')}
 <p>Ao informar o último ajuste, preencha a data e a demanda única ou os valores de ponta e fora ponta daquela contratação.</p>
 <h3>Localização</h3><Input label="Endereço da instalação" name="address" maxLength={1000} defaultValue={editing?.address||''}/><Input label="Cidade" name="city" maxLength={255} defaultValue={editing?.city||''}/><Input label="Estado" name="state" maxLength={50} defaultValue={editing?.state||''}/>
 <Button type="submit">{busy?'Salvando...':'Salvar configuração'}</Button>{editing?<Button type="button" variant="secondary" onClick={reset}>Cancelar edição</Button>:null}</fieldset></form></Card>:<p>{allowNew?'Selecione um cliente para cadastrar ou editar sua estrutura energética.':'Consulte a estrutura energética abaixo. Para editar uma unidade, selecione seu cliente.'}</p>}
 <Card title="Estrutura energética cadastrada">{!units.some(u=>!customerId||u.customer_id===customerId)?<p>Nenhuma unidade cadastrada para esta seleção.</p>:null}{units.filter(u=>!customerId||u.customer_id===customerId).map(u=><article key={u.id} className="ds-card"><h3>{u.name||u.consumer_unit_number}</h3><p>{customers.find(c=>c.id===u.customer_id)?.company_name||'Cliente vinculado'}</p><p>{u.distributor} · Instalação {u.consumer_unit_number}</p><p>Grupo {u.tariff_group} · {subgroups[u.tariff_subgroup||'']||'Subgrupo não informado'} · {modalities[u.tariff_modality||'']||'Modalidade não informada'}</p><p>Classe: {classes[u.consumption_class||'']||'Não informada'} · Mercado Livre: {u.free_market==null?'Não informado':u.free_market?'Sim':'Não'}</p><details><summary>Demandas, tarifas e último ajuste</summary><p>Demanda: {u.contracted_demand??'—'} kW · Ponta: {u.contracted_demand_peak??'—'} kW · Fora ponta: {u.contracted_demand_off_peak??'—'} kW</p><p>Tarifa demanda: {u.demand_tariff??'—'} R$/kW · Ponta: {u.demand_tariff_peak??'—'} · Fora ponta: {u.demand_tariff_off_peak??'—'}</p><p>Energia ponta: {u.energy_tariff_peak??'—'} R$/kWh · Fora ponta: {u.energy_tariff_off_peak??'—'} R$/kWh · Reativa: {u.reactive_energy_tariff??'—'} R$/kVArh</p><p>Último ajuste: {date(u.last_demand_adjustment_date||'')} · Demanda: {u.last_demand_value??'—'} kW · Ponta: {u.last_demand_peak??'—'} kW · Fora ponta: {u.last_demand_off_peak??'—'} kW</p></details><p>Tensão: {u.voltage||'Não informada'} · {u.address} {u.city} {u.state}</p>{canEdit&&customerId?<Button variant="secondary" disabled={busy} onClick={()=>{setEditing(u);setGroup(['A','B'].includes(u.tariff_group)?u.tariff_group:'');setModality(u.tariff_modality||'');setVersion(v=>v+1);setError('');window.scrollTo({top:0,behavior:'smooth'});}}>Editar configuração</Button>:null}</article>)}</Card></section>;
}
