'use client';
import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {Customer,Unit,PERM} from './types';
import SupplyOperatingFields,{OperatingSummary,OperatingTerms,readOperatingTerms} from './SupplyOperatingFields';
import SupplyTermsFields,{AnnualPrice,SupplyTerms,readSupplyTerms} from './SupplyTermsFields';
import {EntryKind,Payload,Field,entryKinds,entrySteps,initialEntry,issueLabel} from './entry-fields';
type Entry={id:string;customer_id:string;kind:EntryKind;payload:Payload;status:'INCOMPLETE'|'DRAFT'|'REGISTERED';issues:string[];deferred_steps:number[];revision:number;updated_at:string};
function supplySeed(p:Payload){return {annual_prices:p.annualPrices||[],pricing_mode:p.pricingMode,adjustment_index:p.adjustmentIndex,adjustment_frequency:p.adjustmentFrequency,adjustment_date:p.adjustmentDate,adjustment_rule:p.adjustmentRule,guarantee_type:p.guaranteeType,guarantee_amount:p.guaranteeAmount,guarantee_institution:p.guaranteeInstitution,guarantee_description:p.guaranteeDescription,flexibility_min_percent:p.flexibilityMinPercent,flexibility_max_percent:p.flexibilityMaxPercent,modulation:p.modulation,submarket:p.submarket,seasonality_mode:p.seasonalityMode,seasonality_rule:p.seasonalityRule,seasonal_volumes:p.seasonalVolumes||[]} as SupplyTerms & OperatingTerms;}
export default function EntryWizard({customers,units,filterCustomer,onDirty,onActive,onRegistered,requestStart}:{requestStart:(action:()=>void)=>void;customers:Customer[];units:Unit[];filterCustomer:string;onDirty:(v:boolean)=>void;onActive:(v:boolean)=>void;onRegistered:()=>void}){
 const {hasPermission}=useAuth();const canCreate=hasPermission(PERM.create),canUpdate=hasPermission(PERM.update),canUnit=hasPermission('05613764-311a-4e71-ac99-475ad1dfe87a');
 const [rows,setRows]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [open,setOpen]=useState(false),[editing,setEditing]=useState<Entry|null>(null),[kind,setKind]=useState<EntryKind>('supply'),[customer,setCustomer]=useState(''),[step,setStep]=useState(-1),[payload,setPayload]=useState<Payload>({}),[seed,setSeed]=useState<Payload>({}),[deferred,setDeferred]=useState<number[]>([]),[version,setVersion]=useState(0),[dirty,setDirty]=useState(false),[cancel,setCancel]=useState(false),[register,setRegister]=useState<Entry|null>(null),[schedule,setSchedule]=useState(false);
 const form=useRef<HTMLFormElement>(null),working=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 const steps=entrySteps[kind];
 async function reload(){setLoading(true);setError('');try{setRows(await apiRequest<Entry[]>('/api/v1/contract-entry-drafts'));}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os lançamentos.');}finally{setLoading(false);}}
 useEffect(()=>{let live=true;apiRequest<Entry[]>('/api/v1/contract-entry-drafts').then(r=>{if(live)setRows(r);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 useEffect(()=>{if(open)heading.current?.focus();},[step,open]);
 function mark(){setDirty(true);onDirty(true);setMessage('');}
 function start(row?:Entry){setEditing(row||null);setKind(row?.kind||'supply');setCustomer(row?.customer_id||filterCustomer);setPayload(row?.payload||initialEntry('supply'));setSeed(row?.payload||{});setDeferred(row?.deferred_steps||[]);setSchedule(!!row?.payload.annualPrices?.length);setStep(row?0:-1);setVersion(v=>v+1);setError('');setMessage('');setDirty(false);onDirty(false);setOpen(true);onActive(true);setCancel(false);setRegister(null);}
 function close(){setOpen(false);onActive(false);setDirty(false);onDirty(false);setCancel(false);setEditing(null);}
 function patch(key:string,value:Payload[string]){setPayload(old=>{const next={...old};if(value==='')delete next[key];else next[key]=value;
 if(key==='tariffGroup'){delete next.tariffSubgroup;delete next.tariffModality;for(const k of ['contractedDemand','contractedDemandPeak','contractedDemandOffPeak','demandTariff','demandTariffPeak','demandTariffOffPeak'])delete next[k];}
 if(key==='tariffModality'){for(const k of value==='BLUE'?['contractedDemand','demandTariff']:['contractedDemandPeak','contractedDemandOffPeak','demandTariffPeak','demandTariffOffPeak'])delete next[k];}
 if(key==='remunerationModel'&&value==='FIXED')next.savingsPercentage=0;
 return next;});mark();}
 function capture(){let p={...payload};if(kind==='supply'&&form.current){const f=new FormData(form.current);p={...p,...readOperatingTerms(f),...readSupplyTerms(f)};const annual=JSON.parse(String(f.get('annualPrices')||'[]')) as AnnualPrice[];p.annualPrices=annual;if(annual.length){const price=annual[0].pricePerMwh;p.currentPrice=price===''?'':Number(price);p.annualPrices=annual.map((r:AnnualPrice)=>({...r,pricePerMwh:r.pricePerMwh===''?'':Number(r.pricePerMwh)}));}if(p.guaranteeType&&String(f.get('guaranteeAmount')||'')==='')delete p.guaranteeAmount;}return p;}
 function move(next:number,skip=false){setPayload(capture());if(step>=0&&step<steps.length){setDeferred(old=>skip?Array.from(new Set([...old,step])):old.filter(n=>n!==step));mark();}setStep(next);}
 async function save(){if(working.current)return;working.current=true;setBusy(true);setError('');const p=capture();setPayload(p);try{const row=await apiRequest<Entry>('/api/v1/contract-entry-drafts'+(editing?'/'+editing.id:''),{method:editing?'PUT':'POST',body:{customerId:customer,kind,payload:p,deferredSteps:deferred,...(editing?{revision:editing.revision}:{})}});setRows(old=>[row,...old.filter(r=>r.id!==row.id)]);close();setMessage(row.status==='INCOMPLETE'?'Lançamento salvo com pendências. Use Continuar preenchimento para retomá-lo.':'Lançamento salvo como rascunho. Revise antes de registrar.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar. Seus campos continuam nesta tela.');}finally{working.current=false;setBusy(false);}}
 async function finish(){if(!register||working.current)return;working.current=true;setBusy(true);setError('');try{const row=await apiRequest<Entry>('/api/v1/contract-entry-drafts/'+register.id+'/register',{method:'POST',body:{revision:register.revision}});setRows(old=>old.map(r=>r.id===row.id?row:r));setRegister(null);setMessage(row.kind==='supply'?'Contrato criado como rascunho na consulta de Fornecedor Mercado Livre. A ativação continua separada.':'Cadastro registrado. Consulte-o na área correspondente.');onRegistered();}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar. Atualize a lista antes de tentar novamente.');}finally{working.current=false;setBusy(false);}}
 function field(f:Field){if(f.show&&!f.show(payload))return null;let opts=f.options;
 if(f.key==='tariffSubgroup')opts=Object.fromEntries(Object.entries(opts||{}).filter(([k])=>!!payload.tariffGroup&&k.startsWith(String(payload.tariffGroup))));
 if(f.key==='tariffModality')opts=Object.fromEntries(Object.entries(opts||{}).filter(([k])=>(payload.tariffGroup==='A'?['BLUE','GREEN']:payload.tariffGroup==='B'?['WHITE','CONVENTIONAL']:[]).includes(k)));
 const label=f.label+(f.required?' *':'');const value=String(payload[f.key]??'');
 if(f.type==='select'||f.type==='unit')return <label key={f.key}>{label}<select className="ds-input" value={String(value)} onChange={e=>patch(f.key,f.key==='freeMarket'&&e.target.value!==''?e.target.value==='true':e.target.value)}><option value="">{f.type==='unit'&&!f.required?'Cliente como um todo':'Selecione / preencher depois'}</option>{f.type==='unit'?units.filter(u=>u.customer_id===customer).map(u=><option value={u.id} key={u.id}>{u.name} — {u.consumer_unit_number}</option>):Object.entries(opts||{}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>;
 if(f.type==='textarea')return <label key={f.key}>{label}<textarea className="ds-input" maxLength={4096} value={value} onChange={e=>patch(f.key,e.target.value)}/></label>;
 return <Input key={f.key} label={label} type={f.type||'text'} min={f.type==='number'?0:undefined} max={f.max} step={f.type==='number'?'any':undefined} maxLength={f.maxLength||4096} value={value} disabled={f.key==='currentPrice'&&schedule} onChange={e=>patch(f.key,f.type==='number'&&e.target.value!==''?Number(e.target.value):e.target.value)}/>;
 }
 function pendingLabel(row:Entry,key:string){return key.startsWith('step:')?'Etapa deixada para depois: '+(entrySteps[row.kind][Number(key.slice(5))]?.title||'Revisão'):issueLabel(key);}
 return <section aria-label="Lançamentos guiados" style={{margin:'16px 0'}}>
 {error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 {!open?<><div style={{display:'flex',gap:12,flexWrap:'wrap'}}>{canCreate?<Button disabled={loading||busy} onClick={()=>requestStart(()=>start())}>Inserir novo</Button>:null}<Button variant="secondary" disabled={busy||loading} onClick={()=>void reload()}>Atualizar lançamentos</Button></div>
 {loading?<p>Carregando lançamentos...</p>:rows.some(r=>r.status!=='REGISTERED'&&(!filterCustomer||r.customer_id===filterCustomer))?<Card title="Lançamentos para concluir">{rows.filter(r=>r.status!=='REGISTERED'&&(!filterCustomer||r.customer_id===filterCustomer)).map(r=><article className="ds-card" key={r.id}><h3>{String(r.payload.contractNumber||r.payload.name||'Novo lançamento')} · {entryKinds[r.kind]}</h3><p>{customers.find(c=>c.id===r.customer_id)?.company_name||'Cliente vinculado'} · <strong>{r.status==='INCOMPLETE'?'Preenchimento pendente':'Rascunho — aguarda revisão'}</strong></p>{r.issues.length?<details open><summary>{r.issues.length} pendência(s)</summary><ul>{r.issues.map(k=><li key={k}>{pendingLabel(r,k)}</li>)}</ul></details>:null}{canUpdate&&(r.kind!=='distributor'||canUnit)?<Button variant="secondary" disabled={busy} onClick={()=>requestStart(()=>start(r))}>Continuar preenchimento</Button>:null}{r.status==='DRAFT'&&canCreate&&(r.kind!=='distributor'||canUnit)?<Button disabled={busy} onClick={()=>setRegister(r)}>Revisar registro</Button>:null}</article>)}</Card>:<p>Nenhum lançamento pendente nesta seleção.</p>}
 {register?<Card title="Confirmar registro"><p>{entryKinds[register.kind]} · {customers.find(c=>c.id===register.customer_id)?.company_name} · {String(register.payload.contractNumber||register.payload.name||'Lançamento')}</p><p>{register.kind==='supply'?'O contrato será criado como rascunho. Revise na consulta antes de ativar.':register.kind==='distributor'?'A unidade será cadastrada para este cliente. Os parâmetros de cálculo continuam sujeitos à revisão própria.':'A vigência será registrada e preservada no histórico. Confirme os valores antes de continuar.'}</p><Button variant="secondary" disabled={busy} onClick={()=>requestStart(()=>start(register))}>Conferir todos os campos</Button><Button disabled={busy} onClick={()=>void finish()}>{busy?'Registrando...':'Confirmar registro'}</Button><Button variant="secondary" disabled={busy} onClick={()=>setRegister(null)}>Cancelar</Button></Card>:null}</>:<Card title={editing?'Continuar lançamento':'Inserir novo lançamento'}>
 <h3 ref={heading} tabIndex={-1}>{step<0?'1. Cliente e tipo de cadastro':step===steps.length?'Revisão do lançamento':(step+2)+'. '+steps[step].title}</h3>
 {step<0?<div className="organizations-create__form"><label>Cliente em operação<select className="ds-input" value={customer} onChange={e=>{setCustomer(e.target.value);mark();}}><option value="">Selecione o cliente</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></label><label>Tipo de cadastro<select className="ds-input" value={kind} onChange={e=>{const k=e.target.value as EntryKind;setKind(k);setPayload(initialEntry(k));setSeed({});setDeferred([]);setSchedule(false);setVersion(v=>v+1);mark();}}>{Object.entries(entryKinds).filter(([k])=>k!=='distributor'||canUnit).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><Button disabled={!customer} onClick={()=>{mark();setStep(0);}}>Próximo</Button></div>:<>
 <p><strong>{customers.find(c=>c.id===customer)?.company_name}</strong> · {entryKinds[kind]}</p>
 <p>Etapa {step+2} de {steps.length+2}. Campos com * são obrigatórios para concluir o cadastro. É possível salvá-los para depois.</p>
 <form ref={form} key={version} onSubmit={e=>e.preventDefault()} noValidate>
 {steps.map((s,i)=><fieldset key={s.title} hidden={step!==i} disabled={busy} style={{border:0,padding:0,display:step===i?'block':'none'}}><legend>{s.title}</legend><p>{s.help}</p><div className="organizations-create__form">{s.fields?.map(field)}{s.special==='operating'?<SupplyOperatingFields value={supplySeed(seed)} busy={busy} onDirty={()=>mark()}/>:s.special==='terms'?<SupplyTermsFields value={supplySeed(seed)} busy={busy} onDirty={()=>mark()} onSchedule={setSchedule}/>:null}</div></fieldset>)}
 {step===steps.length?<div><p>Confira as etapas antes de salvar. O lançamento não será usado no motor de cálculo enquanto não passar pelo registro e pelas validações correspondentes.</p>{steps.map((s,i)=><article className="ds-card" key={s.title}><h4>{s.title}{deferred.includes(i)?' — preencher depois':''}</h4>{s.fields?.filter(f=>!f.show||f.show(payload)).map(f=><p key={f.key}><strong>{f.label}:</strong> {payload[f.key]==null||payload[f.key]===''?'Não informado':f.type==='unit'?units.find(u=>u.id===payload[f.key])?.name||'Unidade selecionada':f.options?.[String(payload[f.key])]||String(payload[f.key])}</p>)}{s.special==='operating'?<OperatingSummary value={supplySeed(payload)}/>:s.special==='terms'?<div>{payload.annualPrices?.length?payload.annualPrices.map((p,n)=><p key={n}>{p.startDate||'Início pendente'} a {p.endDate||'Término pendente'}: {p.pricePerMwh===''?'Preço pendente':'R$ '+p.pricePerMwh+'/MWh'} · {p.priceStatus==='BASE'?'Preço-base, reajuste pendente':'Preço final'}</p>):<p>Sem tabela anual. Preço único informado na etapa de volume.</p>}<p>Índice: {String(payload.adjustmentIndex||'Não informado')} · Data-base: {String(payload.adjustmentDate||'Não informada')}</p><p>{String(payload.adjustmentRule||'')}</p><p>Garantia: {String(payload.guaranteeInstitution||'Não informada')} · Valor: {payload.guaranteeAmount==null?'Não informado':'R$ '+String(payload.guaranteeAmount)}</p></div>:null}<Button type="button" variant="secondary" disabled={busy} onClick={()=>setStep(i)}>Revisar {s.title.toLocaleLowerCase()}</Button></article>)}{deferred.length?<Alert>As etapas deixadas para depois serão salvas como pendências.</Alert>:null}<Button type="button" disabled={busy} onClick={()=>void save()}>{busy?'Salvando...':'Salvar lançamento'}</Button></div>:<div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:24}}><Button type="button" variant="secondary" disabled={busy||step===0} onClick={()=>{setPayload(capture());setStep(n=>n-1);}}>Anterior</Button><Button type="button" disabled={busy} onClick={()=>move(step+1)}>Próximo</Button><Button type="button" variant="secondary" disabled={busy} onClick={()=>move(step+1,true)}>Preencher depois e pular</Button></div>}
 </form></>}
 <div style={{marginTop:16}}><Button variant="secondary" disabled={busy} onClick={()=>dirty?setCancel(true):close()}>Fechar lançamento</Button></div>{cancel?<div role="alert"><p>Há alterações não salvas. Para mantê-las, avance até a revisão e clique em Salvar lançamento.</p><Button variant="secondary" onClick={()=>setCancel(false)}>Continuar preenchendo</Button><Button onClick={close}>Descartar alterações não salvas</Button></div>:null}
 </Card>}
 </section>;
}
