'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {date,money} from './types';
type Row={id:string;value_unit?:string;version:number;effective_date:string;index_name:string;index_reference:string;rate_percent:number|null;notice_days:number;base_value:number;next_value:number|null;reason:string;created_at:string;created_by_name?:string};
export default function FeeAdjustments({kind,id,onDirty}:{kind:'management'|'services';id:string;onDirty:(v:boolean)=>void}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Row[]>([]),[write,setWrite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[loaded,setLoaded]=useState(false),[editing,setEditing]=useState(false);const lock=useRef(false),request=useRef('');
 const path='/api/v1/fee-adjustments/'+kind+'/'+id;
 useEffect(()=>{if(!open)return;let live=true;setBusy(true);apiRequest<{rows:Row[];canWrite:boolean}>(path).then(r=>{if(live){setRows(r.rows);setWrite(r.canWrite);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[open,path]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');const f=new FormData(e.currentTarget);try{if(!request.current)request.current=crypto.randomUUID();await apiRequest(path,{method:'POST',body:{effectiveDate:String(f.get('effectiveDate')),indexName:String(f.get('indexName')),ratePercent:f.get('ratePercent')===''?null:Number(f.get('ratePercent')),indexReference:String(f.get('indexReference')),noticeDays:Number(f.get('noticeDays')),reason:String(f.get('reason')),previousId:rows[0]?.id||null,requestId:request.current}});setEditing(false);onDirty(false);setMessage('Reajuste salvo com autor e justificativa. Histórico preservado.');const r=await apiRequest<{rows:Row[]}>(path);setRows(r.rows);}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.');}finally{setBusy(false);lock.current=false;}}
 const current=rows[0],today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),future=current&&(current.effective_date>today||current.next_value===null);
 return <section><Button type="button" variant="secondary" onClick={()=>setOpen(v=>!v)} disabled={editing||busy}>{open?'Fechar reajustes':'Reajuste anual e histórico'}</Button>{open?<div className="ds-card"><h4>Reajuste anual</h4>{error?<Alert variant="error">{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}{busy?<p>Processando...</p>:null}
 <p>O índice corrige {kind==='management'?'o valor fixo por unidade; o percentual do plano híbrido permanece igual':'o valor mensal ou o preço por MWh'}. Emissão fiscal e cobrança automática serão implantadas futuramente.</p>
 {current?<p>Próxima vigência registrada: {date(current.effective_date)} · {current.index_name} · Valor anterior: R$ {money(current.base_value)} · {current.next_value===null?'Próximo valor pendente da divulgação/conferência do índice':'Valor reajustado: R$ '+money(current.next_value)}{kind==='management'?' por unidade/mês. No híbrido, soma-se a parcela variável apurada.':' ('+(current.value_unit||'valor contratual')+').'}</p>:loaded?<p>Nenhum reajuste programado.</p>:null}
 {write&&loaded&&!editing?<Button type="button" onClick={()=>{setEditing(true);request.current='';}}>{future?'Corrigir programação com auditoria':'Programar reajuste anual'}</Button>:null}
 {editing?<form onSubmit={save} onChange={()=>{request.current='';onDirty(true);}}><fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:12}}>
 <Input label="Aplicar a partir de (primeiro dia da competência)" name="effectiveDate" type="date" required defaultValue={future?current.effective_date:undefined} readOnly={!!future}/>
 <Input label="Índice contratual (ex.: IPCA, IGP-M, INPC)" name="indexName" maxLength={80} minLength={2} required defaultValue={current?.index_name}/>
 <Input label="Percentual acumulado (%) — vazio enquanto pendente" name="ratePercent" type="number" step="0.000001" min="-100" max="1000" defaultValue={future?current.rate_percent??'':''}/>
 <Input label="Período de referência e fonte do índice" name="indexReference" maxLength={500} minLength={3} required defaultValue={future?current.index_reference:''}/>
 <Input label="Avisar o cliente com antecedência (dias)" name="noticeDays" type="number" min="1" max="365" step="1" defaultValue={current?.notice_days??30} required/>
 <Input label="Justificativa do cadastro ou correção" name="reason" minLength={3} maxLength={1000} required/>
 <p>A data deve estar dentro da vigência contratual, respeitar o intervalo anual e ser futura. O valor será calculado pelo servidor. Sem índice confirmado, a apuração a partir dessa competência ficará pendente.</p>
 <Button type="submit">Salvar programação auditada</Button><Button type="button" variant="secondary" onClick={()=>{setEditing(false);onDirty(false);}}>Cancelar edição</Button></fieldset></form>:null}
 <details><summary>Histórico de reajustes ({rows.length})</summary>{rows.map(r=><article key={r.id}><p>Versão {r.version} · {date(r.effective_date)} · {r.index_name} · {r.rate_percent===null?'Índice pendente':r.rate_percent+'%'} · {r.next_value===null?'Valor pendente':'R$ '+money(r.next_value)}</p><p>Fonte/período: {r.index_reference}. Aviso: {r.notice_days} dias antes.</p><p>{r.reason} · Autor: {r.created_by_name||'Nome não disponível'} · {new Date(r.created_at).toLocaleString('pt-BR')}</p></article>)}</details></div>:null}</section>;
}
