'use client';
import {comparisonMoney} from './comparison-view';
type Version={id:string;version:number;revision:number;source:string}|null;
export type SupplierCostsData={status:string;costs:string|null;credits:string|null;balance:string|null;baseInvoice:string|null;extraPurchases:string|null;version:Version;entries:{id:string;label:string;category:string;effect:string;amount:string;source:string}[];blockers:string[];warnings:string[]};
export type AdditionalCostsData={version:Version;scenarios:{scenario:string;status:string;costs:string|null;credits:string|null;balance:string|null;blockers:string[]}[];warnings:string[]};
const valid=(v:string|null)=>typeof v==='string'&&comparisonMoney(v)!=='Valor indisponível';
function Pending({blockers}:{blockers:string[]}){return <><strong className='ee-compare-pending'>Aguardando revisão</strong><ul>{blockers.map((b,i)=><li key={i}>{b}</li>)}</ul></>;}
export function SupplierCosts({data,onCorrect}:{data?:SupplierCostsData;onCorrect?:()=>void}){
 const ready=data?.status==='AVAILABLE'&&!data.blockers.length&&[data.balance,data.baseInvoice,data.extraPurchases,data.costs,data.credits].every(valid);
 return <section className='ee-distributor-subtotal' aria-label='Custo faturado do fornecedor'><h3>Fornecedor faturado · ACL</h3><p>Fatura regular e compras extras conferidas na competência. A referência contratual permanece separada.</p>{!data?<p>Memória do fornecedor ainda indisponível nesta resposta.</p>:<article className='ee-distributor-card'>{ready?<><strong className='ee-distributor-amount'>{comparisonMoney(data.balance!)}</strong><dl><div><dt>Faturas regulares, líquidas de créditos</dt><dd>{comparisonMoney(data.baseInvoice!)}</dd></div><div><dt>Compras extras, líquidas de créditos</dt><dd>{comparisonMoney(data.extraPurchases!)}</dd></div><div><dt>Custos registrados</dt><dd>{comparisonMoney(data.costs!)}</dd></div><div><dt>Créditos deduzidos</dt><dd>{comparisonMoney(data.credits!)}</dd></div></dl><details><summary>Faturas, compras extras e fontes</summary>{data.entries.map(e=><article key={e.id}><h4>{e.label}</h4><p>{e.category==='SUPPLIER_EXTRA_ENERGY'?'Compra extra':'Fatura regular'} · {e.effect==='CREDIT'?'Crédito':'Custo'} · {comparisonMoney(e.amount)}</p><p>{e.source}</p></article>)}</details></>:<Pending blockers={data.blockers}/>}<p>Fonte da versão: {data.version?.source||'Não disponível'}{data.version?' · Versão '+data.version.version+' · Revisão '+data.version.revision:''}</p></article>}{onCorrect?<button type='button' className='ee-compare-link' onClick={onCorrect}>Abrir custos mensais para conferir faturas e compras extras ↗</button>:null}{data?<details className='ee-distributor-rules'><summary>Escopo do custo faturado</summary>{data.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>:null}</section>;
}
export function AdditionalCosts({data}:{data?:AdditionalCostsData}){
 return <section className='ee-distributor-subtotal' aria-label='Saldo de custos adicionais'><h3>Saldo de custos adicionais</h3><p>Custos menos créditos. Fornecedor e compras extras não entram neste saldo.</p>{!data?<p>Consolidação ainda indisponível nesta resposta.</p>:<><div className='ee-compare-scenarios'>{['ACR','ACL'].map(s=>{const matches=data.scenarios.filter(v=>v.scenario===s),v=matches.length===1?matches[0]:undefined,ready=v&&['AVAILABLE','DECLARED_ZERO'].includes(v.status)&&!v.blockers.length&&[v.costs,v.credits,v.balance].every(valid);return <article className='ee-distributor-card' key={s}><h4>{s}</h4>{ready&&v?<><strong className='ee-distributor-amount'>{comparisonMoney(v.balance!)}</strong>{v.status==='DECLARED_ZERO'?<p>Ausência de custos adicionais declarada e validada.</p>:<dl><div><dt>Custos</dt><dd>{comparisonMoney(v.costs!)}</dd></div><div><dt>Créditos</dt><dd>{comparisonMoney(v.credits!)}</dd></div></dl>}</>:<Pending blockers={v?.blockers||['Memória indisponível.']}/>}</article>;})}</div><details className='ee-distributor-rules'><summary>Regra de consolidação dos custos adicionais</summary>{data.warnings.map((w,i)=><p key={i}>{w}</p>)}</details></>}</section>;
}
