'use client';
import AuditIdentity,{type Identity} from '../../components/AuditIdentity';
import {useEffect,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api';
import styles from './investments.module.css';
import {Button,Alert} from '@/app/components/ui';
import {useAuth} from '@/app/providers';
type Item={category:string;description:string;amount:string;date:string;classification:'ESTIMATED'|'REALIZED';source:string;documentId?:string};
type InvestmentVersion={auditIdentities?:Record<string,Identity>;id:string;version:number;payload_hash:string;validated:boolean;actor_name:string;created_at:string;body:{items:Item[];startMonth:string;total:string;note:string;sourceStudy?:{id:string}|null};validation?:{auditIdentities?:Record<string,Identity>;actor_name:string;note:string}|null};
type InvestmentWorkspace={canValidate:boolean;versions:InvestmentVersion[];documents:{id:string;name:string}[];studies:{id:string;version:number;amount:string}[]};
const blank=():Item=>({category:'MIGRATION',description:'',amount:'',date:'',classification:'ESTIMATED',source:''});
const names:Record<string,string>={MIGRATION:'Serviços de migração',CCEE:'Emolumentos CCEE',ADAPTATION:'Adequações',OTHER:'Outros'};
export default function Investments({customerId,units,onDirty}:{customerId:string;units:{id:string;customer_id?:string;name:string}[];onDirty:(v:boolean)=>void}){
 const {hasPermission}=useAuth(),[unit,setUnit]=useState(''),[data,setData]=useState<InvestmentWorkspace|null>(null),[items,setItems]=useState<Item[]>([blank()]),[start,setStart]=useState(''),[note,setNote]=useState(''),[sourceStudy,setSourceStudy]=useState(''),[validationNote,setValidationNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const generation=useRef(0),request=useRef<string|null>(null),validationRequest=useRef<string|null>(null);
 const canCreate=hasPermission('beb6ec90-8ba8-40ce-a156-aeef6cc75cce')&&hasPermission('9541a7bb-c20a-4c4d-9f4c-2185262c8e9c'),canValidate=hasPermission('fd8a932f-87c0-4f86-8389-9f30c50e95b7')&&Boolean(data?.canValidate);
 useEffect(()=>()=>{generation.current++;onDirty(false);},[onDirty]);
 const update=(f:()=>void)=>{request.current=null;f();onDirty(true);};
 const populate=(d:InvestmentWorkspace)=>{setData(d);const latest=d.versions?.[0];setItems(latest?.body.items??[blank()]);setStart(latest?.body.startMonth??'');setSourceStudy(latest?.body.sourceStudy?.id??'');setNote('');setValidationNote('');request.current=null;validationRequest.current=null;onDirty(false);};
 const load=async(id:string)=>{const n=++generation.current;setBusy(true);setError('');setData(null);setItems([blank()]);setStart('');try{const d=await apiRequest<InvestmentWorkspace>('/api/v1/contract-investments?'+new URLSearchParams({customerId,unitId:id}));if(n===generation.current)populate(d);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Consulta indisponível.');}finally{if(n===generation.current)setBusy(false);}};
 const save=async()=>{const n=generation.current;setBusy(true);setError('');request.current??=crypto.randomUUID();try{await apiRequest('/api/v1/contract-investments',{method:'POST',body:{customerId,unitId:unit,requestId:request.current,expectedVersion:data!.versions?.[0]?.version??0,startMonth:start,items,sourceStudyId:sourceStudy||undefined,note}});if(n===generation.current)await load(unit);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Cadastro indisponível.');}finally{if(n===generation.current)setBusy(false);}};
 const validate=async()=>{const n=generation.current,r=data!.versions[0];setBusy(true);setError('');validationRequest.current??=crypto.randomUUID();try{await apiRequest('/api/v1/contract-investments/'+r.id+'/validate',{method:'POST',body:{requestId:validationRequest.current,payloadHash:r.payload_hash,note:validationNote}});if(n===generation.current)await load(unit);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Validação indisponível.');}finally{if(n===generation.current)setBusy(false);}};
 return <section className={styles.workspace}><p>Registre investimentos da unidade. Cada salvamento cria uma versão para conferência. Alterações não modificam relatórios anteriores.</p><label>Unidade<select className="ds-input" disabled={busy} value={unit} onChange={e=>{if(items.some(i=>i.description)&&note&&!window.confirm('Descartar os campos não salvos desta unidade?'))return;setUnit(e.target.value);if(e.target.value)void load(e.target.value);else{generation.current++;setData(null);onDirty(false);}}}><option value="">Selecione a unidade</option>{units.filter(u=>!u.customer_id||u.customer_id===customerId).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>{busy?<p role="status">Consultando…</p>:null}{error?<Alert variant="error">{error}</Alert>:null}{data?<><p>Início do acompanhamento financeiro: deve corresponder ao primeiro mês de economia após a migração. O ROI utilizará as economias publicadas desde esse mês até o corte do relatório.</p><label>Início do acompanhamento<input className="ds-input" type="month" disabled={busy||!canCreate} value={start} onChange={e=>update(()=>setStart(e.target.value))}/></label>
 {data.studies.length?<label>Importar investimento estimado do estudo ACL<select className="ds-input" disabled={busy||!canCreate} value={sourceStudy} onChange={e=>{const s=data.studies.find(v=>v.id===e.target.value);update(()=>{setSourceStudy(e.target.value);if(s&&!items.some(i=>i.source.includes(s.id)))setItems(a=>[...a.filter(i=>i.description||i.amount),{...blank(),description:'Investimento estimado no estudo ACL',amount:s.amount,source:'Estudo ACL '+s.id+' · versão '+s.version+' · estimativa a conferir.'}]);});}}><option value="">Sem importação</option>{data.studies.map(s=><option value={s.id} key={s.id}>Estudo v{s.version} · R$ {s.amount}</option>)}</select></label>:<p>Nenhum estudo ACL revisado com investimento disponível nesta unidade. O cadastro manual continua disponível.</p>}
 {items.map((i,index)=><fieldset className={styles.item} key={index} disabled={busy||!canCreate}><legend>Investimento {index+1}</legend><div className={styles.grid}><label>Categoria<select className="ds-input" value={i.category} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,category:e.target.value}:v)))}>{Object.entries(names).map(([v,name])=><option value={v} key={v}>{name}</option>)}</select></label><label>Descrição<input className="ds-input" maxLength={160} value={i.description} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,description:e.target.value}:v)))}/></label><label>Valor R$<input className="ds-input" inputMode="decimal" value={i.amount} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,amount:e.target.value.replace(',','.')}:v)))}/></label><label>Data<input className="ds-input" type="date" value={i.date} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,date:e.target.value}:v)))}/></label><label>Classificação<select className="ds-input" value={i.classification} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,classification:e.target.value as Item['classification']}:v)))}><option value="ESTIMATED">Estimado — exige conferência</option><option value="REALIZED">Realizado — com evidência</option></select></label><label>Documento da unidade<select className="ds-input" value={i.documentId??''} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,documentId:e.target.value||undefined}:v)))}><option value="">Selecione a evidência</option>{data.documents.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label></div><label>Fonte e justificativa<textarea className="ds-input" maxLength={500} value={i.source} onChange={e=>update(()=>setItems(a=>a.map((v,n)=>n===index?{...v,source:e.target.value}:v)))}/></label>{items.length>1?<Button variant="secondary" onClick={()=>update(()=>setItems(a=>a.filter((_,n)=>n!==index)))}>Remover desta nova versão</Button>:null}</fieldset>)}
 <label>Justificativa da versão<textarea className="ds-input" maxLength={1000} value={note} disabled={busy||!canCreate} onChange={e=>update(()=>setNote(e.target.value))}/></label><div className={styles.actions}><Button variant="secondary" disabled={busy||!canCreate||items.length>=30} onClick={()=>update(()=>setItems(a=>[...a,blank()]))}>Adicionar investimento</Button><Button disabled={busy||!canCreate||!start||note.trim().length<20} onClick={()=>void save()}>Salvar versão para conferência</Button></div>
 {data.versions[0]&&!data.versions[0].validated?<><label>Justificativa de validação<textarea className="ds-input" value={validationNote} maxLength={1000} disabled={busy||!canValidate} onChange={e=>{validationRequest.current=null;setValidationNote(e.target.value);}}/></label><Button disabled={busy||!canValidate||validationNote.trim().length<20} onClick={()=>void validate()}>Validar investimentos da versão salva</Button><p>A validação refere-se aos dados salvos, não aos campos que você ainda está editando. Somente Gestor ou Administrador autorizado pode validar.</p></>:null}
 <h3>Versões preservadas</h3>{data.versions.map(v=><details key={v.id}><summary>v{v.version} · {v.validated?'Validada':'Aguardando validação'} · R$ {v.body.total}</summary><AuditIdentity historical identity={v.auditIdentities?.created_by} recordedName={v.actor_name}/><p>{new Date(v.created_at).toLocaleString('pt-BR')} · {v.body.note}</p><p>{v.body.items.map((i:Item)=>i.description+' — R$ '+i.amount+' ('+i.classification+')').join('; ')}</p>{v.validation?<div><AuditIdentity historical title="Validador" identity={v.validation.auditIdentities?.validated_by} recordedName={v.validation.actor_name}/><p>{v.validation.note}</p></div>:null}</details>)}</>:null}</section>;
}
