'use client';
import {useState,FormEvent} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {Unit} from './types';
import type {CorrectionContext} from './preparation-navigation';
import AuditAuthor from './AuditAuthor';
type Contract={id:string;customer_id:string;contract_number:string;remuneration_model?:string;fixed_fee_monthly?:number};
type Row={id:string;version:number;fixed_fee_basis:string;allocations:{consumerUnitId:string;percentage:string}[];source:string;reason:string;created_by:string;created_by_name?:string|null;created_at:string};
export default function ManagementAllocation({customerId,units,contracts,onDirty,initialContext}:{initialContext?:CorrectionContext;customerId:string;units:Unit[];contracts:Contract[];onDirty:(v:boolean)=>void}) {
 const [contractId,setContract]=useState(initialContext?.recordId||''),[month,setMonth]=useState(initialContext?.month||''),[rows,setRows]=useState<Row[]|null>(null),[canConfigure,setCan]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editing,setEditing]=useState(false),[shares,setShares]=useState<Record<string,string>>({}),[source,setSource]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const contract=contracts.find(c=>c.id===contractId&&c.customer_id===customerId),hybrid=contract?.remuneration_model==='HYBRID',available=units.filter(u=>u.customer_id===customerId);
 function clear(){setRows(null);setError('');}function close(){setEditing(false);onDirty(false);}
 async function load(e:FormEvent){e.preventDefault();setBusy(true);setError('');setRows(null);try{const r=await apiRequest<{rows:Row[];canConfigure:boolean}>('/api/v1/management-fee-allocations?contractId='+encodeURIComponent(contractId)+'&month='+month);setRows(r.rows);setCan(r.canConfigure);}catch(e){setError(e instanceof Error?e.message:'Consulta indisponível.');}finally{setBusy(false);}}
 function start(){setShares(Object.fromEntries(available.map(u=>[u.id,rows?.[0]?.allocations.find(a=>a.consumerUnitId===u.id)?.percentage??''])));setSource(rows?.[0]?.source??'');setReason('');setConfirmed(false);setEditing(true);onDirty(true);}
 async function save(e:FormEvent){e.preventDefault();if(!confirmed||busy)return;setBusy(true);setError('');try{const row=await apiRequest<Row>('/api/v1/management-fee-allocations',{method:'POST',body:{contractId,month,fixedFeeBasis:'PER_UNIT',allocations:hybrid?available.map(u=>({consumerUnitId:u.id,percentage:shares[u.id]})):[],source,reason,...(rows?.[0]?{previousId:rows[0].id}:{})}});setRows(old=>[row,...(old||[])]);close();}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar.');}finally{setBusy(false);}}
 if(!customerId)return null;
 return <Card title='Regra mensal dos honorários'><p>O fixo é cobrado integralmente por unidade. No híbrido, o percentual usa a economia consolidada do cliente após os demais custos e antes dos honorários; apenas a parcela variável é rateada. Confirme a regra por competência para evitar reinterpretar registros antigos.</p>{error?<Alert variant='error'>{error}</Alert>:null}<form onSubmit={load}><fieldset disabled={busy||editing} className='organizations-create__form'><label>Contrato de honorários<select className='ds-input' required value={contractId} onChange={e=>{setContract(e.target.value);clear();}}><option value=''>Selecione</option>{contracts.filter(c=>c.customer_id===customerId).map(c=><option key={c.id} value={c.id}>{c.contract_number}</option>)}</select></label><Input label='Competência dos honorários' type='month' min='2000-01' max='2199-12' required value={month} onChange={e=>{setMonth(e.target.value);clear();}}/><Button type='submit'>Consultar regra mensal</Button></fieldset></form>
 {rows&&!editing&&canConfigure?<Button disabled={busy} onClick={start}>{rows.length?'Registrar correção da regra':'Configurar regra da competência'}</Button>:null}
 {editing?<form onSubmit={save}><fieldset disabled={busy} className='organizations-create__form'><p>Contrato {contract?.contract_number} · {month} · fixo cadastrado: R$ {String(contract?.fixed_fee_monthly??'não informado')} por unidade.</p><label><input type='checkbox' required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo a cobrança integral do fixo em cada unidade, sem rateio.</label>{hybrid?<><h3>Rateio somente da parcela variável</h3><p>Informe todas as unidades, inclusive zero quando não participarem. O total deve ser exatamente 100%. O fixo permanece integral mesmo quando o rateio variável for zero.</p>{available.map(u=><Input key={u.id} label={'Percentual variável · '+u.name+' — '+u.consumer_unit_number} required inputMode='decimal' pattern='(100([.]0{1,4})?|[0-9]{1,2}([.][0-9]{1,4})?)' value={shares[u.id]??''} onChange={e=>setShares(s=>({...s,[u.id]:e.target.value.replace(',','.')}))}/>)}</>:null}<Input label='Fonte e justificativa da regra mensal' required maxLength={2000} value={source} onChange={e=>setSource(e.target.value)}/>{rows?.length?<Input label='Motivo da correção da regra' required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/>:null}<p>Ao confirmar, esta versão será preservada. Correções exigem uma nova versão. A confirmação não emite cobrança nem publica resultado financeiro.</p><Button type='submit'>Confirmar regra mensal</Button><Button type='button' variant='secondary' onClick={close}>Cancelar regra mensal</Button></fieldset></form>:null}
 {rows?.map(r=><article className='ds-card' key={r.id}><h3>Regra mensal · versão {r.version}{rows[0].id===r.id?' · Atual':''}</h3><p>Fixo integral por unidade. {r.allocations.length?'Rateio da parcela variável:':'Modelo fixo: sem rateio.'}</p>{r.allocations.map(a=><p key={a.consumerUnitId}>{available.find(u=>u.id===a.consumerUnitId)?.name||'Unidade anteriormente vinculada'}: {a.percentage}%</p>)}<p>Fonte: {r.source}</p>{r.reason?<p>Correção: {r.reason}</p>:null}<p>Confirmado por <AuditAuthor id={r.created_by} name={r.created_by_name}/> · {new Date(r.created_at).toLocaleString('pt-BR')}</p></article>)}
 </Card>;
}
