'use client';
import {FormEvent,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {Unit,PERM} from './types';
const fields={"consumptionTotal":"Consumo total (kWh)","consumptionPeak":"Consumo na ponta (kWh)","consumptionOffPeak":"Consumo fora ponta (kWh)","demandSingle":"Demanda medida única (kW)","demandPeak":"Demanda medida na ponta (kW)","demandOffPeak":"Demanda medida fora ponta (kW)","reactiveTotal":"Energia reativa excedente (kVArh)"};
type Measurements=Record<keyof typeof fields,string|null>;
type Row={id:string;consumer_unit_id:string;month:string;version:number;revision:number;previous_id:string|null;status:'DRAFT'|'VALIDATED';measurements:Measurements;source_reference:string;notes:string;correction_reason:string;created_by:string;updated_by:string;validated_by:string|null;validated_at:string|null;updated_at:string};
type Event={id:string;revision:number;action:string;recorded_at:string;snapshot:Row};
type Editor={id?:string;revision?:number;previousId:string|null;measurements:Measurements;sourceReference:string;notes:string;correctionReason:string};
const blank=()=>Object.fromEntries(Object.keys(fields).map(k=>[k,null])) as Measurements;
export default function MonthlyInputs({customerId,units,onDirty}:{customerId:string;units:Unit[];onDirty:(v:boolean)=>void}){
 const {hasPermission}=useAuth();const [unitId,setUnit]=useState(''),[year,setYear]=useState(''),[month,setMonth]=useState('');
 const [rows,setRows]=useState<Row[]|null>(null),[canValidate,setValidate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[discard,setDiscard]=useState(false),[confirm,setConfirm]=useState<Row|null>(null),[history,setHistory]=useState<{id:string;events:Event[]}|null>(null);
 const period=year+'-'+month,available=units.filter(u=>u.customer_id===customerId),create=hasPermission(PERM.create),update=hasPermission(PERM.update);
 function clearResults(){setRows(null);setError('');setMessage('');setConfirm(null);setHistory(null);}
 function close(){setEditor(null);setDiscard(false);onDirty(false);}
 function patch(p:Partial<Editor>){setEditor(d=>d?{...d,...p}:d);onDirty(true);}
 async function load(e:FormEvent){e.preventDefault();setError('');setMessage('');setRows(null);setConfirm(null);setHistory(null);if(!unitId||!/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(period)){setError('Selecione unidade, mês e ano entre 2000 e 2199.');return;}setBusy(true);try{const r=await apiRequest<{rows:Row[];canValidate:boolean}>('/api/v1/calculation-monthly-inputs?consumerUnitId='+encodeURIComponent(unitId)+'&month='+period);setRows(r.rows);setValidate(r.canValidate);}catch(e){setError(e instanceof Error?e.message:'Falha na consulta.');}finally{setBusy(false);}}
 function start(row?:Row){setEditor(row?{...(row.status==='DRAFT'?{id:row.id,revision:row.revision}:{}),previousId:row.status==='DRAFT'?row.previous_id:row.id,measurements:{...row.measurements},sourceReference:row.source_reference,notes:row.notes,correctionReason:row.status==='DRAFT'?row.correction_reason:''}:{previousId:null,measurements:blank(),sourceReference:'',notes:'',correctionReason:''});onDirty(true);setConfirm(null);setHistory(null);setError('');setMessage('');}
 async function save(e:FormEvent){e.preventDefault();if(!editor||busy)return;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Row>('/api/v1/calculation-monthly-inputs'+(editor.id?'/'+editor.id:''),{method:editor.id?'PUT':'POST',body:{consumerUnitId:unitId,month:period,measurements:editor.measurements,sourceReference:editor.sourceReference,notes:editor.notes,correctionReason:editor.correctionReason,previousId:editor.previousId,...(editor.id?{revision:editor.revision}:{})}});setRows(old=>[row,...(old||[]).filter(r=>r.id!==row.id)].sort((a,b)=>b.version-a.version));close();setMessage('Rascunho salvo. Confira as medições e a fonte antes da validação.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 async function validate(){if(!confirm||busy)return;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Row>('/api/v1/calculation-monthly-inputs/'+confirm.id+'/validate',{method:'POST',body:{revision:confirm.revision}});setRows(old=>(old||[]).map(r=>r.id===row.id?row:r));setConfirm(null);setMessage('Versão validada e preservada. Isso valida as medições informadas; não publica uma apuração financeira.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível validar.');}finally{setBusy(false);}}
 async function audit(id:string){setBusy(true);setError('');try{setHistory({id,events:await apiRequest<Event[]>('/api/v1/calculation-monthly-inputs/'+id+'/events')});}catch(e){setError(e instanceof Error?e.message:'Histórico indisponível.');}finally{setBusy(false);}}
 const details=(r:Row)=><><dl>{Object.entries(fields).map(([k,l])=><div key={k}><dt>{l}</dt><dd>{r.measurements[k as keyof Measurements]??'Não informado'}</dd></div>)}</dl><p style={{whiteSpace:'pre-wrap'}}>Fonte: {r.source_reference}</p><p style={{whiteSpace:'pre-wrap'}}>{r.notes}</p>{r.correction_reason?<p>Motivo da correção: {r.correction_reason}</p>:null}<p>Autor: {r.created_by} · Última alteração: {r.updated_by} · {new Date(r.updated_at).toLocaleString('pt-BR')}</p>{r.validated_at?<p>Validado por {r.validated_by} em {new Date(r.validated_at).toLocaleString('pt-BR')}</p>:null}</>;
 if(!customerId)return <p>Selecione um cliente para consultar os dados mensais de suas unidades.</p>;
 return <section className='backoffice-page'><h2>Dados mensais para apuração</h2><p>Registre as medições conferidas na fatura ou relatório de medição. Campos vazios significam não informado. Esta etapa não calcula custos nem economia.</p>
 {error?<Alert variant='error'>{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 <Card title='Unidade e competência dos dados'><form onSubmit={load}><fieldset disabled={busy||!!editor} className='organizations-create__form'>
 <label>Unidade dos dados mensais<select className='ds-input' required value={unitId} onChange={e=>{setUnit(e.target.value);clearResults();}}><option value=''>Selecione</option>{available.map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label>
 <label>Mês dos dados mensais<select className='ds-input' required value={month} onChange={e=>{setMonth(e.target.value);clearResults();}}><option value=''>Selecione</option>{['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'].map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select></label>
 <Input label='Ano dos dados mensais' required inputMode='numeric' pattern='(20|21)[0-9]{2}' maxLength={4} value={year} onChange={e=>{setYear(e.target.value);clearResults();}}/>
 <Button type='submit'>{busy?'Aguarde...':'Consultar dados mensais'}</Button></fieldset></form></Card>
 {rows&&!editor&&create&&!rows.some(r=>r.status==='DRAFT')?<Button disabled={busy} onClick={()=>start(rows[0])}>{rows.length?'Criar versão corrigida':'Novo rascunho mensal'}</Button>:null}
 {editor?<Card title={editor.id?'Editar medições do rascunho':editor.previousId?'Nova versão das medições':'Novo rascunho mensal'}><form onSubmit={save}><fieldset disabled={busy} className='organizations-create__form'><p>{available.find(u=>u.id===unitId)?.name} · {period}</p><p>Informe consumo em kWh, demanda medida em kW e energia reativa excedente em kVArh. Demanda contratada permanece no cadastro da distribuidora. Use demanda única ou por posto.</p>
 {Object.entries(fields).map(([k,label])=><Input key={k} label={label} inputMode='decimal' maxLength={19} pattern='(0|[1-9][0-9]{0,11})([.][0-9]{1,6})?' placeholder='Não informado' value={editor.measurements[k as keyof Measurements]??''} onChange={e=>patch({measurements:{...editor.measurements,[k]:e.target.value===''?null:e.target.value.replace(',','.')}})}/>)}
 <label>Fonte e evidência das medições<textarea className='ds-input' required maxLength={2000} placeholder='Identifique fatura/relatório, número, período de leitura e páginas dos valores.' value={editor.sourceReference} onChange={e=>patch({sourceReference:e.target.value})}/></label>
 <label>Observações dos dados mensais<textarea className='ds-input' maxLength={2000} value={editor.notes} onChange={e=>patch({notes:e.target.value})}/></label>
 {editor.previousId?<label>Justificativa da nova versão<textarea className='ds-input' required maxLength={2000} value={editor.correctionReason} onChange={e=>patch({correctionReason:e.target.value})}/></label>:null}
 <Button type='submit'>Salvar dados mensais em rascunho</Button><Button type='button' variant='secondary' onClick={()=>setDiscard(true)}>Cancelar preenchimento mensal</Button>
 {discard?<div role='alert'><p>Descartar somente os campos não salvos deste formulário?</p><Button type='button' onClick={close}>Descartar preenchimento mensal</Button><Button type='button' variant='secondary' onClick={()=>setDiscard(false)}>Continuar preenchimento mensal</Button></div>:null}
 </fieldset></form></Card>:null}
 {rows?<Card title={'Versões da competência '+period}>{!rows.length?<p>Nenhuma versão cadastrada para esta unidade e competência.</p>:rows.map((r,i)=><article className='ds-card' key={r.id}><h3>Versão {r.version} · {r.status==='DRAFT'?'Rascunho':'Validada'}{i===0?' · Mais recente':''}</h3><p>{r.status==='VALIDATED'?'Conteúdo preservado. Correções exigem uma nova versão.':'Ainda não validada para a apuração.'}</p>{details(r)}
 {r.status==='DRAFT'&&update?<Button disabled={busy||!!editor} variant='secondary' onClick={()=>start(r)}>Editar medições</Button>:null}
 {r.status==='DRAFT'&&update&&canValidate?<Button disabled={busy||!!editor} onClick={()=>setConfirm(r)}>Revisar e validar medições</Button>:null}
 <Button variant='secondary' disabled={busy||!!editor} onClick={()=>void audit(r.id)}>Histórico das medições</Button>
 {confirm?.id===r.id?<div role='alert'><p>Confirme que conferiu as medições acima com a fonte. A versão ficará imutável; dados não informados continuarão ausentes e poderão impedir o cálculo.</p><Button disabled={busy} onClick={()=>void validate()}>Confirmar validação das medições</Button><Button disabled={busy} variant='secondary' onClick={()=>setConfirm(null)}>Cancelar validação</Button></div>:null}
 {history?.id===r.id?<details open><summary>Histórico de alterações das medições</summary>{history.events.map(e=><details key={e.id}><summary>Revisão {e.revision} · {{CREATED:'Criado',UPDATED:'Atualizado',VALIDATED:'Validado'}[e.action]||e.action} · {new Date(e.recorded_at).toLocaleString('pt-BR')}</summary>{details(e.snapshot)}</details>)}</details>:null}
 </article>)}</Card>:null}
 <p>A validação das medições é feita por Gestor ou Administrador da organização. Custos, tributos, dados CCEE e resultados financeiros serão tratados nas etapas seguintes.</p>
 </section>;
}
