'use client';
import {FormEvent,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {Unit,PERM} from './types';
const categories={CCEE:'CCEE',EXPOSURE:'Exposição / curto prazo',CHARGE:'Encargos',OTHER:'Outros ajustes'};
const taxes={UNSPECIFIED:'Pendente de classificação',INCLUDED:'Tributos incluídos no valor',EXCLUDED:'Tributos não incluídos',NOT_APPLICABLE:'Não se aplica'};
type CostItem={id:string;label:string;category:string;scenario:string;effect:string;amount:string;source:string;taxTreatment:string};
type Costs={noCosts:boolean;items:CostItem[]};
type Row={id:string;consumer_unit_id:string;month:string;version:number;revision:number;previous_id:string|null;status:'DRAFT'|'VALIDATED';costs:Costs;source_reference:string;notes:string;correction_reason:string;created_by:string;updated_by:string;validated_by:string|null;validated_at:string|null;updated_at:string};
type Event={id:string;revision:number;action:string;recorded_at:string;snapshot:Row};
type Editor={id?:string;revision?:number;previousId:string|null;costs:Costs;sourceReference:string;notes:string;correctionReason:string};
const blank=():Costs=>({noCosts:false,items:[]});
export default function MonthlyCosts({customerId,units,onDirty}:{customerId:string;units:Unit[];onDirty:(v:boolean)=>void}){
 const {hasPermission}=useAuth();const [unitId,setUnit]=useState(''),[year,setYear]=useState(''),[month,setMonth]=useState('');
 const [rows,setRows]=useState<Row[]|null>(null),[canValidate,setValidate]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editor,setEditor]=useState<Editor|null>(null),[discard,setDiscard]=useState(false),[confirm,setConfirm]=useState<Row|null>(null),[history,setHistory]=useState<{id:string;events:Event[]}|null>(null);
 const period=year+'-'+month,available=units.filter(u=>u.customer_id===customerId),create=hasPermission(PERM.create),update=hasPermission(PERM.update);
 function clearResults(){setRows(null);setError('');setMessage('');setConfirm(null);setHistory(null);}
 function close(){setEditor(null);setDiscard(false);onDirty(false);}
 function patch(p:Partial<Editor>){setEditor(d=>d?{...d,...p}:d);onDirty(true);}
 function patchItem(index:number,p:Partial<CostItem>){if(editor)patch({costs:{...editor.costs,items:editor.costs.items.map((item,i)=>i===index?{...item,...p}:item)}});}
 async function load(e:FormEvent){e.preventDefault();setError('');setMessage('');setRows(null);setConfirm(null);setHistory(null);if(!unitId||!/^(20|21)\d{2}-(0[1-9]|1[0-2])$/.test(period)){setError('Selecione unidade, mês e ano entre 2000 e 2199.');return;}setBusy(true);try{const r=await apiRequest<{rows:Row[];canValidate:boolean}>('/api/v1/calculation-monthly-costs?consumerUnitId='+encodeURIComponent(unitId)+'&month='+period);setRows(r.rows);setValidate(r.canValidate);}catch(e){setError(e instanceof Error?e.message:'Falha na consulta.');}finally{setBusy(false);}}
 function start(row?:Row){setEditor(row?{...(row.status==='DRAFT'?{id:row.id,revision:row.revision}:{}),previousId:row.status==='DRAFT'?row.previous_id:row.id,costs:{...row.costs,items:row.costs.items.map(i=>({...i}))},sourceReference:row.source_reference,notes:row.notes,correctionReason:row.status==='DRAFT'?row.correction_reason:''}:{previousId:null,costs:blank(),sourceReference:'',notes:'',correctionReason:''});onDirty(true);setConfirm(null);setHistory(null);setError('');setMessage('');}
 async function save(e:FormEvent){e.preventDefault();if(!editor||busy)return;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Row>('/api/v1/calculation-monthly-costs'+(editor.id?'/'+editor.id:''),{method:editor.id?'PUT':'POST',body:{consumerUnitId:unitId,month:period,costs:editor.costs,sourceReference:editor.sourceReference,notes:editor.notes,correctionReason:editor.correctionReason,previousId:editor.previousId,...(editor.id?{revision:editor.revision}:{})}});setRows(old=>[row,...(old||[]).filter(r=>r.id!==row.id)].sort((a,b)=>b.version-a.version));close();setMessage('Rascunho salvo. Confira os custos e a fonte antes da validação.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 async function validate(){if(!confirm||busy)return;setBusy(true);setError('');setMessage('');try{const row=await apiRequest<Row>('/api/v1/calculation-monthly-costs/'+confirm.id+'/validate',{method:'POST',body:{revision:confirm.revision}});setRows(old=>(old||[]).map(r=>r.id===row.id?row:r));setConfirm(null);setMessage('Versão validada e preservada. Isso valida os custos informados; não publica uma apuração financeira.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível validar.');}finally{setBusy(false);}}
 async function audit(id:string){setBusy(true);setError('');try{setHistory({id,events:await apiRequest<Event[]>('/api/v1/calculation-monthly-costs/'+id+'/events')});}catch(e){setError(e instanceof Error?e.message:'Histórico indisponível.');}finally{setBusy(false);}}
 const details=(r:Row)=><>{r.costs.noCosts?<p>Revisado: sem custos ou créditos adicionais nesta competência.</p>:r.costs.items.map(i=><article className='ds-card' key={i.id}><h4>{i.label}</h4><p>{categories[i.category as keyof typeof categories]} · {i.scenario} · {i.effect==='COST'?'Custo':'Crédito'} · R$ {i.amount}</p><p>{taxes[i.taxTreatment as keyof typeof taxes]}</p><p>Fonte do lançamento: {i.source}</p></article>)}<p style={{whiteSpace:'pre-wrap'}}>Fonte: {r.source_reference}</p><p style={{whiteSpace:'pre-wrap'}}>{r.notes}</p>{r.correction_reason?<p>Motivo da correção: {r.correction_reason}</p>:null}<p>Autor: {r.created_by} · Última alteração: {r.updated_by} · {new Date(r.updated_at).toLocaleString('pt-BR')}</p>{r.validated_at?<p>Validado por {r.validated_by} em {new Date(r.validated_at).toLocaleString('pt-BR')}</p>:null}</>;
 if(!customerId)return <p>Selecione um cliente para consultar os custos mensais de suas unidades.</p>;
 return <section className='backoffice-page'><h2>Custos mensais para apuração</h2><p>Registre custos e créditos adicionais atribuídos a esta unidade e competência. Não repita energia, tarifas ou honorários já previstos nos contratos. Esta etapa não calcula economia nem importa dados da CCEE.</p>
 {error?<Alert variant='error'>{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}
 <Card title='Unidade e competência dos dados'><form onSubmit={load}><fieldset disabled={busy||!!editor} className='organizations-create__form'>
 <label>Unidade dos custos mensais<select className='ds-input' required value={unitId} onChange={e=>{setUnit(e.target.value);clearResults();}}><option value=''>Selecione</option>{available.map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label>
 <label>Mês dos custos mensais<select className='ds-input' required value={month} onChange={e=>{setMonth(e.target.value);clearResults();}}><option value=''>Selecione</option>{['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'].map((m,i)=><option key={m} value={String(i+1).padStart(2,'0')}>{m}</option>)}</select></label>
 <label>Ano dos custos mensais<select className='ds-input' required autoComplete='off' value={year} onChange={e=>{setYear(e.target.value);clearResults();}}><option value=''>Selecione o ano</option>{Array.from({length:200},(_,i)=>String(2000+i)).map(y=><option key={y} value={y}>{y}</option>)}</select></label>
 <Button type='submit'>{busy?'Aguarde...':'Consultar custos mensais'}</Button></fieldset></form></Card>
 {rows&&!editor&&create&&!rows.some(r=>r.status==='DRAFT')?<Button disabled={busy} onClick={()=>start(rows[0])}>{rows.length?'Criar versão corrigida':'Novo rascunho mensal'}</Button>:null}
 {editor?<Card title={editor.id?'Editar custos do rascunho':editor.previousId?'Nova versão dos custos':'Novo rascunho mensal'}><form onSubmit={save}><fieldset disabled={busy} className='organizations-create__form'><p>{available.find(u=>u.id===unitId)?.name} · {period}</p><p>Informe o valor em reais conforme o documento de origem. Identifique tributos incluídos ou excluídos; não há gross-up automático. Custos do cliente ou da organização precisam de rateio justificado antes do lançamento por unidade.</p>
 <label><input type='checkbox' checked={editor.costs.noCosts} disabled={editor.costs.items.length>0} onChange={e=>patch({costs:{...editor.costs,noCosts:e.target.checked}})}/> Revisei e não há custos ou créditos adicionais nesta competência</label>
 {editor.costs.items.map((item,index)=><fieldset className='ds-card' key={item.id}><legend>Lançamento {index+1}</legend>
 <Input label={'Descrição do lançamento '+(index+1)} required maxLength={200} value={item.label} onChange={e=>patchItem(index,{label:e.target.value})}/>
 <label>Categoria<select className='ds-input' value={item.category} onChange={e=>patchItem(index,{category:e.target.value})}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Cenário<select className='ds-input' value={item.scenario} onChange={e=>patchItem(index,{scenario:e.target.value})}><option value='ACL'>ACL — Mercado Livre</option><option value='ACR'>ACR — Mercado Regulado</option></select></label>
 <label>Natureza<select className='ds-input' value={item.effect} onChange={e=>patchItem(index,{effect:e.target.value})}><option value='COST'>Custo</option><option value='CREDIT'>Crédito</option></select></label>
 <Input label={'Valor em reais do lançamento '+(index+1)} required inputMode='decimal' maxLength={15} pattern='(0|[1-9][0-9]{0,11})([.][0-9]{1,2})?' value={item.amount} onChange={e=>patchItem(index,{amount:e.target.value.replace(',','.')})}/>
 <label>Tratamento tributário<select className='ds-input' value={item.taxTreatment} onChange={e=>patchItem(index,{taxTreatment:e.target.value})}>{Object.entries(taxes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <Input label={'Fonte do lançamento '+(index+1)} required maxLength={1000} value={item.source} onChange={e=>patchItem(index,{source:e.target.value})}/>
 <Button type='button' variant='secondary' onClick={()=>patch({costs:{...editor.costs,items:editor.costs.items.filter((_,i)=>i!==index)}})}>Remover lançamento {index+1} do rascunho</Button>
 </fieldset>)}
 <Button type='button' disabled={editor.costs.noCosts||editor.costs.items.length>=100} onClick={()=>patch({costs:{...editor.costs,items:[...editor.costs.items,{id:crypto.randomUUID(),label:'',category:'CCEE',scenario:'ACL',effect:'COST',amount:'',source:'',taxTreatment:'UNSPECIFIED'}]}})}>Adicionar lançamento</Button>
 <label>Fonte e evidência dos custos<textarea className='ds-input' required maxLength={2000} placeholder='Identifique os documentos revisados, o critério de rateio e a justificativa caso não haja custos adicionais.' value={editor.sourceReference} onChange={e=>patch({sourceReference:e.target.value})}/></label>
 <label>Observações dos custos mensais<textarea className='ds-input' maxLength={2000} value={editor.notes} onChange={e=>patch({notes:e.target.value})}/></label>
 {editor.previousId?<label>Justificativa da nova versão<textarea className='ds-input' required maxLength={2000} value={editor.correctionReason} onChange={e=>patch({correctionReason:e.target.value})}/></label>:null}
 <Button type='submit'>Salvar custos mensais em rascunho</Button><Button type='button' variant='secondary' onClick={()=>setDiscard(true)}>Cancelar preenchimento mensal</Button>
 {discard?<div role='alert'><p>Descartar somente os campos não salvos deste formulário?</p><Button type='button' onClick={close}>Descartar preenchimento mensal</Button><Button type='button' variant='secondary' onClick={()=>setDiscard(false)}>Continuar preenchimento mensal</Button></div>:null}
 </fieldset></form></Card>:null}
 {rows?<Card title={'Versões da competência '+period}>{!rows.length?<p>Nenhuma versão cadastrada para esta unidade e competência.</p>:rows.map((r,i)=><article className='ds-card' key={r.id}><h3>Versão {r.version} · {r.status==='DRAFT'?'Rascunho':'Validada'}{i===0?' · Mais recente':''}</h3><p>{r.status==='VALIDATED'?'Conteúdo preservado. Correções exigem uma nova versão.':'Ainda não validada para a apuração.'}</p>{details(r)}
 {r.status==='DRAFT'&&update?<Button disabled={busy||!!editor} variant='secondary' onClick={()=>start(r)}>Editar custos</Button>:null}
 {r.status==='DRAFT'&&update&&canValidate?<Button disabled={busy||!!editor} onClick={()=>setConfirm(r)}>Revisar e validar custos</Button>:null}
 <Button variant='secondary' disabled={busy||!!editor} onClick={()=>void audit(r.id)}>Histórico dos custos</Button>
 {confirm?.id===r.id?<div role='alert'><p>Confirme que conferiu os custos e créditos acima com a fonte. A versão ficará imutável; dados não informados continuarão ausentes e poderão impedir o cálculo.</p><Button disabled={busy} onClick={()=>void validate()}>Confirmar validação dos custos</Button><Button disabled={busy} variant='secondary' onClick={()=>setConfirm(null)}>Cancelar validação</Button></div>:null}
 {history?.id===r.id?<details open><summary>Histórico de alterações dos custos</summary>{history.events.map(e=><details key={e.id}><summary>Revisão {e.revision} · {{CREATED:'Criado',UPDATED:'Atualizado',VALIDATED:'Validado'}[e.action]||e.action} · {new Date(e.recorded_at).toLocaleString('pt-BR')}</summary>{details(e.snapshot)}</details>)}</details>:null}
 </article>)}</Card>:null}
 <p>A validação dos custos é feita por Gestor ou Administrador da organização. A integração CCEE, o cálculo tributário e os resultados financeiros serão tratados nas etapas seguintes.</p>
 </section>;
}
