'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import {Alert,Button,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {date,money} from './types';
type Price={id:string;start_date:string;end_date:string;price_per_mwh:number;reason:string};
export default function PriceHistory({id,start,end,canWrite,onDirty}:{id:string;start:string;end:string;canWrite:boolean;onDirty:(dirty:boolean)=>void}){
 const path='/api/v1/contract-configurations/energy/'+encodeURIComponent(id)+'/prices';const [rows,setRows]=useState<Price[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);const pending=useRef(false);
 useEffect(()=>{let cancelled=false;apiRequest<Price[]>(path).then(r=>{if(!cancelled)setRows(r);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[path]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current)return;if(!confirm){setConfirm(true);return;}const form=e.currentTarget,f=new FormData(form);const body={startDate:String(f.get('startDate')),endDate:String(f.get('endDate')),pricePerMwh:Number(f.get('pricePerMwh')),reason:String(f.get('reason'))};if(body.endDate<body.startDate){setError('Confira as datas do período.');return;}pending.current=true;setBusy(true);setError('');try{const r=await apiRequest<Price>(path,{method:'POST',body});setRows(old=>[...old,r]);form.reset();setConfirm(false);onDirty(false);}catch(e){setError(e instanceof Error?e.message:'Não foi possível registrar o preço.');}finally{pending.current=false;setBusy(false);}}
 return <section><h4>Histórico de preços por vigência</h4><p>O preço-base do contrato é preservado. Registre preços específicos para períodos dentro da vigência, sem sobreposição. Estes cadastros ainda não executam cálculos de faturas.</p>{error?<Alert variant="error">{error}</Alert>:null}{loading?<p>Carregando preços...</p>:rows.length?<ul>{[...rows].sort((a,b)=>a.start_date.localeCompare(b.start_date)).map(r=><li key={r.id}>{date(r.start_date)} a {date(r.end_date)}: R$ {money(r.price_per_mwh)}/MWh — {r.reason}</li>)}</ul>:<p>Nenhum período específico cadastrado.</p>}
 {canWrite?<form className="organizations-create__form" onSubmit={save} onChange={()=>{setConfirm(false);onDirty(true);}}><fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:12}}><Input label="Início do período de preço" name="startDate" type="date" min={start.slice(0,10)} max={end.slice(0,10)} required/><Input label="Término do período de preço" name="endDate" type="date" min={start.slice(0,10)} max={end.slice(0,10)} required/><Input label="Preço do período (R$/MWh)" name="pricePerMwh" type="number" min="0" step="any" required/><Input label="Motivo / referência do reajuste" name="reason" maxLength={4096} required/>{confirm?<p>Confira os valores. O período registrado não poderá ser sobrescrito.</p>:null}<Button type="submit">{busy?'Registrando...':confirm?'Confirmar período':'Revisar período de preço'}</Button></fieldset></form>:null}</section>;
}
