'use client';
import OperationalComposition,{CompositionData} from './OperationalComposition';
import ContractSupplierCost from './ContractSupplierCost';
import ManagementFeeMemory,{ManagementFeeData} from './ManagementFeeMemory';
import DistributorSubtotal,{DistributorSubtotalData} from './DistributorSubtotal';
import {SupplierCosts,AdditionalCosts,SupplierCostsData,AdditionalCostsData} from './FinancialCosts';
import {useState} from 'react';
import {comparisonRows,comparisonMoney,ComparisonInput,ComparisonEntry} from './comparison-view';
import {CorrectionContext} from './preparation-navigation';
type Data=ComparisonInput&{operationalComposition?:CompositionData;managementFeeMemory?:ManagementFeeData;supplierCostMemory?:SupplierCostsData;additionalCostSubtotal?:AdditionalCostsData;distributorSubtotal?:DistributorSubtotalData;month:string;unit:{id:string;name:string};checkedAt:string;counts:{blockers:number;reviews:number};supplyReference?:{lines:unknown[];pending:unknown[]}};
const categories=[{id:'tariffs',label:'Distribuidora',description:'Energia, demanda e reativos',icon:'01'},{id:'supplier',label:'Fornecedor',description:'Contrato, mínimo e compra extra',icon:'02'},{id:'taxes',label:'Tributos',description:'Bases e regras aprovadas',icon:'03'},{id:'costs',label:'Custos adicionais',description:'CCEE, encargos e créditos',icon:'04'}] as const;
export default function ScenarioComparison({data,customerId,onCorrect}:{data:Data;customerId?:string;onCorrect?:(c:CorrectionContext)=>void}){
 const [category,setCategory]=useState<'tariffs'|'taxes'|'costs'|'supplier'>('tariffs'),rows=comparisonRows(data),visible=rows.filter(r=>r.group===category);
 const missing={supplier:!data.contractSupplierCost&&!data.supplierCostMemory,tariffs:!data.tariffPreview,taxes:!data.taxMemory,costs:!data.costLedger};
 function correct(e:ComparisonEntry){if(!onCorrect||!customerId)return;onCorrect({customerId,unitId:data.unit.id,month:data.month,tab:e.kind==='SUPPLIER'?'supply':e.kind==='COST'?'costs':'parameters',kind:e.kind==='COST'||e.kind==='SUPPLIER'?undefined:e.kind,recordId:e.recordId,message:e.detail});}
 function cell(entries:ComparisonEntry[],scenario:string){return <div className={'ee-compare-cell ee-compare-cell--'+scenario.toLowerCase()}><span className='ee-compare-mobile-label'>{scenario}</span>{entries.length?entries.map((e,i)=><div key={(e.recordId||e.label)+'-'+i} className='ee-compare-entry'>
 {e.state==='VALUE'?<><strong className='ee-compare-money'>{comparisonMoney(e.amount)}</strong><span className='ee-compare-tag'>Valor da rubrica</span></>:<strong className={e.state==='PENDING'?'ee-compare-pending':'ee-compare-declared'}>{e.state==='PENDING'?'Pendente':e.label}</strong>}
 <p>{e.detail}</p>{e.source?<details><summary>Fonte e revisão</summary><p>{e.source}{e.revision?' · Revisão '+e.revision:''}</p></details>:null}
 {e.state==='PENDING'&&onCorrect&&customerId?<button type='button' className='ee-compare-link' onClick={()=>correct(e)}>Revisar cadastro <span aria-hidden='true'>↗</span></button>:null}
 </div>):<div className='ee-compare-absent'><strong>Sem valor calculado</strong><p>Ausência de valor não significa custo zero ou não aplicação.</p></div>}</div>;}
 return <section className='ee-comparison' aria-label='Comparativo preliminar ACL e ACR'>
 <header className='ee-compare-hero'><div><span className='ee-compare-eyebrow'>EXPERT ENERGY / ANÁLISE DE CENÁRIOS</span><h2>ACL <span>×</span> ACR</h2><p className='ee-compare-subtitle'>Cada componente. Os dois cenários. Uma visão.</p><p className='ee-compare-context'>{data.unit.name} <span aria-hidden='true'>/</span> {data.month.slice(5,7)+'/'+data.month.slice(0,4)}</p></div><div className='ee-compare-state'><span className='ee-compare-status'>Comparação parcial</span><p>Os componentes disponíveis estão lado a lado. A composição operacional reúne as rubricas revisadas abaixo. Honorários e economia líquida ainda aguardam fechamento.</p><a href='#preparation-findings'>Ver pendências <span aria-hidden='true'>↓</span></a></div></header>
 <div className='ee-compare-scenarios'>{(['ACR','ACL'] as const).map(s=>{const entries=rows.flatMap(r=>r[s]);return <article key={s} className={'ee-compare-scenario ee-compare-scenario--'+s.toLowerCase()}><div className='ee-compare-card-top'><span>{s==='ACR'?'CENÁRIO REGULADO':'CENÁRIO LIVRE'}</span><span className='ee-compare-dot' aria-hidden='true'/></div><h3>{s}</h3><p>{s==='ACR'?'Ambiente de Contratação Regulada':'Ambiente de Contratação Livre'}</p><div className='ee-compare-total'><span>Custo total do cenário</span><strong>Aguardando consolidação</strong></div><div className='ee-compare-card-bottom'><span><b>{entries.filter(e=>e.state==='VALUE').length}</b> rubricas com valor</span><span><b>{entries.filter(e=>e.state==='PENDING').length}</b> pendências nas memórias</span></div></article>;})}</div>
 <OperationalComposition data={data.operationalComposition} onCorrect={onCorrect&&customerId?tab=>onCorrect({customerId,unitId:data.unit.id,month:data.month,tab,message:'Revise as origens e os tratamentos indicados na composição operacional.'}):undefined}/><details className='ee-preparation-detail'><summary>Subtotal isolado da distribuidora</summary><DistributorSubtotal data={data.distributorSubtotal}/></details>
 <ManagementFeeMemory data={data.managementFeeMemory} onCorrect={onCorrect&&customerId?()=>onCorrect({customerId,unitId:data.unit.id,month:data.month,tab:'management',recordId:data.managementFeeMemory?.contract?.id,message:'Confirme o fixo por unidade e o rateio somente da parcela variável nesta competência.'}):undefined}/>
 <div className='ee-compare-savings'><div><span className='ee-compare-eyebrow'>ECONOMIA LÍQUIDA</span><h3>Ainda não apurada</h3><p>Será apresentada após integrar todos os custos aplicáveis e os honorários da gestão.</p></div><div className='ee-compare-saving-values'><span>Economia em R$ <strong>—</strong></span><span>Economia em % <strong>—</strong></span></div></div>
 <div className='ee-compare-section-heading'><div><span className='ee-compare-eyebrow'>EXPLORE A COMPOSIÇÃO</span><h3>Comparação por componente</h3></div><p>Valores calculados na consulta, sem somar bases ou tratamentos diferentes.</p></div>
 <div className='ee-compare-categories' aria-label='Categorias da comparação'>{categories.map(c=><button type='button' key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)} className={'ee-compare-category'+(category===c.id?' is-active':'')}><span className='ee-compare-category-number' aria-hidden='true'>{c.icon}</span><strong>{c.label}</strong><span>{c.description}</span><small>{c.id==='supplier'?(data.contractSupplierCost?data.contractSupplierCost.bands.length:(data.supplierCostMemory?.entries.length||0)):rows.filter(r=>r.group===c.id).length} componentes na consulta <span aria-hidden='true'>↗</span></small></button>)}</div>
 {category==='supplier'&&data.contractSupplierCost?<ContractSupplierCost data={data.contractSupplierCost} onCorrect={onCorrect&&customerId?(tab,id)=>onCorrect({customerId,unitId:data.unit.id,month:data.month,tab,recordId:id,message:'Confira as condições e os requisitos do faturamento contratual.'}):undefined}/>:null}
 {category==='supplier'&&!data.contractSupplierCost?<SupplierCosts data={data.supplierCostMemory} onCorrect={onCorrect&&customerId?()=>onCorrect({customerId,unitId:data.unit.id,month:data.month,tab:'costs',message:'Confira a fatura regular e as compras extras desta competência.'}):undefined}/>:null}
 {category==='costs'?<AdditionalCosts data={data.additionalCostSubtotal}/>:null}
 {category!=='supplier'?<div className='ee-compare-matrix' aria-live='polite' aria-label={'Comparação: '+categories.find(c=>c.id===category)?.label}><div className='ee-compare-matrix-heading'><span>COMPONENTE</span><strong>ACR</strong><strong>ACL</strong></div>{missing[category]?<p className='ee-compare-empty'>A memória desta categoria não está disponível. Atualize a conferência.</p>:visible.length?visible.map(r=><article key={r.key} className='ee-compare-row'><h4>{r.label}</h4>{cell(r.ACR,'ACR')}{cell(r.ACL,'ACL')}</article>):<p className='ee-compare-empty'>Nenhum componente disponível nesta categoria. Confira os cadastros e as pendências; isso não representa custo zero.</p>}</div>:null}
 <div className='ee-compare-footnote'><strong>Leitura dos valores</strong><p>As rubricas podem usar bases e tratamentos tributários diferentes. Os valores não devem ser somados manualmente nem interpretados como economia. A energia ACL usa o contrato vigente; mínimo não consumido e compra extra são detalhados no card Fornecedor. A NF é utilizada para conferência.</p><small>Consulta em {new Date(data.checkedAt).toLocaleString('pt-BR')} · sem publicação financeira</small></div>
 </section>;
}
