'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Alert,Button,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import AuditAuthor from './AuditAuthor';
import {invoicePermissions} from './SupplierInvoices';
type Row={id:string;version:number;status:string;reason:string;document_id:string;source_hash:string;created_by:string;created_by_name?:string;created_at:string};
type View={documentaryContext?:{hash:string};canConfigure:boolean;rows:Row[];documents:{id:string;original_filename:string}[];supplier:{taxTreatment?:string;contract?:{id:string};consumedMwh:string|null;billedMwh:string|null;volumeDifferenceMwh?:string;reconciliationContext?:{hash:string};reconciliation?:{current:boolean};requirements:{code:string;message:string}[]}};
export default function SpotReconciliation({contract,onDirty,initialMonth}:{initialMonth?:string;contract:{id:string;start_date:string;end_date:string};onDirty:(v:boolean)=>void}){
 const {context,hasPermission}=useAuth(),org=context&&context.scope!=='global'?context.currentOrganization.id:'',canView=hasPermission(invoicePermissions.view),canEdit=hasPermission('fd8a932f-87c0-4f86-8389-9f30c50e95b7');
 const [month,setMonth]=useState(initialMonth||contract.start_date.slice(0,7)),[attempt,setAttempt]=useState(0),[view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const current=useRef(''),pending=useRef(false);const key=org+':'+contract.id+':'+month;
 useEffect(()=>{let cancelled=false;current.current=key;setView(null);setError('');setLoading(true);setMessage('');
 if(!org||!canView||!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)){setLoading(false);return;}
 apiRequest<View>('/api/v1/supplier-spot-reconciliations?contractId='+encodeURIComponent(contract.id)+'&month='+month).then(r=>{if(!cancelled)setView(r);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;current.current='';};},[key,attempt,canView]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current||!view)return;const form=e.currentTarget,f=new FormData(form),scope=current.current,status=String(f.get('status')),source=status==='PENDING'?(view.documentaryContext||view.supplier.reconciliationContext):view.supplier.reconciliationContext;if(!source)return;pending.current=true;setBusy(true);setError('');setMessage('');try{
 const row=await apiRequest<Row>('/api/v1/supplier-spot-reconciliations',{method:'POST',body:{contractId:contract.id,month,status,documentId:String(f.get('documentId')),reason:String(f.get('reason')||'').trim(),sourceHash:source.hash,confirmed:f.get('confirmed')==='on',...(view.rows[0]?{previousId:view.rows[0].id}:{})}});
 if(scope!==current.current)return;setView(old=>old?{...old,rows:[row,...old.rows]}:old);form.reset();onDirty(false);setMessage('Conciliação salva no histórico, versão '+row.version+'. Atualizando os requisitos desta competência…');
 try{const refreshed=await apiRequest<View>('/api/v1/supplier-spot-reconciliations?contractId='+encodeURIComponent(contract.id)+'&month='+month);if(scope!==current.current)return;setView(refreshed);setMessage('Conciliação salva no histórico, versão '+row.version+'. Requisitos atualizados. Volte a Preparar apuração para consultar o diagnóstico completo.');}
 catch{if(scope===current.current)setError('A versão '+row.version+' foi salva, mas não foi possível atualizar os requisitos. Use Atualizar conciliação; não salve novamente a mesma revisão.');}
 }catch(e){if(scope===current.current)setError(e instanceof Error?e.message:'Falha ao salvar conciliação.');}finally{pending.current=false;if(scope===current.current)setBusy(false);}}
 if(!canView)return <p>É necessária permissão de consulta de documentos para conciliar.</p>;
 const r=view?.supplier,ready=r?.contract?.id===contract.id&&!!r?.reconciliationContext,canRecord=!!view?.documentaryContext||ready,canApprove=ready&&!r?.requirements.some(q=>q.code!=='SPOT_VOLUME_DIFFERENCE'&&(r.taxTreatment!=='RESERVED'||q.code!=='SPOT_TAX_RESERVATION'));
 return <section aria-label='Conciliação da compra pontual'><h4>Conciliação da compra pontual (MCP)</h4><p>Preserva o consumo medido e a quantidade comprada. Se houver cobrança adicional ou erro na fonte, corrija o lançamento com auditoria antes de concluir. A opção sem custo adicional exige comprovante que explique a diferença e confirme o encerramento financeiro.</p>
 <Input label='Competência da conciliação' type='month' value={month} min={contract.start_date.slice(0,7)} max={contract.end_date.slice(0,7)} disabled={busy} onChange={e=>{setMonth(e.target.value);onDirty(false);}}/><Button variant='secondary' disabled={busy||loading} onClick={()=>setAttempt(n=>n+1)}>Atualizar conciliação</Button><p>Envie o comprovante em <Link href='/backoffice/documents'>Documentos</Link>, para a mesma unidade e competência.</p>
 {error?<Alert variant='error'>{error}</Alert>:null}{message?<p role='status'>{message}</p>:null}{loading?<p>Consultando fontes e histórico...</p>:null}
 {r?<><p>Consumo: {r.consumedMwh?.replace('.',',')||'Pendente'} MWh · Compra: {r.billedMwh?.replace('.',',')||'Pendente'} MWh · Diferença: {r.volumeDifferenceMwh?.replace('.',',')||'Pendente'} MWh</p>{r.requirements.length?<ul>{r.requirements.map(q=><li key={q.code}>{q.message}</li>)}</ul>:null}{!ready?<p>A aprovação fica disponível após confirmar compra pontual, medição e nota em Custos mensais, com diferença de volume identificada. Você pode registrar evidências complementares como pendentes enquanto conclui essas etapas.</p>:null}</>:null}
 {canRecord&&view?.canConfigure&&canEdit?<form onSubmit={save} onChange={()=>onDirty(true)}><fieldset disabled={busy||loading}><legend>Registrar revisão da conciliação</legend><p>Para evidência complementar insuficiente para concluir a análise, use Manter pendente. Registre medição, perdas, resultado e páginas na justificativa; solicite o demonstrativo definitivo de contabilização/liquidação quando necessário. Cada documento fica preservado no histórico, sem alterar o consumo OCR. O fechamento com ressalva mantém a solicitação do demonstrativo definitivo.</p><p>Manter pendente permite registrar a auditoria sem aprovar. {canApprove?(r?.taxTreatment==='RESERVED'?'A conclusão com ressalva está disponível. A conclusão sem ressalva está bloqueada porque há tributos não confirmados.':'A conclusão sem custo adicional está disponível. A conclusão com ressalva exige tributação não confirmada nas condições e nos custos.'):'As conclusões estão bloqueadas pelos requisitos acima; registre evidências como pendentes enquanto resolve esses requisitos.'}</p><label>Resultado<select className='ds-input' name='status' required defaultValue='PENDING'><option value='PENDING'>Manter pendente / solicitar correção</option><option value='APPROVED_NO_COST' disabled={!canApprove||r?.taxTreatment==='RESERVED'}>Diferença documentada sem custo adicional</option><option value='APPROVED_TAX_RESERVATION' disabled={!canApprove||r?.taxTreatment!=='RESERVED'}>Concluir com ressalva — tributos não confirmados</option></select></label><p>Para concluir com ressalva, selecione Tributação não confirmada nas condições de faturamento e na nota em Custos mensais. O valor original da nota é preservado. Somente o ICMS explicitamente confirmado em Custos mensais é acrescido pelo motor; tributos não confirmados não são presumidos. Justifique a incerteza, a análise da diferença de volume e a necessidade de revisão posterior. Não declara isenção, imposto zero ou tributos incluídos.</p><label>Documento comprobatório<select className='ds-input' name='documentId' required defaultValue=''><option value=''>Selecione o comprovante</option>{view.documents.map(d=><option value={d.id} key={d.id}>{d.original_filename}</option>)}</select></label><label>Causa, conclusão e referência no documento<textarea className='ds-input' name='reason' required minLength={20} maxLength={2000}/></label><label><input type='checkbox' name='confirmed' required/> Conferi o documento e os valores. A diferença de volume foi analisada na justificativa. Sem ressalva, confirmo que não há cobrança ou crédito pendente. Com ressalva, assumo expressamente a incerteza tributária e o uso do valor documental com somente o ICMS adicional explicitamente confirmado em Custos mensais, sujeito a revisão.</label><Button type='submit'>{busy?'Salvando conciliação...':'Salvar conciliação auditada'}</Button></fieldset></form>:null}
 <h5>Histórico da conciliação</h5>{view?.rows.length?view.rows.map((row,i)=><article className='ds-card' key={row.id}><strong>Versão {row.version} · {row.status==='APPROVED_TAX_RESERVATION'?'Concluída com ressalva tributária':row.status==='APPROVED_NO_COST'?'Aprovada sem custo adicional':'Pendente'}</strong>{i===0&&r?.reconciliationContext&&row.source_hash!==r.reconciliationContext.hash?<p>Fontes alteradas: esta revisão não libera o cálculo atual.</p>:null}<p>{row.reason}</p><p>Documento: {view.documents.find(d=>d.id===row.document_id)?.original_filename||row.document_id}</p><p>Registrado por <AuditAuthor id={row.created_by} name={row.created_by_name}/> · {new Date(row.created_at).toLocaleString('pt-BR')}</p></article>):!loading?<p>Nenhuma conciliação registrada.</p>:null}</section>;
}
