'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Alert,Button,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import AuditAuthor from './AuditAuthor';
import {invoicePermissions} from './SupplierInvoices';
type Row={id:string;version:number;status:string;reason:string;document_id:string;source_hash:string;created_by:string;created_by_name?:string;created_at:string};
type View={canConfigure:boolean;rows:Row[];documents:{id:string;original_filename:string}[];supplier:{contract?:{id:string};consumedMwh:string|null;billedMwh:string|null;volumeDifferenceMwh?:string;reconciliationContext?:{hash:string};reconciliation?:{current:boolean};requirements:{code:string;message:string}[]}};
export default function SpotReconciliation({contract,onDirty}:{contract:{id:string;start_date:string;end_date:string};onDirty:(v:boolean)=>void}){
 const {context,hasPermission}=useAuth(),org=context&&context.scope!=='global'?context.currentOrganization.id:'',canView=hasPermission(invoicePermissions.view),canEdit=hasPermission('fd8a932f-87c0-4f86-8389-9f30c50e95b7');
 const [month,setMonth]=useState(contract.start_date.slice(0,7)),[attempt,setAttempt]=useState(0),[view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const current=useRef(''),pending=useRef(false);const key=org+':'+contract.id+':'+month;
 useEffect(()=>{let cancelled=false;current.current=key;setView(null);setError('');setLoading(true);setMessage('');
 if(!org||!canView||!/^\d{4}-(0[1-9]|1[0-2])$/.test(month)){setLoading(false);return;}
 apiRequest<View>('/api/v1/supplier-spot-reconciliations?contractId='+encodeURIComponent(contract.id)+'&month='+month).then(r=>{if(!cancelled)setView(r);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;current.current='';};},[key,attempt,canView]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(pending.current||!view?.supplier.reconciliationContext)return;const form=e.currentTarget,f=new FormData(form),scope=current.current;pending.current=true;setBusy(true);setError('');setMessage('');try{
 const row=await apiRequest<Row>('/api/v1/supplier-spot-reconciliations',{method:'POST',body:{contractId:contract.id,month,status:String(f.get('status')),documentId:String(f.get('documentId')),reason:String(f.get('reason')||'').trim(),sourceHash:view.supplier.reconciliationContext.hash,confirmed:f.get('confirmed')==='on',...(view.rows[0]?{previousId:view.rows[0].id}:{})}});
 if(scope!==current.current)return;setView(old=>old?{...old,rows:[row,...old.rows]}:old);form.reset();onDirty(false);setMessage('Conciliação salva no histórico, versão '+row.version+'. Atualize Preparar apuração para recalcular com as fontes atuais.');
 }catch(e){if(scope===current.current)setError(e instanceof Error?e.message:'Falha ao salvar conciliação.');}finally{pending.current=false;if(scope===current.current)setBusy(false);}}
 if(!canView)return <p>É necessária permissão de consulta de documentos para conciliar.</p>;
 const r=view?.supplier,ready=r?.contract?.id===contract.id&&!!r?.reconciliationContext;
 return <section aria-label='Conciliação da compra pontual'><h4>Conciliação da compra pontual (MCP)</h4><p>Preserva o consumo medido e a quantidade comprada. Se houver cobrança adicional ou erro na fonte, corrija o lançamento com auditoria antes de concluir. A opção sem custo adicional exige comprovante que explique a diferença e confirme o encerramento financeiro.</p>
 <Input label='Competência da conciliação' type='month' value={month} min={contract.start_date.slice(0,7)} max={contract.end_date.slice(0,7)} disabled={busy} onChange={e=>{setMonth(e.target.value);onDirty(false);}}/><Button variant='secondary' disabled={busy||loading} onClick={()=>setAttempt(n=>n+1)}>Atualizar conciliação</Button><p>Envie o comprovante em <Link href='/backoffice/documents'>Documentos</Link>, para a mesma unidade e competência.</p>
 {error?<Alert variant='error'>{error}</Alert>:null}{message?<p role='status'>{message}</p>:null}{loading?<p>Consultando fontes e histórico...</p>:null}
 {r?<><p>Consumo: {r.consumedMwh?.replace('.',',')||'Pendente'} MWh · Compra: {r.billedMwh?.replace('.',',')||'Pendente'} MWh · Diferença: {r.volumeDifferenceMwh?.replace('.',',')||'Pendente'} MWh</p>{r.requirements.length?<ul>{r.requirements.map(q=><li key={q.code}>{q.message}</li>)}</ul>:null}{!ready?<p>A conciliação fica disponível após confirmar compra pontual, medição e nota em Custos mensais, com diferença de volume identificada.</p>:null}</>:null}
 {ready&&view?.canConfigure&&canEdit?<form onSubmit={save} onChange={()=>onDirty(true)}><fieldset disabled={busy||loading}><legend>Registrar revisão da conciliação</legend><label>Resultado<select className='ds-input' name='status' required defaultValue='PENDING'><option value='PENDING'>Manter pendente / solicitar correção</option><option value='APPROVED_NO_COST'>Diferença documentada sem custo adicional</option></select></label><label>Documento comprobatório<select className='ds-input' name='documentId' required defaultValue=''><option value=''>Selecione o comprovante</option>{view.documents.map(d=><option value={d.id} key={d.id}>{d.original_filename}</option>)}</select></label><label>Causa, conclusão e referência no documento<textarea className='ds-input' name='reason' required minLength={20} maxLength={2000}/></label><label><input type='checkbox' name='confirmed' required/> Conferi o documento e os valores. Para aprovar sem custo adicional, confirmo que a evidência explica toda a diferença e não há cobrança ou crédito pendente relacionado a ela.</label><Button type='submit'>{busy?'Salvando conciliação...':'Salvar conciliação auditada'}</Button></fieldset></form>:null}
 <h5>Histórico da conciliação</h5>{view?.rows.length?view.rows.map((row,i)=><article className='ds-card' key={row.id}><strong>Versão {row.version} · {row.status==='APPROVED_NO_COST'?'Aprovada sem custo adicional':'Pendente'}</strong>{i===0&&r?.reconciliationContext&&row.source_hash!==r.reconciliationContext.hash?<p>Fontes alteradas: esta revisão não libera o cálculo atual.</p>:null}<p>{row.reason}</p><p>Documento: {view.documents.find(d=>d.id===row.document_id)?.original_filename||row.document_id}</p><p>Registrado por <AuditAuthor id={row.created_by} name={row.created_by_name}/> · {new Date(row.created_at).toLocaleString('pt-BR')}</p></article>):!loading?<p>Nenhuma conciliação registrada.</p>:null}</section>;
}
