'use client';
import {useState} from 'react';
import {Button,Input} from '@/app/components/ui';
export type AnnualPrice={startDate:string;endDate:string;pricePerMwh:number|string;priceStatus:'FINAL'|'BASE'};
export type SupplyTerms={annual_prices?:AnnualPrice[];pricing_mode?:string;adjustment_index?:string;adjustment_frequency?:string;adjustment_date?:string;adjustment_rule?:string;guarantee_type?:string;guarantee_amount?:number;guarantee_institution?:string;guarantee_description?:string};
export const guarantees:Record<string,string>={BANK_GUARANTEE:'Carta fiança',INSURANCE:'Seguro garantia',BANK_DEPOSIT:'Depósito bancário',OTHER:'Outro'};
export default function SupplyTermsFields({value,busy,onDirty,onSchedule}:{value:SupplyTerms|null;busy:boolean;onDirty:(v:boolean)=>void;onSchedule:(v:boolean)=>void}){
 const [periods,setPeriods]=useState<AnnualPrice[]>(value?.annual_prices||[]),[mode,setMode]=useState(value?.pricing_mode||'FIXED'),[guarantee,setGuarantee]=useState(value?.guarantee_type||'');
 function change(rows:AnnualPrice[]){setPeriods(rows);onSchedule(rows.length>0);onDirty(true);}
 function update(i:number,key:keyof AnnualPrice,v:string){change(periods.map((p,j)=>j===i?{...p,[key]:v}:p));}
 return <fieldset disabled={busy} style={{border:0,padding:0,display:'grid',gap:16}}><h3>Preços por ano e reajuste</h3>
 <label>Forma de precificação<select className="ds-input" name="pricingMode" value={mode} onChange={e=>{setMode(e.target.value);if(e.target.value==='FIXED')change(periods.map(p=>({...p,priceStatus:'FINAL'})));}}><option value="FIXED">Valores definidos por ano</option><option value="INDEXED">Reajuste por índice</option><option value="MIXED">Valores por ano e reajuste por índice</option></select></label>
 <p>Cadastre uma linha para cada ano contratual ou período parcial. A tabela deve cobrir toda a vigência, sem lacunas ou sobreposições. O primeiro período define o preço-base do contrato.</p>
 <input type="hidden" name="annualPrices" value={JSON.stringify(periods)}/>
 {periods.map((p,i)=><fieldset key={i} style={{border:'1px solid #475569',borderRadius:8,padding:16,display:'grid',gap:12}}><legend>Período {i+1}</legend><Input label={'Início do período '+(i+1)} type="date" value={p.startDate} onChange={e=>update(i,'startDate',e.target.value)} required/><Input label={'Fim do período '+(i+1)} type="date" value={p.endDate} onChange={e=>update(i,'endDate',e.target.value)} required/><Input label={'Preço do período '+(i+1)+' (R$/MWh)'} type="number" min="0" step="any" value={p.pricePerMwh} onChange={e=>update(i,'pricePerMwh',e.target.value)} required/>
 {mode!=='FIXED'?<label>Situação do preço<select className="ds-input" value={p.priceStatus} onChange={e=>update(i,'priceStatus',e.target.value)}><option value="BASE">Preço-base — reajuste ainda não aplicado</option><option value="FINAL">Preço final — definido ou já corrigido</option></select></label>:null}<Button variant="secondary" type="button" onClick={()=>change(periods.filter((_,j)=>i!==j))}>Remover período {i+1}</Button></fieldset>)}
 <Button type="button" variant="secondary" disabled={periods.length>=50} onClick={()=>change([...periods,{startDate:'',endDate:'',pricePerMwh:'',priceStatus:mode==='FIXED'?'FINAL':'BASE'}])}>Adicionar ano / período</Button>
 {mode!=='FIXED'?<><Input label="Índice de reajuste (ex.: IPCA)" name="adjustmentIndex" maxLength={50} defaultValue={value?.adjustment_index||''} required/><Input label="Data-base do reajuste" name="adjustmentDate" type="date" defaultValue={value?.adjustment_date?.slice(0,10)||''} required/><input type="hidden" name="adjustmentFrequency" value="ANNUAL"/><label>Regra contratual de reajuste<textarea className="ds-input" name="adjustmentRule" maxLength={4096} defaultValue={value?.adjustment_rule||''} required placeholder="Informe índice, janela de acumulação, primeiro reajuste e condições previstas no contrato."/></label><p>Reajuste anual. Valores marcados como base aguardam apuração do índice; este cadastro não calcula inflação nem aplica correção automática. Valores finais não devem receber o mesmo reajuste novamente.</p></>:null}
 <h3>Garantia contratual</h3><label>Tipo de garantia<select className="ds-input" name="guaranteeType" value={guarantee} onChange={e=>setGuarantee(e.target.value)}><option value="">Não informada / não solicitada</option>{Object.entries(guarantees).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
 {guarantee?<><Input label="Valor da garantia (R$)" name="guaranteeAmount" type="number" min="0" step="0.01" defaultValue={value?.guarantee_amount??''} required/><Input label="Instituição da garantia" name="guaranteeInstitution" maxLength={255} defaultValue={value?.guarantee_institution||''} required/>{guarantee==='OTHER'?<Input label="Descrição da outra garantia" name="guaranteeDescription" maxLength={1000} defaultValue={value?.guarantee_description||''} required/>:null}</>:null}</fieldset>;
}
export function readSupplyTerms(f:FormData){
 const text=(k:string)=>String(f.get(k)||'').trim();
 const periods=(JSON.parse(text('annualPrices')||'[]') as AnnualPrice[]).map(p=>({...p,pricePerMwh:Number(p.pricePerMwh)}));
 return {annualPrices:periods,pricingMode:text('pricingMode'),adjustmentIndex:text('adjustmentIndex'),adjustmentDate:text('adjustmentDate')||null,adjustmentFrequency:text('adjustmentFrequency')||undefined,adjustmentRule:text('adjustmentRule'),guaranteeType:text('guaranteeType')||null,guaranteeAmount:text('guaranteeType')?Number(text('guaranteeAmount')):null,guaranteeInstitution:text('guaranteeType')?text('guaranteeInstitution'):null,guaranteeDescription:text('guaranteeType')==='OTHER'?text('guaranteeDescription'):null};
}
