'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import AuditAuthor from './AuditAuthor';
type Contract={id:string;contract_number:string;start_date:string;end_date:string;contracted_volume_mwh:number};
type Rule={id:string;version:number;start_date:string;end_date:string;volume_basis:string;min_percent:string;max_tolerance_percent:string;price_mode:string;index_percent:string|null;index_source:string|null;tax_treatment:string;source:string;reason:string;created_by:string;created_by_name?:string|null;created_at:string};
export default function SupplierBillingRules({contract,onDirty}:{contract:Contract;onDirty:(v:boolean)=>void}){
 const [rows,setRows]=useState<Rule[]>([]),[can,setCan]=useState(false),[busy,setBusy]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState(false),[mode,setMode]=useState('');
 useEffect(()=>{let cancelled=false;apiRequest<{rows:Rule[];canConfigure:boolean}>('/api/v1/supplier-billing-rules?contractId='+encodeURIComponent(contract.id)).then(r=>{if(!cancelled){setRows(r.rows);setCan(r.canConfigure);}}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[contract.id]);
 function close(){setEditing(false);onDirty(false);}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget),s=(k:string)=>String(f.get(k)||'').trim(),body={contractId:contract.id,startDate:s('startDate'),endDate:s('endDate'),volumeBasis:s('volumeBasis'),minPercent:s('minPercent').replace(',','.'),maxTolerancePercent:s('maxTolerancePercent').replace(',','.'),priceMode:mode,taxTreatment:s('taxTreatment'),source:s('source'),reason:s('reason'),...(mode==='BASE_PLUS_INDEX'?{indexPercent:s('indexPercent').replace(',','.'),indexSource:s('indexSource')}:{ }),...(rows[0]?{previousId:rows[0].id}:{})};setBusy(true);setError('');try{const r=await apiRequest<Rule>('/api/v1/supplier-billing-rules',{method:'POST',body});setRows(old=>[r,...old]);close();}catch(e){setError(e instanceof Error?e.message:'Falha ao registrar condições.');}finally{setBusy(false);}}
 return <Card title='Faturamento automático · take-or-pay'><p>O volume faturável vem do contrato e do consumo validado. Mínimo não consumido e compra extra são separados. A NF serve para conferência e não é somada novamente.</p>{error?<Alert variant='error'>{error}</Alert>:null}{busy?<p>Processando condições...</p>:null}{!busy&&!rows.length?<p>Nenhuma condição confirmada. O motor aguarda o cadastro explícito dos limites.</p>:null}{!editing&&can?<Button onClick={()=>{setEditing(true);setMode('');onDirty(true);}}>{rows.length?'Registrar nova versão das condições':'Configurar faturamento automático'}</Button>:null}
 {editing?<form onSubmit={save} onChange={()=>onDirty(true)}><fieldset disabled={busy} className='organizations-create__form'><Input label='Início da condição de faturamento' type='date' name='startDate' defaultValue={contract.start_date.slice(0,10)} required/><Input label='Fim da condição de faturamento' type='date' name='endDate' defaultValue={contract.end_date.slice(0,10)} required/>
 <label>Base do volume contratado<select className='ds-input' name='volumeBasis' defaultValue='' required><option value=''>Selecione</option><option value='MONTHLY'>Volume do contrato em MWh por mês</option><option value='SEASONAL'>Distribuição sazonal por ano e mês</option></select></label><p>Volume cadastrado: {String(contract.contracted_volume_mwh)} MWh. Confirme a base mensal ou use a distribuição sazonal explícita. Não será feita divisão implícita por 12.</p>
 <Input label='Mínimo faturável — take-or-pay (%)' name='minPercent' type='number' min='0' max='9999' step='0.0001' required/><Input label='Tolerância acima do volume contratado (%)' name='maxTolerancePercent' type='number' min='0' max='9999' step='0.0001' required/><p>Mínimo: percentual do volume contratado. Máximo: volume contratado acrescido da tolerância. Exemplo: 100 MWh, mínimo de 70% e tolerância de 30% permitem faturamento entre 70 e 130 MWh. Consumo de 60 MWh fatura 70; consumo de 120 fatura 120; consumo de 140 exige compra extra de 10 MWh. Informe 30 para tolerância de 30%, não 130.</p>
 <label>Preço e reajuste<select className='ds-input' value={mode} onChange={e=>setMode(e.target.value)} required><option value=''>Selecione</option><option value='FINAL'>Usar preço final vigente, já reajustado</option><option value='BASE_PLUS_INDEX'>Preço-base vigente + índice acumulado documentado</option></select></label>{mode==='BASE_PLUS_INDEX'?<><Input label='Índice acumulado sobre o preço-base (%)' type='number' name='indexPercent' min='-99.999999' max='9999' step='0.000001' required/><Input label='Fonte e período do índice aplicado' name='indexSource' maxLength={2000} required/><p>Informe o acumulado aplicável à vigência desta condição. O motor aplica uma única vez sobre o preço-base. Não é aplicada correção sobre preço marcado como final.</p></>:null}
 <label>Tratamento do preço contratado<select className='ds-input' name='taxTreatment' defaultValue='' required><option value=''>Selecione</option><option value='NET'>Sem tributos — tributos apurados separadamente</option><option value='GROSS'>Com tributos incluídos</option></select></label><Input label='Fonte contratual das condições' name='source' required maxLength={2000}/>{rows.length?<Input label='Motivo da nova versão ou vigência' name='reason' required maxLength={2000}/>:null}<p>Esta confirmação preserva o histórico. A versão mais recente aplicável ao mês prevalece. Vigências parciais, preço ausente e compra extra sem valor impedem concluir a conferência do fornecedor.</p><Button type='submit'>Confirmar condições de faturamento</Button><Button variant='secondary' type='button' onClick={close}>Cancelar condições</Button></fieldset></form>:null}
 {rows.map(r=><article key={r.id} className='ds-card'><h4>Condição · versão {r.version}</h4><p>{r.start_date} a {r.end_date} · {r.volume_basis==='MONTHLY'?'Volume mensal':'Sazonalidade'}</p><p>Mínimo {r.min_percent}% · tolerância acima do contratado {r.max_tolerance_percent}% · {r.tax_treatment==='NET'?'Sem tributos':'Tributos incluídos'}</p><p>{r.price_mode==='FINAL'?'Preço final vigente':'Preço-base + índice acumulado '+r.index_percent+'%'}{r.index_source?' · '+r.index_source:''}</p><p>Fonte: {r.source}</p>{r.reason?<p>Motivo: {r.reason}</p>:null}<p>Registrado por <AuditAuthor id={r.created_by} name={r.created_by_name}/> · {new Date(r.created_at).toLocaleString('pt-BR')}</p></article>)}</Card>;
}
