'use client';
import {Alert,Card} from '@/app/components/ui';
export type TariffPreviewData={formulaVersion:string;measurement:{id:string;version:number;revision:number;source:string}|null;lines:{parameterId:string;revision:number;label:string;scenario:string;timeBand:string;measure:string;rate:string;quantity:string;quantityUnit:string;exactAmount:string;amount:string;treatment:string;embeddedTaxCodes:string[];source:string;formula:string;quantitySource?:string;startDate:string;endDate:string}[];pending:{parameterId:string;label:string;scenario:string;reason:string}[];warnings:string[]};
const decimal=(v:string)=>v.replace('.',',');
const band:Record<string,string>={ALL:'Todos os postos',PEAK:'Ponta',OFF_PEAK:'Fora ponta'};
const measure:Record<string,string>={BRL_KW:'R$/kW',BRL_KWH:'R$/kWh',BRL_MWH:'R$/MWh',BRL_KVARH:'R$/kVArh'};
export default function TariffPreview({data}:{data?:TariffPreviewData}){
 return <Card title='Memória preliminar das tarifas'>
 {!data?<p>A memória das tarifas ainda não está disponível nesta resposta. Atualize a conferência após a publicação da API.</p>:<>
 <Alert>Valores isolados por rubrica. Não são o total ACL/ACR nem a economia. Consulte as pendências antes de usar os valores.</Alert>
 {data.measurement?<p>Medições: versão {data.measurement.version} · revisão {data.measurement.revision} · fonte: {data.measurement.source}</p>:<p>É necessária uma versão validada das medições para calcular as tarifas.</p>}
 {data.lines.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><caption>Componentes calculados na competência</caption><thead><tr>{['Rubrica / cenário','Quantidade','Tarifa','Valor da rubrica'].map(t=><th key={t} scope='col' style={{textAlign:'left',padding:12,borderBottom:'1px solid #334155'}}>{t}</th>)}</tr></thead><tbody>{data.lines.map(l=><tr key={l.parameterId}><td style={{padding:12,verticalAlign:'top',borderBottom:'1px solid #334155'}}><strong>{l.label} · {l.scenario}</strong><p>{band[l.timeBand]||l.timeBand}</p><details><summary>Ver fórmula e fontes</summary><p>Fórmula: {l.formula}</p>{l.quantitySource?<p>Fonte e regra da quantidade faturável: {l.quantitySource}</p>:null}<p>Valor antes do arredondamento: R$ {decimal(l.exactAmount)}</p><p>Fonte da tarifa: {l.source} · revisão {l.revision}</p><p>Vigência: {l.startDate} a {l.endDate}</p><p>{l.treatment==='NET'?'Valor sem tributos embutidos. Os tributos ainda não foram acrescidos.':'Valor com tributos embutidos: '+l.embeddedTaxCodes.join(', ')+'. Nenhum tributo foi acrescido novamente.'}</p></details></td><td style={{padding:12,verticalAlign:'top',borderBottom:'1px solid #334155'}}>{decimal(l.quantity)} {l.quantityUnit}</td><td style={{padding:12,verticalAlign:'top',borderBottom:'1px solid #334155'}}>{decimal(l.rate)} {measure[l.measure]||l.measure}</td><td style={{padding:12,verticalAlign:'top',borderBottom:'1px solid #334155'}}>R$ {decimal(l.amount)}</td></tr>)}</tbody></table></div>:<p>Nenhuma rubrica calculada. Isso não significa custo zero.</p>}
 {data.pending.length?<><h3>Rubricas ainda não calculadas</h3><ul>{data.pending.map((p,i)=><li key={p.parameterId+'-'+i}><strong>{p.label} · {p.scenario}:</strong> {p.reason}</li>)}</ul></>:null}
 <details><summary>Limites desta memória e arredondamento</summary><ul>{data.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>Valores calculados no servidor com aritmética decimal exata. Exibição por linha em centavos, com meio centavo arredondado para cima. Fórmula: {data.formulaVersion}.</p></details>
 </>}
 </Card>;
}
