'use client';
import {useEffect,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import {PERM,Unit,date} from './types';
import {matchTariffLibrary} from './tariff-library-match';
type Item={component:string;band:string;measure:string;value:string;label:string};
type Profile={distributor:string;group:string;subgroup:string;modality:string;category:string;consumptionClass:string;startDate:string;endDate:string;source:string;notes:string;items:Item[]};
type Version={id:string;root_id:string;version:number;profile:Profile;reason:string;created_at:string;created_by:string;actor_id_name?:string};
type Tax={code:string;rate:string;mode:string;included:string[]};
const key=(i:Item)=>i.component+':'+i.band;
const codes=['ICMS','PIS','COFINS'];
const labels:Record<string,string>={TE:'Energia TE',TUSD_ENERGY:'TUSD energia',TUSD_DEMAND_USED:'Demanda utilizada',TUSD_DEMAND_UNUSED:'Demanda não utilizada',REACTIVE:'Energia reativa',GREEN:'Verde',BLUE:'Azul',CONVENTIONAL:'Convencional',WHITE:'Branca',PEAK:'Ponta',OFF_PEAK:'Fora ponta',ALL:'Todos',BRL_KWH:'R$/kWh',BRL_MWH:'R$/MWh',BRL_KW:'R$/kW',BRL_KVARH:'R$/kVArh'};
const field={display:'block',width:'100%',padding:8,background:'#101c2d',color:'inherit',border:'1px solid #4b6078',borderRadius:6};
const button={padding:'9px 14px',border:'1px solid #4b6078',borderRadius:6,margin:4};
const empty=():Profile=>({distributor:'',group:'A',subgroup:'A4',modality:'GREEN',category:'Geral',consumptionClass:'GENERAL',startDate:'',endDate:'',source:'',notes:'',items:[]});
export default function TariffLibrary({customerId,units,onApplied}:{customerId:string;units:Unit[];onApplied:()=>void}){
 const {hasPermission}=useAuth();const canCreate=hasPermission(PERM.create),canUpdate=hasPermission(PERM.update);
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Version[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [dist,setDist]=useState(''),[group,setGroup]=useState(''),[subgroup,setSubgroup]=useState(''),[modality,setModality]=useState(''),[category,setCategory]=useState(''),[cls,setCls]=useState('');
 const [editor,setEditor]=useState<Profile|null>(null),[previous,setPrevious]=useState<string|null>(null),[reason,setReason]=useState(''),[history,setHistory]=useState<string|null>(null);
 const [chosen,setChosen]=useState<Version|null>(null),[unitId,setUnitId]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[gross,setGross]=useState(''),[embedded,setEmbedded]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]),[taxes,setTaxes]=useState<Tax[]>([]),[cip,setCip]=useState(''),[other,setOther]=useState(''),[otherLabel,setOtherLabel]=useState(''),[aclPrice,setAclPrice]=useState(''),[aclSource,setAclSource]=useState(''),[why,setWhy]=useState(''),[expired,setExpired]=useState(false),[expiredReason,setExpiredReason]=useState('');
 const [lookupUnit,setLookupUnit]=useState(''),[lookupMonth,setLookupMonth]=useState(''),[lookupCategory,setLookupCategory]=useState('');
 const [preview,setPreview]=useState<{rows:any[];monthlyCosts:any[];notes:string[]}|null>(null);
 const unit=units.find(u=>u.id===unitId&&u.customer_id===customerId),scenario=unit?.free_market===true?'ACR':unit?.free_market===false?'ACL':null;
 const latest=rows.filter(r=>!rows.some(n=>n.root_id===r.root_id&&n.version>r.version));
 async function load(){setRows(await apiRequest<Version[]>('/api/v1/tariff-library'));}
 async function run(f:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await f();}catch(e){setError(e instanceof Error?e.message:'Falha na operação.');}finally{setBusy(false);}}
 useEffect(()=>{if(open)void run(load);},[open]); // eslint-disable-line react-hooks/exhaustive-deps
 function edit(p:Partial<Profile>){setEditor(e=>e?{...e,...p}:e);}
 function application(v:Version){setChosen(v);setPreview(null);setSelected(v.profile.items.map(key));setTaxes(codes.map(code=>({code,rate:'',mode:'',included:v.profile.items.filter(i=>code!=='ICMS'||i.component!=='TUSD_DEMAND_UNUSED').map(key)})));setGross('');setEmbedded([]);setStart(v.profile.startDate);setEnd(v.profile.endDate);setCip('');setOther('');setOtherLabel('');setWhy('');setExpired(false);setExpiredReason('');setAclPrice('');setAclSource('');setError('');setMessage('');}
 function payload(){if(!chosen||!scenario||gross==='')throw new Error('Selecione unidade com mercado definido e informe se há tributos embutidos.');return{consumerUnitId:unitId,startDate:start,endDate:end,scenario,includedTaxes:gross==='YES',selected,embeddedCodes:gross==='YES'?embedded:[],taxes:gross==='NO'?taxes.map(t=>({...t,included:t.included.filter(k=>selected.includes(k))})):[],cip,other,otherLabel,...(scenario==='ACL'?{aclEnergyPrice:aclPrice}:{}),aclSource,reason:why,expiredConfirmed:expired,expiredReason};}
 function findReference(){const found=matchTariffLibrary(rows,units.find(u=>u.id===lookupUnit&&u.customer_id===customerId),lookupMonth,lookupCategory);if(!found.candidate){setError(found.message);setMessage('');return;}application(found.candidate);setUnitId(lookupUnit);setStart(found.start!);setEnd(found.end!);setMessage(found.message);}
 const visible=latest.filter(r=>(!dist||r.profile.distributor===dist)&&(!group||r.profile.group===group)&&(!subgroup||r.profile.subgroup===subgroup)&&(!modality||r.profile.modality===modality)&&(!category||r.profile.category===category)&&(!cls||r.profile.consumptionClass===cls));
 const selectFilter=(label:string,property:keyof Profile,value:string,set:(x:string)=>void)=><label>{label}<select style={field} value={value} onChange={e=>set(e.target.value)}><option value="">Todas</option>{Array.from(new Set(latest.map(r=>String(r.profile[property])))).sort().map(s=><option key={s} value={s}>{labels[s]||s}</option>)}</select></label>;
 return <section aria-label="Biblioteca tarifária" style={{border:'1px solid #4b6078',padding:18,borderRadius:12,margin:'18px 0'}}>
 <h3>Biblioteca tarifária por distribuidora</h3><p>Escolha o enquadramento e preencha os parâmetros de comparação em lote, com fonte, versão e auditoria.</p>
 {canCreate&&canUpdate&&!open&&<button type="button" style={button} onClick={()=>{setOpen(true);setPrevious(null);setEditor(empty());setReason('');}}>Inserir nova biblioteca</button>}
 <button type="button" style={button} onClick={()=>setOpen(!open)}>{open?'Fechar biblioteca':'Abrir biblioteca tarifária'}</button>
 {open&&<><div role="alert">{error}</div><p role="status">{message}</p>
 <fieldset style={{border:'1px solid #4b6078',padding:16,margin:'12px 0'}}><legend>Buscar referência automaticamente para a competência</legend><p>ACL usa a referência ACR da mesma distribuidora e enquadramento. Para unidade ACR, a simulação ACL também exige preço e fonte do fornecedor.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:12}}><label>Unidade da busca automática<select style={field} value={lookupUnit} onChange={e=>{setLookupUnit(e.target.value);setError('');setMessage('');}}><option value="">Selecione</option>{units.filter(u=>u.customer_id===customerId).map(u=><option key={u.id} value={u.id}>{u.name} — {u.consumer_unit_number}</option>)}</select></label><label>Competência da referência<input type="month" style={field} value={lookupMonth} onChange={e=>{setLookupMonth(e.target.value);setError('');setMessage('');}}/></label><label>Categoria da busca (se necessário)<select style={field} value={lookupCategory} onChange={e=>{setLookupCategory(e.target.value);setError('');setMessage('');}}><option value="">Todas — somente correspondência única</option>{Array.from(new Set(latest.map(r=>r.profile.category))).sort().map(c=><option key={c} value={c}>{c}</option>)}</select></label></div><button type="button" style={button} disabled={busy||!canCreate||!canUpdate} onClick={findReference}>Buscar e preencher tarifas da competência</button><p>A busca preserva a versão e a fonte. Não prorroga vigências nem presume impostos ou custos ausentes.</p></fieldset>
 <button type="button" style={button} disabled={busy} onClick={()=>run(load)}>Atualizar biblioteca</button>
 {canCreate&&canUpdate&&<><button type="button" style={button} disabled={busy} onClick={()=>{setPrevious(null);setEditor(empty());setReason('');}}>Inserir nova biblioteca</button><button type="button" style={button} disabled={busy} onClick={()=>run(async()=>{const p=await apiRequest<Profile&{reason:string}>('/api/v1/tariff-library/elektro-seed');setEditor(p);setPrevious(null);setReason(p.reason);})}>Carregar tabela Elektro A4 Verde do PDF</button></>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12}}>{selectFilter('Distribuidora','distributor',dist,setDist)}{selectFilter('Grupo','group',group,setGroup)}{selectFilter('Subgrupo','subgroup',subgroup,setSubgroup)}{selectFilter('Modalidade','modality',modality,setModality)}{selectFilter('Categoria','category',category,setCategory)}{selectFilter('Classe da tabela','consumptionClass',cls,setCls)}</div>
 {!rows.length&&!busy&&<p>Nenhuma tabela cadastrada. Carregue o primeiro enquadramento ou cadastre uma nova tabela.</p>}
 {visible.map(v=><article key={v.id} style={{borderTop:'1px solid #4b6078',padding:'16px 0'}}><strong>{v.profile.distributor} · {v.profile.subgroup} · {labels[v.profile.modality]} · {v.profile.category} · {v.profile.consumptionClass==='GENERAL'?'Geral, sem distinção de classe na fonte':v.profile.consumptionClass} · v{v.version}</strong><p>Vigência: {date(v.profile.startDate)} a {date(v.profile.endDate)}{v.profile.endDate<new Date().toISOString().slice(0,10)?' — VENCIDA: atualizar ou confirmar uso histórico':''}</p><p>{v.profile.source}</p><button type="button" style={button} disabled={busy||!canCreate||!canUpdate} onClick={()=>application(v)}>Selecionar e preencher parâmetros</button><button type="button" style={button} disabled={busy||!canCreate||!canUpdate} onClick={()=>{setEditor(structuredClone(v.profile));setPrevious(v.id);setReason('');}}>Revisar em nova versão</button><button type="button" style={button} onClick={()=>setHistory(history===v.root_id?null:v.root_id)}>Histórico da biblioteca</button>{history===v.root_id&&rows.filter(r=>r.root_id===v.root_id).map(r=><details key={r.id}><summary>v{r.version} · {r.actor_id_name||r.created_by} · {new Date(r.created_at).toLocaleString('pt-BR')}</summary><p>{r.reason}</p><p>{date(r.profile.startDate)} a {date(r.profile.endDate)} · {r.profile.source}</p><ul>{r.profile.items.map(i=><li key={key(i)}>{i.label}: {i.value} {labels[i.measure]}</li>)}</ul></details>)}</article>)}
 {editor&&<div role="dialog" aria-label="Cadastro de enquadramento tarifário" style={{border:'2px solid #54cee7',padding:18,marginTop:15}}><h4>{previous?'Nova versão da tabela':'Cadastrar tabela'}</h4><p>As versões e parâmetros anteriores serão preservados. A biblioteca contém referências; sua aplicação exige confirmação tributária.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{(['distributor','group','subgroup','category','consumptionClass','startDate','endDate'] as const).map(k=><label key={k}>{({distributor:'Distribuidora',group:'Grupo (A ou B)',subgroup:'Subgrupo',category:'Categoria',consumptionClass:'Classe (GENERAL quando a fonte não distingue)',startDate:'Vigência inicial',endDate:'Vigência final'})[k]}<input style={field} type={k.includes('Date')?'date':'text'} value={editor[k]} onChange={e=>edit({[k]:e.target.value})}/></label>)}<label>Modalidade<select style={field} value={editor.modality} onChange={e=>edit({modality:e.target.value})}>{['GREEN','BLUE','CONVENTIONAL','WHITE'].map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label></div>
 <label>Fonte / documento<input style={field} value={editor.source} onChange={e=>edit({source:e.target.value})}/></label><label>Notas de cobertura<textarea style={field} value={editor.notes} onChange={e=>edit({notes:e.target.value})}/></label>
 <table style={{width:'100%'}}><thead><tr><th>Componente</th><th>Posto</th><th>Unidade</th><th>Valor da tarifa</th><th>Ação</th></tr></thead><tbody>{editor.items.map((i,index)=><tr key={index}><td><select aria-label={`Componente ${index+1}`} style={field} value={i.component} onChange={e=>edit({items:editor.items.map((v,n)=>n===index?{...v,component:e.target.value,label:labels[e.target.value]}:v)})}>{['TE','TUSD_ENERGY','TUSD_DEMAND_USED','TUSD_DEMAND_UNUSED','REACTIVE'].map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></td><td><select aria-label={`Posto ${index+1}`} style={field} value={i.band} onChange={e=>edit({items:editor.items.map((v,n)=>n===index?{...v,band:e.target.value}:v)})}>{['PEAK','OFF_PEAK','ALL'].map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></td><td><select aria-label={`Unidade ${index+1}`} style={field} value={i.measure} onChange={e=>edit({items:editor.items.map((v,n)=>n===index?{...v,measure:e.target.value}:v)})}>{['BRL_KWH','BRL_MWH','BRL_KW','BRL_KVARH'].map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></td><td><input aria-label={`Valor ${index+1}`} style={field} value={i.value} onChange={e=>edit({items:editor.items.map((v,n)=>n===index?{...v,value:e.target.value.replace(',','.')}:v)})}/></td><td><button type="button" style={button} onClick={()=>edit({items:editor.items.filter((_,n)=>n!==index)})}>Remover do rascunho</button></td></tr>)}</tbody></table>
 <button type="button" style={button} onClick={()=>edit({items:[...editor.items,{component:'TE',band:'PEAK',measure:'BRL_KWH',value:'',label:'Energia TE'}]})}>Adicionar componente</button><label>Justificativa do cadastro ou revisão<textarea style={field} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" style={button} disabled={busy} onClick={()=>run(async()=>{await apiRequest('/api/v1/tariff-library',{method:'POST',body:{...editor,...(previous?{previousId:previous}:{}),reason}});setEditor(null);await load();setMessage('Tabela salva com autor, justificativa e versão preservados.');})}>Salvar versão da biblioteca</button><button type="button" style={button} onClick={()=>setEditor(null)}>Cancelar edição</button></div>}
 {chosen&&<div role="dialog" aria-label="Aplicar biblioteca tarifária" style={{border:'2px solid #54cee7',padding:18,marginTop:15}} onChange={()=>setPreview(null)}><h4>Preencher parâmetros — {chosen.profile.distributor} · {chosen.profile.subgroup} · v{chosen.version}</h4><p>{chosen.profile.notes}</p>
 <label>Unidade para aplicação<select style={field} value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Selecione</option>{units.filter(u=>u.customer_id===customerId).map(u=><option value={u.id} key={u.id}>{u.name} · {u.consumer_unit_number}</option>)}</select></label><p>Cenário de comparação: {scenario||'Defina o mercado no cadastro da unidade'}. {scenario==='ACL'?'Simulação de migração ao mercado livre.':'Referência do mercado cativo para unidade ACL.'}</p>
 <label>Aplicar de<input style={field} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Aplicar até<input style={field} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><p>O período deve estar integralmente dentro da vigência da tabela. Mudanças dentro do mês exigem as duas referências.</p>
 {chosen.profile.endDate<new Date().toISOString().slice(0,10)&&<><p role="alert">Esta vigência está vencida. Atualize a biblioteca para períodos posteriores.</p><label><input type="checkbox" checked={expired} onChange={e=>setExpired(e.target.checked)}/> Confirmo uso histórico dentro da vigência original.</label><label>Justificativa do uso histórico<input style={field} value={expiredReason} onChange={e=>setExpiredReason(e.target.value)}/></label></>}
 <fieldset><legend>Componentes a preencher</legend>{chosen.profile.items.map(i=><label key={key(i)} style={{display:'block'}}><input type="checkbox" checked={selected.includes(key(i))} onChange={e=>setSelected(s=>e.target.checked?[...s,key(i)]:s.filter(k=>k!==key(i)))}/>{i.label} · {i.value} {labels[i.measure]}</label>)}</fieldset>
 <label>A tarifa tem impostos embutidos?<select style={field} value={gross} onChange={e=>setGross(e.target.value)}><option value="">Selecione</option><option value="YES">Sim — não acrescentar novamente</option><option value="NO">Não — informar tributos</option></select></label>
 {gross==='YES'&&<fieldset><legend>Quais tributos já estão nos valores selecionados?</legend>{codes.map(c=><label key={c}><input type="checkbox" checked={embedded.includes(c)} onChange={e=>setEmbedded(s=>e.target.checked?[...s,c]:s.filter(x=>x!==c))}/>{c} </label>)}<p>Esta declaração se aplica a todas as tarifas selecionadas. Se uma parcela tiver tratamento diferente, aplique-a em lote separado.</p></fieldset>}
 {gross==='NO'&&<section aria-label="Alíquotas e bases tributárias"><h4>Informar impostos</h4><p>Cada imposto usa sua própria base, sem somar impostos entre si. Confira o regime e os componentes antes de confirmar.</p>{taxes.map((t,index)=><fieldset key={t.code}><legend>{t.code}</legend><label>Alíquota {t.code} (%)<input style={field} inputMode="decimal" value={t.rate} onChange={e=>setTaxes(s=>s.map((v,n)=>n===index?{...v,rate:e.target.value.replace(',','.')}:v))}/></label><label>{t.code==='ICMS'?'ICMS é calculado por dentro?':`Forma de cálculo do ${t.code}`}<select style={field} value={t.mode} onChange={e=>setTaxes(s=>s.map((v,n)=>n===index?{...v,mode:e.target.value}:v))}><option value="">Selecione</option><option value="INSIDE">Sim — por dentro</option><option value="OUTSIDE">Não — por fora</option></select></label><p>Rubricas incluídas na base:</p>{chosen.profile.items.filter(i=>selected.includes(key(i))).map(i=><label key={key(i)} style={{display:'block'}}><input type="checkbox" checked={t.included.includes(key(i))} onChange={e=>setTaxes(s=>s.map((v,n)=>n===index?{...v,included:e.target.checked?[...v.included,key(i)]:v.included.filter(k=>k!==key(i))}:v))}/>{i.label}</label>)}</fieldset>)}</section>}
 <label>CIP — valor final mensal (R$; informe 0 se não houver)<input style={field} value={cip} onChange={e=>setCip(e.target.value.replace(',','.'))}/></label><label>Outro custo final mensal (R$; informe 0 se não houver)<input style={field} value={other} onChange={e=>setOther(e.target.value.replace(',','.'))}/></label><label>Descrição do outro custo<input style={field} value={otherLabel} onChange={e=>setOtherLabel(e.target.value)}/></label>
 {scenario==='ACL'&&<><label>Preço da energia do fornecedor para simulação ACL (R$/MWh)<input style={field} value={aclPrice} onChange={e=>setAclPrice(e.target.value.replace(',','.'))}/></label><label>Fonte / proposta da energia ACL<input style={field} value={aclSource} onChange={e=>setAclSource(e.target.value)}/></label></>}
 <label>Justificativa e fonte das condições tributárias<textarea style={field} value={why} onChange={e=>setWhy(e.target.value)}/></label><button type="button" style={button} disabled={busy} onClick={()=>run(async()=>setPreview(await apiRequest('/api/v1/tariff-library/'+chosen.id+'/preview',{method:'POST',body:payload()})))}>Conferir preenchimento automático</button>
 {preview&&<><h4>Prévia — {preview.rows.length} parâmetros</h4><ul>{preview.rows.map((r,index)=><li key={index}>{r.label} · {labels[r.time_band]} · {r.amount_text??'Já incluído'} {labels[r.measure]||r.measure} · {r.treatment}</li>)}</ul><ul>{preview.monthlyCosts.map((c,index)=><li key={index}>Custos mensais: {c.label} · R$ {c.amount} · valor final</li>)}</ul>{preview.notes.map(n=><p key={n}>{n}</p>)}<button type="button" style={button} disabled={busy||!canCreate||!canUpdate} onClick={()=>run(async()=>{const result=await apiRequest<{parameter_ids:string[];monthly_cost_id:string|null}>('/api/v1/tariff-library/'+chosen.id+'/apply',{method:'POST',body:payload()});setMessage(`${result.parameter_ids.length} parâmetros registrados em rascunho, com versão da biblioteca e autor.${result.monthly_cost_id?" CIP/outros registrados em Custos mensais.":""} Aprove tarifas antes dos tributos.`);setChosen(null);setPreview(null);onApplied();})}>Confirmar e criar parâmetros em lote</button></>}
 <button type="button" style={button} disabled={busy} onClick={()=>{setChosen(null);setPreview(null);}}>Fechar aplicação</button></div>}
 </>}
 </section>;
}
