 'use client';
import {FormEvent,useRef,useState} from 'react';
import {apiRequest} from '@/app/lib/api/client';
import {Button,Input,Alert} from '@/app/components/ui';
export default function VariableFeeCorrection({row,onSaved}:{row:{id:string;fixed_fee_monthly?:number;savings_percentage?:number};onSaved:(row:any)=>void}){
 const [history,setHistory]=useState<any[]|null>(null);
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef(''),lock=useRef(false);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');const f=new FormData(e.currentTarget);if(!request.current)request.current=crypto.randomUUID();try{const saved=await apiRequest<any>('/api/v1/contract-configurations/management/'+encodeURIComponent(row.id)+'/variable-correction',{method:'POST',body:{expectedFixed:Number(row.fixed_fee_monthly),expectedPercentage:Number(row.savings_percentage),percentage:Number(f.get('percentage')),reason:String(f.get('reason')),requestId:request.current}});onSaved(saved);setOpen(false);}catch(e){setError(e instanceof Error?e.message:'Correção não confirmada.');}finally{lock.current=false;setBusy(false);}}
 async function loadHistory(){try{setHistory(await apiRequest<any[]>('/api/v1/contract-configurations/management/'+encodeURIComponent(row.id)+'/variable-corrections'));}catch(e){setError(e instanceof Error?e.message:'Histórico indisponível.');}}
 return <section>{Number(row.fixed_fee_monthly)!==0?<Button type="button" variant="secondary" onClick={()=>setOpen(v=>!v)}>Corrigir cadastro para somente variável</Button>:null}<Button type="button" variant="secondary" onClick={()=>void loadHistory()}>Histórico de correções dos honorários</Button>{history?<div>{history.length?history.map(h=><p key={h.id}>{new Date(h.created_at).toLocaleString('pt-BR')} · Fixo: R$ {h.before_row.fixed_fee_monthly} → R$ {h.after_row.fixed_fee_monthly}; variável: {h.before_row.savings_percentage}% → {h.after_row.savings_percentage}%. Fonte: {h.reason}. Autor: {h.actor}.</p>):<p>Nenhuma correção registrada.</p>}</div>:null}{!open&&error?<Alert variant="error">{error}</Alert>:null}{open?<form onSubmit={save} onChange={()=>{request.current='';}}><p>O fixo ficará em R$ 0,00. A correção preserva o contrato anterior no histórico de auditoria e não altera apurações já publicadas.</p>{error?<Alert variant="error">{error}</Alert>:null}<fieldset disabled={busy}><Input name="percentage" label="Percentual variável confirmado (%)" type="number" min="0.0001" max="100" step="0.0001" required defaultValue={row.savings_percentage}/><Input name="reason" label="Fonte e justificativa da correção do cadastro" minLength={10} maxLength={4096} required/><label><input type="checkbox" required/>Confirmei que o contrato cobra somente a parcela variável.</label><Button type="submit">{busy?'Corrigindo...':'Salvar correção auditada'}</Button></fieldset></form>:null}</section>;
}
