export enum Permission {
  // Contratos
  CREATE_CONTRACT = 'CREATE_CONTRACT',
  READ_CONTRACT = 'READ_CONTRACT',
  UPDATE_CONTRACT = 'UPDATE_CONTRACT',
  DELETE_CONTRACT = 'DELETE_CONTRACT',

  // Fees
  CREATE_FEE = 'CREATE_FEE',
  READ_FEE = 'READ_FEE',
  APPROVE_FEE = 'APPROVE_FEE',
  PUBLISH_FEE = 'PUBLISH_FEE',

  // Backoffice
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_DATA = 'EXPORT_DATA',

  // Usuários
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_AUDIT = 'VIEW_AUDIT',
}
