'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest,ApiError} from '@/app/lib/api/client';
import WorkflowModal from '../contracts/WorkflowModal';
type Row={id:string;provider_id:string;event:string;payment_id:string;received_at:string;company:string|null;status:string;gross_cents:number|null;proposal_id:string|null};
type Payment={grossCents:number;netCents:number|null;status:string};
type Check={version:number;status:string;note:string;actor_name:string|null;actor_id:string;created_at:string;summary:Payment|null};
type Detail={event:Row&{summary:Payment};binding:{id:string;gross_cents:number;proposal_id:string;company:string;actor_name:string|null;actor_id:string;justification:string}|null;checks:Check[]};
const endpoint='/api/v1/admin/sales/asaas';
const names:Record<string,string>={PENDING:'Aguardando conferência',UNLINKED:'Sem vínculo',PROCESSING:'Em conferência',REVIEW:'Requer análise',VERIFIED:'Conferido no sandbox'};
const money=(v:number|null|undefined)=>v==null?'Não informado':(v/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const message=(e:unknown)=>e instanceof ApiError?e.message:'Consulta sandbox indisponível.';
const actions={display:'flex',gap:12,flexWrap:'wrap' as const,marginTop:16};
export default function AsaasSandbox(){
 const [data,setData]=useState<{rows:Row[];total:number;bindings:number}|null>(null),[page,setPage]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filter,setFilter]=useState(''),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState<Detail|null>(null),[insert,setInsert]=useState(false),[id,setId]=useState(''),[proposalId,setProposalId]=useState(''),[paymentId,setPaymentId]=useState(''),[customerId,setCustomerId]=useState(''),[justification,setJustification]=useState('');
 useEffect(()=>{let live=true;setData(null);setError('');apiRequest<{rows:Row[];total:number;bindings:number}>(endpoint+'?page='+page+filter).then(v=>{if(live)setData(v);}).catch(e=>{if(live)setError(message(e));});return()=>{live=false;};},[page,filter,refresh]);
 const submit=(e:FormEvent)=>{e.preventDefault();setPage(0);setDetail(null);setFilter('&search='+encodeURIComponent(search)+'&status='+status+(from?'&from='+from:'')+(to?'&to='+to:''));setRefresh(v=>v+1);};
 const read=async(row:Row)=>{setBusy(true);setError('');try{setDetail(await apiRequest<Detail>(endpoint+'/'+row.id));}catch(e){setError(message(e));}finally{setBusy(false);}};
 const verify=async()=>{if(!detail)return;setBusy(true);setError('');try{await apiRequest(endpoint+'/'+detail.event.id+'/verify',{method:'POST'});setDetail(await apiRequest<Detail>(endpoint+'/'+detail.event.id));setRefresh(v=>v+1);}catch(e){setError(message(e));try{setDetail(await apiRequest<Detail>(endpoint+'/'+detail.event.id));}catch{/* Preserve current view on unavailability. */}}finally{setBusy(false);}};
 const bind=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await apiRequest(endpoint+'/bindings',{method:'POST',body:{id,proposalId,paymentId,customerId,justification}});setInsert(false);setRefresh(v=>v+1);}catch(e){setError(message(e));}finally{setBusy(false);}};
 return <Card title="Financeiro comercial · Asaas sandbox"><p>Ambiente de teste exclusivo do Owner. A etapa 4A não cria cobranças, recorrência, assinatura, nota fiscal ou licenças. Conferido significa compatibilidade do evento com a consulta no sandbox.</p>{error&&!detail&&!insert?<Alert>{error}</Alert>:null}<div style={actions}><Button variant="secondary" onClick={()=>setRefresh(v=>v+1)}>Atualizar sandbox</Button><Button disabled={!data||busy} onClick={()=>{setId(crypto.randomUUID());setProposalId('');setPaymentId('');setCustomerId('');setJustification('');setError('');setInsert(true);}}>Inserir vínculo de teste</Button></div>{data?<><details><summary>Filtros avançados</summary><form onSubmit={submit}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:16}}><Input label="Empresa, proposta ou evento" value={search} maxLength={100} onChange={e=>setSearch(e.target.value)}/><label className="ds-field"><span className="ds-label">Situação</span><select className="ds-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todas</option>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><Input type="date" label="Recebido a partir de" value={from} onChange={e=>setFrom(e.target.value)}/><Input type="date" label="Recebido até" value={to} onChange={e=>setTo(e.target.value)}/></div><Button type="submit">Aplicar filtros</Button></form></details><p>{data.bindings} vínculos de teste · {data.total} eventos</p><div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Empresa / evento</th><th>Situação</th><th>Primeiro ciclo previsto</th><th>Recebido</th><th>Ação</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><td>{row.company??'Sem vínculo comercial'}<br/>{row.provider_id}<br/>{row.event}</td><td>{names[row.status]??row.status}</td><td>{money(row.gross_cents)}</td><td>{new Date(row.received_at).toLocaleString('pt-BR')}</td><td><Button variant="secondary" disabled={busy} onClick={()=>void read(row)}>Detalhes</Button></td></tr>)}</tbody></table></div>{!data.rows.length?<p>Nenhum evento recebido. Não são apresentados dados ilustrativos.</p>:null}<div style={actions}><Button variant="secondary" disabled={page===0} onClick={()=>setPage(v=>v-1)}>Anterior</Button><span>Página {page+1}</span><Button variant="secondary" disabled={(page+1)*25>=data.total||page>=1000} onClick={()=>setPage(v=>v+1)}>Próxima</Button></div></>:null}
 {insert?<WorkflowModal title="Vínculo financeiro sandbox" onClose={()=>{if(!busy)setInsert(false);}}>{error?<Alert>{error}</Alert>:null}<p>Registra uma referência a cobrança de teste já existente no sandbox. Não cria cliente ou cobrança no Asaas. O valor inicial vem da proposta aprovada, incluindo os adicionais únicos. A referência externa da cobrança deverá corresponder a este vínculo: <span style={{overflowWrap:'anywhere'}}>{id}</span>.</p><form onSubmit={bind}><fieldset disabled={busy} style={{border:0,padding:0}}><Input label="ID da proposta aprovada" required value={proposalId} onChange={e=>{setProposalId(e.target.value);setId(crypto.randomUUID());}}/><Input label="ID da cobrança sandbox (pay_)" required value={paymentId} onChange={e=>{setPaymentId(e.target.value);setId(crypto.randomUUID());}}/><Input label="ID do cliente sandbox (cus_)" required value={customerId} onChange={e=>{setCustomerId(e.target.value);setId(crypto.randomUUID());}}/><Input label="Justificativa" required minLength={5} maxLength={1000} value={justification} onChange={e=>{setJustification(e.target.value);setId(crypto.randomUUID());}}/><Button type="submit">Preservar vínculo interno</Button></fieldset></form></WorkflowModal>:null}
 {detail?<WorkflowModal title="Evento financeiro sandbox" onClose={()=>{if(!busy)setDetail(null);}}>{error?<Alert>{error}</Alert>:null}<p>{detail.binding?.company??'Sem vínculo'} · {detail.event.event}<br/>ID do evento: {detail.event.provider_id}<br/>Cobrança: {detail.event.payment_id}</p><Card title="Valores informados na notificação"><p>Bruto: {money(detail.event.summary.grossCents)}<br/>Líquido: {money(detail.event.summary.netCents)}<br/>Diferença bruto − líquido: {detail.event.summary.netCents===null?'Aguardando informação':money(detail.event.summary.grossCents-detail.event.summary.netCents)}</p><p>Estes valores ainda precisam de conferência. A diferença não comprova, sozinha, a composição das taxas.</p></Card>{detail.binding?<details><summary>Vínculo preservado</summary><p>Proposta: {detail.binding.proposal_id}<br/>Primeiro ciclo previsto: {money(detail.binding.gross_cents)}<br/>Autor: {detail.binding.actor_name??'Nome não disponível'} (registrado na época)<br/>ID: {detail.binding.actor_id}<br/>{detail.binding.justification}</p></details>:null}<details open><summary>Histórico de conferências</summary>{detail.checks.length?detail.checks.map(c=><p key={c.version}>{names[c.status]} · {new Date(c.created_at).toLocaleString('pt-BR')}<br/>{c.actor_name??'Nome não disponível'} (registrado na época) · ID: {c.actor_id}<br/>{c.note}</p>):<p>Aguardando conferência.</p>}</details><Button variant="secondary" disabled={busy||!detail.binding} onClick={()=>void verify()}>Conferir novamente no sandbox</Button><p>A consulta externa depende de habilitação específica; não cria ou altera cobranças.</p></WorkflowModal>:null}
 </Card>;
}
