'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest,ApiError} from '@/app/lib/api/client';
import WorkflowModal from '../contracts/WorkflowModal';
type Event={version:number;status:string;actor_id:string;actor_name:string|null;created_at:string;justification:string};
type Definition={title:string;clauses:{title:string;text:string}[]};
type Template={id:string;revision:number;latest_revision:number;definition:Definition;events:Event[]};
type Draft={id:string;customer_name:string;proposal_id:string;terms_revision:number;template_revision:number;status:string;version:number;sha256:string;created_at:string;actor_name:string|null;actor_id:string};
type Detail=Draft&{events:Event[];justification:string;snapshot:{parties:{supplier:Party;customer:Party};template:{definition:Definition};proposal:{snapshot:Record<string,unknown>};terms:{definition:Record<string,string>}}};
type Party={name:string;document:string;address:string;signatory:string;email:string};
type Data={templates:Template[];drafts:Draft[];total:number;totalTemplates:number};
const endpoint='/api/v1/admin/sales/contracts',grid={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:16},buttons={display:'flex',gap:12,flexWrap:'wrap' as const,marginTop:16};
const labels:Record<string,string>={DRAFT:'Rascunho',CHECKED:'Conferido',APPROVED_INTERNAL:'Aprovado internamente'};
const blankParty=():Party=>({name:'',document:'',address:'',signatory:'',email:''});
const initial:Definition={title:'Licenciamento EnergyOS — modelo preliminar',clauses:[
 {title:'Objeto e escopo',text:'O objeto proposto é o acesso ao EnergyOS nos módulos e limites descritos no quadro comercial anexo. Esta minuta depende de conferência das partes, do escopo e das condições antes de qualquer assinatura.'},
 {title:'Uso e responsabilidades',text:'Cada usuário deverá utilizar seu acesso individual conforme o vínculo e as permissões concedidas. A contratante deverá indicar os responsáveis por administrar seus usuários e conferir os dados inseridos no ambiente.'},
 {title:'Resultados e validação humana',text:'Análises, previsões e informações de inteligência artificial apoiam a operação e exigem conferência das fontes e premissas. A contratação não estabelece garantia de economia de energia, retorno financeiro ou ausência de divergências nos dados de origem.'},
 {title:'Preço, pagamento e implantação',text:'Valores, moeda, periodicidade, impostos incluídos, implantação e suporte estão descritos nas condições comerciais anexas, preservadas na versão selecionada. A aprovação desta minuta interna não cria cobrança ou libera acesso.'},
 {title:'Prazo, renovação e cancelamento',text:'O prazo e a condição de renovação devem corresponder ao anexo comercial. [PENDENTE: definir aviso prévio, procedimento de cancelamento e tratamento das obrigações remanescentes antes de aprovar este modelo.]'},
 {title:'Dados, confidencialidade e encerramento',text:'[PENDENTE: definir responsabilidades sobre dados pessoais, confidencialidade, retenção, exportação e encerramento do acesso. Conferir compatibilidade com a política de privacidade e com as funcionalidades implantadas.]'},
 {title:'Conferência final',text:'[PENDENTE: conferir qualificação das partes e poderes dos signatários, anexos, responsabilidades, tratamento de controvérsias e disposições finais. Este texto preliminar não deve ser enviado para assinatura.]'}
]};
const errorText=(e:unknown)=>e instanceof ApiError?e.message:'Minutas indisponíveis. Atualize antes de tentar novamente.';
function History({events}:{events:Event[]}){return <details><summary>Histórico preservado</summary>{events.map(e=><p key={e.version}>{labels[e.status]} · {new Date(e.created_at).toLocaleString('pt-BR')}<br/>{e.actor_name??'Nome não disponível'} (registrado na época) · ID: {e.actor_id}<br/>{e.justification}</p>)}</details>;}
export default function ContractDrafts({proposalId}:{proposalId?:string}){
 const [data,setData]=useState<Data|null>(null),[page,setPage]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[status,setStatus]=useState(''),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [modal,setModal]=useState<'template'|'create'|'detail'|'review'|null>(null),[template,setTemplate]=useState<Template|null>(null),[definition,setDefinition]=useState<Definition>(initial),[detail,setDetail]=useState<Detail|null>(null),[reviewTarget,setReviewTarget]=useState<{id:string;kind:string;revision:number;event:Event}|null>(null);
 const [requestId,setRequestId]=useState(()=>crypto.randomUUID()),[recordId,setRecordId]=useState(()=>crypto.randomUUID()),[justification,setJustification]=useState(''),[terms,setTerms]=useState<{revision:number;status:string;expired:boolean}[]>([]),[termsRevision,setTermsRevision]=useState(''),[templateKey,setTemplateKey]=useState(''),[supplier,setSupplier]=useState<Party>(blankParty),[customer,setCustomer]=useState<Party>(blankParty);
 useEffect(()=>{let live=true;setData(null);setError('');apiRequest<Data>(endpoint+'?page='+page+'&search='+encodeURIComponent(proposalId??filter)+'&status='+status).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[page,filter,status,refresh,proposalId]);
 const close=()=>{if(!busy){setModal(null);setDetail(null);setTemplate(null);setReviewTarget(null);}};
 const open=(kind:typeof modal)=>{setError('');setJustification('');setRequestId(crypto.randomUUID());setRecordId(crypto.randomUUID());setModal(kind);};
 const edit=()=>setRequestId(crypto.randomUUID());
 const save=async(path:string,body:unknown)=>{setBusy(true);setError('');try{await apiRequest(endpoint+path,{method:'POST',body});setModal(null);setDetail(null);setRefresh(v=>v+1);}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const read=async(id:string)=>{setBusy(true);setError('');try{setDetail(await apiRequest<Detail>(endpoint+'/'+id));setModal('detail');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const pdf=async(id:string)=>{setBusy(true);setError('');try{const blob=await apiRequest<Blob>(endpoint+'/'+id+'/pdf',{responseType:'blob',cache:'no-store'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='energyos-minuta-'+id+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const startCreate=async()=>{if(!proposalId)return;setBusy(true);setError('');try{const result=await apiRequest<{revisions:{revision:number;status:string;expired:boolean}[]}>('/api/v1/admin/sales/commercial/proposals/'+proposalId+'/terms');setTerms(result.revisions);setTermsRevision('');setTemplateKey('');setSupplier(blankParty());setCustomer(blankParty());open('create');}catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const partyForm=(title:string,value:Party,set:(v:Party)=>void)=><Card title={title}><div style={grid}>{Object.entries({name:'Razão social',document:'CNPJ / documento',address:'Endereço',signatory:'Nome completo do signatário',email:'E-mail do signatário'}).map(([key,label])=><Input key={key} label={label} type={key==='email'?'email':'text'} required minLength={3} maxLength={500} value={value[key as keyof Party]} onChange={e=>{set({...value,[key]:e.target.value});setRecordId(crypto.randomUUID());}}/>)}</div></Card>;
 const startReview=(id:string,kind:string,revision:number,event:Event)=>{setReviewTarget({id,kind,revision,event});open('review');};
 return <Card title="Minutas contratuais internas"><p>Exclusivo do Owner. Modelos e condições precisam ser conferidos; esta etapa não envia, assina, cobra ou ativa licenças.</p>{error?<Alert>{error}</Alert>:null}<div style={buttons}><Button variant="secondary" disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Atualizar minutas</Button>{proposalId?<Button disabled={busy||!data} onClick={()=>void startCreate()}>Preparar minuta</Button>:<Button disabled={busy||!data} onClick={()=>{setTemplate(null);setDefinition(initial);open('template');}}>Inserir modelo</Button>}</div>
 {data&&!proposalId?<><details style={{marginTop:16}}><summary>Modelos contratuais · {data.totalTemplates}</summary>{data.templates.map(t=><Card key={t.id+":"+t.revision} title={t.definition.title}><p>Revisão {t.revision} · {labels[t.events.at(-1)?.status??'DRAFT']}</p><details><summary>Cláusulas desta revisão</summary>{t.definition.clauses.map((c,i)=><section key={i}><h3>{c.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{c.text}</p></section>)}</details><History events={t.events}/><div style={buttons}><Button variant="secondary" disabled={busy||t.revision!==t.latest_revision} onClick={()=>{setTemplate(t);setDefinition(t.definition);open('template');}}>Nova revisão</Button>{t.revision===t.latest_revision&&t.events.at(-1)?.status!=='APPROVED_INTERNAL'?<Button disabled={busy} onClick={()=>startReview(t.id,'template',t.revision,t.events.at(-1)!)}>Conferir modelo</Button>:null}</div></Card>)}</details><form onSubmit={(e:FormEvent)=>{e.preventDefault();setFilter(query);setPage(0);}} style={buttons}><Input label="Empresa ou ID da proposta" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/><label className="ds-field"><span className="ds-label">Situação</span><select className="ds-input" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Todas</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><Button type="submit">Filtrar</Button></form></>:null}
 {data?<><p>{data.total} minutas encontradas.</p><div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Empresa e minuta</th><th>Situação</th><th>Registro</th><th>Ação</th></tr></thead><tbody>{data.drafts.map(d=><tr key={d.id}><td style={{overflowWrap:'anywhere'}}><strong>{d.customer_name}</strong><br/>{d.id}<br/>Proposta: {d.proposal_id}</td><td>{labels[d.status]}</td><td>{new Date(d.created_at).toLocaleString('pt-BR')}<br/>{d.actor_name??'Nome não disponível'}</td><td><Button variant="secondary" disabled={busy} onClick={()=>void read(d.id)}>Abrir</Button></td></tr>)}</tbody></table></div><div style={buttons}><Button variant="secondary" disabled={busy||page===0} onClick={()=>setPage(v=>v-1)}>Anterior</Button><span>Página {page+1}</span><Button variant="secondary" disabled={busy||page>=1000||(page+1)*25>=Math.max(data.total,proposalId?0:data.totalTemplates)} onClick={()=>setPage(v=>v+1)}>Próxima</Button></div></>:null}
 {modal?<WorkflowModal title={{template:'Modelo contratual versionado',create:'Preparar minuta interna',detail:'Minuta preservada',review:'Conferência interna'}[modal]} onClose={close}>{error?<Alert>{error}</Alert>:null}
 {modal==='template'?<form onSubmit={e=>{e.preventDefault();void save('/templates',{id:template?.id??recordId,requestId,expectedRevision:template?.revision??0,definition,justification});}}><fieldset disabled={busy} style={{border:0,padding:0}}><p>Texto preliminar para revisão. Substitua os campos PENDENTE antes de conferir e aprovar; nenhuma cláusula está aprovada automaticamente.</p><Input label="Título do modelo" required minLength={5} maxLength={120} value={definition.title} onChange={e=>{setDefinition({...definition,title:e.target.value});edit();}}/>{definition.clauses.map((c,i)=><Card key={i} title={'Cláusula '+(i+1)}><Input label="Título da cláusula" required minLength={3} maxLength={120} value={c.title} onChange={e=>{setDefinition({...definition,clauses:definition.clauses.map((x,j)=>j===i?{...x,title:e.target.value}:x)});edit();}}/><label className="ds-field"><span className="ds-label">Texto</span><textarea className="ds-input" rows={5} required minLength={10} maxLength={2000} value={c.text} onChange={e=>{setDefinition({...definition,clauses:definition.clauses.map((x,j)=>j===i?{...x,text:e.target.value}:x)});edit();}}/></label><Button variant="secondary" disabled={definition.clauses.length===1} onClick={()=>{setDefinition({...definition,clauses:definition.clauses.filter((_,j)=>j!==i)});edit();}}>Remover cláusula</Button></Card>)}<Button variant="secondary" disabled={definition.clauses.length>=30} onClick={()=>{setDefinition({...definition,clauses:[...definition.clauses,{title:'',text:''}]});edit();}}>Inserir cláusula</Button><Input label="Justificativa da revisão" required minLength={5} maxLength={1000} value={justification} onChange={e=>{setJustification(e.target.value);edit();}}/><Button type="submit">Preservar modelo em rascunho</Button></fieldset></form>:null}
 {modal==='create'?<form onSubmit={e=>{e.preventDefault();const [templateId,revision]=templateKey.split(':');void save('',{id:recordId,proposalId,termsRevision:Number(termsRevision),templateId,templateRevision:Number(revision),parties:{supplier,customer},justification});}}><fieldset disabled={busy} style={{border:0,padding:0}}><p>Proposta: {proposalId}. Preencha e confira as partes; o contato comercial não é presumido como signatário.</p><div style={grid}><label className="ds-field"><span className="ds-label">Condições aprovadas e vigentes</span><select className="ds-input" required value={termsRevision} onChange={e=>{setTermsRevision(e.target.value);setRecordId(crypto.randomUUID());}}><option value="">Selecione</option>{terms.filter(t=>t.status==='APPROVED_INTERNAL'&&!t.expired).map(t=><option key={t.revision} value={t.revision}>Revisão {t.revision}</option>)}</select></label><label className="ds-field"><span className="ds-label">Modelo aprovado</span><select className="ds-input" required value={templateKey} onChange={e=>{setTemplateKey(e.target.value);setRecordId(crypto.randomUUID());}}><option value="">Selecione</option>{data?.templates.filter(t=>t.events.at(-1)?.status==='APPROVED_INTERNAL').map(t=><option key={t.id+":"+t.revision} value={t.id+':'+t.revision}>{t.definition.title} · r{t.revision}</option>)}</select></label></div>{partyForm('Prestadora',supplier,setSupplier)}{partyForm('Contratante',customer,setCustomer)}<Input label="Justificativa da minuta" required minLength={5} maxLength={1000} value={justification} onChange={e=>{setJustification(e.target.value);setRecordId(crypto.randomUUID());}}/><p>O backend preservará proposta, condições, modelo e PDF em uma única gravação. Falhas não criam uma minuta incompleta.</p><Button type="submit">Gerar e preservar minuta interna</Button></fieldset></form>:null}
 {modal==='detail'&&detail?<><p>Minuta: {detail.id}<br/>Documento preservado · SHA-256: <span style={{overflowWrap:'anywhere'}}>{detail.sha256}</span></p><Card title="Partes"><p>Prestadora: {detail.snapshot.parties.supplier.name}<br/>Contratante: {detail.snapshot.parties.customer.name}<br/>Signatário indicado: {detail.snapshot.parties.customer.signatory}</p></Card><details><summary>Oferta, condições e cláusulas preservadas</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(detail.snapshot,null,2)}</pre></details><History events={detail.events}/><div style={buttons}><Button variant="secondary" disabled={busy} onClick={()=>void pdf(detail.id)}>Baixar PDF interno preservado</Button>{detail.events.at(-1)?.status!=='APPROVED_INTERNAL'?<Button disabled={busy} onClick={()=>startReview(detail.id,'draft',1,detail.events.at(-1)!)}>Conferir minuta</Button>:null}</div></>:null}
 {modal==='review'&&reviewTarget?<form onSubmit={e=>{e.preventDefault();void save('/reviews',{id:reviewTarget.id,requestId,kind:reviewTarget.kind,revision:reviewTarget.revision,expectedVersion:reviewTarget.event.version,status:reviewTarget.event.status==='DRAFT'?'CHECKED':'APPROVED_INTERNAL',justification});}}><fieldset disabled={busy} style={{border:0,padding:0}}><p>Registro: {reviewTarget.id}. {labels[reviewTarget.event.status]}. Aprovação somente interna; não equivale à assinatura das partes.</p><details open><summary>Conteúdo para conferência</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(reviewTarget.kind==='template'?data?.templates.find(t=>t.id===reviewTarget.id&&t.revision===reviewTarget.revision)?.definition:detail?.snapshot,null,2)}</pre></details><Input label="Justificativa da conferência" required minLength={5} maxLength={1000} value={justification} onChange={e=>{setJustification(e.target.value);edit();}}/><Button type="submit">{reviewTarget.event.status==='DRAFT'?'Registrar conferência':'Aprovar internamente'}</Button></fieldset></form>:null}
 </WorkflowModal>:null}</Card>;
}
