'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Alert,Button,Card,Input} from '@/app/components/ui';
import {apiRequest,ApiError} from '@/app/lib/api/client';
import WorkflowModal from '../contracts/WorkflowModal';
type Definition={validUntil:string;contractTerm:string;paymentTerms:string;implementationTerms:string;supportTerms:string;renewalCancellationTerms:string;exclusions:string};
type Event={version:number;status:string;actor_id:string;actor_name:string|null;created_at:string;justification:string};
type Revision={revision:number;definition:Definition;actor_id:string;actor_name:string|null;created_at:string;justification:string;expired:boolean|null;events:Event[]};
type Data={asOfDate:string;proposal:{id:string;snapshot:{planName:string;planVersion:number;policyVersion:number;units:number;users:number;documentsLimit?:number|null;cycle:string;monthlyRecurringCents:number;annualRecurringCents:number;policy:{starts:string;ends:string}}};revisions:Revision[]};
const endpoint='/api/v1/admin/sales/commercial';
const empty:Definition={validUntil:'',contractTerm:'',paymentTerms:'',implementationTerms:'',supportTerms:'',renewalCancellationTerms:'',exclusions:''};
const labels:Record<keyof Definition,string>={validUntil:'Validade da oferta',contractTerm:'Prazo de contratação proposto',paymentTerms:'Condições de pagamento',implementationTerms:'Implantação e inclusões',supportTerms:'Condições de suporte',renewalCancellationTerms:'Renovação e cancelamento',exclusions:'Exclusões do escopo'};
const statuses:Record<string,string>={DRAFT:'Rascunho',CHECKED:'Conferida',APPROVED_INTERNAL:'Aprovada internamente'};
const errorText=(e:unknown)=>e instanceof ApiError?e.message:'Condições comerciais indisponíveis. Tente atualizar.';
function TermsWorkspace({id}:{id:string}){
 const [data,setData]=useState<Data|null>(null),[definition,setDefinition]=useState<Definition>(empty),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[justification,setJustification]=useState(''),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
 const load=async()=>{const d=await apiRequest<Data>(endpoint+'/proposals/'+id+'/terms',{cache:'no-store'});setData(d);return d;};
 useEffect(()=>{let live=true;apiRequest<Data>(endpoint+'/proposals/'+id+'/terms',{cache:'no-store'}).then(d=>{if(live){setData(d);setDefinition(d.revisions[0]?.definition??empty);setEditing(d.revisions.length===0);}}).catch(e=>{if(live)setError(errorText(e));});return()=>{live=false;};},[id]);
 const current=data?.revisions[0],event=current?.events.at(-1),snapshot=data?.proposal.snapshot;
 const newRevision=()=>{setDefinition(current?.definition??empty);setJustification('');setRequestId(crypto.randomUUID());setEditing(true);};
 const mutate=async(e:FormEvent,review:boolean)=>{e.preventDefault();setBusy(true);setError('');try{
  await apiRequest(endpoint+(review?'/offer-term-reviews':'/offer-terms'),{method:'POST',body:review?{requestId,proposalId:id,revision:current!.revision,expectedVersion:event!.version,status:event!.status==='DRAFT'?'CHECKED':'APPROVED_INTERNAL',justification}:{requestId,proposalId:id,expectedRevision:current?.revision??0,definition,justification}});
  await load();setEditing(false);setJustification('');setRequestId(crypto.randomUUID());
 }catch(e){setError(errorText(e));}finally{setBusy(false);}};
 const actionJustification=<Input label="Justificativa da ação (sem dados pessoais)" value={justification} required minLength={5} maxLength={1000} onChange={e=>{setJustification(e.target.value);setRequestId(crypto.randomUUID());}}/>;
 const renderDefinition=(d:Definition)=><dl>{Object.entries(labels).map(([key,label])=><div key={key} style={{padding:'10px 0',borderBottom:'1px solid #405571'}}><dt className="ds-label">{label}</dt><dd style={{margin:'6px 0',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{d[key as keyof Definition]||'Não preenchido'}</dd></div>)}</dl>;
 return <><p>Minuta interna. A aprovação destas condições não registra aceite do cliente, assinatura, envio, cobrança ou licença.</p>{error?<Alert>{error}</Alert>:null}{!data?<Button variant="secondary" disabled={busy} onClick={()=>{setBusy(true);load().then(d=>{setDefinition(d.revisions[0]?.definition??empty);setEditing(!d.revisions.length);setError('');}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>Atualizar condições</Button>:null}{snapshot&&data?<>
 <Card title="Proposta aprovada · somente leitura"><p>{snapshot.planName} · catálogo v{snapshot.planVersion} · política v{snapshot.policyVersion}</p><p>{snapshot.units} unidades · {snapshot.users} usuários · Documentos: {snapshot.documentsLimit===null?'ilimitados':snapshot.documentsLimit??'não registrado nesta versão'}</p><p>{(snapshot.monthlyRecurringCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/mês · {(snapshot.annualRecurringCents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/ano. Periodicidade escolhida: {snapshot.cycle==='ANNUAL'?'anual':'mensal'}.</p><p>Vigência dos preços: {snapshot.policy.starts} a {snapshot.policy.ends}. Datas de validação no backend: {data.asOfDate} (UTC).</p></Card>
 <p>Custos ou módulos novos exigem uma nova proposta pelo motor comercial. Preencher condições não altera os valores acima.</p>
 <Button variant="secondary" disabled={busy} onClick={()=>{setBusy(true);load().then(()=>{setError('');setRequestId(crypto.randomUUID());}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>Atualizar histórico</Button>
 {!editing?<Button variant="secondary" disabled={busy} onClick={newRevision}>Nova revisão das condições</Button>:null}
 {editing?<form onSubmit={e=>void mutate(e,false)}><fieldset disabled={busy} style={{border:0,padding:0}}><h3>{current?'Nova revisão após v'+current.revision:'Primeira revisão das condições'}</h3><Input label={labels.validUntil} type="date" max={snapshot.policy.ends} min={snapshot.policy.starts} value={definition.validUntil} onChange={e=>{setDefinition(v=>({...v,validUntil:e.target.value}));setRequestId(crypto.randomUUID());}}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16}}>{(Object.keys(labels) as (keyof Definition)[]).filter(k=>k!=='validUntil').map(key=><label className="ds-field" key={key}><span className="ds-label">{labels[key]}</span><textarea className="ds-input" style={{minHeight:110}} maxLength={1000} value={definition[key]} onChange={e=>{setDefinition(v=>({...v,[key]:e.target.value}));setRequestId(crypto.randomUUID());}}/></label>)}</div><p>O rascunho pode estar incompleto. Conferir e aprovar exige todos os campos preenchidos e validade compatível com os preços.</p>{actionJustification}<div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Button type="submit">{busy?'Salvando…':'Preservar rascunho'}</Button>{current?<Button variant="secondary" onClick={()=>setEditing(false)}>Cancelar edição</Button>:null}</div></fieldset></form>:current?<Card title={'Minuta preservada · revisão '+current.revision}><p>{statuses[event?.status??'DRAFT']} · {current.expired===true?'Validade vencida':current.expired===null?'Validade não preenchida':'Validade registrada'}</p>{renderDefinition(current.definition)}{event&&event.status!=='APPROVED_INTERNAL'?<form onSubmit={e=>void mutate(e,true)}><fieldset disabled={busy} style={{border:0,padding:0}}>{actionJustification}<Button type="submit" disabled={current.expired===true}>{event.status==='DRAFT'?'Registrar conferência':'Aprovar condições internamente'}</Button></fieldset></form>:<p>Condições aprovadas internamente; contratação permanece em etapa separada.</p>}</Card>:null}
 <details style={{marginTop:20}}><summary>Histórico preservado · {data.revisions.length} revisões mais recentes</summary>{data.revisions.map(r=><details key={r.revision} style={{marginTop:12}}><summary>Revisão {r.revision} · {statuses[r.events.at(-1)?.status??'DRAFT']}</summary><p>{r.actor_name??'Nome não disponível'} · registrado na época · ID original: {r.actor_id}<br/>{r.justification}</p>{renderDefinition(r.definition)}{r.events.map(e=><p key={e.version}>{statuses[e.status]} · {new Date(e.created_at).toLocaleString('pt-BR')} · {e.actor_name??'Nome não disponível'} · registrado na época · ID original: {e.actor_id}<br/>{e.justification}</p>)}</details>)}</details>
 </>:null}</>;
}
export default function OfferTerms({id}:{id:string}){const [open,setOpen]=useState(false);return <><Button variant="secondary" onClick={()=>setOpen(true)}>Condições da oferta</Button>{open?<WorkflowModal title="Condições da oferta · minuta interna" onClose={()=>setOpen(false)}><TermsWorkspace key={id} id={id}/></WorkflowModal>:null}</>;}
