'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Eye,Play,Plus,CalendarDays,ShieldCheck} from 'lucide-react';
import BackofficeShell from '@/app/components/BackofficeShell';
import ProtectedRoute from '@/app/components/ProtectedRoute';
import {Alert,Button,Card} from '@/app/components/ui';
import {apiRequest} from '@/app/lib/api/client';
import {useAuth} from '@/app/providers';
import styles from './registrations.module.css';
const view='f5364101-4486-42c2-a90f-807937ac3001';
type Row={id:string;customer_id:string;consumer_unit_id:string;agenda_id:string|null;month:string;operation:string;title:string;notes:string;deadline:string;evidence_reference:string;status:string;revision:number};
type Workspace={organizationId:string;rows:Row[];canManage:boolean;canApprove:boolean;transmissionEnabled:boolean;disclosure:string};
type Option={id:string;name?:string;legal_name?:string;unit_name?:string;customer_id?:string;title?:string;consumer_unit_id?:string;due_at?:string;ends_at?:string;starts_at?:string;status?:string};
const statuses:Record<string,string>={DRAFT:'Rascunho',REVIEW:'Em revisão',APPROVED:'Aprovado internamente',CANCELLED:'Cancelado'};
const operations:Record<string,string>={REGISTER_CONTRACT:'Registro de contrato livre',VALIDATE_AMOUNTS:'Validação de contrato e montantes'};
const date=(v:string)=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});
function Workspace(){
 const {context,hasPermission}=useAuth();const org=context?.scope==='organization'?context.currentOrganization.id:'';
 const [state,setState]=useState<Workspace|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Row|null|undefined>(undefined),[history,setHistory]=useState<{revision:number;reason:string;recorded_at:string;actor_id:string}[]|null>(null),[customers,setCustomers]=useState<Option[]>([]),[units,setUnits]=useState<Option[]>([]),[agenda,setAgenda]=useState<Option[]>([]),[customer,setCustomer]=useState(''),[unit,setUnit]=useState(''),[agendaId,setAgendaId]=useState(''),[month,setMonth]=useState('');
 const modal=useRef<HTMLDialogElement>(null),audit=useRef<HTMLDialogElement>(null),generation=useRef(0);
 useEffect(()=>{const n=++generation.current;if(!org)return;apiRequest<Workspace>('/api/v1/ccee-registrations').then(v=>{if(n===generation.current){if(v.organizationId!==org)throw new Error('Resposta fora da organização ativa.');setState(v);}}).catch(e=>{if(n===generation.current)setError(e.message);});return()=>{generation.current=n+1;};},[org]);
 useEffect(()=>{if(editing!==undefined)modal.current?.showModal();},[editing]);
 useEffect(()=>{if(history)audit.current?.showModal();},[history]);
 useEffect(()=>{let stop=false;if(customer)apiRequest<Option[]>('/api/v1/consumer-units?customerId='+encodeURIComponent(customer)).then(v=>{if(!stop)setUnits(v.filter(u=>u.customer_id===customer));}).catch(e=>{if(!stop)setError(e.message);});return()=>{stop=true;};},[customer]);
 async function load(n:number){const v=await apiRequest<Workspace>('/api/v1/ccee-registrations');if(n===generation.current&&v.organizationId===org)setState(v);}
 async function open(row:Row|null){const n=generation.current;setError('');try{const c=await apiRequest<Option[]>('/api/v1/customers');let a:Option[]=[];if(hasPermission('cb949e2a-e01d-4cf0-8c69-6ca74fe4d627'))a=(await apiRequest<{rows:Option[]}>('/api/v1/operations/agenda')).rows;if(n!==generation.current)return;setCustomers(c);setUnits([]);setAgenda(a);setCustomer(row?.customer_id??'');setUnit(row?.consumer_unit_id??'');setAgendaId(row?.agenda_id??'');setEditing(row);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Não foi possível consultar os vínculos.');}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),n=generation.current;setBusy(true);setError('');try{const selected=agenda.find(a=>a.id===agendaId);const deadline=selected?(selected.due_at||selected.ends_at||selected.starts_at):new Date(String(f.get('deadline'))).toISOString();await apiRequest('/api/v1/ccee-registrations',{method:'POST',body:{id:editing?.id??crypto.randomUUID(),requestId:crypto.randomUUID(),revision:editing?.revision??0,reason:String(f.get('reason')),customerId:customer,unitId:unit,...(agendaId?{agendaId}:{}),month:String(f.get('month')),operation:String(f.get('operation')),title:String(f.get('title')),notes:String(f.get('notes')),deadline,evidenceReference:String(f.get('evidenceReference'))}});if(n!==generation.current)return;setEditing(undefined);modal.current?.close();setMessage('Rascunho registrado. Nenhuma informação foi enviada à CCEE.');await load(n);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{if(n===generation.current)setBusy(false);}}
 async function transition(row:Row,status:string){const reason=window.prompt('Informe o motivo da alteração (mínimo 3 caracteres):');if(!reason)return;const n=generation.current;setBusy(true);setError('');try{await apiRequest('/api/v1/ccee-registrations/'+row.id+'/transition',{method:'POST',body:{requestId:crypto.randomUUID(),revision:row.revision,status,reason}});if(n===generation.current){setMessage('Revisão interna atualizada. Nenhum envio à CCEE foi realizado.');await load(n);}}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Falha na revisão.');}finally{if(n===generation.current)setBusy(false);}}
 async function inspect(row:Row){const n=generation.current;try{const h=await apiRequest<NonNullable<typeof history>>('/api/v1/ccee-registrations/'+row.id+'/history');if(n===generation.current)setHistory(h);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Falha na auditoria.');}}
 const selectedAgenda=agenda.find(a=>a.id===agendaId);const rows=state?.rows.filter(r=>!month||r.month.startsWith(month))??[];
 return <section><header><h1>Registros CCEE</h1><p>Módulo avulso · preparação e revisão dos registros por competência.</p></header>{error?<Alert>{error}</Alert>:null}{message?<Alert>{message}</Alert>:null}{!state&&!error?<p>Conferindo contratação e permissões…</p>:null}{state?<><Card title="Fechamento mensal"><p>{state.disclosure}</p><p><ShieldCheck size={16}/> Contratação, permissão e representação são verificações independentes.</p><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end'}}><label>Competência <input aria-label="Filtrar competência CCEE" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{state.canManage?<Button onClick={()=>void open(null)} disabled={busy}><Plus size={16}/> Preparar registro</Button>:null}<Link href="/backoffice/operation/agenda"><CalendarDays size={16}/> Consultar agenda</Link></div></Card><div style={{display:'grid',gap:16,gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))'}}>{rows.map(row=><Card key={row.id} title={row.title}><p>{operations[row.operation]} · {row.month.slice(0,7)}</p><p>{statuses[row.status]} · revisão {row.revision}</p><p>Prazo: {date(row.deadline)} (Brasília)</p><p>Cliente: {row.customer_id} · unidade: {row.consumer_unit_id}</p><p>{row.agenda_id?'Vinculado à agenda registrada':'Prazo informado manualmente; conferir calendário oficial'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{state.canManage&&row.status==='DRAFT'?<><Button variant="secondary" onClick={()=>void open(row)} disabled={busy}><Play size={16}/> Abrir</Button><Button onClick={()=>void transition(row,'REVIEW')} disabled={busy}>Enviar à revisão</Button></>:null}{row.status==='REVIEW'&&state.canApprove?<Button onClick={()=>void transition(row,'APPROVED')} disabled={busy}>Aprovar internamente</Button>:null}{row.status==='REVIEW'&&state.canManage?<Button variant="secondary" onClick={()=>void transition(row,'DRAFT')} disabled={busy}>Devolver ao rascunho</Button>:null}<Button variant="secondary" onClick={()=>void inspect(row)} disabled={busy}><Eye size={16}/> Auditoria</Button><Button disabled title="Adaptador de transmissão ainda não homologado">Enviar à CCEE</Button></div></Card>)}</div>{!rows.length?<p>Nenhum registro nesta competência. Dados não são gerados automaticamente.</p>:null}<p style={{fontSize:12,opacity:.7}}>Fonte: Manual CCEE de serviços de contratos livres. ImportarArquivo registra/valida; ConsultarResultadoProcessamento e consultas de contratos/montantes confirmam o processamento. A revisão interna não substitui essas confirmações.</p></>:null}
 <dialog ref={modal} onCancel={()=>setEditing(undefined)} style={{maxWidth:720,width:'90%',maxHeight:'85vh',overflow:'auto'}}>{editing!==undefined?<form className={styles.form} onSubmit={save}><h2>{editing?'Editar rascunho':'Preparar registro CCEE'}</h2><p>As informações serão armazenadas na organização ativa para revisão.</p><label>Cliente <select required value={customer} onChange={e=>{setCustomer(e.target.value);setUnits([]);setUnit('');setAgendaId('');}}><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name||c.legal_name||c.id}</option>)}</select></label><label>Unidade <select required value={unit} onChange={e=>{setUnit(e.target.value);setAgendaId('');}}><option value="">Selecione</option>{units.map(u=><option key={u.id} value={u.id}>{u.name||u.unit_name||u.id}</option>)}</select></label><label>Agenda <select value={agendaId} onChange={e=>setAgendaId(e.target.value)}><option value="">Conferir e informar prazo manualmente</option>{agenda.filter(a=>a.customer_id===customer&&a.consumer_unit_id===unit&&!['DONE','CANCELLED'].includes(a.status??'')).map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>{selectedAgenda?<p>Prazo da agenda: {date(selectedAgenda.due_at||selectedAgenda.ends_at||selectedAgenda.starts_at||'')}</p>:<label>Prazo (horário local) <input name="deadline" type="datetime-local" required defaultValue={editing?new Date(Date.parse(editing.deadline)-new Date(editing.deadline).getTimezoneOffset()*60000).toISOString().slice(0,16):''}/></label>}<label>Competência <input name="month" type="month" required defaultValue={editing?.month.slice(0,7)||month}/></label><label>Operação <select name="operation" defaultValue={editing?.operation??'VALIDATE_AMOUNTS'}>{Object.entries(operations).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Título <input name="title" required minLength={3} maxLength={160} defaultValue={editing?.title}/></label><label>Referência da evidência (documento/contrato) <input name="evidenceReference" required minLength={3} maxLength={500} defaultValue={editing?.evidence_reference}/></label><label>Dados e pontos de conferência <textarea name="notes" required minLength={3} maxLength={6000} defaultValue={editing?.notes}/></label><label>Motivo <input name="reason" required minLength={3} maxLength={500}/></label><p>Não inclua senhas, certificados ou chaves. Valores informados ainda não constituem arquivo CCEE homologado.</p><Button type="submit" disabled={busy}>Salvar rascunho</Button><Button variant="secondary" type="button" disabled={busy} onClick={()=>{modal.current?.close();setEditing(undefined);}}>Fechar</Button></form>:null}</dialog>
 <dialog ref={audit} onCancel={()=>setHistory(null)} style={{maxWidth:720,width:'90%'}}><h2>Auditoria de revisões</h2>{history?.map(h=><p key={h.revision}>Revisão {h.revision} · {date(h.recorded_at)} · {h.actor_id}<br/>{h.reason}</p>)}<Button variant="secondary" onClick={()=>{audit.current?.close();setHistory(null);}}>Fechar</Button></dialog></section>;
}
export default function Page(){const {context,hasPermission}=useAuth();const allowed=context?.scope==='organization'&&(context.accessMode==='platform_operation'||(['admin_org','gestor','operacional'].includes(context.currentOrganization.role)&&hasPermission(view)));return <ProtectedRoute><BackofficeShell>{allowed?<Workspace key={JSON.stringify([context?.user.id,context?.scope==='organization'?context.currentOrganization.id:'',context?.scope==='organization'?context.currentOrganization.permissions:[]])}/>:<Alert>Selecione uma organização e um perfil autorizado para Registros CCEE.</Alert>}</BackofficeShell></ProtectedRoute>;}
