import {BadRequestException,ConflictException,ForbiddenException,Injectable,InternalServerErrorException,NotFoundException} from '@nestjs/common';
import {ArrayMaxSize,ArrayUnique,IsArray,IsString,IsUUID,Length,IsOptional} from 'class-validator';
import {TenantContext} from '../../common/interfaces/tenant-context.interface';
import {PERMISSIONS as P} from '../../common/constants/permissions';
import {validateWriteDto} from '../../common/validation/validate-write-dto';
import {SupabaseService} from '../../services/supabase.service';
import {LicensesService} from '../licenses/services/licenses.service';
import {DocumentsService} from '../documents/services/documents.service';
import {DocumentFile} from '../documents/services/document-file';
import {OperationsService,operationKind,operationPermissions} from './operations.service';
export class EvidenceVersionDto {@IsOptional() @IsUUID() previousDocumentId?:string;}
export class EvidenceMessageDto {
 @IsUUID() requestId!:string;
 @IsString() @Length(3,160) subject!:string;
 @IsString() @Length(3,6000) body!:string;
 @IsArray() @ArrayMaxSize(5) @ArrayUnique() @IsUUID(undefined,{each:true}) documentIds!:string[];
}
@Injectable()
export class ClientEvidenceService {
 constructor(private db:SupabaseService,private licenses:LicensesService,private operations:OperationsService,private documents:DocumentsService){}
 private client(){return this.db.getClient();}
 private check(error:any){if(!error)return;if(error.code==='P2031')throw new ForbiddenException('Vínculo ou permissão da troca de evidências indisponível.');if(error.code==='P2032')throw new ConflictException('O registro ou a tentativa mudou. Consulte novamente o histórico.');if(error.code==='P2033')throw new NotFoundException('Registro não compartilhado com este cliente/unidade.');throw new InternalServerErrorException('Não foi possível consultar a troca de evidências.');}
 private bounded(result:any){this.check(result.error);if(!Array.isArray(result.data)||result.data.length>200)throw new BadRequestException('Histórico extenso; nenhum conjunto parcial foi emitido.');return result.data;}
 private async allowed(t:TenantContext){if(!t.organizationId||!t.userId||(t.scope as string)==='global')throw new ForbiddenException('Selecione uma organização.');await this.licenses.requireEntitlement(t.organizationId,'free_market_management');await this.licenses.requireEntitlement(t.organizationId,'document_management');}
 private async customer(t:TenantContext){
  await this.allowed(t);if(t.accessMode||t.role!=='consulta'||!t.permissions?.includes(P.DOCUMENTS_REPORTS_VIEW))throw new ForbiddenException('Exige perfil externo de consulta vinculado a um cliente.');
  const r=await this.client().from('organization_members').select('organization_id,user_id,role_id,status,affiliation_type,exclusive_customer_id,roles(id,name,scope,organization_id,permissions)').eq('organization_id',t.organizationId).eq('user_id',t.userId).in('status',['active','ACTIVE']).maybeSingle();this.check(r.error);const m=r.data,role=m?.roles;
  if(!m||m.organization_id!==t.organizationId||m.user_id!==t.userId||String(m.status).toUpperCase()!=='ACTIVE'||m.role_id!==t.roleId||role?.id!==t.roleId||role?.name!=='consulta'||role.scope!=='organization'||role.organization_id!==t.organizationId||!role.permissions?.includes(P.DOCUMENTS_REPORTS_VIEW)||m.affiliation_type!=='external'||!m.exclusive_customer_id)throw new ForbiddenException('Vínculo externo exclusivo indisponível.');
  const c=await this.client().from('customers').select('id,status').eq('organization_id',t.organizationId).eq('id',m.exclusive_customer_id).is('deleted_at',null).maybeSingle();this.check(c.error);if(c.data?.id!==m.exclusive_customer_id||c.data?.status!=='ACTIVE')throw new ForbiddenException('Cliente indisponível.');return m.exclusive_customer_id as string;
 }
 private async record(id:string,t:TenantContext,kind?:string,write=false){
  await this.allowed(t);if(!/^[a-f0-9-]{36}$/i.test(id))throw new BadRequestException('Registro inválido.');
  if(kind){const k=operationKind(kind);if(!t.permissions.includes(P.DOCUMENTS_VIEW)||(write&&!t.permissions.includes(operationPermissions[k][1])))throw new ForbiddenException('Exige documentos e permissão da área.');const r=await this.operations.one(id,k,t);if(!r.customer_id||!r.consumer_unit_id)throw new BadRequestException('Vincule cliente e unidade antes de trocar evidências.');return r;}
  const customer=await this.customer(t);const r=await this.client().from('operation_records').select('id,kind,operation_number,requested_by_name,created_at,effective_date,customer_id,consumer_unit_id,status').eq('organization_id',t.organizationId).eq('customer_id',customer).eq('id',id).maybeSingle();this.check(r.error);if(!r.data)throw new NotFoundException('Registro indisponível.');
  const shared=await this.client().from('operation_client_messages').select('id').eq('organization_id',t.organizationId).eq('record_id',id).eq('customer_id',customer).eq('consumer_unit_id',r.data.consumer_unit_id).eq('direction','OUTBOUND').limit(1);this.check(shared.error);if(!shared.data?.length)throw new NotFoundException('Registro não compartilhado.');return r.data;
 }
 private async metadata(r:any,t:TenantContext){const [c,u]=await Promise.all([this.client().from('customers').select('id,company_name').eq('organization_id',t.organizationId).eq('id',r.customer_id).is('deleted_at',null).maybeSingle(),this.client().from('consumer_units').select('id,name,consumer_unit_number').eq('organization_id',t.organizationId).eq('customer_id',r.customer_id).eq('id',r.consumer_unit_id).maybeSingle()]);this.check(c.error);this.check(u.error);if(!c.data||!u.data)throw new NotFoundException('Cliente/unidade indisponível.');return {id:r.id,kind:r.kind,number:r.operation_number??r.id,requestedBy:r.requested_by_name??'Nome indisponível no registro anterior',openedAt:r.created_at,customer:c.data,unit:u.data,status:r.status};}
 async portalList(t:TenantContext){const customer=await this.customer(t);const messages=this.bounded(await this.client().from('operation_client_messages').select('record_id,subject,created_at,consumer_unit_id').eq('organization_id',t.organizationId).eq('customer_id',customer).eq('direction','OUTBOUND').order('created_at',{ascending:false}).limit(201));const ids=[...new Set(messages.map((m:any)=>m.record_id))];if(!ids.length)return [];const records=this.bounded(await this.client().from('operation_records').select('id,kind,operation_number,requested_by_name,created_at,effective_date,customer_id,consumer_unit_id,status').eq('organization_id',t.organizationId).eq('customer_id',customer).in('id',ids).limit(201));if(await this.customer(t)!==customer)throw new ForbiddenException('Vínculo mudou. Atualize seu acesso.');return Promise.all(records.filter((r:any)=>messages.some((m:any)=>m.record_id===r.id&&m.consumer_unit_id===r.consumer_unit_id)).map(async(r:any)=>({...await this.metadata(r,t),subject:messages.find((m:any)=>m.record_id===r.id&&m.consumer_unit_id===r.consumer_unit_id).subject})));}
 async thread(id:string,t:TenantContext,kind?:string){const r=await this.record(id,t,kind);const messages=this.bounded(await this.client().from('operation_client_messages').select('id,subject,body,direction,document_ids,actor_name,created_at').eq('organization_id',t.organizationId).eq('record_id',id).eq('customer_id',r.customer_id).eq('consumer_unit_id',r.consumer_unit_id).order('created_at').order('id').limit(201));const ids=[...new Set<string>(messages.flatMap((m:any)=>m.document_ids))];const documents=ids.length?this.bounded(await this.client().from('documents').select('id,original_filename,mime_type,file_size_bytes,document_type').eq('organization_id',t.organizationId).eq('customer_id',r.customer_id).eq('consumer_unit_id',r.consumer_unit_id).eq('file_verified',true).in('id',ids).limit(201)):[];const reads=kind&&messages.length?this.bounded(await this.client().from('operation_client_reads').select('message_id,opened_at').eq('organization_id',t.organizationId).in('message_id',messages.map((m:any)=>m.id)).order('opened_at').limit(201)):[];await this.record(id,t,kind);return {record:await this.metadata(r,t),messages:messages.map((m:any)=>({...m,openedAt:reads.find((v:any)=>v.message_id===m.id)?.opened_at??null})),documents,canReply:!['DONE','CANCELLED','ARCHIVED'].includes(r.status)&&(!kind||t.permissions.includes(operationPermissions[operationKind(kind)][1])),disclosure:'Abertura registra a consulta da mensagem no portal; não comprova leitura do arquivo, ciência jurídica, validação ou aprovação financeira.'};}
 async append(id:string,input:EvidenceMessageDto,t:TenantContext,kind?:string){const d=await validateWriteDto(EvidenceMessageDto,input);await this.record(id,t,kind,true);const result=await this.client().rpc('append_operation_client_message',{p_org:t.organizationId,p_actor:t.userId,p_record:id,p_request:d.requestId,p_direction:kind?'OUTBOUND':'INBOUND',p_subject:d.subject,p_body:d.body,p_documents:d.documentIds});this.check(result.error);return {id:result.data?.id};}
 async opened(id:string,message:string,t:TenantContext){const r=await this.record(id,t);const m=await this.client().from('operation_client_messages').select('id').eq('organization_id',t.organizationId).eq('record_id',id).eq('customer_id',r.customer_id).eq('consumer_unit_id',r.consumer_unit_id).eq('direction','OUTBOUND').eq('id',message).maybeSingle();this.check(m.error);if(!m.data)throw new NotFoundException('Mensagem indisponível.');const result=await this.client().rpc('open_operation_client_message',{p_org:t.organizationId,p_actor:t.userId,p_message:message});this.check(result.error);return {opened:true};}
 async upload(id:string,file:DocumentFile,t:TenantContext,kind?:string,input:EvidenceVersionDto={}){const r=await this.record(id,t,kind,true);if(kind&&!t.permissions.includes(P.DOCUMENTS_UPLOAD))throw new ForbiddenException('Exige permissão de envio de documentos.');if(['DONE','CANCELLED','ARCHIVED'].includes(r.status))throw new ConflictException('Troca encerrada.');const version=input&&typeof input==='object'&&!Array.isArray(input)&&!Object.keys(input).length?{}:await validateWriteDto(EvidenceVersionDto,input);let reference=String(r.effective_date??r.created_at).slice(0,7)+'-01';let previousDocumentId:string|undefined;let documentType='OTHER';
 if(version.previousDocumentId){const thread=await this.thread(id,t,kind);if(!thread.documents.some((d:any)=>d.id===version.previousDocumentId))throw new NotFoundException('O original não foi compartilhado neste registro.');const prior=await this.documents.findOne(version.previousDocumentId,t.organizationId);if(prior.customer_id!==r.customer_id||prior.consumer_unit_id!==r.consumer_unit_id||!['OTHER','CONTRACT_ENERGY','CONTRACT_MANAGEMENT','COMPLIANCE_REPORT'].includes(prior.document_type)||!prior.file_verified)throw new BadRequestException('Retorno versionado exige um modelo/documento diverso da mesma unidade. Faturas OCR e contratos seguem revisão do backoffice.');reference=String(prior.reference_month).slice(0,7)+'-01';previousDocumentId=prior.id;documentType=prior.document_type;}
 const result=await this.documents.upload({customerId:r.customer_id,consumerUnitId:r.consumer_unit_id,documentType,referenceMonth:reference,description:'Evidência da operação '+String(r.operation_number??r.id),...(previousDocumentId?{previousDocumentId}:{})},file,t.organizationId,t.userId);await this.record(id,t,kind,true);return {id:result.id,name:result.original_filename};}
 async download(id:string,document:string,t:TenantContext,kind?:string){const thread=await this.thread(id,t,kind);if(!thread.documents.some((d:any)=>d.id===document))throw new NotFoundException('Arquivo não compartilhado neste registro.');return this.documents.download(document,t.organizationId);}
}

