import {OperationsService,operationKind,operationTransition,operationPermissions} from './operations.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
function fixture(){const q:any={};for(const k of ['select','eq','is','in','not','order','limit','gte','lte','lt','maybeSingle'])q[k]=jest.fn(()=>q);q.then=(r:any)=>Promise.resolve({data:[],error:null}).then(r);const client:any={from:jest.fn(()=>q),rpc:jest.fn(async()=>({data:{id:'saved'},error:null}))};const db:any={getClient:()=>client};const license:any={requireEntitlement:jest.fn(async()=>{})};const t:any={userId:'actor',organizationId:'a',scope:'organization',role:'operacional',permissions:Object.values(operationPermissions).flat()};const s=new OperationsService(db,license);return {s,q,db,license,t};}
describe('Operation security and workflow',()=>{
 it('queries source alerts only with their individual permissions and tenant',async()=>{const f=fixture();await f.s.notifications(f.t);expect(f.db.getClient().from.mock.calls.map((v:any)=>v[0])).toEqual(['operation_records','operation_notification_reads']);f.t.permissions.push(P.DOCUMENTS_VIEW,P.ORGANIZATION_CONTRACTS_VIEW,P.ORGANIZATION_LICENSES_VIEW);f.db.getClient().from.mockClear();await f.s.notifications(f.t);expect(f.db.getClient().from.mock.calls.map((v:any)=>v[0])).toEqual(['operation_records','operation_notification_reads','document_ocr_jobs','energy_contracts','management_contracts','licenses']);expect(f.license.requireEntitlement).toHaveBeenCalledWith('a','document_management');expect(f.q.eq).toHaveBeenCalledWith('organization_id','a');});
 it('cannot mark an invented or obsolete source notification as read',async()=>{const f=fixture();await expect(f.s.markRead({key:'energy:missing:'+ 'a'.repeat(64)},f.t)).rejects.toThrow('escopo');expect(f.db.getClient().rpc).not.toHaveBeenCalled();});
 it.each(['agenda','requests','events'])('scopes %s records to the active organization',async k=>{const f=fixture();await f.s.list(k,f.t);expect(f.q.eq).toHaveBeenCalledWith('organization_id','a');expect(f.q.eq).toHaveBeenCalledWith('kind',k);expect(f.license.requireEntitlement).toHaveBeenCalledWith('a','free_market_management');});
 it.each([{scope:'global'},{organizationId:''},{userId:''},{role:'consulta'},{permissions:[]}])('denies absent or client/global access %p',async patch=>{const f=fixture();await expect(f.s.list('agenda',{...f.t,...patch})).rejects.toThrow();expect(f.q.select).not.toHaveBeenCalled();});
 it('fails closed on licence before reading',async()=>{const f=fixture();f.license.requireEntitlement.mockRejectedValue(new Error('Expired'));await expect(f.s.list('agenda',f.t)).rejects.toThrow('Expired');expect(f.q.select).not.toHaveBeenCalled();});
 it('rejects unknown kind including prototype keys',()=>{for(const k of ['pld','__proto__','constructor'])expect(()=>operationKind(k)).toThrow();});
 it('rejects injected scope filters and inverted dates',async()=>{const f=fixture();await expect(f.s.list('agenda',f.t,{organizationId:'b'} as any)).rejects.toThrow();await expect(f.s.list('agenda',f.t,{from:'2026-10-10',to:'2026-10-01'})).rejects.toThrow();});
 it('keeps manager publication exclusive even with operator manage permission',async()=>{const f=fixture();await expect(f.s.transition('record','events',{requestId:'11111111-1111-4111-a111-111111111111',revision:1,reason:'Conferido',status:'PUBLISHED'},f.t)).rejects.toThrow('Gestor');});
 it('requires request client, deadline and type before writing',async()=>{const f=fixture();await expect(f.s.save('requests',null,{requestId:'11111111-1111-4111-a111-111111111111',revision:0,reason:'Conferido',title:'Pedido',description:'Descrição',priority:'NORMAL',responsibleId:'actor'},f.t)).rejects.toThrow('prazo');});
 it('requires manage permission independently from view',async()=>{const f=fixture();f.t.permissions=[P.OPERACAO_CALENDAR_VIEW];await expect(f.s.save('agenda',null,{} as any,f.t)).rejects.toThrow();});
 it('does not allow state shortcuts or edits of closed events',()=>{expect(operationTransition('events','DRAFT','PUBLISHED')).toBe(false);expect(operationTransition('events','REVIEW','PUBLISHED')).toBe(true);expect(operationTransition('events','PUBLISHED','DRAFT')).toBe(false);expect(operationTransition('agenda','DONE','OPEN')).toBe(false);});
 it('notification queries use only permitted areas and personal organization-scoped receipts',async()=>{const f=fixture();f.t.permissions=[P.OPERACAO_REQUESTS_VIEW];await f.s.notifications(f.t);expect(f.q.in).toHaveBeenCalledWith('kind',['requests']);expect(f.q.eq).toHaveBeenCalledWith('organization_id','a');expect(f.q.eq).toHaveBeenCalledWith('user_id','actor');});
});
