import {BotReportsService,reportPeriod} from './bot-reports.service';
import {PERMISSIONS as P} from '../../common/constants/permissions';
const t:any={organizationId:'org',userId:'actor',roleId:'role',role:'consulta',scope:'organization',permissions:[P.INTELLIGENCE_AI_USE,P.DOCUMENTS_REPORTS_VIEW]};
function fixture(){const rpc=jest.fn(async()=>({data:{customerId:'c1',units:[],groups:[]},error:null}));const license={available:jest.fn(async()=>true)},ai={interpret:jest.fn()},reports={one:jest.fn()},financial={reports:jest.fn()},rag={retrieve:jest.fn(),retrieveClient:jest.fn()};const service=new BotReportsService({getClient:()=>({rpc})} as any,reports as any,financial as any,license as any,rag as any,ai as any,{list:jest.fn()} as any,{get:()=>false} as any);return {rpc,license,ai,reports,financial,rag,service};}
describe('Isolated report and client authorization',()=>{
 it.each([{...t,permissions:[]},{...t,accessMode:'platform_operation'},{...t,role:'gestor'},{...t,scope:'global'}])('rejects invalid portal context before data or AI calls',async ctx=>{const f=fixture();await expect(f.service.clientUnits('2026-01','2026-02',ctx)).rejects.toThrow();expect(f.rpc).not.toHaveBeenCalled();expect(f.ai.interpret).not.toHaveBeenCalled();});
 it('derives customer from live membership, never from request',async()=>{const f=fixture();await f.service.clientUnits('2026-01','2026-02',t);expect(f.rpc).toHaveBeenCalledWith('bot_energy_client_reports',{p_org:'org',p_actor:'actor',p_role:'role',p_from:'2026-01',p_to:'2026-02',p_unit:null});await expect(f.service.ask({question:'Resultados?',unitId:'123',from:'2026-01',to:'2026-02',kind:'FINANCIAL',customerId:'other'},t,'client')).rejects.toThrow();expect(f.ai.interpret).not.toHaveBeenCalled();});
 it('rechecks revoked live membership and licence before subsequent queries',async()=>{const f=fixture();await f.service.clientUnits('2026-01','2026-02',t);f.rpc.mockResolvedValueOnce({data:null,error:{code:'42501'}} as any);await expect(f.service.clientUnits('2026-01','2026-02',t)).rejects.toThrow();f.license.available.mockResolvedValueOnce(false);await expect(f.service.clientUnits('2026-01','2026-02',t)).rejects.toThrow('licença');expect(f.ai.interpret).not.toHaveBeenCalled();});
 it.each([['2026-13','2026-13'],['2026-03','2026-01'],['2025-01','2026-01'],['anything','2026-01']])('rejects invalid or overlong periods %s %s',(from,to)=>expect(()=>reportPeriod(from,to)).toThrow());
 it('does not route a consulta user to backoffice or use draft norms',async()=>{const f=fixture();await expect(f.service.ask({question:'Qual regra?',reportId:'123',kind:'OPERATIONAL'},t,'backoffice')).rejects.toThrow();expect(f.reports.one).not.toHaveBeenCalled();expect(f.ai.interpret).not.toHaveBeenCalled();});
});

describe('Published backoffice report integration',()=>{
 const id='ea1f0660-a111-4111-8111-111111111111';
 const backoffice={...t,role:'operacional',permissions:[...t.permissions,P.ORGANIZATION_CONTRACTS_VIEW]};
 function reportFixture(){const f=fixture();const publication={id:'g1',payloadHash:'hash1',version:1};f.reports.one.mockResolvedValue({body:{header:{customerId:'c1',unitId:'u1',unitName:'Minha unidade'},period:{from:'2026-01',to:'2026-01'},publications:[publication],annualProjection:null}});f.financial.reports.mockResolvedValue({primary:{period:{from:'2026-01',to:'2026-01'},coverage:{publishedMonths:1,requestedMonths:1,missingMonths:[]},publications:[publication],months:[],totals:null,invoices:[{unitId:'u1',month:'2026-01',groupId:'g1',version:1,payloadHash:'hash1',measurements:{measurements:{consumptionTotal:'50',demandPeak:'10'}}}],unitRows:[]}});f.ai.interpret.mockResolvedValue({state:'READY',answer:'Consumo publicado'});return f;}
 it('links the three report views to scoped current publication evidence',async()=>{for(const kind of ['OPERATIONAL','FINANCIAL','EXECUTIVE']){const f=reportFixture();const r=await f.service.ask({question:'Qual meu consumo?',reportId:id,kind},backoffice,'backoffice');expect(r.state).toBe('READY');expect(f.financial.reports).toHaveBeenCalledWith({from:'2026-01',to:'2026-01',customerId:'c1',unitId:'u1'},backoffice);expect(f.ai.interpret.mock.calls[0][2].some((e:any)=>e.id==='measurement-2026-01-consumptionTotal')).toBe(true);expect(f.rag.retrieve).not.toHaveBeenCalled();}}
 );
 it('abstains on unreleased norms and never sends draft normative content to AI',async()=>{const f=reportFixture();f.rag.retrieve.mockResolvedValue({state:'NO_EVIDENCE',evidence:[],sources:[]});const r=await f.service.ask({question:'Como corrigir o fator de potência?',reportId:id,kind:'OPERATIONAL'},backoffice,'backoffice');expect(r.state).toBe('NO_EVIDENCE');expect(f.ai.interpret).not.toHaveBeenCalled();});
 it('does not replace a historical report with newer publications or answer for another period',async()=>{let f=reportFixture();f.financial.reports.mockResolvedValue({primary:{publications:[{id:'g2',payloadHash:'hash2',version:2}]}});await expect(f.service.ask({question:'Consumo?',reportId:id,kind:'OPERATIONAL'},backoffice,'backoffice')).rejects.toThrow('recente');expect(f.ai.interpret).not.toHaveBeenCalled();f=reportFixture();expect((await f.service.ask({question:'Qual maior consumo no ano 2026?',reportId:id,kind:'OPERATIONAL'},backoffice,'backoffice')).state).toBe('CONTEXT_REQUIRED');expect(f.ai.interpret).not.toHaveBeenCalled();});
});
