import {clientReportAnalytics} from './client-report-sources';
import {reviewDigest} from '../contracts/services/review-snapshots.service';
const period={from:'2026-01',to:'2026-02'};
function fixture(){const unit={id:'u1',name:'Minha',acr:'100.00',aclBeforeFees:'60.00',totalFees:'10.00',aclAfterFees:'70.00',savingsAfterFees:'30.00'};const payload={formatVersion:'financial-settlement-1.0',sources:{organizationId:'org',customerId:'c1',month:'2026-01'},financial:{status:'AVAILABLE',acr:'100.00',aclBeforeFees:'60.00',totalFees:'10.00',aclAfterFees:'70.00',savingsBeforeFees:'40.00',savingsAfterFees:'30.00',units:[unit]},preparations:{u1:{measurements:{validatedVersion:{measurements:{consumptionTotal:'50'}}}}},reservations:[]};const row={organization_id:'org',customer_id:'c1',consumer_unit_id:'u1',financial_group_id:'g1',month:'2026-01-01',version_number:1,status:'PUBLISHED',validation_status:'VALIDATED',approved_at:'approved',published_at:'published',published_by:'actor',financial_format:'financial-settlement-1.0',financial_hash:reviewDigest(payload)};return {customerId:'c1',units:[{id:'u1',name:'Minha'}],groups:[{payload,consistent:true,rows:[row]}]};}
describe('Portal published payload integrity and unit scope',()=>{
 it('uses only published unit amounts with missing months preserved',()=>{const data=fixture(),before=JSON.stringify(data),a=clientReportAnalytics(data,'org',period,'u1');expect(a.totals).toMatchObject({aclAfterFees:'70.00',savingsAfterFees:'30.00'});expect(a.coverage.missingMonths).toEqual(['2026-02']);expect(JSON.stringify(data)).toBe(before);});
 it.each([{status:'DRAFT'},{validation_status:'DRAFT'},{published_at:null},{approved_at:null},{published_by:null},{organization_id:'other'},{customer_id:'other'},{financial_hash:'forged'},{consumer_unit_id:'other'}])('rejects unpublished or out-of-scope source %p',change=>{const data=fixture();Object.assign(data.groups[0].rows[0],change);expect(()=>clientReportAnalytics(data,'org',period,'u1')).toThrow();});
 it('rejects tampered bodies, mixed captures, duplicate months and foreign unit selection',()=>{let data=fixture();data.groups[0].payload.preparations.u1.measurements.validatedVersion.measurements.consumptionTotal='999';expect(()=>clientReportAnalytics(data,'org',period,'u1')).toThrow();data=fixture();data.groups[0].consistent=false;expect(()=>clientReportAnalytics(data,'org',period,'u1')).toThrow();data=fixture();data.groups.push(data.groups[0]);expect(()=>clientReportAnalytics(data,'org',period,'u1')).toThrow();expect(()=>clientReportAnalytics(fixture(),'org',period,'other')).toThrow();});
});
