import {reportEvidence} from './report-evidence';
const scope={unitId:'u1',unitName:'Minha unidade',audience:'client'};
const analytics=()=>({period:{from:'2026-01',to:'2026-03'},coverage:{publishedMonths:2,requestedMonths:3,missingMonths:['2026-02']},totals:{aclAfterFees:'30.00'},months:[],unitRows:[{unitId:'u1',month:'2026-01',amounts:{aclAfterFees:'10.00'}},{unitId:'u1',month:'2026-03',amounts:{aclAfterFees:'20.00'}}],invoices:[{unitId:'u1',month:'2026-01',groupId:'g1',version:1,payloadHash:'h1',measurements:{measurements:{consumptionTotal:'3',demandPeak:'10'}}},{unitId:'u1',month:'2026-03',groupId:'g3',version:2,payloadHash:'h3',measurements:{measurements:{consumptionTotal:'7',demandPeak:'20'}}}]});
describe('Published report analytical boundary',()=>{
 it('computes exact means, maxima and weighted specific cost in backend only',()=>{const a=analytics(),before=JSON.stringify(a),e=reportEvidence(a,scope);expect(JSON.parse(e.find(x=>x.id==='aggregate-consumptionTotal')!.value)).toMatchObject({sum:'10.000000',average:'5.000000',maximum:'7',maximumMonth:'2026-03',observedMonths:2,requestedMonths:3});expect(e.find(x=>x.id==='specific-period')!.value).toBe('3.000000');expect(e.find(x=>x.id==='specific-2026-01')!.value).toBe('3.333333');expect(JSON.stringify(a)).toBe(before);});
 it('does not sum demand, invent missing months, zero reactive energy or payment',()=>{const e=reportEvidence(analytics(),scope);expect(JSON.parse(e.find(x=>x.id==='aggregate-demandPeak')!.value)).toMatchObject({sum:null,average:'15.000000'});expect(e.some(x=>x.id.includes('reactive'))).toBe(false);expect(e.find(x=>x.id==='limits')!.value).toContain('não comprova pagamento');});
 it('does not leak another unit or source notes and rejects duplicate months',()=>{const a=analytics();a.invoices.push({...a.invoices[0],unitId:'u2',measurements:{measurements:{consumptionTotal:'999',demandPeak:'999'}}});(a.invoices[0] as any).reservations=['PRIVATE NOTE'];const e=JSON.stringify(reportEvidence(a,scope));expect(e).not.toContain('999');expect(e).not.toContain('PRIVATE NOTE');a.invoices.push(a.invoices[0]);expect(()=>reportEvidence(a,scope)).toThrow('AMBIGUOUS');});
 it('does not publish a specific period cost against incomplete measurement coverage',()=>{const a=analytics();delete (a.invoices[0].measurements.measurements as any).consumptionTotal;expect(reportEvidence(a,scope).some(x=>x.id==='specific-period')).toBe(false);});
});
